### ISSUE TITLE
mktemp needs 6 or more X's

### ISSUE THREAD

**Issue by sthen** [stedolan/jq#1000]
mktemp(1) isn't posix specified, but it's reasonable to use mktemp(3) to implement it which requires 6 trailing X's in the format, so the following is needed for tests to work on OS which enforce this:

```
--- tests/setup.orig	Fri Oct 23 10:45:40 2015
+++ tests/setup	Fri Oct 23 10:45:51 2015
@@ -29,7 +29,7 @@ clean () {
     fi
 }
 trap clean EXIT
-d=`mktemp -d -t jqXXXXX || true`
+d=`mktemp -d -t jqXXXXXX || true`
 if [ -z "$d" ]; then
     echo "Your OS does not support mktemp(1) -d" 1>&2
     exit 1
```

**Comment by dtolnay** [comment]
Thanks! I have applied the fix you provided.
