### ISSUE TITLE
Requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by smartleoyu** [stedolan/jq#1015]
Hi,

I did "brew install jq" but then I got this:

==> Downloading http://stedolan.github.io/jq/download/source/jq-1.4.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "jq"
Download failed: http://stedolan.github.io/jq/download/source/jq-1.4.tar.gz

Is the file moved to another place or?

Thank you.

**Comment by danielvarga** [comment]
+1, same here.

**Comment by dtolnay** [comment]
@smartleoyu @danielvarga this was fixed a few months ago in homebrew. See https://github.com/Homebrew/homebrew/pull/42773. You need to run `brew update` to pick up the changes.
