### ISSUE TITLE
Merge objects into one

### ISSUE THREAD

**Issue by Nic2012** [stedolan/jq#1016]
As a input i have
```
totalcapacity=15642720 KB
free=15149216 KB
freeimages=587
```

with jq1.4 and "split("\n")|.[]|split("=")|{(.[0]|tostring):.[1]}" it returns
```
{
  "totalcapacity": "15642720 KB"
}
{
  "free": "15149216 KB"
}
{
  "freeimages": "587"
}
```
What is missing to get all keys/value pairs in 1 object like
```
{
  "totalcapacity": "15642720 KB",
  "free": "15149216 KB",
  "freeimages": "587",
}
```
Regards,
Nic

**Comment by Nic2012** [comment]
I can answer myself...
Command has to be changed from
`split("\n")|.[]|split("=")|{(.[0]|tostring):.[1]}` into
`[split("\n")|.[]|split("=")|{(.[0]|tostring):.[1]}]|reduce .[] as $item ({}; . + $item)`

If I am understand the logic behind jq (?) then the afterwards `reduce` interates through array and aggregates each item together. Array structure is done by surrounded `[]`.

@jq-developers
Well, the online jq player helps to investigate, but the attached examples there and in manual are mostly to simple to fully understand jq behaviour. To steep the learning curve it would a great help to have more tutorials and complex examples especially on string inputs etc.

**Comment by pkoppstein** [comment]
A simpler approach is to use the -s option with ```add```.  Assume the file assign.jq contains:

    [ split("\n")[] | select(length > 0) | split("=") | {(.[0]|tostring):.[1]} ] | add

Then:

    $ jq -s -R -f assign.jq assign.txt

    {
      "totalcapacity": "15642720 KB",
      "free": "15149216 KB",
      "freeimages": "587"
    }

Regarding your other points -- the manual is comprehensive, but there are other resources, such as:
* https://github.com/stedolan/jq/wiki/FAQ
* https://github.com/stedolan/jq/wiki/Cookbook
* http://rosettacode.org/wiki/Category:Jq

**Comment by Nic2012** [comment]
Thanks that works.
But in case I have repetition like
...
totalcapacity=15642720 KB
free=15149216 KB
freeimages=587
totalcapacity=2000 KB
free=200 KB
freeimages=12
...
jq returns always the last items
{
  "totalcapacity": "2000 KB",
  "free": "200 KB",
  "freeimages": "12"
}
How can I prevent this so that result is
{
  "totalcapacity": "15642720 KB",
  "free": "15149216 KB",
  "freeimages": "587",
  "totalcapacity": "2000 KB",
  "free": "200 KB",
  "freeimages": "12"
}

**Comment by nicowilliams** [comment]
> Thanks that works.
> But in case I have repetition like
> ...
> totalcapacity=15642720 KB
> free=15149216 KB
> freeimages=587
> totalcapacity=2000 KB
> free=200 KB
> freeimages=12
> ...
> jq returns always the last items
> {
> "totalcapacity": "2000 KB",
> "free": "200 KB",
> "freeimages": "12"
> }
> How can I prevent this so that result is
> {
> "totalcapacity": "15642720 KB",
> "free": "15149216 KB",
> "freeimages": "587",
> "totalcapacity": "2000 KB",
> "free": "200 KB",
> "freeimages": "12"
> }
>

For that you'd have use the streaming parser option in jq-1.5 (see
the --stream command-line option) and resemble the object yourself (there's
a built-in for that, but none that does what you want, so you'll have to
tweak the existing one).

**Comment by Nic2012** [comment]
I still using jq 1.4, so there is no solution possible ?

**Comment by pkoppstein** [comment]
@Nic2012 -- It seems a bit pointless, but here's how to do what you requested using jq (including jq 1.4):

go.jq
```
[ split("\n")[]
| select(length > 0)
| split("=")
| "\"\(.[0]|tostring)\":" + "\"\(.[1])\"\n" ]
| "{\n" + add + "}"
```
Invocation:
```
jq -s -r -R -f go.jq assign.txt
```

**Comment by nicowilliams** [comment]
>
> I still using jq 1.4, so there is no solution possible ?
>

No, sorry.  We'll, you could jq-code your JSON parser, but that's be a lot
of work...  JSON does allow duplicate object keys, but parsers are given
wide latitude as to how they deal with that, and most will take the last
key/value pair for any key with duplicates.  Duplicate keys in JSON objects
are... not advisable for that reason.

**Comment by Nic2012** [comment]
[ split("\n")[]
| select(length > 0)
| split("=")
| "\"\(.[0]|tostring)\":" + "\"\(.[1])\"\n" ]
| "{\n" + add + "}"

Returns
{
"totalcapacity":"15642720 KB"
"free":"15149216 KB"
"freeimages":"587"
"totalcapacity":"2000 KB"
"free":"200 KB"
"freeimages":"12"
}
without the colons at the end of each object.

**Comment by Nic2012** [comment]
Well I think my example was not a good one. According to my previous issue https://github.com/stedolan/jq/issues/946 I have sometimes in gphoto2  the case that I have simultaneously 2 returning results, named with same keys, but described different context:
```
Label: Aperture
Type: RADIO
Current: 5.6
Label: ISO
Type: RADIO
Current: 200
```

If I reuse solution from issue https://github.com/stedolan/jq/issues/946 then jq result looks like
```
{
  "Label": [
    "Aperture",
    "ISO"
  ],
  "Type": [
    "RADIO",
    "RADIO"
  ],
  "Current": [
    "5.6",
    "200"
  ]
}
```
But I would like to "clustering" it by the key "label" instead:
```
{
    "Aperture": [
        {
            "Label": "Aperture",
            "Type": "RADIO",
            "Current": "5.6"
        }
    ],
    "ISO": [
        {
            "Label": "ISO",
            "Type": "RADIO",
            "Current": "200"
        }
    ]
}
```

**Comment by pkoppstein** [comment]
Nic2012 - I've revised go.jq to use join/1 so that the output includes commas.

You might like to ask general usage questions at https://stackoverflow.com/questions/tagged/jq

**Comment by Nic2012** [comment]
Thanks, but as y mentioned earlier the result makes no sense and my example wasnt the right one.

**Comment by Nic2012** [comment]
Yeah, I've got it!
Input as
```
Label: Aperture
Type: RADIO
Current: 5.6
Choice: 0 2.8
Choice: 1 5.6
Label: ISO
Type: RADIO
Current: 200
Choice: 0 200
Choice: 1 250
```
```
def low: explode | map( if 65 <= . and . <= 90 then . + 32  else . end) | implode;
def red: reduce (.[] | split(": ")) as $item ({};
                 ($item[0]|low) as $key |
				 $item[1] as $value |
				 .[$key] =
				     if has($key)|not then
						$value
					 elif .[$key]|type == "array" then
						.[$key] + [$value]
					 else [.[$key], $value] end);
[split("Label: ")
| .[1:]
| .[0:][]
| split("\n")
| {(.[0]|low):[(.[1:][])|select(length>0)]|red} ]
| reduce .[] as $item ({}; . + $item)
```
Retuns what I am looking for
```
{
  "aperture": {
    "type": "RADIO",
    "current": "5.6",
    "choice": [
      "0 2.8",
      "1 5.6"
    ]
  },
  "iso": {
    "type": "RADIO",
    "current": "200",
    "choice": [
      "0 200",
      "1 250"
    ]
  }
}
```
That was fun, thanks a lot for the support :)
