### ISSUE TITLE
Alternative operator does not work for entire array of results

### ISSUE THREAD

**Issue by nickconnicdev** [stedolan/jq#1020]
Hi,

I am trying to parse some JSON output that comes in from JIRA using curl.

I have some JSON data that when parsed does not return anything. Not null, not empty, just nothing.

If I run this: 
cat data.tmp | ./jq -r '.issues[1].fields.fixVersions[].name // "null"'
I get null for the item at index 1, which is correct; there is no data there.

However when I switch back to my script and parse the entire array of issues using:
cat data.tmp | ./jq -r '.issues[].fields.fixVersions[].name // "null"'
it does not return "null" for the items that have no data, and I am losing some columns when I awk to a comma separated table format.

I am using jq 1.3
I have tried the -e operator with jq 1.4 but got the same result.

Thank you for your support.

**Comment by dtolnay** [comment]
It is an order of operations issue. The `//` is happening to the entire previous expression, not just `.name`. Try this instead:

    cat data.tmp | jq -r '.issues[].fields.fixVersions[] | (.name // "null")'
