### ISSUE TITLE
question: how to concactenate values from list of dicts?

### ISSUE THREAD

**Issue by sc0rp10** [stedolan/jq#1023]
I have json like this:
```
{
    "items": [
        {
            "name": "foo",
            "time": "123453124",
            "ignored": "some_value"
        },
        {
            "name": "bar",
            "time": "123453125",
            "ignored": "some_value"
        },
        {
            "name": "baz",
            "time": "123453126",
            "ignored": "some_value"
        }
    ]
}
```
I need output like map (name => time)
```
foo	123453124
bar	123453125
baz	123453126
```

I tried to concatenate values with `'.items[].created_time + .items[].link''`, but i got n^2 elements (each time * each name fields) and without any separator. Maybe is there another method for this?

**Comment by dtolnay** [comment]
Your sample input is not valid json, but once you fix it, try something like this:

```
$ jq <test.json '.items | map({key: .name, value: .time}) | from_entries'
{
  "foo": 123453124,
  "bar": 123453125,
  "baz": 123453126
}
```

**Comment by sc0rp10** [comment]
Sorry, i've fixed json and created playground: https://jqplay.org/jq?q=.toto%20%7C%20map_values(select(.x==%22t%22))&j=%7B%22toto%22:%20%7B%22a%22:%20%7B%22x%22:%20%22t%22%7D,%20%22b%22:%20%7B%22x%22:%20%22t%22%7D,%20%22c%22:%20%7B%22x%22:%20%22r%22%7D%7D%7D

**Comment by sc0rp10** [comment]
@dtolnay thanks for reply! I got another dict, but I need to flat text list is it possible with jq?

**Comment by dtolnay** [comment]
Sorry I missed the fact that you needed flat text instead of the map.

```
$ jq -r <test.json '.items[] | "\(.name) \(.time)"'
foo 123453124
bar 123453125
baz 123453126
```

`-r` means raw output, meaning don't put quotes around output strings.

**Comment by sc0rp10** [comment]
oh, what simple! Thanks for reply, @dtolnay!
