### ISSUE TITLE
Redirecting or piping output has different behaviour

### ISSUE THREAD

**Issue by scraperdragon** [stedolan/jq#1028]
This caught me by surprise -- omitting the (mandatory) jq filter causes the help to be printed instead, but only if the output is redirected to a file or piped: the `.` filter is implied if redirection does not occur.

```
> echo '"x"' | ./jq -r
x
> echo '"x"' | ./jq -r > foo
jq - commandline JSON processor [version 1.5]
Usage: ./jq [options] <jq filter> [file...]
```

This is particularly mystifying if jq is invoked within a shell script, since it means the shell scripts' behaviour radically changes.

The obvious workaround is to use the `.` filter, but it's not obvious you need it when it sometimes succeeds.

I don't have a strong preference for whether it should always fail or always assume `.` as a default filter.

**Comment by wtlangford** [comment]
This was actually an intended behavior. I don't remember why we only
supported it when the output `isatty()`, though.

**Comment by nicowilliams** [comment]
On Mon, Nov 30, 2015 at 08:13:37AM -0800, William Langford wrote:
> This was actually an intended behavior. I don't remember why we only
> supported it when the output `isatty()`, though.

The idea was that running jq with no arguments on a tty should yield a usage message.  That was something @stedolan wanted, and that I concur with.

We could tighten the logic and print the usage message only when `isatty(STDIN_FILENO) && isatty(STDOUT_FILENO)`.

**Comment by wtlangford** [comment]
Ah, that's right.  I do remember that.  I'm not sure that behavior is much
better, though.  It's still a special case causing a different behavior.
That said, it means that the only way to get that usage message now is to
either ask for it explicitly with -h or run jq with no arguments and no
piping.  Or invalid arguments, I suppose.  I guess that is a more logical
special case.  I'm fine with this, I think.

**Comment by dtolnay** [comment]
The current behavior is

    if (!program && isatty(STDOUT_FILENO) && !isatty(STDIN_FILENO))
        program = ".";

I like Nico's suggestion. To break down the cases:

| command | current | proposed |
| ------------- | ----------- | ----------- |
| `jq` | help | help |
| `jq > out` | help | assume "." |
| `curl | jq` | assume "." | assume "." |
| `curl | jq > out` | help | assume "." |

**Comment by nicowilliams** [comment]
@dtolnay Yes, that's the idea.  I suppose that if any arguments have been given (other than `-h`/`--help`) then assuming that a missing program is `.` would be reasonable as well.

**Comment by amosshapira** [comment]
I concur with @dtolnay's summary. I reached the current issue when I tried to use jq to colorize output from another program and have it work only if the output was the terminal.

**Comment by nicowilliams** [comment]
The relevant code in jq is this:

    #if (!defined(WIN32) && defined(HAVE_ISATTY)) || defined(HAVE__ISATTY)

    #if defined(HAVE__ISATTY) && defined(isatty)
    #undef isatty
    #define isatty _isatty
    #endif

      if (!program && isatty(STDOUT_FILENO) && !isatty(STDIN_FILENO))
        program = ".";
    #endif

The `#define` of `isatty` needs to move further up since we use `isatty()` further up.  The conditional needs to be `!program && (isatty(STDOUT_FILENO) || !isatty(STDIN_FILENO))`.

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/1285
