### ISSUE TITLE
Remove null values (and keys) from JSON

### ISSUE THREAD

**Issue by jonmathews-zz** [stedolan/jq#104]
I can't figure out how to remove null values (and corresponding keys) from the input JSON. I can get it to output only the values, but the keys are dropped. I've tried various combinations of the recurse, map, select and del functions...

For example, with this input:

```
[
  {
    "Item": "A",
    "Price": 12.23,
    "Qty": 123
  },
  {
    "Item": "B",
    "Price": null,
    "Qty": 234
  },
  {
    "Item": "C",
    "Price": 23.2,
    "Qty": null
  }
]
```

I want to generate this output:

```
[
  {
    "Item": "A",
    "Price": 12.23,
    "Qty": 123
  },
  {
    "Item": "B",
    "Qty": 234
  },
  {
    "Item": "C",
    "Price": 23.2
  }
]
```

**Comment by norcalli** [comment]
Even shorter!

    del(.[][] | nulls)

**Comment by pke** [comment]
Can this be combined to remove also entries that do not have their value `.DMC == 0`? I tried

`del(.[][] | select(. == "" or .DMC==0))`

But it gives me `invalid path expression with result true`

**Comment by nicowilliams** [comment]
@pke what version of jq are you using?  Can you give us a sample input?

**Comment by pke** [comment]
I am using the newest win32 version just downloaded.
Sample input is

```json
[
  {
     "name": "foo",
     "FIELD1": "",
     "FIELD2": "value2",
     "DMC": 1,
  },
  {
     "name": "bar",
     "FIELD1": "",
     "FIELD2": "value2",
     "DMC": 0,
  }
]
```

Expected result: 

```json
[
  {
     "name": "foo",
     "FIELD2": "value2",
     "DMC": 1,
  }
]
```

**Comment by nicowilliams** [comment]
@pke Ah, I'm not sure what the `.==""` part of your program is meant to match, but what you want is something like this: `del(.[] | select(.DMC==0))`.  Here the input to `select()` will be an object where you'd find `.DMC` and so on -- it's what you want deleted, so you'll want to have that as the input to `select()` and that as the output of the whole expression passed to `del()`.  If you have a second condition like `.name=="foo"`, add it like so: del(.[] | select(.DMC==0 or .name=="foo"))`.

**Comment by pke** [comment]
@nicowilliams The ``.==""` should remove all key, that have empty values. I modified this mentioned shortly above my post https://github.com/stedolan/jq/issues/104#issuecomment-167396874

**Comment by nicowilliams** [comment]
@pke 

Your solution is correct.

**Comment by pke** [comment]
Very well then ;) thanks

**Comment by pkoppstein** [comment]
Here's an alternative that might be slightly faster:

    map( select(.DMC != 0) | with_entries( select( .value != 0 )) )

**Comment by pke** [comment]
@pkoppstein That's what I was thinking about ;) Thanks. Possible to remove the .DMC keys in the same go also?

**Comment by pkoppstein** [comment]
@pke - How about:

map( select(.DMC != 0) | with_entries( select( .value != 0 and .key != "DMC" ) ))

**Comment by pke** [comment]
@pkoppstein perfect! Thanks and sorry for hijacking the OP thread.

**Comment by pkoppstein** [comment]
@pke - Yes, in future it would be better to ask usage qustions at stackoverflow.com with the jq tag.

**Comment by nicowilliams** [comment]
BTW, all of these solutions do some amount of allocation.  In principle we could optimize down the amount of allocation needed for the first approach (use `del/1`), but we can't really reduce the amount of allocation needed for the `map/1` approach.  So if you want the most efficient solution, then the first is it, at least in principle, and until we optimize it further, you could measure the two.

**Comment by nicowilliams** [comment]
The only reason `del/1` absolutely must allocate some memory is for the paths constructed by `path/1`, but that's OK because that array can be reused over and over.  It also allocates because of `depaths/1` wanting an array of paths, but we could add a `delpath/1` that doesn't.  Then provided `.` has only one refcount then no allocation would be needed.

But `map/1` and `with_entries/1` must allocate in all cases.

So in principle the `del/1`-using program can be more efficient, at least as to memory allocations.  It still might not be in run-time anyways, naturally, but I think it would be if we further optimize it.

**Comment by pkoppstein** [comment]
@nicowilliams - Speaking of efficiency, I believe the following tweak of the existing walk/1 will allow TCO:

```
# Apply f to composite entities recursively, and to atoms
def walk(f):
  def walk_:
  . as $in
  | if type == "object" then
      reduce keys[] as $key
        ( {}; . + { ($key):  ($in[$key] | walk_) } ) | f
  elif type == "array" then map( walk_ ) | f
  else f
  end;
  walk_;
```

**Comment by ash211** [comment]
With newer versions of jq (1.6 and later per https://github.com/stedolan/jq/issues/963) you can use this expression to remove null-valued keys recursively:

`'walk( if type == "object" then with_entries(select(.value != null)) else . end)'`

**Comment by saizai** [comment]
I've tweaked this a bit to remove all empty items, and added this to my `~/.jq`:

```
def remove_empty:
  . | walk(
    if type == "object" then
      with_entries(
        select(
          .value != null and
          .value != "" and
          .value != [] and
          .value != {}
        )
      )
    else .
    end
  );
```

**Comment by davidfetter** [comment]
Here's a more general one without the redundant `. |`:
```def remove_empty:
  walk(
    if type == "array" then
      map(select(. != null))
    elif type == "object" then
      with_entries(
        select(
          .value != null and
          .value != "" and
          .value != [] and
          .value != {}
        )
      )
    else
      .
    end
  );
```

**Comment by nicowilliams** [comment]
Pithier: `delpaths([path(..?) as $p | select(getpath($p) == null) | $p])`:

```
$ jq -n '{a:{b:null},c:{d:1}} | delpaths([path(..?) as $p | select(getpath($p) == null) | $p])'
{
  "a": {},
  "c": {
    "d": 1
  }
}
```

A more online but slightly more complicated version:

```
jq -n '{a:{b:null},c:{d:1}} | reduce (path(..?) as $p | select(getpath($p) == null) | $p) as $p (.; delpaths([$p]))'
{
  "a": {},
  "c": {
    "d": 1
  }
}
```

**Comment by peteristhegreat** [comment]
@nicowilliams Thank you for the great example!  Note that it requires jq 1.6 to use it.

**Comment by saizai** [comment]
@nicowilliams What's the benefit to your second version? Is there any reason it can't be put in `~/.jq` and used as a simple passthrough function, ie `jq '. | delnulls | …' …`?

**Comment by saizai** [comment]
@davidfetter Does this catch `""`/`[]`/`{}` — or nested empties like `[{””:[]},[]]`?

>     if type == "array" then
>       map(select(. != null))
>     elif type == "object" then

IME most of my cruft comes in from format conversions, eg CSV → JSON, or from external sources that don't know how to use proper `null` and instead use either empty string or various signal values. 

So my version tries to catch all of those. 

This should include nested ones (for which depth-first processing is necessary). E.g. `[[""],[""]]` definitely `!=null` (ask a number theorist 😉), but depth-first conversion will turn it into `[[],[]]` → `[]` → `null`.

**Comment by saizai** [comment]
Here's an updated version of mine:

`~/.jq`
```jq
def isempty(v):
 (v == null or v == "" or v == [] or v == {});

def isnotempty(v):
 (isempty(v) | not);

def remove_empty:
  walk(
   if type == "array" then
      map(select(isnotempty(.)))
   elif type == "object" then
      with_entries(select(isnotempty(.value))) # Note: this will remove keys with empty values
   else .
   end
  );
```

Usage:
```bash
$  echo '{"x":[[["",""],["a",""]],"","b"],"y":null,"z":[{},{"1":2}]}' | jq -c '. | remove_empty'
{"x":[[["a"]],"b"],"z":[{"1":2}]}
$ echo '""' | jq '. | remove_empty'
""
$ echo 'null' | jq '. | remove_empty'
null
```

**Comment by pkoppstein** [comment]
@saizai - Please note that isempty/1 is already a built-in function.  It checks whether its argument is an empty stream, so it would be helpful if you chose a different name for your def.

For future reference, one can easily check whether jq defines a NAME/ARITY filter using: `jq -n builtins`, e.g.

    $ jq -n builtings | grep isempty
    "isempty/1"

    $ jq -n '"isempty/1" | IN(builtins[])'
    true

**Comment by luckman212** [comment]
@pkoppstein Nice tip! FYI- you have a little typo: `builtings` → `builtins`

**Comment by luckman212** [comment]
Here's what I'm using, jq 1.6:

```jq
def nonulls:
  [ "", null, [], {} ] as $e |
  walk(
    if type == "object" then
      with_entries(select(.value | IN($e[]) | not))
    elif type == "array" then
      map(select(. | IN($e[]) | not))
    else . end
  );
```

```bash
$ jq -n '{ foo: "", baz: null, quux: [], nice: [ "x", "y", { foo: "" }, null, 123 ] } | nonulls'
{
  "nice": [
    "x",
    "y",
    123
  ]
}
```

**Comment by SantoshSahoo02** [comment]
Thanks for all your answers.
Still I can't figure out how to remove null values from a key of JSON array type.
I need an empty key({}) if all the values are null or remove nulls from the JSON array.
In the below example, I want to filter the nulls from Workloads JSON array. Please let me know any workaround . Thanks a lot. 
**[ I am using jq version 1.5 ]**

For example, with this input:	
```
{
  "EC2 Instance Metadata": [
    {
      "EC2 Private IPv4 DNS Name": "compute.internal-1",
      "EC2 Private IPv4 address": "1.2.3.4",
      "Workloads": [
        null
      ],
      "Application Pods": [
        "pod-1"
      ],
      "Application Containers": [
        "container"
      ],
      "Container Images": [
        "image/1.0"
      ]
    },
    {
      "EC2 Private IPv4 DNS Name": "compute.internal-2",
      "EC2 Private IPv4 address": "1.2.3.44",
      "Workloads": [
        null
      ],
      "Application Pods": [
        "pod-2"
      ],
      "Application Containers": [
        "container-2"
      ],
      "Container Images": [
        "image/2.0"
      ]
    },
    {
      "EC2 Private IPv4 DNS Name": "compute.internal-3",
      "EC2 Private IPv4 address": "1.23.3.44",
      "Workloads": [
        "workload-1",
        "workload-2",
        "workload-3",
        null,
        null,
        null,
        "workload-4"
      ],
      "Application Pods": [
        "pod-1",
        "pod-2"
      ],
      "Application Containers": [
        "cnt-1",
        "cnt-2"
      ],
      "Container Images": [
        "image-1",
        "image-2"
      ]
    }
  ]
}
```
I want to generate this output:

```
{
  "EC2 Instance Metadata": [
    {
      "EC2 Private IPv4 DNS Name": "compute.internal-1",
      "EC2 Private IPv4 address": "1.2.3.4",
      "Workloads": [
        {}
      ],
      "Application Pods": [
        "pod-1"
      ],
      "Application Containers": [
        "container"
      ],
      "Container Images": [
        "image/1.0"
      ]
    },
    {
      "EC2 Private IPv4 DNS Name": "compute.internal-2",
      "EC2 Private IPv4 address": "1.2.3.44",
      "Workloads": [
        {}
      ],
      "Application Pods": [
        "pod-2"
      ],
      "Application Containers": [
        "container-2"
      ],
      "Container Images": [
        "image/2.0"
      ]
    },
    {
      "EC2 Private IPv4 DNS Name": "compute.internal-3",
      "EC2 Private IPv4 address": "1.23.3.44",
      "Workloads": [
        "workload-1",
        "workload-2",
        "workload-3",
        "workload-4"
      ],
      "Application Pods": [
        "pod-1",
        "pod-2"
      ],
      "Application Containers": [
        "cnt-1",
        "cnt-2"
      ],
      "Container Images": [
        "image-1",
        "image-2"
      ]
    }
  ]
}
```

**Comment by wader** [comment]
@SantoshSahoo02  Maybe something like this `del(.. | select(. == null))`? but it looks like you want some nulls to become empty objects?

**Comment by SantoshSahoo02** [comment]
@wader Thanks for the heads up! Yes, nulls to be replaced by empty objects. Here is the proposed solution.
`jq '(.. | arrays) |= if all(type == "null") then [{}] else map(values) end')`

**Comment by angular-material2** [comment]
> Very well then ;) thanks





https://phps.space/questions/a-guide-on-displaying-a-specific-value-stored-within-an-array-using-json-techniques
