### ISSUE TITLE
Consider making '.' the default when no filters specified

### ISSUE THREAD

**Issue by rfreebern** [stedolan/jq#1040]
When piping output through jq for pretty-printing, it gets cumbersome to type `jq '.'` every single time. It would be nice if `'.'` was the default when no filter was specified and there is input on STDIN.

**Comment by nicowilliams** [comment]
Duplicate of #1028.

**Comment by dtolnay** [comment]
Not quite a duplicate. This is already the behavior in jq 1.5.

**Comment by nicowilliams** [comment]
Ah, good point.  Still, it's a duplicate of some other issue then.

**Comment by rfreebern** [comment]
Oh, thanks! Sorry, I read the docs but didn't see this behavior mentioned, and most examples still use `jq '.'`. Glad to know all I need to do is upgrade!
