### ISSUE TITLE
Comment continuation needed on first comment following shebang

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#1044]
Historically shebangs allow only one argument in the shebang line.  This means that if the script author doesn't know the path to the script interpreter *and* they need to pass any additional arguments to said interpreter, then they can't write the script.

The typical thing to do is this:

    #!/bin/sh
    # this comment is here just for the continuation so foo interpret doesn't eval this next line \
    exec jq -f "$0" "$@"

But jq does _not_ have comment continuations now, so adding them now would break backwards compatibility.  But I think it'd be safe to scan for the shebang and continued comment on the first line in `main()` (as opposed to in `src/parser.y`).  Then the above would work and there chance of breakage would be astronomically small.

**Comment by pkoppstein** [comment]
The [FAQ](https://github.com/stedolan/jq/wiki/FAQ) now documents the `exec jq` trick.

**Comment by nicowilliams** [comment]
Thanks @pkoppstein.

**Comment by averca7** [comment]
](url)
