### ISSUE TITLE
jq parse error w.r.t control characters 

### ISSUE THREAD

**Issue by rupenp** [stedolan/jq#1049]
Hi,

I am wondering if there is a workaround to avoid jq exiting after "control-code caused" parse error is received and allow it to skip and continue reading the file.
"parse error: Invalid string: control characters from U+0000 through U+001F must be escaped"

I know there has been some past discussion on the jq issue list on this control-codes topic, and there is wikipage (http://rosettacode.org/wiki/Strip_control_codes_and_extended_characters_from_a_string#jq) which shows how to strip control codes in the raw string before its passed json loader. But all that doesnt work. My current workaround for this is that I parse/stream my json data to a helper python script, which does json.load/json.dump from/to stdin/stdout, whatever goes through (doesn't cause exception) is passed on to jq .

It would be really nice if either:
(a) there is filter I can build around which will allow jq to skip on parse error and continue reading the file
(b) or if I can hack jq source , recompile jq locally and use it for my purpose.

Any advice or help on this will be very helpful.

**Comment by pkoppstein** [comment]
Under a certain set of rather restricted conditions, it is possible to recover from "bad input".  The basic idea is to read the possibly bad input on a line-by-line basis, and use `fromjson` in the jq program, as that is where there is support for try/catch.  A version of jq with `inputs` is required (e.g. jq 1.5). Here is an example:
### File: bad.json
```
[1,2,3]
{id=546456, userId=345345}
[4,5,6]
```

### File: handle.jq
```
def handle: inputs | [., (fromjson | "length is \(length)")] ;

def process: try handle catch ("Failed", process) ;

process
```
### See jq run:
```
$ jq -R -n -f handle.jq bad.json
[
  "[1,2,3]",
  "length is 3"
]
"Failed"
[
  "[4,5,6]",
  "length is 3"
]
```

**Comment by rupenp** [comment]
Ok, I see. Let me try it out thanks. Although the bad-json data in my case are tweets, and sometimes those are not properly written out to a file, so they may be simply malformed or prematurely truncated json strings.

**Comment by nicowilliams** [comment]
@rupenp [RFC7159](https://tools.ietf.org/html/rfc7159) a) does not allow any control characters other than some whitespace (tabs and newlines) in JSON texts, and b) requires that they be escaped when in strings.  If you have JSON texts that violate one of these requirements, you can try to get around them with `sed(1)`.  Something like `sed -e s/\t/\\t/g -e ...`, perhaps, for violations of (b), for example.

You should also go fix whatever is causing this problem at the source.

**Comment by rupenp** [comment]
Thank you  @pkoppstein and  @nicowilliams .

I was able to successfully incorporate @pkoppstein 's suggested filter, its working out great.

**Comment by gitjeff05** [comment]
I know this is an old thread put I wanted to comment anyways:

Like others, I noticed that `jq` was having issues parsing json with control characters:

```json
{
  "name": [
    "hi\n",
    "there"
  ]
}
```

When running jq on this string I would get the error:

```bash session
> echo '{ "name": ["hi\n", "there"] }' | jq .
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 1
```

I initially thought that  it was because the `\n` control character was invalid inside json as mentioned above and in [rfc8259](https://tools.ietf.org/html/rfc8259).

I now believe that this has to do with how `echo` (zsh 5.7.1) *interprets* the newline and before it gets passed to `jq`. To validate this I created another file with `echo '{ "name": ["hi\n", "there"] }' > file2.json`:

```bash session
> cat -ev file2.json
{ "name": ["hi$
", "there"] }$
```

I believe it is the newline placed after the `hi` that `jq` has a problem with (i.e., it interprets the control characters instead of treating them as literals). I tried the same echo command in `GNU bash, version 3.2.57` and I did *not* get the errors. Different shells have different implementations of `echo`.

## The fix

```bash session
> printf "%s" '{ "name": ["hi\n", "there"] }' | jq .
```
or
```bash session
> echo -E '{ "name": ["hi\n", "there"] }' | jq .
```

**Comment by Doriangaensslen** [comment]
I've ran into this issue because I used kubecolor.... so make sure you are not using it when parsing with jq or jid

**Comment by alexpatinoa** [comment]
Hi Guys;

I got the same issue in github action;
Action:
```
- name: Obtain Value
    run: |
      cat new_ecdsa_config.json | jq '.'
```
      
Json:
```
{
  "certificate": "value long string
                          multine"
}
```

When run the action jq not retrieve the value and jump this error;

```
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 26, column 53
Error: Process completed with exit code 4.
```

Any ideas???

**Comment by pkoppstein** [comment]
@alexpatinoa - Sometimes it pays to try to understand the error message.  In this case, you can verify the proposed JSON is actually invalid, e.g. by checking at jsonlint.com.  You could escape the newline using `\n`

**Comment by alexpatinoa** [comment]
Hello @pkoppstein 
You know how to do it?
The truth is that I am a beginner in json and jq issues and no matter how many sentences I add, I always get the same error.
:(

**Comment by alexpatinoa** [comment]
@pkoppstein i tried
`jq '.certificate' new_ecdsa_config.json | sed 's/\\[tn]//g'`
Locally works fine but in action fails for the escape

**Comment by wader** [comment]
In the action where does `new_ecdsa_config.json` come from? from a git repo checkout or is created somehow?

Some idea how to debug:
- Do something like `hexdump -C new_ecdsa_config.json` in the action to see what is going on
- Replace `cat new_ecdsa_config.json | jq '.'` with `cat new_ecdsa_config.json | jq -Rs '{input: ., json: (try fromjson catch .)}'` to see input and also what jq parses it too or what error it throws

**Comment by alexpatinoa** [comment]
@wader the file new_ecdsa_config.json is generate in the action by another action.
The content is something like this 

`{"certificate": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEK1RDQ0E2Q2dBd0lCQWdJVEZBQUFBQysrYkNRRTdrbVFLUUFBQUFBQUx6QUtCZ2dxaGtqT1BRUURBakJODQpNUlF3RWdZS0NaSW1pWlB5TEdRQkdSWUVRMDlTVURFY01Cb0dDZ21TSm9"}`


This throw error in action
`echo $(cat new_ecdsa_config.json | jq '.')  `

This throw error in action
`echo $(cat new_ecdsa_config.json | jq '.certificate')  

Error `parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 26, column 53`

I see an \n when i execute but i tried everything to escape the '\n' and de result is the same

But in my local works fine, i think is the ubuntu of te action

**Comment by wader** [comment]
Ok then i would guess there is some difference how the json file is generated. In the action try to hexdump it or as i suggested run jq with `-Rs` to slurp the whole input as a string so that you can see what you are actually feeding to jq.

**Comment by yb66** [comment]
I've received this error message too, but the most important aspect for me is that the error message is so poor at telling me the problem:

> parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 9, column 134

*Which* control character? jq just parsed it so jq must know, you're going to make me break out another tool to find it? Just tell me!

Also, my JSON was all on one line, "line 9, column 134" is either an internal representation or a consequence of the parsing or providing output. Just *show me* the line in question!

**Better error messages would improve this situation** ***immeasurably***, probably more than any of the solutions above (none of which solved my problem, so now I'll use a different tool).

At least it's not like the old Windows error messages that were gobbledegook with an opaque error number, but it's in that realm.

**Comment by wader** [comment]
Looking at the code https://github.com/jqlang/jq/blob/ba741e59684a1b626e48b651d40c694b7940545b/src/jv_parse.c#L497 it shouldn't be much problem but would probably require that all returned error strings are allocated and freed later on... i'm guessing that is why someone didn't bother including the exact character in the error message.
