### ISSUE TITLE
OS X Install available in MacPorts

### ISSUE THREAD

**Issue by psylum** [stedolan/jq#1050]
The download website lists that you can use homebrew or the raw binary for installing jq on OS X. MacPorts also includes jq for installation. It is currently at version 1.5 (latest, at time of filing this issue). It is a similarly trivial install: `(sudo) port install jq`.

**Comment by pkoppstein** [comment]
Availability via MacPorts has been noted at https://github.com/stedolan/jq/wiki/Installation
Thanks, @psylum.
