### ISSUE TITLE
Cannot query on path where element name contains a hyphen

### ISSUE THREAD

**Issue by karlfunk** [stedolan/jq#1051]
I am working on a Hadoop Ambari blueprint as input e.g. [1] as my test input. 

This contains the following:

jq '.configurations[0]' inputs/ex1.txt 
{
  "kerberos-env": {
    "properties_attributes": {},
    "properties": {
      "realm": "AMBARI.APACHE.ORG",
      "kdc_type": "mit-kdc",
      "kdc_host": "(kerberos_server_name)",
      "admin_server_host": "(kerberos_server_name)",
      "encryption_types": "aes des3-cbc-sha1 rc4 des-cbc-md5",
      "ldap_url": "",
      "container_dn": ""
    }
  }
}

If I now want to access kerberos-env or its children I cannot construct the path e.g. 

jq '.configurations[0].kerberos-env.properties'
error: env is not defined
.configurations[0].kerberos/-env.properties                             1 compile error

I have tried various attempts at escaping the dash (and removed it from the input to confirm the path works without it).

[1] https://cwiki.apache.org/confluence/display/AMBARI/Blueprints#Blueprints-BlueprintExample:ProvisioningMulti-NodeHDP2.3ClustertouseKERBEROS

**Comment by pkoppstein** [comment]
jq 1.5 gives you several alternatives:

    $ jq -n '{"x": [{"a-b":1}]} | .x[0]["a-b"]'
    1

    $ jq -n '{"x": [{"a-b":1}]} | .x[0] | .["a-b"]'
    1

    $ jq -n '{"x": [{"a-b":1}]} | .x[0] | ."a-b"'
    1

For more details, see the current version of the jq manual (in the ".foo.bar" section), or google (for example) with keywords: jq key hyphen

**Comment by karlfunk** [comment]
Perfect. Thanks for the very quick answer!
