### ISSUE TITLE
Conditional statement with regular expression

### ISSUE THREAD

**Issue by pcgeek86** [stedolan/jq#1052]
I think I'm doing something wrong here, so bear with me. I'm trying to use a simple regular expression match, using the `test()` function in `jq`, which returns `true` or `false`. 

As far as the input is concerned, don't worry about the details of the `azure` command. For the sake of this discussion, the input I have looks similar to the following:

```JSON
[
  {
    "name": "foo"
  },
  {
    "name": "bar"
  }
]
```

Here is what I have working so far:

```bash
azure group list --json | jq '.[].name | test("Acad")' --raw-output
```

> FYI, unrelated to the issue, I'm using the `--raw-output` parameter, because I don't want double quotes surrounding the final, resulting output.

However, instead of getting `true` or `false` as the result, I want the original JSON property value. To do this, I decided to use an `if-then-end` statement. However, I'm getting errors with this syntax.

```
azure group list --json | jq '.[].name | if test("Acad") then . end' --raw-output
```
> jq: error: syntax error, unexpected end (Unix shell quoting issues?) at <top-level>, line 1:
.[].name | if test("Acad") then "." end
jq: error: Possibly unterminated 'if' statement at <top-level>, line 1:
.[].name | if test("Acad") then "." end
jq: 2 compile errors

Can anyone help me identify the syntax error in my `if-then-end` statement? The `test()` function emits `true` or `false`, according to the documentation, so I can't see why this isn't working. I'd appreciate any insights.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by pkoppstein** [comment]
The jq `if` statement requires the `else` clause: if _ then _ else _ end

But you should probably be using `select`, which is like: if _ then . else empty end

So in your case, you may wish to consider: `select( test("Acad") )`

**Comment by pcgeek86** [comment]
Hmmm, as I was going through the documentation, I almost gave `select( )` a try. I guess I should have. Thanks @pkoppstein!

<img width="1063" alt="screen shot 2015-12-23 at 3 13 59 pm" src="https://cloud.githubusercontent.com/assets/466713/11985995/d6b8b7d2-a987-11e5-8f4d-68a786bdd15d.png">

Cheers,
Trevor Sullivan
