### ISSUE TITLE
Possible Bug?

### ISSUE THREAD

**Issue by vito-c** [stedolan/jq#1055]
`jq --slurpfile foo <(echo '{"a":5,"c":5,"e":5,"f":5}') '(..|objects) | to_entries | map( if $foo[0]|has(.key) then .value = $foo[0][.key] else . end )' <(echo '{"a":1,"b":{"c":1,"d":{"e":2}},"f":3}')`

results in 
`jq: error (at /dev/fd/62:1): Cannot check whether object has a null key`

but this works
`jq --slurpfile foo <(echo '{"a":5,"c":5,"e":5,"f":5}') '(..|objects) | to_entries | map( if $foo[0][.key] != null then .value = $foo[0][.key] else . end )' <(echo '{"a":1,"b":{"c":1,"d":{"e":2}},"f":3}')`

**Comment by pkoppstein** [comment]
@vito-c -- `$foo[0]|has(.key)` is equivalent to `$foo[0]|has( $foo[0]|.key)`, i.e. $foo[0][null], which produces the error you see.  No mystery about that, ergo no bug.

**Comment by vito-c** [comment]
@pkoppstein thanks
