### ISSUE TITLE
Cross-compile via Travis-CI too

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#1059]
It seems it's possible to cross-compile in Travis-CI builds.

A few links:

 - http://stackoverflow.com/questions/28155308/how-to-cross-compile-with-mingw-on-linux-for-windows

   This one has a great answer.  We need grab the Mingw pkgs [from a third-party repo](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-from-a-custom-apt-repository) (which I guess we can trust as far as CI goes), then use them in the Travis build.  Ideally Travis would just provide these...

 - https://trac.osgeo.org/geos/ticket/659
 - http://www.scriptscoop.net/t/d39c9eac38a2/how-to-cross-compile-with-mingw-on-linux-for-windows.html
 - http://sourceforge.net/p/mingw-w64/mailman/message/31846195/

**Comment by JanSchulz** [comment]
There is also appveyor, which allows compilations on windows using the VSC compilers (multiple versions are installed) and mingw: http://help.appveyor.com/discussions/questions/372-build-setup-for-a-c-program#comment_33757635

Appveyor also can automatically generate artifacts which are downloadable via the individual build pages, so one can download a build for each PR.

**Comment by JanSchulz** [comment]
BTW: According to https://msdn.microsoft.com/en-us/library/hh567368.aspx#featurelist, the latest VS mostly supports C++11

**Comment by nicowilliams** [comment]
@JanSchulz And they support a clang frontend, which means GCC C extensions (e.g., `__cleanup__`, statement-expressions, etc.) can be used.

I'd love to have this:

    #define JV(v) jv v __attribute__ ((__cleanup__(jv_free)))

then many automatic (local) variables of type `jv` could be declared with `JV()` instead.  That would greatly simplify a lot of code in jq.

**Comment by nicowilliams** [comment]
@JanSchulz Thanks for the appveyor link!

**Comment by nicowilliams** [comment]
Closing for now.  Thanks to @JanSchulz we now have appveyor support, though it's not yet enabled.

**Comment by nicowilliams** [comment]
Also, appveyor can run our tests on Windows.  So, yeah, that's superior to building on Windows via Travis.

**Comment by erikbrinkman** [comment]
@nicowilliams Given that you mentioned the following given failing appveyor builds:

> Another option might be to see if there's any way to cross-compile on Travis and screw Windows, though that would require cross-compiling Oniguruma too, which would mean having to include Oniguruma in-tree, which sucks.

In a PR, it seemed reasonable to bring this back up. In particular, would it be that bad to include onigurama as a submodule in tree? Then all builds would have support, and it shouldn't really require any more maintenance. Also, would it not be possible to cross compile it just like the mingw libraries? I should mention that I have no experience developing on Windows, so these could be very dumb comments.

**Comment by nicowilliams** [comment]
I don't think it would be bad, no, though I don't know that we can checkout submodules (or whatever the operation is called; I haven't used submodules) within a Travis build.  In a pinch we can commit a tarball.

**Comment by erikbrinkman** [comment]
I'm pretty sure submodules can be pretty easily used with travis as I have another project that uses them. I'll play around with a branch that looks at building with a submoduled onigurama and you can see what it looks like it see if it makes sense to push forward.

**Comment by nicowilliams** [comment]
Ah, that's good news.
