### ISSUE TITLE
Function to strip quotes from a string

### ISSUE THREAD

**Issue by vishvananda** [stedolan/jq#106]
When getting output from json apis and attempting to use them with other unix utilities, you often need just the value of a string without the surrounding quotes.  Clearly i can do something like:

curl ... | jq .keypairs[$i].keypair.name | tr -d '"'

but it would be nice to be able to do:

curl ... | jq '.keypairs[$i].keypair.name | tovalue'

or something along those lines

**Comment by Ripounet** [comment]
Great, thanks ghost

**Comment by StefanScherer** [comment]
Thanks @ghost !

**Comment by CanadianJeff** [comment]
awesome this helped me too thanks
