### ISSUE TITLE
Brew installation not working.

### ISSUE THREAD

**Issue by david-caldwell** [stedolan/jq#1064]
$: brew install jq
==> Downloading http://stedolan.github.io/jq/download/source/jq-1.4.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "jq"
Download failed: http://stedolan.github.io/jq/download/source/jq-1.4.tar.gz

**Comment by wtlangford** [comment]
Brew should be installing jq 1.5.  Are your formulas out of date?

**Comment by david-caldwell** [comment]
It's possible, but the following urls return 404.

http://stedolan.github.io/jq/download/source/jq-1.4.tar.gz
http://stedolan.github.io/jq/download/source/jq-1.5.tar.gz

**Comment by wtlangford** [comment]
So my jq formula in brew is downloading from `
https://github.com/stedolan/jq/releases/download/jq-1.5/jq-1.5.tar.gz`,
which is certainly correct.  The urls you've listed haven't been right
since... August, it seems.  I'd run `brew update`.

**Comment by david-caldwell** [comment]
brew update exposed a few other issues.

I was finally able to get `brew update` working.

Thanks for your help.
