### ISSUE TITLE
why do jv_string_length_bytes(), jv_dump_string() etc free their input argument

### ISSUE THREAD

**Issue by mewalig** [stedolan/jq#1065]
Just out of curiosity: why were various function such as jv_string_length_bytes() and jv_dump_string() written such that they free their input argument? It seems to create a lot of unnecessary extra calls to jv_copy() when the user does not want the arg to be freed, and it seems also somewhat unintuitive to know that a function named e.g. jv_string_length_bytes(x) is also going to do a jv_free() on x.

wouldn't it be cleaner, more intuitive and less verbose to be able to do something like:

       while (jv_is_valid(result = jq_next(jq))) { // one thing we need to know is that jq_next() will alloc
         ... // do stuff here that does not free result
             // no need to ever call jv_copy(), and 
             //   we don't need to remember [or resort to reviewing the jv code to know]
             //   that some jv_xxx calls free their argument while others do not
         free(result);
      }

?

**Comment by nicowilliams** [comment]
I think that the string and array length functions really ought not consume
a reference of their input, but aside from those and jv_copy(), the
general convention is that any function that takes a jv releases it, so if
you don't want this then you must pass a copy.  This helps make memory
management for jv automatic.  You have to get used to it, but it's a very
good thing.

**Comment by nicowilliams** [comment]
Another exception is jv_show(), since that's meant for use in
source debuggers, and then having to type jv_show(jv_copy(...),0) is a pain.

**Comment by mewalig** [comment]
Got it, thank you

**Comment by nicowilliams** [comment]
BTW, jv_string_value() is a prime example of where not consuming a
reference it's obnoxious, but there's no choice there.  For the length
functions there are almost no uses without jv_copy(), but if you have even
one case where you want a length function to consume its input's reference
then you can't just ` return jv_array_length(foo);` because then you have
to jv_free(foo) before returning.  And... that's where the few uses without
jv_copy() are: in f_length(), in src/builtin.c.  So there you go.

**Comment by nicowilliams** [comment]
I often wish I could `return foo(jv_string_value(some_value));`, but this isn't possible without using the GCC C extension `__cleanup__(function)` variable attribute.  With Visual Studio now supporting clang as a front end, this might be something we can use soon enough...

**Comment by mewalig** [comment]
How about just having two versions of the functions? For example, you could append _nofree() to function names for versions of functions that do not free their input arg:
```
jv_string_length_bytes() 
jv_string_length_bytes_nofree()
```
It would make the code much more readable (clearer function names + less clutter e.g. calls to jv_copy()) and also perform better. The alternate funcs could even just be macro defines.

**Comment by mewalig** [comment]
and if you didn't want to actually make them separate funcs, the 2 calling conventions could just be macro definitions.
