### ISSUE TITLE
looking for a workaround to get "one block of JSON per line"

### ISSUE THREAD

**Issue by OlivierThompson** [stedolan/jq#1067]
Hi there,

Would it be possible to use JQ on windows in order to  transform a json input file (or stream) in a way that each document is on a single line with only a Carriage Return / Line Feed (CRLF) between each document.

This would help a common issue encontered on Windows while inserting JSON files into mongodb database with mongoimport. 

Thanks a lot

see these links :
http://mathematica.stackexchange.com/questions/76240/export-to-json-format-specifically-for-mongodb
https://www.amido.com/format-json-for-mongoimport-exe-2/

**Comment by pkoppstein** [comment]
@OlivierThompson - I believe you're looking for the "-c" command-line option.  As in: `jq -c .`

**Comment by OlivierThompson** [comment]
Thank you for quick reply, I'm novice with JSON and appreciate your help. Here a some details. 
First I get the JSON from tradier.com with curl command line (I replaced my token with xxxxx). The result file is attached in SPY.zip.

C:\Users\Olivier>curl -H "Accept: application/json"  -H "Authorization: Bearer 
xxxxxxxxxxxxxxxxxxxxxxxxx" "https://sandbox.tradier.com/v1/markets/options/cha
ins?symbol=SPY&expiration=2016-01-08" | more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  116k  100  116k    0     0   101k      0  0:00:01  0:00:01 --:--:--  101k
{"options":{"option":[{"symbol":"SPY160108P00219500","description":"SPY Jan 8 20
16 $219.50 Put","exch":"Z","type":"option","last":0.0,"change":null,"change_perc
entage":null,"volume":0,"average_volume":0,"last_volume":0,"trade_date":0,"open"
:null,"high":null,"low":null,"close":null,"prevclose":"NaN","week_52_high":0.0,"
week_52_low":0.0,"bid":26.0,"bidsize":1,"bidexch":"C","bid_date":1452287688000,"
ask":29.39,"asksize":10,"askexch":"M","ask_date":1452287688000,"open_interest":0
,"underlying":"SPY","strike":219.5,"contract_size":100,"expiration_date":"2016-0
1-08","expiration_type":"weeklys","option_type":"put","root_symbol":"SPY"},{"sym
bol":"SPY160108C00219500","description":"SPY Jan 8 2016 $219.50 Call","exch":"Z"
,"type":"option","last":0.02,"change":0.0,"change_percentage":0.0,"volume":0,"av
erage_volume":0,"last_volume":2,"trade_date":1451420156000,"open":null,"high":nu
ll,"low":null,"close":null,"prevclose":0.02,"week_52_high":0.0,"week_52_low":0.0
,"bid":0.0,"bidsize":0,"bidexch":"C","bid_date":1452287699000,"ask":0.02,"asksiz
...
...
Now I wish to import this JSON to mongodb, but mongoimport will refuse to process this file because it doesn't have one block of JSON per line. So I tried to transform the JSON file with jq , on my windows 7 machine. But I can't find the right way to get one block of JSON per line, and also by the way to get rid of the unnecessary JSON first field (ie optionS) and commas after each block.

This is what I get with the -c option :   

C:\Users\Olivier>type SPY.json | jq-win64.exe -c .  | more
{"options":{"option":[{"symbol":"SPY160108P00219500","description":"SPY Jan 8 20
16 $219.50 Put","exch":"Z","type":"option","last":0,"change":null,"change_percen
tage":null,"volume":0,"average_volume":0,"last_volume":0,"trade_date":0,"open":n
ull,"high":null,"low":null,"close":null,"prevclose":"NaN","week_52_high":0,"week
_52_low":0,"bid":26,"bidsize":1,"bidexch":"C","bid_date":1452287688000,"ask":29.
39,"asksize":10,"askexch":"M","ask_date":1452287688000,"open_interest":0,"underl
ying":"SPY","strike":219.5,"contract_size":100,"expiration_date":"2016-01-08","e
xpiration_type":"weeklys","option_type":"put","root_symbol":"SPY"},{"symbol":"SP
Y160108C00219500","description":"SPY Jan 8 2016 $219.50 Call","exch":"Z","type":
"option","last":0.02,"change":0,"change_percentage":0,"volume":0,"average_volume
":0,"last_volume":2,"trade_date":1451420156000,"open":null,"high":null,"low":nul
l,"close":null,"prevclose":0.02,"week_52_high":0,"week_52_low":0,"bid":0,"bidsiz
e":0,"bidexch":"C","bid_date":1452287699000,"ask":0.02,"asksize":900,"askexch":"
Q","ask_date":1452287699000,"open_interest":216,"underlying":"SPY","strike":219.
5,"contract_size":100,"expiration_date":"2016-01-08","expiration_type":"weeklys"
,"option_type":"call","root_symbol":"SPY"},{"symbol":"SPY160108P00219000","descr
iption":"SPY Jan 8 2016 $219.00 Put","exch":"Z","type":"option","last":14.57,"ch
ange":0,"change_percentage":0,"volume":0,"average_volume":0,"last_volume":20,"tr
ade_date":1449769149000,"open":null,"high":null,"low":null,"close":null,"prevclo

Anyhow I can manage to do the job with C# or perl, but I THINK having such a option in jq could help other projects with importing JSON to mongodb, since there are not much straightforward guides for these use case.

Thanks a lot in advance 






[SPY.zip](https://github.com/stedolan/jq/files/83469/SPY.zip)

**Comment by pkoppstein** [comment]
Perhaps you are running into a Windows-specific issue?

On a Mac, I've verified that "jq -c" works properly, both using your SPY.json
and the dataset given on the mongodb website (https://docs.mongodb.org/getting-started/shell/import-data/):

```
$ jq -c . SPY.json | wc -l
       1

$ wc -l dataset.json
   25359 /tmp/dataset.json

$ jq -c . dataset.json | wc -l
   25359
```

**Comment by nicowilliams** [comment]
The answer is `-c`.

**Comment by OlivierThompson** [comment]
I thank you very much for you help and time you spent on this issue, it was not at all closely related to jq. 
Actually I didn't find the write way to use jq (maybe this is Windows-specific) but I found a workaround with python. I'm a python beginner anyhow I show you my python code below, just in order to better explain what I needed.

thanks to http://pythontips.com/2013/08/08/storing-and-loading-data-with-json/
```python
#Copyright (C) OlivierThompson
import sys
import json

parsed_input = json.load(open('SPY.json'))
class OptionChain(object):

    def __init__(self, underlying, expiration_date,strike,symbol,volume,open_interest):
        self.underlying = underlying
        self.expiration_date = expiration_date
        self.strike = strike
        self.symbol = symbol
        self.volume = volume
        self.open_interest = open_interest
def jdefault(o):
    return o.__dict__
for entry in parsed_input["options"]["option"]:
   option_chain  = OptionChain(entry["underlying"] ,entry["expiration_date"],entry["strike"] ,entry["symbol"] , entry["volume"],entry["open_interest"]  )
   print json.dumps(option_chain,default=jdefault)
```
And the result is now suitable with mongoimport : 

```json
{"expiration_date": "2016-01-08", "symbol": "SPY160108P00219500", "volume": 0, "underlying": "SPY", "strike": 219.5, "open_interest": 0}
{"expiration_date": "2016-01-08", "symbol": "SPY160108C00219500", "volume": 0, "underlying": "SPY", "strike": 219.5, "open_interest": 216}
{"expiration_date": "2016-01-08", "symbol": "SPY160108P00219000", "volume": 0, "underlying": "SPY", "strike": 219.0, "open_interest": 0}
{"expiration_date": "2016-01-08", "symbol": "SPY160108C00219000", "volume": 0, "underlying": "SPY", "strike": 219.0, "open_interest": 1811}
{"expiration_date": "2016-01-08", "symbol": "SPY160108P00190000", "volume": 6297, "underlying": "SPY", "strike": 190.0, "open_interest": 28669}
{"expiration_date": "2016-01-08", "symbol": "SPY160108C00190000", "volume": 66, "underlying": "SPY", "strike": 190.0, "open_interest": 519}
{"expiration_date": "2016-01-08", "symbol": "SPY160108C00185000", "volume": 0, "underlying": "SPY", "strike": 185.0, "open_interest": 16}
{"expiration_date": "2016-01-08", "symbol": "SPY160108P00196000", "volume": 2692, "underlying": "SPY", "strike": 196.0, "open_interest": 18668}
{"expiration_date": "2016-01-08", "symbol": "SPY160108P00195500", "volume": 3194, "underlying": "SPY", "strike": 195.5, "open_interest": 7520}
{"expiration_date": "2016-01-08", "symbol": "SPY160108P00195000", "volume": 14239, "underlying": "SPY", "strike": 195.0, "open_interest": 23782}
```
Thanks a lot.

**Comment by nicowilliams** [comment]
$ jq -c '.options.option | {underlying, expiration_date, strike, symbol, volume, open_interest}'

**Comment by OlivierThompson** [comment]
Brillant.
I confirm my isssue was Windows specific, the above command fails on a windows 7 with jq-win64.exe.  
Thank you very much.

**Comment by nicowilliams** [comment]
You have to mind your quotes on Windows.  The simplest thing to do is to put the jq program in a file and then use `jq -f program_file.jq ...`, then you don't have to worry about shell quoting.

**Comment by ThomasRooney** [comment]
In case anyone finds this issue again (with latest jq), and the `-c` argument doesn't work (as it didn't for me) an easy workaround is to make sure to strip carriage return characters from the output. E.g.

```
$ cat package.json | jq  -c '.devDependencies|keys|.[]' |xargs echo
 yaml-loadereriddlewareindeportermlgngacy

$ cat package.json | jq '.devDependencies|keys|.[]' | tr -d '\r' |xargs echo
@storybook/addon-knobs @storybook/addon-options @storybook/react ...
```
