### ISSUE TITLE
How to refer to `--arg` arguments

### ISSUE THREAD

**Issue by lisi4ok** [stedolan/jq#1068]
```
{
    "env": "dev",
    "dev": {
        "global": {
            "buildpath": "/var/www/",
            "defaultbranch": "master",
            "mysqlpassword": "paasasas"
        },
        "projects" : {
            "prj1": {
                "dependencies": {},
                "description": ""
            }
        }
    }
}
```

```
PRJNAME='prj1'

echo $PRJNAME

jq --arg v "$PRJNAME" '.dev.projects."$v"' config.json 
jq '.dev.projects.prj1' config.json 
exit
```

The output:

```
prj1
null
{
  "dependencies": {},
  "description": ""
}
```

So echo prj has value,
The 1st select don`t outputs anything.
The normal select outputs json.
PLEASE HELP

**Comment by nicowilliams** [comment]
You need to use this:

    $ jq --arg v "$PRJ_NAME" '.dev.projects.[$v]' config.json

I.e., `"$v"` doesn't do what you think.

**Comment by slapresta** [comment]
[This has already been asked on StackOverflow.](http://stackoverflow.com/questions/34745451/passing-arguments-to-jq-filter) You can close the issue here.
