### ISSUE TITLE
Building the jq from source

### ISSUE THREAD

**Issue by vpavlushkov** [stedolan/jq#1069]
Hi,

I was trying to build jq on my Debian 7.9 machine as described in https://stedolan.github.io/jq/download/ but I am getting error while running make:
~/jq$ make
make  all-am
make[1]: Entering directory `/home/victor/jq'
  CC     src/builtin.lo
src/builtin.c:1375:23: fatal error: builtin.inc: No such file or directory
compilation terminated.
make[1]: *** [src/builtin.lo] Error 1
make[1]: Leaving directory `/home/victor/jq'
make: *** [all] Error 2

All previous commands have succeeded with a warning that some Ruby libraries were not found and docs/tests would not be available, which is fine for me. I did use the flag '--disable-maintainer-mode' for configure, if that makes any difference.

Am I missing something simple? Thanks!

**Comment by nicowilliams** [comment]
I followed the build-from-source docs and building the 1.5 tarball worked for me.

**Comment by ripta** [comment]
@vpavlushkov I ran into the same error. Running `./configure` without `--disable-maintainer-mode` works for me, though. The option seems to [skip generating `src/builtin.inc`](https://github.com/stedolan/jq/blob/8f6f28c8d3fd6fb85439add3e812edeb5a887999/Makefile.am#L27).

**Comment by nicowilliams** [comment]
Oh, I see.  We need to have `src/builtin.inc` in `BUILT_SOURCES` even when using `--disable-maintainer-mode`.  (Or commit `src/builtin.inc`, though we'd rather not.)

**Comment by nicowilliams** [comment]
Thanks for the report.
