### ISSUE TITLE
builtin 'now' results too many digits

### ISSUE THREAD

**Issue by tommiatplayfish** [stedolan/jq#1071]
According to documentation, the 'now' should return epoch, in seconds. In my ubuntu 14.04 system it seems to return epoch and a lot of millis.

{ "timestamp": 1452740226.24755 }

This is a bit problematic, for example elasticsearch can only take 10 (seconds) or 13 (including millis) digits of epoch. Also if you want to output with millis, there should be no dot :)

**Comment by pkoppstein** [comment]
I don't quite understand any of the problems you describe. `now` returns the time as a floating point number, so 1.1 would mean 1.1 seconds (since the start of the Unix epoch).  If you want the whole number of seconds as a string, consider:

    jq -n ' now | tostring / "."| .[0]'  
    "1452746891"
If you want the number of milliseconds, notice that:

    jq -n 'now * 1000 | tostring / "."| .[0] | length'
    13

**Comment by nicowilliams** [comment]
$ jq -n 'now|floor'
    1452747462
    $
