### ISSUE TITLE
Piped jq and error handling

### ISSUE THREAD

**Issue by brandonrobertz** [stedolan/jq#1092]
I'm using jq in a unix pipe-based streaming process. The data coming in is sometimes flawed and it causes jq to exit with code 4. This kills the whole pipe and is forcing me to "fix" the data before it goes to jq. I've tried all kinds of shell hacks and am trying to find a way to get jq to essentially ignore the errors and continue processing from stdin. Short of hacking jq's error-handling routines (which is next on the list for me), is there a way to get jq to silently ignore bad JSON input?

**Comment by pkoppstein** [comment]
Here are two alternatives:

(1) The --seq option (as documented in the jq manual -- an extract is appended to this note);

(2) Use the technique described in the [FAQ ](https://github.com/stedolan/jq/wiki/FAQ)under the heading:

> Q: Is there a way to have jq keep going after it hits an error in the input file?

#############

(1) 
"Use the application/json-seq MIME type scheme for separating JSON texts in jq’s input and output. This means that an ASCII RS (record separator) character is printed before each value on output and an ASCII LF (line feed) is printed after every output. Input JSON texts that fail to parse are ignored (but warned about), discarding all subsequent input until the next RS. This more also parses the output of jq without the --seq option."

**Comment by brandonrobertz** [comment]
That does it. Thank you.
