### ISSUE TITLE
Filter from file crashes JQ if filename is 60 character or longer

### ISSUE THREAD

**Issue by gadton** [stedolan/jq#1094]
Sounds strange but JQ 1.5 on Win 7 crashes if I load a filter from file and the name of that file (including folders) is 60 character or longer.
`jq-win64.exe -f "D:\Alex\div\Bilder\Tools\PraesGen\.\prepareGPSInformation.jq"`
is one char too long.
The length of the command line (other parameter, ...) do not matter.

**Comment by pkoppstein** [comment]
The good news is that this problem has already been addressed (see #1072) and has been judged worthy of triggering the creation of a shiny new official release of jq.

The not-so-good news is that it hasn't happened yet, partly because of the question posed at #1072 as follows:

> Should we now make a 1.6 or a 1.5.1 release?
