### ISSUE TITLE
Accented characters can't be used in constructing key paths

### ISSUE THREAD

**Issue by frankhmiv** [stedolan/jq#1099]
Unable to query for JSON elements named with accented characters, such as é.

`[frank@manifold examples]$ jq '. | { category:.p.catégorie }' example_bad.json
jq: error: syntax error, unexpected INVALID_CHARACTER, expecting '}' (Unix shell quoting issues?) at <top-level>, line 1:
. | { category:.p.catégorie }                     
jq: 1 compile error

[frank@manifold examples]$ jq '. | { category:.p.categorie }' example_good.json
{
  "category": "BANK"
}

[frank@manifold examples]$ cat example_bad.json
{
  "p": {
    "catégorie": "BANK",
    "city": "Marseille"
  }
}%                                                                                                                                                       

[frank@manifold examples]$ cat example_good.json
{
  "p": {
    "categorie": "BANK",
    "city": "Marseille"
  }
}%                                                                                                                                                       

[frank@manifold examples]$ `

**Comment by pkoppstein** [comment]
From the jq manual:

>  The .foo syntax only works for simply keys i.e. keys that are all alphanumeric characters. .[<string>] works with keys that contain special characters such as colons and dots. For example .["foo::bar"] and .["foo.bar"] work while .foo::bar and .foo.bar would not.

**Comment by nicowilliams** [comment]
Some day it'd be nice to allow a much larger character repertoire for identifiers...  That requires care, as we may want to reserve quite a few characters for possible use as new operators.
