### ISSUE TITLE
Cannot parse keys that start with '#'

### ISSUE THREAD

**Issue by seanjohnsen** [stedolan/jq#1131]
jq is unable to get the value from the 'artist.#text' field (presumably) because it starts with '#'
```
{
  "artist": {
    "#text": "Belle and Sebastian",
    "mbid": "e5c7b94f-e264-473c-bb0f-37c85d4d5c70"
}
```

**Comment by pkoppstein** [comment]
See "Q: What alternatives are there to .["key"] for accessing the value of a key?" in the jq [FAQ](https://github.com/stedolan/jq/wiki/FAQ)
