### ISSUE TITLE
Segfault in capture with emoji

### ISSUE THREAD

**Issue by ashb** [stedolan/jq#1134]
So I found a wierd bug trying to parse a plain text file to produce json output (hence using JQ for it).

My use case was more complex but I managed to reproduce it down to this test case:

```
% echo "💩 " | jq -R 'capture(".")'
{}
% echo "💩 " | jq -R 'capture("(.)")'
Segmentation fault: 11
% jq --version
jq-1.5
```

Or a version that might be easier to paste/encode in a test:
```
echo $'\xf0\x9f\x92\xa9\x20' | jq -R 'capture("(.)")'
```

**Comment by pkoppstein** [comment]
Good news!  This bug has already been fixed:
```
$ echo $'\xf0\x9f\x92\xa9\x20' | jq -R 'capture("(.)")'
{}
$ jq --version
jq-1.5rc2-150-g1740fd0
```

Of course, in practice you're more likely to use capture/1 differently,
e.g. 
```
echo $'\xf0\x9f\x92\xa9\x20' | jq -R 'capture("(?<a>.)") | .a | explode'
[
  128169
]
```

**Comment by ashb** [comment]
Seems likely it would fix it, yes. Now we just need a new release :)

**Comment by pkoppstein** [comment]
@ashb wrote:

> Now we just need a new release :)

The most recent post in the #922 thread (dated Dec 2015) essentially says as much, and there have been other indications that there was an intention to create a new release "RSN". 

(@nicowilliams - If you're too busy, is this something that can delegated?)
