### ISSUE TITLE
Use jq as a scripting language

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [stedolan/jq#1143]
Hello

I would like to know how to write jq as a script. The same way I would do with a python or a bash script:

```
$ python script.py < content.json
$ ./script.py < content.json
```

I tried using an hashbang but jq tries to parse the content as json instead of a filter.

Thank you !

**Comment by slapresta** [comment]
Use `-f`, as in `jq -f myscript.jq mycontent.json`

**Comment by saldecoco** [comment]
RTFM: see the question _Can I use jq in the shebang line? Can a jq script be turned into an executable command?_ in the [FAQ](https://github.com/stedolan/jq/wiki/FAQ).

**Comment by GuillaumeLeclerc** [comment]
Sorry I searched the FAQ but for hashbang instead of shebang.

**Comment by chrisdonlan** [comment]
The hash-bang `#!/usr/bin/jq -f` should work.

**Comment by emanuele6** [comment]
Sine jq 1.6, you can also use the [`# \` trick](https://wiki.tcl-lang.org/page/exec+magic) à la tcl:

```jq
#!/bin/sh --
# \
exec jq -f "$0" -- "$@"

# jq code here
```

**Comment by nitsanavni** [comment]
one more option using `env`:
```jq
#!/usr/bin/env -S jq -nrf
"Hello world!"
```

**Comment by doronbehar** [comment]
Hey all, I too encountered the need to add the `-S` argument to `env`, and it wasn't pointed out in the FAQ. Here's my edit to the FAQ:

https://github.com/jqlang/jq/wiki/FAQ/_compare/10b8b89be9a88a0e7cfb6cb10593b198826cd50a...7772bfc9e35701f97f4535bd7bed0ae79e04f364

Comments / further edits are welcome.
