### ISSUE TITLE
AND and OR wonky semantics

### ISSUE THREAD

**Issue by jrdriscoll** [stedolan/jq#1147]
I tried to search for this, but didn't find anything, so I apologize in advance if this has been discussed before.

    $ jq -n 'true or empty'
    true
    $ jq -n 'empty or true'
    $

    $ jq -n ' false and empty '
    false
    $ jq -n ' empty and false '
    $

Ok, so I can understand that AND and OR are not necessarily abelian, e.g.

    $ jq -n ' "Boom!" | false and error '
    false
    $ jq -n ' "Boom!" | error and false '
    jq: error (at <unknown>): Boom!

    $ jq -n ' "Boom!" | true or error '
    true
    $ jq -n ' "Boom!" | error or true '
    jq: error (at <unknown>): Boom!
    $

But I'm not sure `empty` is like an error.  I was expecting `empty or true` to be `true`.

The "lazy" evaluation also causes the cross product behaviour to be a bit strange

    $ jq -n ' (true, false) or (false, false, false) '
    true
    false
    false
    false
    $

    $ jq -n ' (false, true) and (false, true, true) '
    false
    false
    true
    true
    $

which makes it hard to argue that the behaviour of empty is needed to make the cross product behaviour consistent.

Anyway, here is a simplified example of how this caused me a bunch of confusion:

    echo '
      {
        "data": "number1",
        "info": [
          { "source": "metric-1", "score": 50 },
          { "source": "metric-2", "score": 100 }
        ]
      }
      {
        "data": "number2",
        "info": [
          { "source": "metric-2", "score": 100 },
          { "source": "metric-3", "score": 500 }
        ]
      }
    ' | \
      jq '
        if 
          (.info[] | select(.source=="metric-1") | .score) > 0 or
          (.info[] | select(.source=="metric-2") | .score) > 0 or
          (.info[] | select(.source=="metric-3") | .score) > 0
        then .data else empty end
    '  
This only returns the first data item because the `select` of `metric-1` on the second data item returns `empty` and `empty` `or` anything is `empty`.

To get this to work properly, you need to do something like this

    if 
      ([.info[] | select(.source=="metric-1") | .score, -infinite] | max) > 0 or
      ([.info[] | select(.source=="metric-2") | .score, -infinite] | max) > 0 or
      ([.info[] | select(.source=="metric-3") | .score, -infinite] | max) > 0
    then .data else empty end

to avoid getting `empty` or multiple results.

**Comment by pkoppstein** [comment]
@jrdriscoll - The behaviors of jq's 'and' and 'or' that you describe are well-known and I believe adequately documented, though perhaps the utility of `//` in this context would be worth highlighting.

Consider, for example:

   def Or(a;b): (a//null) or (b//null);

With this definition, `Or(empty; 1)` evaluates to `true`.  Note, however, that `empty | Or(.; 1)` produces the empty stream (as expected).

Please also note that you are free to define your own variants of `and`, `or`, and `if/then/else`; for example, if you want a non-boolean version of "or" that works on arrays, consider:

    def OR: reduce .[] as $v (false; . // $v);

With this definition, [empty,1,2,3] yields 1.

Here is a very useful variant of "if":

    def when(filter; action): if filter?//null then action else . end;

**Comment by jrdriscoll** [comment]
I only bring this up because I very much like the clean semantics of jq.  I am increasingly using it in production systems in preference to other scripting languages.

I think I am legitimately surprised at the actual semantics given the documentation.   

>  false and null are considered “false values”, and anything else is a “true value”.

While it is true that the algebra is simplified by collapsing non-null values onto true or false, the actual algebra is not boolean, but a wonky (in my view) non-abelian algebra over `{true, false, empty, error}`.

> If an operand of one of these operators produces multiple results, the operator itself will produce a result for each input.

This is not true as `(true, false) and empty` produces the single result `false`.

The cross product example in the documentation `(true, true) and (true, false)` could almost be considered misleading as it is one of the few cases where the result is actually the full cross product.

The documentation does not mention that the arguments are evaluated lazily, and in particular, does not mention the surprising (to me at least) role of `empty` in the lazy evaluation.

**Comment by pkoppstein** [comment]
Setting aside the question of whether the documentation can be significantly improved without making it more complex, the key point is that "empty" is not a value, but the absence of a value.  That's why I mentioned that `empty | (.//null)` is different from `(empty//null)`.  Similarly, `error` should not be construed as a value (and certainly not as a JSON value).  

In my view the documentation could probably be tweaked a bit to make it clearer earlier on that jq is fundamentally about streams of JSON values.  At any rate, it seems to me that if you read the documentation with that in mind, things should be much clearer.

By the way, in case it's not obvious to whoever is reading this, `(true, false) and empty` reduces to the stream `(true and empty), (false and empty)`, which (by virtue of the short-circuit semantics of 'and') reduces to `empty, false`, i.e. the single-element stream: `false`.

**Comment by jrdriscoll** [comment]
All I have left to say is [WAT!](https://www.destroyallsoftware.com/talks/wat).
