### ISSUE TITLE
Using `def` changes the input?

### ISSUE THREAD

**Issue by fadado** [stedolan/jq#1151]
Defining a function to replicate strings (I know `s * n` will do a similar  work) I discovered an estrange behavior. This first case works as expected:

    $ jq -n 'def repl(s; n): reduce [range(n) | s][] as $t (""; . += $t);  repl("abc"; 3)'
    "abcabcabc"

But using the dot fails:

    $ echo '"abc"' | jq 'def repl(s; n): reduce [range(n) | s][] as $t (""; . += $t) ;  repl(.; 3)'
    jq: error (at <stdin>:1): string ("") and number (0) cannot be added

Using tostring you see what happens:

    $ echo '"abc"' | jq 'def repl(s; n): reduce [range(n) | s][] as $t (""; . += ($t|tostring)) ;  repl(.; 3)'
    "012"

If you save the input before defining the function the behavior is also the expected:

    $ echo '"abc"' | jq '. as $x | def repl(s; n): reduce [range(n) | s][] as $t (""; . += ($t|tostring)) ;  repl($x; 3)'
    "abcabcabc"

Is this a bug or using `def`  changes the input?

**Comment by fadado** [comment]
**SOLVED!**

In the definition of `repl` I must use a `$` valued argument!

    $ echo '"abc"' | jq 'def repl($s; n): reduce [range(n) | $s][] as $t (""; . += $t) ;  repl(.; 3)'
    "abcabcabc"

**Comment by pkoppstein** [comment]
@fadado - The issue here was that in the original definition of repl, you had 'range(n) | s', so if "s" is "." then this becomes, in effect, 'range(n) | .'.  

By the way, a simpler (and faster) definition of `repl` would be:

    def repl($s; n): reduce range(n) as $i (""; . + $s) 

For anyone reading this who is using a version of jq that does not support dollar-prefixed arguments in defs, here is a more generic definition:

    def repl(s; n): s as $s | reduce range(0;n) as $i (""; . + $s) ; 

To avoid reduce:

    def repl(s;n): s as $s | [range(0;n)|$s] | add;

**Comment by nicowilliams** [comment]
@fadado: `.` is not the `.` you expect!

Function arguments are *closures* so a function argument expression that consists of `.` will output whatever is given to it where the function body calls that argument closure.

This can be confusing, certainly.
