### ISSUE TITLE
how to disable the jq log

### ISSUE THREAD

**Issue by chenxing12** [stedolan/jq#1152]
when I use jq, it will print log, how config it disable log?
` % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
126   409  102   409    0    98   1423    341 --:--:-- --:--:-- --:--:--  4442
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
124   374  124   374    0     0    240      0  0:00:01  0:00:01 --:--:--   277
`

**Comment by chenxing12** [comment]
![jq](https://cloud.githubusercontent.com/assets/11866078/15316317/3ffeabaa-1bd1-11e6-9db9-7af632e62446.png)

**Comment by saldecoco** [comment]
This looks like `curl` output. Simply ask `curl`to be silent:

    curl --silent ... | jq ...
