### ISSUE TITLE
brew install failed

### ISSUE THREAD

**Issue by e9485111** [stedolan/jq#1154]
$ brew install jq
==> Downloading http://stedolan.github.io/jq/download/source/jq-1.4.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "jq"
Download failed: http://stedolan.github.io/jq/download/source/jq-1.4.tar.gz

**Comment by slapresta** [comment]
Run `brew update`, then try again.

**Comment by e9485111** [comment]
It works, thanks!

**Comment by nikitavoloboev** [comment]
I believe `brew install jq` installs something else.

Because running `jq` on some JSON file I get this : 

```
jq triggers.json
jq: error: triggers/0 is not defined at <top-level>, line 1:
triggers.json
jq: 1 compile error
```
