### ISSUE TITLE
latest version for ubuntu 14.04 is v1.3

### ISSUE THREAD

**Issue by rubensayshi** [stedolan/jq#1164]
http://packages.ubuntu.com/trusty/jq

is it possible to update these, would be really awesome <3 !

**Comment by cristovaov** [comment]
Would love to see the package updated. A workaround for now is:   
```
curl -O -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
chmod +x jq-linux64
sudo mv jq-linux64 /usr/bin/jq
```

**Comment by dequis** [comment]
The jq developers have no control over ubuntu packages. Close this and open a bug in ubuntu's bug tracker instead to request a backport.

See https://launchpad.net/ubuntu/+source/jq

Also, note that it's part of ubuntu's policy to not include any updates other than critical bugfixes in the main repositories of stable releases, even more in the case of LTS. The backports repository is more relaxed, and includes 1.4 according to the link. But in the general case, if you want newer versions of things, get newer releases (such as 16.04).

**Comment by zstadler** [comment]
The current [download documentation](https://stedolan.github.io/jq/download/) is somewhat misleading as it says:

> jq 1.5 is in the official [Debian](https://packages.debian.org/jq) and [Ubuntu](http://packages.ubuntu.com/jq) repositories. Install using `sudo apt-get install jq`.

while the jq version in the repositories depends on the specific Debian and Ubuntu releases.

Pull request https://github.com/stedolan/jq/pull/1536 created for updating the documentation.
