### ISSUE TITLE
Rename a key in an object

### ISSUE THREAD

**Issue by edi9999** [stedolan/jq#1167]
How is it possible to rename a key ?

Say I have : 

'{"long_message" : "Foo bar baz"}'

and I'd like to have 

'{"msg" : "Foo bar baz"}'

Is this achievable with jq ?

**Comment by pkoppstein** [comment]
Suppose you have an arbitrary object, obj, which is known to contain a key, "from", and is also known not to contain the key "to".  To rename "from" to "to", you could use the filter:

    . + {"to": .from} | del(.from)

This could of course be abstracted into a new jq filter.

To rename a key programmatically, you could use with_entries, e.g.

    with_entries( if .key | contains("-") then .key |= sub("-";".") else . end)

**Comment by edi9999** [comment]
Thanks !

**Comment by JordanSimba** [comment]
This is solutions works, but can it be generalised to a key with multiple hyphens?
foo-bar-x -> foo_bar_x
I've come across a use case where one service enforces hyphen in names but bash does not seem to support this.

**Comment by piegamesde** [comment]
The FAQ link is dead

**Comment by pkoppstein** [comment]
@piegamesde - The link is now alive.
