### ISSUE TITLE
is there a way to make `jq` print each key with the length of its respective values?

### ISSUE THREAD

**Issue by evandrix** [stedolan/jq#1171]
For instance,
   input: {"k1":[1,2,3], "k2":[4,5], "k3":[6]}
   output: {"k1":3, "k2":2, "k3":1}

**Comment by evandrix** [comment]
nvm, i've got it: `jq -r '. as $o|keys|map([.,($o[.]|length|tostring)]|join("\t"))[]'`

**Comment by slapresta** [comment]
@evandrix To obtain the output on your original post, you can just do `jq 'map_values(length)'`. If you want tab-separated records as in your final answer, try `jq -r 'to_entries[] | "\(.key)\t\(.value | length)"'`.

**Comment by pkoppstein** [comment]
Consider also:
```
    $ jq -c 'with_entries(.value |= length)'
    {"k1":[1,2,3], "k2":[4,5], "k3":[6]}
    {"k1":3,"k2":2,"k3":1}
```

**Comment by evandrix** [comment]
oh wow! thanks!
