### ISSUE TITLE
Equivalent to SELECT * FROM a WHERE a.key IN ("some", "list", "of", "values")

### ISSUE THREAD

**Issue by luolong** [stedolan/jq#1187]
I can't really explaion it any cleaner than the subject line of this issue.

I want to select a set of objects based on the value of a key.

I know that the conventional syntax for this is:

```jq
.devices[]|select(.type = "somevalue")
```

But what if I want to select objects that any value in a set (an array?) of values?

In short, how do I write an equivalent of an SQL query in jq:
```sql
SELECT * FROM devices WHERE type IN ("some", "list", "of", "values")
```

I've tried using `in` operator, but time and again, I've found out that it does not quite work like this:
```jq
.devices[]|select(.type in ["some", "list", "of", "values"])
```

I am probably missing something really simple here, but I can't really figure out what... I keep stumbling on this problem...

**Comment by slapresta** [comment]
You can use `index`, which is like JS's `indexOf`. So, if you have something like:

```json
[{"type": "a", "value": 1}, {"type": "b", "value": 2}, {"type": "c", "value": 3}]
```

And you want to get an array of those elements where `type` is in `["b", "c", "d"]`, you can do:

```
map(select(.type as $type | ["b", "c", "d"] | index($type)))
```

Hope this helps!

**Comment by luolong** [comment]
it has to ... although I was hoping for something simpler ... ah well
