### ISSUE TITLE
How is input_line_number meant to be used?

### ISSUE THREAD

**Issue by nkgm** [stedolan/jq#1193]
Trying `"\(input_line_number) \(.[])"` on this json input:

``` json
[
    1,
    2,
    3
]
```

I may have this all figured out wrong, but I was expecting:

```
"2 1"
"3 2"
"4 3"
```

Instead I get:

```
"4 1"
"4 2"
"4 3"
```

**Comment by nkgm** [comment]
Fast forward 2 years later I bump into my own question and now I have an answer. It appears `input_line_number` is meant to be used with `--raw-input/-R`.

**Comment by pkoppstein** [comment]
`input_line_number` is meaningful whether or not used with the `--raw-input/-R'  option.  When used without `-R', it simply yields the line number of the last character of the current JSON text being read, it being understood that the counter is not reset when reading from multiple files.

**Comment by nkgm** [comment]
> it simply yields the line number of the last character of the current JSON text being read

That was my original observation, but I wasn't sure if it was the original intent, or a mere by-product (seeing there's not much in the manual to go by).
