### ISSUE TITLE
Question: Can functions be stored in local config/rc file?

### ISSUE THREAD

**Issue by fearphage** [stedolan/jq#1195]
I know it's possible to define custom functions in `jq`. However, I would like to author functions that probably shouldn't be a part of the stdlib, but I'd like to share them with my team. 

Is there a config file or rc file I can create to get jq to pull in my local functions? I know the alternative to this is just to create an alias. I'm just wondering if this currently possible or if not if something like this might make it onto the roadmap.

**Comment by fearphage** [comment]
Found it.

**Comment by nrobert13** [comment]
@fearphage would you mind sharing the solution?

**Comment by emanuele6** [comment]
@nrobert13 don't directly mention a user after more than 6 years to ask a question that literally anybody could answer...

Check the "MODULES" section of the manual page. It will say "If "$HOME/.jq" is a file, it is sourced into the main program.".

**Comment by nrobert13** [comment]
sorry, thanks for the hint. I thought it would make sense to have the question answered, once it's here.
