### ISSUE TITLE
Support for custom key and value names in `from_entries`

### ISSUE THREAD

**Issue by rymndhng** [stedolan/jq#1220]
I'm wondering if it's possible to add support for named keys to use in `from_values` when the JSON array does not use `key`, `Key`, `name`, `Name`.

**Comment by slapresta** [comment]
You can just perform the transformation beforehand: `map({key: .bacon, value: .lettuce}) | from_entries`.

I'm not sure how something like `from_entries("bacon"; "lettuce") would make it any easier, although I guess it could be useful in some cases.

**Comment by rymndhng** [comment]
That's fair. It didn't cross my mind to compose the functions that way. Seems like a nifty trick to share :)
