### ISSUE TITLE
Having a problem with OSX and the binary 1.5

### ISSUE THREAD

**Issue by davesnx** [stedolan/jq#1230]
Hello guys,

I'm getting a problem and I'm not sure how to continue to investigate what I'm doing wrong.

I create a node wrapper around `jq`(called [node-jq](https://github.com/sanack/node-jq)) and now I'm implementing on build time to download the binary depend on each SO and put it inside `node_modules/.bin`, for who isn't familiar with NodeJS world is where the package manager (npm) locates the binaries from the dependencies.
The idea behind is to not have `jq` installed in the system globally, just inside the node-jq dependencies.

So... all the stuff seems pretty straight forward, but I found an issue that stops me.
Once I download the binary and I change the permissions I can't make it running getting a 

```bash
→ node_modules/.bin/jq . package.json
zsh: exec format error: node_modules/.bin/jq
```

or binary isn't executable, etc.

and then I suppose that I download the incorrect version of the binary, but in the jq-1.5 there's only the 64bits arch.

I'm using Mac OSX 10.10 running on 64bits, and actually, If I'm running jq from `/usr/local/bin` works perfectly fine. 

My question is, I'm missing something about the permissions?
I'm downloading the correct architecture? Could be a bug?

Thanks for reading all of this and thanks for maintaining such a great tool like `jq` 👍 

[Here](https://github.com/sanack/node-jq/pull/41) is all the code, If you're curious.

**Comment by davesnx** [comment]
Any idea @slapresta ?

**Comment by slapresta** [comment]
Not really... What's the output of `file node_modules/.bin/jq`? I'm thinking maybe you're not really downloading the binary for some reason (a HTTP redirect not being followed?)

**Comment by davesnx** [comment]
Isn't related with jq, sorry guys!
