### ISSUE TITLE
Feature request: a place to put user-defined functions

### ISSUE THREAD

**Issue by maxrothman** [stedolan/jq#1231]
Since most jq programs are written ad-hoc, it'd be helpful to have a place to store common snippets as functions I can re-use later. There is a module system, but using imports is clunky for this use-case. A reasonable place to put them might be a module in a standard file location, e.g. `~/.jqrc` or `~/.jqconfig` which gets imported automatically.

**Comment by pkoppstein** [comment]
jq 1.4 and 1.5 both check whether ~/.jq is a file, and if so, read it in.

**Comment by maxrothman** [comment]
Oh! Great. I couldn't find any reference to that in the documentation. Could it be updated?

**Comment by pkoppstein** [comment]
The jq manual already does document the .jq feature -- specifically, the development version says:

    If “$HOME/.jq” is a file, it is sourced into the main program.

**Comment by maxrothman** [comment]
Ah, I see. Since it was at the end of a section talking about how to include modules, and because the previous example referred to `.jq` as a directory, I didn't realize that you didn't have to _tell_ jq to include that file.
