### ISSUE TITLE
How should I refer to an arg as the LHS of a new object? [1.3] [args]

### ISSUE THREAD

**Issue by jpluscplusm** [stedolan/jq#1236]
I can't grok how to use an arg set via `--arg` as the left hand side of a new object.  I _think_ I understand the generic object construction syntax, but it seems to bomb when using args.

(I'm constrained to v1.3 For Reasons, so I'd _really_ like to learn how to do this without forcing an upgrade - as annoying as that is!)

``` shell
~$ jq --version
jq version 1.3
~$ echo '{"foo":{"bar":"baz"}}' | jq --arg toplevel "TOP" '{ $toplevel: .foo }'
error: syntax error, unexpected '$'
{ $toplevel: .foo }
  ^
1 compile error
~$ echo '{"foo":{"bar":"baz"}}' | jq --arg toplevel "TOP" '{ TOP: .foo }'
{
  "TOP": {
    "bar": "baz"
  }
}
```

I'd expect both outputs to be the same - what am I missing?

**Comment by pkoppstein** [comment]
1.  Good news!  You just need parentheses around the key name when it is presented as anything but a string:
```
   echo '{"foo":{"bar":"baz"}}' | jq --arg toplevel TOP '{ ($toplevel): .foo }'
    {
      "TOP": {
        "bar": "baz"
      }
    }
```
2. In future, please ask usage questions at stackoverflow.com
