### ISSUE TITLE
How can I list sub-key names within a main-key?

### ISSUE THREAD

**Issue by haodong** [stedolan/jq#1242]
I've searched the manual and git repo and really have no clue.

eg.

```json
{
  "date": "2016-09-24",
  "students": {
    "John": "00001",
    "King": "00003",
    "Micheal": "00004",
    "Ashley": "00002"
  },
  "teacher": "David"
}
```
I'd like to output `"John", "King", "Micheal", "Ashley"`, any form is acceptable.
Thanks!

**Comment by pkoppstein** [comment]
1. In future, please ask usage questions at https://stackoverflow.com/questions/tagged/jq

2. If you read up on "keys" in the manual or the [FAQ](https://github.com/stedolan/jq/wiki/FAQ),  you should be able to figure it out yourself.

3. There are similar questions on stackoverflow - have you googled 'site:stackoverflow.com jq keys' ?

4. Hint: `.students | keys`

**Comment by haodong** [comment]
Thanks.
Actually, I have found [this post](http://stackoverflow.com/questions/23118341/get-key-names-from-jq-json-unix-command), it seems that I can figure it out by myself if I do more research.
