### ISSUE TITLE
join two json files based on common key

### ISSUE THREAD

**Issue by s3c1t** [stedolan/jq#1247]
I have 2 json files with common key and I need to JOIN them As follows:
(for example:  jq -join -key "id" jsonFile1 jsonFile2)

jsonFile1:
{"id":"10","data":"abc"}
{"id":"20","data":"xyz"}
{"id":"30","data":"qwe"}
{"id":"40","data":"wsx"}
{"id":"50","data":"zxc"}

jsonFile2:
{"id":"60","content":"ert"}
{"id":"40","content":"tgb"}
{"id":"10","content":"yui"}
{"id":"30","content":"ujm"}
{"id":"70","content":"rfv"}

output:
{"id":"10","data":"abc","content":"yui"}
{"id":"30","data":"qwe","content":"ujm"}
{"id":"40","data":"wsx","content":"tgb"}

**Comment by pkoppstein** [comment]
This has been asked (and already has two answers) at https://stackoverflow.com/questions/39826489/a-way-for-jq-to-output-paths-in-a-way-itself-can-read

**Comment by pkoppstein** [comment]
The `join` defined at https://github.com/stedolan/jq/issues/1475 is an outer join but can be used to solve the problem at hand, as shown below.

The following assumes that:
* the definition of join/1 mentioned above is in ~/.jq/jq/jq.jq; and
* EITHER your version of jq already defines INDEX, OR that jq.jq includes its definition.

```
$ jq -c -s 'include "jq"; join(.id)' <(jq -s . file1.json) <(jq -s . file2.json)
{"id":"10","data":"abc","content":"yui"}
{"id":"20","data":"xyz"}
{"id":"30","data":"qwe","content":"ujm"}
{"id":"40","data":"wsx","content":"tgb"}
{"id":"50","data":"zxc"}
{"id":"60","content":"ert"}
{"id":"70","content":"rfv"}
```
To filter out the incomplete rows, one could select(length==3):
```
$ jq -c -s 'include "jq"; join(.id) | select(has("data") and has("content"))' <(jq -s . file1.json) <(jq -s . file2.json)
{"id":"10","data":"abc","content":"yui"}
{"id":"30","data":"qwe","content":"ujm"}
{"id":"40","data":"wsx","content":"tgb"}
```

**Comment by Smile4ever** [comment]
See also https://stackoverflow.com/questions/49037956/how-to-merge-arrays-from-two-files-into-one-array-with-jq/
