### ISSUE TITLE
echo pipe to jq to file

### ISSUE THREAD

**Issue by Dekken** [stedolan/jq#1253]
Hey, this is probably answered somewhere already, but how can I get the following to work?

echo '{"json":"value"}' | jq  > file

I use jq to format/validate JSON strings, and it's not always feasible to copy from a terminal.

Thanks

**Comment by slapresta** [comment]
Use `jq .` instead of `jq`.

**Comment by Dekken** [comment]
thanks, I figured it had to be something simople!

**Comment by rzr** [comment]
IHMO, in non interactive mode it would make sense to set -M and . filter by default

**Comment by nicowilliams** [comment]
@rzr If we ever touch this again it will be to make a program (`.`, whatever) an absolute requirement whether you're using pipes or ttys.
