### ISSUE TITLE
truncate_stream works only with 0 or 1 as input

### ISSUE THREAD

**Issue by shokoe** [stedolan/jq#1263]
This works as expected:
`jq -n '[{foo:"bar"},{foo:"baz"}]' | jq -cn --stream 'fromstream(1|truncate_stream(inputs))'`
Output:
`{"foo":"bar"}`
`{"foo":"baz"}`

These two give empty output:
1. `jq -n '{"jo":[{foo:"bar"},{foo:"baz"}]}' | jq -nc --stream 'fromstream(2|truncate_stream(inputs))'`
2. `jq -n '{"mo":{"jo":[{foo:"bar"},{foo:"baz"}]}}' | jq -nc --stream 'fromstream(3|truncate_stream(inputs))'`

Expected output for both commands is the same as the working example.
Tested on version 1.5.

**Comment by JeffreyMercado** [comment]
This one seems to have been fixed by commit dc679081fa770c260ca9a569a8a4fdbb10bcdc20.
