### ISSUE TITLE
addons.mozilla.org (AMO) API

### ISSUE THREAD

**Issue by davidhedlund** [stedolan/jq#1268]
How do I play with https://addons.mozilla.org/api/v3/addons/addon/noscript/ for example?

I could not use the [jq tutorial](https://stedolan.github.io/jq/tutorial/) for this.

**Comment by pkoppstein** [comment]
The first two lines are most likely the cause of whatever difficulty you're experiencing.  jq can read text or JSON, but it is usually more trouble than it's worth to try using jq to read JSON-with-comments directly.   In other words, you might have to figure out how to remove those first two lines.  (In a pinch, that could be done using jq, but there is almost surely a better way.)

For future reference, please use stackoverlow.com (with the `jq` tag) for jq usage questions.  These "issues" pages are mainly for bug reports and specific enhancement requests.  A request for jq to support JSON-with-comments has already been made (#402) and (for better or worse) denied :-(

**Comment by davidhedlund** [comment]
> The first two lines are most likely the cause of whatever difficulty you're experiencing. jq can read text or JSON, but it is usually more trouble than it's worth to try using jq to read JSON-with-comments directly. In other words, you might have to figure out how to remove those first two lines. (In a pinch, that could be done using jq, but there is almost surely a better way.)

I don't find any comments (/**/) in https://addons.mozilla.org/api/v3/addons/addon/noscript/

> For future reference, please use stackoverlow.com (with the jq tag) for jq usage questions. These "issues" pages are mainly for bug reports and specific enhancement requests. A request for jq to support JSON-with-comments has already been made (#402) and (for better or worse) denied :-(

Thank you for pointing me to the right forum, I will.

**Comment by davidhedlund** [comment]
This was useful:

> cat noscript.json | jq '.name' | grep "en-US" | cut -d "\"" -f 4

**Comment by davidhedlund** [comment]
This works
> cat noscript.json | jq '.name.es'
> "NoScript"

but "-" mess it up
> cat noscript.json | jq '.name.en-US'
> error: US is not defined

**Comment by davidhedlund** [comment]
* https://github.com/stedolan/jq/issues/341

**Comment by uzairlakho107-ctrl** [comment]
Thanks for the clarification and for pointing them to the right place. Having dedicated resources for troubleshooting always makes technical issues easier to resolve. I also like using Instatroid for technology guides and practical tips on software and development topics: https://instatroid.net/
