### ISSUE TITLE
Need option to return jq status code, considering null and false might be valid return values

### ISSUE THREAD

**Issue by fatbearinc** [stedolan/jq#1272]
I've posted a question on stackoverflow:

http://stackoverflow.com/questions/40513044/how-can-it-be-determined-if-a-jq-selector-succeeds-or-fails-given-null-or-false

In short, the -e option is not reliable to tell whether an error happens for a given selector because false and null can be valid return values.  For example:

jq -re .key <<<'{"key":false}'
jq -re .key <<<'{"key":null}'

Both of the above have a return status of 1. This is misleading for those cases in which one wants to know an actual error happened. Returning a valid result should not be accompanied by a non-zero return code.

Because -e has established meaning, can a new option be added so that only in the case of an actual error will a non-zero return value be returned?

**Comment by thedward** [comment]
Why are you using the `-e` option if you don't want a final value of `null` or `false` to make jq exit with a status of `1`? That is literally the exact purpose of that option.

Without the `-e` option the default behavior is to exit with a non-zero exit status on an error.

If your basic concern is that the two examples below produce the same result, then probably need to think a little bit more about the problem you are trying to solve.

```{.bash}
jq .key <<<'{"key":null}'
```

```{.bash}
jq .key <<<'{}'
```

In jq, trying to retrieve a value via a nonexistent key is not an error (unless you tell jq any final value of `null` or `false` is an error via the `-e` option).

If you want jq to exit with a non-zero status when trying to retrieve a value with a nonexistent key, then you can define a custom function:

```{.jq}
def get($k): if has($k) then .[$k] else error("invalid key") end;
```

Then put it in your `~/.jq` file and use it like this:

```
$ jq -r 'get("key")' <<<$'{"key":null}' ; echo $?
null
0
$ jq -r 'get("key")' <<<$'{}' ; echo $?
jq: error (at <stdin>:1): invalid key
5
```

(and you don't even need the `-e` option)

**Comment by fatbearinc** [comment]
Thanks for the thought. I just looked at the manual and the error(message) does not provide an example.

I originally started using jq -e because idioms such as:

jq '.key' <<<'{}'

return success. But, when I use the -e option, I get the wanted error return status.

Then, of course, I ran into the problems of dealing with results of false and null and error return status codes.

My problem is that I want a generic solution to the problem so that I can have a central Bash function that takes jq selectors and returns 0 if the selector succeeds and returns 1 if the selector fails.

Consider this computational selector:

```
% jq '.[]|select(.CheckId|startswith("serfHealth"))|.Status' <<< '[
{ "CheckId":"serfHealth", "Status": false },
{ "CheckId":"service:postgres", "Status": true }
]'
false
%
```

The above has a result of false and should have a 0 return status code. Doing it without the -e gives the wanted 0 return status code, but as I've mentioned, it is necessary to use the -e option to deal with selectors such as selecting non-existent keys.  In general, I'm calling a Bash function "Select" as:

Select "<jqSelector" "<bashVariable>"

This function has access to the JSON input data already. The <jqSelector> that is being passed in has already been constructed elsewhere in my code, so the actual invocation is like:

if Select "$selector" result ; then
   do something with the result
else
   the result variable contains the error message from the bad jq selector
fi

If the error() function can be used to alleviate this general problem, can you show me using the generic selector "$selector" in a Bash program how this is done?

**Comment by fatbearinc** [comment]
All I need to know is whether a given jq filter pulls data out of a JSON data structure or not. The JSON data can contain values: `null, "", false, 0`, etc.  Without knowing the filter details, is there any way for me to know whether the jq result is explicitly found in the input JSON data?

**Comment by nicowilliams** [comment]
We may need a `has_path(path_expr)` sort of builtin for this...

**Comment by pkoppstein** [comment]
def has_path(path_expr): any( paths; . == path_expr )

**Comment by nicowilliams** [comment]
@pkoppstein Well, `path(..?)` gives you all paths...

We can code `has_path` in an unsatisfactory way like so:

    def has_path(p): any(p == path(..?));

Just like you wrote.   But what I'd like is to be able to write `has_path(.a.b.c.d)` rather than having to write `has_path(["a","b","c","d"])`.  Ah!!  We do have a `has_path`: `path(.a?.b?.c?.c?)` does the right thing in that it produces `empty` (no results) if the path doesn't exist.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> path(..?) gives you all paths

Perhaps you forgot that currently it doesn't produce path to null, which of course is the raison d'etre for `allpaths`:
```
$ jq -nc '{a:{b:{c:null}}} | paths(..?)'
["a"]
["a"]
["a","b"]
```

This works:

```
def haspath(dotpath):
  (null | path(dotpath) ) as $p
  |  any( allpaths ; . == $p ) ;
```

**Comment by nicowilliams** [comment]
That's very elegant, though I'm sad about the need for `allpaths`.  I don't think we can change `path()` as to paths that end in `null`, not now.

**Comment by pkoppstein** [comment]
Two questions to ponder:

1. Other discussions have highlighted the need for the functionality of`allpaths` but of course it could be named something else, or we could (for example) define `paths/1` in such a way that `paths(true)` (for example) provides the desired functionality. 

2.  Should `conditional_recurse` be a top-level function?

**Comment by nicowilliams** [comment]
I'd like to understand why `path/1` does not output paths to null values first.  If we can produce a version that does not have that problem, then we can make `has_path/1` more efficient.

**Comment by nicowilliams** [comment]
@pkoppstein 

Ah, the issue is just with `..` and `..?`, and thus with `recurse/0` (`..` becomes a call to `recurse`), rather than with `path/1`.  Perhaps we could say that's a bug we could fix...

BTW, these are the definitions of `recurse` in jq:

    # recurse
    def recurse(f): def r: ., (f | select(. != null) | r); r;
    def recurse(f; cond): def r: ., (f | select(cond) | r); r;
    def recurse: recurse(.[]?);
    def recurse_down: recurse;

Note the similarity to (and subtle difference with) your `conditional_recurse`.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> the issue is just with .. and ..?

I'm not sure what you have in mind, as:
```
jq -nc '{a:{b:{c:null}}} | ..'
{"a":{"b":{"c":null}}}
{"b":{"c":null}}
{"c":null}
```

**Comment by nicowilliams** [comment]
@pkoppstein Yeah, but try it with `path(..)`:

    $ jq -cn '{a:{b:{c:null}}}|(.a.b.c,path(.a.b.c),[..],path(..))'
    null
    ["a","b","c"]
    [{"a":{"b":{"c":null}}},{"b":{"c":null}},{"c":null}]
    []
    ["a"]
    ["a","b"]
    $

**Comment by nicowilliams** [comment]
@pkoppstein And, actually, the example you showed shows that `..` is broken.  This is what we get now:

```
jq -nc '{a:{b:{c:null}}} | ..'
{"a":{"b":{"c":null}}}
{"b":{"c":null}}
{"c":null}
```

and this is what we should get:

```
jq -nc '{a:{b:{c:null}}} | ..'
{"a":{"b":{"c":null}}}
{"b":{"c":null}}
{"c":null}
null
```

**Comment by nicowilliams** [comment]
The fix for `..` seems to be:

```
-def recurse(f): def r: ., (f | select(. != null) | r); r;
+def recurse(f): def r: ., (f | r); r;
```

Doesn't break any tests.  Elides the need for `allpaths`, which makes me happy :).

**Comment by nicowilliams** [comment]
Here's a version of `has_path()` that is efficient and depends on `..` being corrected as above:

```
def has_path(p):
  first(
    (path(p) as $p |
    if ($p|length == 0) then false
    elif ($p|length == 1) then has($p[0])
    elif getpath($p[0:-1])|has($p[-1]) then true
    else false end|select(.)),false);
```

Not necessarily very elegant, but efficient.  And it works.

Now, maybe, just maybe, the C function `jv_has()` ought to behave like the above when the `k` argument is an array.  Or maybe we could have a C-coded `jv_has_path()`.

**Comment by pepasflo** [comment]
> All I need to know is whether a given jq filter pulls data out of a JSON data structure or not. The JSON data can contain values: `null, "", false, 0`, etc. Without knowing the filter details, is there any way for me to know whether the jq result is explicitly found in the input JSON data?

I just wanted to check if there has been any update to this.  Is it possible to just pass a single command line option which causes `jq` to exit non-zero if it doesn't find a match?  That would be tremendously useful for shell scripting.

**Comment by nicowilliams** [comment]
You can use the `-e` / `--exit-status` option, or the `halt_error` builtin.

**Comment by robinbowes** [comment]
I've recently hit a use-case where I'd like `jq` to raise an error if any of the specified json paths are not found.

I want to validate a json file, and make sure specific fields are present.

For example:

```
{
  "name": "foo",
  "repo_directory": "profiles/customer",
  "repo_identifier": "example/security_groups",
  "tags": {
    "cloud": "aws",
    "region": "ap-northeast-1",
    "service": "security_groups",
    "site": "aws-tokyo",
    "stage": "development",
    "vpc_code": "customer"
  },
  "variables": {
    "cloud": "aws",
    "cost_center": "RnD",
    "region": "ap-northeast-1",
    "service": "security_groups",
    "site": "aws-tokyo",
    "ssm_region": "us-east-1",
    "stage": "development",
    "vpc_code": "customer"
  }
}
```

I'm doing something like this:

```
mandatory_elements=(
  .name
  .repo_directory
  .repo_identifier
  .tags.cloud
  .tags.cluster
  .tags.region
  .tags.service
  .tags.site
  .tags.stage
  .tags.vpc_code
  .variables
)
declare -a output=()
for element in "${mandatory_elements[@]}" ; do
  if ! jq --exit-status "$element" < "$file" >/dev/null; then
    output+=("$file is missing mandatory element '$element'.")
  fi
done
printf '%s' "${output[*]}"
```

It would be really helpful to be able to check for all elements at the same time with something like this:

```
script=$(IFS=, ; echo "${mandatory_elements[*]}")
if ! jq --exit-status "$script" < "$file" ; then
   # check each item individually using the previous code
fi
```

Is there any way to do that currently, or would you consider adding a "missing item throws an error" option?

**Comment by ChillerDragon** [comment]
> or would you consider adding a "missing item throws an error" option?

I would love to see that option. Having a error message saying "can not access x" and failing with non zero exit code instead of returning null would be nice to have in some scenarios.
