### ISSUE TITLE
Convert output to JS object literal?

### ISSUE THREAD

**Issue by ryexley** [stedolan/jq#1273]
jq is a fantastic tool...I've found it very useful, and am very grateful for it. However, there is one use case that seems very simple, but I've not been able to figure out how to do this. I would love to be able to take whatever output I get and return it as a JS object literal, rather than JSON. So, literally just taking the output JSON and run it through `JSON.parse`. Am I missing something? Is there an easy way to do this that I'm just not finding?

**Comment by slapresta** [comment]
A JSON is [(almost)](http://timelessrepo.com/json-isnt-a-javascript-subset) always a valid JS object literal. I'm not sure if I follow. What would be the expected output?

**Comment by ryexley** [comment]
Yeah, sorry...I should've been more clear. I'm talking about an object that will pass linter tests. Primarily, when running `JSON.parse` against a simple JSON object, the result will at very least have the quotes stripped off of the keys that don't need them. That's what I'm looking for.

As an example...given this JSON output:

```json
{
  "one": 1,
  "two": "TWO",
  "three": "threeeeee"
}
```

The desired out put would be:

```javascript
{
  one: 1,
  two: "TWO",
  three: "threeeeee"
}
```

Hope that helps clarify.

**Comment by wtlangford** [comment]
So, this is something that comes up every so often, but the j in jq is for
JSON (but jq isn't an acronym.  At least, not as far as I know.)  I'm not
super keen on adding an output format that isn't actually JSON, and we've
turned down other such requests in the past.

That said, I suppose my question for you is "what's your use case that JSON
text doesn't solve your problem, but your desired output above does?"
 Personally, I'd complain about a linter that didn't like the first output.

**Comment by ryexley** [comment]
That's fine. I wasn't really requesting a feature...was just asking if it was there and I wasn't seeing/finding it. My use case is this: I want to use some data from an API in a set of unit tests. So querying the API and grabbing a subset of it with JQ to paste into a spec file for test data. Very useful for stuff like that. In my case though, both JSHint and ESLint (even the default implementations if I'm not mistaken) will complain about "unnecessary quotes" around the keys of the object...so to appease the linter, I have to manually remove those quotes. Not really a big deal, I can do it manually without much trouble...but if I could do it automatically with a tool, even better.

Like I said...this is not a big deal...I was just curious if this was something that was do-able with JQ and I was missing it. Thanks for the great tool.

**Comment by wtlangford** [comment]
No problem!
That's...  I find that to be an odd default behavior for a linter, in that
the quoted form is always less ambiguous.  Personally, I'd consider trying
to find a way to disable that linter check as opposed to removing them
manually (which is likely to be error-prone because text manipulation is
hard).

Regardless, glad to be able to shed some light on this for you.

**Comment by ryexley** [comment]
There are ways to disable it...and that is a possible solution as well, yes. Thanks for the clarification, and again, for the great tool.

**Comment by roan815** [comment]
@ryexley https://openjs.space/questions/javascript-object-notation-is-a-standard-way-of-formatting

**Comment by wader** [comment]
Think i've seen links like this before, is the weird SEO spam etc?

**Comment by tianmiaohu-fis** [comment]
This is a use case for Javascript object literal in MongoDB's runCommand.  See below link on the update command:
https://www.mongodb.com/docs/manual/reference/command/update/#mongodb-dbcommand-dbcmd.update
