### ISSUE TITLE
Clarify support for Math functions

### ISSUE THREAD

**Issue by eric-brechemier** [stedolan/jq#1274]
Based on the [Math section of `jq` Manual](https://stedolan.github.io/jq/manual/#Math), I expected `jq` to support the [`round` function defined in `<math.h>`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/round.html#). It seems, however, that the assertion `jq also has most standard math functions from the C math library` is not accurate.

I found a list of the functions from the C math library supported by `jq` in [libm.h](https://github.com/stedolan/jq/blob/0c93eb3379241dc4775718a9d39f54a6c4de20d6/src/libm.h) in the source code:

 * acos
 * acosh
 * asin
 * asinh
 * atan
 * atanh
 * cbrt
 * cos
 * cosh
 * exp
 * exp2
 * floor
 * j0
 * j1
 * log
 * log10
 * log2
 * sin
 * sinh
 * sqrt
 * tan
 * tanh
 * tgamma
 * y0
 * y1
(25 functions)

It is shorter than the [list of functions defined in Math.h](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/math.h.html), ignoring `float` and `long double` variants:

```
double      acos(double);
double      acosh(double);
double      asin(double);
double      asinh(double);
double      atan(double);
double      atan2(double, double);
double      atanh(double);
double      cbrt(double);
double      ceil(double);
double      copysign(double, double);
double      cos(double);
double      cosh(double);
double      erf(double);
double      erfc(double);
double      exp(double);
double      exp2(double);
double      expm1(double);
double      fabs(double);
double      fdim(double, double);
double      floor(double);
double      fma(double, double, double);
double      fmax(double, double);
double      fmin(double, double);
double      fmod(double, double);
double      frexp(double, int *);
double      hypot(double, double);
double      j0(double);
double      j1(double);
double      jn(int, double);
double      ldexp(double, int);
double      lgamma(double);
double      log(double);
double      log10(double);
double      log1p(double);
double      log2(double);
double      logb(double);
double      modf(double, double *);
double      nan(const char *);
double      nearbyint(double);
double      nextafter(double, double);
double      nexttoward(double, long double);
double      pow(double, double);
double      remainder(double, double);
double      remquo(double, double, int *);
double      rint(double);
double      round(double);
double      scalbln(double, long);
double      scalbn(double, int);
double      sin(double);
double      sinh(double);
double      sqrt(double);
double      tan(double);
double      tanh(double);
double      tgamma(double);
double      trunc(double);
double      y0(double);
double      y1(double);
double      yn(int, double);
(57 functions)
```

**Comment by pkoppstein** [comment]
@eric-brechemier - 

(1) jq coverage of the math functions does vary by platform, and from version to version, but jq 1.5 provides more coverage on most platforms than your list of 25 functions. In particular, as of June 28, 2015, the following are also provided on most platforms and have their standard "libm" definitions: 

```
atan2/2, hypot/2, pow/2, remainder/2
```

In addition, if you look in builtin.c, you'll see that fabs() is provided via `length/0`.
Also, nan() is provided as `nan/0`, as verified by:

    $ jq -n 'nan | isnan'
    true

Admittedly, these last two are a bit obscure, which leads to the next point.

(2) The [FAQ](https://github.com/stedolan/jq/wiki/FAQ) does attempt to provide greater clarity at "Q: What mathematical functions are supported?"  

(3) The manual does say "most standard math functions", not "most libm functions". Given the general orientation of the manual to conciseness, the phrasing seems reasonable to me. If I had to choose between tweaking the manual and Increasing the coverage, I'd choose the latter :-)

**Comment by eric-brechemier** [comment]
@pkoppstein Thanks for the pointer to the FAQ.

As you noted, tweaking the (online and `man`) manual to include this list would be helpful.

Now, I do wonder how the line is drawn between standard and non-standard mathematical functions, for example `floor` (included) vs `ceil` and `round` (not included).

While it is possible to implement these functions in user space, it is quite ugly, and probably not as efficient as linking to a C function:

```
# Round to the closest integer (above starting at .5 included, otherwise below) 
def round:                                                                      
  . as $notRounded                                                              
  | (.|floor) as $roundedBelow                                                  
  | if $notRounded - $roundedBelow < 0.5                                        
      then $roundedBelow                                                        
      else $roundedBelow + 1                                                    
    end                                                                         
;
```

**Comment by pkoppstein** [comment]
@eric-brechemier - Yep all round. :-)

**Comment by nicowilliams** [comment]
We definitely need to add more of these!

**Comment by nicowilliams** [comment]
See #1328 and 597c1f6.

I've added all of those except (for no good reason; I just realized I missed them, and I may add them later): `remquo` and `scalbn`.  Also, `nan` is already a builtin with different semantics from the POSIX C `nan()` semantics.

I've also added these in addition to those: `drem`, `exp10`, `gamma`, `pow10`, and `significand`.

I've not checked that all work everywhere that they can.  I may have to define some macros to get them a.

**Comment by eric-brechemier** [comment]
@nicowilliams Thanks!

**Comment by tggagne** [comment]
The expression below is used to filter bitbucket pull-request data into a CSV.  I need to use the ceil() function on the last value.  I can't figure out the syntax to get a ceil() of the last expression, `$parent.size/$parent.pagelen`.

`jq -r --tab ' . as $parent | .values[] | [ .id, .state, .author.display_name, .created_on, .destination.repository.name, $parent.page, $parent.size/$parent.pagelen ] | flatten | @csv '`

**Comment by wader** [comment]
@tggagne hi, i guess you want `..., ($parent.size/$parent.pagelen | ceil), ...`
