### ISSUE TITLE
Port as postgresql extension

### ISSUE THREAD

**Issue by niquola** [stedolan/jq#1276]
Awesome jq! How difficult to port this until as postgresql extension for jsonb? Could you point me where to start?

**Comment by eric-brechemier** [comment]
[Chapter 36 of PostgreSQL's documentation, Extending SQL](https://www.postgresql.org/docs/current/static/extend.html), looks like a good place to start :)

**Comment by niquola** [comment]
I mean, postgresql use it's own jsonb implementation - how jq could be decomposed to work with jsonb?

**Comment by eric-brechemier** [comment]
I would start by analyzing [`jq`'s source code](https://github.com/stedolan/jq/tree/master/src) to identify which files participate in each of the main responsibilities:

### Parsing Arguments

* `main.c`, `version.h` - main program

### Parsing `jq` filters

* `linker.c`, `linker.h` - load jq modules
* `locfile.c`, `locfile.h` - identification of locations in jq modules
* `lexer.c`, `lexer.h` (from `lexer.l`) - tokenization of jq filters
* `parser.c`, `parser.h` (from `parser.y`), `jq_parser.h` - parsing of jq filters
* `bytecode.c`, `bytecode.h`, opcode_list.h - definition of byte code
* `compile.c`, `compile.h` - compilation of jq filters to byte code

### Parsing JSON

* `jv_file.c`, `jv.h` - load JSON files
* `util.c`, `jq.h` - read JSON input files and apply JSON parser
* `jv_parse.c`, `jv.h` - JSON parser
* `jv_dtoa.c`, `jv_dtoa.h` - parsing of numbers
* `jv_unicode.c`, `jv_unicode.h`, `jv_utf8_tables.h` - UTF-8 string parsing
* `jv.c`, `jv_aux.c`, `jv.h` - representation and operations on JSON values

### Transforming JSON

* `builtin.c`, `builtin.h`, `builtin.jq`, `libm.h` - built-in functions
* `execute.c`, `jq.h`, `exec_stack.h`  - execution of byte code

### Serializing JSON

* `jv_dtoa.c`, `jv_dtoa.h` - serialization of numbers
* `jv_unicode.c`, `jv_unicode.h`, `jv_utf8_tables.h` - UTF-8 string serializing

### Other

* `jq_test.c` - testing
* `jv_print.c`, `jv.h` - serialization of values displayed in error messages
* `jv_alloc.c`, `jv_alloc.h` - memory allocation
* `util.c`, `util.h` - misc utilities: resolve paths, print to console
* `inject_errors.c` - error injection library

The build makes both the `jq` program and a library, `libjq.la`, which includes all of the following source code except:

* `main.c`, version.h - main program
* `inject_errors.c` - error injection library

You can then analyze which parts need to be rewritten and which parts can be kept to apply a transformation from JSONB to JSONB.

**Comment by niquola** [comment]
Thank you, for such a detailed answer - that's what I need to start!!!

**Comment by nicowilliams** [comment]
We've talked on IRC about this.  Because of how JSONB works in PG, I think a proper fast integration would probably be a from-scratch implementation of jq.  Of course, a lesser integration can be done just fine as it is right now, but with parsing and re-encoding around all calls to jq from SQL.

Another possibility might be to integrate more completely but with re-encoding only when inputs are JSONB or outputs are cast to JSONB, but this would require changes to PG internals.

In any case, there is ongoing work in the PG community to add JSONPath support to PG.
