### ISSUE TITLE
counting the number of elements in output

### ISSUE THREAD

**Issue by junaid-ali** [stedolan/jq#1277]
Does jq support counting the number of elements in the output? I can't find any [documentation](https://stedolan.github.io/jq/manual) for that. It would be useful in some scenarios.

**Comment by eric-brechemier** [comment]
The [length](https://stedolan.github.io/jq/manual/#length) function counts the number of elements in an array.

**Comment by junaid-ali** [comment]
Thanks @eric-brechemier for the response.
Length function appears to output "number of Unicode codepoints a string contains" in case of strings i.e
if i have the following output:
"samsung"
"apple"
"windows"
Using length function the output will be
7
5
7
A count function is useful when we just want to count the output elements e.g for the above case,  output should be "3" as there are 3 items in the output.

**Comment by pkoppstein** [comment]
To answer your question, consider two cases:

In the first case, suppose your filter is f, and that it generates an array of results.
Then to output the array of results together with a count of the number of results, you would write:

      f | (., length)

Now suppose your filter is f and that it generates a stream of results; you could then write:

    [f] | (.[], length)

In practice, it might be easier to use something like: jq -c ... | wc -l

By the way, if your filter produces a stream of results and if you wanted to number each one sequentially, you could write:

    foreach f as $f (0; .+1; [.,$f])

**Comment by junaid-ali** [comment]
Thanks @pkoppstein, I'm using "$ wc -l" in my case. I thought there might be any direct jq method that I'm missing.
