### ISSUE TITLE
Support JSONP data type

### ISSUE THREAD

**Issue by yleo77** [stedolan/jq#128]
If the URL return  data type that is JSONP,,,  this script will parse error..

**Comment by pkoppstein** [comment]
There is now a FAQ about JSONP in https://github.com/stedolan/jq/wiki/FAQ#general-questions

The FAQ addresses the common case where the P (padding) takes the form of a function call.

**Comment by dtolnay** [comment]
The FAQ gives the command for using JSONP input. Developing a more general solution is difficult because JSONP is so poorly specified.

**Comment by marcosscriven** [comment]
The mentioned FAQ re JSONP recommends:

```
curl ..... | jq -s -R '.[1+index("("): rindex(")")] | fromjson' | jq .....
```

However, the internal pipe to ```fromjson``` causes an error. Removing it works fine.

**Comment by pkoppstein** [comment]
@marcosscriven - Here's an example "from the wild" that illustrates that using 'fromjson' (a) works; and (b) produces results that jq can understand: 

    $ curl -Ss 'http://ipinfo.io/?callback=callback' | jq -R -s '.[1+index("("): rindex(")")] | fromjson'
    {
      "ip": "98.110.32.27",
      "hostname": "pool-98-110-32-27.cmdnnj.fios.verizon.net",
      "city": "Plainsboro",
      "region": "New Jersey",
      "country": "US",
      "loc": "40.3289,-74.5857",
      "org": "AS701 MCI Communications Services, Inc. d/b/a Verizon Business",
      "postal": "08536"
    }

In this and other cases, if 'fromjson' is omitted, then the result will be a string, which may be what you want, but which will generally make "downstream" processing a bit tricky.  Of course you're free to omit 'fromjson' if you just want the string :-)

**Comment by marcosscriven** [comment]
Thanks @pkoppstein - Another issue I faced is if the results form curl contains a close bracket, so the index returned by ```rindex``` truncated the valid JSON result.

**Comment by pkoppstein** [comment]
@marcosscriven - It usually helps to give an example, especially in circumstances like this where you or I could easily give examples that have closing parentheses and that work as intended.  If you give an example, we'll be better able to understand the problem, and there's a chance that in documenting the example, you'll find the source of the problem yourself.

**Comment by marcosscriven** [comment]
Sorry @pkoppstein - I wasn't really looking for guidance on my last message, it was more just an FYI. Thanks again for your help.

**Comment by muhammedbasil** [comment]
I used sed to remove the callback and it worked.
please see the below example

`echo 'jsonp({"k":"v"});' | sed 's/jsonp(//' | sed 's/)//' | jq "."`

first **sed** remove the callbackname and opening parentheses. then second **sed** remove the closing parentheses.
Now I could not find the method to identify the last occurrence of the closing parentheses to avoid the removing the closing parentheses in between. But the above works in my cases.

**Comment by muhammedbasilsk** [comment]
I used sed to remove the callback and it worked.
please see the below example

`echo 'jsonp({"k":"v"});' | sed 's/jsonp(//' | sed 's/)//' | jq "."`

first **sed** remove the callbackname and opening parentheses. then second **sed** remove the closing parentheses.
Now I could not find the method to identify the last occurrence of the closing parentheses to avoid the removing the closing parentheses in between. But the above works in my cases.
