### ISSUE TITLE
slurpfile does not set variable, returns error code

### ISSUE THREAD

**Issue by mcstafford-git** [stedolan/jq#1280]
Tested in jq-1.5-1-a5b5cbe (installed via apt) and jq-1.5rc2-152-g0b82185 (from git/master) on Ubuntu 16.10/yakkety.

    url='https://api.github.com/repos/stedolan/jq/commits?per_page=5'
    curl $url 1> ./jq-test.json 2>/dev/null
    jq --slurpfile arr ./jq-test.json

> jq - commandline JSON processor [version 1.5-1-a5b5cbe]
> Usage: jq [options] <jq filter> [file...]
> 
> 	jq is a tool for processing JSON inputs, applying the
> 	given filter to its JSON text inputs and producing the
> ...

    echo $?
> 2

**Comment by pkoppstein** [comment]
Your invocation of jq specified neither a "source" nor a jq filter.   Consider instead:

    jq -n --slurpfile arr jq-test.json '$arr'

"-n" means there is no "source" (i.e. do not read from STDIN), and '$arr' is a filter.

**Comment by uvwild** [comment]
its missing in jq-1.4.1
