### ISSUE TITLE
Strange `range` behavior

### ISSUE THREAD

**Issue by fadado** [stedolan/jq#1284]
I don't understand this `range` behavior using jq-1.5:

```
$ jq -cn '[range(0,1;3,4)]'
[0,1,2,3,1,2,3]
$ jq -cn '[range(0,1;4)]'
[0,1,2,3,1,2,3]
```

But, as I expect:

```
$ jq -cn 'def r(a;b):(a|tostring)+(b|tostring); [r(0,1;3,4)]'
["03","13","04","14"]
$ jq -cn 'def r(a;b):(a|tostring)+(b|tostring); [r(0,1;4)]'
["04","14"]

```

**Comment by pkoppstein** [comment]
The "strange range behavior" you observed was a bug.  I say "was" because it was fixed after the release of jq 1.5:

    $ jq1.5 -n '[range((0,2);(4,4))] | length'
    6
   $ jq -n '[range((0,2);(4,4))] | length'
   12

(The bug came about because`range/2` was (and remains) hard-coded; that in turn was probably because `range/2` existed before TCO was implemented.)

**Comment by fadado** [comment]
> The "strange range behavior" you observed was a bug. I say "was" because it was fixed after the release of jq 1.5:

Oops! I will try to compile **jq** by myself... In the interim this partial `range` emulation works as expected:

```
def from($m; $n):
    def r: if . < $n then ., (.+1|r) else empty end;
    $m|r
;
```

A related confusion is in the page [Advanced Topics](https://github.com/stedolan/jq/wiki/Advanced-Topics#cartesian-product-behavior-of-some-expressions). The text says:

> Some expressions have a kind of "Cartesian product" behavior.  For example, `range(0,1; 3,4)` is the same as `range(0;3), range(0;4), range(1;3), range(1;4)`. 

This is not true, but I will not edit the page because I can't test now the code with the last **jq**.
The correct text must say, I think:

> Some expressions have a kind of "Cartesian product" behavior.  For example, `range(0,1; 3,4)` is the same as `range(0;3), range(1;3), range(0;4), range(1;4)`. 

Sorry if I'm wrong... I'm a bit puzzled...

**Comment by pkoppstein** [comment]
> This is not true

Using the current version (jq-1.5rc2-150-g1740fd0):

    $ jq -n '[range(0,1; 3,4)] ==[range(0;3), range(0;4), range(1;3), range(1;4)]'
    true

Note also:

    $ jq -n 'def r(a;b): a as $a | b as $b | range($a;$b); [r(0,1; 3,4)] ==[r(0;3), r(0;4), r(1;3), r(1;4)]'
    true
    $ jq -n 'def r($a;$b): range($a;$b);[r(0,1; 3,4)] ==[r(0;3), r(0;4), r(1;3), r(1;4)]'
    true

**Comment by fadado** [comment]
Agree. I apologize for my confusion when using an old jq version.
