### ISSUE TITLE
want to filter list

### ISSUE THREAD

**Issue by anthonyettinger** [stedolan/jq#1291]
I want to skip items that have `.name` as null and for those items that *do* have `.name` I want to show two other attributes: `.location,.date`

**Comment by pkoppstein** [comment]
@anthonyettinger  - This sounds like a straightforward usage question.  Could you please post it, with a concise example of input and expected output, at stackoverflow.com using the jq tag?  If you get a satisfactory answer there, then please remember to "close" this "Issue".  Thank you.

**Comment by cumanzor** [comment]
I have a similar example as a matter of fact:

My structure is something like this:

```
[
    {
        "url":"http://something.com"
        "result": {"keyA:valA, keyB:val}
    },
    {
        "url":"http://something.com"
        "result": {}
    }
[...]
]
```

I want to print out the urls where the result object isn't empty. Just found this tool today and it will be extremely useful, hate myself I can't figure out this simple use case 👨‍🚀 .
