### ISSUE TITLE
Provide option to fail silently.

### ISSUE THREAD

**Issue by jgberg** [stedolan/jq#1293]
I'm using jq inside of a shell script where it is part of a command pipeline. It is looking for an item in the JSON sent to it. However, upstream in the pipe, something may happen and non-JSON is sent down the pipe. When this happens jq rightfully chokes and it emits "parse error: Invalid numeric literal at line 1, column 7".  As this is spit up on the screen, it is unhelpful to my users.

I'd like it instead to fail silently, not emitting anything, while I can still there was problem by looking at the exit code for the pipeline, which is 4 in this case.

So I'm suggesting a simple option to jq:
--silent
that functions to have jq shut up on errors. Script writers can rely on the exit code to handle errors as needed then.

**Comment by pkoppstein** [comment]
For reference, the main workarounds are:

1)  redirect STDERR using 2>

2) assuming you have access to a version of jq that supports try/catch, use them to handle jq errors, e.g. along the lines illustrated by this transcript:

    $ jq -n 'try inputs catch "Caught"' <<< foo
    "Caught"

**Comment by nicowilliams** [comment]
Per @pkoppstein, I don't think this needs fixing.
