### ISSUE TITLE
How can one tell if result of filter is null from JSON data or null from jq behavior?

### ISSUE THREAD

**Issue by fatbearinc** [stedolan/jq#1296]
These give the same result and return codes (both 1):

```
jq -e '.a' <<<'{}'
jq -e '.a' <<<'{"a": null}'
```

If the -e flag is omitted, both have a return code of 0.  In all cases, the result of these operations is null.

I want to distinguish the first from the second.  What jq tricks can I do that will help?

I'm feeling like I want an option that says that trying to access a non-existent key is an error.  In the meantime, I need a workaround that will help me distinguish these two cases.

Note that the above example is for illustration purposes.  See [this post](http://stackoverflow.com/questions/41124355/how-can-i-tell-if-a-jq-filter-successfully-pulls-data-from-a-json-data-structure) for more complex examples.

**Comment by fatbearinc** [comment]
I think I have an idea for a workaround.  Would you please confirm this is a good workaround?

```
#!/bin/bash

Select()
{
   local Name="$1"
   local Filter="$2"
   local Input="$3"
   local Result Status

   Result="$(jq -e --arg Name "$Name" "$Filter" <<<"$Input")"
   Status=$?

   case $Status in
   1) jq --arg Name "$Name" "path($Filter)" <<<"$Input" >/dev/null 2>&1
      Status=$?
      [[ $Status -eq 0 ]] && Result=$(jq --arg Name "$Name" "$Filter" <<<"$Input")
      ;;
   *) ;;
   esac

   [[ $Status -eq 0 ]] || Result="***ERROR***"
   echo "$Status $Result"
}

Filter='.[]|select(.user == $Name)|.value'
Input='
[
   {"user":"steve", "value":false},
   {"user":"tom", "value":true},
   {"user":"pat", "value":null},
   {"user":"jane", "value":""}
]'


Select steve "$Filter" "$Input"
Select tom   "$Filter" "$Input"
Select pat   "$Filter" "$Input"
Select jane  "$Filter" "$Input"
Select mary  "$Filter" "$Input"
```

And executing this:

```
./Select.sh 
0 false
0 true
0 null
0 ""
4 ***ERROR***
```

This workaround meets my needs.  What do you think?

**Comment by pkoppstein** [comment]
@fatbearinc - Given that jq is stream-oriented, I'm inclined to think that you would be better off focusing on your observation:

>    I'm feeling like I want an option that says that trying to access a non-existent key is an error.

Given that jq is the way it is, the way to approach the issue is to define a filter that makes the distinction you want. Thus consider:

    def get(f): if has(f) then .[f] else error("object does not have \(f)") end;

So, rather than writing `.a` as in your example, you'd write get("a").   Now you can easily tell whether or not an object has a key, and you're all set to go.   You would presumably want to do the same type of thing for arrays.

**Comment by fatbearinc** [comment]
@pkoppstein But this solution assumes that I know which keys in advance that I need to check. My problem is that I need something general that can take any filter and treat it as an error if a key does not exist. And, as an aside, the has() function is very limited: it handles only leaf keys.

In the example I provide, the filter is '.[]|select(.user == $Name)|.value' and it acts on an array of dictionaries. I need to know that all dictionaries have both a user key and a value key in this example. And, of course, this is just an example. JSON data structures are typically more complex and the filters that manipulate them can be equally complex. I need it to be the case that during evaluation that if any key does not exist that this can be discovered.  I would think that the jq executable is the right place to have such functionality because whatever I might try to do will just be a workaround and will probably never solve the general problem of discovering whether or not keys accessed by a filter are missing.

I would like to see some jq option that requires referenced keys to exist that are referenced in a filter and which results in a non-zero return code if referenced keys do not exist.

**Comment by fatbearinc** [comment]
So, is there any function **check(filter)** that checks the filter and returns a boolean that tells us whether that filter tries to access non-existent keys or indices?

**Comment by pkoppstein** [comment]
@ is there any function check(filter) that can be devised ...?

No. jq does not support the meta-programming that would be required for such a function to be written in jq.

**Comment by fatbearinc** [comment]
Thanks for that confirmation. Based on this, I think the best course of action for my application is to prohibit the value of `null` in JSON data structures and add as part of the application data modeling a value such as `"@unset@"` (and allow it to be configured by the application user to be any string of their choice). I will also have to create my own setters and getters to avoid situations where `null` values are created automatically (e.g., creating sparse arrays). Doing this would then allow the application to treat `null` always as an indicator of an error condition.

Is there any chance of a feature request getting implemented for the **--none-default \<json>** option I previously mentioned? It would be nice someday to not have to implement the fairly arduous workaround that is needed that I mention above.

Your feedback, both here and in [stackoverflow.com](http://stackoverflow.com/questions/41124355/how-can-i-tell-if-a-jq-filter-successfully-pulls-data-from-a-json-data-structure), has been appreciated.

**Comment by nicowilliams** [comment]
No need for a `--none-default` option.  You can check if a value is null, and you can define your own getter that does the right thing, as shown by @pkoppstein, with whatever default you want (e.g., `empty`, `error`, or some default value).

Adding a default value option would be dangerous because it would probably break various internal uses of the index operation (as well as uses elsewhere in your own code).
