### ISSUE TITLE
using jq with JSON having $self inside JSON

### ISSUE THREAD

**Issue by hectoralicea** [stedolan/jq#1297]
I have a JSON file that I am not able to pull attributes using JQ.  It has the $self thing, and that's something i've never seen.  
Sometimes this jq query works:  .api.$self.name  but Its not reliable.  Sometimes it works sometimes it fails.  All the time the following fails: .apiVersion.$self.name

what's up with $self tag.  How does that work.  Is it just like any other field name or does it have a special purpose.

{
  "api": {
    "$self": {
      "name": "query-lender-leap-agent"
    }
  },
  "apiVersion": {
    "$self": {
      "name": "1.1.0",
      "description": "ESB Query .",
      "tags": [],
      "order": 1,
      "deprecated": false,
      "endpointUri": "http://localhost:8086/hla-esb/api/v1.1"
    }
  },

**Comment by pkoppstein** [comment]
"$" is a special character in jq.  Key names with special characters have to be presented as JSON strings (with the double-quotation marks).  In all versions of jq, you can use the syntax

`.["KEYNAME"]`

In recent versions, you can abbreviate this to `."KEYNAME"`

"$" is special in jq in another way too -- if you're interested, please read the jq manual. 

In future, please ask usage questions at http://stackoverflow.com/questions/tagged/jq
