### ISSUE TITLE
Setting exit code

### ISSUE THREAD

**Issue by saleyn** [stedolan/jq#1300]
Is there a way to set the exit code without requiring to have the last term equal to `false`?

I'd like to check an object for presence of a key, and if found, print the value of that key, set exit code to 1, and abort.  Is it doable?

**Comment by pkoppstein** [comment]
In the *ix world, commands that succeed without error generally yield a return code of 0.  jq generally follows that tradition, so if you are willing to adopt that convention, what you seem to need is easily doable. Here's one way.

The idea is to check whether or not the object has the key of interest using a function that will raise an error condition if it doesn't. The following filter will do the job:

    def get(keyname): if def get(f): if has(f) then .[f] else error("\(type) is not defined at \(f)") end;

(This function should of course be called with the key name, a JSON string.)

If you do not want to be bothered with the error message that would be sent to STDERR if the error condition is raised, you can redirect it to /dev/null (or NUL in a Windows environment), e.g. along the lines of:

   jq .... 2> /dev/null

If you really must have an error code of 1 to signal success, then I'd suggest writing a wrapper script (or function) that uses the above technique.

By the way, for future reference, please ask usage questions at stackoverflow.com, using the tag:[ jq](https://stackoverflow.com/questions/tagged/jq)   There is an extensive set of Q&As there, as well as the [jq FAQ](https://github.com/stedolan/jq/wiki/FAQ).

**Comment by saleyn** [comment]
Thanks for your help!  This exactly addressed my need.  I suggest adding this example to the FAQ or cookbook as this problem if very common to the *NIX world.

**Comment by pkoppstein** [comment]
@saleyn - I fixed a typo in the definition of get/1, and followed your suggestion re the FAQ.  Thanks!
