### ISSUE TITLE
Unexpected Indexing Failure

### ISSUE THREAD

**Issue by bpourkazemi** [stedolan/jq#1302]
Input:
```json
[
    {"id": 1, "color": "blue"},
    {"id": 2, "color": "yellow"}
]
```

Desired output:
```json
[
    "1, blue",
    "2, yellow"
]
```

Attempt fails with `Cannot index number with string "color"`:
```
| jq 'map([.id|tostring, .color] | join(", "))'
```

Yet, reversing the elements in the array works (albeit, the output order is reversed):
```
| jq 'map([.color, .id|tostring] | join(", "))'
```

Is this correct?

**Comment by pkoppstein** [comment]
1.  The first line with `map` in the above post just needs a pair of parentheses:

     map([(.id|tostring), .color] | join(", "))

yields: ["1, blue","2, yellow"]

The way you had it is equivalent to `.id | (tostring, .color)`, which requires the evaluation of .id.color, and hence the error message.  The moral: if in doubt about grouping, just add parentheses.

2. For future reference, please ask usage questions at stackoverflow.com, using the jq tag. See e.g. http://stackoverflow.com/questions/tagged/jq

**Comment by bpourkazemi** [comment]
Thank you!

**Comment by pkoppstein** [comment]
You're welcome. Thank you for closing the issue.

By the way, you can get the same result (using jq 1.5) with:

    [.[] | .[]] | [join(", ")]

 You might also be interested to try this filter on your JSON:

     [.[][]]
