### ISSUE TITLE
Selectors like .15m don't work

### ISSUE THREAD

**Issue by rspielmann** [stedolan/jq#1304]
Example:

`wget -O - https://blockchain.info/de/ticker -q | jq ".EUR"`

This works. The output is:

`
{
  "15m": 906.89,
  "last": 906.89,
  "buy": 902.65,
  "sell": 906.89,
  "symbol": "€"
}
`

Next, I tried

`wget -O - https://blockchain.info/de/ticker -q | jq ".EUR.15m"`

with the result

`jq: error: syntax error, unexpected LITERAL, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
.EUR.15m    
jq: 1 compile error`

whereas

`wget -O - https://blockchain.info/de/ticker -q | jq ".EUR.last"`

works fine.

I used jq-1.5-1-a5b5cbe.

**Comment by pkoppstein** [comment]
The syntax '.selector' can (by design) only be used if the selector name is alphanumeric AND begins with an alphabetic character. Thus in your case you could write .["EUR"] | .["15m"] or any of the shorthand forms allowed by the particular version of jq being used.

**Comment by nicowilliams** [comment]
Yes, `.foo` needs `foo` to be ident-like.
