### ISSUE TITLE
transforming urls in json document

### ISSUE THREAD

**Issue by emetsger** [stedolan/jq#1306]
Hi, 

I'm sure there has to be an easy solution to this, but I'm new to jq and have been fumbling around, making progress, but at this point I'm stumped.  Here's my use case:

I have a [JSON document](https://jqplay.org/s/3WctRQDHhg) from a [JSON-API 1.0 endpoint](http://jsonapi.org/format/).  What I want to do is base64 encode the query parameters of URLs in the document, but otherwise preserve the existing document.

For example, the url `http://localhost:8000/v2/nodes/xug4a/comments/?filter%5Btarget%5D=xug4a` would be transformed to `http://localhost:8000/v2/nodes/xug4a/comments/P2ZpbHRlciU1QnRhcmdldCU1RD14dWc0YQo=`

If the sample input was:
```json
{
  "data": {
    "relationships": {
      "files": {
        "links": {
          "related": {
            "href": "http://localhost:8000/v2/nodes/xug4a/files/",
            "meta": {}
          }
        }
      },
      "comments": {
        "links": {
          "related": {
            "href": "http://localhost:8000/v2/nodes/xug4a/comments/?filter%5Btarget%5D=xug4a",
            "meta": {}
          }
        }
      },
    },
    "attributes": {
      "foo": "bar"      
    },
    "type": "nodes",
    "id": "xug4a"
  }
}
```

The output would be the same, except for the base64 encoded query string:
```json
{
  "data": {
    "relationships": {
      "files": {
        "links": {
          "related": {
            "href": "http://localhost:8000/v2/nodes/xug4a/files/",
            "meta": {}
          }
        }
      },
      "comments": {
        "links": {
          "related": {
            "href": "http://localhost:8000/v2/nodes/xug4a/comments/P2ZpbHRlciU1QnRhcmdldCU1RD14dWc0YQo=",
            "meta": {}
          }
        }
      },
    },
    "attributes": {
      "foo": "bar"      
    },
    "type": "nodes",
    "id": "xug4a"
  }
}
```

I've been able to get as far as performing the [transformation of the url itself](https://jqplay.org/s/i7drFzt8hJ) using a clumsy filter `if (. | rindex("?") > 0) then [.] | map(.[0:rindex("?")], (.[rindex("?"):length] | @base64)) | join("") else . end`, but I'm having trouble implementing the transformation of the document.  

The documentation is great, but I've looked at some samples, and in the cookbook, and I'm having trouble piecing it together.  Any help is much appreciated!

**Comment by pkoppstein** [comment]
1. Regarding the tweaking of the URL, I'd suggest:

     def tweak: rindex("?") as $r | if $r then .[0:$r] + (.[$r:] | @base64) else . end;

2.  There are of course several ways to achieve what you want, but personally I'd probably go with:

    walk( if type == "object" and has("href") then .href |= tweak else . end )

The key, though, is `|=`.  If your jq does not have `walk` you can easily find its definition (in jq) on the internet, e.g. on the [jq FAQ](https://github.com/stedolan/jq/wiki/FAQ), at stackoverflow.com, etc.

3. Speaking of stackoverflow.com, in future, please ask usage questions there, using the `jq` tag.

**Comment by emetsger** [comment]
@pkoppstein thanks very much.  In the future, I'll use stackoverflow.  The pointers are much appreciated.
