### ISSUE TITLE
Allows reversed key filters .[].(!)ingress

### ISSUE THREAD

**Issue by krasi-georgiev** [stedolan/jq#1309]
{
  "ingress": {
    "IPAMConfig": {
      "IPv4Address": "10.255.0.7"
    },
    "Links": null,
    "Aliases": [
      "f8207bb35f6f"
    ],
    "NetworkID": "dytmdd3uys7xqq0km6wcemyc7",
    "EndpointID": "551ea14b8bcea4fcab1cbe5e9b29ffa13210010844497285d37ef90478c522a5",
    "Gateway": "",
    "IPAddress": "10.255.0.7",
    "IPPrefixLen": 16,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:0a:ff:00:07"
  },
  "x1": {
    "IPAMConfig": {
      "IPv4Address": "10.0.0.4"
    },
    "Links": null,
    "Aliases": [
      "f8207bb35f6f"
    ],
    "NetworkID": "epeig64no9r8vdnjml5s1whqh",
    "EndpointID": "0ad58188f2cc9571bb53a1fe5bdacd037578372bc10e17e37dab80bc683ffa4a",
    "Gateway": "",
    "IPAddress": "10.0.0.4",
    "IPPrefixLen": 24,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:0a:00:00:04"
  }
 "x2": {
    "IPAMConfig": {
      "IPv4Address": "10.0.0.4"
    },
    "Links": null,
    "Aliases": [
      "f8207bb35f6f"
    ],
    "NetworkID": "epeig64no9r8vdnjml5s1whqh",
    "EndpointID": "0ad58188f2cc9571bb53a1fe5bdacd037578372bc10e17e37dab80bc683ffa4a",
    "Gateway": "",
    "IPAddress": "10.0.0.4",
    "IPPrefixLen": 24,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:0a:00:00:04"
  }
}

would like to select all but "ingress"

something like
.[].(!)ingress

ingress is static and x1 and x2 are dynamic and might also contain other keys

I looked through all other functions and options and couldn't find a way to do this.

**Comment by pkoppstein** [comment]
> would like to select all but "ingress"

The simplest approach would presumably be to use `del`:
 
    del(.ingress)

For non-alphanumeric keys, you'd use the form: del( .["ingress"] )

In future, please ask usage questions at stackoverflow.com with the tag jq

**Comment by krasi-georgiev** [comment]
noted

thanks for the help regardless of being posted here instead of stackoverflow
