### ISSUE TITLE
request: make jq stdin accept json and output pretty print json

### ISSUE THREAD

**Issue by conrado** [stedolan/jq#1310]
it's very common to use jq to pretty print json. would it hurt to have jq accept stdin standard and output as if it had been called as `jq .[]`

**Comment by pkoppstein** [comment]
As you say, it is common to use jq to pretty print JSON, as in `echo 1 | jq .`.  Using jq 1.5, this can even be shortened to `echo 1 | jq`.  Making `.[]` the default filter would break this completely, so I'm afraid your suggestion as I understand it does not make any sense.  

(Please note that there is a potential problem with using jq as a pretty-printer: jq converts JSON numbers to IEEE 754 64-bit values, thus in most cases losing the original representation.)

**Comment by nicowilliams** [comment]
@conrado: yes, it would break backwards compatibility.
