### ISSUE TITLE
|= doesn't handle empty results from the update expression

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#1314]
The fix in `src/builtin.jq` is trivial:

    -def _modify(paths; update): reduce path(paths) as $p (.; setpath($p; getpath($p) | update));
    +def _modify(paths; update): reduce path(paths) as $p (.; setpath($p; getpath($p) | (.,update)));

**Comment by nicowilliams** [comment]
This will probably be fixed by the fix to #1313.

**Comment by nicowilliams** [comment]
IIRC we have another issue asking that empty in `|=` be the same as deleting the values at the given paths where the update expression outputs `empty`.  I'm not sure that's a good idea.

I can confirm that fixing #1313 fixes this.

**Comment by pkoppstein** [comment]
Regarding the cautionary note ("I'm not sure that's a good idea"), I'd like to suggest that at this point, the sine qua non is that `map_values(select(f))` should behave in the way that most people expect and/or want.  This could, if need be, be accomplished in jq 1.5 quite simply by:

    def map_values(f):
      with_entries( [.value|f] as $v | select( $v|length == 1) | .value = $v[0] ) ;

**Comment by nicowilliams** [comment]
@pkoppstein Well, but `map_values(f)` is defined in terms of `|=`, so `map_values(select(stuff))` never worked correctly.

We can argue about whether `stuff |= empty` means "delete stuff" or "leave stuff alone".  Here I think "delete stuff" is nice when you want it, but surprising when you don't.  We have a way to delete things when that's what we want, but if you want to do updates and deletions in one expression, then having `stuff |= empty` mean "delete stuff" sure is the better semantic to choose.  Implementing that will be tricky.

As for `reduce`, when the update expression produces `empty`, we currently have undefined results, and that's surprising and annoying.  I think the only choices as to `reduce` and empty updates are: "undefined behavior" or "leaves state unmodified".

**Comment by nicowilliams** [comment]
Given a fix to #1313, this causes `|=` to delete paths when the update expression is `empty`:

```
def _modify(paths; update): reduce path(paths) as $p (.; label $out | (setpath($p; getpath($p) | update) | ., break $out), delpaths([$p]));
```

Example:

```
$ ./jq -cn '{a:{b:{c:1,d:2}}}|.a.b.c |= select(.!=1)'
{"a":{"b":{"d":2}}}
$ ./jq -cn '{a:{b:{c:1,d:2}}}|(.a.b,.a.b.d) |= if type=="object" then empty else 50 end'
{"a":{"b":{"d":50}}}
$ ./jq -cn '{a:{b:{c:1,d:2}}}|.a.b |= if type=="object" then empty else 50 end'
{"a":{}}
$ ./jq -cn '{a:{b:{c:1,d:2}}}|(.a.b,.a.b.d) |= if type=="object" then empty else . end'
{"a":{"b":{"d":null}}}
```

Now, without this fix only the _first_ value of the update expression will take:

```
$ ./jq -cn '{a:{b:{c:1,d:2}}}|.a.b.c |= range(5)'
{"a":{"b":{"c":4,"d":2}}}
```

whereas without this fix only the _last_ value of the update expression will take:

```
./jq -cn '{a:{b:{c:1,d:2}}}|.a.b.c |= range(5)'
{"a":{"b":{"c":0,"d":2}}}
```

That's a bit of a backwards-incompatibility...  Though it's probably desirable too, as it will make `|=` more efficient by default.  I can fix this by wrapping `update` in `last()`:

```
def _modify(paths; update): reduce path(paths) as $p (.; label $out | (setpath($p; getpath($p) | last(update)) | ., break $out), delpaths([$p]));
```

But I'd rather not have to.

I'm looking for advice on this one.  @pkoppstein @wtlangford @stedolan @dtolnay.

**Comment by nicowilliams** [comment]
I really like the idea that `|=` with empty updates -> deletes the path.  It won't break existing code because `|=` with empty updates produces null altogether, which is a bug (see #1313).

But this new behavior could be a bit risky in that it makes `|=` too... expressive.  But I think that's OK.

**Comment by nicowilliams** [comment]
In retrospect, this can't be fixed.  See #1543.

**Comment by nicowilliams** [comment]
Actually, we could implement this without fixing #1313.  If the paths being modified lead to simple values, then fixing this is fine, but otherwise we get the same performance issues as in #1543.  We'll back this out too.

**Comment by nicowilliams** [comment]
Actually, if we're going to *delete* the value being modified when the RHS is `empty`, then we can do that efficiently.
