### ISSUE TITLE
SQL-style operators (functions) needed

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#1322]
We could have an `INDEX(index_expr)` and `INDEX(stream; index_expr)` functions that produce an object indexed by the given expression.  `index_expr` should be an expression that constructs an index key as a string, array, or object (the array or object kind will be stringified with `tojson`).

We could then have a `JOIN($index; join_expr)` and `JOIN($index; stream; join_expr)` functions that do the obvious thing.  The `join_expr` needs to output a key (based on `.`) for the `$index`.

We also need an `IN($array_or_object)` and `IN_STREAM(stream)` functions which return true if `.` is in the given array or object or stream.

**Comment by nicowilliams** [comment]
I've needed this many a time...

We could also have a concept of a `TABLE` that has a primary array or object and zero, one, or more indices as well as descriptions of their keys, which would then allow index expressions to be more automatic.  However, we're not building an RDBMS here -- we don't need too much luxury.

**Comment by rdm** [comment]
These seem to exist now, but could use some illustrative examples in the manual. (I suppose the test cases might do, but ideally something different.)
