### ISSUE TITLE
aggrgation and calculation in jq

### ISSUE THREAD

**Issue by aalgarn1** [stedolan/jq#1331]
I am new in jq and I have project that uses it. I want ti to know how can I aggregate and calculate. For example , we have the following: 
[{"name":"JSON", "good":true}, 
 {"name":"XML", "good":false},
 {"name":"HTML", "good":false},
 {"name":"XML", "good":true},
 {"name":"XML", "good":false},
 {"name":"JSON", "good":false}]

How can I create records that uses aggregate and count to show results like:
   JSON, 2
   XML, 3
   HTML, 1

**Comment by pkoppstein** [comment]
With your example data, the following query:

    group_by(.name)[] | [.[0].name, length]

produces:

```
["HTML",1]
["JSON",2]
["XML",3]
```

For future reference, please ask usage questions at stackoverflow.com with the jq tag:

https://stackoverflow.com/questions/tagged/jq
