### ISSUE TITLE
output reshape

### ISSUE THREAD

**Issue by aalgarn1** [stedolan/jq#1333]
I have the following example:
[{"foo": 42, "bar": "less interesting data"},
{"foo": 46, "bar": "less interesting data"},
{"foo": 43, "bar": "less interesting data"}]

when I use **jq '[.[].foo]'** , the result like:
[
  42,
  46,
  43
]
However, I want to show result like [42,46,43] in order to use add or calculate average(add/length)

**Comment by pkoppstein** [comment]
As requested in response to your previous question, please ask usage questions at stackoverflow.com with the jq tag:

https://stackoverflow.com/questions/tagged/jq

**Comment by nicowilliams** [comment]
@aalgarn1 It's unclear what you want.  If you want the output all on one line use the `-c` option.
