### ISSUE TITLE
Error with variables in JQ command

### ISSUE THREAD

**Issue by msgbrr** [stedolan/jq#1336]
if I try to use jq with variable : 

i=1
echo ${foo} | jq ".fastdl.curl."$i"" > /tmp/alpha.txt

I have this error : 

.fastdl.curl.1            1 compile error

Someone has a solution?

**Comment by pkoppstein** [comment]
1. You can try diagnosing the problem yourself by using `echo`, e.g.

    echo jq ".fastdl.curl."$i""

You'll see that the jq filter you've constructed is invalid.  Perhaps your filter should be `.fastdl.curl[$i]`?   It's hard to say as you haven't included details about the input.

2. There are better ways to pass environment variables to jq.  See e.g. the jq FAQ https://github.com/stedolan/jq/wiki/FAQ

3. In future, please ask usage questions at stackoverflow.com using the jq tag
