### ISSUE TITLE
delete of subarray

### ISSUE THREAD

**Issue by h0nIg** [stedolan/jq#1339]
hi

```
[
	{
		"name": "name1",
		"organizations": [
			{
				"name": "name2",
				"spaces": [
					{
						"name": "name3",
						"otherkey":"otherval"
					},
					{
						"name": "name4",
						"otherkey":"otherval"
					}
				]
			}
		]
	}
]
```

i just want to remove the array object with name=name4 and want to keep the rest of the object intact. I tried with map(select) but this will just give me the full object. Is it possible to work with del on specific subarrays and keep the rest as it is?

result should be the following. in addition i want to avoid enumeration all attributes to keep:
```
[
	{
		"name": "name1",
		"organizations": [
			{
				"name": "name2",
				"spaces": [
					{
						"name": "name3",
						"otherkey":"otherval"
					}
				]
			}
		]
	}
]
```

any idea?

**Comment by h0nIg** [comment]
recognized questions should be posted on stackoverflow: http://stackoverflow.com/questions/42215211/delete-on-nested-array-with-jq

**Comment by nicowilliams** [comment]
The thing you're looking for is the `del()` builtin.  See the [documentation](https://stedolan.github.io/jq/manual/).

**Comment by nicowilliams** [comment]
Also, the question is a bit underspecified.  One might say that `del(..?|select(.name4?))` should be the answer, but that might go too far for you.
