### ISSUE TITLE
Absolute value

### ISSUE THREAD

**Issue by ghost** [stedolan/jq#134]
Given this file

``` json
{
  "recordings": [
    {
      "id": "38a356f7-7749-4436-b27d-c3002deaddba",
      "duration": 231
    },
    {
      "id": "a855cd36-e786-4a66-80b7-bc5af792ac20",
      "duration": 230
    }
  ]
}
```

I would like to get the absolute value of `230` minus the duration. I can use the command

``` bash
jq '.recordings | sort_by(230 - .duration)' foo.json
```

but this only subtracts, not absolute value.

**Comment by svnpenn** [comment]
Shouldn’t this be added to the manual?

http://stedolan.github.io/jq/manual#length

**Comment by erhhung** [comment]
Please also describe the decision to use `length` for `abs` in the FAQ section "What mathematical functions are supported?". It's currently very roundabout to find that one of the most basic math functions, `abs()` is actually implemented as `length`!

**Comment by pkoppstein** [comment]
@erhung - The FAQ section you mention now mentions `length` along the lines you suggest.
