### ISSUE TITLE
jq in the Wikipedia

### ISSUE THREAD

**Issue by fadado** [stedolan/jq#1344]
I started a very small page for jq in the Wikipedia:

<https://en.wikipedia.org/wiki/Jq_(programming_language)>

Please change everything you want.  I only wanted to start the page: surelly it will have errors!

JJOR

**Comment by nicowilliams** [comment]
Nice!!  I appreciate the links to Icon and Haskell.

**Comment by fadado** [comment]
> Nice!! I appreciate the links to Icon and Haskell.

Wikimedia is angry about the logo copyrigth status. The say:

> File:Jq logo.png has been marked as a possible copyright violation. Wikimedia Commons only accepts free content—...

I added the image to

<https://commons.wikimedia.org/wiki/File:Jq_logo.png>

and the image metada can be edited at

<https://commons.wikimedia.org/w/index.php?title=File:Jq_logo.png&action=edit>

Can anybody help to fix the license image description? 

JJOR

**Comment by nicowilliams** [comment]
Only @stedolan could.  I'll e-mail him.

**Comment by fadado** [comment]
The wikipedia editor called "Cryptic" deleted the  JQ page two days ago.
I don't know the wikipedia bureaucracy enough to fight for this case. I started a [talk with "Cryptic"](https://en.wikipedia.org/wiki/User_talk:Cryptic#Deletion_of_Jq_(programming_language))
but I need the help of some wikipedia guru to convince "Cryptic" to change the deletion.

The page still survives at <https://www.wikiwand.com/en/Jq_(programming_language)>.

Thanks in advance and apologies for the offtopic.

**Comment by nicowilliams** [comment]
@fadado ugh, must I create a wikipedia account to comment on this?

```
    @Jordinas: (talk page stalker) FYI the reason was "Expired PROD, concern was: The only reference is primary, as are all external links. No indication that this is more than a personal project. Article was created by Jordinas, whose contributions all involve adding links to jq from other pages; COI likely.". ([https://en.wikipedia.org/w/index.php?title=Special:Log&logid=96412147 deletion log). If you do indeed have a COI, I suggest declaring it. If you intend to recreate the page, I would also suggest submitting it to AfC rather than creating it in mainspace. Just my 2 cents. If you are just someone who codes in Jq and wanted to right about it, then feel free to disregard. --DannyS712 (talk) 07:15, 22 January 2019 (UTC)
```

What is "COI"?  Why did the editor make no effort to find out that it's not just a "personal" project, and so what the$%^&!@ ^%&@! if it is.  Yes, it's @stedolan's personal project, but a) there are many, many users, b) there are many contributors, c) there are several maintainers.

**Comment by pkoppstein** [comment]
@nicowilliams, @fadado -

COI = conflict of interest

In case it helps, the ranking at http://rosettacode.org/wiki/RC_POP.OUT currently shows jq at #46, immediately ahead of Pascal (!):


 	  rank:  46               (462 entries)  Jq
          rank:  47               (447 entries)  PASCAL
          rank:  48               (446 entries)  Forth
          rank:  49               (434 entries)  AWK
          rank:  50  [tied]       (429 entries)  R
          rank:  50  [tied]       (429 entries)  Rust
          rank:  52               (407 entries)  Seed7
          rank:  53               (403 entries)  PL/I
          rank:  54               (400 entries)  PHP
          rank:  55               (399 entries)  Groovy
          rank:  56               (362 entries)  MATLAB
          rank:  57               (361 entries)  Scheme
          rank:  58               (343 entries)  Maple
          rank:  59  [tied]       (334 entries)  Liberty BASIC
          rank:  59  [tied]       (334 entries)  Swift

**Comment by nicowilliams** [comment]
Thanks @pkoppstein.  I used that link in an update to the talk page.  Let's see how it goes from here.

**Comment by pkoppstein** [comment]
@nicowilliams - I think it's very odd that the following page contains no reference to deleting the jq article, even though the article was deleted very recently:

https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion

Perhaps there are grounds for thinking that the deletion was improperly performed.

The undeletion process is supposed to involve discussion with the party responsible for the deletion, but Cryptic's home page says:

> Ask someone else if you need a prompt reply. Since I'm mostly involved in deletions, WP:REFUND or WP:DRV is a good bet.
