### ISSUE TITLE
ER: programmatic way to test whether a $variable has been set

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#1345]
Currently there does not appear to be a way to test programmatically whether a "dollar-variable" has been set, e.g.

    $ jq -n 'try $a catch null'
    jq: error: a/0 is not defined at <top-level>, line 1:
    try $a catch null    
    jq: 1 compile error

Similarly for `$a?`

This is particularly problematic if one wants to allow, but not require, a variable to be specified on the command line (e.g. using the `--arg <var> <value>` option).

**Comment by nicowilliams** [comment]
We need:

 - `$ARGS`, an array (always set) with all remaining arguments when either of two new CLI arguments, `--args` and `--args-json`, are used
 - `$ARG`, an object with any named arguments (always set)
 - `$ENV`, an object (instead of the `env` builtin), but which is not constructed unless it's needed (i.e., appears to always be present)

**Comment by nicowilliams** [comment]
@pkoppstein See #1346.

**Comment by nicowilliams** [comment]
Oh, and unintentionally this also allows the use of both, filename and positional arguments:

```
$ ./jq -c --arg foo bar '[., $foo, $ARGS]' <(echo null) <(echo '"foobar"') --jsonargs -- '{}' '[]' 1
[null,"bar",{"positional":[{},[],1],"named":{"foo":"bar"}}]
["foobar","bar",{"positional":[{},[],1],"named":{"foo":"bar"}}]
$ 
```

And this demonstrates that `--` works as intended:

```
$ ./jq -c --arg foo bar '[., $foo, $ARGS]' <(echo null) <(echo '"foobar"') --jsonargs '{}' '[]' 1
[null,"bar",{"positional":[{},[],1],"named":{"foo":"bar"}}]
["foobar","bar",{"positional":[{},[],1],"named":{"foo":"bar"}}]
$ ./jq -c --arg foo bar '[., $foo, $ARGS]' <(echo null) <(echo '"foobar"') --args -- -h '{}' '[]' 1
[null,"bar",{"positional":["-h","{}","[]","1"],"named":{"foo":"bar"}}]
["foobar","bar",{"positional":["-h","{}","[]","1"],"named":{"foo":"bar"}}]
$ 
```

**Comment by chancez** [comment]
FWIW it wasn't obvious to me at first how $ARGS helped here, even though I've used it a lot. But since `$ARGS` is always defined, you can now access args from it, and it will return null if the value isn't there. For example, I defined the following function and use it this way:

```
def named(p): $ARGS.named | getpath([p]);

.
| if named("repository") and named("tag") then
    .spec.template.spec.containers[].image = (named("repository") + ":" + named("tag"))
else
    .
end

```
