### ISSUE TITLE
Variable bindings in path() expressions yield error

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#1347]
```
$ jq -c '.a as $x | .b = "b"' <<< '{"a":null,"b":null}'
{"a":null,"b":"b"}
$ jq -c '(.a as $x | .b) = "b"' <<< '{"a":null,"b":null}'
jq: error (at <stdin>:1): Invalid path expression near attempt to access element "b" of {"a":null,"b":null}
$ 
```

The issue here is that the `.a` in the `.a as $x |` isn't part of the path expression, but is treated as such, so then the subsequent `.b` yields an error because the `.` in `.b` refers not to `.a` but to the original input.

The thing to do, evidently, is to bracket the `.a` with `SUBEXP_BEGIN` and `SUBEXP_END`.

**Comment by nicowilliams** [comment]
Closed in `master` with 8cde328.

**Comment by nicowilliams** [comment]
This was reported on IRC.

**Comment by lhunath** [comment]
This issue also occurs as a result of `getpath`:

    jq '( (path(.[])) as $x | getpath($x) | .a ) = "x"' <<< '[{"a": null}]'

**Comment by nicowilliams** [comment]
@lhunath Now that's interesting.  Yeah, `getpath` does not play by the path rules.  Mind you, here there's a workaround: just use `.[].a = "x"`, but yeah, there are legitimate uses of `getpath` in path expressions.
