### ISSUE TITLE
`strftime` first calls `gmtime`, but it's not always the right thing to do

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#1349]
https://gist.github.com/awaxa/f7f4693c9601539c087f93631227ff96

**Comment by nicowilliams** [comment]
This is really a design bug.  Not sure how to fix it now.

**Comment by nicowilliams** [comment]
We need `tm` time in order to call `strftime()`, so we need to know a priori if the input is in UTC or not.  We don't get to find out.  We probably need a new builtin for this, `strflocaltime` or something.

**Comment by nicowilliams** [comment]
Fixed by adding `strflocaltime()`.

**Comment by awaxa** [comment]
Very cool!  Thank you @nicowilliams!

```shell
jq --version ; node -e 'console.log(JSON.stringify({date: (new Date).getTime()}))' | jq '.date/1000 | strftime("%Y-%m-%d %H:%M:%S %Z")'
jq-1.5
"2017-02-24 06:44:37 PST"
```

```shell
./jq --version ; node -e 'console.log(JSON.stringify({date: (new Date).getTime()}))' | ./jq '.date/1000 | strflocaltime("%Y-%m-%d %H:%M:%S %Z")'
jq-1.5rc2-188-g27c29ae
"2017-02-23 22:44:53 PST"
```

**Comment by nicowilliams** [comment]
@awaxa I really should have thought of to do this when we added the date builtins in the first place.  Anyways, you're welcome, and I'm glad it works for you.

**Comment by pvdb** [comment]
Just checking: even though I can confirm that `strflocaltime()` in the development version is awesome, it looks like it doesn't do the right thing for `%z` and `%Z` AFAICT, unless I'm missing something obvious 😕
