### ISSUE TITLE
Release 1.6!

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#1352]
We now have the CI builds passing again.  We can now start thinking about what else to pull, what else to fix, and when to release.

**Comment by pkoppstein** [comment]
1. The online manual has the following mangled text, which also appears in the current manual.yml:

    try repeat(exp) catch .=="break" then empty else error;

I believe that should be:

    try repeat(exp) catch if .=="break" then empty else error end

2. Please consider https://github.com/stedolan/jq/pull/1354

3. As you probably know, I'd favor having an official release (whether 1.5.1 or 1.6) ASAP or at least before incorporating any changes that are non-trivial.

Thanks.

**Comment by nicowilliams** [comment]
There will be no 1.5.1 release.  Only 1.6.

I've already begun selecting what remaining open issues will be closed in 1.6 and which will be closed later.

Work in-progress will complete unless it gets gummed up.

Bugs will get fixed.

There is no urgency.  The maintainers are volunteers.  If you need something that's in `master`, build from git.

**Comment by luisdavim** [comment]
any idea when 1.6 is comming out?

**Comment by ronabop** [comment]
Has something specific gotten gummed up, or is there a specific area of work that needs more volunteers?

**Comment by daurnimator** [comment]
Would love to see this release happen. I really want to be able to use `@base64d`!

**Comment by nVitius** [comment]
Having to build `jq` from source every time I want to install on a new machine. It would be great to have an official 1.6 release.

**Comment by nicowilliams** [comment]
1.6rc1 tagged.  Let's make a release of that tonight.

**Comment by nugend** [comment]
Are 1.6rc1 prebuilt binaries going to be created?

**Comment by kastiglione** [comment]
Any update on a new release?

**Comment by eyalzek** [comment]
I don't tend to +1 but what's blocking this?

**Comment by andreyev-melo-movile** [comment]
Please release a new version ASAP!!

TIA!
--
Andreyev

**Comment by zmwangx** [comment]
Shouting doesn't help, it only irritates people.

**Comment by andreyev** [comment]
Ooops, I'm so sorry if my last comment sounds shouting... :-( It's late night and I've spent a couple of hours in a 1.5 version's bug so I don't choose carefully my words, so please apologize me! (I've built 1.6 and the bug gone! :-) )

Did you have any plans to release a new version? There's something we could do to help you with this?

Thanks for the great work with jq!

**Comment by lovelyzoo** [comment]
Just adding my name to the chorus here. An install of 1.6rc1 from Appveyor resolves an issue that was preventing deployment.

Any word on the release date?
And, echoing others, thanks for your efforts.

**Comment by zmwangx** [comment]
@wtlangford The tarball https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.tar.gz is a little weird:

```console
$ tar tf jq-1.6.tar.gz
./._jq-1.6
jq-1.6/
jq-1.6/._.github
jq-1.6/.github/
jq-1.6/._.gitmodules
jq-1.6/.gitmodules
jq-1.6/._.travis.yml
jq-1.6/.travis.yml
jq-1.6/._appveyor.yml
jq-1.6/appveyor.yml
jq-1.6/._AUTHORS
jq-1.6/AUTHORS
jq-1.6/._build
jq-1.6/build/
jq-1.6/._ChangeLog
jq-1.6/ChangeLog
jq-1.6/._compile-ios.sh
jq-1.6/compile-ios.sh
jq-1.6/._config
jq-1.6/config/
jq-1.6/._configure.ac
jq-1.6/configure.ac
jq-1.6/._COPYING
jq-1.6/COPYING
...
```

Also it doesn't contain a `configure` script, which was part of previous release tarballs. It would be nice to not have to run `autoreconf` for a release.

**Comment by wtlangford** [comment]
Ah, my bad. That weirdness is from my mac. I'll fix that and also run `autoreconf`.

**Comment by wtlangford** [comment]
I've pushed up corrected source tarballs.

**Comment by zmwangx** [comment]
Cool, thanks.

**Comment by kastiglione** [comment]
Thanks @wtlangford!

**Comment by ljos** [comment]
Is it possible to get proper release notes other than just listing some things, and then saying "and more"? I am trying to update jq-mode for emacs to 1.6, but I don't follow develop so I don't know everything that is new.

**Comment by wtlangford** [comment]
@ljos I'm happy to add more detail to the notes, but I'd need to know what you're looking for/needing. Part of the reason for the sparseness of the notes is that this release took 3 years, and we weren't great about keeping a clean changelog during it, so I had to read through the commit history, and couldn't capture everything.

**Comment by ljos** [comment]
I understand. What I would like is what are the new builtin functions. Are there new keywords? Is there any new syntax? Basically, how has the language changed on the surface?

**Comment by pkoppstein** [comment]
@wtlangford - Just noticed that the NEWS has not been updated: 
https://github.com/stedolan/jq/blob/master/NEWS
