### ISSUE TITLE
Spaces and Bash Variables

### ISSUE THREAD

**Issue by AlexKucera** [stedolan/jq#1362]
I tried to search for a solution and also tried all kinds of variations I can think of but am coming up empty.

I have the following bash script:

```Shell
# Global Environment Variables

function json_var()
{
	result=`cat "$1" | jq '.["$2"]'`
	result="${result%\"}"
	result="${result#\"}"
	echo "$result"
}

export global_config="/Volumes/ProjectsRaid/x_Pipeline/x_AppPlugins/bd_pipeline/global_config.json"

export RAID=`json_var $global_config "project drive"`
echo $RAID
``` 

Which either returns `null` (in this example) or I get `jq: error: syntax error, unexpected IDENT (Unix shell quoting issues?) at <top-level>, line 1:`.

Now if I replace the `$2`with `project drive` so the line reads ```result=`cat "$1" | jq '.["project drive"]'``` the whole thing works as expected. How do I need to set up my quoting or other formatting to make this function work?

**Comment by AlexKucera** [comment]
Btw. the JSON in question looks like this:

```JSON
{
    "project drive": "/Volumes/ProjectsRaid",
    "projects location": "WorkingProjects",
	"pipeline location": "x_Pipeline",
	"project default config": "/Volumes/ProjectsRaid/x_Pipeline/x_AppPlugins/bd_pipeline/project_config.json",
    "project config name": "project_config.json",
    "clients": {
      "name": "client",
      "project": "project"
    }
}
```

**Comment by nicowilliams** [comment]
@AlexKucera 

```
function json_var()
{
        eval set -- $(jq --arg idx "$2" '@sh "\(.[$idx])"' "$1"
        echo "Got: $# $*"
}
```

should do the trick.

**Comment by AlexKucera** [comment]
Thanks Nico. I had to tweak it a little to make it work for my case. But it got me on the right track.

This is what I ended up with:

```Shell
function json_var {
    eval "var=$(jq --arg idx "$2" '@sh "\(.[$idx])"' "$1")"
	echo $var | sed "s/^\([\"']\)\(.*\)\1\$/\2/g" # Strips additional quotes from the beginngin or end
}


export global_config="/Volumes/ProjectsRaid/x_Pipeline/x_AppPlugins/bd_pipeline/global_config.json"
export TESTER=`json_var $global_config "project drive"`

echo $TESTER
```

**Comment by nicowilliams** [comment]
> This is what I ended up with:
>
> function json_var {
>     eval "var=$(jq --arg idx "$2" '@sh "\(.[$idx])"' "$1")"
> 	echo $var | sed "s/^\([\"']\)\(.*\)\1\$/\2/g" # Strips additional quotes from the beginngin or end
> }
>
>
Watch out!  Put $var in double quotes.  Using eval and @sh makes this safe
w.r.t. values that have shell special characters in then, but you have
double-quote $var, else you lose that safety.

**Comment by KempfCreative** [comment]
This discussion just resolved a duplicate question I had as well in regards to using bash variables with spaces in them. Just wanted to give my +1 for this magic, since I have no idea what is going on with the `@sh ...` portion of this.
