### ISSUE TITLE
Recursive modification stepping on its toes

### ISSUE THREAD

**Issue by stanch** [stedolan/jq#1366]
Sorry for the obscure title, but I don’t know how to describe this other than by example. Suppose I have this data:
```
$ jq -n '{a: {b: [1, {b: 3}]}}'
{
  "a": {
    "b": [
      1,
      {
        "b": 3
      }
    ]
  }
}
```
Now I want to replace `.b` with `.b[0]` wherever `.b` is an array, i.e. I want this output:
```
{
  "a": {
    "b": 1
  }
}
```
Here is what I tried:
```
$ jq -n '{a: {b: [1, {b: 3}]}} | (.. | objects | select(has("b"))) |= .b[0]'
jq: error (at <unknown>): Cannot index number with string "b"
```
My understanding is that after the replacement the path to the inner `b` (`.a.b[1].b`), which is already found, becomes invalid, because `.a.b` is now a number. I then tried to select arrays only, however this does not seem to be possible:
```
$ jq -n '{a: {b: [1, {b: 3}]}} | (.. | objects | select(has("b") and (.b | type == "array"))) |= .b[0]'
jq: error (at <unknown>): Invalid path expression with result {"b":[1,{"b":3}]}
```
**Is there any way I can make this recursive modification?** Currently I am using the following workaround:
```
$ jq -n '{a: {b: [1, {b: 3}]}} | (.. | objects | select(has("b"))) |= if .b | type == "array" then .b |= .[0:1] else . end | (.. | objects | select(has("b"))) |= .b[0]'
{
  "a": 1
}
```
The idea above is to trim the array first, without changing its type. This removes the inner `b`, allowing to apply the modification.

**Comment by nicowilliams** [comment]
The title is not obscure at all.

This works for me: `jq -cn '{a: {b: [1, {b: 3}]}} | (.. | objects | select(has("b"))|.b|select(type=="array")) |= .[0]'`, which produces `{"a":{"b":1}}`.

**Comment by nicowilliams** [comment]
The case where you got `Invalid path expression with result ...` is a bug.  We should fix it.

**Comment by pkoppstein** [comment]
If your jq has `walk/1` then you can use this filter:

    walk(if type == "object" and has("b") and (.b|type) == "array" then .b |= .[0] else . end)

If not, its definition in jq is on the jq FAQ and can also easily be found by googling (e.g.: def walk jq faq)

**Comment by stanch** [comment]
Thanks guys! I’ll go with `walk`, I think it’s a bit easier on the eye ;) Completely forgot this existed!
