### ISSUE TITLE
Apostrophe or single quote in value opens prompt

### ISSUE THREAD

**Issue by bobbintb** [stedolan/jq#1372]
I am getting strange behavior when parsing an element with an `'`. For example, this:

`jq '.Main[] | .Items[] | select( .ItemName== "My item" ) | .Status'`

will return `false`, which is correct. But this:

`jq '.Main[] | .Items[] | select( .ItemName== "Bob's  item" ) | .Status'`

will just go into a prompt like this: `>` and I have to force close to go back to the command line. I tried escaping the `'` with `/` but it didn't work. From what I understand, I shouldn't even have to escape an `'`. Any idea what is wrong?

**Comment by pkoppstein** [comment]
This is a shell issue.  If you use a single quote as the string delimiter, you have to be careful bout using the single quote within the string.

For future reference, please ask usage questions at stackoverflow.com with the jq tag.

**Comment by bobbintb** [comment]
Yes, thank you. I see the issue now. It seemed more like a bug at the time. My fault.

**Comment by pkoppstein** [comment]
@bobbintb - No problem.  Many of us have been there.  For future reference, it would be helpful if you could "close" issues that you've opened and that have been resolved. Thanks.
