### ISSUE TITLE
Top level variable not available in function definition

### ISSUE THREAD

**Issue by ml019** [stedolan/jq#1375]
I am attempting to process a JSON based swagger definition and augment the API methods to add the specifics of AWS API Gateway integration. It involves walking the tree and adding an attribute to the objects representing each method. 

I provide the swagger file as the first command line file, and the boilerplate JSON to be added in a second file, along with the slurp option, e.g.

```
jq -s -f filter.jq swagger.json template.json
```

I've run across an issue with variable scoping so have simplified the issue as much as possible.

When I run the filter below, it fails (jq-1.5) with 

```
jq: error: template/0 is not defined at <top-level>, line 3:
 . + {"x-amazon-apigateway-integration" : $template }
```

whereas if I switch to the commented out line, I get the contents of the swagger file plus the extra attribute I am expecting.

I've tried various combinations of bracketing without success. Is there something about variable scoping and functions that I've missed?

Thanks

Filter:-

```
def walk:
 . + {"x-amazon-apigateway-integration" : $template }
;
.[1] as $template | .[0] | walk
# .[1] as $template | .[0] | . + {"x-amazon-apigateway-integration" : $template }
```

**Comment by nicowilliams** [comment]
Can you use github markdown quoting and show us the exact command-line invocation?  Use backticks to quote jq programs and shell commands in github issues/comments.

**Comment by pkoppstein** [comment]
@ml019 - In your definition:

    def walk: . + {"x-amazon-apigateway-integration" : $template } ;

the "dollar-variable" can only refer to a global variable, as declared on the command line.

It looks like you should define `walk/1` (e.g. "def walk(template): ...." or perhaps "def walk($template): ...") so you can pass in the value.

**Comment by ml019** [comment]
In the complete example, I am using a parameter on the walk function to determine when I am on the correct object

```
def walk_with_parent($parentKey):
  . as $in
  | if type == "object" then
      reduce keys[] as $key ( {}; 
                . + { ($key):  ($in[$key] | walk_with_parent($key)) }
        ) |
        if $parentKey and ($parentKey | test("get|put|patch|post|delete|options|head")) then
            . + {"x-amazon-apigateway-integration" : $template }
        else
            .
        end
  else
    .
  end;

.[1] as $template | .[0] | walk_with_parent(null)
```
I've had no success passing two argments to a function, but if that is possible, I will switch to passing the template in as an argument as well.

**Comment by ml019** [comment]
As a workaround, I've moved the template to a command line argument so it will be global.

```
TEMPLATE="$(jq -c '.' template.json)"
jq -f filter.jq --argjson template "${TEMPLATE}" swagger.json
```

and filter.jq:-

```
def walk_with_parent($parentKey):
  . as $in
  | if type == "object" then
      reduce keys[] as $key ( {}; 
                . + { ($key):  ($in[$key] | walk_with_parent($key)) }
        ) |
        if $parentKey and ($parentKey | test("get|put|patch|post|delete|options|head")) then
            . + {"x-amazon-apigateway-integration" : $template }
        else
            .
        end
  else
    .
  end;

walk_with_parent(null)
```

**Comment by pkoppstein** [comment]
Note that a two-parameter function has to be defined (and invoked) using ; rather than ,

**Comment by nicowilliams** [comment]
@ml019 jq is lexically scoped, which means that any one piece of jq program can only "see" names that can statically be found looking backwards "to the left".  So, `. as $foo | $foo` works, but `def bar: $foo;` does not unless `$foo` is a binding defined on the command-line.

Here's a whacky example:

```
$ jq 'def foo: . as $bar | def bar: $bar; bar; foo'
```

works!  While this one does not:

```
$ jq 'def foo: . as $bar | def bar: $not_there; bar;
        # this binding is not visible in the bar function:
        5 as $not_there | foo'
```

In a language like, say, bash, that has dynamic variables, that sort of code would work.  But jq is lexically bound.
