### ISSUE TITLE
Is there a way to use hashmap/list as condition building block?

### ISSUE THREAD

**Issue by int8** [stedolan/jq#1376]
Hi there, 

I have set of jsons in a file as input 

I am looking for a way to keep only those objects that meet the following (pseudo-jq) condition: 

single_json[key] IN  List 

where List is predefined list of values (around 50k) - stored in another file (lets say one value per line) 

Is smth like that possible and feasible? thanks

**Comment by pkoppstein** [comment]
@int8 - Yes, and yes.  Please post your question at stackoverflow.com using the jq tag.  That way, it's more likely that other people will benefit from the answer(s).  You might also benefit from having a variety of responses to choose from.

**Comment by int8** [comment]
thanks, done that: http://stackoverflow.com/questions/43089326/is-there-a-way-to-use-hashmap-list-as-jq-tool-condition-building-block
