### ISSUE TITLE
double quotes in filter expression magically disappear when run under Powershell

### ISSUE THREAD

**Issue by yizhong-ms** [stedolan/jq#1377]
```
jq '.a == "x"'
```
This works fine in Bash, but not in Powershell:

```
PS> jq '.a == "x"'
jq: error: x/0 is not defined at <top-level>, line 1:
.a == x
jq: 1 compile error

PS> echo '.a == "x"'
.a == "x"

PS> jq --version
jq-1.5
```

It seems that the double quotes are gone. Why?

**Comment by nicowilliams** [comment]
I've no idea what the quoting rules are for PowerShell, but I just tried it and it looks like you have to backslash escape those double quotes.  Go figure.

http://windowsitpro.com/blog/single-quotes-vs-double-quotes-powershell-whats-difference
https://www.simple-talk.com/sysadmin/powershell/when-to-quote-in-powershell/
https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Quoting_Rules
http://jon.netdork.net/2015/09/08/powershell-and-single-vs-double-quotes/

**Comment by nicowilliams** [comment]
I should add that there's nothing jq can do about the shell.  You could try running the Ubuntu on Windows thing...  Or Cygwin, or MinGW.

**Comment by yizhong-ms** [comment]
I did try on Git Bash and it worked...

Seems to be a known powershell issue:

http://stackoverflow.com/questions/6714165/powershell-stripping-double-quotes-from-command-line-arguments

**Comment by jgeorgeson** [comment]
triple-quote works for me

```
> get-content -raw inventory.json | jq '._meta.hostvars[]|select(.system_os_name != """Linux""")|.ip'
```
