### ISSUE TITLE
Can't pipe jq output to jq input

### ISSUE THREAD

**Issue by rlipscombe** [stedolan/jq#1378]
I have a script that does something like the following:

    curl -s $URL | jq

The trailing `| jq` is to pretty-print the output. This all works fine.

However, when I go to further filter the output with `jq` (as in `./myscript | jq '...'`), it doesn't do anything; it just prints the usage help. To reproduce:

    cat foo.json | jq | jq    # doesn't work

If I add '.' as the filter expression to the first `jq`, it works as expected:

    cat foo.json | jq '.' | jq    # does work

I'd kinda expected the change in jq 1.5 that made '.' implicit to work in this case as well.

**Comment by wtlangford** [comment]
Yes, this is a common complaint. There have been many issues about it.

We have fixed it (changed the behavior) in the latest master.

**Comment by rlipscombe** [comment]
Thanks. I look forward to a 1.6 release.

**Comment by nicowilliams** [comment]
We should never have made the program optional.
