### ISSUE TITLE
Question: Referencing top-level JSON arguments using input object expression

### ISSUE THREAD

**Issue by jmdacruz** [stedolan/jq#1382]
Given that the following is possible:

```shell
echo '{"id": "1"}' | jq '$objects[.id]' --argjson objects '{"1": {"value": "one"}, "2": {"value": "two"}}'
```
produces the following output:
```json
{
  "value": "one"
}
```

And:
```shell
echo '{"id": "2"}' | jq '$objects[.id]' --argjson objects '{"1": {"value": "one"}, "2": {"value": "two"}}'
```
produces the following output:
```json
{
  "value": "two"
}
```

I'm wondering if there is an expression `XYZ` in the line below that would have the same effect:
```shell
echo '{"id": "1"}' | jq '$XYZ' --argjson "1" '{"value": "one"}' --argjson "2" '{"value": "two"}'
```

Basically, I'm trying to figure out if I can achieve the same effect but for all top-level `argjson` arguments passed to the command line, instead of having to use a big object that I can index dynamically using the input to the transform.

Any thoughts? Is this possible?

**Comment by wtlangford** [comment]
To start, we do prefer that usage questions go to either https://stackoverflow.com/questions/tagged/jq or #jq on freenode.

That said, we do have `$ARGS` on master, which could solve your problem.

Perhaps something like this:
```
echo '{"id": "1"}' | jq --argjson "1" "..." --argjson "2" "..." '$ARGS.named[.id]'
```

Additionally, I'm not sure what you're hoping to achieve in this way.  I'd be concerned that as your task scales, you'll run into the command line length maximum.

**Comment by jmdacruz** [comment]
Thanks @wtlangford! I'm actually using pyjq, which I understand is compiled against jq 1.5, so this feature probably won't be there. In any case I can "simulate" it by providing an `argjson` object that looks exactly like the one you describe above. I guess this should do the trick. Also, I assume pyjq is compiled against the underlying jq libraries (and not forking the jq command line) hence the command line length should not be a problem. 

Also, thanks for pointing out the IRC channel, I'll be sure to use that from now on.

**Comment by wtlangford** [comment]
Hm, I'm not sure about pyjq. I'd have to look. Argjson is a feature of the
jq binary where it adds global variable bindings for those parameters. Pyjq
could be doing something similar, or it could be forking. If it's forking,
I might recommend a different approach. The one large object won't be any
slower in jq, and it could be loaded in with --argfile.

**Comment by jmdacruz** [comment]
Got it. You can take a look at pyjq here: https://github.com/doloopwhile/pyjq

**Comment by nicowilliams** [comment]
@jmdacruz Is that a fork of https://github.com/mwilliamson/jq.py?

Anyways, Python supports generators.  jq expressions are generators.  Ergo Python bindings of jq should be generators.  Accumulating all outputs of a jq expression is not as good nor performant as making the evaluator a generator.

**Comment by jmdacruz** [comment]
@nicowilliams Not sure, but I think they are quite different.
