### ISSUE TITLE
yylex error when rebuilding lexer.c

### ISSUE THREAD

**Issue by svnpenn** [stedolan/jq#1386]
When my system builds "src/lexer.c" and "src/lexer.h", it adds this line among
others:

~~~c
#define yylex jq_yylex
~~~

This causes a big problem:

~~~
In file included from src/parser.y:124:0:
src/lexer.h:44:19: error: conflicting types for ‘jq_yylex’
src/parser.y:149:5: note: in expansion of macro ‘yylex’
 int yylex(YYSTYPE* yylval, YYLTYPE* yylloc, block* answer, int* errors,
     ^
In file included from src/parser.y:124:0:
src/lexer.h:405:12: note: previous declaration of ‘jq_yylex’ was here
src/parser.y: In function ‘jq_yylex’:
src/parser.y:152:13: error: too few arguments to function ‘jq_yylex’
   int tok = jq_yylex(yylval, yylloc, lexer);
             ^
In file included from src/parser.y:124:0:
src/lexer.h:44:19: note: declared here
src/parser.y:149:5: note: in expansion of macro ‘yylex’
 int yylex(YYSTYPE* yylval, YYLTYPE* yylloc, block* answer, int* errors,
     ^
~~~

As a workaround, I can:

~~~sh
touch src/lexer.c
~~~

Or:

~~~
./configure --disable-maintainer-mode
~~~

but all these do is prevent "src/lexer.c" and "src/lexer.h" from being remade.

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/689

**Comment by wtlangford** [comment]
What are your system's flex/bison versions? (Also, are they flex/bison or lex/yacc?)
Also, what's your system?

**Comment by svnpenn** [comment]
@wtlangford see below:

~~~
$ flex --version
flex 2.6.3

$ bison --version
bison (GNU Bison) 3.0.4

$ uname -a
CYGWIN_NT-6.1 Steven-PC 2.8.0(0.309/5/3) 2017-04-01 20:47 x86_64 Cygwin
~~~

**Comment by svnpenn** [comment]
@wtlangford it is the newer Flex that is causing the problem:

- cygwin 2.6.3 bad
- cygwin 2.6.1 good
- msys2 2.6.3 bad
- msys2 2.6.1 good

**Comment by wtlangford** [comment]
That's... Odd. I would never have found that.
Any idea what specifically broke? Are there maybe some new #defines we need?

**Comment by svnpenn** [comment]
@wtlangford no idea. I have never built flex, so I am trying to do that now so I can "git bisect"

**Comment by svnpenn** [comment]
https://github.com/westes/flex/issues/160

**Comment by svnpenn** [comment]
https://github.com/westes/flex/issues/162

**Comment by svnpenn** [comment]
@wtlangford see https://github.com/westes/flex/issues/162 - issue has been fixed on master and will be on 2.6.4 when it is released

**Comment by svnpenn** [comment]
@wtlangford see https://github.com/westes/flex/issues/162 - issue has been fixed
on master and will be on 2.6.4 when it is released.

I think I will close this. It is a Flex issue not a JQ issue. Plus I dont really
have a good reason to rebuild lexer.c anyway. I have added
`--disable-maintainer-mode` to my build script:

http://github.com/svnpenn/glade/blob/1cb67d6/jq/install.sh#L6-L7

and removed Flex and Bison from my makefile:

http://github.com/svnpenn/glade/blob/1cb67d6/jq/makefile#L4

**Comment by therealromster** [comment]
Just patch flex 2.6.3 or downgrade to 2.6.2 https://crux.nu/ports/crux-3.2/core/flex/flex-2.6.3-add_defines.patch
