### ISSUE TITLE
-1 index doesn't work

### ISSUE THREAD

**Issue by oscarcappa** [stedolan/jq#1388]
Hi, the "-1" index doesn't work, this is my output.
pi@serverPI:~ $ echo $RESULT | jq '.result' | jq length
3 # an information
pi@serverPI:~ $ echo $RESULT | jq '.result[-1].update_id'
null # the issue
pi@serverPI:~ $ echo $RESULT | jq '.result[2].update_id'
723200 # Data is available
pi@serverPI:~ $ echo $RESULT | jq '.result[3].update_id'
null # test...
pi@serverPI:~ $
# thank you

**Comment by pkoppstein** [comment]
1. The feature allowing negative integers to be used to count backwards was introduced in jq version 1.5, so it looks like you are using an earlier version of jq.  

2. For future reference, when reporting an issue, please don't forget the jq version number as well as a "minimal complete verifiable example" (http://stackoverflow.com/help/mcve).  Thanks.

**Comment by oscarcappa** [comment]
Thank you, it is my first report on github :-)
I took it from "apt-get install jq" on raspbian
pi@serverPI:~ $ jq
jq - commandline JSON processor [version 1.4-1-e73951f]
You hit the target!
Thank you
