### ISSUE TITLE
Contributing jq modules/recipes 

### ISSUE THREAD

**Issue by rupenp** [stedolan/jq#1392]
Hi 

I use jq a lot for data-wrangling with Twitter and other open-datasets. And over the course I have written several jq scripts, which I would like to share. I was wondering what is the right mechanism for sharing or adding to the codebase on the official jq repository?  More specifically, how to share non-builtins jq helper functions? 

This is analogous to Python package index or docker hub where folks can share what they have built  and also prevent some of the builtin bloats!

**Comment by nichtich** [comment]
See #535 and https://github.com/stedolan/jq/wiki/Modules, so this issue can be closed.
