### ISSUE TITLE
ENOMEM conditions should be reported as such

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#1393]
The current version of jq crashes when processing a very large JSON document, though it can read the file (jq .), and can correctly process similar but smaller versions of the same document.

First, here's the problem:

```
$ cat features.jq
.features |= map(.tippecanoe.minzoom = 13) 
| .features | length

$ jq -f features.jq /tmp/10000000.json
jq: error (at /tmp/10000000.json:60000004): Invalid path expression near attempt to access element "features" of {"features":[{"type":"Feat...
```

Second, here's how the input file was generated:

`$ jq --argjson N 10000000 '{"features": [range(0;$N) | {"type":"Feature", "properties": {"FEATCODE": 15014}}] }'`

Third, here's evidence the file can be read successfully (though slowly):

```
$ time jq '.features | length' /tmp/10000000.json
10000000

real	4m16.365s
user	1m31.759s
sys	1m15.459s

```
Fourth, some details about jq and the environment:

```
$ jq --version
jq-1.5rc2-233-g4b4cf78

$ uname -a
Darwin Mac-mini.local 13.4.0 Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64 x86_64

```

**Comment by nicowilliams** [comment]
That's... not a crash.

**Comment by nicowilliams** [comment]
This happens even with `N` == 10.

**Comment by nicowilliams** [comment]
On my system jq dies.  I suspect `ENOMEM` or running out of stack.

**Comment by nicowilliams** [comment]
@pkoppstein So, what are you trying to accomplish?  Perhaps we can find a more efficient way to do it.

**Comment by pkoppstein** [comment]
> what are you trying to accomplish?

See https://stackoverflow.com/questions/43469103/process-huge-geojson-file-with-jq. 

In brief, the main goal is to find an efficient way to perform the update on a very large file. I was in the process of characterizing the performance of each of the following:

    .features |= map(.tippecanoe.minzoom = 13) 

    .features[].tippecanoe.minzoom = 13

Thanks.

**Comment by nicowilliams** [comment]
Streaming should be the answer.  Yes, I know, streaming is not as fast as it should be.  Also, we need an output-side streamer that outputs values assembled from a stream but without having to assemble them in memory.

**Comment by nicowilliams** [comment]
I don't think there's a real serious problem here.  The file you're using is 896MB.  That's rather big.  If the array in question has just two references during evaluation of the jq program then you'll end up consuming twice that much and twice the overhead for the internal representation of the parsed JSON.  That's a lot of RAM.

**Comment by nicowilliams** [comment]
However, we do need new features to make processing huge files possible:

 - we need to improve the streaming parser so that it is faster by reusing the path output value and modifying for each new result

 - we need an output mode (or builtin to be used with `--raw-output`) that reconstitutes a stream into a proper JSON text

These two features should make it possible to process huge texts, though, of course, processing a streamed text requires writing jq code rather differently.

**Comment by pkoppstein** [comment]
@nicowilliams -

As I see it, the first order of business here is to get jq to issue an appropriate ENOMEM error. The actual error I encountered is quite misleading in several respects, e.g. it complains about the input file, even though jq is able to read the file in its entirety:

>    jq: error (at /tmp/10000000.json:60000004): Invalid path expression near attempt to access element "features" of {"features":[{"type":"Feat...

Should I open another ER about that?

As you point out, currently it seems unlikely that `--stream` is the solution to this particular type of problem as it requires an efficient way to reconstitute the JSON.

I would like to believe that jq could handle `.features |= map(.tippecanoe.minzoom = 13) ` super-efficiently.  Is that really impossible?

**Comment by nicowilliams** [comment]
@pkoppstein True, though I'll have to inject ENOMEM, both for testing and for the purpose of reproducing.

**Comment by nicowilliams** [comment]
No, `--stream` is the solution, since it is possible to reconstitute the JSON efficiently (just output it in pieces).

(Mind you, `--stream` can't help if you have huge strings.)

**Comment by nicowilliams** [comment]
This might be a good time to introduce a special (constant) invalid `jv` for indicating `ENOMEM`.  It'd be nice if all `jv` functions could accept such an input and return the same.

**Comment by pkoppstein** [comment]
@nicowilliams - At the aforementioned stackoverflow.com page, I posted jq-only and jq-awk solutions to the problem that complete for N=10,000,000 (file size: 940MB). 

u+s times on my tired old machine are:

jq-only: 15m 15s
jq-awk:   7m 40s

If you could provide a --stream solution, I could post comparable numbers ...

**Comment by nicowilliams** [comment]
@pkoppstein Here's a start:

```
./jq -cn --stream 'foreach inputs as $i ({prev:-1,first:null};
if $i[0][0] != "features" or $i[0][1] == .prev then . else .prev = $i[0][1] | .first = $i end;
if $i != .first then $i else [["features",$i[0][1],"tippecanoe","minzoom"],13], [["features",$i[0][1],"tippecanoe"]], $i end)' /tmp/huge.json
```

This inserts the necessary streamed entries.

Reconstructing a JSON text in a streaming way is an exercise for later.

**Comment by nicowilliams** [comment]
Also, I've pushed 0bd7614, which may make jq fail better for you.

**Comment by nicowilliams** [comment]
Almost perfect:

```
$ ./jq -cnr --stream '
    "[",
    foreach fromstream(2|truncate_stream(inputs) |
                                     if (.[0]|length == 1) and (.|length == 1)
                                     then [["tippecanoe","minzoom"],13],[["tippecanoe","minzoom"]],[["tippecanoe"]]
                                     else . end) as $o (0;
                                                                 if .==0 then 1 else 2 end; if .==1 then $o else ",", $o end),"]"' /tmp/huge.json
```

(Missing is the `{features: ... }` wrapper.)

It's slow because streaming has that garbage non-reuse bug :(

**Comment by pkoppstein** [comment]
> I've pushed 0bd7614, which may make jq fail better for you.

Dang, now it doesn't crash!!!  :-)

**Comment by nicowilliams** [comment]
Thanks for confirming!

**Comment by pkoppstein** [comment]
> EDIT: It took 7.5m:

On the aforementioned tired old machine, I get:

```
real	18m14.782s
user	16m31.969s
sys	0m5.003s
```

So (except for the small detail about the memory footprint) awk wins :-)
