### ISSUE TITLE
Accessing fields that contain a special character

### ISSUE THREAD

**Issue by lanthaler** [stedolan/jq#140]
It seems as there's no way to access a field which contains a special character such as `@` or `$`. For example, let's say I want to extract the value of the `@id` member from the following document

```
{
  "@id": "http://example.com/",
  "desc": "cannot extract value of @id member"
}
```

`jq .@context file.json` fails with the following error:

```
error: syntax error, unexpected FORMAT, expecting $end
.@id
 ^^^
1 compile error
```

**Comment by joshzitting** [comment]
I am having a similar issue. my json looks like this 
`{
  "_t": "JSONObject",
  "192-168-100-100": {
    "ipAddress": "192.168.100.100",
    "cpuLoad": 30,
    "_t": "JSONObject",
    "callersOnHold": 1
}
}`
And I need to access callersOnHold
But I cant get to/past the "192-168-100-100"
jq ".192-168-100-100" status

This is on ubuntu.. Thanks for any help in advance!

**Comment by slapresta** [comment]
@joshzitting `jq '.["192-168-100-100"]'

**Comment by joshzitting** [comment]
@slapresta oh my heck! thank you! I swear I have tried every variation!

**Comment by slapresta** [comment]
No problem! For other usage questions, please head over to [StackOverflow's `jq` tag](http://stackoverflow.com/tags/jq)

**Comment by PatrickAlphaC** [comment]
Not sure if something was updated, but the following worked for me on MacOS bash shell. 

```bash
jq '."@id"' test.json
```

**Comment by CN-tan** [comment]
this works for me, thanks a lot.

**Comment by vakenbolt** [comment]
@PatrickAlphaC Works for me as well on Mac OS. Thanks for posting! 🙏

**Comment by alexandraveres7** [comment]
@PatrickAlphaC worked on Rocky Linux as well. thank you!

**Comment by dexmagic** [comment]
Adding another example to help others who ran into this.

what alexandravres7 wrote works for me too. Given this input
```json
{
    "symbol": "CHTR",
    "status": "SUCCESS",
    "callExpDateMap": {
        "2023-06-16:9": {
            "155.0": [
                {
                    "putCall": "CALL"
                }
             ]
        }
    }
}
```

the following command works as expeected:

```
$ jq '.symbol, .status, .callExpDateMap."2023-06-16:9"' options.json  
"CHTR"
"SUCCESS"
{
  "155.0": [
    {
      "putCall": "CALL"
    }
  ]
}
```
