### ISSUE TITLE
@base64d fails

### ISSUE THREAD

**Issue by srfrnk** [stedolan/jq#1408]
When running the following:
```
echo '"blah"' | jq '@base64' | jq '@base64d'
```

I get:
```
jq: error (at <stdin>:1): base64d is not a valid format
```

This should always work right? Am I missing something?

`jq --version` is `jq-1.5-1-a5b5cbe`

OS:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Comment by wtlangford** [comment]
`@base64d` was only added recently (post 1.5).  Until we release a new version, you'll have to build `master` to get `@base64d`

**Comment by yellowmegaman** [comment]
hi! 1.5 seems to include base64d https://github.com/stedolan/jq/releases/tag/jq-1.5
but it ain't working

**Comment by eaviles** [comment]
Is 1.6 going to be released soon?

**Comment by Sylvain303** [comment]
Still not on recent distribution

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

jq version

```bash
$ jq --version
jq-1.5-1-a5b5cbe
```

```bash
$ echo '"blah"' | jq '@base64' | jq '@base64d'
jq: error (at <stdin>:1): base64d is not a valid format
```

It would be nice to tag the documentation that it starts at some version: 

https://stedolan.github.io/jq/manual/#Formatstringsandescaping

**Comment by pkoppstein** [comment]
> It would be nice to tag the documentation that it starts at some version:

Sure, but in the meantime, please note that at the top of the page you reference, it does say "jq Manual (development version)", and also gives pointers to the various different releases.
