### ISSUE TITLE
src/jv_unicode.c:12: const char *jvp_utf8_backtrack(const char *, const char *, int *): Assertion `min < start` failed.

### ISSUE THREAD

**Issue by mateon1** [stedolan/jq#1410]
Hello, I am fuzzing jq with afl-fuzz, and within a few seconds of starting this assert failure was found.

To reproduce:

1. Create a file `pattern.jq` containing a single `@` symbol (without a newline);
`$ echo -n '@' > pattern.jq`
2. Run `jq -f pattern.jq`
```
$ jq -f pattern.jq
jq: src/jv_unicode.c:12: const char *jvp_utf8_backtrack(const char *, const char *, int *): Assertion `min < start' failed.
Aborted
```

**Comment by pkoppstein** [comment]
@mateon1 - Thanks for the report.  In future, it would probably be a good idea to indicate the jq version.  I can confirm the problem exists in the currently-most-recent version on master:

```
$ jq --version
jq-1.5rc2-237-gcb3d5af

$ jq -n -f /tmp/pattern.jq
Assertion failed: (min < start), function jvp_utf8_backtrack, file src/jv_unicode.c, line 12.
```

**Comment by mateon1** [comment]
@pkoppstein Ah, no problem. I should have mentioned I used latest master, but you got that.

**Comment by nicowilliams** [comment]
```
diff --git a/src/jv_unicode.c b/src/jv_unicode.c
index b3a50b2..d197349 100644
--- a/src/jv_unicode.c
+++ b/src/jv_unicode.c
@@ -9,7 +9,7 @@
 // *missing_bytes.  If there are no leading bytes or an invalid byte is
 // encountered, NULL is returned and *missing_bytes is not altered.
 const char* jvp_utf8_backtrack(const char* start, const char* min, int *missing_bytes) {
-  assert(min < start);
+  assert(min <= start);
   if (min == start) {
     return min;
   }
```

Feel free to apply that in your tree so you can keep fuzzing.

Thanks for the report!

**Comment by mateon1** [comment]
@nicowilliams Please note that this patch is not an actual fix, it just makes this crash rarer.
This assertion still fails for empty input files, and files with "interesting" file sizes, like 4096, 8192, 32768

**Comment by nicowilliams** [comment]
@mateon1 Oh, I see.  Got it.
