### ISSUE TITLE
Has a runtime dependency on ubuntu

### ISSUE THREAD

**Issue by skaffen2** [stedolan/jq#1412]
On the home page is written: "jq is written in portable C, and it has zero runtime dependencies."

However when I go to install it on ubuntu 16.4, it says:

The following additional packages will be installed:
  libonig2
The following NEW packages will be installed:
  jq libonig2

libonig2 is a runtime dependency, so the statement about zero runtime dependencies is not true.  I suggest that sentence is changed to mention the dependency on the regex library.

**Comment by nicowilliams** [comment]
jq now has Oniguruma built-in.  Ubuntu and others, when 1.6 comes out, should build jq with the built-in Oniguruma.
