### ISSUE TITLE
Lots of compiler warnings on macOS 10.12

### ISSUE THREAD

**Issue by chdiza** [stedolan/jq#1416]
On macOS 10.12 building from master, I see a lot of compiler warnings.  I have no idea whether these are important or whether they're related to the test failures I reported in #1415.  The warnings I see are here: https://gist.github.com/chdiza/816921374243a6cc46a33c4b3b7a2112

**Comment by nicowilliams** [comment]
Can you post the `config.log` for your build?

**Comment by chdiza** [comment]
My `config.log` is [here](https://gist.github.com/chdiza/670828755cb00b7e14be3efe2fdb7d98).

**Comment by nicowilliams** [comment]
@chdiza Thanks.

**Comment by nicowilliams** [comment]
@chdiza While I've not fixed all of these (and, indeed, some I won't), I've pushed b0d6d28 which might fix the warning about `lgamma_r()` -- can you confirm?

**Comment by chdiza** [comment]
@nicowilliams It did fix the `lgamma_r` warning, thanks.
