### ISSUE TITLE
JQ on Windows: German mutated vowel

### ISSUE THREAD

**Issue by TimoC1982** [stedolan/jq#1418]
Hi guys,

I actually use JQ on Windows (wonderfull tool) to transform different json files for an ETL process. 
Basicly it works as expected. My Problem is that some of the APIs delivers data with mutated vowel (like ä/ö/ü or ß). The original data are in ANSI Format. 
How can i transform that date without the removal of the mutated vowels?

Regards
Timo

**Comment by slapresta** [comment]
It shouldn't cause any problems as long as the data is UTF-8. You mention on the issue that the data is in "ANSI format", which seems unlikely since ANSI doesn't support characters other than basic Latin letters. If you figure out which encoding it's in, you can convert from that encoding to UTF-8 and then pass that to jq.

**Comment by TimoC1982** [comment]
Hi Slapresta,

I checked the Export Encoding. I opened one of the json files with Notepad++ and the Encoder checker gived back: UTF8 without BOM. But get still that erros

**Comment by nicowilliams** [comment]
JSON is Unicode only, and, really, UTF-8 only.  jq does not support using ANSI character data encoding.  You have to use UTF-8, as that's all jq supports.

**Comment by slapresta** [comment]
@TimoC1982 Which errors are you getting? jq will not remove non-ANSI characters for you under any circumstance. Whatever is generating the export may be removing them for you, though.

**Comment by pkoppstein** [comment]
@TimoC1982 - Several methods for converting to UTF-8 on Windows are described here:

https://docs.moodle.org/33/en/Converting_files_to_UTF-8#Windows_computers

If you have access to iconv, you can easily include it in a pipeline along the lines of:

.... | iconv -f ISO-8859-1 -t utf-8 | jq -R .

If you have problems with any of these methods, please let us know, or post a question on stackoverflow.com
