### ISSUE TITLE
--cache feature

### ISSUE THREAD

**Issue by rileytg** [stedolan/jq#1421]
my day to day
```
$ curl mildly-slow-service.com/foo.json | jq '.'
# wait a little
... a lot more than you wanna see ...
$ curl mildly-slow-service.com/foo.json | jq '.firstThingIWant'
# wait a little more
... less, but still more than you wanna see ...
$ curl mildly-slow-service.com/foo.json | jq '.firstThingIWant[0].secondLevel'
# waiting here for the same thing ive already curled twice. k.
... still not what i want ....
$ curl mildly-slow-service.com/foo.json | '.firstThingIWant[0].secondLevel[0]' 
# wait AGAIN
jq: error (at <stdin>:1): Cannot index object with number
```
![picture_2_c](https://cloud.githubusercontent.com/assets/692817/26711908/82a01606-4718-11e7-8a0a-4306431fbf58.jpg)
```
$ curl mildly-slow-service.com/foo.json | '.firstThingIWant[0].secondLevel.theLabelFieldIBeenLookingFor'
# yes, wait again.
... finally see what i want ...
```
![happy-kitteh-smile](https://cloud.githubusercontent.com/assets/692817/26712065/9f655f70-4719-11e7-9713-59315c10f2cd.jpg)

I spend too much requesting the same oversized payloads over and over. I trim down on each invocation of `jq` but wait the curl time each time. (You really feel the pain of a syntax error, especially if ur a `jq` noob.)

I propose a `--cache` flag (with a short flag too)
```
$ curl example.com/foo.json | jq --cache
# wait a little
... too much ...
$ jq --cache '.[0].field'
# no wait 
... ur field ...
```

sorry if this exists and i haven't found it :-/

I gave this a shot with just bash but fell way short. i've made a `jqcurl foo.com` that is `curl $@ > .jqc` and  a `jqc` with: 
```
if [ -f .jqe ]; then 
	cat .jqe | jq $@
fi
```
Usage:
```
$ jqcurl foo.com
$ jqc '.'
$ jqc '.[0]'
# etc
```

I also know i could just write to a file on the first curl, that is what i do. I just like the idea of not polluting my source tree when debugging.

**Comment by rileytg** [comment]
im now using `~/.jq-cache` to avoid polluting source

**Comment by pkoppstein** [comment]
@rileytag - please look at the two jq-based wrappers described at https://stackoverflow.com/questions/41631626/is-there-a-jq-command-line-tool-or-wrapper-which-lets-you-interactively-explore

**Comment by rileytg** [comment]
https://github.com/fiatjaf/jiq

even better than i imagined! thank you!
