### ISSUE TITLE
Escape objects from their parent arrays

### ISSUE THREAD

**Issue by ziyaddin** [stedolan/jq#1424]
After several `jq` operations I got this JSON structure:
```
[
  {
    "foo": 3,
    "bar": "baz"
  }
]
[
  {
    "foo": 2,
    "bar": "baz"
  }
]
[
  {
    "foo": 1,
    "bar": "baz"
  }
]
```

How can I escape all objects from their arrays and have just list of independent objects without any parent arrays by keeping the same order of objects in the whole document?

**Comment by pkoppstein** [comment]
1. `.[]` can be used to achieve the effect you describe, e.g. `[1,2] | .[]` yields the stream consisting of 1 followed by 2. 

2. In future, please ask usage questions at stackoverflow.com using the tag `jq`.  Thanks.

**Comment by ziyaddin** [comment]
Thank you!
