### ISSUE TITLE
'and' operator produces a different number of values depending on the input

### ISSUE THREAD

**Issue by nornagon** [stedolan/jq#1426]
```bash
$ jq -n '(true, true) and (true, false)'
true
false
true
false
$ jq -n '(true, false) and (true, false)'
true
false
false
```

This was surprising to me; I expected to receive N*M results for input streams of size N,M regardless of what the input values are.

(Not that sending multiple input values on both sides of an `and` is a particularly common use case, but this seems inconsistent.)

**Comment by thedward** [comment]
Interestingly:

```sh
$ jq -n '(true, false)|(true, false) and .'
true
false
false
false

$ jq -n '(true, false)|. and .'
true
false

$ jq -n '(true, false) as $x|$x and $x'
true
false

$ jq -n '(true, false) as $x|(true,false) as $y|$x and $y'
true
false
false
false
```

**Comment by nornagon** [comment]
I think this might be due to short circuiting?

**Comment by pkoppstein** [comment]
Yes, it's due to short-circuiting.  See for example:

https://github.com/stedolan/jq/wiki/Advanced-Topics#cartesian-product-behavior-of-some-expressions

**Comment by nornagon** [comment]
Yep, makes sense. Surprising, though. Might be worth linking that wiki link in the docs for `and`!
