### ISSUE TITLE
JSON does allow better than IEEE 754 numbers

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#143]
The issue was raised at the IETF JSON WG this week: does JSON permit arbitrary precision numbers?  The syntax certainly does.  Neither RFC4627 nor ECMAScript 6 (draft) preclude it, and many implementations use whatever the native language run-time, OS, and/or machine architecture provide -- often not limited to IEEE 754 64-bit real numbers.

jq currently only supports IEEE 754 64-bit numbers.  It could probably do better: also 64-bit signed integers using C int64_t (perhaps with much care regarding overflows, or perhaps not).  It could even use bignum libraries.  It's all probably too much, but I'm filing (and closing) this issue just to record this.

**Comment by rsrsps** [comment]
>>I'm not sure I see any use at all for 64-bit integers. Arbitrary-sized bigints might well be useful, but I see no reason to want int64.<<

Concrete values that only make sense as a number like Unix epoch nanotime already exceed the resolution available in the implementations that use floats for large integers.  This is genuinely annoying as the Javascript implementations quietly truncate the values.

(just adding)

**Comment by tomwhoiscontrary** [comment]
I just tripped myself up using jq with nanosecond-scale unix timestamps:

```
$ echo '{"timestamp":1499816949527975237}' | jq .timestamp
1499816949527975200
```

I appreciate that there are some real headaches around using different number implementations according to the value. But there are also headaches around silently changing the values in the data.

If support for numbers not exactly representable as 64-bit floats isn't on the cards, how about an error exit rather than approximation?

**Comment by lfairy** [comment]
Just got bitten by this today.

The API we use at work associates each entity with a 64-bit integer ID. I started to question the output of jq when some of these IDs were showing up as equal.

**Comment by leonid-s-usov** [comment]
Please try this branch #1752
