### ISSUE TITLE
JSON names starting with numbers are falsely reported as invalid

### ISSUE THREAD

**Issue by nicdoye** [stedolan/jq#1432]
According the the spec

> A string is a sequence of zero or more Unicode characters, wrapped in double quotes, using backslash escapes. 

But names starting with numbers cause `jq` to error as below.

```
❯ echo '{ "1foo": "bar" }' | jq .1foo
jq: error: syntax error, unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
.1foo
jq: 1 compile error
```

**Comment by wtlangford** [comment]
That's not valid for jq's `.accessor` syntax. However, you can always use `.["1foo"]` instead!

**Comment by csnook** [comment]
This also breaks "jq ."

**Comment by pkoppstein** [comment]
@csnook wrote:

> This also breaks "jq ."

It's unclear exactly what the "this" is, but if you find that:

    echo '{ "1foo": "bar" }' | jq .

fails in some way, it's probably because you're not using a bash-like shell.
