### ISSUE TITLE
jq changes its usage depending on whether or not stdout is a TTY

### ISSUE THREAD

**Issue by thanatos** [stedolan/jq#1433]
```sh
» echo '[1,2,3]'>foo
» # This works fine
» jq <foo
[
  1,
  2,
  3
]
» # This doesn't.
» jq <foo | cat
jq - commandline JSON processor [version 1.5]
Usage: jq [options] <jq filter> [file...]
…
```
This took way too many brain cells to debug, frankly. No user expects the invocation syntax of a command to change depending on whether the output is a TTY, which is the behavior `jq` exhibits above.

(Further, if you just invoke `jq --help`, it says,

```
» jq --help
jq - commandline JSON processor [version 1.5]
Usage: jq [options] <jq filter> [file...]
```
which isn't true in the stdout-is-not-a-TTY case: `jq <a.json` works, but doesn't match the Usage.

(The actual, real world example looked more like this:
```
» diff a.json b.json
<one line, that differs>
» # okay, that was dumb. Let's use jq to pretty print it first.
» diff <(jq <a.json) <(jq <b.json)
<receive the usage string, twice>
» # spend a moment contemplating what I did wrong
» jq <a.json
<pretty prints>
» # retry the diff
<fails>
» # WAT
```
)

**Comment by pkoppstein** [comment]
@thanatos - The history of the issues you raise is quite involved so let me just refer you to  https://github.com/stedolan/jq/issues/1110 and point out two things:

1.  If ever in doubt, simply provide a filter explicitly. (That's what the "Usage" synopsis suggests, no?)

2.  The behavior at "master" is an improvement over jq 1.5
