### ISSUE TITLE
evaluate javascript [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [stedolan/jq#1434]
Would be possible to add something like the following?
This could allow us to define comments in a json object without hacky tricks.

`jq -r .github.token ./config/production.json #json evaluation`
`jq --js -r .github.token ./config/production.js #javascript exported object evaluation`

**Comment by nicowilliams** [comment]
We're not opposed to adding new input/output formats, but *all* input/output formats *must* conform to the JSON data model.  As such, comments in data cannot be supported except by mapping the data onto a schema that can represent comments as normal JSON data.

**Comment by nicowilliams** [comment]
In any case, jq will NEVER support evaluation of JavaScript _code_.

**Comment by nicowilliams** [comment]
Feel free to open a new issue asking for any additional serialization formats, though beware that we're not likely to add that anytime soon.
