### ISSUE TITLE
Conditional extract

### ISSUE THREAD

**Issue by damianobarbati** [stedolan/jq#1436]
Can we use jq to extract a field or another? 
This way we can use jq to evalute string in other commands.

```
{
    "development": {
        "host": {
            "hostname": "dev.quant01.com"
        }
    }
}
```
```
$ jq -e -r .ddevelopment.host.hostname package.json || jq -r .development.host.hostname package.json
null
dev.quant01.com
```

I thought -e switch could cause the bash function to exit 1, so the OR condition was fullfilled resulting in just `dev.quant01.com`

**Comment by slapresta** [comment]
To test several different paths, you could use the alternative operator (`//`):

`jq '.foo.bar.baz // .quux.bar.baz' whatever.json`

This will return the first value that isn't `null`.

**Comment by damianobarbati** [comment]
Thanks @purpliminal , perfect!
