### ISSUE TITLE
Change of behavior tokenizing `tonumber?//false`

### ISSUE THREAD

**Issue by fadado** [stedolan/jq#1439]
I just compiled the last version of jq (jq-master-0.1-2-g0be0dac) and one program of mine broke. jq rejected to compile

    tonumber?//false

I changed  the code to

    tonumber? // false

and the problem disappeared.

JJOR

**Comment by JeffreyMercado** [comment]
`?//` is now an operator by itself which is why you're seeing the errors. See commit 3a8c8f4747313d324f4309af66e2211319eccffd. Looks like it's still a work in progress.

**Comment by fadado** [comment]
> ?// is now an operator by itself

Ok! Thanks for clarifying the issue!
