### ISSUE TITLE
Need to get all keys containing a specific character '/'

### ISSUE THREAD

**Issue by shanky249** [stedolan/jq#1443]
I have a specific json content for which I need to **get all keys** which contains the character **/** in their values.
**JSON:**
`{
    "dig": "sha256:d2aae00e4bc6424d8a6ae7639d41cfff8c5aa56fc6f573e64552a62f35b6293e",
    "name": "example",
    "binding": {
        "wf.example.input1": "/path/to/file1",
        "wf.example.input2": "hello",
        "wf.example.input3": ["/path/to/file3","/path/to/file4"],
        "wf.example.input4": 44
    }
}`

How do I get below kind of output.
**Output:**
*.binding["wf.example.input1"]
.binding["wf.example.input3"] | .[0]
.binding["wf.example.input3"] | .[1]*

**Comment by shanky249** [comment]
I tried _jq 'map(select(contains ("/")))'_ , but it gives me **jq: error (at <stdin>:1): object ({"wf.exampl...) and string ("/") cannot have their containment checked** error.

**Comment by pkoppstein** [comment]
> get all keys which contains the character / in their values.

Your example indicates you actually want the paths, and the following query provides the jq representation of them.  Specifically, the query:

    paths(type == "string" and contains("/"))

produces:

```
["binding","wf.example.input1"]
["binding","wf.example.input3",0]
["binding","wf.example.input3",1]
```
This format can be used in queries (e.g. using `getpath` and `setpath`), but if you need some other format, by all means have at it.

For future reference, please direct jq usage questions to stackoverflow.com, using the jq tag.

**Comment by shanky249** [comment]
I need to fetch all the elements that have a file path or an array of file path as their value. I think this should be able to help me move ahead. Thanks 👍

**Comment by pkoppstein** [comment]
@shanky249 - Please ask usage questions at stackoverflow.com using the jq tag.  Your revised question is not very clear in a number of respects, so it would help if you gave a simple example with both input and the expected output.

**Comment by shanky249** [comment]
@pkoppstein Sure. Will keep that in mind. Just another query on top of the same question. Now that i have all the elements that contains some file paths as their values, is there a way to fetch both key and value for the same and then store them as another JSON? For example, in JSON mentioned for this question, I need to get the output as another JSON containing all the matched paths. My output JSON should look something like: 
`{ "binding": { "wf.example.input1": "/path/to/file1", "wf.example.input3": [ "/path/to/file3", "/path/to/file4" ] }}`

**Comment by pkoppstein** [comment]
@shanky249 - Your question is a good one, and that is all the more reason for you to ask it at stackoverflow.com (with the jq tag), as more people will benefit from an answer there. Thanks for your understanding.

**Comment by shanky249** [comment]
I have posted this question on stackoverflow.com. Here is the link [https://stackoverflow.com/questions/45025624/need-to-get-all-key-value-pairs-from-a-json-containing-a-specific-character](url)
