### ISSUE TITLE
A filter that works in jqplay and not in the shell

### ISSUE THREAD

**Issue by aborruso** [stedolan/jq#1448]
Hi all,
I'm using this filter in this [snippet](https://jqplay.org/s/NgJceYz2ng): `.html.body.tr[1].td[] | ."$t"`

When I use it in the shell I have the below error. The problem is in `$` but I do not know how to escapet it.

Some advice for me?

Thank you

```
error: syntax error, unexpected QQSTRING_START, expecting $end
.html.body.tr[1].td[] | ."$t"
                         ^
1 compile error

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1018:11)
    at WriteWrap.afterWrite (net.js:804:14)
```

**Comment by pkoppstein** [comment]
1. Key names that begin with "$" are regarded as special, so you'd have to write `.["$t"]`, as in:

    .html.body.tr[1].td[] | .["$t"]

2. In future, please ask usage questions at stackoverlflow.com with the "jq" tag. Guidelines are at http://stackoverflow.com/help/mcve (mcve: minimal complete verifiable example)

**Comment by aborruso** [comment]
@pkoppstein thank you

**Comment by aborruso** [comment]
hi @pkoppstein , I'm sorry but there is something that I do not understand.

I have change my filter and now in jqplay is [[.html.body.tr[1] | {data:.td[0]."$t"}]](https://jqplay.org/s/Zkt-BudjEf). It works.

If in my ubuntu shell I use `jq '[.html.body.tr[1] | {data:.td[0].["$t"]}]'` I have

```
error: syntax error, unexpected '[', expecting IDENT
[.html.body.tr[1] | {data:.td[0].["$t"]}]
                                 ^
```

Thank you again

**Comment by wtlangford** [comment]
What's your `jq --version` ?

**Comment by aborruso** [comment]
@wtlangford it's 1.3

**Comment by aborruso** [comment]
@wtlangford I have updated to 1.5 and it's the same.

Thank you

**Comment by wtlangford** [comment]
Hm. I'm not sure what we've changed since 1.3 about this, but my guess is
that 1.3's parser doesn't like .[0].["something"]

I don't have a 1.3 laying around, but you can always just do
.[0]|.["something"]

Additionally, .[0]["something"] should probably work on 1.3

**Comment by aborruso** [comment]
@wtlangford I have tried jq 1.5 with 

- `'[.html.body.tr[1] | {data:.td[0].["$t"]}]'`
- `'[.html.body.tr[1] | {data:.td[0].[$t]}]'
- '[.html.body.tr[1] | {data:.td[0].["t"]}]'

It does not work

**Comment by wtlangford** [comment]
How about '[.html.body.tr[1] | {data:.td[0]["$t"]}]' or '[.html.body.tr[1]
| {data:.td[0]|.["$t"]}]'

**Comment by pkoppstein** [comment]
@aborrusu - As @wtlangford explained, both of these will work in all versions of jq:

     .[0]["$t"]

     .[0]["$t"]

Also, it would be better to ask usage questions at stackoverflow.com with the jq tag, as that way others can more easily benefit.  (It is difficult to extract an answer from a lengthy linear back-and-forth discussion ...)

**Comment by aborruso** [comment]
Hi @pkoppstein and @wtlangford `.[0]["$t"]` and `.[0]|.["$t"]` work

Thank you very much
