### ISSUE TITLE
jq --version prints to stderr

### ISSUE THREAD

**Issue by FRosner** [stedolan/jq#1452]
I am trying to determine the version and using it in a variable. When I do `jq_version=$(jq --version)` it is not working because `jq --version` prints to the stderr. Is that expected behaviour?

**Comment by pkoppstein** [comment]
It is evidently the intended behavior.  You should be able to redirect stderr to stdin, e.g. using bash:

    jq_version=$(jq -V 2>&1)

**Comment by FRosner** [comment]
Yup did that now. I was just wondering if this is expected as it looks quite counter intuitive :)

Thanks anyway for the clarification!
