### ISSUE TITLE
How to get variable works?

### ISSUE THREAD

**Issue by chinajuanbob** [stedolan/jq#1453]
Hi,

I hit a issue with jq

I store a string in variable $ver, but can not get the right result from jq.

Here is my code:

```
chinajuanbob@Host:~$ echo $ver
0.1
chinajuanbob@Host:~$ echo [\"0.1\"] | jq 'contains(["0.1"])'
true
chinajuanbob@Host:~$ echo [\"0.1\"] | jq 'contains(["${ver}"])'
false

```

How should I solve this issue?

Thanks a lot!

chinajuanbob

**Comment by fadado** [comment]
Shell quoting is tricky:

```
$ export ver=0.1
$ echo '["0.1"]' | jq 'contains(["'${ver}'"])'
true
```

**Comment by wtlangford** [comment]
If you're going to use shell quoting, then you should do
```sh
$ export ver=0.1
$ echo '["0.1"]' | jq 'contains(["'"${ver}"'"])'
true
```

To avoid splitting problems.

Be careful, though. If your variable contains double quotes,  they won't get escaped properly, and jq will fail to compile your program.

**Comment by purpliminal** [comment]
Don't use shell interpolation inside your jq program directly! Instead, declare it as a jq argument, then use that argument in your program.

```
export ver=0.1
echo '["0.1"]' | jq --arg ver $ver 'contains([$ver])'
```

**Comment by chinajuanbob** [comment]
Thanks you all! It works!
