### ISSUE TITLE
JQ processing a JSON file returned from REST

### ISSUE THREAD

**Issue by AntJackson** [stedolan/jq#1456]
Please forgive me, i'm new to JQ and hopefully this is a simple one. I'm retrieving data from Sage X3 in a JSON format via Curl/REST.

JQ is sorting the data for however on $query functions from REST i get really a funny style format. Whne i try to out the data i just get "NULL"

The format of my returned JSON is below

{
    "$itemsPerPage": 20,
    "$resources": [
        {
            "$uuid": "825c85f1-b9c7-412a-9188-9ec02e55148d",
            "$etag": "2015-09-30T10:07:37Z",
            "PTHNUM": "RECFR0110035"
        }
    ],
    "$links": {
        "$last": {
            "$url": "http://172.26.49.214:8124/mobile1/x3/erp/TEST/XV1PSFREC?representation=XV1PSFREC.$query&key=lt&orderBy=BPSNDE&where=BPSNDE%20eq%20%2711003856%27",
            "$type": "application/json;vnd.sage=syracuse",
            "$method": "GET"
        }
    }
}

I've tried multiple combinations but i just want to output the "PTHNUM". I used
.[]|.PTHNUM
but just get null and if i remove the everything outside the [] it works fine. 
Thanks
Anthony

**Comment by thedward** [comment]
In the future I'd recommend asking usage questions on StackOverflow.com using the jq tag.

In this particular case — assuming you just want the value of `PTHNUM` — either of the following should work:

```sh
jq '.["$resources"][].PTHNUM'
```
```sh
jq '..|.PTHNUM?//empty'
```

**Comment by pkoppstein** [comment]
For the record, after the release of jq 1.5, a change was made which invalidates '..|.PTHNUM?//empty' in that a space is now required after the "?":

```
$ github/jq/jq -n  '..|.PTHNUM?// empty' 
jq: error: syntax error, unexpected ?//, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
..|.PTHNUM?//empty          
jq: 1 compile error

$ github/jq/jq -n '..|.PTHNUM? //empty' 
$ 
```
