### ISSUE TITLE
tojson doesn't honour command-line -S key sorting flag

### ISSUE THREAD

**Issue by mjcherbert** [stedolan/jq#1457]
as mentioned in other issues, the output produced by tojson doesn't seem to be affected by the -S option in particular (presumably other options also don't work) ...

**Comment by pkoppstein** [comment]
@mjcherbert - As the help text for the -S option says:

>   -S               sort keys of objects on output;

Thus this option has no effect on `tojson`, which never sorts the keys when converting to a string.  If this is confusing, please remember that jq first reads the input (if any), processes it (e.g. using tojson), and then outputs the results.

**Comment by mjcherbert** [comment]
interesting, my assumption about hashes in jq seems to be incorrect - they do appear to preserve order (at least immediately after creation by from_entries) ... my apologies - I understood a hash to be unordered and that because tojson was producing different output for ostensibly the same hash that this was because it was not sorting things itself (and therefore wasn't following -S) ... your example unfortunately was a little simplistic, but I've expanded on that and confirmed for myself that your workaround works for version 1.5 with a hash of at least 11 elements input in a random order. Thanks
