### ISSUE TITLE
jq error

### ISSUE THREAD

**Issue by payamzowghi** [stedolan/jq#1459]
`RECEIPT_HANDLE=$(echo "${OUTPUT}" | jq '.Messages[0].ReceiptHandle' | tr -d '"')`
I got this error:
parse error: Invalid numeric literal at line 1, column 9
echo $RECEIPT_HANDLE
'MESSAGES	mangodb0	bc1d4ad19db881ae1bd3ef536369691b	0c62586a-c6c0-4f2e-a5d8-3407e9ed6b67	AQEBaezupqoZC69miFNjvbLg0Vc7ZqOk7Wx3ienfvamhPlxPf9wb7Upg+BqE+zLAxxKtP1eFRUlTIgur4DfkZj1UlZ8pzlKCcF7ZRDWoOXMiEMmWzTnFiicOjEmuJ4e5hUV5EI4JJ3lujCHNUO1fZ+BQ12zN7TYg6SORcdk3rWu6rXCclXmuzLyQ4c91T7I836w5rzekvarWnuhs0fH9ukbXT1QnX00yUNhHzUDp2sPBwrM8Y/Ur6zLAFzrL9h1a7T/Oh2qDU6TbIVy7fHoKWZNOYsdoO/d2kClfZ9N3r+irrXBjCcYOclbnnqqutxjCkZC2PfvJHoKfFLWDGGdh9pvr6wdzHxjydJJocjP7Yd1YH+iqHQzW9M4RdrMXrzEwxbtQ'

I think that jq has a problem with space.do you know how to solve the issue?

**Comment by thedward** [comment]
Without knowing the value of `$OUTPUT`, this question is unanswerable.
