### ISSUE TITLE
jq   introduces single quotes in jenkins causing issues..

### ISSUE THREAD

**Issue by eearif** [stedolan/jq#1463]
Dear Sir,
step 1 :---
downurl=$(/usr/local/bin/jq .links.download[0].url curl.txt)  when used in jenkins.

it converts itself into 
step2 :--
downurl=$(/usr/local/bin/jq  '.links.download[0].url'  curl.txt)  during execution.

and later obtains the download url as follows  in form of bug.
actual  incorrect value   ' "downloadurl" '   
but the expected value is  "downloadurl"
Can you please check why the single quotes is being introduced in the jq command in step2 ..

Thanks
John..

**Comment by jbristow** [comment]
Hmm, do you have an example of the data you're working with?

From your query I constructed:
```javascript
{
  "links": {
    "download": [
      {"url": "downloadurl"},
      {"other":"stuff"},
      {"stuff":"other"}
    ]
  }
}
```
But I can't reproduce this with my bash (GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16))

I get `downurl="downloadurl"`

**Comment by nicowilliams** [comment]
Sounds like a Windows shell quoting issue to me.
