### ISSUE TITLE
JQ doesn't support dash `-` character in dictionary key names?

### ISSUE THREAD

**Issue by asangal** [stedolan/jq#1464]
https://stackoverflow.com/questions/45703291/parse-or-view-json-data-fields-using-jq-tool-utility-where-field-names-have-a/45703341#45703341

While trying to access a dictionary key's value where the key name contains a `-` character, it's failing and giving the following errors.
```

jq: error (at <stdin>:27): null (null) and number (2) cannot be subtracted
jq: 1 compile error

jq: error: three/0 is not defined at <top-level>

jq: error: syntax error, unexpected INVALID_CHARACTER, expecting $end (Unix shell quoting issues?) at <top-level>

jq: error: syntax error, unexpected INVALID_CHARACTER, expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:

```
PS above stackoverflow link for more.

**Comment by jbristow** [comment]
Hmm, using your info:
```javascript
{
  "pages": {
    "book1": [
      "page1",
      "page2-para1",
      "page3-para1-sentence1",
      "page3-para2-sentence3-word4"
    ]
  },
  "content": {
    "book1": {
      "name": "giga",
      "url": "-",
      "field1": "value1",
      "field-2": "value-2",
      "field-three": {
        "name": "THIRD",
        "url": "book1/field-three/",
        "short-url": "book1/field-three/chota-chetan"
      },
      "authur": {
        "name": "lori CHUCK",
        "displayIndex": 4
      },
      "route": "/in-gc/hindi-chini-bhai-bhai"
    }
  }
}
```
.content.book1."field-2"

returns 

"value-2"

```bash
$ cat tmp.json | jq '.content.book1."field-2"'
"value-2"
```

**Comment by jbristow** [comment]
This is covered in the manual https://stedolan.github.io/jq/manual/#Basicfilters under "Object Identifier-index"

**Comment by orrgal1** [comment]
for some reason this didn't work for me in top level. i ended up changing the key to abc_def instead of abc-def.

**Comment by emanuele6** [comment]
@orrgal1 Perhaps you did not quote the `"` characters in your command; if you run `jq ."abc-def"` in your shell, the quotes are interpreted by the shell and removed, so you effectively just run `jq .abc-def`.
If you use `jq '."abc-def"'` so that the `"` characters are quoted, then `jq` actually receives the `"` characters.

**Comment by orrgal1** [comment]
i think i tried those options but maybe i missed something. will try again.

**Comment by cliusz** [comment]
the latest verision v1.7 is still no suppport?

**Comment by jbristow** [comment]
No support for what?

**Comment by cliusz** [comment]
> No support for what?

the v1.7 verison of jq still appear the compile error bug.

**Comment by jbristow** [comment]
It's not a bug. 

[From the manual:](https://jqlang.github.io/jq/manual/#object-identifier-index)
> The `.foo` syntax only works for simple, identifier-like keys, that is, keys that are all made of alphanumeric characters and underscore, and which do not start with a digit.
>
> If the key contains special characters or starts with a digit, you need to surround it with double quotes like this: `."foo$"`, or else `.["foo$"]`.
>
> For example `.["foo::bar"]` and `.["foo.bar"]` work while `.foo::bar` does not.

**Comment by nicowilliams** [comment]
> for some reason this didn't work for me in top level. i ended up changing the key to abc_def instead of abc-def.

Are you using double quotes to quote your jq program from the shell?  Are you on Windows?
