### ISSUE TITLE
jq-linux64 downloads an html file with links to dangerous website per safeweb.norton.com

### ISSUE THREAD

**Issue by NorthDecoder** [stedolan/jq#1469]
* To repeat the process goto
https://stedolan.github.io/jq/download/

* choose the jq 1.5 binaries for 64-bit download link
https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64

* At the bash prompt
 ```
$ mkdir $HOME/bin/jq
$ cd $HOME/bin/jq
$ curl https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -o jq
$ pico jq
```
Read the html text and see the link to the malicious web site.
Copy and paste the link of that file into 
https://safeweb.norton.com/

**Comment by nicowilliams** [comment]
That's GitHub redirecting you to their S3.  Nothing we can do about that.
