### ISSUE TITLE
Test fails with busybox/mktemp (Alpine Linux)

### ISSUE THREAD

**Issue by rgdoliveira** [stedolan/jq#1473]
jq suite test fails with mktemp from busybox with the error:

mktemp: Invalid argument
Your OS does not support mktemp(1) -d

It seems wrong because busybox mktemp does support -d.
In tests/setup files it uses `mktemp -d -t jqXXXXX` but seems it is missing a X (should be 6)

**Comment by rgdoliveira** [comment]
My mistake. Seems this issue is already fixed after 1.5 release. I'm closing this issue

**Comment by ncopa** [comment]
commit b7a219a91dc1094022478dd9bc0f60275367ce25
