### ISSUE TITLE
 Making all in modules/oniguruma make[2]: *** No rule to make target `all'. 

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#1480]
Having trouble building jq from master on OSX.  "make" fails as shown. Please note also that currently the automated github build is failing:

https://github.com/stedolan/jq/blob/master/README.md

**Comment by SkyWriter** [comment]
@pkoppstein I got that when I forgot to run `git submodule update --init` (as per README). Just in case it helps you or someone else who stumbles upon the issue.

**Comment by pkoppstein** [comment]
@SkyWriter - Tx.

**Comment by wgordon17** [comment]
Also getting this error when running `make` from the tarball
