### ISSUE TITLE
cannot use argument in select filter

### ISSUE THREAD

**Issue by rodneymo** [stedolan/jq#1482]
hi,

JQ arguments don't seem to expand inside select filter. 

This doesn't work. The LAST_RECORD argument does not expand inside the select statement.
curl "https://api.ethermine.org/miner/0x2e4af23c44fa2e7483cef44125c3dbe998fe5a81/payouts"| jq --arg LAST_RECORD 1500922738 -r '.data[] | select(.paidOn > $LAST_RECORD)

but this works:
curl "https://api.ethermine.org/miner/0x2e4af23c44fa2e7483cef44125c3dbe998fe5a81/payouts"| jq --arg LAST_RECORD 1500922738 -r '.data[] | select(.paidOn > 1500922738)

Am I doing something wrong or is this a bug?

**Comment by pkoppstein** [comment]
Consider: 

    $ jq -n --arg LAST_RECORD 1500922738 '$LAST_RECORD'
    "1500922738"

Notice that in the above, $LAST_RECORD is a string.  Since you want to do a numeric comparison, you will either have to use--argjson (if your jq supports it), or do the appropriate conversion, e.g. using `tonumber`.

**Comment by rodneymo** [comment]
the tonumber filter worked perfectly!!! Thanks a bunch
