### ISSUE TITLE
got "Argument list too long" when use '|='

### ISSUE THREAD

**Issue by SeekerResource** [stedolan/jq#1490]
when use this command

> jq ".item |= ${api_final}" ${test_file}

to update value for field item, got error

> /usr/local/bin/jq: Argument list too long

and size of variable ${api_final} is about 251,000 characters

**Comment by pkoppstein** [comment]
Did you perhaps mean something along the following lines?

    jq --arg x "${api_final}" '.item = $x'

**Comment by SeekerResource** [comment]
still got the same error '/usr/local/bin/jq: Argument list too long', @pkoppstein

**Comment by pkoppstein** [comment]
On my Mac:

```
$ jq -n '.[51000]=0 | tostring | length'
255003

$ jq -n '.[51000]=0 | tostring' > 255003.json
$ jq -n --argfile x 255003.json '.item = $x | type'
"object"
$ jq -n --argfile x 255003.json '.item = $x | .item | length'
255003
```

p.s. 
```
jq -n --arg x "$(cat 255003.json)" '.item = $x | type'
```

**Comment by nicowilliams** [comment]
`Argument list too long` is a system error.  Argument and environment sizes are limited by all Unix-like kernels.  You exceeded that size.  Use `-f` to pass extra large programs.  (But beware that jq function bodies, and the top-level jq program, are limited in compiled size to 64K code units each.)
