### ISSUE TITLE
Feature request: Add a command like flag to ignore parse errors.

### ISSUE THREAD

**Issue by ericm1024** [stedolan/jq#1492]
I work with a system at my job that spits out enormous log files where each line is a json blob, and I use jq to help me digest these logs. However, sometimes something writes invalid json to a log file, and I get an error like this:
```
parse error: Invalid numeric literal at line 1159, column 12299
```
Given that this is a 5GB log file, I probably don't care about that line. It would be nice if I could say
```
jq -I < log.log
```
and have it ignore errors and move onto the next line.

**Comment by pkoppstein** [comment]
Please note that jq already provides a mechanism for achieving what you want.  See:

    Q: Is there a way to have jq keep going after it hits an error in the input file?

in the [FAQ](https://github.com/stedolan/jq/wiki/FAQ)
