### ISSUE TITLE
JQ Doesn't output anything when output is redirected to a file

### ISSUE THREAD

**Issue by robacarp** [stedolan/jq#1496]
Thanks for making a great tool. I've been surprised at how easy jq is to pick up and build powerful tools with, which means the design is well thought out. I've run into a simple issue I can't seem to find documentation around.

I read through #1110 and I don't think this is related, but I could be wrong. 

I'm trying to insert a key into a json object, something like this:

```
$ cat environments/production.json | jq -M '. * { "passing": false }' > environments/production.json
```

Without the output redirection, the json blob printed to STDOUT correctly, with the added key. When I add the output redirection, the file is never written to. I feel like I must be missing something subtle.

The behavior is also reproducible by simply: 

```
$ cat file.json | jq '.' > file.json
```

Which I would assume would leave the file unchanged, or at least be an idempotent pretty-printing of the contents. Instead the file is left empty.

I've tried under fish shell and bash with the same results.

Cheers

**Comment by pkoppstein** [comment]
As noted in the[jq FAQ](https://github.com/stedolan/jq/wiki/FAQ) (see i.p. Q: How can "in-place" editing of a JSON file be accomplished?), using shell redirection to overwrite the input file is ill-advised.  Various alternatives are suggested there.  Using `sponge` often works out well.

**Comment by robacarp** [comment]
Great, I knew there had to be an easy solution. Thanks for the quick response, and thanks again for a great tool!

**Comment by srghma** [comment]
for dir

```
fd ".*.json" dir/ --exec bash -c 'jq "." {} | sponge {}'
```

**Comment by srghma** [comment]
for dir

```
fd ".*.json" dir/ --exec bash -c 'jq "." {} | sponge {}'
```
