### ISSUE TITLE
Can't handle JSON5 comments - "parse error: Invalid numeric literal"

### ISSUE THREAD

**Issue by harryttd** [stedolan/jq#1499]
When running jq on a JSON file that is using JSON5 comments, I received this error `parse error: Invalid numeric literal at line 5, column 5`.

**Comment by gerrywastaken** [comment]
@harryttd Why close this as completed on the same day as you open it? That is super misleading

<img width="1336" height="750" alt="Image" src="https://github.com/user-attachments/assets/30dc9e18-e93b-4080-9025-48695900c761" />

**Comment by Flimm** [comment]
Currently, jq can only parse JSON, which doesn't support a syntax for comments. jq can't parse JSON5 (which does specify syntax for comments).

Others have already submitted feature requests to allow jq to parse JSON5 with comments. See these related issues: https://github.com/jqlang/jq/issues/1571 https://github.com/jqlang/jq/issues/1607 https://github.com/jqlang/jq/issues/2855 . See also this [FAQ entry](https://github.com/jqlang/jq/wiki/FAQ#processing-not-quite-valid-json).
