### ISSUE TITLE
dash need to be parsed in another way to allow more flexable use of jq

### ISSUE THREAD

**Issue by t5unamie** [stedolan/jq#1500]
imagine the following json
config.json
```
{
 "config-1": "abc:asdasda/asdasda/dfasdfasd",
 "config-2": "abc:1231231/asdasda/12312312"
}
```
I want to do something like this.

PROFILE="config-1"
output=`jq -r '.["${PROFILE}"]' ~/config.json`

Does anyone have any recommendations? This would solve a lot of peoples needs since they want to parse into a search something thats has special characters or spaces. where it's a variable.

I remember a ticket around 2 years ago where I asked something similar.

**Comment by svnpenn** [comment]
Use `--arg`

**Comment by t5unamie** [comment]
Thanks this works as expected
