### ISSUE TITLE
Incorrect output of gsub for string with unicode character

### ISSUE THREAD

**Issue by ekuler** [stedolan/jq#1505]
When processing string with gsub containing unicode characters, the output is incorrect, the replacement is performed at wrong position. 

Example:
`echo "</li> <li><b>lorem ipsum</b> <!-- lorem ipsum -->€lorem ipsum</li><!-- lorem ipsum--> <li>" | jq --raw-input 'gsub("</li>.*?<li>";"; ")' `

Output:
`"; <b>lorem ipsum</b> <!-- lorem ipsum -->€lorem ips; i>"`

Expected output:
`"; <b>lorem ipsum</b> <!-- lorem ipsum -->€lorem ipsum;" `

Tested with jq version 1.5

**Comment by fadado** [comment]
> Expected output:

     "; <b>lorem ipsum</b> €lorem ipsum;"

Using `jq-master-0.1-2-g0be0dac` the bug does not exists:

```
$ echo "</li> <li><b>lorem ipsum</b> <!-- lorem ipsum -->€lorem ipsum</li><!-- lorem ipsum--> <li>" | jq --raw-input 'gsub("</li>.*?<li>";"; ")'
"; <b>lorem ipsum</b> <!-- lorem ipsum -->€lorem ipsum; "
```
jq 1.5 is very old. You must compile jq using the instructions in the GitHub main page.

**Comment by pkoppstein** [comment]
> jq 1.5 is very old. You must compile jq using the instructions in the GitHub main page.

Windows users have an alternative: see 
https://github.com/stedolan/jq/wiki/Installation#windows-using-appveyor

**Comment by nicowilliams** [comment]
Yes, we need to do a release.  We're working on it.
