### ISSUE TITLE
Duplicate keys ?

### ISSUE THREAD

**Issue by haisamido** [stedolan/jq#1509]
The below json is not valid json since the key "x" is repeated at the same level, yet jq does not complain. jq quietly uses only the second "x"!

`{
  "foo": {
    "bar": [
      {
        "x": 1, "x": 2
      }
    ]
  }
}`

Here's a code snippet https://jqplay.org/s/HSWXjrZmdG

**Comment by pkoppstein** [comment]
This is a jq feature, not a bug.  

Specifically, jq is supposed to be able to read in any valid JSON, and the example you give is indeed valid JSON.  

JSON processors are given some leeway as to semantics, and jq chooses to do what it does in this case quite deliberately.  (Note in particular that it is consistent with the behavior of "+" on JSON objects.)

**Comment by jaques-sam** [comment]
Apparently, the sandard does not say duplicate keys are not allowed... https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object
