### ISSUE TITLE
JQ no longer working

### ISSUE THREAD

**Issue by bernardbaker** [stedolan/jq#1510]
This is a bash script which is no longer working correctly. My intention is to store the **.firstName** property value in **tempFirstName**.

**Sample JSON**
```
[
  {
    "id": 110207,
    "firstName": "Bernard",
    "lastName": "Baker",
    "email": "bbaker@matw.com"
  }
]
```

`tempFirstName=$(cat "${data[0]}" | jq ".[] | select(.id == $trafficEmployeeId) | .firstName")`

Where `${data[0]}` is the sample JSON.

**Comment by wtlangford** [comment]
Are you receiving some kind of error? I don't see anything overtly wrong.
Though, using bash variables in your jq program is a bad idea. Use the
--argjson flag and use single quotes around your program instead.
Otherwise... I don't see any direct issues. More explanation of what is
going wrong would be helpful.

**Comment by pkoppstein** [comment]
Further to @wtlangford's response:

1. You haven't indicated what the value of $trafficEmployeeId is.
2. Assuming trafficEmployeeId=110207, the following is probably close to what you need:

    tempFirstName=$(cat "${data[0]}" | jq --argjson eid "$trafficEmployeeId" '.[] | select(.id == $eid) | .firstName')

Please note that (except in Windows environments) it is usually best to use single-quotation marks to quote the jq filter.

**Comment by bernardbaker** [comment]
The problem was in fact the input. Which was the reason that I did not get a match in the filter.

When multiple objects were being processed the value of "$trafficEmployeeId" contained a new line followed by another / the same ID number.
