### ISSUE TITLE
Is it possible to create custom filters?

### ISSUE THREAD

**Issue by umarashfaq** [stedolan/jq#1511]
As my filters grow complex, it becomes increasingly difficult to keep track of the logic. It'd be super cool if I can contain pieces of my logic in custom filters. For example:

```
jq '.myArray | my_custom_filter(.id)' my.json
```
I know there's a section [Modules](https://stedolan.github.io/jq/manual/#Modules) in the docs, but I'm not sure if it's relevant to the question. Most of the search results about `jq` return stuff about `jquery`. 

So, is it possible to create custom filters?

**Comment by thedward** [comment]
You probably want to read the section of the manual titled  _**["Defining Functions"](https://stedolan.github.io/jq/manual/#DefiningFunctions)**_.

In general, usage questions are better directed to [stackoverflow.com](https://stackoverflow.com/questions/tagged/jq).

**Comment by umarashfaq** [comment]
Thank you, and point noted about StackOverflow. Closing this issue.
