### ISSUE TITLE
gsub on invisible control characters

### ISSUE THREAD

**Issue by np** [stedolan/jq#1532]
This has been tested with jq 1.5:

```
$ jq -n '"\u200eX" | gsub("\u200e"; "")'
""
```

While the string `"X"` was expected.

**Comment by pkoppstein** [comment]
This is a well-known issue with jq 1.5 but has been fixed in the "master" version, which I hope you will be able to use.  If you have trouble installing from "master", please see https://github.com/stedolan/jq/wiki/Installation

**Comment by np** [comment]
Thanks, you can close this issue.

Why isn't there a new release?

**Comment by nicowilliams** [comment]
We're working on a release.  No ETA, sorry.
