### ISSUE TITLE
Invalid numeric literal

### ISSUE THREAD

**Issue by yasarhussain** [stedolan/jq#1533]
I'm trying to run the following command in Windows:
`jq .id example.json`

The example.json file is a recently exported tweet from Twitter's public API.

I get the following error every time I try to run:
`parse error: Invalid numeric literal at line 1, column 3`

Any ideas why it's giving me this error?

**Comment by pkoppstein** [comment]
1. I've verified that using jq 1.3, jq 1.5 and the current "master" version of jq, your program works with your data on a Mac. For example:

```
$ jq-1.3 .id example.json
929177125218746400
928138978708123600
928138978641043500
```

2. If you continue to have difficulties, please provide further details about:
* The computing environment (notably operating system, version of jq)
* Whether the "." filter works (e.g. run `jq . example.json`)

3.  Please don't forget to "close" this issue when the difficulty you describe has been resolved.

4. For future reference, please consider posting usage questions such as this one at stackoverflow.com with the tag "jq".

**Comment by yasarhussain** [comment]
Apologies for going through the wrong venue.  I'm running jq 1.5 on a Windows 7 64-bit machine.  When I use the "." filter, I get the same response.

**Comment by yasarhussain** [comment]
The JSON that was sent to me was not saved as UTF8.  I changed the encoding and everything is working as expected.

**Comment by pkoppstein** [comment]
I have verified that both the programs . and .id work with your JSON on Windows.  

My guess is that the contents of your file are not the same as what you have posted, or that the file is not encoded as UTF-8.  Perhaps you could paste the JSON into Notepad and save it as a UTF-8 file, and try again.

**Comment by yasarhussain** [comment]
Yup, saving it as UTF-8 is what the issue was.  Thanks for your help!
