### ISSUE TITLE
Strange behaviour on input without line terminators

### ISSUE THREAD

**Issue by Wyatts** [stedolan/jq#1534]
I discovered this while munging with some JSON output from Graphite, so this is a problem that can be encountered in the wild relatively easily.  The reduced case is you have two things (arrays or some other sort of object) that you want to concatenate.

```
$ jq --version
jq-1.5
$ echo $ARGH
[1,2][3,4]
$ echo $ARGH | jq -s add   #This is the expected result
[
  1,
  2,
  3,
  4
]
$ echo -n $ARGH | jq -s add   #The -n on echo disables newlines
[
  1,
  2
]
7         #WTF?
```
If you use a file to test this instead, `file` will describe it as "ASCII text, with no line terminators".  A demonstration:
```
$ file real-example.json
real-example.json: ASCII text, with no line terminators
$ cat real-example.json
[{"target": "system", "datapoints": [[1.1024494729647363, 1508544000]]}][{"target": "user", "datapoints": [[1.5750960532123335, 1508544000]]}]$ ^C
$ jq . real-example.json
[
  {
    "target": "system",
    "datapoints": [
      [
        1.1024494729647363,
        1508544000
      ]
    ]
  }
]
[
  {
    "target": "user",
    "datapoints": [
      [
        1.5750960532123335,
        1508544000
      ]
    ]
  }
]
```
Okay, looks well enough, but two separate arrays is annoying.
```
$ jq add real-example.json
{
  "target": "system",
  "datapoints": [
    [
      1.1024494729647363,
      1508544000
    ]
  ]
}
{
  "target": "user",
  "datapoints": [
    [
      1.5750960532123335,
      1508544000
    ]
  ]
}
```
Err, now they're objects instead of arrays.  Not quite.  Should slurp.
```
$ jq -s add real-example.json
[
  {
    "target": "system",
    "datapoints": [
      [
        1.1024494729647363,
        1508544000
      ]
    ]
  }
]
{
  "target": "user",
  "datapoints": [
    [
      1.5750960532123335,
      1508544000
    ]
  ]
}
```
Wait, what?  One is in an array and the other is not?  I'd guess however this happens is really the problem.

For full disclosure, this is where I started:
```
$ jq  '[ .[] | {(.target): .datapoints[0][0]} ] |add' real-example.json
{
  "system": 1.1024494729647363
}
{
  "user": 1.5750960532123335
}
```
"Oh, I can just slurp and add them and it'll work fine."
```
$ jq  -s 'add | [ .[] | {(.target): .datapoints[0][0]} ] |add' real-example.json
{
  "system": 1.1024494729647363
}
jq: error (at real-example.json:0): Cannot index string with string "target"
$ #Wait. What.
```
And the money shot:
```
$ echo >> real-example.json
$ file real-example.json
real-example.json: ASCII text
$ cat real-example.json
[{"target": "system", "datapoints": [[1.1024494729647363, 1508544000]]}][{"target": "user", "datapoints": [[1.5750960532123335, 1508544000]]}]
$ jq -s 'add | [ .[] | {(.target): .datapoints[0][0]} ] |add' real-example.json
{
  "system": 1.1024494729647363,
  "user": 1.5750960532123335
}
```
Add a terminator and everything works as expected.

**Comment by pkoppstein** [comment]
Yes, this is a problem with jq 1.5 and more recent versions.  Curiously enough, this problem was not evident in earlier versions (1.3 and 1.4):

```
$ jq1.5 -c -s . noline.json
[[1,2]]
[3,4]

$ jq1.4 -c -s . noline.json
[[1,2],[3,4]]

$ jq1.3 -c -s . noline.json
[[1,2],[3,4]]
```

**Comment by Wyatts** [comment]
Figured out how to make it build on this Ubuntu machine, so I took the liberty of bisecting.  Seems it first popped up in commit 5bfb9781f7e5ba2ad99b71150bccc559d53b928f.  Unfortunately, that's... a fairly big change:
`10 files changed, 480 insertions(+), 80 deletions(-)`

**Comment by staticshock** [comment]
I'm running into this issue as well while looking at S3 data collected via AWS Firehose, which does not line-terminate records. The interesting thing is that this bug doesn't _always_ manifest, but, in my case, it does happen in over 90% of files.

**Comment by nicowilliams** [comment]
Thanks for the report!

**Comment by wtlangford** [comment]
This was a bug in the slurp code that I've fixed in `f06deb8`. I added a test for this so we don't regress. Thanks again for the report!

**Comment by pkoppstein** [comment]
@wtlangford - I'm afraid that fix broke jq rather badly.

    $ jq1.5 --version
    jq-1.5rc2-253-gf06deb8

    $ echo '[1,2][3,4]' | jq1.5 -cs add

now hangs.

**Comment by wtlangford** [comment]
That's very odd, because I ran that test locally. But yes, I see it too.

**Comment by wtlangford** [comment]
Ah, I moved something after I ran that test, which broke it. Fix inbound.

**Comment by wtlangford** [comment]
Okay, I pushed 79ece35, which should fix that. And I added a with-newline test like I should have the first time.

**Comment by pkoppstein** [comment]
As theologians are wont to say: testing is the work of the devil.

**Comment by nicowilliams** [comment]
Thanks @wtlangford!
