### ISSUE TITLE
`jq` allows raw tab character in strings, which seems to be an extension to main JSON specs

### ISSUE THREAD

**Issue by hauleth** [stedolan/jq#1544]
As it would be braking change, I think there should be additional flag `--strict` that would allow only documents that are valid JSON according to spec, with no extensions.

**Comment by nicowilliams** [comment]
@hauleth We once had a bug where jq allowed unquoted newlines in strings.  We did not consider fixing that a breaking change.

**Comment by nicowilliams** [comment]
```
./jq .
"       "
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 1, column 3
```

**Comment by nicowilliams** [comment]
That's jq in master.  What version did you see this bug in?

**Comment by hauleth** [comment]
Current stable 1.5 (installed via HomeBrew).

**Comment by hauleth** [comment]
It would be nice to see `jq` to be ran against [JSON test suite by Nicolas Seriot](https://github.com/nst/JSONTestSuite/tree/master/test_parsing).

**Comment by nicowilliams** [comment]
Thanks for the link.

**Comment by pkoppstein** [comment]
> It would be nice to see jq to be ran against JSON test suite by Nicolas Seriot.

Actually, this has been done: see e.g. https://github.com/stedolan/jq/issues/1264

**Comment by nicowilliams** [comment]
Ah, thx for pointing that out @pkoppstein.
