### ISSUE TITLE
Floating-point strings have trailing zeroes removed.

### ISSUE THREAD

**Issue by Shaptic** [stedolan/jq#1550]
It's debatable whether or not this is a bug, but I'd expect the input string and the output number to be the same:

```bash
echo '{ "number": "123.450" }' | jq '.number | tonumber'
123.45
```

Obviously, it's easy enough to work around this (using `sed` to remove quotes instead, or `awk` to print with trailing zeroes), but it requires a non-`jq` solution.

**Comment by pkoppstein** [comment]
@Shaptic - The problem you've noticed is just the tip of the iceberg (see e.g. https://github.com/stedolan/jq/wiki/FAQ#caveats and the currently open issues: #218 #369 #1120 #1357 #1545).  

The idea of retaining and using the original representation when possible has been made, but as best I can tell, is unlikely to be incorporated into jq in the foreseeable future.  More likely, perhaps, is better control of output formatting -- see #1363

In the meantime, please note that jq's string-handling capabilities can often be used to overcome jq's limitations, depending of course on the specific circumstances.

**Comment by PinkD** [comment]
I found this **"feature"** was fixed. Now I need to trim ending zeroes by my self.
https://github.com/jqlang/jq/wiki/FAQ#numbers
