### ISSUE TITLE
Using jq to do data filtering from JSON file

### ISSUE THREAD

**Issue by Rahulnigam28** [stedolan/jq#1556]
Hello,
I  have a json input  file 
[
{"certname": "exampleA.com"
"name": "operating system",
"value":"Windows",
"environment":"production" },
{"certname": "exampleA.com"
"name": "memory",
"value":"SSD",
"environment":"production" },
{"certname": "exampleB.com"
"name": "operatingsystem",
"value":"Linux",
"environment":"production" },
{"certname": "exampleB.com"
"name": "memory",
"value":"HDD",
"environment":"production" }
]
I want to convert it into following

**OUTPUT**
[ {
"certname": "exampleA.com"
"operatingsystem": "Windows",
"memory": "SSD",
},
{"certname":"exampleB.com",
"operatingsystem": "Linux",
"memory": "HDD"
}
]

Please help me with the command I was able to do that but it happens only for one element in an array, 

 jq -r  '[.[]] | group_by (.certname) | [reduce .[][] as $item ({}; . + {"\($item.name)":$item.value}) | { "certname": .clientcert , "memory": .memory, "status": "managed", "operatingsystem": .operatingsystem}]'

As shown above this command only gives the last element as output, its output will be 

[{"certname":"exampleB.com",
 "memory": "HDD",
"status": "managed",
"operatingsystem": "Linux"
}]

**Comment by nicowilliams** [comment]
```
$ jq 'reduce (.[]) as $in ({}; .[$in.certname][$in.name] = $in.value)' <<EOF
[
{"certname": "exampleA.com",
"name": "operating system",
"value":"Windows",
"environment":"production" },
{"certname": "exampleA.com",
"name": "memory",
"value":"SSD",
"environment":"production" },
{"certname": "exampleB.com",
"name": "operatingsystem",
"value":"Linux",
"environment":"production" },
{"certname": "exampleB.com",
"name": "memory",
"value":"HDD",
"environment":"production" }
]
EOF
```

**Comment by Rahulnigam28** [comment]
Thank you,I am able to do that from my input file. However, the input file which I passed was filtered.

my input file is something like this:
  {
    "certname": "exampleA.com",
    "name": "uptime",
    "value": "1 day",
    "environment": "production"
  },
  {
    "certname": "exampleA.com",
    "name": "uptime_days",
    "value": 1,
    "environment": "production"
  },
 
  {
    "certname": "exampleA.com",
    "name": "interfaces",
    "value": "Ethernet 2",
    "environment": "production"
  },
 
  {
    "certname": "exampleA.com",
    "name": "rubyversion",
    "value": "2.1.9",
    "environment": "production"
  },

 {
    "certname": "exampleBcom",
    "name": "uptime",
    "value": "2 day",
    "environment": "production"
  },
  {
    "certname": "exampleB.com",
    "name": "uptime_days",
    "value": 2,
    "environment": "production"
  },
 
  {
    "certname": "exampleB.com",
    "name": "interfaces",
    "value": "Ethernet 4",
    "environment": "production"
  },
 
  {
    "certname": "exampleB.com",
    "name": "rubyversion",
    "value": "2.1.3",
    "environment": "production"
  },

{"certname": "exampleA.com",
"name": "operating system",
"value":"Windows",
"environment":"production" },

{"certname": "exampleA.com",
"name": "memory",
"value":"SSD",
"environment":"production" },

{"certname": "exampleB.com",
"name": "operatingsystem",
"value":"Linux",
"environment":"production" },

{"certname": "exampleB.com",
"name": "memory",
"value":"HDD",
"environment":"production" }

]

**Comment by Rahulnigam28** [comment]
Got it working I did map select before your reduce command. Thanks a lot.  jq ' map(select(.name == "virtual" or .name == "operatingsystem")) | group_by (.certname)| flatten | reduce (.[]) as $in ({}; .[$in.certname][$in.name] = $in.value)'

**Comment by pkoppstein** [comment]
> my input file is something like this

That's a bit vague, but note that (unless in "raw text" or "--seq" mode), jq generally expects its input to be a stream of valid JSON entities, without anything other than white space between the JSON entities.

Your input seems to be a bit of a mish-mash, and most likely you'll have to fix it.  It would probably be best if you can arrange to ensure that the source of your input is producing valid JSON or valid JSON streams. 

There is some information about fixing nearly-valid JSON on the jq FAQ especially at https://github.com/stedolan/jq/wiki/FAQ#processing-not-quite-valid-json

Please ask any further usage questions at stackoverflow.com with the jq tag:
https://stackoverflow.com/questions/tagged/jq

**Comment by Rahulnigam28** [comment]
The input file is only for testing purpose, I am running curl command to generate JSON output in  stream, since the json output is too big ,I have typed in the structure of the output
