### ISSUE TITLE
How to access shell variable value as key name

### ISSUE THREAD

**Issue by prudhviravella** [stedolan/jq#1561]
Hi,

I want to append new key value to the existing object
For ex, my existing json is like below
> {"person1:"{"name":"name","na":"ma"}}

I want to create something like below

>{"person1:"{"name":"name","na":"ma"},"person2":"{""name":"name","na":"mb"}"}

I used below command to add new key pair.
>keyname="person2"
>value={this will hold the value}
>echo $(cat $Name.json | jq --arg foo bar '. + {$keyname: $value}')

Error
>jq: error: syntax error, unexpected ':' (Unix shell quoting issues?) at <top-level>, line 1:
. + {: $foo}
jq: 1 compile error

Can't we use the shell variable values as keyname ?

Please help me

Thanks,

**Comment by pkoppstein** [comment]
Please read up on the `--arg` and `--argjson` command-line options.

If you have any further usage questions, please ask them on stackoverflow.com using the jq tag:
https://stackoverflow.com/questions/tagged/jq
