### ISSUE TITLE
Update image on docker hub

### ISSUE THREAD

**Issue by tnguyen14** [stedolan/jq#1564]
Can the image on docker hub https://hub.docker.com/r/stedolan/jq/ be updated? It was last updated 2 years ago.

**Comment by nicowilliams** [comment]
We're not responsible for it.

**Comment by tnguyen14** [comment]
@nicowilliams thanks for letting me know that. Do you know who is? Or is there an alternative docker image that you maintain?

**Comment by pkoppstein** [comment]
@tnguyen14 - unfortunately there has not been an official release of jq for a very long time. You may want to check, butI think you’ll find that docker has the most recent official version (1,5).
