### ISSUE TITLE
FreeBSD build failure - undefined reference to `exp10'

### ISSUE THREAD

**Issue by jungle-boogie** [stedolan/jq#1565]
Hi All,

I can install jq 1.5 from the releases page without any issue.

Using the instructions in the README for git master, the jq build is failing:
```
/.libs/libjq.a(builtin.o): In function `f_pow10':
/home/jungle/bin/jq-src/src/libm.h:253: undefined reference to `pow10'
./.libs/libjq.a(builtin.o): In function `f_exp10':
/home/jungle/bin/jq-src/src/libm.h:178: undefined reference to `exp10'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:984: jq] Error 1
gmake[2]: Leaving directory '/usr/home/jungle/bin/jq-src'
gmake[1]: *** [Makefile:1147: all-recursive] Error 1
gmake[1]: Leaving directory '/usr/home/jungle/bin/jq-src'
gmake: *** [Makefile:824: all] Error 2
```

Is there some other configuration option needed from master?

**Comment by yurivict** [comment]
Please don't use ```pow10```, ```exp10```. These are GNU extensions, and may be missing on non-linux systems.

**Comment by nicowilliams** [comment]
@jungle-boogie can you post `./configure` output?

**Comment by jungle-boogie** [comment]
You can see it here: http://termbin.com/dmo3

**Comment by yurivict** [comment]
On my FreeBSD system:
```
checking for exp10... no
checking for pow10... no
```

So for some reason, configure made a mistake on jungle-boogie's system.

**Comment by jungle-boogie** [comment]
I'm doing config:
`./configure --with-oniguruma=builtin --disable-maintainer-mode`

Do I need specific packages installed first?

**Comment by yurivict** [comment]
@jungle-boogie All you need to do is:
1. Patch your port with the patch I've sent you
2. make patch
3. In configure.ac, change exp10 and pow10 to something else.
4. Proceed with building the port (make && make install)

Please let me know if this helped.

**Comment by jungle-boogie** [comment]
The patch @yurivict provided in a private email worked!

Thanks for the hand-holding, @yurivict.

**Comment by yurivict** [comment]
> The patch @yurivict provided in a private email worked!
> Thanks for the hand-holding, @yurivict.

You are very welcome!
