### ISSUE TITLE
jq --version doesn't show version number

### ISSUE THREAD

**Issue by jungle-boogie** [stedolan/jq#1566]
Hi Again,

jq 1.6 doesn't show version information:
```
% jq --version
jq--
```

from the man page:
```
   --version:

           Output the jq version and exit with zero.
```

**Comment by nicowilliams** [comment]
Did you `git fetch --tags origin`?

**Comment by iax7** [comment]
I think this can be closed.
![image](https://user-images.githubusercontent.com/6983510/55911456-562d0300-5ba6-11e9-9c86-2d04c31630f2.png)

**Comment by jungle-boogie** [comment]
Geeze, sorry for not writing back on this. I probably did install from git src.

**Comment by dobeerman** [comment]
I installed jq via apk on "node:18-alpine" and it doesn't show version. What I do wrong?

**Comment by wader** [comment]
Hmm can reproduce with:
```
$ docker run --rm -ti alpine:3.17.2 sh -c 'apk add jq && jq --version'
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
(1/2) Installing oniguruma (6.9.8-r0)
(2/2) Installing jq (1.6-r2)
Executing busybox-1.35.0-r29.trigger
OK: 8 MiB in 17 packages
jq--
```
Can't really see anything wrong with the build https://git.alpinelinux.org/aports/tree/main/jq/APKBUILD so i would suspect jq's Makefile i dong something fishy.
