### ISSUE TITLE
Convert string to number

### ISSUE THREAD

**Issue by gismoranas** [stedolan/jq#1573]
I was not able to find a method to do the conversion, I have numbers like these 

1	BTC	0.95	-0.9	4.66	12510.0347694	209944804624
2	XRP	-1.4	20.32	152.91	3.0001778772	116224325352
3	ETH	-0.38	14.16	41.82	855.46060978	82782240871.0
4	BCH	-0.28	-9.44	-5.72	2014.21666593	34026741225.0
5	ADA	-0.43	15.05	205.03	0.9961012084	25825986293.0

which are strings in the json. I'd like to be able to convert them to double and change the precision (only 3 digits after the dot) or int. Thanks for your help :)

**Comment by alice0ch** [comment]
我和你也有同样的问题, 我想把一个字符串类型的数据转成数字, 然后比较.我的数据如下格式:
[
  {
    "name": "xxx_144_e9af8b0e7.tar.gz",
    "buildNo": "144"
  },
  {
    "name": "xxx_85_bfc35c102.tar.gz",
    "buildNo": "85"
  }
]
我想把buildNo转成数字类型,然后根据buildNo排序

**Comment by pkoppstein** [comment]
@alice0ch -

    map(.buildNo |= tonumber) | sort_by(.buildNo)

In future, please ask usage questions at stackoverflow.com using the jq tag.
