### ISSUE TITLE
Suggestion: stream windowing

### ISSUE THREAD

**Issue by connesc** [stedolan/jq#1577]
Currently, the only way to combine distinct JSON entities is to use `--slurp`, which loads the entire input into memory.

An intermediate approach would be to add a `window(size, step)` filter, which produces arrays of (at most) `size` input items, each array starting `step` items further than the previous one.
With `step = 1`, we can get a sliding window, while with `step = size` we can slice the input into fixed-size chunks.
The last chunk may be partial, but this can be filtered manually with `| select(length == XXX)`.

Examples:

```
printf '%s\n' 1 2 3 4 | jq 'window(2, 1) | add / length'
=> 1.5
   2.5
   3.5
```

```
printf '%s\n' 1 2 3 4 5 | jq 'window(2, 2) | add / length'
=> 1.5
   3.5
   5
```

Would this be possible with `jq`?

**Comment by pkoppstein** [comment]
This issue was addressed (long ago) in jq 1.5, the current official release.

In short, simply use `inputs` (normally with the `-n` option).  Further details and examples are in the jq manual and other online resources.

**Comment by connesc** [comment]
Thanks @pkoppstein for pointing this out! I have found further reference in #197.

For future reference, I have been able to write the `window` like this:

```
def window(values; size; step): foreach values as $item ({index: 0, items: []}; {index: (.index + 1), items: (.items + [$item])[-size:]}; if (.items | length) == size and ((.index + size) % step) == 0 then .items else empty end);
```

Then I can successfully use it with `inputs`:

```
printf "%s\n" 1 2 3 4 | jq -n 'include "./window"; window(inputs; 2; 1) | add / length'
=> 1.5
   2.5
   3.5
```

Note that this implementation ignore the terminal partial chunk (if any).

Question: isn't the `window` function generic enough to be included as a builtin?

**Comment by pkoppstein** [comment]
> isn't the window function generic enough to be included as a builtin?

Unfortunately there is currently a rather high penalty for adding new builtins, so in general it has become difficult to justify the cost of a new one unless it supersedes an old one.

As it happens, there is some overlap between your `window` and the existing filters, `_nwise/1` and `_nwise/2`.  I have already proposed (#1572) removing the latter and replacing the former with a much more efficient version: 

```
def _nwise($n):
  def nw: if length <= $n then . else .[0:$n] , (.[$n:] | nw) end;
  nw;
```

So one question which would need to be answered is: Is there a significant performance difference between this revised `_nwise/1` and the same functionality implemented using `window/3`?  Would you care to run some tests?

**Comment by connesc** [comment]
You are right, my initial implementation was ignoring any partial group at the end of the stream. I was aware of that, but did not spend much time because it's not trivial to handle.

Good news: this is fixed now! I have implemented a much more robust version of `window/3` in [this gist](https://gist.github.com/connesc/d6b87cbacae13d4fd58763724049da58).
The code is more complex, so I have added comments and tests. I'm confident it's working as expected now.

Based on that, implementing `_nwise/1` is as simple as:

```
def _nwise($n): window(.[]; $n; $n);
```

Regarding performance, I have used the same test case as #1572:

```
jq -n '[[range(0; n)] | _nwise(3)] | length'
```

Since the main benefit of `window/3` is to operate directly in streaming mode, I have also tested this equivalent command:

```
jq -n 'reduce window(range(0; n); 3; 3) as $in (0; . += 1)'
``` 

For each test, I have monitored the total time and the maximum memory usage:

`n` | builtin | optimized | `window`-based | `window` streaming
-- | -- | -- | -- | --
10,000 | 10.57 s / 4180 KB | 0.01 s / 2384 KB | 0.07 s / 2712 KB | 0.05 s / 2344 KB
100,000 | 1093.70 s / 27028 KB | 0.09 s / 5232 KB | 0.44 s / 8340 KB | 0.47 s / 2488 KB
1,000,000 | | 0.83 s / 35932 KB | 4.32 s / 67148 KB | 4.40 s / 2244 KB
10,000,000 | | 8.30 s / 253252 KB | 41.97 s / 628932 KB | 43.46 s / 2404 KB

Conclusions:
* Both time and memory usage are linear for the optimized `_nwise/1` and the `window`-based implementation. Far far better than the builtin version.
* The optimized `_nwise/1` performs clearly better than the `window`-based implementation: speed x5, memory /2.
* The streaming approach permitted by `window/3` allows to keep memory usage constant, whatever the size of the input stream.

So, `window/3` appears to be more powerful while the optimized version of `_nwise/1` is lighter. Classic dilemma. :smile:

**Comment by nicowilliams** [comment]
Well done!

**Comment by pkoppstein** [comment]
@connesc - Thanks for the excellent research!  It's nice to know that TCO works properly :-)

@nicowilliams - This little exercise highlights what I think is a significant deficiency in jq at the moment - the inability to handle an "end-of-stream" condition efficiently and in general.  Sometimes, of course, one can circumvent the problem by giving up on generality (e.g. using `null` or `NaN` as an EOS marker), but any generic solution, such as the boxing technique used here, seems to come at the cost of performance in some way.  Is this issue worthy of its own Enhancement Request?

**Comment by connesc** [comment]
Thanks for your answers!

FYI, I have written yet another version of `window/3` ([updated gist](https://gist.github.com/connesc/d6b87cbacae13d4fd58763724049da58)). This one is much simpler and a bit more performant. :tada: 

Back to the performance comparison with the optimized `_nwise/1`, it is worth noting that its complexity is proportional to the **output** length, while the complexity of `window/3` is proportional to the **input** length. This makes a big difference when changing the `$n` parameter: for a given input, both versions are roughly as fast for `$n == 1`, but your `_nwise/1` become faster and faster when increasing `$n`.
I think this is inherent to the streaming approach of `window/3`, so I don't expect any huge improvement.

That said, I still believe that `window/3` could be a good replacement for the builtin `_nwise`:

* A complexity proportional to the input length is probably what users expect spontaneously, and it is already much better than the builtin version.
* That allows to improve native jq features without increasing the number of builtins.
* The need for grouping consecutive items arises very often (at least, it did many times for me), and would be nice to be addressable without having to resort to `foreach` or `reduce`, which are not beginners-friendly.

**Comment by nicowilliams** [comment]
@pkoppstein The lack of an `EOS` value is rather inherent to jq's design.  `empty` backtracks -- it could not produce `EOS` then backtrack.  You're right that one can use `NaN`s as an `EOS` by convention, and perhaps we could add a `NaN`-like value to be a better `EOS`, but we can't make jq add an `EOS` to the input stream, or `empty`.

**Comment by pkoppstein** [comment]
@nicowilliams - I hesitate to respond given the importance of the next jq release, but for future reference, I was hoping that a variation of `foreach` along the following lines would be feasible:

     foreach stream as $x (START; MIDDLE; EMIT; FINALLY)

That is, the effect would be:

    foreach ((stream|[.]), null) as $boxed (START;
      if $boxed == null then . else $boxed[0] as $x | MIDDLE end;
      if $boxed == null then FINALLY else EMIT end);

but hopefully without the boxing :-)

**Comment by nicowilliams** [comment]
Oh yes, I've been wanting `finally` expressions...

**Comment by connesc** [comment]
The *finalize form* of `foreach` looks really interesting IMHO.
I would just expose `$x` to `EMIT` as well.

To illustrate how this form could be used, I have added 2 files to [the gist](https://gist.github.com/connesc/d6b87cbacae13d4fd58763724049da58):

* `window_finalize.jq`: example of how `window/3` could be implemented with the new form
* `window_finalize_converted.jq`: the same example converted to a correct jq program as proposed above
