### ISSUE TITLE
Strange output with select filter

### ISSUE THREAD

**Issue by vw1234** [stedolan/jq#1578]
I am playing the jq at https://jqplay.org/ as I am new to the JQ.  I have difficult to understand the output. Here is my original json file
```
{
    "instanceSnapshots": [
        {
            "fromInstanceName": "Ubuntu-4GB-DB-warehouse",
            "fromAttachedDisks": [],
            "name": "DB_warehouse-2018-01-03_21.12" ,
            "createdAt": 1515013977.464
        },
        {
            "fromInstanceName": "Ubuntu-4GB-DB-warehouse",
            "fromAttachedDisks": [],
            "name": "DB_warehouse-2018-01-04_17.50",
            "createdAt": 1515088259.406
        },
        {
            "fromInstanceName": "Ubuntu-4GB-Web",
            "fromAttachedDisks": [],
            "name": "AWC_Web-2018-01-04_06.25",
            "createdAt": 1515047106.259
        }
    ]
}
```
if I run:  jq '.[] | select(.[].fromInstanceName | contains("Ubuntu-4GB-DB-warehouse"))'
I got the objects listed twice.

I  run : .[] | select(.[].fromInstanceName | contains("Ubuntu-4GB-DB-warehouse")) | .[].name and got 
```
"DB_warehouse-2018-01-03_21.12"
"DB_warehouse-2018-01-04_17.50"
"AWC_Web-2018-01-04_06.25"
"DB_warehouse-2018-01-03_21.12"
"DB_warehouse-2018-01-04_17.50"
"AWC_Web-2018-01-04_06.25"
```
I expected to have two items listed as I have two objects in the original file with fromInstanceName as Ubuntu-4GB-DB-warehouse

I run .instanceSnapshots[] | select(.fromInstanceName | contains("Ubuntu-4GB-DB-warehouse")) | .name and get the right result. but I can not use the sort_by createdAt anymore.

I googled and played more but I can't make it work well for me.  Any ideas about this?
Thanks a lot.

**Comment by nicowilliams** [comment]
Sort first, then iterate and select.  Something like:

```
jq '.instanceSnapshots | sort_by(.createdAt) | .[] | select(.fromInstanceName | contains("Ubuntu-4GB-DB-warehouse")) | .name'
```

**Comment by vw1234** [comment]
Thanks a lot, nicowilliams.  This works great.  
Do you know why jq '.[] | select(.[].fromInstanceName | contains("Ubuntu-4GB-DB-warehouse"))' list the objects twice? I know I have two items match the filter.  But why not just the right items ?

**Comment by nicowilliams** [comment]
@vw1234 Yes: because you're iterating inside the `select()`.  You're welcome!
