### ISSUE TITLE
should use "," comma for "as" 

### ISSUE THREAD

**Issue by knoguchi** [stedolan/jq#1586]
The syntax for "as $var" with "|" is confusing.  Once "as" is in place it's no longer piping the output.  Therefore | is inappropriate.  

I suggest a comma "," in place of "|", or add "," as alternative syntax in order to keep the backward compatibility.  Thoughts?

**Comment by pkoppstein** [comment]
> once "as" is in place it's no longer piping the output. 

That's simply incorrect, as you can easily see e.g. from the fact that `1 | 2 as $x | .` produces 1.

Indeed, you can think of `E as $x` as `.` with the side-effect that $x is bound to the (or a) value produced by E.  

Evidently you've simply misunderstood something along the way, but it really is very simple once you realize how simple it is :-)

**Comment by knoguchi** [comment]
Sorry if my phrasing was unclear.  I'm not misunderstanding.   I know your example produces 1.   `1 | 2 | .` and `1 | 2 as $x | .` produce different output.  That's not great is my point.  The current design might be simple but readability is low. 

It becomes more unclear when it has multiple `as`es and pipes.   You have to scan for `as` and backtrack to find the input for the next filter.  By introducing comma, you only have to look for | regardless the number of `as` in between the pipes.

Manual of Assignment:
> The expression exp as $x | ... means: for each value of expression exp, run the rest of the pipeline with the entire original input, and with $x set to that value. Thus as functions as something of a foreach loop.

Sounds like it works as control flow as well as variable binding operator.    Are there languages that work similarly?   I'm genuinely curious.  

thanks :)

**Comment by pkoppstein** [comment]
> You have to scan for as and backtrack to find the input for the next filter.

Perhaps you should read jq from top to bottom, as with most (all?) natural languages; at least that's why I like to have the pipes aligned vertically:

```
1
| 2 as $x
| .

```
To me that looks much better than any alternative I can think of that retains the centrality of pipelines as an organizing principle.

**Comment by nicowilliams** [comment]
So, maybe a slightly different syntax would be better, but it doesn't seem terribly important.
