### ISSUE TITLE
Add benchmark tests

### ISSUE THREAD

**Issue by antonmedv** [stedolan/jq#1589]
Does jq was some benchmark tests?

**Comment by nicowilliams** [comment]
No, it doesn't.  It really should though...

**Comment by antonmedv** [comment]
Please, recreate issue.

**Comment by pkoppstein** [comment]
A possible starting point: https://github.com/stedolan/jq/wiki/X---Experimental-Benchmarks

**Comment by nicowilliams** [comment]
Thanks @pkoppstein.

@antonmedv Why recreate?
