### ISSUE TITLE
Merging results into a single array - by "reduce"?

### ISSUE THREAD

**Issue by jot-the-coder** [stedolan/jq#1594]
I'm new to jq and would like to ask a question about **merging results into a single array** in version 1.5.

Say I have an array of JSON objects:
```
[
  { "x": "1", "y": "A" },
  { "x": "2", "y": "B" },
  { "x": "3", "y": "C" },
  { "x": "4", "y": "D" }
]  
```
and to process each of them and finish as an array, say
```
[
  {
    "id": "1",
    "name": {
      "en": "A"
    }
  },
  {
    "id": "2",
    "name": {
      "en": "B"
    }
  },
  {
    "id": "3",
    "name": {
      "en": "C"
    }
  },
  {
    "id": "4",
    "name": {
      "en": "D"
    }
  }
]
```
Then I write my filter like this: `.[] | { id: .x, name: { en: .y } }`. Of course it's not the right way since the array is broken into serveral results:
```
{
  "id": "1",
  "name": {
    "en": "A"
  }
}
{
  "id": "2",
  "name": {
    "en": "B"
  }
}
....
```

Even I reduce it like
`.[] | { id: .x, name: { en: .y } } | reduce . as $item ([]; . + [$item])`
it's still not a single array but 4 array containing each object: (jqplay here: [https://jqplay.org/s/vfeI259moz](https://jqplay.org/s/vfeI259moz))
```
[
  {
    "id": "1",
    "name": {
      "en": "A"
    }
  }
]
[
  {
    "id": "2",
    "name": {
      "en": "B"
    }
  }
]
....
```

Though I know a filter like this would do the job:
`reduce .[] as $item ([]; . + [{ id: $item.x, name: { en: $item.y } }])`
still there are reasons for me here (and occasions for us) that a filter ".[] | ......" could be helpful to manipulate items - just they are broken down after that.

Hence I would like to know if there is **a way to merge the multiple results back to an array again?** (as well as a bigger JSON too, if possible) I've went through the documents of jq, it mentioned that functions like "reduce" and "foreach" are ways to loop each item, but it seems they do not behave the way I am looking for. Could that be my wrong usage on them?

Or would there be something like "meld" or "join" something that I missed in the documents?

Thanks very much for the help.

**Comment by pkoppstein** [comment]
The following filter will produce the results you indicated you want:

    map( {id: .x, name: {en: .y}} )

In future, please ask any usage questions at stackoverflow.com with the jq tag:

stackoverflow.com/questions/tagged/jq

Thanks.

**Comment by jot-the-coder** [comment]
Thanks @pkoppstein , it's exactly what I missed.
