### ISSUE TITLE
string and number cannot be used for join()

### ISSUE THREAD

**Issue by jpcarey** [stedolan/jq#1595]
If you run the `join` example, it errors:
```
jq: error (at <stdin>:0): string (" ") and number (1) cannot be added
exit status 5
```

 `jq 'join(" ")'`
input: `["a",1,2.3,true,null,false]`
output: `"a 1 2.3 true  false"`

version 1.5

From the docs:
> Numbers and booleans in the input are converted to strings. Null values are treated as empty strings. Arrays and objects in the input are not supported.

**Comment by pkoppstein** [comment]
I believe the documentation you are citing refers to the "development" version of jq, whereas the behavior (as you note) corresponds to jq 1.5.  In any case, please note that `join/1` was enhanced in after the release of jq 1.5 (in August 2015), and now behaves in accordance with the specification you mention.

**Comment by jpcarey** [comment]
Yeah, after I opened, I went looking at the source to fix. The one in
source works properly.
https://github.com/stedolan/jq/blob/master/src/builtin.jq#L63-L66
