### ISSUE TITLE
feature request: add --arg-input , -i to suck input json directly from process argument instead of stdin or input files 

### ISSUE THREAD

**Issue by etosan** [stedolan/jq#1601]
First thanks for this awesome tool! It is making my life infinitely easier.  

> Until now I used it mainly for json log processing and for other data handling.
>
>Recently I started to use it more and more in shell scripts. 
By shell I mean real, POSIX compliant shells like DASH and various POSIX compatible BSD versions,
eg. not bash, as it is not present in certain environments .
> There are some small warts when using jq this way, but it is bearable, as one can easily wrap jq into shellfuncs and have them deal with that.

JSON is relatively bearable format for both humans and machines and allows one to get structural data, otherwise quite hard to do in shell, easily.

It's also easy to store JSON fragments in shell variables, newlines or not. 

Sometimes one needs to transform data on their way out from jq, in raw form. This can be handled, too by piping into `tr`,`awk` or `sed`.

However at some point certain awkwardness is introduced into the machinery.

Consider this:
```sh
JSON_FRAG='{"tval": true, "fval": false, "nval": 42}'
```
When one wants to jq-ize `$JSON_FRAG`, the var has to be sent to jq through pipeline:

```sh
JSON_RESULT="$(printf '%s' "${JSON_FRAG}" | jq '.tval')"
```

This has several effects, but most important are, that shell (might or might not) spawn sub process (which is quite a waste of resources, in addition to spawning jq) for printing, and second is getting errors from pipelines is extremely flaky, if not directly impossible (in posix shells). In general, even `exec >` trickery doesn't cut it.

Although many kinds of hacks around this are possible, it would be easiest and most efficient if one could just send input json fragment as blob in process argument vector (instead of it being stdin or input file).

Described idiom would then become:

```sh
JSON_RESULT="$(jq -i "${JSON_FRAG}" '.tval')"
#or
JSON_RESULT="$(jq --arg-input "${JSON_FRAG}" '.tval')"
```
Most importantly it is now possible to handle processing errors:
```sh
JSON_RESULT="$(jq -e -i "${JSON_FRAG}" '.tval')" || { printf 'script: %s' 'processing json failed!' ; exit 1 ; }
```

jq already seems to have json from argument reading infrastructure in place for `--argjson` handling, so this would probably be minor architectural change. Decision how to handle multiple input sources (stdin, argument, files) should be made by someone more familair with jq.

Also jq already handles inputless use case with `--null-input`,`-n`, so this would be minor addition to the program.

I believe this would bring great advantages to shell scripters everywhere.

Hope I haven't missed anything described in manual how to do this other way.

**Comment by pkoppstein** [comment]
> Hope I haven't missed anything described in manual how to do this other way.

It seems maybe you've missed --arg and --argjson

For example, instead of:

    JSON_RESULT="$(printf '%s' "${JSON_FRAG}" | jq '.tval')"

you can write:

    JSON_RESULT="$(jq -n --argjson j "$JSON_FRAG" '$j | .tval')"

Note also that in bash and friends, one can use so-called "here-strings":

    JSON_RESULT="$(jq .tval <<< "$JSON_FRAG")"

**Comment by etosan** [comment]
Unfortunately <<< "here-strings", that look most compact, seems not to be POSIX portable and is some kind of bashism. Search of POSIX docs reveals presence of string "here-doc"  but I couldn't find string "here-string" (pun intended), although it might be defined somewhere, where it wasn't found, as I used web interface.

At least all the environments I have access to die with similar error:

```
$ /bin/sh -c 'cat <<< test'
sh: 1: Syntax error: redirection unexpected
```

or

```
$ /bin/sh -c 'cat <<< test'
sh: Syntax error: redirection unexpected (expecting word)
```

Thanks this hack of yours is much better:
```
JSON_RESULT="$(jq -n --argjson j "$JSON_FRAG" '$j | .tval')"
```
I never used jq `$var`, so I was unaware I can actually do this!

For better readability this can be wrapped into shellfunc, so it basically fixes my problem albeit in a roundabout way.

But I still maintain that `-i`/`-I`/`--input-arg`/`--arg-input` or something like that would be much more usable/discoverable.

I believe the code change would be minimal, and for users who bind custom `$var`s it would clearly differentiate "arg input point" from "var arg bind points". Also `jq -i "$data"` is more readable than `jq -n  --argjson j "$JSON_FRAG" '$j'`.

So my question becomes, if there is no will to do it, are there any chances of patch doing this (adding -i) even getting through?

**Comment by pkoppstein** [comment]
> are there any chances of patch doing this (adding -i) even getting through?

Good question.  The jq maintainers have expressed a great deal of reluctance to add new flags.  Also, as you may have noticed, there has not been any software update for over two months, even though there is at least one very worthy outstanding PR.

**Comment by etosan** [comment]
Roger then, for now I will use your workaround for the time being. Thank you very much!

**Comment by nicowilliams** [comment]
@etosan In `master` we have `--args` and `--jsonargs`, which lets you access remaining arguments via `$ARGS` in the jq program.
