### ISSUE TITLE
Help needed: Merging two hashes based on a subkey

### ISSUE THREAD

**Issue by Ganneff** [stedolan/jq#1602]
Hi,

help needed! I am trying to merge a json data structure from a tool in a useful way for me, but I seem unable to get the right magic out.

What I have is

`{
  "version": 2150000,
  "instances": {
    "013cb70f-044f-4ef9-8749-7335e65f5d6d": {
      "name": "machine1.domain.example.com",
      "primary_node": "cb8562cd-eac0-425a-98f3-7f4b6c0836fe",
      "os": "debootstrap+jessie",
      "hypervisor": "kvm",
      "hvparams": {
        "initrd_path": "",
        "kernel_path": ""
      },
      "beparams": {
        "minmem": 4096,
        "maxmem": 4096,
        "vcpus": 2
      },
      "osparams": {},
      "osparams_private": {},
      "admin_state": "up",
      "admin_state_source": "admin",
      "nics": [
        {
          "mac": "aa:00:00:9c:e0:6d",
          "nicparams": {
            "link": "something"
          },
          "uuid": "05dc81d6-8f19-44ca-9071-49a70234243a"
        },
        {
          "mac": "aa:00:00:f3:97:88",
          "nicparams": {
            "link": "otherthing"
          },
          "uuid": "beed4558-d687-4852-8faa-252122dc60f8"
        }
      ],
      "disks": [
        "57956993-1414-4bb6-86f8-598534ee44cf",
        "66313224-3542-413b-a5f0-c1d4c59bf6bb",
        "c0f9000b-c96f-4c30-947b-2898f84a141b"
      ],
      "disks_active": true,
      "network_port": 11303,
      "ctime": 1489588297.352438,
      "mtime": 1502112548.53799,
      "uuid": "013cb70f-044f-4ef9-8749-7335e65f5d6d",
      "serial_no": 14,
      "tags": [
        "nfs",
        "test",
      ]
    }
  },
  "networks": {},
  "disks": {
    "57956993-1414-4bb6-86f8-598534ee44cf": {
      "logical_id": [
        "3par",
        "07265184-925e-49a5-8de8-75bfd67e7784.ext.disk0"
      ],
      "dev_type": "ext",
      "children": [],
      "nodes": [],
      "iv_name": "disk/0",
      "size": 10240,
      "mode": "rw",
      "params": {
        "cpg": "AO_High_SSD_r5",
        "provider": "3par",
        "prv": "thin"
      },
      "uuid": "57956993-1414-4bb6-86f8-598534ee44cf",
      "serial_no": 1,
      "ctime": 1489588299.115079,
      "mtime": 1489588299.115079
    },
    "66313224-3542-413b-a5f0-c1d4c59bf6bb": {
      "logical_id": [
        "3par",
        "163f4b3f-967e-45e2-9893-902291db68ba.ext.disk1"
      ],
      "dev_type": "ext",
      "children": [],
      "nodes": [],
      "iv_name": "disk/1",
      "size": 1024,
      "mode": "rw",
      "name": "96a376df-6c14-43c1-8092-40198026a443.ext.disk1",
      "params": {
        "cpg": "unused",
        "hnm": "someothermachine:disk1",
        "provider": "3par",
        "prv": "thin"
      },
      "uuid": "66313224-3542-413b-a5f0-c1d4c59bf6bb",
      "serial_no": 1,
      "ctime": 1489588300.608801,
      "mtime": 1489588300.608801
    },
    "c0f9000b-c96f-4c30-947b-2898f84a141b": {
      "logical_id": [
        "3par",
        "444cef1b-2d04-4384-b599-ec1e43cf9df4.ext.disk2"
      ],
      "dev_type": "ext",
      "children": [],
      "nodes": [],
      "iv_name": "disk/2",
      "size": 1024,
      "mode": "rw",
      "params": {
        "cpg": "FC_r5",
        "provider": "3par",
        "prv": "thin"
      },
      "uuid": "c0f9000b-c96f-4c30-947b-2898f84a141b",
      "serial_no": 1,
      "ctime": 1489588302.78969,
      "mtime": 1489588302.78969
    }
  },
  "filters": {},
  "ctime": 1399471610.073019,
  "mtime": 1518172346.130795,
  "serial_no": 18003
}
`

and what I would like to achieve is getting it merged so that the
disks array entries in the instances are replaced with the actual data
for the disks, which can be found in the disks dictionary later.

I am able to extract things left and right, but I can't wrap my head
around replacing the plain UUIDs in that area by their actual data.

Any hint on how to go for that would be great!

Thanks!

**Comment by pkoppstein** [comment]
The trick is to begin by creating a variable to hold the dictionary: 

    .disks as $disks    
    | (.instances | .[] | .disks) |= map( $disks[.] )

The above may not be exactly what you want, but it should give you some ideas.  

For future reference, please ask usage questions at stackoverflow.com with the jq tag:
https://stackoverflow.com/questions/tagged/jq

That way, more people will be able to respond, and the answer(s) will be probably be more readily findable as well.

**Comment by Ganneff** [comment]
Hi

great, thank you, that actually does 98% of what I want, to add the rest is simple. The thing with the variable got me going, thanks for that.

And sorry, next time its stackoverflow.
