### ISSUE TITLE
Feature Request argument to redact sensitive values

### ISSUE THREAD

**Issue by majormoses** [stedolan/jq#1603]
It is pretty common that I often curl api's or cat files that have secrets and rather than pulling the data and then pasting it into github, gist, pastebin, slack, etc and then manually redacting the info it would be nice if I could ensure that it is redacted before copy/pasting in case you accidentally click a button or hit enter submitting it.

Something along these lines:
```
# ideally something like this
cat /tmp/uchiwa.json | jq --redact .uchiwa.pass --redact uchiwa.user .

# Ideally it would produce a json blob something like this
{
  "uchiwa": {
    "user": "<REDACTED>",
    "pass": "<REDACTED>",
    "refresh": 5,
    "host": "0.0.0.0",
    "port": 3000
  },
  "sensu": [
    {
      "name": "Sensu",
      "host": "127.0.0.1",
      "url": "http://127.0.0.1:4567",
      "path": "",
      "ssl": false,
      "timeout": 5
    }
  ]
}
```

**Comment by pkoppstein** [comment]
For reference, here are some workarounds.

1. Direct approach

    `jq '.uchiwa.pass = "<REDACTED>" | .uchiwa.user = "<REDACTED>"' `

2. Using def

   ` jq 'def r(p):p="<REDACTED>"; .uchiwa |= (r(.pass)|r(.user))' `

3. Using def and walk

    ` jq 'def r(p;q):p="<REDACTED>"|q="<REDACTED>"; walk(if has("pass")? // false then r(.user; .pass)  else . end)'`

If your jq does not have walk, you can snarf its def from the jq[ FAQ ](https://github.com/stedolan/jq/wiki/FAQ)or [builtin.jq](https://github.com/stedolan/jq/blob/master/src/builtin.jq)

**Comment by majormoses** [comment]
Nice I will have to start using some of those workarounds but I think it should be a first class feature at some point.

**Comment by nicowilliams** [comment]
@majormoses jq is a *general* programming language.  You can do what you request entirely as a jq program.  We don't add command-line options anymore for things that can be done with existing command-line options and jq's programming power.
