### ISSUE TITLE
Make it portable

### ISSUE THREAD

**Issue by ruipach** [stedolan/jq#1604]
Hi,

how about making it portable?

I am trying to deploy this little (big) took in a linux system without root permissions.
Unfortunatelly it's wasn't possible, as the binaries are not working (segmentation fault) and the binaries extraced from the packaged (fedora) require the lib files in /usr/lib64 where my user is not able to deply files.

Could these be placed along with the jq binary and make it really portable, without the need for root access?

Thanks!
RPach

**Comment by nicowilliams** [comment]
The binaries *we* release are statically linked.  If that doesn't work for you then you need to build from source.

As an aside: you should never expect that you can install bits by hand that are taken from a packaging system and that that should work.

**Comment by ruipach** [comment]
Hi

Thanks for the fast reply!

I have tried to use the packaged version because the statically linked
binaries (jq-linux64) do not run: segmentation fault.

$ uname -r
2.6.18-406.el5

Regards



--
Não divulgue o endereço electrónico dos seus amigos. Use "Bcc" ou "Cco" -
cópia oculta - para enviar os seus emails. Retire os endereços dos seus
amigos antes de reenviar. Dificulte a disseminação de vírus, spams e
banners.

**Comment by nicowilliams** [comment]
@ruipach Can you paste `uname -srvmpio` output?

**Comment by ruipach** [comment]
Hi Nico,

here's the output:

$ uname -srvmpio
Linux 2.6.18-406.el5 #1 SMP Fri May 1 10:37:57 EDT 2015 x86_64 x86_64
x86_64 GNU/Linux

Thanks!


--
Não divulgue o endereço electrónico dos seus amigos. Use "Bcc" ou "Cco" -
cópia oculta - para enviar os seus emails. Retire os endereços dos seus
amigos antes de reenviar. Dificulte a disseminação de vírus, spams e
banners.
