### ISSUE TITLE
Matching entries in two arrays

### ISSUE THREAD

**Issue by TheChatty** [stedolan/jq#1609]
I have a primary array `[{"id":"a","p":5},{"id":"b","p":7},{"id":"c","p":8}]` and a secondary array `[{"id":"a","p":9},{"id":"b","p":7},{"id":"d","p":4}]`. Now I want to enhance the primary array with data from secondary array if available (and delete entries where .p==.c).

The most intuitive approach (to me) isn't working:
```
# echo '[{"id":"a","p":5},{"id":"b","p":7},{"id":"c","p":8}]' | jq -c --argjson sec '[{"id":"a","p":9},{"id":"b","p":7},{"id":"d","p":4}]' '.[]|{id,p,"c":$sec[.id].p}'
jq: error (at <stdin>:1): Cannot index array with string "a"
```

An approach using select removes elements not available in both arrays:
```
# echo '[{"id":"a","p":5},{"id":"b","p":7},{"id":"c","p":8}]' | jq -c --argjson sec '[{"id":"a","p":9},{"id":"b","p":7},{"id":"d","p":4}]' '.[]|. as {id:$id,p:$c}|{id,p,"c":($sec[]|select(.id==$id and .p!=$c).p)}'
{"id":"a","p":5,"c":9}
```

I want to achieve this output (keep entries even though not in the secondary array):
```
{"id":"a","p":5,"c":9}
{"id":"c","p":8,"c":null}
```

**Comment by pkoppstein** [comment]
This q has been asked (and answered) at https://stackoverflow.com/questions/49040090/jq-enrich-primary-array-with-secondary-array
