### ISSUE TITLE
new line error in zshell: command not found: \n

### ISSUE THREAD

**Issue by ElePhontitis** [stedolan/jq#1615]
Parsing json with freshly installed jq 1.5 works, but with zshell this error always appears at the last line of the output:

`zsh: command not found: \n`

**Comment by ElePhontitis** [comment]
Issue only appears if I use single quotes in a command like `jq  '.taskDefinition'`

**Comment by pkoppstein** [comment]
Please be more specific as to input, and computing environment. Using zsh on a Mac, there is no problem whatsoever, e.g.

    jq -n '.foo'
    null

Following the mcve guidelines at https://stackoverflow.com/help/mcve would be a good start. Thank you.

**Comment by ElePhontitis** [comment]
I am sorry, my shell somehow appended a "\n" after each line. Just saw it when I scrolled through my terminal history. Closing this. Sorry bothering you!
