### ISSUE TITLE
Sort Keys insensitive

### ISSUE THREAD

**Issue by iamandrewluca** [stedolan/jq#1621]
I was able to combine 3 files using `jq` and sort keys using `--sort-keys` but the sorting is case sensitive.

```bash
jq -Ss '.[0] * .[1] * .[2]' file1.json file2.json file3.json > final.json
```
Is there any way to sort using case insensitive?
Thanks in advance!

**Comment by pkoppstein** [comment]
Currently, you would have to sort the keys programmatically.  Here is a generic function for sorting the keys of an object by some criterion:
```
def keys_sort_by(f):
  to_entries | sort_by(.key|f ) | from_entries;
```
Given a JSON object, this could be used  like so:

    keys_sort_by(ascii_upcase)

To handle an arbitrary JSON document (or documents):

    walk(if type == "object" then keys_sort_by(ascii_upcase) else . end)

If your jq does not have `walk`, its def can be snarfed from the jq FAQ https://github.com/stedolan/jq/wiki/FAQ or from https://github.com/stedolan/jq/blob/master/src/builtin.jq
