### ISSUE TITLE
Feature request: Guide to adding built-ins

### ISSUE THREAD

**Issue by JesseTG** [stedolan/jq#1630]
There are a few builtins I'd like to add.  Adding to `builtins.jq` is easy, because that's literally an embedded script.  However, I want to add to `builtins.c` to implement some functionality that can't easily be done in `jq` such as hexadecimal conversions, and I don't quite know how to do that.  Can you point me to the following:

- Conventions you want to maintain
- Handling the possibility of different types as input
- Handling multiple arguments
- Raising errors
- Any resource management I need to do

Thank you, I'd appreciate that.

**Comment by pkoppstein** [comment]
Many of the pages on the jq wiki address the questions you raise. You might like to start with the “Internals” pages, such as https://github.com/stedolan/jq/wiki/Internals:-introduction

**Comment by JesseTG** [comment]
...ah.  Okay, thank you.  If need be, I'll update the wiki pages to make some of this more clear.
