### ISSUE TITLE
Can't sub asterisk

### ISSUE THREAD

**Issue by hoshsadiq** [stedolan/jq#1633]
This is possibly a bug. I'm trying to replace the asterisk character from a string, but no matter what I try it refuses to work. This is the result

```
$ jq '"*" | sub("\\*", "something else")'
jq: error: sub/1 is not defined at <top-level>, line 1:
"*" | sub("\\*", "something else")       
jq: 1 compile error
$ jq '"*" | sub("\\\\*", "something else")'
jq: error: sub/1 is not defined at <top-level>, line 1:
"*" | sub("\\\\*", "something else")       
jq: 1 compile error
```

Any ideas how this can be solved?

**Comment by wtlangford** [comment]
The comma operator doesn't do what you think it does here. What you wanted was `sub("\\*"; "something else")`. jq uses `;` to separate arguments.

See [the docs](https://stedolan.github.io/jq/manual/#Comma:,) for a bit more on the comma operator, but essentially, what you're doing is trying to call `sub/1` with a single argument twice (first as `sub("\\*")`, then as `sub("something else")` and then you'd get an output stream of the results from those calls. Except, there is no `sub/1`, which is the error you're receiving.

**Comment by hoshsadiq** [comment]
Oh wow! That dreaded semicolon bites again. Thanks!
