### ISSUE TITLE
`localtime` does not seem to be a filter/function, even when mentioned in the doc.

### ISSUE THREAD

**Issue by Pysis868** [stedolan/jq#1634]
Same applies to the similar `strflocaltime`.

For this one, like `strftime`, they seem to be functions, rather than filters, so adding a `("")` suffix gives a better error message showing me that the functionality does exist.

```
⋊> ~ jq -n '1521834943 | localtime'
jq: error: localtime/0 is not defined at <top-level>, line 1:
1521834943 | localtime
jq: 1 compile error

⋊> ~ jq -n 'localtime("")'
jq: error: localtime/1 is not defined at <top-level>, line 1:
localtime("")
jq: 1 compile error

⋊> ~ jq -n 'strflocaltime("")'
jq: error: strflocaltime/1 is not defined at <top-level>, line 1:
strflocaltime("")
jq: 1 compile error

⋊> ~ jq --version
jq-1.5
⋊> ~ brew info jq
jq: stable 1.5 (bottled), devel 1.6rc1, HEAD
Lightweight and flexible command-line JSON processor
https://stedolan.github.io/jq/
/usr/local/Cellar/jq/1.5 (18 files, 954.8KB) *
  Poured from bottle on 2016-02-22 at 21:03:42
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/jq.rb
==> Dependencies
Required: oniguruma ✘
==> Options
--devel
	Install development version 1.6rc1
--HEAD
	Install HEAD version
```

**Comment by Pysis868** [comment]
Found "Add `localtime` and `strflocaltime` (fix #1349)" (06f20603f6022b721fa6a001969fbbb1111f113d) and tag "jq-1.6rc1" on Dec 11, 2017.

I just got confused since I saw `localtime` in the manual online, but they were not in the latest stable release.  If that's the case, and they are actually in `devel`, or even `HEAD`, maybe mark that as such until they are 'fully' included?

**Comment by pkoppstein** [comment]
@Pysis868 - There are several versions of the manual online, one for each released version of jq, and one for the "master" (development) version.  Each version of the manual is appropriately tagged, but you would not be the first to have overlooked the version details. If you really do find a mismatch between the "master" documentation and the "master" version, please let us know.  Thanks.

**Comment by Pysis868** [comment]
How about making the documentation default to stable that is immediately available by default in package managers?

**Comment by ruicih** [comment]
strflocaltime is still not working, where can I find the download "jq-1.6rc1"

**Comment by pkoppstein** [comment]
@ruicih - Please see https://github.com/stedolan/jq/wiki/Installation
