### ISSUE TITLE
group_by does not specify order of resulting inner arrays

### ISSUE THREAD

**Issue by AntiBlueQuirk** [stedolan/jq#1635]
group_by has the following documentation:

"group_by(.foo) takes as input an array, groups the elements having the same .foo field into separate arrays, and produces all of these arrays as elements of a larger array, sorted by the value of the .foo field."

This is useful for many things, but I've been having trouble using it for joining arrays of objects. #1090 suggests that this can easily be done with something like this: `group_by(.id) | map(add)`

Given this data:
```
def items_left:
[
  {"id": "A", "name": ""},
  {"id": "B", "name": ""},
  {"id": "C", "name": ""}
];
def items_right:
[
  {"id": "A", "name": "Aardvark"},
  {"id": "B", "name": "Beetle"},
  {"id": "C", "name": "Caterpillar"}
];
```

Running a script like this `(items_left + items_right) | group_by(.id)` produces the following output:

```
[
  [
    {
      "id": "A",
      "name": ""
    },
    {
      "id": "A",
      "name": "Aardvark"
    }
  ],
  [
    {
      "id": "B",
      "name": ""
    },
    {
      "id": "B",
      "name": "Beetle"
    }
  ],
  [
    {
      "id": "C",
      "name": ""
    },
    {
      "id": "C",
      "name": "Caterpillar"
    }
  ]
]
```

This is fine, and appending `| map(add)` to the script will result in the expected, merged result:

```
[
  {
    "id": "A",
    "name": "Aardvark"
  },
  {
    "id": "B",
    "name": "Beetle"
  },
  {
    "id": "C",
    "name": "Caterpillar"
  }
]
```

However, I have observed that sometimes the order of the inner arrays of group_by's result is not consistent, especially with larger input arrays. For instance, sometimes group_by will return this (snippet) instead:

```
  [
    {
      "id": "C",
      "name": "Caterpillar"
    },
    {
      "id": "C",
      "name": ""
    }
  ]
```

Notice how the inner objects are inverted from the source array now? This means that the result of map(add) will have a value of "" for "name", because the second object is merged into the first. Due to this, I've found `group_by(.id) | map(add)` to be useless for merging objects, since it will randomly decide which object gets precedence for merging.

I think that group_by should have a specified order for the inner arrays, preferably the order that the objects were collected from the input array. (Or maybe that's already the intended behavior, and this is a bug report.)

I've tested both the Cygwin version (--version reports jq-1.5), as well as the most recent win64 version (1.5), and both exhibit this behavior, though they differ in which elements they select to invert. (It might also vary for each execution. I'm not sure.)

**Comment by AntiBlueQuirk** [comment]
I've gotten around this in the meantime by tagging the "right hand" objects with a special merge key, and then reversing the inner arrays in the map if necessary (`map(if .[0].___merge then (reverse | add) else add end)`), then removing the key later.

**Comment by wtlangford** [comment]
That's... odd. I looked through the code and this shouldn't happen. Can you
provide inputs that exhibit the behavior?

**Comment by pkoppstein** [comment]
Please note that `group_by` is implemented using a sorting algorithm and I believe that the following comment in the jq FAQ is in effect applicable to `group_by` as well:

```
As of January 18, 2016 (7835a72), the builtin sort filter is stable; prior to that, stability was
platform-dependent. This means that stability is NOT guaranteed in jq 1.5 or earlier.
```
To obtain a Windows version of jq later than 1.5, see https://github.com/stedolan/jq/wiki/Installation#windows-using-appveyor

**Comment by AntiBlueQuirk** [comment]
@pkoppstein Okay that probably explains it, as well as another problem I was having (`sort_by` was inexplicably acting unstable when I thought it should be. I thought the 1.5 release was more recent than that. I guess I just misread the date. Or maybe I read that FAQ entry as "before 1.5".)

If 7835a72 fixes this, then I guess there's no bug, and I just need to update.
