### ISSUE TITLE
How to search JSON key that contains specific string with jq?

### ISSUE THREAD

**Issue by hillz2** [stedolan/jq#1638]
I have a JSON data:

    {
    	"orderTotal_1": {
    		"fields": {
    			"button": {
    				"actionDialog": null,
    				"actionUrl": null,
    				"clicked": false,
    				"enable": true,
    				"text": "LANJUTKAN KE PEMBAYARAN",
    				"textColor": null
    			},
    			"payment": {
    				"pay": "Rp1.953.800",
    				"taxTip": "Termasuk PPN, jika berlaku.",
    				"title": "Total"
    			},
    			"timestamp": 1522355946093
    		},
    		"id": "1",
    		"tag": "orderTotal",
    		"type": "biz"
    		},
    	"rightContainer_10010": {
    		"fields": {
    			"css": {
    				"backgroundColor": null,
    				"floatPosition": "right",
    				"marginTop": null,
    				"width": "388px"
    			}
    		},
    		"id": "10010",
    		"tag": "rightContainer",
    		"type": "container"
    	},
    	"toPayBtn_10021": {
    		"fields": {
    			"clicked": false,
    			"enable": true,
    			"text": "LANJUTKAN KE PEMBAYARAN"
    		},
    		"id": "10021",
    		"tag": "toPayBtn",
    		"type": "biz"
    	},
    	"voucherInput_1": {
    		"fields": {
    			"buttonText": "GUNAKAN",
    			"placeHolder": "Masukkan Kode Voucher",
    			"status": "default"
    		},
    		"id": "1",
    		"tag": "voucherInput",
    		"type": "biz"
    	}
    }

I want to get `toPayBtn_10021` but the number `10021` is dynamic. So it can be `toPayBtn_34` `toPayBtn_21` etc. 

This is the output that I want to achieve:

    "toPayBtn_10021": {
    	"fields": {
    		"clicked": false,
    		"enable": true,
    		"text": "LANJUTKAN KE PEMBAYARAN"
    	},
    	"id": "10021",
    	"tag": "toPayBtn",
    	"type": "biz"
    }
This is what I have tried:

    jq '.toPayBtn*'

But it results in:

    jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
    .toPayBtn*         
    jq: 1 compile error
    exit status 3

Regex doesn't seem to work with `jq` How do I fix it ?

**Comment by pkoppstein** [comment]
Thanks for your interest in jq.  We have found that it is usually much better for everyone if usage questions about jq are posted on stackoverflow.com with the jq tag:  https://stackoverflow.com/questions/tagged/jq

That way, you are more likely to get faster responses, and others are more likely to benefit as well. In addition, these "Issues" pages can focus on actual issues (bugs and improvements).

Also, besides the "official" tutorial and documentation, you may find the [FAQ](https://github.com/stedolan/jq/wiki/FAQ) helpful.  See in particular the section on regular expressions: https://github.com/stedolan/jq/wiki/FAQ#support-for-regular-expressions

**Comment by hillz2** [comment]
Thank you
