### ISSUE TITLE
Extract a field's value based on another field

### ISSUE THREAD

**Issue by Lepo75** [stedolan/jq#1639]
Hello,

I would like to a field's value based on another field's value. I tried this:
jq '.[] | select(.[logged_in_link] | contains ("virtual") | .id' )
but it gives me error: jq: error: syntax error, unexpected $end, expecting ';' or ')' (Unix shell quoting issues?) at <top-level>, line 1:
.[] | select(.[logged_in_link] | contains ("virtual") | .id  
How can I get the value? Thanks a lot

**Comment by pkoppstein** [comment]
You probably meant something like this:

    jq '.[] | select(.["logged_in_link"] | contains ("virtual")) | .id' 

(Usually the error message is worth heeding.)

In future, please ask usage questions such as this at stackoverflow.com https://stackoverflow.com/questions/tagged/jq

Thank you.

**Comment by Lepo75** [comment]
It works like a charm!
Thanks a lot!
