### ISSUE TITLE
extra open brace syntax error missed by jq

### ISSUE THREAD

**Issue by seachanged** [stedolan/jq#1642]
I just found jq 1.5, just started using it. 

I was torturing it a little to see how well it tolerated junky input, 
tossed in an open brace between entities, 
expected to see a syntax error something like 
"pending object not closed" 
or "incomplete object" 
or "missing } at EOF matches { at line #"

but got nothing. I checked the productions in the source code for bison/yacc, and it looks like it should work ( { ObjPat } ), so it's not immediately obvious why this one slips by.  

Thanks for your time.

**Comment by pkoppstein** [comment]
The issue you describe seems to be same as one that has recently been fixed: https://github.com/stedolan/jq/issues/1305
