### ISSUE TITLE
Wildcards on Windows

### ISSUE THREAD

**Issue by adoxa** [stedolan/jq#1644]
I'm using the 64-bit Windows version (jq-1.6rc1-10-g7fd9e86) from AppVeyor (1.0.285). Passing wildcards on the command line aborts:

```
J:\>jq *.json
Assertion failed!

Program: J:\jq.exe
File: src/main.c, Line 256

Expression: wargc == argc
...
```

**Comment by pkoppstein** [comment]
Try 
    jq . *.json

or 

     jq empty *.json

**Comment by pkoppstein** [comment]
jq currently relies on the shell in which it executes to expand wildcards on the command-line.  I verified that this works on a Windows 10 machine using bash.

**Comment by adoxa** [comment]
It looks like the wildcards are expanded by the runtime (so `argv[]` has the list), but jq is converting the original Unicode Windows command line (so `wargv[]` has the single wildcard). It might be better to wrap `wmain`.

**Comment by sergeevabc** [comment]
Windows 7.
```console
$ json [any command] *.json                      
Assertion failed!                                                             
Program: D:\\\json\jq.exe                                                
File: src/main.c, Line 256                                                    
Expression: wargc == argc                                                     
This application has requested the Runtime to terminate it in an unusual way. 
Please contact the application's support team for more information.           
```

**Comment by adoxa** [comment]
I'd say your version is too old. (Here)[https://ci.appveyor.com/project/stedolan/jq/builds/38968669/job/srl900l3ybjf48rl/artifacts] is the last successful 64-bit build on AppVeyor (untested), but be quick, it expires "in a day".
