### ISSUE TITLE
Parsing JSON Array Data (Support)

### ISSUE THREAD

**Issue by xcertgit** [stedolan/jq#1645]
Dear All,

I have a json output like below. 
How can I transform all array's node data itself to one line separated with "|" using https://jqplay.org/ simulation tool.

[  
  {
    "ABC": 12345,
    "DEF": "X - XXXXXXX",
    "GHI": "ACT",
    "JKL": "0123456789",
    "MNO": "00123456789",
    "PRS": null
  },
  {
    "ABC": 23456,
    "DEF": "Y - YYYYYYYY",
    "GHI": "PASS",
    "JKL": "1234567890",
    "MNO": "01234567890",
    "PRS": "23456Y"
  },
  {
    "ABC": 34567,
    "DEF": "Z - ZZZZZZZZ",
    "GHI": "ACT",
    "JKL": "2345678901",
    "MNO": "02345678901",
    "PRS": null
  },
  {
    "ABC": 45678,
    "DEF": "T - TTTTTTTT",
    "GHI": "PASS",
    "JKL": "3456789012",
    "MNO": "03456789012",
    "PRS": null
  }
]

Result should be:

"12345|X - XXXXXXX|ACT|0123456789|00123456789|"
"23456|Y - YYYYYYY|PASS|1234567890|01234567890|23456Y"
"34567|Z - ZZZZZZZ|ACT|2345678901|02345678901|"
"45678|T - TTTTTTT|PASS|3456789012|03456789012|"

Best

**Comment by bendem** [comment]
You'd use [string interpolation](https://stedolan.github.io/jq/manual/#Stringinterpolation-\(foo\)).

Something like `.[] | "\(.ABC) - \(.DEF) | \(.GHI)"`

**Comment by xcertgit** [comment]
Thanks alot

**Comment by pkoppstein** [comment]
It might be better to use `join`, for example if a generic solution (i.e. independent of the number of keys) is needed:

    .[] | [.[] | tostring] | join("|")

If you are using a sufficiently recent version of jq, you can drop the `tostring` conversion.

For future reference, please ask usage questions at stackoverflow.com with the jq tag: https://stackoverflow.com/questions/tagged/jq

That way, you are more likely to get good answers quickly, and others are more likely to benefit as well.

**Comment by xcertgit** [comment]
@pkoppstein thanks for your contribution.
I am new at around here I will consider your suggestion
