### ISSUE TITLE
How to store a variable and use it in a select

### ISSUE THREAD

**Issue by Wicaeed** [stedolan/jq#1646]
I have the following data structure:
```
[
"NodeID": "vrizvxqcvrs52c28dkz46qwc8",
"RemoteManagers": [
    {
      "NodeID": "vrizvxqcvrs52c28dkz46qwc8",
      "Addr": "10.23.217.200:2377"
    },
    {
      "NodeID": "iavpgnh0z36rjiiu964hti499",
      "Addr": "10.23.217.202:2377"
    },
    {
      "NodeID": "phlc5hx7g2hyhj4f3m1s70il6",
      "Addr": "10.23.217.201:2377"
    }
  ]
```
I would like to return only the nodes that don't match my own NodeID.

So far I've come up with the following:
```
docker info --format '{{ json . }}' | jq -r '.Swarm | .NodeAddr as $a | .RemoteManagers | map(select(.Addr != $a))[0].Addr'
```

However I don't think that the conditional is functioning as I think it is since I keep on returning my own Addr value from the RemoteManagers array:
```
docker info --format '{{ json . }}' | jq -r '.Swarm | .NodeAddr as $a | .RemoteManagers | map(select(.Addr != $a))[0].Addr'
10.23.217.200:2377
```

It seems as if the `$a` variable is not being stored with a value, and is returning all results.

Is there a correct way to use a value from the .NodeID object to filter the results?

**Comment by pkoppstein** [comment]
With the sample JSON as input, the filter:

```
.NodeID as $nid
| .RemoteManagers |= map(select(.NodeID != $nid))
```

produces:

```
{
  "NodeID": "vrizvxqcvrs52c28dkz46qwc8",
  "RemoteManagers": [
    {
      "NodeID": "iavpgnh0z36rjiiu964hti499",
      "Addr": "10.23.217.202:2377"
    },
    {
      "NodeID": "phlc5hx7g2hyhj4f3m1s70il6",
      "Addr": "10.23.217.201:2377"
    }
  ]
}
```

For future reference, please post usage questions at stackoverflow.com with the jq tag:
https://stackoverflow.com/questions/tagged/jq
