### ISSUE TITLE
capture: parse error: Invalid numeric literal at line 2, column 0

### ISSUE THREAD

**Issue by kenorb** [stedolan/jq#1649]
I'm following the example from `man jq`:

           jq 'capture("(?<a>[a-z]+)-(?<n>[0-9]+)")'
              "xyzzy-14"
           => { "a": "xyzzy", "n": "14" }

as follow, but I've got the errors:

```
$ jq 'capture("(?<a>[a-z]+)-(?<n>[0-9]+)")' <<<"xyzzy-14"
parse error: Invalid numeric literal at line 2, column 0
$ echo "xyzzy-14" | jq 'capture("(?<a>[a-z]+)-(?<n>[0-9]+)")'
parse error: Invalid numeric literal at line 2, column 0
```

What I'm doing wrong?

```
$ jq --version
jq-1.5
```

**Comment by thedward** [comment]
The shell interprets `"xyzzy-14"` as a string of 8 characters, beginning with `x` and ending with `4` — this is not a valid JSON string. You need to quote or escape the double quotes, so try either:

    jq 'capture("(?<a>[a-z]+)-(?<n>[0-9]+)")' <<<"\"xyzzy-14\""

or:

    jq 'capture("(?<a>[a-z]+)-(?<n>[0-9]+)")' <<<'"xyzzy-14"'

**Comment by kenorb** [comment]
Thanks. Adding single-quotes around double-quotes seems to work.

```
$ echo '"xyzzy-14"' | jq 'capture("(?<a>[a-z]+)-(?<n>[0-9]+)")'
{
  "a": "xyzzy",
  "n": "14"
}
```
