### ISSUE TITLE
issue accessing keys which contain - (hyphen) in the name

### ISSUE THREAD

**Issue by kunal-pmj** [stedolan/jq#1656]
{
    "1": 4,
    "2": 0,
    "651": 3,
    "kunal-test": 3,
    "abc" : 14
}

Imagine a JSON like this.
Uisng jq ."kunal-test" 

results in following error: 
jq: 1 compile error
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   109  100   109    0     0    243      0 --:--:-- --:--:-- --:--:--   244
(23) Failed writing body

**Comment by pkoppstein** [comment]
1. On a Mac or *ix machine, you would have to enclose the filter as shown in single-quotes; you’d have to perform some gymnastics if using Windows unless you put the filter in a file as explained in the online jq manual: https://stedolan.github.io/jq/manual/

2. The error message you report does not correspond at all with the other details given. In future, please follow the guidelines at https://stackoverflow.com/help/mcve as much as possible.

3. For future reference, please post usage questions at stackoverflow.com using the jq tag: https://stackoverflow.com/questions/tagged/jq

**Comment by pkoppstein** [comment]
As documented in many places, you can always use the fundamental method for accessing the value of a key: `.["KEY"]`

There are alternatives depending on your version of jq, but the fundamental method is supported by all versions.

**Comment by thedward** [comment]
@RedactedCode

When you type:

```sh
jq .["x-access-level"] fragment.json
```

the double quotes are consumed by your shell, so `jq` sees your expression as:

```
.[x-access-level]
```

In order to preserve the double quotes in the string passed to `jq`, try instead:

```sh
jq '.["x-access-level"]' fragment.json
```

**Comment by MaurGi** [comment]
> @RedactedCode
> 
> When you type:
> 
> ```shell
> jq .["x-access-level"] fragment.json
> ```
> 
> the double quotes are consumed by your shell, so `jq` sees your expression as:
> 
> ```
> .[x-access-level]
> ```
> 
> In order to preserve the double quotes in the string passed to `jq`, try instead:
> 
> ```shell
> jq '.["x-access-level"]' fragment.json
> ```

this way does not work with variables expansion :
```
$ echo ${json} |  jq -r -c '.${cloud}.${level}.["apps-owners"]'
jq: error: syntax error, unexpected '$' (Unix shell quoting issues?) at <top-level>, line 1:
.${cloud}.${level}.["apps-owners"] 
```

**Comment by nicowilliams** [comment]
@MaurGi There are command-line options for that, like `--arg varname value` and so on.

**Comment by graphixillusion** [comment]
@nicowilliams i'm having the same issue under Windows. Let's use this simple code:

```
{
  "data": {
    "bookmark-data-key": [
      "bookmark-data-value"
    ]
  }
}
```

This command works good under linux/jqplay website:

`
jq .data."bookmark-data-key"
`
but i can't make it works under Windows 10. I always get errors:

```
jq: error: data/0 is not defined at <top-level>, line 1:
.data.bookmark-data-key
jq: error: key/0 is not defined at <top-level>, line 1:
.data.bookmark-data-key
jq: 2 compile errors

```

I have tried several options:

jq .data."bookmark-data-key"
jq ".data."bookmark-data-key"
jq .data.["bookmark-data-key"]
jq '.data."bookmark-data-key"'

Nothing.

**Comment by itchyny** [comment]
@graphixillusion How about `jq '.data.\"bookmark-data-key\"'` ?

**Comment by pkoppstein** [comment]
At a WIndows command prompt, you cannot use bash-style quoting.

Instead, try:

     jq .data["bookmark-data-key"]

or

       jq ".data[\"bookmark-data-key\"]"

If neither of these works, put the jq commands in a file and invoking jq with the -f option.

**Comment by graphixillusion** [comment]
@itchyny @pkoppstein these two commands works:

```
jq .data.\"bookmark-data-key\"
jq ".data[\"bookmark-data-key\"]"
```

This doesn't:

`jq .data["bookmark-data-key"]`
