### ISSUE TITLE
`--join-output` makes `jq` behave really weird

### ISSUE THREAD

**Issue by doronbehar** [stedolan/jq#1660]
I'm experiencing a very weird behavior when using `jq` with `--join-output`. I wish I could tell whether this problem is present in with the latest git version or in [`1.6rc1`](https://github.com/stedolan/jq/releases/tag/jq-1.6rc1) but I can't due to #1659.

Example:
```
$ curl --silent 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | jq --join-output '.[0] | .commit.message, ":", .commit.committer.name'
```

The output shown in the terminal:
```
Make limit/2 more efficient

```
The output actually printed yet part of it disappears somehow (tested with `xclip`):
```
Make limit/2 more efficient

Contributed by @pkoppstein.:Nicolas Williams
```
Without the `--join-output`:
```
$ curl --silent 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | jq '.[0] | .commit.message, ":", .commit.committer.name'
"Make limit/2 more efficient\n\nContributed by @pkoppstein."
":"
"Nicolas Williams"
```

It doens't feel like a correct behavior to me.

I'm trying to write a script using `jq` that will process private information printed by another program so I'm declined to use it as an example input in this issue report. With this input, I get no output at all.

**Comment by muhmuhten** [comment]
No newline is added at the end of a line with `--join-output`. Based on that and the fact that the output can be captured by xclip, and that you have a fancy prompt setup in your dotfiles, I suspect that your prompt may be erasing or masking the last line of output without a final newline.

If you're still experiencing this, check the output of the following:

```
# the above
curl --silent 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | jq --join-output '.[0] | .commit.message, ":", .commit.committer.name'
```

```
# should display fully
curl --silent 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | jq --join-output '.[0] | .commit.message, ":", .commit.committer.name, "\n"'
```

```
# likely appears to produce no output at all
printf hi, world
```

```
# likely displays only the first line
printf 'line 1\nline 2'
```

**Comment by nicowilliams** [comment]
Right, the problem is that the first output has embedded newlines, and then jq prints the other two without a newline in between -- because that's what `--join-output` does.

What do you really want to see, @doronbehar?  I suspect you misunderstood the purpose of `--join-output`...

**Comment by doronbehar** [comment]
Yea I learned that a few weeks ago as well. ZSH (at least with my setup) doesn't show text which is printed without newline at the end so you are right, this is not a bug.
