### ISSUE TITLE
sub has issues with unicode characters

### ISSUE THREAD

**Issue by Loki-Astari** [stedolan/jq#1661]
The following:

    > echo '"“AFFINITY” ALBARIÑO"' | jq -r '.|sub("^(?<head>.+)";"-\(.head)-")'
    -“AFFINITY” ALBARIÑO-IÑO
                          ^^^    Last three characters should be removed.

The string “AFFINITY” ALBARIÑO has a couple of multi-byte characters

     “   Left Double quote \u201C
     ”   Right Double quote \u201D \u9D

So the matched string is 19 characters (unicode code points long) but 22 bytes long. The match above matches all 19 characters but only replaces 19 bytes. Thus leaving the string "IÑO" not replaced in the original string.

**Comment by pkoppstein** [comment]
1. The good news is that this bug was fixed after the release of jq 1.5.  The bad news is that a version with the bug fix has not yet been officially released.  See https://github.com/stedolan/jq/wiki/Installation for further guidance.

2. There is never any need to begin a pipeline with `.|`
