### ISSUE TITLE
[suggestion] --heredoc flag instead of magic interaction between -Rs

### ISSUE THREAD

**Issue by abcq2** [stedolan/jq#1662]
There are 2 things the `jq` language can't natively achieve:

1.	ignore syntax: all input is parsed as json including quotation marks and string escapes.
2.	wrap multiple inputs: the output of a filter can be wrapped in an array like so: `[filter]`. However, there is no way to get the entire input as one filter.

To work around these gaps in the language, two command line flags are provided:

1.	ignore syntax: the `-R` or `--raw-input` flag treats each line as a string.
2.	wrap multiple inputs: the `-s` or `--slurp` flag treats the entire input as an array.

If you wanted to treat the input as an array of strings, with one string per line, you might have thought something like:

	jq --raw-input --slurp
	
would work, but you would be **WRONG**.

When both of these flags are present, the entire input is treated as one string. This is to say that `--raw-input` no longer treats each line as a string when `--slurp` is present, and `--slurp` no longer treats the input as an array when `--raw-input` is present. **There is no way to access the usual `--slurp` functionality when `--raw-input` is used, and vice versa**, apart from a second invocation of `jq`:

	jq -R . | jq -s $program

Personally, I don't understand why these flags should be mutually exclusive. I would suggest something like

	jq --heredoc

to function like the current special behaviour controlled by `-Rs`, and make `-R` and `-s` function consistently.

**Comment by pkoppstein** [comment]
> If you wanted to treat the input as an array of strings ...

Actually, thanks to `inputs`, this can be done very easily:

```
$ jq -nR '[inputs]' << EOF
abc
def
EOF
[
  "abc",
  "def"
]

```

In the light of the availability of `input` and `inputs`, perhaps you could clarify your critique.

**Comment by abcq2** [comment]
whoops. The problem was with my site install, between the keyboard and the chair

**Comment by abcq2** [comment]
Can I ask, why does `jq -R [inputs]` drop the first line but `jq -nR [inputs]` doesn't?

**Comment by pkoppstein** [comment]
> Can I ask, why does jq -R [inputs] drop the first line

Actually, it's not jq that drops the first line of input in this case, as can be seen if you write: `jq -R [., inputs]`

The somewhat unintuitive behavior can be seen as the result of evolution.  Originally, when jq did not have `input` or `inputs`, it was deemed more user-friendly to read from STDIN by default, etc etc etc.
