### ISSUE TITLE
incorrect parsing

### ISSUE THREAD

**Issue by Scott1** [stedolan/jq#1675]
I'm seeing some cases where large numbers are coming out incorrect, here is an example:

JSON input: {"id":13714540419440739}
command line: jq '.id'
returns: 13714540419440740
expected: 13714540419440739

see:
https://jqplay.org/s/wKC1pFMuak

**Comment by pkoppstein** [comment]
This is a well-known issue.  See e.g. #1652 and the "Caveats" section of the [jq FAQ](https://github.com/stedolan/jq/wiki/FAQ)

**Comment by Scott1** [comment]
Ah ok, thanks for the info @pkoppstein
