### ISSUE TITLE
How can I delete key in object inside of array based on its type?

### ISSUE THREAD

**Issue by fabiogomezdiaz** [stedolan/jq#1677]
I have an array of JSON objects and I need to delete a field based on it's name and it's type. I am trying to do something similar to this, but encountering all kinds of errors.

```bash
jq '.[] |= with_entries(if .key == "_id" and .value | type == "object" then .del(.key) else . end)' file.json;
```

Essentially, I would like to convert this:
```json
[{
	"_id": {
		"$oid": "5aac4cafec9e26b41aefef58"
	},
	"objectId": "7Re9GtLdoF",
	"identifier": "winter",
},
{
	"_id": "5aac4cafec9e26b41aefef59",
	"objectId": "5STazRQKgU",
	"identifier": "grapenut"
}]
```

Into something like this:
```json
[{
	"objectId": "7Re9GtLdoF",
	"identifier": "winter",
},
{
	"_id": "5aac4cafec9e26b41aefef59",
	"objectId": "5STazRQKgU",
	"identifier": "grapenut"
}]
```

Basically I would like to erase field `_id` if its value is an `object`.

Any clues on how I can accomplish this?

I highly appreciate the help in advance.

**Comment by pkoppstein** [comment]
You're very close. This variation of your filter will do the job:

    .[] |= with_entries(if .key == "_id" and (.value | type) == "object" then empty else . end)

Here's a slightly shorter variant:

    map( with_entries(select(.key != "_id" or (.value | type) != "object")))

In future, please ask usage questions at stackoverflow.com with the jq tag: 
tackoverflow.com/questions/tagged/jq

**Comment by joebowbeer** [comment]
close this issue?

**Comment by fabiogomezdiaz** [comment]
Yes please
