### ISSUE TITLE
jq is hanging when trying to extract data from json

### ISSUE THREAD

**Issue by sudhakarcs50** [stedolan/jq#1682]
Hi,

My Json file has following structure

    {
    "group0": [
        {
            "id": 9,
            "href": "href1",
            "name": "Americas",
            "group1": [
                {
                    "id": 8,
                    "href": "href2",
                    "name": "Anguilla (UK)",
                    "type": "country",
                    "field0": "ai",
                    "group2": {
                        "field1": 9,
                        "field2": 1,
                        "field3": 1
                    }
                },
                {
                    "id": 9,
                    "href": "href3",
                    "name": "Antigua and Barbuda",
                    "type": "country",
                    "field0": "ag",
                    "group2": {
                        "field1": 9,
                        "field2": 1,
                        "field3": 2
                    }
                },
                {
                    "id": 10,
                    "href": "href4",
                    "name": "Argentina",
                    "type": "country",
                    "field0": "ar",
                    "group2": {
                        "field1": 8,
                        "field2": 1,
                        "field3": 2
                    },
                    "group3": [
                        {
                            "id": 599,
                            "href": "",
                            "name": "Rosario and Santa Fe (both Santa Fe province)",
                            "field3": 3
                        }
                    ]
                }
                
            ]
        },
        {
            "id": 10,
            "href": "href5",
            "name": "Asia & the Pacific",
            "group1": [
                {
                    "id": 1,
                    "href": "href6",
                    "name": "Afghanistan",
                    "type": "country",
                    "field0": "af",
                    "group2": {
                        "field1": 10,
                        "field2": 3,
                        "field3": 5
                    }
                },
                {
                    "id": 14,
                    "href": "href7",
                    "name": "Australia",
                    "type": "country",
                    "field0": "au",
                    "group2": {
                        "field1": 7,
                        "field2": 1,
                        "field3": 2
                    }
                },
                {
                    "id": 19,
                    "href": "href8",
                    "name": "Bangladesh",
                    "type": "country",
                    "field0": "bd",
                    "group2": {
                        "field1": 9,
                        "field2": 2,
                        "field3": 3
                    },
                    "group3": [
                        {
                            "id": 216,
                            "href": "",
                            "name": "Chittagong Hill Tracts; Dhaka",
                            "field3": 4
                        }
                    ]
                }
                
            ]
        }  
    ]
}

i want to extract the fileds group1.field0, group1.name,group2.field1, group1.field3

the command i am running is below

    jq '.group0[].group1[]|"\(.name)|\(.field0)|\(.group2.field1)|\(.group2.field3)"' sample.json

when i run the above command in Solaris it just hangs and does nothing. when i run the above command with only 2 fields i am getting data 

    jq '.group0[].group1[]|"\(.name)|\(.field0)"' sample.json

can someone please help me what am i doing wrong. the first command is working on jqplay.org which uses jq version 1.5 and jq version on our server is 1.4. i don't know whether lower version may be the issue(latest version for Solaris is 1.4 only).

**Comment by pkoppstein** [comment]
Using jq 1.5:

```
jq '.group0[].group1[]|"\(.name)|\(.field0)|\(.group2.field1)|\(.group2.field3)"' sample.json
"Anguilla (UK)|ai|9|1"
"Antigua and Barbuda|ag|9|2"
"Argentina|ar|8|2"
"Afghanistan|af|10|5"
"Australia|au|7|2"
"Bangladesh|bd|9|3"
```

**Comment by sudhakarcs50** [comment]
the same commands are working on jq 1.4 and 1.5 for Windows. i don't know whether this is issue with Solaris jq 1.4

**Comment by pkoppstein** [comment]
@sudhakarcs50 - I'm afraid I won't be able to help other than to suggest that you try to upgrade your version of jq on Solaris.  jq 1.4 is very old.

Installing the "master" version of jq would probably be no more difficult than installing jq 1.5 so if I were in your shoes, I'd start with the "master" version.

**Comment by sudhakarcs50** [comment]
@pkoppstein, it seems JQ 1.5 for Solaris was not released and our admin team had issues with compiling from the source tar ball

**Comment by pkoppstein** [comment]
@sudhakarcs50 - One does not need admin permissions to install jq.
