### ISSUE TITLE
how to get value of element "$"?

### ISSUE THREAD

**Issue by knutov** [stedolan/jq#1683]
json example:

```
{
  "$": "some string"
}
```

I want to get "some string" from `jq`. How to do it?

```
echo '{ "$": "some string" }' | jq  -r '$'
```
in all ways of quoting `$` is not working.

Workaround with `sed` working fine:
```
echo '{ "$": "some string" }' | sed 's/\$/self/g' | jq  -r '.self'
```

**Comment by leonid-s-usov** [comment]
This worked for me 
`echo '{ "$": "some string" }' | jq -r '."$"'`

**Comment by knutov** [comment]
```
$ echo '{ "$": "some string" }' | jq -r '."$"'
error: syntax error, unexpected QQSTRING_START, expecting $end
."$"
 ^
1 compile error
```

Ubuntu 16.04 LTS
```
$ aptitude show jq |  grep -i version
Version: 1.3-1.1ubuntu1
```

**Comment by leonid-s-usov** [comment]
i'm on Mac, 
```
$> jq --version
jq-1.5
```

try updating your JQ

**Comment by pkoppstein** [comment]
Whichever version of jq you are using, you can always use the fundamental syntax:

    .["$”]

**Comment by knutov** [comment]
@pkoppstein 

are you sure?

```
curl ... | jq  -r '.doc.elem[0].id.["$"]'
error: syntax error, unexpected '[', expecting IDENT
.doc.elem[0].id.["$"]
                ^
1 compile error
```

**Comment by pkoppstein** [comment]
@knutov wrote:
> are you sure?

Yes. The problem with your example is that you're missing some pipes ("|").  You can only leave out the pipes under very restricted circumstances.

**Comment by knutov** [comment]
sorry, do not understang you. 

```
# this works:
echo '{ "$": "some string" }' | jq -r '.["$"]'

# but not this:
echo '{ "doc":{ "elem":[ { "id":{ "$":"123" } } ] } }' | jq  -r '.doc.elem[0].id.["$"]'
error: syntax error, unexpected '[', expecting IDENT
.doc.elem[0].id.["$"]
                ^
1 compile error
```

which pipe I am missing?

**Comment by pkoppstein** [comment]
If in doubt, simply start with the unabbreviated filter.  In the present case, that would be: 

    .doc | .elem[0] | .id | .["$"]

**Comment by knutov** [comment]
Thanks, it works.

But.. `echo ... | sed 's/\$/self/g' |jq  -r '.doc.elem[0].id.self'` works without pipes, why? Why using $ makes it so different?

**Comment by knutov** [comment]
`jq  -r ' .doc.elem[0].id | .["$"] '` also works, what does pipe do exactly in this case?

**Comment by leonid-s-usov** [comment]
This is exactly the case of #1699
Just remove the `.` before `["$"]`:

    $ echo '{ "doc":{ "elem":[ { "id":{ "$":"123" } } ] } }' | jq  -r '.doc.elem[0].id["$"]'
    123

**Comment by knutov** [comment]
@leonid-s-usov thanks!

**Comment by leonid-s-usov** [comment]
The confusion here is that the dot in front of the brackets in the expression ` ... | .["..."]` is different than the dots in the expression `a.b.c.d`. 
In the former case the dot represents the input itself, so it is "indexable" by the `["..."]` syntax. 
In the latter case the dot is a separator, part of a syntactic sugar grammar, which treats the right side of it as a shorthand syntax for indexing the left side of it. Hence, `a.b.c.[]` doesn't make sense cause it's _kind of_ equivalent of `a.b.c["[]"]`

**Comment by knutov** [comment]
yes, I understand now, but as with #1699 case `a.b.c.[]` looks much better to me then `a.b.c["[]"]`, so it make sense.

`.doc.elem.[0]` does not look logical to me, as it is array inside `elem` ( like `[ {...}, {...} ]` in json ). But single element named dollar is not array in my case and I'd rather expect `."$"` which is working in newer versions.

**Comment by leonid-s-usov** [comment]
Well, it's just some rationale behind the basic `["x"]` syntax. Just like in PHP, arrays and maps are kind of the same, the only difference is that arrays are indexed by integer keys, and object are indexed by string keys. So,

    elem[0]

is very much similar to 

    id["$"]

in terms that `elem` can be thought as

    elem: {
        0: { "id": { "$": "123" } }
    }
