### ISSUE TITLE
jq should not sort object keys by default

### ISSUE THREAD

**Issue by gcatlin** [stedolan/jq#169]
`echo '{"a":1, "b":2, "c":3, "d":4}' | jq '.'` produces the following output:

```
{
  "d": 4,
  "c": 3,
  "b": 2,
  "a": 1
}
```

Observed behavior: keys were sorted in reverse order

Expected behavior: keys should be in the original order

**Comment by childnode** [comment]
unfortunately I can't see what https://github.com/stedolan/jq/commit/91cfc34ae40e2be359a6a09e956d84abf63f8448 changed ... behavior is still the same for me on jq-1.5-1-a5b5cbe

```json
{
  "d": {
  },
  "z": {
  },
  "b": {
  }
}
```

becomes 
```json
[
  "b",
  "d",
  "z"
]
```

**Comment by pkoppstein** [comment]
> Update sorry, just saw #1109 (comment)

Yes, 91cfc34 was just the first step.  Also note that it was not until 4a57b84 (30 Sept 2014) that `to_entries` respected the key ordering, and not until 7b81a83 (19 June 2017) that `walk` did so.
