### ISSUE TITLE
Unexpected output on large array slices

### ISSUE THREAD

**Issue by karimjp** [stedolan/jq#1690]
Attempting to obtain a subarray for range 75,000 to 75,002 yields and incorrect result. However, it works for a lower range. See examples below:

Using python 2.7 in a terminal,

Bad result:
python -c 'print range(80000)' | jq '.[75000:75002]'
[
  9464,
  9465
]

Good result: 
python -c 'print range(80000)' | jq '.[65000:65002]'
[
  65000,
  65001
]

jq --version
jq-1.5

**Comment by erip** [comment]
It looks like slices fail at `2**16-1`, so it looks like slices are of type `uint16_t` (or whatever equivalent type my compiler decides).

```sh
~ ⌚ 10:48:55
$ python3 -c "print(list(range(80000)))" | jq ".[65535:65538]"
[
  65535,
  65536,
  65537
]

~ ⌚ 10:49:04
$ python3 -c "print(list(range(80000)))" | jq ".[65536:65539]"
[
  0,
  1,
  2
]
```

**Comment by erip** [comment]
Could `jvp_array_slice` accept `long start` and `long end` instead?

**Comment by pkoppstein** [comment]
@erip - This problem was fixed some time ago, but unfortunately as you have found, that was after the release of jq 1.5.  So the (hopefully for you) simple solution is to upgrade jq to a more recent version :-)

See e.g. https://github.com/stedolan/jq/wiki/Installation

**Comment by erip** [comment]
@pkoppstein Is there a different repo somewhere? It looks like [it hasn't been fixed on github](https://github.com/stedolan/jq/blob/9df19f53e44e97d59688a9f3d3736ff0f9cd0222/src/jv.c#L288). I'm using the most recent jq for OS X -- not sure about @karimjp.

**Comment by pkoppstein** [comment]
@erip - I believe the fix was 65cbaac34498a75973e26799dc03dd81bd27e5ad of Mar 1, 2017.

**Comment by erip** [comment]
Oh, an interesting solution! Thanks, @pkoppstein. The issue was that I needed to _upgrade_ my jq, not install. heh, silly me. `brew upgrade --HEAD jq` fixed it.

**Comment by pkoppstein** [comment]
@erip - Would you happen to know how python users of https://pypi.org/project/jq/ (as in "pip install jq") can install a later version of jq.so so they aren't tied to jq 1.5?

**Comment by erip** [comment]
@pkoppstein - Not offhand, no. Brute force is just to rebuild from source.

**Comment by pkoppstein** [comment]
@erip - On a Mac, rebuilding from source does not create the required jq.so
