### ISSUE TITLE
Support of hexademical literals

### ISSUE THREAD

**Issue by cono** [stedolan/jq#1693]
Following example should work and shouldn't generate any errors:
```
# echo '{"hello":0x000000}' | jq
parse error: Invalid numeric literal at line 1, column 18
```

**Comment by pkoppstein** [comment]
Sorry, but that's not JSON.  And of course the "j" in "jq" stands for JSON.

In general, one can use the \u notation, e.g.

    $ jq . <<<'{"hello": "\u0000"}'
```
{
  "hello": "\u0000"
}
 
```
