### ISSUE TITLE
Keys with "-" are not supported in json objects

### ISSUE THREAD

**Issue by JavaPentesters** [stedolan/jq#1694]
`
{"service": {
                "xqy-finance": {
                        "appType": "service",
                }
        }
}
`

Imagine a JSON like this.
Uisng jq  ."service.xqy-finace"   service.json 

The error result is showed as follows:
**jq: error: finance/0 is not defined at <top-level>, line 1:
.service.xqy-finance             
jq: 1 compile error**

**Comment by pkoppstein** [comment]
This topic is covered in the manual, the jq FAQ (
https://github.com/stedolan/jq/wiki/FAQ), this website, stackoverflow.com, and elsewhere.

In this particular case, the filter could be written in the fundamental form:

    .service | .["xqy-finance"]

but other variants are possible, depending on the version of jq being used.
