### ISSUE TITLE
Bug in regex replacement when operating on files/strings with multibyte UTF-8 sequences

### ISSUE THREAD

**Issue by danfuzz** [stedolan/jq#1696]
Found on `jq` version 1.5, as installed by Homebrew on macOS.

When earlier lines have multibyte UTF-8 sequences, regex replacement can end up touching the wrong part of the input, when running with the `--slurp` option. Here's an example transcript:

```
$ cat > florp.txt
😀
😀
😀
😀
😀
😀
😀
😀
01234567890123456789/ABCDEF/01234567890123456789
^D
$ jq --raw-input --raw-output --slurp '. | gsub("ABCDEF"; "XabcdefgX")' < florp.txt 
😀
😀
😀
😀
😀
😀
😀
😀
01234567890123456XabcdefgXCDEF/01234567890123456789
```

That last line should instead read:

```
01234567890123456789/XabcdefgX/01234567890123456789
```

Without the `--slurp` option, this is in fact correctly produced. However, if the UTF-8 characters occur on the same line as the replacement, there's still a problem even without `--slurp`:

```
$ cat > florp.txt
😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀 01234567890/ABCDEF/01234567890
$ jq --raw-input --raw-output '. | gsub("ABCDEF"; "XabcdefgX")' < florp.txt
😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀 01234567890XabcdefgXF/01234567890
```

**Comment by pkoppstein** [comment]
This bug (which does exist in jq 1.5) was fixed long ago.

**Comment by danfuzz** [comment]
Sorry, I looked through the issues and didn't spot it.
