### ISSUE TITLE
Variables bound globally aren't visible at function scope

### ISSUE THREAD

**Issue by davidfetter** [stedolan/jq#1698]
```def f: $a; 1 as $a | f```
yields an unexpected error.

**Comment by pkoppstein** [comment]
This is a feature, not a bug.  The problem is with the expectation.

Incidentally, $a in the example is not global. The only global variables in jq are those defined with command-line options such as —arg or —argjson.

**Comment by naim42** [comment]
I'm not sure I understand this.

`$a` isn't global, but I would at least expect the function's scope to inherit bindings from the filter it's in, so as to make `$a` available in the function. Why isn't this the case? I assume arguments are to be used instead?

**Comment by rfc6919** [comment]
This is the documented behaviour - jq functions are closures, and capture their scope at definition.
https://github.com/stedolan/jq/wiki/Advanced-Topics#closures

**Comment by pkoppstein** [comment]
Apart from global variables, jq's scoping rules are lexical.

Thus, with f defined as $a, f can only be evaluated as $a if $a is "visible" to f. This can be achieved either by defining $a using one of the command-line options such as —arg or —argjson, or as illustrated by this example:

    jq -n '2 as $a | def f: $a; f'

Note also that lexical scoping works with sub-functions as well; thus:

    def f($a): def g: $a; g; f(1)

yields:

    1

**Comment by naim42** [comment]
I see, thanks.
