### ISSUE TITLE
select array by any element exactly matched to specified value

### ISSUE THREAD

**Issue by jjqq2013** [stedolan/jq#1707]
Anyone know to how to implement this?

I have an array which has a nested array, say tagNames, I want to select all item which tagNames contains "auto-test" exactly, not "auto-test2". 
```
{
  "servers":[
      {"id":1, "tagNames": ["auto-test",  "xxx"]},
      {"id":2, "tagNames": ["auto-test2", "xxxx"]}
  ]}
```

So far, I am using
```
echo '{"servers":[{"id":1,"tagNames":["auto-test","xxx"]},{"id":2,"tagNames":["auto-test2","xxxx"]}]}' |\
jq  '[ .servers[] | select(.tagNames | contains(["auto-test"])) ]'
```

I got two records, but I just want the first one.
```
[
  {
    "id": 1,
    "tagNames": [
      "auto-test",
      "xxx"
    ]
  },
  {
    "id": 2,
    "tagNames": [
      "auto-test2",
      "xxxx"
    ]
  }
]
```

So I want this:
```
[
  {
    "id": 1,
    "tagNames": [
      "auto-test",
      "xxx"
    ]
  }
```

Any idea?

**Comment by pkoppstein** [comment]
One way would be to use `index/1`, e.g.

```
.servers[]
| select( .tagNames | index("auto-test"))
```

This produces:

    {"id":1,"tagNames":["auto-test","xxx"]}

If you want that wrapped in an array, you could (for example) wrap the filter above in square brackets.

For future reference, please ask usage questions at stackoverflow.com with the jq tag:

https://stackoverflow.com/questions/tagged/jq

**Comment by jjqq2013** [comment]
thank you so much.
