### ISSUE TITLE
Using multiple select() ?

### ISSUE THREAD

**Issue by FransUrbo** [stedolan/jq#1710]
I'm trying to delete old snapshots in ElasticSearch. I'd like to only keep the last ten successful snapshots and delete all the others, including all the unsuccessful ones.

This is my current command line:

```
(curl -s "http://localhost:9200/_snapshot/${FQDN}/_all" | \
        jq -r '[.snapshots[] | select(.state == "SUCCESS")][-10] | .snapshot' ; \
    curl -s "http://localhost:9200/_snapshot/${FQDN}/_all" | \
        jq -r '.snapshots[] | select(.state != "SUCCESS") | .snapshot')
```

This works fine, but is there anyway I can optimise this to be done in ONE query?

**Comment by nhtzr** [comment]
Hi, I'm not sure about ES api. But for something similar to the snippet, I would use [variables](https://stedolan.github.io/jq/manual/v1.5/#Variables) like:

```
.snapshots as $snapshots |
  ($snapshots | map(select(.state == "SUCCESS"))[-10:]) as $success |
  ($snapshots | map(select(.state != "SUCCESS"))) as $failure |
  $success[].snapshot, $failure[].snapshot
```

I believe that should output the first ten successful snapshots, followed by all other not successful ones.

Consider checking out [the jq tag in stackoverflow](https://stackoverflow.com/questions/tagged/jq) for usage questions in case that was not the response you were looking for.

**Comment by FransUrbo** [comment]
That indeed seem to work! My many, many thanx!!
