### ISSUE TITLE
Weird behaviour on large file streams

### ISSUE THREAD

**Issue by ericescalante** [stedolan/jq#1723]
Hi! Noticed a strange pattern and was wondering if this is a known issue (or what is that I'm most likely doing wrong 😅)

Given a massive JSON file that contains an array of people and their favourite things like so:

```
{
"people": [
{
 "id": "a",
 "name: "b",
 ...
 "favourites": [
    {"page": "a"},
    ...
    {"page": "z"},
 ],
 ...
 "country": "y",
 "city": "z"
},
...]
}
```

When trying to extract just a couple of fields from people from a given country via a stream using a function like:

```
foreach inputs as $in (null;
  if 
    has("id") 
    and has("country") 
    and has("city") 
  then null
  else . as $x
  | $in
  | if length != 2 then null
    elif .[0][-1] == "id" then ($x + {id: .[-1]})
    elif .[0][-1] == "country" and .[-1] == "US" then  ($x + {country: .[-1]})
    elif .[0][-1] == "city" then ($x + {city: .[-1]})
    else $x
    end
  end;
  select(
    has("id") 
    and has("country")
    and has("city")
    ) | . )
```

Jq hangs if the fields we want to extract are on both sides of the 'favourites' sub-array. 
For example, getting `id` and `name` work fine, getting `country` and `city` work fine, but getting `id` together with `country` causes jq to just hang.

The invocation is performed with `jq -nc --stream -f function.jq people.json`

Any ideas heartily welcomed!

**Comment by pkoppstein** [comment]
Your brave attempt is thwarted by the occurrence of:

[["people",0,"favourites",0,"page"]]

in the stream of arrays.

I would suggest you try to rectify your program to take into account that a simple check using `length==2` is insufficient here; then, if you still need further assistance, post your question at stackoverflow.com with the `jq` tag.  This will probably be to everyone's benefit.

**Comment by ericescalante** [comment]
Thanks @pkoppstein, that's a very good hint. I'll follow that, much appreciated! :)
