### ISSUE TITLE
method select(): command not found

### ISSUE THREAD

**Issue by zxlc** [stedolan/jq#1727]
I used the jq built-in method "select" to parse the json string in shell script, and got an error that the command not found.

Here is my shell script: test.sh
```
#!/bin/bash

function test(){

  json='[{"id":1,"name":"jdjson"},{"id":2,"name":"imagetookit"}]'

  detail=`echo $json | jq .[]|select\(.id==2\)`
}

test
```

I just ran the script on the command line and got the following error:
```
$ bash test.sh
test.sh:行5: select(.id==2): 未找到命令  
```

"未找到命令" means "command not found"

the "select" is built-in method of jq command, and I don't know why

Does the function need to be imported?  How to import method of jq?

**Comment by pkoppstein** [comment]
Either use the -f command-line option, or quote the jq program properly.

Since this question has been asked and answererd at 
https://stackoverflow.com/questions/52537826/jq-built-in-method-select-command-not-found,
please do not forget to “close” this issue. 谢谢

**Comment by zxlc** [comment]
thanks

**Comment by zxlc** [comment]
> Either use the -f command-line option, or quote the jq program properly.
> 
> Since this question has been asked and answererd at
> https://stackoverflow.com/questions/52537826/jq-built-in-method-select-command-not-found,
> please do not forget to “close” this issue. 谢谢
thank you

**Comment by zxlc** [comment]
> Either use the -f command-line option, or quote the jq program properly.
> 
> Since this question has been asked and answererd at
> https://stackoverflow.com/questions/52537826/jq-built-in-method-select-command-not-found,
> please do not forget to “close” this issue. 谢谢

thank you
