### ISSUE TITLE
Square-bracket syntax for quoted object properties doesn't work with variables

### ISSUE THREAD

**Issue by benchristel** [stedolan/jq#1737]
**Describe the bug**

In jq-1.5, square-bracket object property access produces a syntax error when the object is referenced via a variable.

**To Reproduce**

The following produces a syntax error:

```bash
echo '{"hi": 1}' | jq '. as $root | $root.["hi"]'
```

```
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
. as $root | $root.["hi"]
jq: 1 compile error
```

But it works if you omit the square brackets:

```bash
echo '{"hi": 1}' | jq '. as $root | $root."hi"'
1
```

**Expected behavior**

Using square brackets to access object properties should work the same as just using quotes.

**Environment (please complete the following information):**
 - OS and Version: macOS 10.11.6
 - jq version: 1.5

Thanks for making jq :)

**Comment by pkoppstein** [comment]
It's not a bug.  The "." following `$root` should be omitted:

    $ echo '{"hi": 1}' | jq '. as $root | $root["hi"]'
    1

**Comment by benchristel** [comment]
Ok, thanks!
