### ISSUE TITLE
v1.5 - win64 - file names longer than 35 characters crash the program

### ISSUE THREAD

**Issue by jimbowatusi** [stedolan/jq#1742]
File names longer than 35 characters are crashing the program.  When I rename the file to a smaller amount of characters, it works as it should.

This works fine:
`jq-win64 . 1234567890123456789012345678901.j`

This does not:
`jq-win64 . 1234567890123456789012345678901.json`

I'm running Windows 10 version 1607 (build 14393.2551) with JQ version 1.5.

![jq-crash](https://user-images.githubusercontent.com/4571418/47215822-c6ce3200-d370-11e8-9355-c548973acf79.png)

**Comment by jcracknell** [comment]
Try using a more recent build of JQ:
https://github.com/stedolan/jq/issues/1205

**Comment by jimbowatusi** [comment]
I thought I had the latest based upon the stedolan/jq/releases folder.  Thanks for the responses.
