### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by ferenczy** [stedolan/jq#1745]
It has been more than 3 years since the latest release. What's the plan for the next release, please? I noticed a release of the version 1.6 was discussed in February 2017 and it still didn't happen.

It would be better to release more frequently and with much less new features in a single release. When I saw the project homepage with news from 2015 the first time, I thought this is a dead project. Only after some deeper digging I noticed it's pretty alive, so I wonder what's happening with the releases?

Anyway, it's really awesome tool!

**Comment by wtlangford** [comment]
I'm currently finishing up a couple of administrative prep tasks and you'll
see 1.6 released in the next couple of days.
