### ISSUE TITLE
jq hangs when including a file whose rooted path is longer than 56 characters

### ISSUE THREAD

**Issue by tlagrone** [stedolan/jq#1747]
**Description**
Attempting to run jq with a query that includes a header file whose rooted file path is equal to or longer than 56 characters causes jq to hang and the following dialog box to appear:

![image](https://user-images.githubusercontent.com/38440573/47441039-fa47fc80-d774-11e8-9b0b-d780a61784f3.png)

The length of the header file name is significant.  The length of the drive/qualifier name is not significant.

**To Reproduce**
```PowerShell
New-Item 'C:\a\b\c\d\e\f\g\h\i\j\k\l\m\n\o\p\q\r\s\t\u\v\w\x' -ItemType 'Directory' -Force
Set-Location 'C:\a\b\c\d\e\f\g\h\i\j\k\l\m\n\o\p\q\r\s\t\u\v\w\x'
'def f: . ;' | Out-File 'header.jq' -Encoding 'ascii'
jq 'include \"header\";' --null-input
```

**Expected Behavior**
jq includes the specified file and executes the rest of the given query without hanging.  In the above example, that would result in the output of `null`.

**Environment**
- Microsoft Windows 10 Pro
- PowerShell 5.1
- jq 1.5

**Comment by jcracknell** [comment]
Try using a more recent build of JQ:
https://github.com/stedolan/jq/issues/1205
