### ISSUE TITLE
The tag '1.6rc2' does not match expected "jq-*" format in scripts/version

### ISSUE THREAD

**Issue by mojoTX** [stedolan/jq#1750]
**Describe the bug**
Building JQ from Git source shows the version as `jq-1.6rc1-17-g0c845aa-dirty`, instead of some variant of `jq-1.6rc2-*`. Digging into the details, it appears that the file [scripts/version](https://github.com/stedolan/jq/blob/master/scripts/version) expects the tag to start with `jq-`.

**To Reproduce**

1. Clone the repository.
1. Run `git tag --list --sort authordate` and note the list of tags. You can confirm that the one at the bottom is the most recent with the `git log` command, e.g., `git log 1.6rc2`
1. Build the project.
1. Run `./jq --version`, and note that it doesn't match most recent tag. 

Another method is:

1. Clone the project.
1. Run `git tag --list --sort authordate` and get the most recent tag. 
1. Check it out with `git checkout <tag>`, e.g., `git checkout 1.6rc2`
1. Now run `git describe --tags --match 'jq-*'`, which is what is used by the script that updates `version.h`. You will probably see `jq-1.6rc1-14-g46d1ce2`, instead of `1.6rc2`. 

**Expected behavior**

The version in `version.h` should match the most recent tag. 

**Environment (please complete the following information):**
OS is irrelevant, but I did my building on a Mac. I'm working off the tip of the master branch, currently commit 0c845aa.

**Additional context**

The tag should either be corrected to match `jq-1.6rc2`, or else the `scripts/version` code should be changed, specifically the "git describe" on line 5, to remove the "--match" clause. 

If it were me, I would just create a new tag, `jq-1.6rc3`, and just be aware that going forward, the tag naming convention is important.  🙂

Also, given the extremely slow pace of JQ development, I would suggest that the project adopt [Semantic Versioning 2.0,](semver.org) and make these new patch releases, e.g., `jq-1.6.0`, `jq-1.6.1`, etc. I would also suggest using annotated tags, since the last annotated tag was 1.3. 

The 1.6rc1 tag was created in December 2017, and 1.6rc2 tag was created in August 2018. Other than just letting the code "soak," is there any reason why the bug fixes couldn't be considered new releases?

**Comment by mojoTX** [comment]
@wtlangford

**Comment by wtlangford** [comment]
> If it were me, I would just create a new tag, `jq-1.6rc3`, and just be aware that going forward, the tag naming convention is important. 🙂

Yeah, I'd just noticed and learned this myself a day or two ago.

> Also, given the extremely slow pace of JQ development ...
> The 1.6rc1 tag was created in December 2017, and 1.6rc2 tag was created in August 2018.

Yeah, I feel pretty bad about the way the timing of this release worked out, but work/general life stuff kept getting in the way. I'm currently doing the final administrative tasks for formally releasing 1.6 (docsite updates, release note crafting, prepping for release signing). Which sets me for... probably this Saturday.

> Other than just letting the code "soak," is there any reason why the bug fixes couldn't be considered new releases?

Primarily, I think we just like letting the code "soak" for a bit. Breaking behavior in a tool like this is often subtle and painful, and I know lots of places that use `jq` in their internal pipelines/tooling. While you should generally version pin your dependencies, we like to be methodical about these releases.
That said, 3 years is _far too long_. My goal is a more regular release cycle after 1.6, with smaller releases (1.6.1, etc...) as we feel we've reached an appropriate point.

> Also, given the extremely slow pace of JQ development, I would suggest that the project adopt Semantic Versioning 2.0

I generally quite like semver, but I don't think it's always the right scheme. We do have an internal logic to the versioning scheme: 2.0 is saved for some kind of major overhaul, 1.7 would be our next normal release, 1.6.1 for any smaller fixes we deem need a tagged release (major crashes, 1 == 0 is true, etc)
