### ISSUE TITLE
jq-1.6 tarball does not include oniguruma

### ISSUE THREAD

**Issue by GPHemsley** [stedolan/jq#1756]
GitHub does not include submodules in its automatically generated tarballs, so there is no "built-in" oniguruma when compiling from the packaged source.

**Comment by wtlangford** [comment]
In the list of artifacts attached to the build are versions of the tarballs with the oniguruma submodule included (https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.tar.gz, https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.zip).
You'll have to use those, and unfortunately there's really nothing I can do about the auto-generated tarballs.

**Comment by Juppit** [comment]
You should clone the project recursive to include the oniguruma submodule:
`git clone --recursive https://github.com/stedolan/jq.git`
This should be stated on the download [page](https://stedolan.github.io/jq/download/).
