### ISSUE TITLE
Inconsistent behavior from jq - don't know how to isolate

### ISSUE THREAD

**Issue by rdm** [stedolan/jq#1762]
**Describe the bug**
I have a bug in my jq code (which I report to myself using jq's error() statement). But when I start trying to isolate the problem the error report changes.

CAUTION: This is *not* a "jq bug" (in the sense of a hard error) this is "jq inconsistent behavior".  Specifically, when processing what should be the same string, in one case I get

    jq: error (at <stdin>:1): expected ';' at position 2546 got '}'

but in a different case (reading the string directly from file rather than creating it using gsub()), I get

    jq: error (at <stdin>:1): expected ';' at position 1082 got ''

(and a string of other error() reports.

I am not expecting that bugs in my jq code be solved here. I just want some hints about how I can isolate the problem. (That said, I am suspecting a jq bug at the root of this inconsistency, which is why I am reporting it here. And, if I am right about that [sadly, I often am wrong], it would be good if that issue could be resolved within jq.)

**To Reproduce**
Create the file named ***z*** from the gist https://gist.github.com/rdm/8fd4bcfbbc69ae1ee2f555df69b4f3a9 

(This file should be 3588 characters long and shasum should report 69bc5689218d617c9cc47d4bc6f65afd9c4533c8 -- in other words, it should have no newlines at the end of the file).

Create the file named ***wp/wp.jq*** from the gist https://gist.github.com/rdm/5a9e65851e4b7863dd71bd3c5c2f6f69

Run this command:

    jq -Rr 'include "wp"; gsub("\\\\r";"\r")|gsub("\\\\n";"\n")|fromwp' <z

Then run these commands:

    jq -Rr 'include "wp"; gsub("\\\\r";"\r")|gsub("\\\\n";"\n")' <z  >x
    jq -Rr 'include "wp"; fromwp' <x

I am thinking that these should produce the same error report. (And, just in case: I am expecting the file ***x*** to have an shasum of ac676a24f158f1afe4d84553980b2cfcea89d7fe)

I am getting different error reports from jq which suggests that the string I read from file is different from the string produced by gsub()|gsub()

**Expected behavior**
I am expecting the same error report from both cases.

**Environment (please complete the following information):**
- os version: Linux Ubuntu 16.04.4 LTS
 - jq version: jq-1.6-1-g2f2d05b-dirty

**Additional context**
I have some minimal description of that wp.jq implementation posted at http://r-nd-m.blogspot.com/2018/02/jq-serialize-for-wordpress.html - I should probably update that at some point, but it at least hints at my use case.

**Comment by wtlangford** [comment]
So your problem is actually based on your use of `-Rr`.
Your gsubs on the first line unescape newline and carriage return characters. If you print the resulting strings as raw output, those newlines will cause strings to split across two lines, and then be interpreted as two separate inputs by the next run of `jq`.

This version gives the same output as your single command:
```
jq -R 'include "wp"; gsub("\\\\r";"\r")|gsub("\\\\n";"\n")' <z  >x
jq -r 'include "wp"; fromwp' <x
```
