### ISSUE TITLE
jq -ar reports malloc error

### ISSUE THREAD

**Issue by itchyny** [stedolan/jq#1763]
**Describe the bug**
jq 1.6 using -a and -r flag reports a malloc error, which I believe should not occur.

**To Reproduce**
```
 $ echo '{"foo":[{"name":"bar"},{"name":"baz"}]}' | jq -ar ".foo[].name"
"bar"
jq(71775,0x7fffa1105380) malloc: *** error for object 0x7fd5fee00c30: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
zsh: done       echo '{"foo":[{"name":"bar"},{"name":"baz"}]}' |
zsh: abort      jq -ar ".foo[].name"
```

**Expected behavior**
No malloc error.

**Environment (please complete the following information):**
 - OS and Version:  macOS
 - jq version: 1.6

```
 $ jq -V
jq-1.6
 $ shasum `which jq`
cd805c2856b38b8040547de9675cd33ab1713c92  /usr/local/bin/jq
```

**Additional context**
With jq 1.5 the malloc error does not happen.

**Comment by pkoppstein** [comment]
I believe the problem was introduced in ae11f111a5d18604c7001e48c3d6e4a5e73fed64

Using the immediately preceding version:

$ ./jq --version
jq-1.6rc1-7-gae11f11-dirty

```
$ echo '{"foo":[{"name":"bar"},{"name":"baz"}]}' | ./jq -ar ".foo[].name"
bar
baz


```

**Comment by leonid-s-usov** [comment]
> I believe the problem was introduced in ae11f11
that commit looks like a documentation typo fix. Are you sure it's related?

**Comment by pkoppstein** [comment]
@leonid-s-usov -  You're right - I made an off-by-one error and have fixed the SHA-1.

**Comment by leonid-s-usov** [comment]
Cool, this makes it trivial to fix the issue - added a comment there on the line

**Comment by wtlangford** [comment]
I pushed a1f1231a73c221155d539a281181ef37f874869d to master which fixes this. For now, if you can build off of master, you'll get the fix.

**Comment by itchyny** [comment]
Great, thank you!
