### ISSUE TITLE
Need advice. The best way to convert an array of object to folder of single object files with a name based on a value inside the object

### ISSUE THREAD

**Issue by andreapernici** [stedolan/jq#1769]
I'm starting from jq + awk and I'd like to convert an array of object to a series of files 

`jq -c  .[] /_data/sponsors.json | awk '{print > "doc00" NR ".json";}'`

Now what I'd like to do is to save the filename to 

"sponsor_uri_segment": "slug-title" that is a value inside the object.

Is there a fast way to do that or I need to nest different jq calls?

This is my json

```
[
	{
		"sponsor_id":"1",
		"sponsor_image":"\/data\/sponsor\/test1.png",
		"sponsor_uri_segment":"test",
	},
	{
		"sponsor_id":"2",
		"sponsor_image":"\/data\/sponsor\/test-ciao.png",
		"sponsor_uri_segment":"test-ciao",
	}
]
```

and I'd like to split and save to:

- test.json
- test-ciao.json

instead of "doc001", "doc002" etc.

**Comment by pkoppstein** [comment]
This should do the trick:

```
jq -cr '.[] | .sponsor_uri_segment, .' /_data/sponsors.json  | awk '
  fn {print $0 > fn ".json"; fn=""; next;}
  {fn=$0} '
```
In future, it would be beneficial for many people, most likely including yourself, if you could ask usage questions at stackoverflow.com/questions/tagged/jq . Thanks.

**Comment by andreapernici** [comment]
Thanks. Will use SF the next time.
