### ISSUE TITLE
^ not matching start of line

### ISSUE THREAD

**Issue by mickdaly** [stedolan/jq#1776]
**Describe the bug**
`^` does not work with regular expression

**To Reproduce**
```
>echo "test" | jq "match(\"^(e)\")"
{
  "offset": 1,
  "length": 1,
  "string": "e",
  "captures": [
    {
      "offset": 1,
      "length": 1,
      "string": "e",
      "name": null
    }
  ]
}
```

```
> echo "test" | jq "match(\"(^e)\"; \"s\")"
{
  "offset": 1,
  "length": 1,
  "string": "e",
  "captures": [
    {
      "offset": 1,
      "length": 1,
      "string": "e",
      "name": null
    }
  ]
}
```
**Expected behavior**
No results returned, same as
```
>echo "test" | jq "match(\"(e)$\")"

``

**Environment (please complete the following information):**
 - Windows 10
 - jq version 1.6

**Comment by pkoppstein** [comment]
The problem you have identified, I believe, has nothing to do with jq, but reflects instead the fact that the caret has special significance on the Windows command-line (cmd).

 To verify it is not a jq issue, put the filter in a file and invoke jq with the -f option.

I suspect that the issue can be resolved by doubling the caret, so to speak.

**Comment by nicowilliams** [comment]
@pkoppstein is almost certainly correct.

**Comment by mickdaly** [comment]
Confirming that @pkoppstein is correct.
