### ISSUE TITLE
oniguruma

### ISSUE THREAD

**Issue by kiwina** [stedolan/jq#1778]
Build from release tar ball fails
`
./configure --with-oniguruma=builtin --disable-maintainer-mode
make
`
`
=== configuring in modules/oniguruma (/root/jq-1.6/modules/oniguruma)
configure: WARNING: no configuration information is in modules/oniguruma
root@ubuntu:~/jq-1.6# make
  GEN      src/builtin.inc
  GEN      src/version.h
make  all-recursive
make[1]: Entering directory '/root/jq-1.6'
Making all in modules/oniguruma
make[2]: Entering directory '/root/jq-1.6/modules/oniguruma'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/root/jq-1.6/modules/oniguruma'
Makefile:1085: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/jq-1.6'
Makefile:762: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by kiwina** [comment]
just need to run
`autoreconf -fi
`

**Comment by nicowilliams** [comment]
Eh, this trips me up often tool.  Maybe configure.ac should emit a message
about it when you ask for the built-in and that fails.

**Comment by meta-gitub** [comment]
Actually, the point about --disable-maintainer-mode is that one does not need the autotools. So, if the solution is to run autoreconf, then --disable-maintainer-mode has to be confidered broken, which is a pity.

In my opinion, maintainer mode should be disabled by default in distribution source packages and the package should build fine without the autotools being installed.

**Comment by wtlangford** [comment]
Yes, the requirement for running `autoreconf -fi` was an error made when I packaged the release source packages for 1.6. It won't happen with future releases.

**Comment by meta-gitub** [comment]
@wtlangford : thanks for your comment. I just have built 1.6 after installing autotools. It is good to hear that autotools will not be needed for future releases.
