### ISSUE TITLE
why yield this result?

### ISSUE THREAD

**Issue by skygragon** [stedolan/jq#1783]
jq 1.5 on mac

```
# echo -n '{"id":9224851642388483}' | jq .
{
  "id": 9224851642388484
}
```

**Comment by linquize** [comment]
JSON does not have `int64` type. It treats this number as `Number` type that store as a floating point number, which may lose precision for int64

**Comment by pkoppstein** [comment]
See also #1743 and PR https://github.com/stedolan/jq/pull/1752
