### ISSUE TITLE
Unknown option --argjson

### ISSUE THREAD

**Issue by LukasWallisch** [stedolan/jq#1786]
When I try to run my bash script I get the above mentioned error. I last tested this around August '18 when it was working fine.

**To Reproduce**
Bash Input:
```jq
jq -c --argjson first 123 '[$first]' <<< '[]'
```
Bash Output:
```
jq: Unknown option --argjson
Use jq --help for help with command-line options,
or see the jq documentation at http://stedolan.github.com/jq
```

**Expected behavior**
As in the Manual mentioned the output should look like this i think:
```jq
[123]
```

Like the --arg option works:`jq -c --arg first 123 '[$first]' <<< '[]'`
Output:`["123"]`

**Environment (please complete the following information):**
 - OS : Ubuntu 14.04
 - jq version 1.3: installed with

>   apt-get install jq 

which doesn't give 1.5, as mentioned on the downloadpage!

**Comment by LukasWallisch** [comment]
Workaround for in this specific case:
```jq
jq -c --arg start 123 '[($start|tonumber)]' <<< []
```
so `($start|tonumber)` can be use like `$start` used with the --argjson option.
Doesn't look nice, but at least it works ;)

**Comment by nicowilliams** [comment]
@LukasWallisch We can't help that Ubuntu 14.04 still ships jq 1.3.  You might want to open an issue with Canonical, though be aware that they'll probably tell you to upgrade to a more recent Ubuntu release.

**Comment by nicowilliams** [comment]
And, of course, we provide some executables on the [jq home page](https://stedolan.github.io/jq/) and the [jq GitHub releases page](https://github.com/stedolan/jq/releases).
