### ISSUE TITLE
Installation with Homebrew does not work on macOS

### ISSUE THREAD

**Issue by FloSchramm** [stedolan/jq#1796]
When i do a 'brew install jp' i'll get an not found error. 

$ brew update
Already up-to-date.
$ brew install jp
Error: No available formula with the name "jp"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
These similarly named formulae were found:
jp2a                  jpeg ✔                jpeg-turbo            jpegoptim             mjpegtools            openjpeg              recoverjpeg
jpcsp                 jpeg-archive          jpeginfo              jpegrescan            mozjpeg               pjproject
To install one of them, run (for example):
  brew install jp2a
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.`

Is macOS not supported anymore?

**Comment by ZeroPointZ** [comment]
typo error - you should have 'brew install jq'

looks like you have 'brew install jp'

**Comment by FloSchramm** [comment]
Damn, you are right! Working like a charm!

**Comment by Jokero** [comment]
I get the following errors after installation:
```
$ jq
-bash: jq: command not found

$ brew link jq
Linking /usr/local/Cellar/jq/1.6... 
Error: Could not symlink include/jq.h
/usr/local/include is not writable.
```

**Comment by FloSchramm** [comment]
Looks like a permission problem. 
Try the following:
sudo chown -R $(whoami) $(brew --prefix)/*
sudo chown -R $USER:admin /usr/local/include
brew doctor

Then do the brew link jq again.

**Comment by Jokero** [comment]
Looks like it will be much easier to install from github 😄 https://github.com/stedolan/jq/wiki/Installation#from-github
