### ISSUE TITLE
Add `filter` builtin

### ISSUE THREAD

**Issue by kszafran** [stedolan/jq#1802]
When I'm operating on arrays I can either split it into a list, transform, and collect back into an array, e.g.:
```
jq '[.[] | .id]' array.json
```
or I can use the more friendly `map` function:
```
jq 'map(.id)' array.json
```

However, when I need to select specific elements, I have to use the first form:
```
jq '[.[] | select(.color == "blue")]' array.json
```
I suggest to add an analogous `filter` function:
```
def filter(f): [.[] | select(f)];
```
so we can write simply:
```
jq 'filter(.color == "blue")' array.json
```

To sum up:
1. `filter` is a common concept in functional programming
2. `filter` is analogous to `map`
3. in more complex transformation it's clearer when you can just pipe into `map` or `filter` without having to split the array into a list and enclose a part of you program in `[`,`]`

**Comment by odnoletkov** [comment]
Jq has inherent concept of 'nothingness' (no output), so you can easily do filtering using built-ins:
```
jq 'map(select(.color == "blue"))' array.json
```

This is in contrast with other languages where `filter` can't be easily expressed and have more reasons to be included in the library.

**Comment by kszafran** [comment]
Interesting, I haven't though of such a solution. Thanks!
