### ISSUE TITLE
Provide python WHL ?

### ISSUE THREAD

**Issue by stuaxo** [stedolan/jq#1810]
Is there any chance of providing a WHL ?

I'm stuck with Windows box at work with, and this would make life easier.

**Comment by wtlangford** [comment]
jq isn't a python program, and we don't ship any python bindings, so I'm not sure what you'd want with a WHL?

**Comment by stuaxo** [comment]
Doh, bad search engining on my part, I saw the pip install for the python bindings and thought it was for jq itself.
