### ISSUE TITLE
How to get minimum value

### ISSUE THREAD

**Issue by cytort** [stedolan/jq#1829]
I have an output of: but i only want the minimum value per mac address. How can I filter this to just show minimum value per mac? I've tried min_by but it doesn't work. Thanks for the help.
"D4:0A:A9:00:01:25"
-49.25
-48.85
-48.85
-48.95
-49.25
"A0:04:60:FC:8D:10"
-48.75
-48.75
-48.75
-48.75
-48.75
"D4:04:CD:E5:5E:2D"
-48.75
-48.75
-48.55
-48.75
-48.75
"D4:0A:A9:0C:80:D9"
-48.75
-48.75
-48.75
-48.55
-48.75

**Comment by nicowilliams** [comment]
```
$ jq -cs min <<EOF
> "D4:0A:A9:00:01:25"
> "A0:04:60:FC:8D:10"
> "D4:04:CD:E5:5E:2D"
> "D4:0A:A9:0C:80:D9"
> EOF
"A0:04:60:FC:8D:10"
$ 
```

**Comment by cytort** [comment]
Hi Nico,

The output that i am looking for is something like this
"D4:0A:A9:00:01:25"
-48.85
"A0:04:60:FC:8D:10"
-48.75
"D4:04:CD:E5:5E:2D"
-48.55
"D4:0A:A9:0C:80:D9"
-48.75

I've attached the file that i am working on. and filtered this so far.
.[] | select(.regStatus=="online") | (.mac),(.usChResponse[]|.rxLevel)
but my desired output is to get the min rxlevel value per mac.

[sample.txt](https://github.com/stedolan/jq/files/2882435/sample.txt)

**Comment by muhmuhten** [comment]
```
% ./jq '[.[]|select(.regStatus=="online")]|group_by(.mac)[]|.[0].mac, ([.[].usChResponse[].rxLevel]|min)' sample.txt | head
"00:40:36:43:5F:31"
-50.65
"18:D6:C7:23:3A:10"
-50.05
"18:D6:C7:40:13:CE"
-50.55
"50:09:59:73:00:2D"
-48.75
"58:19:F8:B6:1A:0D"
-48.75
```

**Comment by nicowilliams** [comment]
@cytort It helps to include that sort of information earlier :)
