### ISSUE TITLE
--run-tests unnecessarily recompiles builtins over and over

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#1833]
Perhaps we should have a memoization of this.  It'd have to be thread safe for `libjq` users.

**Comment by muhmuhten** [comment]
Does this still seem concerning post-#1834? Because if it doesn't, then I think it'd be better to keep low divergence for the testing environment, if for no other reason than to make sure we're checking the same set of linker bugs.

**Comment by nicowilliams** [comment]
@muhmuhten It's not a problem now.  Well, I suppose it might make a difference to test times when run with valgrind...  Anyways, I'll close it.  When we get around to making it so we can do `include "jq/xyz"` where `xyz` might be `all`, `minimal`, `math`, ... then this will get fixed by dint of treating `src/builtin.jq` (and friends) as libraries.
