### ISSUE TITLE
scalars_or_empty is undocumented

### ISSUE THREAD

**Issue by muhmuhten** [stedolan/jq#1840]
Actually, can we get rid of it? It's kind of misnamed (empty means something else...) and it's only used for one test (for the streaming parser 5bfb9781f7e5ba2ad99b71150bccc559d53b928f), which isn't even testing it specifically.

**Comment by nicowilliams** [comment]
Sure, let's get rid of it.

**Comment by nicowilliams** [comment]
Removed in #1845.
