### ISSUE TITLE
Can't redirect to file

### ISSUE THREAD

**Issue by kenorb** [stedolan/jq#1841]
**Describe the bug**

I'd like to use the following shell syntax to redirect input to output file:

`jq <<<'{"foo": "bar"}' > file`

but this doesn't work as expected, as `jq` shows the help page instead. Although it works fine when redirected to `/dev/stdout`.

**To Reproduce**

```
$ jq <<<'{"foo": "bar"}' > file
jq - commandline JSON processor [version 1.5-1-a5b5cbe]
...
```

**Expected behavior**

This should work the same as it works for `/dev/stdout`:

```
$ jq <<<'{"foo": "bar"}' > /dev/stdout
{
  "foo": "bar"
}
```

And the same way, as `python -mjson.tool` works, e.g.

```
$ python -mjson.tool <<<'{"foo": "bar"}' > file
$ cat file 
{
    "foo": "bar"
}
```

**Environment (please complete the following information):**
 - OS and Version: bash in Ubuntu
 - jq version: `jq-1.5-1-a5b5cbe`

**Comment by nicowilliams** [comment]
You have to specify a jq _program_.  For example, if all you want to do is pretty-print JSON, then your program would be just `.`:

```
$ jq . <<<'{"foo": "bar"}' > file
$ cat file
{
  "foo": "bar"
}
$ 
```

There are many programs you can write besides `.`.  See the tutorial and manual.
