### ISSUE TITLE
[REQUEST] | Variable Expansion

### ISSUE THREAD

**Issue by bradennapier** [stedolan/jq#1856]
Sorry if this is included somewhere, looked for a good 30-60 minutes for something along these lines.  I am sure I just missed something! Total jq nub!

Basically I am trying to do a `pick` operation that is dynamic.  My thought process was to do something like this:

```bash
pickJSON() {
  getSomeJSON | jq -r --arg PICK "$1" '{ $PICK }'
}

pickJSON "foo, bar"
```

but this produces

```
{ "PICK": "foo, bar" }
```

Is there a way to essentially ask it to expand shell-style?

---

### Desired Result:

```bash
pickJSON() {
  getSomeJSON | jq -r --arg PICK "$1" '{ $PICK }'
  # perhaps something like...
  # getSomeJSON | jq -r --arg PICK "$1" '{ ...$PICK }'
}

pickJSON "foo, bar"
```

```
{ "foo": "foovalue", "bar": "barvalue" }
```

> Note that I am new to `jq` and i just simplified what i am doing - if the syntax is broken that is why :-D my actual implementaiton has a few pipes in there and it does work if i dont try to pick the values out of it.

**Comment by bradennapier** [comment]
Realized stackoverflow is desired place for this - https://stackoverflow.com/questions/55037108/how-to-expand-variable-value-to-build-a

**Comment by nicowilliams** [comment]
The problem is you seem to want the argument(s) to your `pickJSON` to be part of the jq _program_, but that's not what `--arg` does.  `--arg` gives you a named _value_, not named _code_.

Here's something close to what you want:

```
pickJSON () {
    getSomeJSON | jq --args '. as $dot | reduce $ARGS.positional[] as $pick ({}; .[$pick] = $dot[$pick])'
}
```
