### ISSUE TITLE
jq error messages do not identify jq as error source

### ISSUE THREAD

**Issue by CODE-REaD** [stedolan/jq#1860]
**Describe the bug**
I cannot tell which command in in my piped UNIX command emitted the error.

**To Reproduce**
$ ansible myhost -o -m raw -u mylogin -a "ls -lL /var/www/db-backups" | jq -c
Error displayed:
parse error: Invalid numeric literal at line 1, column 18

**Expected behavior**
jq would identify itself as source of error.  So above message would say:
jq: parse error: Invalid numeric literal at line 1, column 18

**Environment (please complete the following information):**
PRETTY_NAME="CentOS Linux 7 (Core)"
jq-1.6 

**Additional context**

Could be resolved by changing
https://github.com/stedolan/jq/blob/88e1f59ec176ff37781b13bba065ed231ca5222f/src/main.c#L671

to: 
fprintf(stderr, "jq: parse error: %s\n", jv_string_value(msg));

**Comment by nicowilliams** [comment]
Thanks for the report!

**Comment by nicowilliams** [comment]
As the commit I pushed says:

>     However, we should really use the argv[0] progname, not just jq.
>     Someday we may want to support aliases which automatically add certain
>     options, etc.
