### ISSUE TITLE
MSYS2 line ending compatibility

### ISSUE THREAD

**Issue by step-** [stedolan/jq#1870]
I'm running jq 1.6 on an MSYS2 x64 distribution in Windows 10. The jq binary was installed with command `pacman -S mingw-w64-x86_64-jq` ([direct link to the package](http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-jq-1.6-1-any.pkg.tar.xz)).

Issue: jq outputs the DOS \r\n line ending while other MSYS2 binaries correctly output the Unix line ending \n. Consider the following MSYS2 bash shell output:
```
$ jq -n '1' | xxd
00000000: 310d 0a                                  1..

$ echo 1 | xxd
00000000: 310a                                     1.

$ /bin/echo 1 | xxd
00000000: 310a                                     1. 

$ /bin/printf 1 | xxd
00000000: 31                                       1
```
The extra \r that jq adds breaks all shell scripts, because MSYS2 works in binary mode, so the \r is interpreted as a control character.  Example of the twisted things that can happen:
```
$ x="$(echo 1 | jq -r '.,.')"; echo "$x" | xxd
00000000: 310d 0a31 0a
```

Surely, it can't be considered correct that jq `1,1`  will set x equals to (quotes added for emphasis)
```
"1\r
1"
```

The question in my mind is, what are the rest of the MSYS2 binaries doing to "just work" that jq isn't doing, which results in DOS line endings where Unix line endings are expected?

A similar issue was discussed in #92 for cygwin, in particular @hackery's [comment](https://github.com/stedolan/jq/issues/92#issuecomment-457160993) reports the same issue as mine (I think - there aren't enough details to be sure).

While piping jq to `tr -d '\r'` is a possible work-around,I hope it isn't the final answer, considering that `jq` behaves differently from the rest of the MSYS2 binaries for no good reason. See also bullet 3 in [How does MSYS2 differ from Cygwin](https://github.com/msys2/msys2/wiki/How-does-MSYS2-differ-from-Cygwin#runtime).

Thank you

**Comment by nicowilliams** [comment]
Can you test [this version](https://ci.appveyor.com/api/buildjobs/9pc3vq0ih6t3oeok/artifacts/jq.exe) (or [32-bit](https://ci.appveyor.com/api/buildjobs/scuf0tj7ulc57t8q/artifacts/jq.exe)) of jq for Windows, adding a `-b` or `--binary` command-line option?

**Comment by step-** [comment]
Thanks for your quick reply. I tested the 64 bit version and it appears to fix the issue. Look at this:

```
$ echo 1 | jq.exe -b '.,.' | xxd
00000000: 310a 310a                                1.1.

$ x="$(echo 1 |  jq.exe -br '.,.')"; echo "$x" | xxd
00000000: 310a 310a                                1.1.

$ echo 1 |  jq.exe '.,.' | xxd
00000000: 310d 0a31 0d0a                           1..1..

$ x="$(echo 1 |  jq.exe -r '.,.')"; echo "$x" | xxd
00000000: 310d 0a31 0a                             1..1.
                         
$ echo 1 | jq.exe --version
jq-1.2-1089-g88b04a7
```

Based on the version string I suppose that it's an older experiment of some kind?
Fyi, I couldn't further test it with the rest of my script because I got this other error message
```
+ ./platform/win64/jq.exe -b -f /c/jq/validate.jq -r --arg api groups --args
jq: error loading data file jq/common.jq: No such builtin module jq/common.jq

jq: 1 compile error
+ ret=3
```
where the include in validate.jq is `include "jq/common";` and `/c/jq/common.jq` exists. With msys2 jq 1.6 the same include works fine.

**Comment by nicowilliams** [comment]
Disregard the version string.  The executables i linked are from my `dlopen` branch, which has support for built-in modules named `"jq/..."` -- i should make sure you can still have non-built-in modules of that form....

**Comment by nicowilliams** [comment]
@step- So, how hard would it be to rename your modules so they don't start with `"jq/"`?

**Comment by nicowilliams** [comment]
Fixed in master with 0dab2b1.

**Comment by step-** [comment]
> @step- So, how hard would it be to rename your modules so they don't start with `"jq/"`?

@nicowilliams, no problem, I can adapt.

Can I ask you a favor? I don't have an MSYS2 toolchain set up.  Can you please post a link to a compiled jq.exe 64-bit artifact for 0dab2b1 so I can move on with my project?  Thanks

**Comment by nicowilliams** [comment]
Later today, when the Appveyor Windows build of master completes, you can visit https://ci.appveyor.com/project/stedolan/jq click on the 64-bit build, click on artifacts, then click on the jq.exe artifact to download it.  That will be a pre-release executable, so buyer beware.

**Comment by nicowilliams** [comment]
@step-

 - [Appveyor Windows build of master](https://ci.appveyor.com/project/stedolan/jq)
 - [Appveyor Windows 64-bit build of master](https://ci.appveyor.com/project/stedolan/jq/build/job/dnowfuayen9x06po)
 - [artifacts from that](https://ci.appveyor.com/project/stedolan/jq/build/job/dnowfuayen9x06po/artifacts)
 - [64-bit jq.exe artifact from that](https://ci.appveyor.com/api/buildjobs/dnowfuayen9x06po/artifacts/jq.exe)

**Comment by step-** [comment]
Great. Thank you, @nicowilliams .

**Comment by nicowilliams** [comment]
You're welcome.
