### ISSUE TITLE
Question: How to know about capabilities of older version of jq?

### ISSUE THREAD

**Issue by karfau** [stedolan/jq#1871]
Are the docs for old versions still available somewhere?
Or could a version selector be added to https://jqplay.org/ ?

This would make the life easier for people that are stuck in some earlier version, e.g. on a CI system.

**Comment by nicowilliams** [comment]
http://stedolan.github.io/jq/manual/ has links to the manual for each version:

 - http://stedolan.github.io/jq/manual/v1.3
 - http://stedolan.github.io/jq/manual/v1.4
 - http://stedolan.github.io/jq/manual/v1.5
 - http://stedolan.github.io/jq/manual/v1.6

**Comment by karfau** [comment]
Very awesome! Thx
