### ISSUE TITLE
f_strftime/jv2tm: Assertion `jv_get_kind(j) == JV_KIND_ARRAY' failed.

### ISSUE THREAD

**Issue by pallas** [stedolan/jq#1874]
**Describe the bug**
Assertion in strftime builtin.

**To Reproduce**
```jq -n 'range(365)|("5970-03-01T01:02:03Z"|strptime("%Y-%m-%dT%H:%M:%SZ")|mktime)* (86400 * .)|strftime("%Y-%m-%dT%H:%M:%SZ")'```

```"1970-01-01T00:00:00Z"
"345615936-12-13T00:00:00Z"
"691229903-11-25T00:00:00Z"
"1036843870-11-05T00:00:00Z"
"1382457837-10-17T00:00:00Z"
"1728071804-09-28T00:00:00Z"
"2073685771-09-09T00:00:00Z"

jq: jv.c:324: jv_array_get: Assertion `jv_get_kind(j) == JV_KIND_ARRAY' failed.
Program received signal SIGABRT, Aborted.
0x00007ffff76ac80b in raise () from /lib64/libc.so.6
#0  0x00007ffff76ac80b in raise () from /lib64/libc.so.6
#1  0x00007ffff76ae051 in abort () from /lib64/libc.so.6
#2  0x00007ffff76a438a in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff76a4412 in __assert_fail () from /lib64/libc.so.6
#4  0x0000555555585c3b in jv_array_get (j=..., idx=idx@entry=0) at src/jv.c:333
#5  0x00005555555d1bf2 in jv2tm (a=..., tm=tm@entry=0x7fffffffdce0) at src/builtin.c:1400
#6  0x00005555555d90d6 in f_strftime (jq=<optimized out>, a=..., b=...) at src/builtin.c:1524
#7  0x000055555556d766 in jq_next (jq=0x55555565a530) at src/execute.c:853
#8  0x000055555555ec18 in process (jq=0x55555565a530, value=..., flags=<optimized out>, dumpopts=645) at src/main.c:179
#9  0x000055555555cda7 in main (argc=<optimized out>, argv=<optimized out>) at src/main.c:654
```

**Expected behavior**
An error, not an assert.

**Environment (please complete the following information):**
 - OS and Version: Gentoo/Linux
 - jq version jq 1.6 @ 27ef4be, also in 1.5

**Additional context**
Found via American Fuzzy Lop, the above case is a fuzzed version of one of the tests in tests/optional.test

**Comment by pallas** [comment]
Oops, is not a regression from 1.5 as originally stated; it happens in both 1.5 and 1.6 at the above hash.

**Comment by nicowilliams** [comment]
Missing error check.

**Comment by pallas** [comment]
It sounds like you see the bug. LMK if I should keep working on a patch or if you've got one in mind already.

**Comment by nicowilliams** [comment]
No, I found the bug, it's pretty trivial.  Thanks @pallas!
