### ISSUE TITLE
Is it possible to get only first or last object of the output?

### ISSUE THREAD

**Issue by a-rodin** [stedolan/jq#1876]
Hi,

Is is possible to output only last object with `jq`?

For example, for the following input

```js
{"a": 3}
{"a": 4}
{"a": 5}
```
I would like to output only

```js
{"a": 5}
```

The `last` function works only with arrays and it seems like it is not possible to convert "object in each row" input to an array.

**Comment by nicowilliams** [comment]
@a-rodin `jq -n 'last(inputs)'`

**Comment by a-rodin** [comment]
@nicowilliams Thank you, works like a charm!

**Comment by nicowilliams** [comment]
You're welcome!
