### ISSUE TITLE
Preserve special characters (like newline) in output

### ISSUE THREAD

**Issue by kyuferev** [stedolan/jq#1881]
Hi.
I have a JSON file `filename` with `description` field which contains a string with newline characters. For example:
```
{
   "description" : "this is a line with \n character in it"
}
```
When I try to extract this string with `jq -r ".description" filename` I receive this:
```
this is a line with
 character in it
```
But I need to receive the string from `description` exactly as it is, including all special characters. How do I do that?

**Comment by wtlangford** [comment]
So, you've got two options for outputting strings:
1. Output json-encoded strings (these will be double-quoted and escaped)
2. Output raw text with -r (the escapes will be turned back into the original character and printed)

I'm not sure what you want printed out. Can you clarify?

**Comment by kyuferev** [comment]
> I'm not sure what you want printed out. Can you clarify?

I want to receive a single string which is stored in `description` field:
```
~# jq -r ".description" filename
this is a line with \n character in it
~#
```
But instead I'm receiving:
```
~# jq -r ".description" filename
this is a line with
 character in it
~#
```
Using `-r` parameter doesn't help much. I guess I should use json-encoded strings as output and then just cut double-quotes with `sed` or `grep`.

**Comment by kyuferev** [comment]
Yes, receiving output as json-formatted string works:
```
~# jq ".description" filename | sed -e "s/\"//g"
this is a line with \n character in it
~#
```
Should I close this issue?

**Comment by wtlangford** [comment]
Yep, if you're satisfied, you can close this. Do be aware that your regex also strips any double quotes inside the string.

**Comment by kyuferev** [comment]
> 
> 
> Yep, if you're satisfied, you can close this. Do be aware that your regex also strips any double quotes inside the string.

Yes, I've also noticed that and modified it a bit:
```
~# jq ".description" filename | sed -e "s/^\"//g" -e "s/\"$//g"
this is a line with \n character in it
~#
```
Thanks alot!
