### ISSUE TITLE
jq: syntax error, unexpected LITERAL if fieldname is a nummeric under powershell

### ISSUE THREAD

**Issue by TimoC1982** [stedolan/jq#1882]
Hi Guys,

I have a little problem with jq 1.5/1.6 under a Windows 10 enviroment.
I use jq in a PowerShell Shell. If a path of a Array/object contains a nummeric title i got the literal error. I tried to escape the path with " but it Looks like that this isn't work under PowerShell. 

`jq command: . | { last_update:  .starbase_detailed_scan.last_update_time, user_name:  .starbase_detailed_scan.owner_name, alliance_id: .starbase_detailed_scan.owner_alliance_id, drydocks: .starbase_detailed_scan.num_drydocks, tier: .starbase_detailed_scan.owner_level, defence_plattform: .starbase_detailed_scan.num_defence_platforms, shield_triggered: .starbase_detailed_scan.player_shield.triggered_on, shield_end: .starbase_detailed_scan.player_shield.expiry_time, parsteel: .resources."325683920".current_amount, tritanium: .resources."743985951".current_amount, dilithium: .resources."2614028847".current_amount, user_id: .starbase_detailed_scan.owner_user_id, defence_rating: .starbase_detailed_scan.defense_rating }`

example data:
[https://codebeautify.org/online-json-editor/cb8adb0a](url)

any tips?

BR
Timo

**Comment by wtlangford** [comment]
I suspect it's a quoting issue with powershell. Can you paste the full command as you ran it?

**Comment by TimoC1982** [comment]
Hi,

i tried this in bot variants:
`C:\import\stfc\jq.exe -c -f C:\import\stfc\user_filter.jq  C:\Import\stfc\user_k5a92643d5144677afe2406dca65e069.json

`or

`C:\import\stfc\jq.exe -c '. | { last_update: .starbase_detailed_scan.last_update_time, user_name: .starbase_detailed_scan.owner_name, alliance_id: .starbase_detailed_scan.owner_alliance_id, drydocks: .starbase_detailed_scan.num_drydocks, tier: .starbase_detailed_scan.owner_level, defence_plattform: .starbase_detailed_scan.num_defence_platforms, shield_triggered: .starbase_detailed_scan.player_shield.triggered_on, shield_end: .starbase_detailed_scan.player_shield.expiry_time, parsteel: .resources."325683920".current_amount, tritanium: .resources."743985951".current_amount, dilithium: .resources."2614028847".current_amount, user_id: .starbase_detailed_scan.owner_user_id, defence_rating: .starbase_detailed_scan.defense_rating }' C:\Import\stfc\user_k5a92643d5144677afe2406dca65e069.json
`

**Comment by TimoC1982** [comment]
Found it myself

**Comment by m1ksu** [comment]
> Found it myself

https://xkcd.com/979/
