### ISSUE TITLE
Unexpected behaviour with incorrect input

### ISSUE THREAD

**Issue by HaanJde** [stedolan/jq#1887]
**Describe the bug**
Given the input, which is apparently is wrong, I would have expected an error message.

**To Reproduce**
```
$ echo '{ "atribute1": { "attribute2": "name1", "attribute3": { "attribute2": "name2" }, "attribute3": { "attribute2": "name3" }, "attribute3": { "attribute2": "name4" } } }' | jq '.'
{
  "atribute1": {
    "attribute2": "name1",
    "attribute3": {
      "attribute2": "name4"
    }
  }
}
```
 
**Expected behavior**

```
$ cat expected_output.json 
{ 
 "atribute1": {
  "attribute2": "name1",
  "attribute3": {
   "attribute2": "name2"
  },
  "attribute3": {
   "attribute2": "name3"
  },
  "attribute3": {
   "attribute2": "name4"
  }
 }
}
$

```
**Environment (please complete the following information):**
 - OS and Version: Linux Ubuntu 18.04.2
 - jq version: jq-1.6rc1-11-g90bc29c-dirty

**Additional context**
I suspect this to be a language problem, as the competition (jshon) does the same. An error message would be nice, though.

**Comment by pkoppstein** [comment]
>Given the input, which is apparently is wrong, I would have expected an error message.

For better or worse, the JSON specification allows (but deprecates) repeated keys within an object, so the input is not "wrong". If you read the JSON specifications closely, you'll also see that implementations are permitted to take the view, as does jq, that the last-most key wins.

**Comment by HaanJde** [comment]
Thanks Peter. 4/24, if I'm right.
