### ISSUE TITLE
input_filename should be null when read from stdin

### ISSUE THREAD

**Issue by nichtich** [stedolan/jq#1888]
**Describe the bug**
The value of `input_filename` is not documented when input is read from stdin or when option `-n` is used. When read from stdin, it turns out the value is not `null` but a string.

**To Reproduce**

    echo '{}' | jq input_filename
    "<stdin>"

    jq -n '{} | input_filename' 
    null

**Expected behavior**

I'd expect the result to be `null` in both cases.

**Comment by pkoppstein** [comment]
> I'd expect the result to be null in both cases.

That seems wrong.   One would certainly expect the -n option to result in null, but reading from stdin is clearly not the same as not reading from stdin.  Choosing "<stdin>" seems like a reasonable choice for the former case, though the number 0 would have the advantage of avoiding a collision with a file named "<stdin>".

**Comment by nicowilliams** [comment]
On Unix we could make it resolve to `/dev/stdin` or `/dev/fd/0`.  What would we do on Windows?  In any case, a non-absolute path works.
