### ISSUE TITLE
Allow "raw" output of arrays

### ISSUE THREAD

**Issue by arodland** [stedolan/jq#189]
When using `jq -r`, if the result is an array, then assume it's an array of strings, and print them, one per line, without quotes, without commas, and without a leading `[` or trailing `]`.

The goal is that this:

```
echo '{"results":[{"id":1},{"id":2},{"id":3}]}' | jq -r '.results | map("ID is \(.id)")'
```

Will output

```
ID is 1
ID is 2
ID is 3
```

instead of

```
[
  "ID is 1",
  "ID is 2",
  "ID is 3"
]
```

which I think would make `jq -r` that much more useful for interacting with non-JSON tools. In particular it would let you generate tab-separated files.

**Comment by Relequestual** [comment]
> @nicowilliams: In any case, for now the only way to collect items into an array is by placing square brackets around the expression producing the values to be collected.

@nicowilliams Is this still the case? I'm trying to do somthing similar as a last action, because I don't know if i'll have an array or a singe item from the array in my given json.

**Comment by pkoppstein** [comment]
@Relequestual - You can, for example, now use `reduce inputs ....` (using -n instead of -s).  

If that doesn’t answer your question, I would suggest asking it at stacjoverflow.com with the jq tag: 
https://stackoverflow.com/questions/tagged/jq

**Comment by Relequestual** [comment]
@pkoppstein Looks like `-n` is for building JSON data from scratch, aka null as an input. That's what the current docs tell me. I can't work out how that's related to what I asked. (I'm happy to be enlightened, but it doesn't sound like you have the time, and that's OK)

**Comment by pkoppstein** [comment]
The `-n` option is generally needed when using `inputs`.  Some of the documentation about -n might be a bit misleading, or you might have misinterpreted it -- it's a bit tricky to explain, but `input` and `inputs` will (attempt to) read from STDIN.

**Comment by Relequestual** [comment]
From the docs:

> 
> --null-input/-n:
> 
> Don’t read any input at all! Instead, the filter is run once using null as the input. This is useful when using jq as a simple calculator or to construct JSON data from scratch.

If you're saying this will read input from STDIN, then yes this is totally missleading.

Looks like I missunderstood the OPs question here. I'm looking to wrap IN an array, in unwrap an existing array output. Oops! =/

**Comment by pkoppstein** [comment]
“Don’t read any input at all!” should be interpreted to mean “Don’t read any input at all except as explicitly specified.”
