### ISSUE TITLE
jq accepts invalid json input (unterminated objects/arrays)

### ISSUE THREAD

**Issue by wbolster** [stedolan/jq#1893]
## Describe the bug

`jq` does not reject some invalid json input, while it should. It seems this happens for input that contains opening characters for (nested) container types (objects and arrays), but no corresponding closing characters.

## To Reproduce

an opened (but never closed) object `{` does not produce an error:

```
$ echo '{' | jq .
```

similar things happen for `[[[[[`:

```
$ echo '[[[[[[[[[[[[[[[' | jq .
```

## Expected behavior

`jq` should throw an error since this is invalid json.

## Environment

 - OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
 - jq version [e.g. 1.5]

```
$ jq --version
jq-1.5-1-a5b5cbe

$ lsb_release -ds
Ubuntu 19.04
```

**Comment by pkoppstein** [comment]
Note that in jq 1.6, incomplete input (at least in cases such as these) does yields an error:

    $ echo '{' | jq .
    parse error: Unfinished JSON term at EOF at line 2, column 0

    $ echo '[' | jq .
    parse error: Unfinished JSON term at EOF at line 2, column 0

**Comment by wbolster** [comment]
ok, so at least some problems have been fixed already. 👌

not sure if there are remaining cases, and whether this bug report should be the one tracking those. i'll leave it to a maintainer to decide whether this issue can be marked fixed.

**Comment by wbolster** [comment]
i will close this issue since `jq` 1.6 has been out for a while already
