### ISSUE TITLE
bug when install on ubuntu from git source

### ISSUE THREAD

**Issue by ORESoftware** [stedolan/jq#1905]
The commit is:
ad9fc9f559e78a764aac20f669f23cdd020cd943

I run:
```
autoreconf -i
./configure --disable-maintainer-mode

```

I get:

```
checking dependency style of gcc... (cached) gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... gcc -E
checking for bison... no
checking for byacc... no
./configure: line 5562: syntax error near unexpected token `shared'
./configure: line 5562: `LT_INIT(shared static win32-dll)'

```

maybe cause not on windows?

**Comment by nicowilliams** [comment]
Does the tarball from the release page work?  What version of autoconf do you have?

**Comment by ORESoftware** [comment]
idk this was reported 5 days ago, I moved on

**Comment by nicowilliams** [comment]
@ORESoftware Look mate, jq is an open source project maintained and supported by VOLUNTEERS.  So, yes, you have to help us help you.  Actually, even if you were paying us, you'd have to help us help you.  "X doesn't work; make it work" -> "can you tell us more?" -> "ugh, do I have to do everything??" -- that attitude won't take you far.

**Comment by ORESoftware** [comment]
damnit it's all my fault
