### ISSUE TITLE
Extend arrays different behavior with slurpfile vs inplace

### ISSUE THREAD

**Issue by rbo** [stedolan/jq#1908]
**Describe the bug**

If I extend an array with `|= . +` there is an behavior. If I use `--slurpfile` I got a nested array and without slurpfile I got a array as I expected.

**To Reproduce**
```json
$ echo '{ "list": { "file":[{ "a":"a"}]}}' | jq --slurpfile content <( echo '[{"b":"b"},{"c":"c"}]' )  '.list.file |= . + $content'
{
  "list": {
    "file": [
      {
        "a": "a"
      },
      [  <-------- start of my nested array, what I not expected.
        {
          "b": "b"
        },
        {
          "c": "c"
        }
      ]
    ]
  }
}
$ echo '{ "list": { "file":[{ "a":"a"}]}}' | jq '.list.file |= . + [{"b":"b"},{"c":"c"}]'
{
  "list": {
    "file": [
      {
        "a": "a"
      },
      {
        "b": "b"
      },
      {
        "c": "c"
      }
    ]
  }
}
```

**Expected behavior**
The same behavior.

**Environment (please complete the following information):**
 - macOS 10.14.5 (18F132)
 - jq-1.6

**Additional context**

**Comment by nicowilliams** [comment]
Please read the documentation on `--slurpfile`.

**Comment by rbo** [comment]
Ah got it, nested list... 
```json
$ echo '{ "list": { "file":[{ "a":"a"}]}}' | jq --slurpfile content <( echo '[{"b":"b"},{"c":"c"}]' )  '$content'
[
  [
    {
      "b": "b"
    },
    {
      "c": "c"
    }
  ]
]
```

Sadly `{"b":"b"},{"c":"c"}` is not a valid json:
```
echo '{ "list": { "file":[{ "a":"a"}]}}' | jq --slurpfile content <( echo '{"b":"b"},{"c":"c"}' )  '$content'
jq: Bad JSON in --slurpfile content /dev/fd/63: Expected value before ',' at line 1, column 10
```

`--rawfile` escape my json:
```
echo '{ "list": { "file":[{ "a":"a"}]}}' | jq --rawfile content <( echo '{"b":"b"},{"c":"c"}' )  '$content'
"{\"b\":\"b\"},{\"c\":\"c\"}\n"
```

Is there any way to solve my problem with slurping a file into a variable?

**Comment by pkoppstein** [comment]
> Sadly {"b":"b"},{"c":"c"} is not a valid json

Why "sadly"?  It is not valid JSON, so the question is: where does it come from?  If it comes from your imagination, then you could easily make suitable adjustments, either in your imagination, or by adding the surrounding square brackets that would make a comma-separated sequence of JSON objects into a JSON array.  The latter can be accomplished in an unbounded number of ways, e.g. using `sed` or `jq`.  If you want to use jq, it might be useful to know about the`fromjson` builtin, e.g.

```
echo '{"b":"b"},{"c":"c"}' | jq -Rc '"[" + . + "]" | fromjson'
[{"b":"b"},{"c":"c"}]
```
