### ISSUE TITLE
Cannot sanitize/escape string

### ISSUE THREAD

**Issue by ORESoftware** [stedolan/jq#1919]
I have this script:

```bash
#!/usr/bin/env bash

user_input="$'a e""R<*&\04\n\thello!\''"

clean_output="$(jq -nc --arg str "$user_input" '$str')"

echo "clean output: $clean_output"

echo "{\"foo\":\"$clean_output\"}" | jq -r
```

for some reason I always get a parse error. I also tried using an `-r flag`:

```bash
clean_output="$(jq -ncr --arg str "$user_input" '$str')"
```

that didn't work either. Is the string simply un-escapable?

**Comment by pkoppstein** [comment]
Please ask usage questions (especially if it likely to be shell-related) at stackoverflow.com with the jq tag: https://stackoverflow.com/questions/tagged/jq

This is generally to everyone's benefit - espeically yours, the maintainers of jq, and future seekers.

**Comment by ORESoftware** [comment]
for sure np
