### ISSUE TITLE
jq 1.6 debian stetch release

### ISSUE THREAD

**Issue by iilei** [stedolan/jq#1922]
Would be nice if jq 1.6 is available via debian package. [At the moment 1.5 is latest](https://packages.debian.org/search?suite=stretch&arch=amd64&keywords=jq)

**Comment by assafmo** [comment]
Yes please :smiley:

**Comment by wtlangford** [comment]
We don't maintain distro-specific packages. You'll want to reach out to the maintainer of that package and request that they update it.

**Comment by iilei** [comment]
I see. Figured out there is a ["high priority" / "action needed" ](https://tracker.debian.org/pkg/jq) issue filed in Nov 2018 ...

I'll just wait and see 😄
