### ISSUE TITLE
Unable to pass args to jq in shell script

### ISSUE THREAD

**Issue by jsvede** [stedolan/jq#1933]
I need to write a shell script in BASH that allows me to call variety of URLs and extract the keys from the JSON that is returned. I have been trying to use jq to help me with this. I want to be able to pair a URL with the jq filters so I can write a function and pass in a URL and the filter values.

The API I am hitting will return simple objects, complex ones, arrays, etc., so I want to write a function to manage this and pass in the URL and the filter values as args. 

However, when I try this I get errors. I've tried a variety of ways of parameterizing the filters that are used by 'jq' but none have worked. 

So, for example, if I have data like this:
```
{
	"firstName":"John",
	"lastName":"Smith",
	"addresses": [
		{
			"address1":"123 Some Pl",
			"address2":"Apt 1",
			"city":"Somewhere",
			"state":"OK",
			"zip":"12345"
		},
		{
			"address1":"123 No Way",
			"address2":"Apt 555",
			"city":"Another Place",
			"state":"KS",
			"zip":"54321"
		}
	],
	"phoneNumbers": [
		{
			"nickname":"cell",
			"type":"cell",
			"number":"111-222-3333",
			"primary":false
		},
		{
			"nickname":"main",
			"type":"main",
			"number":"222-333-4444",
			"primary":true
		}
		
	]
}
```
And then I run this script:
```
#!/bin/bash

FILE_NAME=customer_data.json

JQ_RESPONSE=$(cat $FILE_NAME | jq -r '. | keys')

echo $JQ_RESPONSE
```
It works as expected and produces this output:
`[ "addressess", "firstName", "lastName", "phoneNumbers" ]`

However, if I want to modify the script to make the filter into args, it doesn't work:
```
#!/bin/bash

FILE_NAME=customer_data.json

JQ_ARGS=.

JQ_RESPONSE=$(cat $FILE_NAME | jq -r '$JQ_ARGS| keys')

echo $JQ_RESPONSE
```
This fails like this:
```
jq: error: $JQ_ARGS is not defined at <top-level>, line 1:
$JQ_ARGS| keys
jq: 1 compile error
```
I've tried a lot of different ways of attacking this problem and haven't been successful:
- a variety of single and double ticks around both the value of `$JQ_ARGS` and also in the `jq` command itself
- using the '--args' approach as documented on stack and other sites

None have worked for me, so for now i've just written a lot of scripts that are copies of each other. Long term, I'd like to solve this a little cleaner.

I must be doing something wrong - is there a way to do this?

**Comment by bwbroersma** [comment]
Use double quotes to use the [Shell Parameter Expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) in bash:
```bash
#!/bin/bash
FILE_NAME=customer_data.json
JQ_ARGS=.
JQ_RESPONSE=$(cat $FILE_NAME | jq -r "$JQ_ARGS| keys")
echo $JQ_RESPONSE
```
I don't think `jq` can handle non json/string arguments (in this case a `.` identity filter).

**Comment by nicowilliams** [comment]
Use `--arg` and `--argjson`.  See the help message and/or manual, and make sure you have a recent jq release.
