### ISSUE TITLE
error: implicit declaration of function 'lgamma_r' is invalid in C99

### ISSUE THREAD

**Issue by haniag** [stedolan/jq#1936]
**Describe the bug**
I am getting an error in compiling using "compile-ios.sh".

**To Reproduce**
Just run the script.

**Expected behavior**
A build for several archs including arm64.

**Environment (please complete the following information):**
macOS 10.12.6

**Additional context**
Here's the error message:

```
src/builtin.c:194:31: error: implicit declaration of function 'lgamma_r' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  jv ret = JV_ARRAY(jv_number(lgamma_r(jv_number_value(input), &sign)));
                              ^
1 error generated.
make[2]: *** [src/builtin.lo] Error 1
```

Note that I previously received an error about not having bison 3, so I used the --disable-maintainer-mode to compile.

**Comment by schlu** [comment]
I know there hasn't been much movement on this in the last 5 months, but I am also running into this issue on mac 10.15.x.

I would be happy to make a PR if anyone has any pointers, I am a little out of my depth trying to troubleshoot this.

**Comment by magnetikonline** [comment]
Worked a treat @Enselic 👍

**Comment by earlchew** [comment]
Digging around when I encountered this issue on:
```
Darwin 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:46 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T8101 arm64
```

`/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h` contains the comment:
```
/*      lgammaf, lgamma, and lgammal are not thread-safe. The thread-safe
    variants lgammaf_r, lgamma_r, and lgammal_r are made available if
    you define the _REENTRANT symbol before including <math.h>                */
```

Augmenting `CPPFLAGS` during configuration also solves the problem:
```
CPPFLAGS=-D_REENTRANT ./configure ...
```

**Comment by jzySaber1996** [comment]
Hello, we're investigating the issue reports in security. Since we observed that this issue may relate to a potential vulnerability, has it been disclosed in CVE already? Hope to receive your reply.

**Comment by wader** [comment]
@jzySaber1996 hi, could you explain more how this could be a security issue?
