### ISSUE TITLE
jq thinks key is number when key starts with a number 

### ISSUE THREAD

**Issue by tessus** [stedolan/jq#1943]
**Describe the bug**
I get a compile error when trying to access a key that starts with a number.

**To Reproduce**
```
echo '{"test":{"7z":{"key":"value"}}}' |jq '.test.7z.key'
```

**Expected behavior**
I expect jq to recognize the key `7z` as a string, so that no double quotes are required to access it. A number is hardly a special character, especially since there are no double quotes required when the number is enclosed by 2 letters.

**Environment (please complete the following information):**
 - OS and Version: macOS 10.14.5 18F203
 - jq version 1.6

**Additional context**
The following 2 commands work:
```
echo '{"test":{"7z":{"key":"value"}}}' |jq '.test."7z".key'
echo '{"test":{"a7z":{"key":"value"}}}' |jq '.test.a7z.key'
```
This tells me that jq does not recognize a string as a string when the strings starts with a number.

**Comment by pkoppstein** [comment]
@tessus - The [jq manual](https://stedolan.github.io/jq/manual/ )says explicitly that the .foo abbreviation -

> only works for simple, identifier-like keys, that is, keys that are all made of alphanumeric characters and underscore, and which do not start with a digit.

In general, it is a good idea to check the specs before filing a bug report.

**Comment by tessus** [comment]
Yep, I checked the docs, but when I looked at the Object Identifier-Index section the first thing that caught my eye were the words `special characters` and I started to read there.

**Comment by pkoppstein** [comment]
Thanks for closing the issue.

**Comment by tessus** [comment]
Btw, the documentations should be changed to:

If the key contains special characters **or starts with a digit**, you need to surround it with double quotes like this: ."foo$", or else .["foo$"].

Otherwise the statement is not correct. A number is not a special character.

**Comment by pkoppstein** [comment]
Sure.  By all means reopen or create a new issue, or better yet, submit a PR :-)

**Comment by tessus** [comment]
Sure. Which `manual.yml` do I have to change? The one in `docs/content/manual` or `docs/content/manual/v1.6` or all of them?

**Comment by wtlangford** [comment]
> Sure. Which `manual.yml` do I have to change? The one in `docs/content/manual` or `docs/content/manual/v1.6` or all of them?

All of them is probably the right answer. This describes functionality that hasn't really changed across versions, so an update to the docs for all of them is a good idea. (the versioned variants update the version-specific web docs).
At minimum, it should be the one in `docs/content/manual`, though, as that's the "primary" documentation file and is used to build the manpage and https://stedolan.github.com/jq/manual

No need to do any of the building, just a change to the `.yml` is enough. I'll find some time shortly after to refresh the site itself.

**Comment by tessus** [comment]
Thanks for the info. Done.
