### ISSUE TITLE
Output of command `echo 5 | jq length` is "5"

### ISSUE THREAD

**Issue by Georg-M** [stedolan/jq#1950]
If this is normal behavior, or it is known issue, please close
```
$ echo 5 | jq length ; echo $?
5
0
```
```
$ jq --version
jq-1.5
$ cat /proc/version
CYGWIN_NT-10.0-17763 version 3.0.7-338.x86_64 (corinna@calimero) (gcc version 7.4.0 20181206 (Fedora Cygwin 7.4.0-1) (GCC) ) 2019-04-30 18:08 UTC
```

**Comment by lbussy** [comment]
Standard conventions dictate return 0; as a successful execution of process with ZERO errors.  In other words the 0 as the return value ($? is return value of the previous command) means the command was successful.

**Comment by Georg-M** [comment]
Sorry, I meant something different opening this issue
1. Output "5" is incorrect for given command
2. Execution shouldn't be successful, since JSON format is not correct

But your particular statement is correct, though

**Comment by wtlangford** [comment]
> Output "5" is incorrect for given command

`length` is defined to return absolute value for numbers: https://github.com/stedolan/jq/blob/master/src/builtin.c#L442-L443

> Execution shouldn't be successful, since JSON format is not correct

Not sure what isn't correct about your JSON format. Your input is the json value `5`, which is a number.

**Comment by Georg-M** [comment]
Sorry, maybe this is my misunderstanding
I believed that command `length` returns number of sub-members (?)
and all JSON files are objects or arrays ({...} or [...])
Most probable, I was wrong, please close this ticket

**Comment by proceau** [comment]
most correct it's

echo '"12345"' | jq length
5

"12345" it's json valide for jq
