### ISSUE TITLE
jq-solaris11-64 responding with error

### ISSUE THREAD

**Issue by gopurx** [stedolan/jq#1953]
**Describe the bug**
Downloaded jq-solaris11-64 from https://github.com/stedolan/jq/releases/download/jq-1.4/jq-solaris11-64, any command with this binary is throwing error:
-ksh: ./jq: ./jq: cannot execute [Invalid argument]

**To Reproduce**
running standard command to find version:

./jq --version

**Expected behavior**
atleast version should be displayed

**Environment (please complete the following information):**
 - Oracle Solaris 11.3 SPARC
 - jq 1.4

**Additional context**

**Comment by wtlangford** [comment]
```
$ file jq-solaris11-64
jq-solaris11-64: ELF 64-bit LSB executable, x86-64, version 1 (Solaris), dynamically linked, interpreter /usr/lib, with debug_info, not stripped
```
The issue is that the binary is compiled for x86-64 Solaris, and yours is SPARC. I'd recommend either running `pkgutil -i jq` to install it, or to compile jq from source yourself (and get a more recent version! jq 1.4 is quite old)

**Comment by gopurx** [comment]
Do we have instructions on how to compile code to generate a new binary? like dependencies needed and commands to execute

**Comment by wtlangford** [comment]
The README at the root of the project has information about the compilation dependencies and how to build from source.
I'd recommend grabbing the source tarball from here: https://github.com/stedolan/jq/releases/tag/jq-1.6 (get the one named `jq-1.6.tar.gz` or `jq-1.6.zip`- the github-provided assets require more work to set up)
Then just follow the instructions in the README for building without bison/flex

**Comment by gopurx** [comment]
running "./configure --with-oniguruma=builtin --disable-maintainer-mode" receiving below error

configure: error: no acceptable C compiler found in $PATH

Do we need to have C compiler for this? Also, what else commands to be executed

**Comment by pkoppstein** [comment]
> Do we need to have C compiler for this

Yes.  For more information about installation, please consult the following:

* https://stedolan.github.io/jq/download/
* https://github.com/stedolan/jq/wiki/Installation
* https://github.com/stedolan/jq/wiki/FAQ#installation
