### ISSUE TITLE
`fromstream(inputs)` always lose the first property

### ISSUE THREAD

**Issue by jjqq2013** [stedolan/jq#1956]
**Describe the bug**
`fromstream(inputs)` filter always lose the first property

**To Reproduce**
```
jq --stream -c <<EOF
{
  "status": 200,
  "message": "OK"
}
EOF
```
result:
```
[["status"],200]
[["message"],"OK"]
[["message"]]
```

but when convert it back to json, it will lose the first property "status"!
```
jq "fromstream(inputs)" <<EOF
[["status"],200]
[["message"],"OK"]
[["message"]]
EOF
```
result
```
{
  "message": "OK"            ####### where is the "status" property?
}
```

If I insert something ahead, then it works
```
jq "fromstream(inputs)" <<EOF
""
[["status"],200]
[["message"],"OK"]
[["message"]]
EOF
```
result:
```
{
  "status": 200,
  "message": "OK"
}
```

**Expected behavior**
convert a json to stream and convert back to json should produce same json as the original one.

**Environment (please complete the following information):**
 - OS and Version: Linux Ubuntu Bionic
 - jq version: jq-1.5-1-a5b5cbe

**Additional context**

**Comment by pkoppstein** [comment]
If you use `inputs`, then in general you should use the -n command-line option; otherwise, jq will automatically read the first JSON entity so that `.` has an initial value.

**Comment by wtlangford** [comment]
Unless you otherwise tell jq not to, it passes the first json value in your
input stream to your program. Your program, however, is discarding that.
You'll need to pass the -n flag to jq, and it will pass null to your
program as the initial value, and then input/inputs will work as you expect.

**Comment by jjqq2013** [comment]
thank you all! It works fine with `-n` option, 
```
echo '{"status":200, "message": "OK"}' | jq --stream -c . | jq 'fromstream(inputs)' -n -c
```
->
```
{"status":200,"message":"OK"}
```
