### ISSUE TITLE
`fromstream(inputs)` does not output result until it read `[["anything"]]` or `[[any_number]]`

### ISSUE THREAD

**Issue by jjqq2013** [stedolan/jq#1957]
**Describe the bug**

**To Reproduce**
```
cat <<EOF | jq 'fromstream(inputs)' -n
[["L1_key","L2_key"],"L2_value"]
[[0]]
EOF
```
and
```
cat <<EOF | jq 'fromstream(inputs)' -n
[["L1_key","L2_key"],"L2_value"]
[[""]]
EOF
```
will both output 
```
{
  "L1_key": {
    "L2_key": "L2_value"
  }
}
```

But if I omit the last meaningless `[[0]]` or `[[""]]`, then it does not work
```
cat <<EOF | jq 'fromstream(inputs)' -n
[["L1_key","L2_key"],"L2_value"]
EOF
```
will output nothing.

**Expected behavior**
do the stream-to-json conversion when input ends, it should output
```
{
  "L1_key": {
    "L2_key": "L2_value"
  }
}
```

**Environment (please complete the following information):**
 - OS and Version: Linux Ubuntu Bionic
 - jq version jq-1.5-1-a5b5cbe

**Additional context**

**Comment by wtlangford** [comment]
This has to do with how the stream format works, and I recommend reading https://stedolan.github.io/jq/manual/#Streaming for a bit more information.

In short, though, the format expects a sequence of values like this:
```
[["L1_key", "L2_key"], "L2_value"] // the path `.L1_key.L2_key` has the value "L2_value"
[["L1_key", "L2_key"]] // Done with the path `.L1_key.L2_key`
[["L1_key"]] // Done with the path `.L1_key`
```
Where an array with two values sets a path, and an array with one value indicates that we're exiting an object or an array.

Your original input doesn't indicate to `fromstream` that you're exiting the inner object (or the outer one, for that matter), so it doesn't think it should be emitting a value.

Streams are notably difficult to work with, so I'd recommend playing around with `tostream` on various values to better understand how they work.

**Comment by jjqq2013** [comment]
thank you for your explanation. 
It seems does not make sense that waiting for 
```
[["L1_key", "L2_key"]] // Done with the path `.L1_key.L2_key`
[["L1_key"]] // Done with the path `.L1_key`
```
before EOF.
