### ISSUE TITLE
How to set initial value for the while loop in jq?

### ISSUE THREAD

**Issue by fengnex** [stedolan/jq#1963]
As said in the topic, how to set initial value for the while loop in jq?
It's related to business requirement.

**Comment by pkoppstein** [comment]
Here's an implentation of `range/2` using `while` that answers the question:
```
def range($init; $upto):
  $init | while(. < $upto; . + 1);
```

Incidentally, the best way to understand `while` and how to use it is to study its def:
```
def while(cond; update):
     def _while:
         if cond then ., (update | _while) else empty end;
     _while;
```

**Comment by fengnex** [comment]
@pkoppstein Thank you very much.
I have verified that the results are in line with expectations!
