### ISSUE TITLE
changes based on select but print all

### ISSUE THREAD

**Issue by Heiko-san** [stedolan/jq#1966]
Sorry for opening an issue for this, but I can't seem to find an answer even after hours of googling and trial&error.

I have a json similar to this (aws tags json)
```
{
  "TagSet": [
    {
      "Value": "val1",
      "Key": "key1"
    },
    {
      "Value": "val2",
      "Key": "key2"
    }
  ]
}
```
I further have the following jq snipppet which does almost what I want
```
jq '.TagSet[] | select(.Key=="key1").Value = "foo"'
```
output:
```
{
  "Value": "foo",
  "Key": "key1"
}
{
  "Value": "val2",
  "Key": "key2"
}
```
So what I want is to replace the Value of a given Key, but in the end the whole json should be printed.

Desired output:
```
{
  "TagSet": [
    {
      "Value": "foo",
      "Key": "key1"
    },
    {
      "Value": "val2",
      "Key": "key2"
    }
  ]
}
```
I can't seem to find a snippet that does the trick.
Any help is appreciated.

**Comment by Peter42** [comment]
`setpath(path(.TagSet[] | select(.Key=="key1") | .Value); "foo")` should do the trick.
https://jqplay.org/s/y6YWdlXfl8

No warranty that this is the best one.

**Comment by Peter42** [comment]
Ok, I just found a better one: add parenthesis :smile: probably to obvious to try.
`(.TagSet[] | select(.Key=="key1")).Value = "foo"`
https://jqplay.org/s/aWWN_xVzpD

**Comment by Heiko-san** [comment]
cool thanks :)
