### ISSUE TITLE
preserve state between input values, or how smart is --slurp?

### ISSUE THREAD

**Issue by georgir** [stedolan/jq#197]
As things are now, we can only process each input individually, we can not implement any sort of dependencies or preserved state between processing of separate input values.
For example we can not do even trivial things like skip every even input, etc...
Some sort of variable assignment that is not scoped just for the next chained subfilter but instead acts as a global may be nice to have.

For subfilters this can more or less be accomplished with collecting values in an array and running reduce on it, but for the topmost filter I do not see any way, except using `--slurp` option.

So if we use `--slurp`, I wonder, does it always buffer all the inputs in an array? Or is it smart enough to rather give us something rather like a generator or iterator or wossname? I.e. if we run a reduce or iterate on it, can it still read inputs one by one and keep its memory usage low?

The same question goes for the array collector `[...]`, does it always cause all elements to be accumulated or is it more like a generator or iterator or wossname if it is followed by some chain that only consumes its values one by one? Yep, I know `[...]|.[]` might be the stupidest thing on earth, but `[...]|reduce...` probably has valid uses.

**Comment by nicowilliams** [comment]
Fixed by the addition of `inputs`.
