### ISSUE TITLE
chocolatey - publish v1.6

### ISSUE THREAD

**Issue by mjarosie** [stedolan/jq#1975]
Are there any plans on releasing jq v1.6 on chocolatey? Currently it's at version 1.5: https://chocolatey.org/packages/jq

**Comment by wtlangford** [comment]
We don't manage the jq packages in different package systems (else we'd go insane).

I'm not super familiar with chocolatey, but I'd recommend reaching out to the package's maintainer, or looking to see what chocolatey's process is for updating packages

**Comment by mjarosie** [comment]
Previous version was resolved as part of issue #920 I see that it was (and still is) managed by @svnpenn (now I think @cup), but the link to the repository is dead: https://github.com/svnpenn/p/tree/master/jq

I've contacted the maintainer through chocolatey website :+1:

**Comment by cup** [comment]
at all

I am not interested in Chocolatey anymore, although I still use JQ. If anyone want to take over maintenance let me know. Else dont expect Choco JQ updates any more.

**Comment by mjarosie** [comment]
I can take over if you're fine with it. I've written an email to you.

**Comment by mjarosie** [comment]
I've just submitted the updated version of the package: https://chocolatey.org/packages/jq/1.6

It still requires moderators approval. I'll close this issue when the new version will be officially published.

**Comment by mjarosie** [comment]
Package was approved by moderator and now offers v1.6 by default. I'm closing the issue. Thanks!
