### ISSUE TITLE
Feature request: Extract JSON from HTML files

### ISSUE THREAD

**Issue by forthrin** [stedolan/jq#1980]
Let me know if this is out of scope, and if there is another tool that does this.

Also, with 500 open issues the project seems swamped, but here goes anyway:

Feature request:

- Possibility to extract JSON objects from HTML files.
- Replace inline functions in the JSON objects with NULL.
- Other conversion necessary to make the JSON objects valid.

This would be VERY handy for a number of projects that extract JSON from HTML pages.

**Comment by pkoppstein** [comment]
I doubt that jq will ever include an HTML parser, not least because there are tools such as `pup`, which not only plays nicely with jq, but is inspired by it:

https://github.com/ericchiang/pup

**Comment by forthrin** [comment]
I had the feeling a tool like this would exist, I just never found it. Thanks a lot for the tip! Add this reference to the FAQ if you have one, ie. "Q: Does jq parse HTML? A: No, but check out pup!"

**Comment by pkoppstein** [comment]
For the record, the jq FAQ page is part of the project wiki, and it has this Q&A:

     𝑸: How can I use jq to process HTML?

     A: First convert the HTML to JSON, e.g. using pup (https://github.com/ericchiang/pup) or hq (https://github.com/rbwinslow/hq).

**Comment by forthrin** [comment]
You thought of everything :) I was too quick to post a feature request. Thanks for taking the time anyway, and these tools will make my life easier!

**Comment by forthrin** [comment]
I forgot to get a clarification on whether there is (or could be) support for replacing inline function definitions inside JSON data with NULL, or alternatively if you have a relatively simple regular expression that does this for any JSON. (I currently have to write brittle special cases each time.)
