### ISSUE TITLE
Positional `--args` fail when first character is `-`

### ISSUE THREAD

**Issue by ohhorob** [stedolan/jq#1986]
**Describe the bug**
I'm using the `--args` option to provide a list to my program. This works just fine unless one of the items in the list begins with "-".

```
$ jq '$ARGS.positional' --args "test" "foo" < sequence.json
[
  "test",
  "foo"
]
```
**To Reproduce**
```
$ jq '$ARGS.positional' --args "test" "-foo" < sequence.json
jq: Unknown option -foo
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```
**Expected behavior**
```
$ jq '$ARGS.positional' --args "test" "-foo" < sequence.json
[
  "test",
  "-foo"
]
```
**Environment (please complete the following information):**
 - macOS
 - jq 1.6 from homebrew

```
$ brew info jq
jq: stable 1.6 (bottled), HEAD
Lightweight and flexible command-line JSON processor
https://stedolan.github.io/jq/
/usr/local/Cellar/jq/1.6 (18 files, 1MB) *
  Poured from bottle on 2018-12-14 at 09:31:19
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/jq.rb
==> Dependencies
Required: oniguruma ✔
```

**Additional context**

**Comment by alice-sawatzky** [comment]
This is normal but unintuitive behavior: most standard CLI parsers interpret strings starting with `-` to be flags. adding `--` as an arg instructs the parser to not parse anything to the right of `--` as an arg.

Your reproducer: (input redirection replaced with `-n` for simplicity)
```
% jq -n '$ARGS.positional' --args "test" "-foo"
jq: Unknown option -foo
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```
fix:
```
% jq -n '$ARGS.positional' --args -- "test" "-foo"
[
  "test",
  "-foo"
]
```
This is a standard behavior of a lot of CLI programs, but it will would be helpful if the docs mentioned this, given the relative obscurity of the behavior.

**Comment by ohhorob** [comment]
Thanks. I'll try and get a PR going for an update to the docs.
