### ISSUE TITLE
Unexpected null value in output

### ISSUE THREAD

**Issue by oneohthree** [stedolan/jq#1987]
**Describe the bug**
I'm getting an unexpected null value in jq output.

```
null
/XAMPP Windows/7.3.9/xampp-windows-x64-7.3.9-0-VC15-installer.exe
```

**To Reproduce**

```bash
curl -s https://sourceforge.net/projects/xampp/best_release.json | jq -r '.[].windows.filename'
```

**Expected behavior**
The output should be `/XAMPP Windows/7.3.9/xampp-windows-x64-7.3.9-0-VC15-installer.exe`

**Environment (please complete the following information):**
 - OS and Version: Debian GNU/Linux 8.11
 - jq version: jq-1.4-1-e73951f

**Comment by wtlangford** [comment]
The structure of that file you're curling looks like this:
```
{
  "release": {
    // this object doesn't have a windows key
  },
  "platform_releases": {
    "windows": { ... },
    "mac": { ... },
    "linux": { ... },
  }
}
```

Using `.[]` on an object produces a stream of all the values. You then look for a `.windows.filename` on each of those. That path doesn't exist on the object in the `resources`, so you get a `null`.

I'm not familiar with that particular json, but if the `releases` key isn't supposed to have a `.windows`, then you should change your jq program to `.platform_releases.windows.filename`

**Comment by oneohthree** [comment]
Thanks a lot for the observation. I didn't realize of the structure.
