### ISSUE TITLE
Relatively long input when using -r puts 0a in 'wrong' location

### ISSUE THREAD

**Issue by dovholuknf** [stedolan/jq#1991]
**Describe the bug**
Relatively long input used with -r will cause jq to put 0a in a strange place.

**To Reproduce**

    this shows the 0a in the wrong location:
    echo "{\"longstring\": \"___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________\"}" | jq -r .longstring | hexdump | tail -2
    0000160 5f5f 5f5f 5f5f 5f5f 5f5f 0a5f
    000016c

    this is one character shorter and shows an 0a at an expected location (the end)
    echo "{\"longstring\": \"__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________\"}" | jq -r .longstring | hexdump | tail -2
    0000160 5f5f 5f5f 5f5f 5f5f 5f5f 000a
    000016b

Notice the `0a` is misplaced in the first example. This causes a lot of problems with data that needs to be decoded like base64 etc.

**Expected behavior**
I would expect the 0a to not even be injected in this example - or it should be injected at the very end of the line.

**Environment (please complete the following information):**
 - Windows subsystem for Linux - ubuntu: jq-1.5-1-a5b5cbe
 - Mint Linux - jq-1.5-1-a5b5cbe (ubuntu variant)

**Additional context**
This is a strange issue to search for a bug report for. hopefully it's not a dupe - I didn't find one that was exactly the same. This one is similar https://github.com/stedolan/jq/issues/1173

**Comment by wtlangford** [comment]
I can't reproduce this on jq 1.6- can you try updating to that and see if you still have the issue?

**Comment by wtlangford** [comment]
Finally got back around to this-

This looks like it's actually a behavior of hexdump attempting to group multiple bytes into 16-bit words and assuming an endianness for them.
Piping the output into `hexdump -C` has the same behavior as that of `xxd`, which outputs `5f0a` for the last two bytes.


The `0d5f 000a` you're seeing on windows is actually this in the original byte order: `5f 0d 0a [00]`, (where the `00` isn't actually present in the file and is added by hexdump) and is just a CRLF line ending on windows.

**Comment by dovholuknf** [comment]
Shiver me timbers - I see what you're saying... I'm really sorry about that :(

There's still something odd going on with my side because we have a process that does exactly this but tries to decode the data after being pulled out with `jq`. At some point the scripts we had (using just `jq -r` and a redirect to file) started to indicate a checksum mismatch so I have moved it over to use `-j` to avoid the extra `0a`.

Sorry to send you on this tanget :(
