### ISSUE TITLE
Merge json objects/files

### ISSUE THREAD

**Issue by estahn** [stedolan/jq#200]
Is there a way to merge to json inputs?

`test.json`:

``` json
{"title": "Frist psot", "author": "Anonymous Coward"}
```

`test2.json`:

``` json
{"title2": "A well-written article", "author2": "Person McPherson"}
```

Command:

``` bash
$ jq "." test.json test2.json
```

Output:

``` json
{
  "author": "Anonymous Coward",
  "title": "Frist psot"
}
{
  "author2": "Person McPherson",
  "title2": "A well-written article"
}
```

Expected Output:

``` json
{
  "author": "Anonymous Coward",
  "title": "Frist psot",
  "author2": "Person McPherson",
  "title2": "A well-written article"
}
```

**Comment by chancez** [comment]
This doesn't recursively merge because `add` uses `+` rules, not `*` though?

**Comment by MuffintopSpeedos** [comment]
@chancez,

It works at the root level of the object and in the case of an array, it will take the objects from each array and return a new array with all of the objects. 

Real-life example: I have 8 files and each are arrays of objects like:
```
[
    {object},
    {object},
    {object},
    {object},
    ...
]
```

Each has a different number of objects:
```
$ ls -1 *.json | while read f; do echo "=> $f"; jq '. | length' $f; done
=> A.json
5899
=> B.json
100000
=> C.json
2919
=> D.json
55015
=> E.json
17432
=> F.json
100000
=> G.json
5534
=> H.json
100000
```

Merging took less than 60 seconds on my busy MacBook Pro to wait until all input streams are read, merge arrays, and pretty-print a sorted output: 
```
$ time jq -Ss 'add' signalflow_metadata_raw-ish_objects.* > merged.json
jq -Ss 'add' signalflow_metadata_raw-ish_objects.* > merged.json  48.40s user 2.54s system 98% cpu 51.758 total
```

The merged JSON is a single array with all of the objects: 
```
$ jq '. | length' merged.json
386799
```

Starting with a base object and then reading all of the input streams will result in that base object being an array with each file's array being added to the base object -- that results in an array of 8 arrays:
```
$ jq -Ss '.' signalflow_metadata_raw-ish_objects.* > merged.json
$ jq '. | length' merged.json
8
```

And that would then look like: 
```
[
    [
        {object},
        {object},
        ...
    ],
    [
        {object},
        {object},
        ...
    ],
    [
        {object},
        {object},
        ...
    ],
    [
        {object},
        {object},
        ...
    ]
]
```

**Comment by expelledboy** [comment]
Can the jq gods assist me in merging a slurp?

Say for example merging deps and dev deps in package.json files. I can do it over multiple runs:
```
	jq -s 'map_values(.devDependencies) | add | { devDependencies: . }' \
		./packages/*/package.json > .docker/devDependencies.json
	jq -s 'map_values(.dependencies) | add | { dependencies: . }' \
		./packages/*/package.json > .docker/dependencies.json
	jq -s '. | add' .docker/*.json > .docker/package.json
```
