### ISSUE TITLE
Feature Request: Option to behave like `cat` on json parse error

### ISSUE THREAD

**Issue by MatrixManAtYrService** [stedolan/jq#2006]
I frequently use jq to parse responses from http requests and forward the necessary data along to drive some action, like so:

```
for endpoint in foo bar baz
do
    curl $host/$endpoint | jq '.get.the.data' | some_action
done
```

Every now and then, something goes wrong with the `curl` and I get "Error 404" instead of valid json.  `jq` turns this into "parse error: Invalid numeric literal at line 1, column 6" and hides the underlying error.  This makes it harder to understand what's wrong.

-----
Current behavior:

    ❯ for input in '{"foo":"bar"}' '["baz", "qux"]' 'Error 404'
    do
       echo $input | jq .
    done

        {
          "foo": "bar"
        }
        [
          "baz",
          "qux"
        ]
        parse error: Invalid numeric literal at line 1, column 6

Behavior with the proposed flag:

    ❯ for input in '{"foo":"bar"}' '["baz", "qux"]' 'Error 404'
    do
       echo $input | jq --cat-on-error .
    done

        {
          "foo": "bar"
        }
        [
          "baz",
          "qux"
        ]
        Error 404

Thanks for considering this feature request, and thanks for maintaining jq, it's awesome.

**Comment by plambert** [comment]
Something like this might be what you need?

```bash
#!/usr/bin/env bash
jq-or-cat() {
  local tempfile opt filter
  tempfile="$(mktemp)" || exit $?
  if jq "$@" > "$tempfile"; then
    cat "$tempfile"
  else
    while [[ $# -gt 0 ]]; do
      opt="$1"; shift
      case "$opt" in
        --arg | --argjson | --slurpfile | --argfile ) shift 2 ;;
        --indent | -f | --from-filename | -L ) shift ;;
        --version | --seq | --stream | --slurp | -s | --raw-input | -R | --null-input | -N | --compact-output | -c | --tab | --color-output | -C | --monochrome-output | -M | --ascii-output | -a | --unbuffered | --sort-keys | -S | --raw-output | -r | --join-output | -j | --exit-status | -e ) : "do nothing" ;;
        --args | --jsonargs ) shift "$#" ;; # these consume all remaining entries
        --run-tests ) shift; [[ $# -eq 0 ]] || { printf 1>&2 '\e[31m%s: %s: expected 0 or 1 arguments, no more\e[0m\n' "$0" "$opt"; exit 1; } ;;
        -* ) printf 1>&2 '\e[31m%s: %s: unknown option\e[0m\n' "$0" "$opt"; exit 2 ;;
        * ) if [[ -z "$filter" ]]; then
              filter="$opt"
            else
              cat "$opt"
            fi
            ;;
      esac
    done
  fi
}

if [[ $# -gt 0 ]]; then
  jq-or-cat "$@"
fi

```

**Comment by MatrixManAtYrService** [comment]
Thanks @plambert,  I hadn't thought to approach it from the bash side (which is weird, I usually think to approach _everything_ from the bash side).  I had some trouble with your script, I was still seeing the jq error:

```
❯ echo 'doofus' | ~/.local/bin/jq-or-cat '.'
parse error: Invalid numeric literal at line 2, column 0
```

But armed with the idea, I wrote something similar that is working for me:
```
#!/usr/bin/env bash

if [[ $# -eq 0 ]]
then
    jq
    exit 0
fi

INPUT=$(mktemp)
cat - 1> $INPUT

QUERY=$(mktemp)
echo "$@" > $QUERY

OUTPUT=$(mktemp)

if cat $INPUT | jq "$@" > "$OUTPUT" 2>/dev/null
then
    cat "$OUTPUT"
else
    cat "$INPUT"
fi
```
You're an inspiration!

This will never bother _me_ again, so I won't cry if somebody closes the issue.  Although for what it's worth, I still think it would be a reasonable addition to the jq interface.

**Comment by nicowilliams** [comment]
I think we have to say no to this.  The problem is that while "cat on parse error" makes some sense if the jq program is `.`, it doesn't make sense in any other case.

A bigger problem is that jq would have to cache the entire input text in case the parser eventually fails.  Wrapping jq with a script as above uses the filesystem to do that caching, which is better.
