### ISSUE TITLE
What should '. |= try . catch .' do in jq 1.6, and why is it different from jq 1.5?

### ISSUE THREAD

**Issue by sshine** [stedolan/jq#2011]
**Describe the bug**
Unless `|=` in combination with `try`-`catch` have changed semantics, this is probably a bug?
```
$ jq-1.5 '. |= try . catch .' <<< 1
1

$ jq-1.6 '. |= try . catch .' <<< 1
{
  "__jq": 0
}
```

*Update:* I understand from #658 that `{"__jq": 0}` is some internal control mechanism.

**To Reproduce**
See above or visit https://jqplay.org/s/M_RpdNHvHF for jq 1.6.

**Expected behavior**
Unless I'm mistaken, this should return `1` in both versions.

Note that neither `. |= .` nor `try . catch .` alone produce this effect.

**Environment (please complete the following information):**
 - jq 1.5 version: Ubuntu Linux 18.04
 - jq 1.6 version: https://jqplay.org/

**Additional context**
Discovered here:

https://stackoverflow.com/questions/58879588/jq-try-catch-goes-directly-to-catch-even-when-no-error

**Comment by wtlangford** [comment]
This... does seem incorrect. I'll see what I can figure out.

**Comment by wtlangford** [comment]
The behavior change would have been introduced here: bd7b48c1b97063bd21aa7e264e61ea3350145486

It's a weird interaction of nesting labels and a try/catch that trips up a bug in the way we generate code for the `catch` handler: https://github.com/stedolan/jq/blob/master/src/compile.c#L1041

The issue is that when we look for the internal errors jq uses to handle certain types of control flow jumps (in particular around labels), we intend to check for the _type_ of the error to be an object, but instead we compare the error to "object". You can see this by running `try error("object") catch .`, which attempts to index into that string to test if we've got an internal error. That results in the internal error getting returned as the value to you.

I'll push a fix later tonight.

**Comment by wtlangford** [comment]
I pushed e74eab8, which fixes this. Thanks for the report!

**Comment by pkoppstein** [comment]
@wtlangford - Great work as always.  Thanks.  

I thought it was time to recreate an instance of jq "from scratch" and sure enough ran into some issues.  After the first failure, I installed pipenv (`brew install pipenv`), and reran `make`, which failed as follows:
```
✔ Successfully created virtual environment! 
Virtualenv location: /Users/peter/.local/share/virtualenvs/docs-utiv-7IS
Traceback (most recent call last):
  File "build_manpage.py", line 4, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
make[2]: *** [jq.1] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
I suppose I'm supposed to install somehow but pip3 says it's already installed:
```
pip3 install lxml
Requirement already satisfied: lxml in /usr/local/lib/python3.7/site-packages (4.4.1)
```

Maybe I need to dig deeper into the (revised?) installation instructions, but I'm disappointed that what used to be a painless process has seemingly become somewhat fraught.  Am I missing something?

**Comment by wtlangford** [comment]
@pkoppstein- yeah, that's an issue I'm aware of. It also prevents people from doing `brew install jq --HEAD`.
Essentially, I didn't set up that whole ruby replacement the way I meant to. Can you try the branch in #1995 and see how it works for you? It changes a few things about how the build process works and only requires a python environment if you make changes to the manpage yml.

**Comment by pkoppstein** [comment]
@wtlangford - Thanks --  `make` completed without too much fuss. For reference, `./jq --version` reports:

jq-1.3-894-ga1f1231

If the dependencies on Ruby have been removed, it seems odd to see:
```
checking for Ruby dependencies... configure: WARNING: The following gems are missing
 * rake (10.4.2)
 * i18n (0.7.0)
 * json (1.8.3)
 * minitest (5.8.0)
 * thread_safe (0.3.5)
 * tzinfo (1.2.2)
 * activesupport (4.2.3)
 * addressable (2.3.8)
 * builder (3.2.2)
 * launchy (2.4.3)
 * liquid (3.0.6)
 * maruku (0.7.2)
 * rack (1.6.4)
 * sass (3.4.16)
 * rack-protection (1.5.3)
 * tilt (2.0.1)
 * sinatra (1.4.6)
 * watch (0.1.0)
 * yui-compressor (0.12.0)
 * bonsai (1.4.9)
 * hpricot (0.8.6)
 * mustache (0.99.8)
 * rdiscount (2.1.8)
 * ronn (0.7.3)
Install missing gems with `bundle install`
*****************************************************************
*  Ruby dependencies for building jq documentation not found.   *
*  You can still build, install and hack on jq, but the manpage *
*  will not be rebuilt and some of the tests will not run.      *
*  See docs/README.md for how to install the docs dependencies. *
*****************************************************************
```
---

The other warning messages of interest are as follows:
```
In file included from src/builtin.c:157:
src/libm.h:163:10: warning: 'drem' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
LIBM_DDD(drem)
         ^
/usr/include/math.h:755:15: note: 'drem' has been explicitly marked deprecated here
extern double drem(double, double) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_9, __IPHONE_NA, __IPHONE_NA);
              ^
In file included from src/builtin.c:157:
src/libm.h:218:9: warning: 'gamma' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
LIBM_DD(gamma)
        ^
/usr/include/math.h:759:15: note: 'gamma' has been explicitly marked deprecated here
extern double gamma(double) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_9, __IPHONE_NA, __IPHONE_NA);
              ^
In file included from src/builtin.c:157:
src/libm.h:278:9: warning: 'significand' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
LIBM_DD(significand)
        ^
/usr/include/math.h:761:15: note: 'significand' has been explicitly marked deprecated here
extern double significand(double) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_9, __IPHONE_NA, __IPHONE_NA);
              ^
src/builtin.c:194:31: warning: implicit declaration of function 'lgamma_r' is invalid in C99 [-Wimplicit-function-declaration]
  jv ret = JV_ARRAY(jv_number(lgamma_r(jv_number_value(input), &sign)));
                              ^
4 warnings generated.
  CC       src/lexer.lo
src/lexer.c:1500:47: warning: comparison of integers of different signs: 'int' and 'yy_size_t' (aka 'unsigned long')
      [-Wsign-compare]
        if ((int) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.

```

**Comment by wtlangford** [comment]
That's... definitely not right. It shouldn't be running that at all, and
the necessary files shouldn't be present for it to be able to. Are you sure
you're on the right commit?

**Comment by pkoppstein** [comment]
@wtlangford: Whoops - I just let SourceTree clone the repo without checking which branch it was checking out.

So, after checking out the relevant version, things ran successfully for a while,
but then the dreaded 'lxml' dragon raised its fearsome head:
```
....
checking for Python dependencies... Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project…
...
✔ Successfully created virtual environment!
...
  GEN      jq.1
Traceback (most recent call last):
  File "build_manpage.py", line 4, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
make[2]: *** [jq.1] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by wtlangford** [comment]
I'm surprised that branch is trying to force you to regen the manpage- it's
supposed to use the prebuilt version unless you've modified manpage.yml.
What's your `git show` say for the current commit?

**Comment by pkoppstein** [comment]
@wtlangford - `git show` begins:

```
commit dd87c3b9d7acf4efaced0a8eccb534df82c6cf27 (HEAD -> fix-brew-head-build, origin/fix-brew-head-build)
Author: William Langford <wlangford@digitalocean.com>
Date:   Tue Oct 22 12:37:19 2019 -0400

    Rework pipenv requirement to be more relaxed
    
    Keep a cached copy of the man tests that we can use when no manpage
    changes are made. This allows automated systems that might not have
    easy access to a pipenv to build and run tests.
```
