### ISSUE TITLE
How to output ?

### ISSUE THREAD

**Issue by pooy** [stedolan/jq#2017]
`{
    "datetime":"2019-11-28T12:28:58.791+0800",
    "cmd":"get",
    "query":"[\"get\",[\"popup:1\"]]",
    "ms":"50.619840621948"
}`

How to output  'query' to json ?

**Comment by pkoppstein** [comment]
With the given input, `jq -r .query` produces valid JSON.

If that's not what you want, please follow the "minimal complete verifiable example" guidelines
at http://stackoverflow.com/help/mcve 

In any case, in future please post usage questions at https://stackoverflow.com/questions/tagged/jq

**Comment by pooy** [comment]
cool , very nice !  thanks!

**Comment by pooy** [comment]
> With the given input, `jq -r .query` produces valid JSON.
> 
> If that's not what you want, please follow the "minimal complete verifiable example" guidelines
> at http://stackoverflow.com/help/mcve
> 
> In any case, in future please post usage questions at https://stackoverflow.com/questions/tagged/jq

cool , very nice ! thanks!
