### ISSUE TITLE
Getting "too many open files" error

### ISSUE THREAD

**Issue by ezmiller** [stedolan/jq#2020]
**Describe the bug**

I'm getting an error related to "open files" when I try to use `jq`:
> jq:2: cannot duplicate fd 0: too many open files
> jq:2: write error: bad file descripto

**To Reproduce**
I get this error if I do `echo "{ foo: "foo" }" | jq '.'`:
```
> echo "{ foo: "foo" }" | jq '.'                
jq:2: cannot duplicate fd 0: too many open files
jq:2: write error: bad file descriptor
```
**Expected behavior**
I'd expect jq to parse the sample input as json.

**Environment (please complete the following information):**
 - OS X (10.14.6 (18G103))
 - jq version: 1.6

**Additional context**
```
> launchctl limit maxfiles                   
maxfiles    64000          524288
```

**Comment by wtlangford** [comment]
Can you try 

```sh
echo '{ foo: "foo" }' | jq '.'
```

jq doesn't really open files when you invoke it like this, so I wonder if it's a weird shell globbing thing happening.

**Comment by Alanscut** [comment]
@ezmiller 
You can try to change your data，such as:
```
echo '{"foo" : "foo"}' | jq '.'
```
because jq is a lightweight and flexible command-line JSON processor.

**Comment by nicowilliams** [comment]
I cannot reproduce this.  As @wtlangford explains, this really can't be the case.  Among other things, the string "cannot duplicate" does not appear in jq, nor does it call `dup(2)` nor `dup2(2)`, nor does it use `fcntl(2)` with `F_DUPFD`.  Therefore the error has to be from your shell.
