### ISSUE TITLE
stderr pipe to jq - reprint only

### ISSUE THREAD

**Issue by ax-ushakov-93** [stedolan/jq#2027]
Hello,

**Describe the bug**
My "pet" `go` application writes to `stder` stream some json for debuggin, but I cannot handle it with `jq`. Can someone help me to understand the issue?

All next stuff do not work. Data simply reprinted.

```sh
go-app | jq
go-app >&1 | jq
go-app >&1 | jq -C '.'
```

**To Reproduce**
Print some stuff to the stderr and pipe it to `jq`.

**Expected behavior**
JSON readed, parsed, and colorfully printed to the tty.

**Environment (please complete the following information):**
some modern `linux`

**Comment by pkoppstein** [comment]
jq reads from STDIN so, in the case that go-app only writes to STDERR, you would use 2>&1 along the lines of:

     go-app 2>&1 | jq .

If go-app also writes to STDOUT, you will have to apply some pipes-fu, which really has nothing to do with jq.  If you need further assistance, you might like to seek help at stackoverflow.com

**Comment by ax-ushakov-93** [comment]
Thanks. I was trying 2>&1 instead of `>&1`.

**Comment by pkoppstein** [comment]
Perhaps the following is closer to what you're looking for:

    go-app 2> >( jq . )
