### ISSUE TITLE
jq filter specific entries in an array

### ISSUE THREAD

**Issue by teryakii** [stedolan/jq#2029]
hi there,  i'll make this short.
This is what im dealin with

```
{
    "remote":  [
        {"name": "cast-1",
         "id": 1212
        },
        {"name": "cast-1",
         "id": 1214
        },
        {"name": "home-11",
         "id": 3212
        },
        {"name": "cast-3",
         "id": 3212
        }
    ]
}
```
my desired output is
```
 "cast-1": 1212 , 1214,
 "cast-3": 3212,
```

with my attempt, i only am able to output this

```
 "cast-1": 1214,
 "cast-3": 3212,
```

my code so far
```
cat newfile.json | jq  'reduce .remote[] as $v ({}; . + {"\($v.name)":$v.id})'  

```

Cant figure out to add the second id
any suggestions?

**Comment by pkoppstein** [comment]
> any suggestions?

Please ask usage questions such as this on stackoverflow.com with the jq tag:  https://stackoverflow.com/questions/tagged/jq

Also, please be explicit as to whether you want the output to be valid JSON (as the "my code" suggests) or not.

**Comment by teryakii** [comment]
> > any suggestions?
> 
> Please ask usage questions such as this on stackoverflow.com with the jq tag: https://stackoverflow.com/questions/tagged/jq
> 
> Also, please be explicit as to whether you want the output to be valid JSON (as the "my code" suggests) or not.

Oh thanks, i'm new to this, so i didnt really know where to ask for help :)
