### ISSUE TITLE
jq should preserve numeric types

### ISSUE THREAD

**Issue by jeenuv** [stedolan/jq#2034]
**Describe the bug**
`jq` meddles with numeric data type.

**To Reproduce**
```
$ echo '{"x": 1.0}' | jq -c
{"x": 1}
```

**Expected behavior**
The data type should be preserved in output as it was in input.

Certain JSON-processing libraries, when the they compare two JSON objects, they also compre the type. This means that JSON that had been processed through `jq`, even if it was a NOP, would have its type meddled, and therefore fail.

In the example above, input `float` data type is modified to an `int` type.

**Environment (please complete the following information):**
 - OS and Version: Linux
 - jq version: jq-1.5-1-a5b5cbe

**Comment by odnoletkov** [comment]
JSON only has unified 'number' data type. So the real problem in your case are these libraries not respecting the spec.

In practice, I think you can pipe all JSON inputs you have through jq before processing them with these libraries. That way all int/float convertions will be performed uniformly and won't affect equality inside the library.

**Comment by leonid-s-usov** [comment]
The latest master is clear from this problem. The merged [Decimal Number](#1752)  support preserves original precision of numbers if they weren't modified by some math function.

**Comment by wtlangford** [comment]
To clarify, we don't consider that behavior inherently a _problem_, so much as a _behavior_. To JSON (and our parser/generator), both `1.0` and `1` are valid encodings of the same value (the number "one").

That said, as @leonid-s-usov pointed out, the decimal number support should preserve your original formatting (so long as you don't do any math with the number), but I wouldn't strictly guarantee that behavior. To my mind, the point of the decimal number support is primarily to prevent issues surrounding IEEE754 double precision.
