### ISSUE TITLE
No mention of ".value" in the manual

### ISSUE THREAD

**Issue by behrangsa** [stedolan/jq#2037]
Maybe I am missing something here, but I can't find any mention of `.value` in the manual.

Looks like it is also a synonym of `.val`.

While is is very much obvious how to interpret it, it is worthwhile to dedicate a paragraph or two to `.key` and `.value` in the manual.

**Comment by pkoppstein** [comment]
> Maybe I am missing something here, but I can't find any mention of .value in the manual.

For jq, the main significance of keys named "value" is in connection with the `to_entries, from_entries, with_entries` family of functions, about which the manual says:
```
These functions convert between an object and an array of key-value pairs. If to_entries is passed an object, then for each k: v entry in the input, the output array includes {"key": k, "value": v}.
```

**Comment by behrangsa** [comment]
My bad!
