### ISSUE TITLE
How to escape '.' ? 

### ISSUE THREAD

**Issue by dbollaer** [stedolan/jq#204]
Hello,

Could please tell me how to escape '.'?

I already tried a few different approaches, but they all failed

examples:

 ./jq '.global".proxy.process.dns.in_flight"'

./jq '.global.proxy$process$dns$in_flight'

 ./jq '.global.proxy.process.dns.in_flight'

Thanks in advance

**Comment by rajendrasati** [comment]
Thanks iluchs for the solution. It worked
