### ISSUE TITLE
when keys  contain - (hyphen) in the name,jq can not deal with this situations

### ISSUE THREAD

**Issue by Alanscut** [stedolan/jq#2048]
**Describe the bug**

when keys  contain - (hyphen) in the name ,jq can not deal with this situations.

**To Reproduce**
```
root@os-001: echo '{"a-b":123}' | jq '.a-b'
jq: error: b/0 is not defined at <top-level>, line 1:
.a-b
jq: 1 compile error

```

**Expected behavior**
jq can deal with this situation

**Environment (please complete the following information):**
 - OS and Version: Ubuntu 18.04.1 
 - jq version : master branch

**Comment by itchyny** [comment]
Try `'.["a-b"]'`, jq can deal with this situation.

**Comment by itchyny** [comment]
`'."a-b"'` works too.

**Comment by Alanscut** [comment]
hi,@itchyny  
Thanks for your help, Beacause I'm a bit confused: why do key values need double quotes in this case, but keys in other cases don't need double quotes.For example:
```
root@os-001: echo '{"a_b":123}' | jq '.a_b'
123


```

**Comment by wtlangford** [comment]
The core of it is that `.a_b` parses as a single token, while `.a-b` parses as `<.a> <MINUS> <b>`.
The error you provided showcases this- it's looking for a 0-ary function named `b`.

More generally, any time a field doesn't match `/[A-Za-z_][A-Za-z0-9_]*/` (See https://github.com/stedolan/jq/blob/master/src/lexer.l#L124 for the definition of `FIELD` in the grammar), then you'll need to encase it in quotes. Notably, `."a-b"` will work, as will `.["a-b"]`

**Comment by Alanscut** [comment]
Thanks for  your help. @wtlangford

**Comment by huapox** [comment]
> `'."a-b"'` works too.

thx
