### ISSUE TITLE
Permission Denied Error

### ISSUE THREAD

**Issue by kingwoftam** [stedolan/jq#2057]
I installed jq on my Mac in Terminal using the command brew install jq, followed by an upgrade using the command brew upgrade jq. Both completed successfully without errors being reported.

I then tried to test jq by using the command 
curl -s "http://api.icndb.com/jokes/random" | jq '.value.joke'

However I just get the error as follows:
-bash: /usr/local/bin/jq: Permission denied

Am I missing something?

**Comment by NeuroWinter** [comment]
I am getting that issue too.
Running this version:
```
$ jq --version
jq-1.5-1-a5b5cbe
```

**Comment by xiaobai-pan** [comment]
hello @kingwoftam 
I execute the same command in a Windows environment and it works.
Is the environment variable not configured?
jq version: 1.6
```
Administrator@QXJJAOECR1Y7KIL MINGW64 ~/Desktop/jq
$ curl -s "http://api.icndb.com/jokes/random" | jq-win64.exe '.value'
{
  "id": 553,
  "joke": "China lets Chuck Norris search for porn on Google.",
  "categories": [
    "explicit"
  ]
}
Administrator@QXJJAOECR1Y7KIL MINGW64 ~/Desktop/jq
$ curl -s "http://api.icndb.com/jokes/random" | jq-win64.exe '.value.joke'
"In a tagteam match, Chuck Norris was teamed with Hulk Hogan against King Kong Bundy and Andre The Giant. He pinned all 3 at the same time."
```

**Comment by itchyny** [comment]
Please provide the output of `brew reinstall jq; which jq; ls -al `which jq`; jq --version`.

**Comment by MiChaelinzo** [comment]
Anyone find a solution?

**Comment by MiChaelinzo** [comment]
Anyone found a solution?

**Comment by sollyucko** [comment]
As a workaround, you should be able to run `chmod a+x /usr/local/bin/jq` (give all users execute permission for the file).

**Comment by neeraz-dt** [comment]
> Please provide the output of `brew reinstall jq; which jq; ls -al "$(which jq)"; jq --version`.

```
==> Downloading https://ghcr.io/v2/homebrew/core/jq/manifests/1.6-1
Already downloaded: /Users/neeraj/Library/Caches/Homebrew/downloads/fc2724606b6ebef1ba0db7d7ae84cfca1df8cfed9e58e3a8714413b3676935f7--jq-1.6-1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:7fee6ea327062b37d34ef5346a84810a1752cc7146fff1223fab76c9b45686e0
Already downloaded: /Users/neeraj/Library/Caches/Homebrew/downloads/de57802c1c3740b0761a664bea8c9f15347d4049295d0c81cd6368eda6b34953--jq--1.6.monterey.bottle.1.tar.gz
==> Reinstalling jq
==> Pouring jq--1.6.monterey.bottle.1.tar.gz
🍺  /usr/local/Cellar/jq/1.6: 18 files, 1.1MB
==> Running `brew cleanup jq`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
/usr/local/bin/jq
lrwxr-xr-x  1 neeraj  admin  23 Sep 15 13:38 /usr/local/bin/jq -> ../Cellar/jq/1.6/bin/jq
jq-1.6
```


I get this error even though the file exists
```
jq: Could not open 4: No such file or directory
```

**Comment by kingwoftam** [comment]
Closing as workaround provided did the trick
