### ISSUE TITLE
Incorrect documentation example for --stream

### ISSUE THREAD

**Issue by lily-commure** [stedolan/jq#2068]
The [manual](https://stedolan.github.io/jq/manual/#Invokingjq) says:

> * `--stream`:
        Parse the input in streaming fashion, outputting arrays of path
        and leaf values (scalars and empty arrays or empty objects).
        For example, `"a"` becomes `[[],"a"]`, and `[[],"a",["b"]]`
        becomes `[[0],[]]`, `[[1],"a"]`, and `[[1,0],"b"]`.

However, the second example is incorrect.  `jq --stream <<<'[[],"a",["b"]]'` actually produces
```
[[0],[]]
[[1],"a"]
[[2,0],"b"]
[[2,0]]
[[2]]
```

The manual's example ought to show the correct path for `"b"`, as well as the fact that `[<path>]` is used to indicate the end of an array in the stream output.

**Comment by Alanscut** [comment]
PR #2010 has resolved this issue.

**Comment by lily-commure** [comment]
Oops, this duplicates #1279
