### ISSUE TITLE
Can't have period in key

### ISSUE THREAD

**Issue by WillBeebe** [stedolan/jq#207]
Hi! My input looks like this:

{
  "results" : [
    {
        "some.key" : 3
    },
    {
        "some.key" : 4
    }
  ]
}

I'd like to be able to do this
./jq ".results.some.key" input

But I can't. I can't figure out how to access those keys, is this possible? Also, I cannot change the schema....

**Comment by paulkernfeld** [comment]
I ran into this, and in case it helps anyone:
- `.foo` is equivalent to `.["foo"]` (as noted above)
- `.foo.bar` is equivalent to any of:
    - `.["foo"]["bar"]`
    - `.foo["bar"]`
    - `.["foo"].bar`

**Comment by marianogappa** [comment]
Sorry for the bump. What about the case where you want to interpolate a key with a dot? i.e.

```
$ echo '[{"foo":2},{"foo":1}]' | jq -r '.[] | "\(.foo)"'
2
1
$ echo '[{"foo.bar":2},{"foo.bar":1}]' | jq -r '.[] | "\(.what do I put here???)"'
```

**Comment by nicowilliams** [comment]
@marianogappa For all non-ident-like keys use `.["whatever the key is goes here"]`.  Interpolation uses jq expressions, so

```
$ echo '[{"foo.bar":2},{"foo.bar":1}]' | jq -r '.[] | "\(.["foo.bar"])"'
```

**Comment by roccomuscaritolo-okta** [comment]
I think you can more with terraform output -json directly like this, without the need of a third party python library.

```sh
$ terraform output -json | jq -r ".quadrant.value.\"$QUAD.region\""
us-east-1
```

**Comment by IamGabrielWu** [comment]
I tried it many times.
How can i  get the vaule of "triggers.tekton.dev/triggers-eventid"
```
{
  "tekton.dev/pipeline": "cloudflare-worker-deploy-run-q7chs",
  "triggers.tekton.dev/eventlistener": "cloudflare-worker-pipeline-listener",
  "triggers.tekton.dev/trigger": "cloudflare-worker-deploy-trigger",
  "triggers.tekton.dev/triggers-eventid": "wbf6p"
}
```
here 's command i ran
```
tkn pipelinerun list --label triggers.tekton.dev/triggers-eventid=wbf6p -n tekton -o json | jq -r ".items[0].metadata.labels.[\"triggers.tekton.dev/triggers-eventid\"]"
```

**Comment by peterromfeldhk** [comment]
after escaping the double quotes it finally worked for me (not sure because of fish ⋊>)
`kubectl ... | jq -r '.data[\"nginx.conf\"]'`

**Comment by NarmathaSubramaniam21** [comment]
db.json
{
    "user.u1": {
      "name": "masteruser",
      "db_var": "db_var"
    }
}

$jqOutput = jq .["user.u1"].user db.json

jq: error: user/0 is not defined at <top-level>, line 1:
.[user.u1].user  
jq: 1 compile error
