### ISSUE TITLE
jq update value without quotes

### ISSUE THREAD

**Issue by gupta05** [stedolan/jq#2078]
I am using the below command below to update a value in json file
jq -c --arg a "$prestart_hook" '.["hooks"]["prestart"] = $a' x.json | tr -d '\' > "$tmp"

The result is something like this 
{"hooks":{"prestart":"{"path":"/proc/25629/exe","args":["libnetwork-setkey"]}{"path":"tmp","args":["abc","xyaa"]}"}}

I want the prestart value to be without the outermost double quotes "". And also comma between two path dictionary which are present in prestart. 
Any pointers appreciated. Tried -R but didnt help.

**Comment by gupta05** [comment]
i think --arg is adding the quotes. my value for the arg is dynamic so can't hardcode it.

**Comment by itchyny** [comment]
Please use --argjson.

**Comment by gupta05** [comment]
I used some sed to get the desired result. --argjson was complaining, i guess the input needs to be in some format.

**Comment by wtlangford** [comment]
For those who stumble upon this later, `--argjson` requires that the value you pass to it be a single JSON value. Your input had two json values in it. In that case, `--slurpfile` is the recommended flag to handle this, you just need to get your json values into a file first.

In bash-like shells, if you wanted to avoid writing a temporary file, you could use process substition and do something like:
```bash
jq -c --slurpfile prestart_hook <(echo "$prestart_hook") '.["hooks"]["prestart"] = $prestart_hook' x.json
```
