### ISSUE TITLE
New release of jq

### ISSUE THREAD

**Issue by Jamim** [stedolan/jq#2080]
Hello,

First of all, thank you for the great tool!

It would be great to have a new version of `jq` with recent improvements.
Is there a release planned for the near future?

Best regards,
Aliaksei

**Comment by flying-sheep** [comment]
As mentioned in #2082, https://github.com/stedolan/jq/milestone/10 is pretty far off still.

I think features like `-0` would come in handy a lot earlier for people.

**Comment by wtlangford** [comment]
This is being discussed in #2305, so closing this in favor of that issue
