### ISSUE TITLE
New 1.7 release proposal

### ISSUE THREAD

**Issue by WilliamTambellini** [stedolan/jq#2082]
jq 1.6 was released in nov 2018.
According to 
https://github.com/stedolan/jq/milestone/10
1.7 is far to be finished.
Any way to reduce the scope of 1.7 ? 
Kind

**Comment by luisdavim** [comment]
this has also been asked in #2080

**Comment by wtlangford** [comment]
This is being discussed in #2305, so closing this in favor of that issue
