### ISSUE TITLE
how to do?

### ISSUE THREAD

**Issue by zhaowengxing** [stedolan/jq#2089]
file:            {"a":1,"arr":[{"b":2,"c":3},{"b":4,"c":5}]}

The result I want is:
{"a":1,"b":2,"c":3}
{"a":1,"b":4,"c":5}
What shall I do?

jq -c '{a,b:.arr[].b,c:.arr[].c}'
get:
{"a":1,"b":2,"c":3}
{"a":1,"b":2,"c":5}
{"a":1,"b":4,"c":3}
{"a":1,"b":4,"c":5}
This is not what I want

**Comment by itchyny** [comment]
```
jq -c '{a} + (.arr[] | {b, c})' 
```

**Comment by zhaowengxing** [comment]
thank you very much!
