### ISSUE TITLE
processing invalid json file

### ISSUE THREAD

**Issue by aisk** [stedolan/jq#209]
I'm using jq to process some log files, and every line of the log file is a json object text.  
But little of them contain some invalide data of strings, when jq processes this lines, it got a "Abort" and exit with -1.
At last I modified jv_print.c, delete line 108 `assert(c != -1);`, skipped the invalid string failed. But I want to know is there any params to skip lines like this?

**Comment by rgeary1** [comment]
:+1:

**Comment by nicowilliams** [comment]
@aisk @joelnn @gaving @Downchuck @stedolan Closed with 89791a0, basically.  It's not *all* you might want, but it's as much as you're likely to get.  Basically, if you're willing to use the JSON text sequence (application/json-seq) MIME type then you can have jq tolerate invalid JSON texts by skipping to the next element in the JSON text sequence.  See the `--seq` option in master and in jq-1.5rc1.  This will be in jq-1.5, which is probably a couple of weeks away.

**Comment by nicowilliams** [comment]
See also #597.
