### ISSUE TITLE
How do I get multiple specified keys and their corresponding values from the object?

### ISSUE THREAD

**Issue by zhouhuihua526** [stedolan/jq#2120]
How do I get multiple specified keys and their corresponding values from the object?
E.g:
{
"Start": "true"
"end": [
    {"name": "yml", "good": false, "user": "w"},
    {"name": "XML", "good": true, "user": "s"},
    {"name": "json", "good": false, "user": "x"}
  ]
}
Expected results:
{"name": "yml", "user": "w"},
{"name": "XML", "user": "s"},
{"name": "json", "user": "x"}

**Comment by itchyny** [comment]
`jq -c ".end[] | { name, user }"`

**Comment by zhouhuihua526** [comment]
ok.thank you!!!

**Comment by zhouhuihua526** [comment]
If another map is nested in the array, how to get the key-value pairs of the map?
E.g:
{
"Start": "true"
"end": [
    {"name": "yml", "good": false, "user": "z", "sex": {"re": "zz"}},
       {"name": "XML", "good": true, "user": "w", "sex": {"re": "ww"}},
       {"name": "json", "good": false, "user": "s", "sex": {"re": "ss"}}
  ]
}
Expected results:
{"name": "yml", "user": "z", "re": "zz"},
{"name": "XML", "user": "w", "re": "ww"},
{"name": "json", "user": "s", "re": "ss"}

**Comment by itchyny** [comment]
`jq -c ".end[] | { name, user, re: .sex.re }"` or `jq -c ".end[] | { name, user, re: (.. | .re? // empty) }"`

**Comment by zhouhuihua526** [comment]
ok. thank you very much!!!

**Comment by zhouhuihua526** [comment]
After obtaining multiple specified keys and their corresponding values from the object, how do I add 8 hours to the value containing the time (UTC time)?
E.g:
{
"Start": "true"
"end": [
     {"name": "yml", "good": false, "user": "w", "time": "2020-05-14T09: 47: 52Z"},
     {"name": "XML", "good": true, "user": "s", time ":" 2020-05-14T09: 47: 53Z "},
     {"name": "json", "good": false, "user": "x", time ":" 2020-05-14T09: 47: 54Z "}
   ]
}
Expected results:
{"name": "yml", "user": "w", time ":" 2020-05-14T17: 47: 54Z "},
{"name": "XML", "user": "s", time ":" 2020-05-14T17: 47: 54Z "},
{"name": "json", "user": "x", time ":" 2020-05-14T17: 47: 54Z "}

**Comment by zhouhuihua526** [comment]
I tried to use fromdate + 8 hours to output, but the final execution failed
E.g:
jq -c ".end [] | {name, user, time | fromdate + 28800 | strftime ("% Y-% m-% dT% H:% M:% SZ ")}"

**Comment by zhouhuihua526** [comment]
Oh, I'm disturbed. I added a bracket. I successfully got my expectations. Thank you. I still have to try more.
