### ISSUE TITLE
Converting unix timestamps in milliseconds occurs Assertion failed!

### ISSUE THREAD

**Issue by WiVi71** [stedolan/jq#2123]
**Edit**

This bug was caused by too large a number. not strftime with "-R"
![millierror](https://user-images.githubusercontent.com/59140461/81765683-73ea3b80-950f-11ea-8964-c89558b9b1e6.PNG)

**To Reproduce**
```ECHO {"published_at": 1461625253393} | jq ".published_at/1000 | strftime(\"%Y-%m-%d\")"```
Converting unix timestamps in second works.
```ECHO {"published_at": 1461625253393} | jq ".published_at | strftime(\"%Y-%m-%d\")"```
But converting unix timestamps in milliseconds occurs unexpected type of error.

**Expected behavior**
jq should alart that the number is too big.

**Environment (please complete the following information):**
 - Jq-1.6-Windows10

---
![-R_ER](https://user-images.githubusercontent.com/59140461/81753617-23fb7c80-94ef-11ea-9fa0-1c01ecfc1e00.PNG)
Wrong jq command with -R options and strftime occurs "Assertion failed!"

**To Reproduce**
```echo {"updateTime":1589179644052} | jq -R "fromjson? | .updateTime | strftime(\"%B %d %Y\")"```

**Expected behavior**
Jq should print "compile error" or "syntax error" or something else.

**Comment by itchyny** [comment]
What's the result of `jq -n "1461625253393 | gmtime"`  ?

**Comment by WiVi71** [comment]
```jq -n "1461625253393 | gmtime"```
will print "jq: error (at <unknown>): errror converting number of seconds since epoch to datetime"

```jq -n "1461625253393/1000 | gmtime"```
will print
````
[
  2016,
  3,
  25,
  23,
  0,
  53.39299988746643,
  1,
  115
]

**Comment by itchyny** [comment]
Thank you.

**Comment by itchyny** [comment]
For a record, `echo '{"updateTime":1589179644052000000}' | jq -R "fromjson? | .updateTime | strftime(\"%B %d %Y\")"` is the reproducible command on macOS, and this command should print `converting number of seconds since epoch to datetime`. #2125 fixes the assertion failure but the command exits silently due to #1859.
