### ISSUE TITLE
jq If the key name contains the symbol ‘’. ‘’, how do I get the value of the key?

### ISSUE THREAD

**Issue by zhouhuihua526** [stedolan/jq#2130]
jq If the key name contains the symbol ‘’. ‘’, how do I get the value of the key?
E.g: 
[{"name.1.test": "JSON", "good": true}, {"name": "XML", "good": false}]
How to get the value of name.1.test?

**Comment by itchyny** [comment]
`."name.1.test"` or `.["name.1.test"]`

**Comment by zhouhuihua526** [comment]
jq How can I delete the collection whose key value is name.1.test and then form the remaining collection into an array? ?
E.g:
[{"name.1.test": "JSON", "good": true}, {"name": "XML", "good": false}, {"name": "yml", "good": true}]
Expected value:
[{"name": "XML"}, {"name": "yml"}]

**Comment by itchyny** [comment]
`[.[] | select(has("name.1.test")|not) | { name }]`

**Comment by zhouhuihua526** [comment]
thank you very much！！but I still have a connection problem.
jq If you delete the collection with the key value of the subset of user under the key value of test.1, and then form the remaining collection into an array? ?
E.g:
[{"name": "JSON", "good": true, "user": {"test.1": "xx"}},
{"name": "XML", "good": false, "user": {"test.2": "zz"}},
{"name": "yml", "good": true, "user": {"test.2": "zz"}}]
Expected value:
[{"name": "XML", "test2": "zz"}, {"name": "yml", "test2": "zz"}]

**Comment by itchyny** [comment]
That's a combination of the solutions I've written for your questions so far.
`[.[] | select(.user | has("test.1") | not) | { name, test2: .user."test.2" }]`

**Comment by zhouhuihua526** [comment]
ok. thank for you very much!

**Comment by zhouhuihua526** [comment]
Sorry, I still have a connection problem
jq When the key value is a subset of user key is test.2 value is gg or key is test3 value is zz, will the set that meets this condition form an array? ?
E.g:
[{"name": "JSON", "good": true, "user": {"test.2": "xx"}},
{"name": "XML", "good": false, "user": {"test.2": "gg"}},
{"name": "yml", "good": true, "user": {"test.3": "zz"}}]
Expected value:
[{"name": "XML", "test2": "gg"}, {"name": "yml", "test3": "zz"}]

**Comment by itchyny** [comment]
`.[] | { name } + if .user."test.2" == "gg" then { test2: "gg" } elif .user."test.3" == "zz" then { test3: "zz" } else empty end`

**Comment by zhouhuihua526** [comment]
jq Can I have multiple if conditions?
E.g: 
. [] | {key} + if ... end + {key} + if ..end

**Comment by itchyny** [comment]
Your issue comments are incomplete and I can't tell how you tried and failed. Please attach your complete query, even if it doesn't work. And I'd recommend you to ask questions at [stackoverflow](https://stackoverflow.com/questions/tagged/jq). This is the issue tracker where we accept issue reports and feature requests, not questions.

**Comment by zhouhuihua526** [comment]
> Your issue comments are incomplete and I can't tell how you tried and failed. Please attach your complete query, even if it doesn't work. And I'd recommend you to ask questions at [stackoverflow](https://stackoverflow.com/questions/tagged/jq). This is the issue tracker where we accept issue reports and feature requests, not questions.

Because I can't find the complete syntax of jq and there are no examples in the jq manual, I can only ask questions. I'm sorry if it caused you any inconvenience

**Comment by pkoppstein** [comment]
zhouhuihua526 - The official jq manual is full of examples but you have to click in the right place to see them.  There are also examples at rosettacode.org (https://rosettacode.org/wiki/Category:Jq), and in other places, notably the jq Cookbook (https://github.com/stedolan/jq/wiki/Cookbook) and other pages of the jq wiki, and my own "Stream-Oriented Introduction to jq" at https://github.com/pkoppstein/jq/wiki/A-Stream-oriented-Introduction-to-jq.

In any case, as already pointed out, this "Issues" web site is mainly for bug reporting and enhancement requests.  Usage questions can be asked at stackoverflow.com with the jq tag.

**Comment by zhouhuihua526** [comment]
> @zhouhuihua526 - The official jq manual is full of examples but you have to click in the right place to see them. There are also examples at rosettacode.org (https://rosettacode.org/wiki/Category:Jq), and in other places, notably the jq Cookbook (https://github.com/stedolan/jq/wiki/Cookbook) and other pages of the jq wiki, and my own "Stream-Oriented Introduction to jq" at https://github.com/pkoppstein/jq/wiki/A-Stream-oriented-Introduction-to-jq.
> 
> In any case, as already pointed out, this "Issues" web site is mainly for bug reporting and enhancement requests. Usage questions can be asked at stackoverflow.com with the jq tag.

Please send a link to the jq manual, I do n’t know if the jq manual I saw is a link to the manual you said, thank you

**Comment by pkoppstein** [comment]
@zhouhuihua526 - https://stedolan.github.io/jq/manual/v1.6/ - there are roughly 60 subsections with examples.

**Comment by zhouhuihua526** [comment]
> @zhouhuihua526 - https://stedolan.github.io/jq/manual/v1.6/ - there are roughly 60 subsections with examples.

But why didn't I click on Example?
