### ISSUE TITLE
pipe doesn't seem to close when using `-n`

### ISSUE THREAD

**Issue by mavenraven** [stedolan/jq#2135]
**Describe the bug**
There is some strange behavior when running `jq` in a loop to construct json. Maybe this is expected behavior, but I can't find any reference to it.

These all work as expected:

`yes | xargs jq -n '"a"' | head -n 2`
`while true; do jq -n '"a"'; echo ""; done | head -n 2`
`while true; do jq --unbuffered -n '"a"'; echo ""; done | head -n 2`
`for i in $(seq 1 100000); do jq -n '"a"'; echo "" ; done | head -n 2`
`for i in $(seq 1 100000); do jq --unbuffered -n '"a"'; echo "" ; done | head -n 2`

. They all output 
```
"a"

```
and the command completes.

None of these work as expected:

`while true; do jq -n '"a"'; done | head -n 2`
`while true; do jq --unbuffered -n '"a"';  done | head -n 2`
`for i in $(seq 1 100000); do jq -n '"a"' ; done | head -n 2`
`for i in $(seq 1 100000); do jq --unbuffered -n '"a"'; done | head -n 2`

. They all output
```
"a"
"a"
```

and then the command hangs forever.

**Environment (please complete the following information):**
 - OS and Version: macOS Mojave
 - jq version: 1.6
-  zsh version: 5.7.1 (x86_64-apple-darwin16.7.0)
- bash version: version 3.2.57(1)-release (x86_64-apple-darwin18)

Just for some context why I care about this, I was playing with a script that would recursively, safely "jsonize" all the paths in given directory, i.e.

```
#!/bin/sh
recurse() {
    for f in "$1"/*; do
        jq -n --arg file "$f" '$file'
        if [ -d "$f" ]; then
            recurse "$f"
        fi
    done
}
recurse "$1"
```

**Comment by mavenraven** [comment]
Never mind, this has nothing to do with jq,
`for i in $(seq 1 100000); do awk 'BEGIN{print "hi"}' ; done | head -n 2` also doesn't work. Sorry!

**Comment by itchyny** [comment]
This is related to the SIGPIPE signal. This issue is even reproducible with /bin/echo; `while true; do /bin/echo 1; done | head -n 2`. You can break the while loop if you want; `while true; do jq -n 1 || break; done | head -n 2`.

**Comment by mavenraven** [comment]
Yeah, I figured it out, I didn't use `set -e`. Thanks though!
