### ISSUE TITLE
Allow filtering out null keys when updating multiple keys

### ISSUE THREAD

**Issue by NathanJAdams** [stedolan/jq#2147]
Just a minor thing really, I need to update 2 child objects, but they're both optional and I don't want to add a null if one of them is missing. My current command wraps each key in a `select` to get around this but it's slightly more verbose than needed. Here's what I have at the moment

`'((select(.a) | .a), (select(.b) | .b)) |= <update a and/or b here>'`

Is there an easier way of saying "don't update if the key doesn't exist"? If not, could one be added, maybe using a `?` or a `!` unless they're already used?

**Comment by vintnes** [comment]
Does this work for you?

    jq -n '{foo: "bar"}, {baz: "qux"} | (.foo, .baz) |= (. // empty | ascii_upcase)'

If `.` is `null`, coerce `empty`, abandoning the pipe.

**Comment by NathanJAdams** [comment]
That worked perfectly thank you!
Closing the issue as solved
