### ISSUE TITLE
Add output option to remove line breaks

### ISSUE THREAD

**Issue by jpetazzo** [stedolan/jq#215]
I'm processing JSON input to extract (and print!) strings that already have trailing `\n`, and I would like to tell `jq` to _not_ add a newline character itself after each entry.

**Comment by gongpengjun** [comment]
I tried `-r` with jq-1.6

```
jq -j <<EOF
> {"created_at":"2021-01-29T10:06:35.974+0000","name":"test001"}
> {"created_at":"2021-02-01T04:03:28.230+0000","name":"test002"}
> {"created_at":"2021-02-01T04:04:13.327+0000","name":"test002"}
> EOF
```

Output:
```
{
  "created_at": "2021-01-29T10:06:35.974+0000",
  "name": "test001"
}{
  "created_at": "2021-02-01T04:03:28.230+0000",
  "name": "test002"
}{
  "created_at": "2021-02-01T04:04:13.327+0000",
  "name": "test002"
}
```

`-j` or `--join-output` option remove line breaks each **output**

But my needs is to remove line breaks each **entry** as following:

```
"created_at": "2021-01-29T10:06:35.974+0000","name": "test001"
"created_at": "2021-02-01T04:03:28.230+0000","name": "test002"
"created_at": "2021-02-01T04:04:13.327+0000","name": "test002"
```

How to achieve the above output with jq option instead of use `tr -d '{}'` to trim `{`and `}`?

**Comment by itchyny** [comment]
You may want the compact output (`-c`) option
```bash
jq -c <<EOF
{"created_at":"2021-01-29T10:06:35.974+0000","name":"test001"}
{"created_at":"2021-02-01T04:03:28.230+0000","name":"test002"}
{"created_at":"2021-02-01T04:04:13.327+0000","name":"test002"}
EOF
{"created_at":"2021-01-29T10:06:35.974+0000","name":"test001"}
{"created_at":"2021-02-01T04:03:28.230+0000","name":"test002"}
{"created_at":"2021-02-01T04:04:13.327+0000","name":"test002"}
```
or use `tojson` and trim the braces.
```bash
jq -r 'tojson[1:-1]' <<EOF
{"created_at":"2021-01-29T10:06:35.974+0000","name":"test001"}
{"created_at":"2021-02-01T04:03:28.230+0000","name":"test002"}
{"created_at":"2021-02-01T04:04:13.327+0000","name":"test002"}
EOF
"created_at":"2021-01-29T10:06:35.974+0000","name":"test001"
"created_at":"2021-02-01T04:03:28.230+0000","name":"test002"
"created_at":"2021-02-01T04:04:13.327+0000","name":"test002"
```

**Comment by AndrewRayCode** [comment]
I'm trying this with -rc and I'm getting a linebreak at the end of what is copied to my clipboard. I'm not sure if this is a jq issue or not.

I'm trying to get an auth0 bearer token from the CLI. auth0's CLI returns JSON. If I run this command and pipe the output to `jq` using the `-r` and `-c` flags:

```
auth0 test login  | jq -rc '.tokens.id_token'
```

Then the output looks something like:

```
(home) $ auth0 test login  | jq -rc '.tokens.id_token'

(some stuff printed to stderr)

access_token_data_1234

(home) $ 
```
Note that there's an additional linebreak after the access_token_data before my prompt shows again. I'm not sure if this linebreak is from jq or not.

Note there is NOT a linebreak `\n` character in the string from the json value itself.

When I pipe the output to pbcopy:

```
auth0 test login  | jq -rc '.tokens.id_token' | pbcopy
```

Then what's put on my clipboard is the token with linebreak after it, so I'm not just copying the token.

**Comment by pkoppstein** [comment]
1. It would help if you could reproduce the problem with a JSON fragment (the tinier the better), and show all the details here.
2. Have you tried the `-j` command-line option?
