### ISSUE TITLE
jq release

### ISSUE THREAD

**Issue by weiganji** [stedolan/jq#2155]
Is there any plan to publish a new version of jq in near future? Thanks.

**Comment by NightMachinary** [comment]
In the meantime, `brew install jq --head` works well for me.

**Comment by fusionneur** [comment]
It has been a while since last release update. Maybe it is time for an official new release

**Comment by vintnes** [comment]
Please, for the love of all that is free, I beg you, noble Maintainers--to whom I am profoundly grateful--to consider small teams without the resources to support unreleased builds. There are **non-trivial** issues with the last two releases. The [libonig segfault](https://github.com/stedolan/jq/issues/1370) pushed us off 1.5 and now we're harassed by mktime DST issues and linking inefficiencies which have been fixed upstream for months.

@wtlangford, I know that coverage has become manifestly more complex over the last year, but could we please have a list of blockers for a release candidate?

**Comment by LolHens** [comment]
I've put together a small docker image which contains all the dependencies needed to compile jq with compatibility down to glibc 2.12 (centos 6). Just wanted to put this here because people like me who are not that experienced with compiling c might find it helpful.
https://github.com/LolHens/jq-buildenv
```sh
docker run -ti -v ~:/host ghcr.io/lolhens/jq-buildenv:latest bash -c 'git clone https://github.com/stedolan/jq.git && cd jq && git submodule update --init && autoreconf -fi && ./configure --with-oniguruma=builtin && make -j8 && make check && mv jq /host/.'
```

**Comment by wtlangford** [comment]
This is being discussed most recently in #2305. Closing this in favor of that one.
