### ISSUE TITLE
Incorrect Instructions in README

### ISSUE THREAD

**Issue by gewthen** [stedolan/jq#2156]
README says:
>If you're not using the latest git version but instead building a
released tarball (available on the website), then you won't need to
run `autoreconf` (and shouldn't), and you won't need flex or bison.

What then needs to be done to compile from a release tarball? From a documentation standpoint that needs to be addressed. Not everyone would know what to do next. 

Aside from the documentation issue, there appears no way forward with compiling from the release tarball which could be why it is not described in the README. There is no `configure` nor any `Makefile` and the docs say to not run `autoreconf`. If I ignore the docs and run `autoreconf` git get invoked, which does not make sense for a release tarball, because it is not a git repo.

I examined all all releases and it seems that there has never been a `configure` file released. There has been a Makefile in version 1.0 and 1.1 (I know that is beside the point).

**Comment by wtlangford** [comment]
You want either the release artifact called `jq-1.6.tar.gz` or `jq-1.6.tar.zip`. The "source code" artifacts are automatically generated by github and are not prepped for distribution. The two artifacts I published as part of the release have a prebuilt `configure` script in them.
