### ISSUE TITLE
selecting parts of a json

### ISSUE THREAD

**Issue by bradawk1** [stedolan/jq#2162]
I hope this is the correct place to ask this?
I have a json that lists all the firmware components for every server.  The structure is something like:`{
  "uri": "/rest/server-hardware/*/firmware?start=0&count=32",
  "total": 102,
  "start": 0,
  "prevPageUri": null,
  "type": "server-firmwareinventory-list-1",
  "category": "server-hardware",
  "count": 32,
  "members": [
    {
      "uri": "/rest/server-hardware/37839392-3033-5a43-3338-2929dd933/firmware",
      "type": "server-hardware-firmware-1",
      "category": "server-hardware",
      "serverHardwareUri": "/rest/server-hardware/37839392-3033-5a43-3338-2929dd933",
      "serverName": "my-server-1",
      "serverModel": "ProLiant DL560 Gen10",
      "state": "Supported",
      "components": [
        {
          "componentVersion": "1.45 Jun 27 2019",
          "componentLocation": "System Board",
          "componentName": "iLO 5",
          "componentKey": "2f34fslkd-c303-4dss-f33-34l2l2"
        },`

There are a whole bunch of components for each server.  I'm trying to find the system ROM version for every model, for example - DL380 Gen10.  I'd also like to get the server name printed with it's system ROM version.  I can get the entire system ROM component to print out, but not the name and it is printing all of the component.  I'd like to just retrieve the componentVersion.  What I have so far is:
`jq -r '.members[] | select(.serverModel | contains("Proliant DL380 Gen10"))' firmware | jq -r '.components[] | select(.componentName=="System ROM")'`
Does anyone know how I would just get the serverName and componentVersion for serverModel == "Proliant DL380 Gen10" and components.componentName=="SystemROM"?

**Comment by crides** [comment]
Why do you need to use 2 `jq` programs? Unless I'm missing something, you should be able to use `jq '.members[] | select(.serverModel == "Proliant DL380 Gen10") | .components[] | select(.componentName == "System ROM") | {serverName, componentVersion}'`.

**Comment by bradawk1** [comment]
Because I'm still trying to learn jq.  :)
That gets me real close.  It is printing out the firmware version for each server, but the serverName is just printing null.  I'll keep researching.

Thanks!

**Comment by crides** [comment]
Oops, I didn't see that `serverName` is not in the components. That would need to be `jq '.members[] | select(.serverModel == "Proliant DL380 Gen10") | .serverName as $name | .components[] | select(.componentName == "System ROM") | {serverName: $name, componentVersion}'.`

**Comment by bradawk1** [comment]
Thanks!  I was playing around with saving serverName as $name, but was not quite getting it correct.  I'm off next week, but I'll give it a try the following week when I get back in to work.

Thanks again!

**Comment by bradawk1** [comment]
I got it working.  `jq -r '.members[] | select(.serverModel == "ProLiant DL380 Gen10" |  .serverName as $name | .components[] | select(.componentName == "System ROM") | {serverName: $name, componentVersion}' firmware-all`

Thanks!  :)
