### ISSUE TITLE
Virus 'Mal/Generic-S' found in file /usr/bin/jq

### ISSUE THREAD

**Issue by mariohuizar** [stedolan/jq#2180]
**Describe the bug**
When installing jq via Ubuntu and afterwards running a virus scan with sophos I got the the message
Virus 'Mal/Generic-S' found in file /usr/bin/jq

**To Reproduce**
install jq on Ubuntu
install sophos
run scan

**Expected behavior**
No virus should be detected

**Environment (please complete the following information):**
 - OS and Version: Ubuntu 19
 - jq version [e.g. 1.5] 1.6

**Comment by diafour** [comment]
See https://github.com/stedolan/jq/issues/2175
