### ISSUE TITLE
build on macOS

### ISSUE THREAD

**Issue by churib** [stedolan/jq#2190]
Hi,

the ruby gem 'ruby-jq' uses jq as external lib to provide jq syntax in ruby (which is quite cool).

Unfortunately jq does not build on newer macOSes when the normal `autreconf && configure.sh && make`-process with gcc is used like on all other platforms and which is also used by ruby-jq:
```
src/builtin.c:200:31: error: implicit declaration of function 'lgamma_r' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  jv ret = JV_ARRAY(jv_number(lgamma_r(jv_number_value(input), &sign)));
```
The gamma functions are not thread-safe and are not defined without the `_REENTRANT`-makro since [version 315 of math.h](https://opensource.apple.com/source/Libm/Libm-315/Source/Intel/math.h.auto.html) (CTRL-F gamma) on Apple's plattforms.

**Comment by bobnautic** [comment]
Same Problem here

**Comment by wtlangford** [comment]
I have a patch in progress that will fix this in the next release (I see ruby-jq uses the 1.6 release tarball, though). You'll want to reach out to the developer of ruby-jq and have them allow you to pass through some cflags. The flag in particular you'll want to add is `-pthread`.

**Comment by sudeep-ib** [comment]
Same issue here on macos bigsur

**Comment by churib** [comment]
@wtlangford can you foresee when the next release including the patch will come?

**Comment by itchyny** [comment]
I think #2196 is acceptable solution for this issue.

**Comment by wtlangford** [comment]
The current master now has fixes for these particular build issues, and hopefully I'll be able to release a new version soon.
