### ISSUE TITLE
Two string multiplications in a row sometimes fail an assertion

### ISSUE THREAD

**Issue by alekswn** [stedolan/jq#2192]
**Describe the bug**
`jq ".*1024*1024"`  sometimes produce incorrect result or might crash on any input.

**To Reproduce**
```
for i in {1..10}; do echo '"a"' | jq ".*1024*1024 | length"; done
1046536
1048576
1048576
1044496
1048576
1048576
1048576
1048576
1048576
1048576
```

**Expected behavior**
```
echo '"a"' | jq ".*1024*1024 | length"
1048576
```

**Environment (please complete the following information):**
 - OS and Version: Ubuntu 18.04.5 LTS
 - jq version 1.5.1

**Additional context**
Also reproducible on jqplay.org (jq v 1.6) : https://jqplay.org/s/h7JcrU1EY8

Incorrect output string contains following fragments: ...`aaaa\u0000\u0000\u0000\u0000\u0000\
u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000aa`...
and ends with failed assertion: 
```
jq: jv_print.c:78: jvp_dump_string: Assertion `c != -1' failed.
```

**Comment by wtlangford** [comment]
This was fixed in this commit: 9163e09605383a88f6e953d6cb5cc2aebe18c84f. It's currently available on master.
