### ISSUE TITLE
documentation for REGEX function is wrong

### ISSUE THREAD

**Issue by varna9000** [stedolan/jq#2197]
The example for using regex flag in [the documentation](https://stedolan.github.io/jq/manual/#RegularexpressionsPCRE):
`test( "a\sb", "x" )`
Shows that we should use comma as delimiter between the pattern and the flag. Im using jq 1.5 so unless this has been changed in 1.6, it doesn't work. One should use semicolon as delimiter (`;`) instead.

**Comment by ajasmin** [comment]
`test( "a\sb", "x" )` is doubly erroneous 
- `\s` in a string literal should be escaped as `\\s`
- The argument delimiter should be `;` instead of `,`

**Comment by ajasmin** [comment]
I just opened https://github.com/stedolan/jq/pull/2229 to fix
