### ISSUE TITLE
Read '@foo/package' key

### ISSUE THREAD

**Issue by OsirisFrik** [stedolan/jq#2200]
Hi

Im tried to read a key value named like `@foo/package`, but not work and return me this message

```
jq: error: syntax error, unexpected '/', expecting QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
.deprendencies.@foo/package
```

I try with this commands:

```sh
jq .dependencies.@foo/package

jq .dependencies.'@foo/package'

jq .dependencies."@foo/package"
```

how i can read the value of the key?

**Comment by itchyny** [comment]
Try `'.dependencies."@foo/package"'` or `'.dependencies.["@foo/package"]'`.
