### ISSUE TITLE
Numbers became corrupted on conversion

### ISSUE THREAD

**Issue by klirichek** [stedolan/jq#2201]
When using jq as pretty-formatter it corrupt some numbers.
Reproduction is quite simple and works both in desktop and 'try online' version.

```
$ jq --version
jq-1.6
$ cat ex.json
{
  "numbers": [
    623237308590442816,
    2696721519739033356,
    15902905282948881040
  ]
}
$ cat ex.json | jq .
{
  "numbers": [
    623237308590442800,
    2696721519739033600,
    15902905282948880000
  ]
}
```

Expected behavior, obviously, is to leave numbers unchanged.

**Comment by itchyny** [comment]
This is a frequently asked question (#545 #1652 #1959 #2109 #2131 #2182) and is already fixed in the master HEAD (implemented by #1752 in Oct, 2019).
```
 % jq --version
jq-master-a17dd32
 % cat ex.json
{
  "numbers": [
    623237308590442816,
    2696721519739033356,
    15902905282948881040
  ]
}
 % cat ex.json | jq .
{
  "numbers": [
    623237308590442816,
    2696721519739033356,
    15902905282948881040
  ]
}
```

**Comment by klirichek** [comment]
@itchyny ok, that is not immediately clear which keywords use to find similar issues and whether they already fixed or not.
(btw, since even 'try online' is still affected - it is hard to realize whether it is already fixed or not. I personally will wait fix in homebrew).
Thanks for answer ).

**Comment by itchyny** [comment]
Speaking of Homebrew, you can install the HEAD version with `brew install --HEAD jq`.
