### ISSUE TITLE
nested variables not working

### ISSUE THREAD

**Issue by badsmoke** [stedolan/jq#2203]
**Describe the bug**
nested variables do not work

**To Reproduce**

echo '{"nested":{"foo":1}}' | jq --arg n nested --arg f foo 'select(.nested.foo)' :white_check_mark:
```
{
  "nested": {
    "foo": 1
  }
}
```

echo '{"nested":{"foo":1}}' | jq --arg n nested --arg f foo 'select(.nested.[$f])' :x:

result:
```
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
select(.nested.[$f])               
jq: 1 compile error

```

echo '{"nested":{"foo":1}}' | jq --arg n nested --arg f foo 'select(.[$n].foo)' :white_check_mark:

```
{
  "nested": {
    "foo": 1
  }
}
```

echo '{"nested":{"foo":1}}' | jq --arg n nested --arg f foo 'select(.[$n].[$f])' :x:

```
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
select(.[$n].[$f])             
jq: 1 compile error

```

**Expected behavior**
```
{
  "nested": {
    "foo": 1
  }
}
```

**Environment (please complete the following information):**
 - OS and Version: ubuntu 20.04
 - jq version: 1.6

**Additional context**

a dirty workound would be to use bash variables, but that is not the point

n=nested; f=foo; echo '{"nested":{"foo":1}}' | jq "select(.$n.$f)"

**Comment by wtlangford** [comment]
Can you share your expected and actual output? All of those cases do what I'd expect them to.

**Comment by badsmoke** [comment]
I've updated it

**Comment by wtlangford** [comment]
Ah, I see now, sorry about that. On jq-1.6, you need to use `.nested[$f]` or `.[$n][$f]`. Support for the `.[$n].[$f]` form came after 1.6 released.

**Comment by badsmoke** [comment]
ok thanks, the syntax is a bit strange but it works
