### ISSUE TITLE
Unable to through output to CSV format by print output on same line with delimiters

### ISSUE THREAD

**Issue by csrajath** [stedolan/jq#2211]
I have a file of 7million lines with below JSON file schema and I need to extract the DOI from each line with the condition that that line contains 'language' = 'eng' and 'resourceTypeGeneral' = "Dataset". 

```json
{
  "id": "10.6084/m9.figshare.6967592",
  "type": "dois",
  "attributes": {
    "doi": "10.6084/m9.figshare.6967592",
    "identifiers": [],
    "creators": [
      {
        "name": "Borges, Bruna Emanuelle Sanches",
      }
    ],
    "titles": [
      {
        "title": "Human papillomavirus infection and cervical cancer precursor lesions in women living by Amazon rivers: investigation of relations with markers of oxidative stress"
      }
    ],
    "language": null,
    "types": {
      "resourceTypeGeneral": "Dataset"
    }
    }
  }
}
```

I tried the below code but it gave me errors like: (`error. jq: error (at <stdin>:41984): Cannot index object with null
error. jq: error (at <stdin>:41984): Cannot index string with string 'attributes'`)

```shell
cat filename.json |  jq -r '.[.attributes.doi, .attributes.language, .attributes.types.resourceTypeGeneral] | select((.attributes.language == "eng") and (.attributes.types.resourceTypeGeneral == "Dataset"))' | @csv'> geo-only.csv
```

The below line of code is providing the output that I need but Unable to pipeline the output to CSV format. 

```
cat filename.json | jq -r 'select(((.attributes.language == "en") or (.attributes.language == "eng")) and (.attributes.types.resourceTypeGeneral == "Dataset")) | .attributes.doi, .attributes.language, .attributes.types.resourceTypeGeneral | @json'> geo-only.json
```

Instead it throws output like below:
```json
"10.13140/rg.2.2.19804.23685"
"en"
"Dataset"
"10.13140/rg.2.2.29870.56649"
"en"
"Dataset"
"10.5281/zenodo.1346135"
"en"
"Dataset"
"10.5281/zenodo.1346134"
"en"
"Dataset"
"10.5517/ccdc.csd.cc10dr5b"
"eng"
"Dataset"
```

**Comment by pkoppstein** [comment]
It looks like you could simply wrap the listing specifying the items in which you're interested within square brackets, and then add `@csv` like so:

    select(...) | [ VALUES  ] | @csv 


In future, or If you require further assistance, please ask usage questions at stackoverflow.com using the `jq` tag:  https://stackoverflow.com/questions/tagged/jq

**Comment by csrajath** [comment]
> It looks like you could simply wrap the listing specifying the items in which you're interested within square brackets, and then add `@csv` like so:
> 
> ```
> select(...) | [ VALUES  ] | @csv 
> ```
> 
> In future, or If you require further assistance, please ask usage questions at stackoverflow.com using the `jq` tag: https://stackoverflow.com/questions/tagged/jq

Worked. Thanks a lot!!!

Sure:-)
