### ISSUE TITLE
JQ filter

### ISSUE THREAD

**Issue by alfador1** [stedolan/jq#2215]
Hello,
Trying to filter jq by lastModified date:
Command:

     curl -s -u admin:ddada 'https://dada-dada-dev-support-author.dad-platform.projectgallery.de/bin/querybuilder.json?path=/etc/packages/&type=nt:file&p.limit=-1&daterange.property=jcr:created&daterange.upperBound=2020-06-26&daterange.upperOperation=' | jq '. | select(.lastModified < "2020-06-24")

But somehow I still receive json answers with 

     "path": "/etc/packages/com.dhl.aem.contentbackup/dgf-assets-1.0.zip",
      "excerpt": "/etc/packages/com.dada.aem.contentbackup/dgf-assets-1.0.zip",
      "name": "dgf-assets-1.0.zip",
      "title": "dgf-assets-1.0.zip",
      "lastModified": "2020-06-24 15:17:07",
      "created": "2020-06-24 15:17:07",
      "size": "4 GB",
      "mimeType": "application/zip"
    },
    {
      "path": "/etc/packages/com.adobe.cq.inbox/cq-inbox-content-1.2.30.zip",
      "excerpt": "/etc/packages/com.adobe.cq.inbox/cq-inbox-content-1.2.30.zip",
      "name": "cq-inbox-content-1.2.30.zip",
      "title": "cq-inbox-content-1.2.30.zip",
      "lastModified": "2020-06-04 19:00:51",
      "created": "2020-06-04 19:00:51",
      "size": "182 KB",
      "mimeType": "application/zip"
    },
As you can see I still receive otputs with lastModified 2020-06-24 15

**Comment by pkoppstein** [comment]
@alfador1 - Thank you for posting your question at stackoverflow.com (https://stackoverflow.com/questions/64915205).

There are two answers there at the moment, so please close this ticket.  

For future reference, it would be helpful if you could post usage questions regarding jq at [stackoverflow.com ](https://stackoverflow.com/questions/tagged/jq )without also opening a ticket here, unless of course you do not receive a satisfactory answer there after a reasonable amount of time.
