### ISSUE TITLE
wrong result for subtracting two numbers

### ISSUE THREAD

**Issue by mkoura** [stedolan/jq#2217]
**Describe the bug**
jq produce wrong result for subtracting two integers

**To Reproduce**
```
$ jq -n '12000000000000000 - 251565'
11999999999748436
```

**Expected behavior**
```
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Prelude> 12000000000000000 - 251565
11999999999748435

Python 3.8.6 (default, Sep 25 2020, 00:00:00)
>>> 12000000000000000 - 251565
11999999999748435

$ echo $((12000000000000000 - 251565))
11999999999748435
```

**Environment (please complete the following information):**
 - OS and Version: Fedora 32
 - jq version jq-1.6

**Comment by mkoura** [comment]
That's strange:
```
$ jq -n '12000000000000000 - 251565'
11999999999748436

$ jq -n '12000000000000000 - 251564'
11999999999748436

$ jq -n '12000000000000000 - 251563'
11999999999748436
```

**Comment by ajasmin** [comment]
From the doc:
> jq currently only has IEEE754 double-precision (64-bit) floating point number support.

Unfortunately, not all JSON parser treat numbers the same.

Using double-precision floats would align with JavaScript which is sometime seen as a superset of JSON.
RFC 8259 which is (one of) the JSON standard also has this to say about it:

>    This specification allows implementations to set limits on the range
>    and precision of numbers accepted.  Since software that implements
>    IEEE 754 binary64 (double precision) numbers [IEEE754] is generally
>    available and widely used, good interoperability can be achieved by
>    implementations that expect no more precision or range than these
>    provide, in the sense that implementations will approximate JSON
>    numbers within the expected precision.  A JSON number such as 1E400
>    or 3.141592653589793238462643383279 may indicate potential
>    interoperability problems, since it suggests that the software that
>    created it expects receiving software to have greater capabilities
>    for numeric magnitude and precision than is widely available.
> 
>    Note that when such software is used, numbers that are integers and
>    are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
>    sense that implementations will agree exactly on their numeric
>    values.
>
