### ISSUE TITLE
@sh doesn't work as expected with space

### ISSUE THREAD

**Issue by sylwit** [stedolan/jq#2222]
**Describe the bug**
Using @sh doesn't work as expected if the value contains space

**To Reproduce**
From the doc this is working
data=( $(jq -n '"a\tb","c"| @sh' )  )
$ echo "${data[0]}"
"'a\tb'"

Now test this (notice the \t which has been changed for a space)
$ data=( $(jq -n '"a b","cd" | @sh' ) )
$ echo ${data[0]}
"'a
$ echo ${data[1]}
b'"
$ echo ${data[2]}
"'cd'"

**Expected behavior**
echo ${data[0]} should return "a b"

**Environment (please complete the following information):**
 - OS and Version: Ubuntu
 - jq version 1.6

**Comment by itchyny** [comment]
This is not an issue of jq, `IFS=$'\n'` fixes for me.

**Comment by itchyny** [comment]
Well, you might expect the filter should replace the space to `\x20`?

**Comment by geirha** [comment]
You need eval for that approach to work

```bash
$ eval "data=( $(jq -rn '"a b","cd","e\tf\ng"|@sh') )"
$ declare -p data
declare -a data=([0]="a b" [1]="cd" [2]=$'e\tf\ng')
$ printf '<%s>\n' "${data[@]}"
<a b>
<cd>
<e	f
g>
```

Not a jq issue.

**Comment by sylwit** [comment]
Playing with IFS as suggested by @itchyny is not a bad solution. I wasn't able to fully do what I wanted but it helps me a lot. Thanks
