### ISSUE TITLE
Can't print unix escape sequence

### ISSUE THREAD

**Issue by remy** [stedolan/jq#2232]
Can't print unix escape sequence.

**To Reproduce**

```
echo 0 | jq '"\033c"' -r
jq: error: Invalid escape at line 1, column 4 (while parsing '"\0"') at <top-level>, line 1:
"\033c"
jq: 1 compile error
```

Equally escaping the slash just prints the text. Using the `@sh` prefix on the string doesn't work either.

**Expected behavior**

There being some way to print escape sequences out from jq. (or equally is this even possible?)

**Environment (please complete the following information):**
 - OS and Version: macOS 10.15.7 (19H2) (Catalina)
 - jq version: 1.6

_Heads up on the "please read this first"_ - this url http://irc.lc/freenode/%23jq/ is down (or certainly unavailable, and Freenode was completely empty.

**Comment by itchyny** [comment]
`jq -nr '"\u001b[31mHello, world!\u001b[0"'`

**Comment by remy** [comment]
@itchyny thank you - that was enough to get me on my way.

It's not quite 100% perfect, but this will clear the screen (I find it puts me back on line 2 rather than the first line, but it's close enough for now):

```
jq -rn '"\u001bc"'
```

**Comment by itchyny** [comment]
You may want `-j` flag as well.
