### ISSUE TITLE
Reducing inputs drops first record

### ISSUE THREAD

**Issue by burtgulash** [stedolan/jq#2234]
Running reduce on **inputs** without -s seems to drop the first record. Is this expected behaviour?

Documentation on **inputs** states the following, which doesn't suggest it should drop the first record.

```
inputs
Outputs all remaining inputs, one by one.
```

% seq 3 | jq -c -s 'reduce .[] as $x ([]; .+[$x])'
[1,2,3]
% seq 3 | jq -c 'reduce inputs as $x ([]; .+[$x])'
[2,3]

% jq --version
jq-1.6

**Comment by itchyny** [comment]
This is an expected behavior of `inputs` function. The first value is considered as the input to the query. Consider using `-n` (`--null-input`).
```sh
❯ echo 1 2 3 | jq '., [inputs]'
1
[
  2,
  3
]

❯ echo 1 2 3 | jq -n '., [inputs]'
null
[
  1,
  2,
  3
]
```

**Comment by burtgulash** [comment]
Makes sense, Thank you.

I can simply do the following to get all inputs into an array:
```
jq '[.,inputs]'
```
