### ISSUE TITLE
Type casting does not work like in JavaScript

### ISSUE THREAD

**Issue by 2x-1** [stedolan/jq#2239]
**Describe the bug**
Type casting in jq does not work like in JavaScript.

**To Reproduce**
All of these work in JavaScript but not in jq:
```
"1"+1
"2"-1
true+""
[]+"1"
```

**Expected behavior**
Try to simulate JavaScript's type casting as completely as possible. It's quite hard to describe the exact behavior, but in most cases it is: Attempt to evaluate things as a number. If it fails, things should be automatically cast to string if possible.

**Environment (please complete the following information):**
 - Windows 10
 - jq version 1.6

**Comment by pkoppstein** [comment]
jq is JSON-oriented, not javascript-oriented. One might even say, in light of “JavaScript: the good parts”, that compatibility with javascript’s bad parts is an anti-goal.
