### ISSUE TITLE
jq breaks out of a while loop

### ISSUE THREAD

**Issue by TalalYousif** [stedolan/jq#2248]
**Describe the bug**
Using jq inside of a while loop causes the loop to break after the first iteration.

**To Reproduce**
```
echo '{"a": 1, "b": 2}' | jq '.[]' | while read key; do            
    jq --arg id "$key" '{"id": $id}'
done
```

**Expected behaviour**
This should be the output:

```
{
  "id": "1\r"
}
{
  "id": "2\r"
}
```

**Actual behaviour**
This is the output:

```
{
  "id": "1\r"
}
```

**Environment (please complete the following information):**
 - OS and Version: Windows 10
 - jq version 1.6

**Comment by itchyny** [comment]
Specify `-n` (`--null-input`) flag for jq inside the loop. Otherwise the program reads the value emitted from the outside jq.
```sh
echo '{"a": 1, "b": 2}' | jq '.[]' | while read key; do            
    jq -n --arg id "$key" '{"id": $id}'
done
```
For investigate what's happening, confirm with
```sh
echo '{"a": 1, "b": 2}' | jq '.[]' | while read key; do            
    jq --arg id "$key" '[., {"id": $id}]'
done
```

**Comment by TalalYousif** [comment]
> Specify `-n` (`--null-input`) flag for jq inside the loop. Otherwise the program reads the value emitted from the outside jq.
> 
> ```shell
> echo '{"a": 1, "b": 2}' | jq '.[]' | while read key; do            
>     jq -n --arg id "$key" '{"id": $id}'
> done
> ```
> 
> For investigate what's happening, confirm with
> 
> ```shell
> echo '{"a": 1, "b": 2}' | jq '.[]' | while read key; do            
>     jq --arg id "$key" '[., {"id": $id}]'
> done
> ```

That worked as expected. Thank you
