### ISSUE TITLE
jq '[inputs]' skips first line.

### ISSUE THREAD

**Issue by gkutiel** [stedolan/jq#2251]
**Describe the bug**
```echo '{"a":1}{"b":2}{"c":3}' | jq -c '[inputs]' ```
outputs
```[{"b":2},{"c":3}]```

**To Reproduce**
Provide a minimal test case to reproduce the behavior.
If the input is large, either attach it as a file, or [create a gist](https://gist.github.com) and link to it here.
```echo '{"a":1}{"b":2}{"c":3}' | jq -c '[inputs]'```

**Expected behavior**
```[{"a":1}{"b":2},{"c":3}]```

**Environment (please complete the following information):**
 - OS Linux Ubuntu 18.04.5 LTS
 - jq version [e.g. 1.6]

**Additional context**

**Comment by itchyny** [comment]
Specify -n flag. The first value is consumed as the input to the query otherwise -n is used.

**Comment by gkutiel** [comment]
Indeed, 10x.
