### ISSUE TITLE
select duplicates input

### ISSUE THREAD

**Issue by gburca** [stedolan/jq#2258]
**Describe the bug**
The built-in `select` results in duplicate output in some cases.

**To Reproduce**
```
$ echo '{"bar": [2, 2]}' | jq -c 'select(.bar[] == 2)'
{"bar":[2,2]}
{"bar":[2,2]}
```

**Expected behavior**
I would expect the output to be just `{"bar":[2,2]}`

**Environment (please complete the following information):**
 - OS and Version: Ubuntu 18.04
 - jq version: jq-1.5-1-a5b5cbe and jq-1.6rc1

**Comment by itchyny** [comment]
The `.bar[]` query iterates through each array element. Try `echo '{"bar": [2, 2]}' | jq -c 'select(.bar | all(. == 2))'` if you want to check all array elements.

**Comment by gburca** [comment]
That works. Thank you. It's still surprising that select behaves that way and is able to amplify the input.
