### ISSUE TITLE
OSX only issue: Unexpected $end  (Unix shell quoting issues?)

### ISSUE THREAD

**Issue by dasharbaz** [stedolan/jq#2264]
**Describe the bug**
I am not able to get jq to work on OSX Catalina 10.15.7. For simplest jsons/filter, I am getting an unexpected syntax error on versions 1.4+. It works for jq 1.3.

**To Reproduce**
It might have to do something with the state of my system but a simple way I am able to reproduce this issue is:
```
$ echo '{"foo": 0}' | jq .
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <builtin>, line 29:
  )
jq: 1 compile error
```

**Expected behavior**
```
echo '{"foo": 0}' | jq .
{
  "foo": 0
}
```

**Environment (please complete the following information):**
 - OS and Version: MacOS Catalina 10.15.7, 64-bit
 - jq versions: 1.6, 1.5, 1.4

**Additional context**
I tried installing jq with brew (`brew install jq`) as well as using binaries directly provided [here](https://stedolan.github.io/jq/download/) for OSX 64-bit. 
Not sure what other context about my system can help identify the root cause but please let me know how can I help here.

**Comment by guyarad** [comment]
For what it's worth - I am not able to reproduce your issue on my identical system (same OS version, same jq version). I'm guessing that you have somehow meddled with your environment in very odd way. BTW, try wrap the period with quotes: `jq '.'`. 
The next thing you should try is opening a terminal for another user (or just rename your bashrc/zshrv to something else temporarily).

**Comment by pkoppstein** [comment]
Grasping at straws here, but have you tried running jq in a bash shell?

**Comment by dasharbaz** [comment]
Thanks @guyarad for the suggestions, I tried them below:
> try wrap the period with quotes
```$ echo '{"foo": 0}' | jq '.'
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <builtin>, line 29:
  )
jq: 1 compile error
```
> opening a terminal for another user
```
$ sudo bash
Password:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2# echo '{"foo": 0}' | jq '.'
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <builtin>, line 29:
  )
jq: 1 compile error
```
> rename your bashrc/zshrv to something else
```
$ mv ~/.bashrc ~/.bashrck
$ echo '{"foo": 0}' | jq '.'
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <builtin>, line 29:
  )
jq: 1 compile error
```

**Comment by dasharbaz** [comment]
@pkoppstein Yeah I have been using bash shell, I switched to zsh and no luck there as well.

**Comment by wtlangford** [comment]
That error implies that something is wrong with the builtins compiled into jq- where did you get your jq binary from?

**Comment by wtlangford** [comment]
Oh I see now you've gotten it from brew. Do you have a ~/.jq file? Try renaming it if you do

**Comment by dasharbaz** [comment]
oh brilliant @wtlangford. It was indeed my ~/.jq file that had the said syntax error and unfortunately `brew uninstall` doesn't remove that file. Probably jq-1.3 doesn't read ~/.jq file.
