### ISSUE TITLE
Adding an `or` clause to a `select` seems to drop results in some cases

### ISSUE THREAD

**Issue by msteffen** [stedolan/jq#2268]
**Describe the bug**
Adding an `or` clause to a `select` seems to drop results in some cases (see example below)

**To Reproduce**
```
$ echo '{ "a": [ ], "b": [ "x", "y", "z" ] }'  | jq 'select(("x" == .b[]))'
{
  "a": [],
  "b": [
    "x",
    "y",
    "z"
  ]
}
$
$ echo '{ "a": [ ], "b": [ "x", "y", "z" ] }'  | jq 'select(("w" == .a[]) or ("x" == .b[]))'
$ # No output
```
**Expected behavior**
```
$ echo '{ "a": [ ], "b": [ "x", "y", "z" ] }'  | jq 'select(("w" == .a[]) or ("x" == .b[]))'
{
  "a": [],
  "b": [
    "x",
    "y",
    "z"
  ]
}
```

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 20.04
 - jq version: 1.6

**Additional context**
None

I'm working around the issue for now with:
```
echo '{ "a": [ "w", "x", "y" ], "b": [ "x", "y", "z" ] }'  \
  | jq 'select((.a | contains(["w"])) or (.b | contains(["x"])))'
```
but adjusted for my dataset. Apologies if I'm misunderstanding the jq language, and thank you for making such a great tool!

**Comment by pkoppstein** [comment]
`.a[]` is empty, so `"w" == .a[]` is empty, and so the ‘or’ is empty, which explains the discrepancy between your expectations and jq semantics.

**Comment by itchyny** [comment]
Another solution is using `any` function; `jq 'select(any(.a[]; . == "w") or any(.b[]; . == "x"))'`.

**Comment by msteffen** [comment]
I see, I didn't understand exactly what was going on here, but I think I do now: `.a[] == X` is the same as `[ .a[] | . == X ]`, which I didn't realize, and `.a[] or .b[]` is the same as `.a[] as $a | .b[] as $b | $a or $b` which I also didn't realize. The result makes total sense to me now .

Thanks for your help! Closing this issue.
