### ISSUE TITLE
Create a winget installer

### ISSUE THREAD

**Issue by rido-min** [stedolan/jq#2269]
Can you add `jq` to winget ?

I'd like to install on Windows with `winget install jq`

https://github.com/microsoft/winget-pkgs

**Comment by jamiebarrow** [comment]
I believe this can be closed. I can do `winget show --id stedolan.jq` and it shows me the package.

```powershell
PS C:\windows\system32> winget show --id stedolan.jq
Found jq [stedolan.jq]
Version: 1.6
Publisher: stedolan
Description: jq is a lightweight and flexible command-line JSON processor.
License: MIT License
Installer:
  Type: portable
  Download Url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe
  SHA256: a51d36968dcbdeabb3142c6f5cf9b401a65dc3a095f3144bd0c118d5bb192753
```

I did have an issue when installing it, relating to the PATH not seeming to be updated, but then I wouldn't want to hijack this specific issue :)

**Comment by birbilis** [comment]
> I did have an issue when installing it, relating to the PATH not seeming to be updated, but then I wouldn't want to hijack this specific issue :)

Did you file an issue on that one? After installing jq via WinGet it seems to be found only if I do

`set PATH=%PATH%;%USERPROFILE%\appdata\local\microsoft\winget\links

**Comment by jamiebarrow** [comment]
> Did you file an issue on that one? After installing jq via WinGet it seems to be found only if I do
> 
> `set PATH=%PATH%;%USERPROFILE%\appdata\local\microsoft\winget\links
> `

I didn't yet, I noticed that the path seemed to work in a new Administrator PowerShell, but not in a normal cmd shell. I did however notice that my environment variables for my user did have that path as above added to it, which was really strange.

I think I tried opening a Git Bash prompt, and jq seemed to work.

But then, it was the end of my workday, so I shut down my laptop and ended up leaving it as something to double check on Monday.

I'll see on Monday if the issue is still there for me, before logging a new issue. Of course, feel free to add one yourself :) If you do please reference it here so I don't make a duplicate, thank you :)

**Comment by jamiebarrow** [comment]
I could also reproduce this issue on a different machine, so I logged an issue in `winget-cli` repo as I believe it's related more to winget functionality.

See https://github.com/microsoft/winget-cli/issues/2498

**Comment by jeffdav** [comment]
I had to completely close and restart the terminal window (not just a new tab) for the new path to get picked up.

**Comment by wader** [comment]
Don't know anything about winget so could someone who knows see if there is something strange with the package manifest at https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/jqlang ?

I also noticed that the package was renamed from stedolan/jq to jqlang/jq in https://github.com/microsoft/winget-pkgs/pull/108751 but searching for jq at https://winget.run it finds https://winget.run/pkg/stedolan/jq

**Comment by nicowilliams** [comment]
> I had to completely close and restart the terminal window (not just a new tab) for the new path to get picked up.

That's normal.  In Windows the `PATH` and other environment variables get set by the window manager when you start a program from the window manager, but the environment variables of _running_ programs don't get changed.  It's the same in Unix-land, actually.

**Comment by eitsupi** [comment]
> I also noticed that the package was renamed from stedolan/jq to jqlang/jq in [microsoft/winget-pkgs#108751](https://github.com/microsoft/winget-pkgs/pull/108751) but searching for jq at [winget.run](https://winget.run) it finds [winget.run/pkg/stedolan/jq](https://winget.run/pkg/stedolan/jq)

It's `wingetdotrun`'s bug. I have the same issue here winget-run/wingetdotrun#37.

**Comment by jenniupdates** [comment]
The environment path that was generated for me was a really long string with a lot of non alphanumeric characters. Once I renamed the folder containing the jq binary to a simple one like "jqlang.jq", corrected the environment path accordingly and restarted my terminal, I was able to run it.

(not sure if the very weird folder naming affected it from being found but hope this helps)
