### ISSUE TITLE
nested json string cause parse error: Invalid numeric literal

### ISSUE THREAD

**Issue by mystorp** [stedolan/jq#2270]
**Describe the bug**
Nested JSON strings cause parsing errors.

**To Reproduce**
test.json
```json
{"1":"1","test":"{\\"1\\":\\"1\\"}"}
```
```bash
jq '.' test.json
```
result
```
parse error: Invalid numeric literal at line 1, column 25
```

**Expected behavior**
no error

**Environment (please complete the following information):**
 - Macosx 10.15.7 brew jq-1.6
 - 5.4.0-65-generic 18.04.1-Ubuntu   jq-1.5+dfsg-2

**Additional context**

**Comment by pkoppstein** [comment]
Your "JSON" is invalid, as e.g. jsonlint.com will tell you.

Maybe you meant: 
```
{"1":"1","test":"{\"1\":\"1\"}"}
```

**Comment by mystorp** [comment]
@pkoppstein thanks, you are right.
