### ISSUE TITLE
Update the ipv4 and ipv6 host records in one run of jq through the dnspod api.

### ISSUE THREAD

**Issue by hongyi-zhao** [stedolan/jq#2279]
Currently, I want to update the A records of my domain names managed by dnspod's authorized DNS server through the dnspod api using curl and jq as shown below:
```
$ curl -sk 'https://dnsapi.cn/Record.List' -d "login_token=mytoken&format=json&domain_id=my_domain_id" | jq -r '.records[] | select(.type =="A") | construct-the-post-data-for-ipv4-addr-updating
$ curl -sk 'https://dnsapi.cn/Record.List' -d "login_token=mytoken&format=json&domain_id=my_domain_id" | jq -r '.records[] | select(.type =="AAAA") | construct-the-post-data-for-ipv6-addr-updating
```
As you can see, for updating the ipv4 and ipv6 A records, I used two separated jq invoking. I try to run the above two commands in one jq call, but still couldn't find a solution. Any hints/comments/suggestions will be highly appreciated.

Regards.
HY

**Comment by pkoppstein** [comment]
One of many possibilities would be to use `or` in the `select`, e.g.

    .records[] | select(.type =="A" or .type == "AAA")

For future reference, please consider asking usage questions as stackoverflow.com using the jq tag.

**Comment by hongyi-zhao** [comment]
> One of many possibilities would be to use `or` in the `select`, e.g.
> 
> ```
> .records[] | select(.type =="A" or .type == "AAA")
> ```

In fact, I've tried with the above construction but failed to do the trick for my case. In detail, I want to achieve the following aim:

` .records[] | select(.type =="A" or .type == "AAA") | if (.type =="A") { do something } elif (.type == "AAA") { do some other thing }`
 
But I cannot figure out the correct jq syntax structure for the above purpose.

> For future reference, please consider asking usage questions as stackoverflow.com using the jq tag.

Thanks for your suggestion.

**Comment by hongyi-zhao** [comment]
Based on the instructions and discussions [here](https://stackoverflow.com/questions/35308616/jq-streaming-of-large-json-files-to-get-only-objects-whose-properties-have-a-spe) and [here](https://stackoverflow.com/questions/29949184/json-jq-if-without-else), I finally figured out the following solution: 

` jq  ' .records[] | select(.type =="A" or .type == "AAA")| if .type = "A" then .value ="new_ip4_addr" elif .type == "AAAA" then .value ="new_ip6_addr" else .  end | ...`

Thanks again.
HY
