### ISSUE TITLE
Bug when using walk to remove object properties

### ISSUE THREAD

**Issue by zaygraveyard** [stedolan/jq#2280]
**Describe the bug**
When trying to remove certain property from an object using `walk(if . == "y" then empty else . end)`, all properties defined before that property are also removed

https://jqplay.org/s/XJ8TobCkvb
Input: `{"a":"x","c":"y","d":0,"f":{},"b":[]}`
Output: `{"d":0,"f":{},"b":[]}`

**Expected behavior**
Output: `{"a":"x","d":0,"f":{},"b":[]}`

**Comment by pkoppstein** [comment]
The behavior you describe has very little to do with `walk`, as illustrated by

    $ echo '{"a":"x","c":"y","d":0,"f":{},"b":[]}' |
       jq '.c = empty'
    $

That is, jq does not really support removing a specific key/value pair by setting the value to `empty`, which is not all that surprising as `empty` is not a JSON value.  

To achieve the effect you want using jq 1.5 or later, you could use `map_values` and `walk`:
```
walk(if type == "object" or type == "array" then map_values(if . == "y" then empty else . end) else . end)
```

Incidentally, this can also be written more succinctly and DRYly as:
```
walk(if type|IN("object", "array") then map_values(select(. != "y" )) else . end)
```

**Comment by zaygraveyard** [comment]
Thank you for the fast response and the detailed explanation.
It might be helpful this was indicated in the [manual](https://stedolan.github.io/jq/manual/#empty), as from the examples one can see that `empty` allows the removal of elements from an array
And might, wrongfully, come to the conclusion that it could also be used to remove key/value pairs (as I did)
