### ISSUE TITLE
Enabling a more terse use of modules for ad-hoc calls

### ISSUE THREAD

**Issue by jolmg** [stedolan/jq#2282]
I was writing [this comment on how to write a `round` function with alternate parity](https://github.com/stedolan/jq/issues/1192#issuecomment-789146384) and realized that while being able to define functions and modules is cool, there doesn't seem to be a terse way to use those definitions for ad-hoc calls of jq. If a user would regularly benefit from their own defined functions, they currently would have to prefix `include "mymodule";` to their jq code every time.

I got a couple of ideas that could possibly improve that that I thought I'd share. I think just one of these would suffice for the issue. (This probably needs no mentioning, but I'm just sharing the ideas and have no expectation of this going anywhere.)

### Auto-inclusion of modules based on name and parity of functions that are called but not defined

For example, the use-case in the linked comment could evolve to something like:

```
$ mkdir ~/jq
$ echo 'def round(p): .*(1/p) | round | ./(1/p);' > ~/jq/round-1.jq
$ alias jq='jq -L ~/jq'
$ jq 'round(0.01)' <<< 123.456
123.46
```

One could also have a flag to enable this auto-inclusion behavior (perhaps `-A`?). This flag could be added to the alias.

```
$ alias jq='jq -A -L ~/jq'
$ jq 'round(0.01)' <<< 123.456
123.46
```

### Add `-I` for inclusion of modules

This new option could perhaps also accept a directory to include all modules in that directory recursively.

Extending from the previous example, one could then:

```
$ alias jq='jq -I ~/jq'
$ jq 'round(0.01)' <<< 123.456
123.46
```

**Comment by itchyny** [comment]
The file ~/.jq is automatically loaded without command line flags.

**Comment by jolmg** [comment]
@itchyny Nice! I totally missed that. That completely satisfies the need, then.

**Comment by pkoppstein** [comment]
@jolmg - Curiously enough, the issue you raised in the title ("Enabling a more terse use of modules"), far from being resolved by the conventions about the "dotfile" (~/.jq), actually highlights what I believe is a bug.  Specifically, jq fails when an `include` statement is included in the ./.jq file:
```
Assertion failed: (block_has_only_binders(binder, bindflags)), function block_bind_each, file src/compile.c, line 369.
Abort trap: 6
```

If you agree that `include` and `import` statements should be allowed in the ~/.jq file, I'd be grateful if you opened a bug report.

**Comment by jolmg** [comment]
@pkoppstein Good catch. I tested putting the function definition in `~/.jq` and that worked, but I didn't think of trying to include modules. I just assumed it would work as well.

I've created the bug report. It's linked right above this comment.

> the issue you raised in the title ("Enabling a more terse use of modules"), far from being resolved by the conventions about the "dotfile" (~/.jq),

Personally, I still think the `-I` flag could be at least as useful if not more so than `-L`. At least, for *me*, I think `-I` would be more useful.

The auto-inclusion is just the first thing that came to mind from being accustomed to how Ruby modules are loaded in Rails, but I prefer the simplicity of `-I`.

What do you think? Should I reopen this issue again? If anyone wants it open, feel free. I'm just lacking familiarity with GitHub etiquette on the matter.
