### ISSUE TITLE
core dumped when using `include` in `~/.jq`

### ISSUE THREAD

**Issue by jolmg** [stedolan/jq#2283]
**Describe the bug**

`jq` core dumps when using `include` in `~/.jq`.

**To Reproduce**

```
$ cat ~/jq/round-1.jq
def round(p): .*(1/p) | round | ./(1/p);
$ cat ~/.jq
include "round-1";
$ jq -L ~/jq 'round(0.01)' <<< 123.456
jq: src/compile.c:369: block_bind_each: Assertion `block_has_only_binders(binder, bindflags)' failed.
[1]    2219450 abort (core dumped)  jq -L jq 'round(0.01)' <<< 123.456
```

**Expected behavior**

```
$ jq -L ~/jq 'round(0.01)' <<< 123.456
123.46
```

**Environment (please complete the following information):**
 - OS and Version: Archlinux last updated 2021-02-17
 - jq version 1.6

**Additional context**

This was discovered by @pkoppstein [in this comment on a separate issue](https://github.com/stedolan/jq/issues/2282#issuecomment-789405660).

**Comment by wtlangford** [comment]
This has been fixed on the current master, closing.
