### ISSUE TITLE
parse error: Exceeds depth limit for parsing

### ISSUE THREAD

**Issue by evandrix** [stedolan/jq#2298]
- err:`parse error: Exceeds depth limit for parsing at line 1, column 18391`
- works fine for `python3 -B -u -m json.tool 08a0f6dbbdc852f486bc3ad9ee693b9c1abe378e.json` though
- similarly, `<08a0f6dbbdc852f486bc3ad9ee693b9c1abe378e.json | python3 -B -u -c "import sys,json;json.dump(json.load(sys.stdin),sys.stdout,ensure_ascii=False,sort_keys=True,separators=(\",\",\":\"))"`

[08a0f6dbbdc852f486bc3ad9ee693b9c1abe378e.json](https://github.com/stedolan/jq/files/6281998/08a0f6dbbdc852f486bc3ad9ee693b9c1abe378e.json.zip)

**Comment by pkoppstein** [comment]
That JSON contains some deeply nested elements (up to 304 deep).  You could use jq's "streaming parser" (jq --stream) to extract or analyze the JSON of interest.

---
```
jq -n -c --stream 'def max(s): reduce s as $s (null; if . == null then $s elif $s > . then $s else . end); max(inputs[0] | length)' 08a0f6dbbdc852f486bc3ad9ee693b9c1abe378e.json 
304
```

**Comment by pkoppstein** [comment]
@evandrix - If the file 08a0f6dbbdc852f486bc3ad9ee693b9c1abe378e.json is not just a test file, then I would suggest that you either "reopen" this ticket or open a new "enhancement request" ticket, using it as an example of the practical need for a larger value of `MAX_PARSING_DEPTH`.  I don't know of any reason not to increase the value to, say, 512. (If you do reopen this ticket, then I would suggest changing its title to make it clear it's an ER.)

**Comment by bric3** [comment]
I also encountered this while making sense of a very big _flattened_ JSON file.

```
$ jq -c '.' aggregate-raw.json
parse error: Exceeds depth limit for parsing at line 1, column 173983
```

I believe the error should at least suggest the stream alternative.
