### ISSUE TITLE
select operator with exact match doesn't work

### ISSUE THREAD

**Issue by graphixillusion** [stedolan/jq#2299]
Hi there. I've a json like this one:

```
{
  "key": "blabla1",
  "field": "10"
}
{
  "key": "blabla2",
  "field": "101"
}
{
  "key": "blabla3",
  "field": "102"
}
{
  "key": "blabla4",
  "field": "103"
}
```

With this command:

`jq . | select(.field=10).key`

i have this output as intended:

```
"blabla1"
"blabla2"
"blabla3"
"blabla4"
```

The problem occurrs when i need to extract the EXACT match value from the field's entry by using this command:

`jq . | select(.field==10).key`

In this case i should have this result:

`"blabla1"`

but jq doesn't output anything. Any clue about this? Thank you!

**Comment by graphixillusion** [comment]
After some tests and researches, i solved this issue using this syntax:

`jq . | select(.field==\"10\").key`

I need to escape " with \ becouse i'm on Windows

**Comment by pkoppstein** [comment]
Glad you found a solution, and thanks for closing the ticket.

Please note that the initial `.|` is unnecessary. 

FYPI, you could also have written (at a Windows prompt):

      jq --arg x 10 "select(.field==$x).key"

Also, for future reference, it's usually better to ask usage questions at stackoverflow.com, using the jq tag:
https://stackoverflow.com/questions/tagged/jq
