### ISSUE TITLE
make check fails on tests/mantest

### ISSUE THREAD

**Issue by rahrah** [stedolan/jq#2300]
Hi,

I tried to build from git (80052e527) on Slackware Current (gcc 10.2.0 libc-2.33). All went well until:

 `make check`

I then get:

```
PASS: tests/optionaltest
FAIL: tests/mantest
PASS: tests/jqtest
PASS: tests/onigtest 
PASS: tests/shtest
PASS: tests/utf8test
PASS: tests/base64test
```

The log file has these valgrind errors at the beginning:

```
==20040== Conditional jump or move depends on uninitialised value(s)
==20040==    at 0x40A304: checkfail (jq_test.c:50)
==20040==    by 0x40A304: run_jq_tests (jq_test.c:91)
==20040==    by 0x40AC03: jq_testsuite (jq_test.c:34)
==20040==    by 0x40528A: main (main.c:545)
==20040== 
==20040== Conditional jump or move depends on uninitialised value(s)
==20040==    at 0x40A336: checkfail (jq_test.c:50)
==20040==    by 0x40A336: run_jq_tests (jq_test.c:91)
==20040==    by 0x40AC03: jq_testsuite (jq_test.c:34)
==20040==    by 0x40528A: main (main.c:545)
==20040== 
```

Then we get the tests enumerated up to 198, then:

```
198 of 198 tests passed (0 malformed, 0 skipped)
FAIL tests/mantest (exit status: 1)

```

Slackware has oniguruma-6.9.6 installed, so I ran with:

`./configure`

I tried, also with:

`./configure --with-oniguruma=builtin`

with essentially the same results.

Using valgrind-3.14.0.

All the best,

===Rich

**Comment by rahrah** [comment]
Hi,

This seems to have been a valgrind issue.  I updated to 3.17.0, after finding more issues with valgrind-3.14.0; all works fine, now.

Apologies for the noise!

===Rich

**Comment by pkoppstein** [comment]
@rahrah - Tx for the update and for closing the issue.
