### ISSUE TITLE
compilation fails when following published instructions

### ISSUE THREAD

**Issue by falves1** [stedolan/jq#2302]
Ubuntu 20.04
git clone https://github.com/stedolan/jq.git
autoreconf -i
./configure --with-oniguruma=builtin --disable-maintainer-mode
make -j8
make check
make install
output:
config.status: executing libtool commands
mkdir -p src
  GEN      src/builtin.inc
mkdir -p src
  GEN      src/version.h
make  all-recursive
make[1]: Entering directory '/usr/src/jq'
Making all in modules/oniguruma
make[2]: Entering directory '/usr/src/jq/modules/oniguruma'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/usr/src/jq/modules/oniguruma'
make[1]: *** [Makefile:1171: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/jq'
make: *** [Makefile:802: all] Error 2
make  check-recursive
make[1]: Entering directory '/usr/src/jq'
Making check in modules/oniguruma
make[2]: Entering directory '/usr/src/jq/modules/oniguruma'
make[2]: *** No rule to make target 'check'.  Stop.
make[2]: Leaving directory '/usr/src/jq/modules/oniguruma'
make[1]: *** [Makefile:1171: check-recursive] Error 1
make[1]: Leaving directory '/usr/src/jq'
make: *** [Makefile:1670: check] Error 2
make  install-recursive
make[1]: Entering directory '/usr/src/jq'
Making install in modules/oniguruma
make[2]: Entering directory '/usr/src/jq/modules/oniguruma'
make[2]: *** No rule to make target 'install'.  Stop.
make[2]: Leaving directory '/usr/src/jq/modules/oniguruma'
make[1]: *** [Makefile:1171: install-recursive] Error 1
make[1]: Leaving directory '/usr/src/jq'
make: *** [Makefile:1680: install] Error 2

**Describe the bug**

**To Reproduce**
Provide a minimal test case to reproduce the behavior.
If the input is large, either attach it as a file, or [create a gist](https://gist.github.com) and link to it here.

**Expected behavior**

**Environment (please complete the following information):**
 - OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
 - jq version [e.g. 1.5]

**Additional context**

**Comment by itchyny** [comment]
Did you checkout the submodule?

**Comment by wtlangford** [comment]
As @itchyny said, this error indicates you didn't checkout the submodule with `git submodule update --init`, like the README indicates you should do. Alternatively, if you have oniguruma installed on your system, that will also work.
