### ISSUE TITLE
How to integrate JQ with C++ ?

### ISSUE THREAD

**Issue by gfeyer** [stedolan/jq#2307]
Hi guys, 

How can JQ be integrated with C++? 

Is this supported in any way or are there any wrappers for C++ ? 

Thanks,
Gabriel.

**Comment by wtlangford** [comment]
jq has a `jq.h` and `libjq.a` that we produce that you should be able to link against. There's no direct C++ support, but they're just C functions, so you're still able to use them.

**Comment by gfeyer** [comment]
Where could I find the prebuilt **_libjq.a_** for Win platform? I've been looking all over the docs but only the .exe are provided. 
Thanks.
