### ISSUE TITLE
How to concatenate values for the same key in selecting from a json based har file

### ISSUE THREAD

**Issue by ssarma-hub** [stedolan/jq#2312]
I am trying to generate a .csv file from processing a .har (JSON based) file.

My current command is like this (note that I need to have ascii_downcase as name is found in upper, lower and Initcaps):

    cat "$har1".har | $jq -r '[ "Name", "StartTime", "Cache", "Encoding", "ECID", "Method", "Size", "Time", "Blocked", "Send", "Wait", "Receive", "Type" ], (.log.entries[] | [
        .request.url,
        .startedDateTime,
        ((.response.headers[] | select(.name | ascii_downcase == "cache-control").value) // ""),
        ((.response.headers[] | select(.name | ascii_downcase == "content-encoding").value) // ""),
        ((.response.headers[] | select(.name | ascii_downcase == "x-oracle-dms-ecid").value) // ""),
            .request.method,
        (if .response.bodySize == 0 then .response.content.size else .response.bodySize end),
        .time,
        .timings.blocked,
        .timings.send,
        .timings.wait,
        .timings.receive,
        ._resourceType ]) | @csv' > "$har1".csv

The har snippet that is causing issues is in the response header. There are multiple entries for "Cache-Control", Like below:

        {
          "name": "Cache-Control",
          "value": "public"
        },
        {
          "name": "Cache-Control",
          "value": "max-age=31536000"
        },

In the following portion of json:

    "response": {
      "status": 200,
      "statusText": "OK",
      "httpVersion": "HTTP/1.1",
      "headers": [
        {
          "name": "Date",
          "value": "Thu, 06 May 2021 04:53:24 GMT"
        },
        {
          "name": "Server",
          "value": "Oracle-HTTP-Server"
        },
        {
          "name": "X-XSS-Protection",
          "value": "1; mode=block"
        },
        {
          "name": "Cache-Control",
          "value": "public"
        },
        {
          "name": "Cache-Control",
          "value": "max-age=31536000"
        },......

The current result due to this in .csv is like [2 columns]:
"public","max-age=31536000"

current code snippet:
        ((.response.headers[] | select(.name | ascii_downcase == "cache-control").value) // ""),
output: they are split as 2 columns.
"xx.js","2021-05-06T06:14:10.505Z","public","max-age=31536000","gzip"...

**I need to get this as:**
"public;max-age=31536000" , 1 column with ";" separator of .csv. eg:
"xx.js","2021-05-06T06:14:10.505Z",**"public;max-age=31536000"**,"gzip"...

I tried groups_by, group_by examples, but got errors one way or another. 

Also tried: They all added extra blank columns on both left and right side as shown below:
code change:
((.response.headers[] | ([select(.name | ascii_downcase == "cache-control").value]) | join(";")) // ""),
output: 
"xx.js","2021-05-06T06:14:10.505Z","","","","public","max-age=31536000","","","","","","","gzip",

code change:
((.response.headers[] | [select(.name | ascii_downcase == "cache-control").value] | join(";")) // ""),
output: 
"xx.js","2021-05-06T06:14:10.505Z","","","","public","max-age=31536000","","","","","","","gzip"

code change:
((.response.headers[] | [(select(.name | ascii_downcase == "cache-control").value)] | join(";")) // ""),
output: 
"xx.js","2021-05-06T06:14:10.505Z","","","","public","max-age=31536000","","","","","","","gzip",

Would appreciate any help regarding this issue.

**Comment by itchyny** [comment]
Wrap the values by `[` and `]` and then use `join`.
`([.response.headers[] | select(.name | ascii_downcase == "cache-control").value] | join(";")),`

**Comment by ssarma-hub** [comment]
That worked thanks.
