### ISSUE TITLE
Can jq expend json in strings ?

### ISSUE THREAD

**Issue by Nurza** [stedolan/jq#2315]
Hello,

Is there a solution to expending json in strings ?

Example:

```shell
echo '{"json":"{\"hello\":\"world\"}"}' | jq <options>
```

Do you know how to have this output please ?

```json
{
  "json": {
    "hello": "world"
  }
}
```

Thank you in advance, have a good day.

**Comment by wader** [comment]
Yes, maybe something like this:
```jq
with_entries(.value|=fromjson)
```

**Comment by Nurza** [comment]
Nice trick, thank you !

But if the json contains other things like this one:

```shell
echo '{"hello":"world", "json":"{\"hello\":\"world\"}"}' | jq 'with_entries(.value|=fromjson)'
```

Then output is:

```
jq: error (at <stdin>:1): Cannot index string with string "json"
```

Can I target the fields to expand instead of expanding all fields ?

**Comment by wader** [comment]
Then try something like
```jq
with_entries((.value|=fromjson)? // .)
```
to target just one field you can do
```jq
.json |= fromjson
```
and you could chain it with more if you like... or write something that reduces from list of fields etc

**Comment by Nurza** [comment]
It's perfect ! Thank you very much, it was quick !

Here is an example of the solution:

```shell
echo '{"hello":"world","ok": { "json":"{\"hello\":\"world\"}"}, "json":"{\"hello\":\"world\"}"}' | jq '.ok.json |= fromjson | .json |= fromjson'
```
output:

```json
{
  "hello": "world",
  "ok": {
    "json": {
      "hello": "world"
    }
  },
  "json": {
    "hello": "world"
  }
}
```

**Comment by wader** [comment]
👍
