### ISSUE TITLE
[support] jq bash while, unable to set variable when key contains a hyphen

### ISSUE THREAD

**Issue by clontarfx** [stedolan/jq#2317]
Hi community, hoping for an answer (or an alias command). I have JSON with a key named "organization-id". If you try to make use of this as a variable (i.e while read -r organization-id; do echo $organization-id; done) you can see that bash will not read the variable due to not supporting the hyphen as part of a variable.

What is the solution for this? Is there the equivalent of an SQL SELECT AS for selecting keys with "."?

```        
jq -r '.[].attributes|."organization-name", .name, ."primary-ip", ."manufacturer-name" | @tsv' |

                while IFS=$'\t' read -r organization-name name primary-ip manufacturer-name; do
                        echo $primary-ip
                done
```

I could do a dirty hack, output the JSON to file, sed - for _, then read the file back in, but I am hoping for less clunk not more.

Cheers

**Comment by pkoppstein** [comment]
You would either write ${primary-ip} or avoid the issue by adjusting the names on the `read` command.

By the way, your question is really a bash question, not a jq one.  Either way, such usage questions are usually best asked at stackoverflow.com, where you can select more than one tag.

Please don't forget to "close" this issue.

**Comment by clontarfx** [comment]
Wow I seriously need another coffee, that answer is 100% correct and I have just had a mind blank and didn't see this at all... and you're right, it is a bash (and PEBCAK) issue 😂
