### ISSUE TITLE
Requesting Support - How to parse when there is no keys in json

### ISSUE THREAD

**Issue by masterprogrammer999** [stedolan/jq#2321]
I'm trying to parse a response from a ruTorrent request with jq in Linux. It looks like below. I've never seen json like that before, there aren't any keys for me to use in jq as a filter.

How would you get a list of all the hashes? They seem to be the name of objects, but I can't list them only.

Also, I wonder how would you filter to get the dates (in seconds, ex. 1622459402) in the objects? I'm used to everything having keys, and thats how know how to do it.

{
      "t": {
        "2C3D7D91DFD0A57CFCA8B7092347B311088D3B6E": [
          "1",
          "0",
          "1",
          "1",
          "Young.Sheldon.S04.1080p.x265-ZMNT",
          "4764367221",
          "1136",
          "1136",
          "4764367221",
          "5201425130",
          "1091",
          "0",
          "0",
          "4194304",
          "",
          "0",
          "0",
          "0",
          "0",
          "0",
          "2",
          "1622459402",
          "0",
          "0",
          "1136",
          "/home/xxxxxxxx/files/Young.Sheldon.S04.1080p.x265-ZMNT",
          "1622421479",
          "2",
          "1",
          "",
          "",
          "4436465131520",
          "1",
          "1"
        ],
        "FAC73275BC376C4C26DFDA41D991D021838DB778": [
          "1",
          "0",
          "1",
          "1",
          "Joshy.2016.NORDIC.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-Danishbits",
          "21160180253",
          "5045",
          "5045",
          "21160180253",
          "4470554624",
          "211",
          "114688",
          "0",
          "4194304",
          "",
          "1",
          "0",
          "1",
          "0",
          "0",
          "2",
          "1622459402",
          "0",
          "0",
          "5045",
          "/home/xxxxxxxx/files/Joshy.2016.NORDIC.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-Danishbits",
          "1622413504",
          "2",
          "1",
          "",
          "",
          "4436465131520",
          "1",
          "1"
        ],
        "671CA27A76DC35E8E9F46723F1F6596A8BC75DA0": [
          "1",
          "0",
          "1",
          "1",
          "Working.Girl.1988.1080p.Bluray.REMUX.AVC.DTS-HD.MA.5.1-4K4U",
          "29680778067",
          "14153",
          "14153",
          "29680778067",
          "12426936320",
          "418",
          "0",
          "0",
          "2097152",
          "",
          "1",
          "0",
          "1",
          "0",
          "0",
          "2",
          "1622459402",
          "0",
          "0",
          "14153",
          "/home/xxxxxxxx/files/Working.Girl.1988.1080p.Bluray.REMUX.AVC.DTS-HD.MA.5.1-4K4U",
          "1622440882",
          "2",
          "1",
          "",
          "",
          "4436465131520",
          "1",
          "1"
        ]
  },
  "cid": 1423760010
}

**Comment by wader** [comment]
The values in `t` are stored in an array of arrays, try something like `.t[][21]` to get all dates

**Comment by masterprogrammer999** [comment]
> The values in `t` are stored in an array of arrays, try something like `.t[][21]` to get all dates

That is exactly what I was looking for! You can even do things like "select(.[4]=="Day of the dead")", which is great.

Now I just miss a way to only print the hashes, which is the names of the arrays.
