### ISSUE TITLE
jq variable is being modifed by pipeline

### ISSUE THREAD

**Issue by dud225** [stedolan/jq#2323]
Hello

I've noticed that a JQ variable can be modified under some circonstances:
```
$ jq -r '
  .Reservations[].Instances[] | 
    .Tags[] as $tags |
      "clustername: \($tags | select(.Key=="eks:cluster-name") | .Value) - tags: \($tags)"'
' /tmp/ec2.json 
  
clustername: eks - tags: {\"Key\":\"eks:cluster-name\",\"Value\":\"eks\"}
```
I don't expect the variable to be modified, especially since the `select` is run within a separate expression.

If changing sligthtly the expression to set the whole array to the variable, it keeps the variable unmodified:
```
$ jq -r '
  .Reservations[].Instances[] |
    .Tags as $tags |
      "clustername: \($tags[] | select(.Key=="eks:cluster-name") | .Value) - tags: \($tags)"
' /tmp/ec2.json 

clustername: eks - tags: [{"Key":"eks:cluster-name","Value":"eks"},{"Key":"eks:nodegroup-name","Value":"nodegroup"},{"Key":"aws:ec2launchtemplate:version","Value":"1"},{"Key":"aws:ec2launchtemplate:id","Value":"lt"},{"Key":"aws:autoscaling:groupName","Value":"eks"},{"Key":"aws:ec2:fleet-id","Value":"fleet"}]
```

Regards.

[ec2.json.gz](https://github.com/stedolan/jq/files/6598426/ec2.json.gz)

**Comment by itchyny** [comment]
The behavior is correct. `.Tags[] as $tags` reads `for each element in .Tags array, assign it as  $tags`. It does not mean assigning the array as `$tags`.

**Comment by dud225** [comment]
OK I get it, thanks for the explanation.
However I would still expect JQ to iterate on every element:
```
## output I'm expecting ##
clustername: {"Key":"eks:cluster-name","Value":"eks"} - tags: {"Key":"eks:cluster-name","Value":"eks"}
clustername: null - tags: {"Key":"eks:nodegroup-name","Value":"nodegroup"}
clustername: null - tags: {"Key":"aws:ec2launchtemplate:version","Value":"1"}
clustername: null - tags: {"Key":"aws:ec2launchtemplate:id","Value":"lt"}
clustername: null - tags: {"Key":"aws:autoscaling:groupName","Value":"eks"}
clustername: null - tags: {"Key":"aws:ec2:fleet-id","Value":"fleet"
```

Why only displaying the one picked up by the `select` function?
```
$ jq -r '
.Reservations[].Instances[] | .Tags[] as $tags | "clustername: \($tags | select(.Key=="aws:ec2:fleet-id")) - tags: \($tags)"
' /tmp/ec2.json
clustername: {"Key":"aws:ec2:fleet-id","Value":"fleet"} - tags: {"Key":"aws:ec2:fleet-id","Value":"fleet"}
```

**Comment by itchyny** [comment]
The function `select`s the value only when the condition is truthy, and it emits nothing (backtracking internally) on falsy result, not `null`.

**Comment by dud225** [comment]
I mean that I'm expecting the `$tags[] | select(.Key=="eks:cluster-name") | .Value` expression to be executed from a separate context and not have any impact on the other interpolations within the same string. So in my previous example, I'm expecting it to set the empty string or whatever in place of the `null`, but not to crunch the whole string.

**Comment by itchyny** [comment]
`// null` or `// ""` prevents the backtracking to stop here
```
 jq -r '
  .Reservations[].Instances[] | 
    .Tags[] as $tags |
      "clustername: \(($tags | select(.Key=="eks:cluster-name") | .Value) // null) - tags: \($tags)"' /tmp/ec2.json 
```

**Comment by dud225** [comment]
Thanks for the explanation.
