### ISSUE TITLE
i want to save the jq output straightly to the file itself

### ISSUE THREAD

**Issue by clerickx** [stedolan/jq#2325]
i run a minecraft server with whitelist on and bedrock support so the problem is i need to edit the whitelist.json file to add the names and uuids for this it takes a lot of time to scan the id and get the uuid and a lot of time is lost in whitelisting 1 person while we have to whitelist 100 people at a time so i made a script to get whitelist and automatically add it to the .json file but i don't know how to use jq so i tried searching for it and i found this command `jq --arg uuid "$uuid" --arg name "$name" '. += [{"uuid": $uuid, "name": $name}]'` (i know this won't run without setting variables) so i ran this command and it worked but it didn't save it in te .json file so i tried `>> whitelist.json` it worked but it repeated the whole whitelist again so i wonder if there is a command to save me from this

**Comment by geirha** [comment]
Write to another file, the move it over the original

```bash
jq --arg uuid "$uuid" --arg name "$name" '. += [{$uuid, $name}]' whitelist.json > whitelist.json.tmp &&
mv whitelist.json.tmp whitelist.json
```

**Comment by clerickx** [comment]
that works thanks
