### ISSUE TITLE
docs: comparsion == allows to use list of values in parentheses on the right side

### ISSUE THREAD

**Issue by dosmanak** [stedolan/jq#2328]
**Describe the bug**
Unsuficient documentation in https://stedolan.github.io/jq/manual/#ConditionalsandComparisons

**To Reproduce**
supose you have a array of objects with field `id` and you want return only objects with particular id.

```
$ echo '[{"id":1},{"id":2},{"id":3},{"id":4}]' | jq '.[]|select(.id == 2)'
{
  "id": 2
}
```
The first example is clear, for list of ids, it is possible to use
```
$ echo '[{"id":1},{"id":2},{"id":3},{"id":4}]' | jq '.[]|select(.id == (2,4))'
{
  "id": 2
}
{
  "id": 4
}
```
The latter example is not documented.

**Expected behavior**
Documentation covers all the functions of the jq tool.

**Environment (please complete the following information):**
 - OS and Version: Linux Fedora 33
 - jq version: jq-1.6

**Comment by vintnes** [comment]
This is not a feature of the `==` operator; it's an idiom enabled by the `,` operator, which creates streams. Multiple comparison expressions are created and scoped within the `select`. Comments added to output:

```
~ jq -n 'range(3) | select ( debug == (1,2) )'
["DEBUG:",0]    #  0 == 1
["DEBUG:",0]    #  0 == 2
["DEBUG:",1]    #  1 == 1  (true)
1
["DEBUG:",1]    #  1 == 2
["DEBUG:",2]    #  2 == 1
["DEBUG:",2]    #  2 == 2  (true)
2
```

Please close this issue as it's not a bug (in fact it's my favorite thing about JQ).

**Comment by dosmanak** [comment]
I agree the the feature is good, but I'd like to have it documented. Or is there documentation of this behavior?

**Comment by vintnes** [comment]
From `man jq`

```
   Comma: ,
       If two filters are separated by a comma, then the same input will be fed
       into both and the two filters' output value streams will be concatenated
       in order: first, all of the outputs produced by the left expression,
       and then all of the outputs produced by the right. For instance, filter
       .foo, .bar, produces both the "foo" fields and "bar" fields as separate
       outputs.
```

**Comment by dosmanak** [comment]
Thank you. I must say, some parts of the docs are hard to comprehend for me. Maybe I should read it all at once.
