### ISSUE TITLE
Release 1.6 does not have pre-autoreconf'ed configure script

### ISSUE THREAD

**Issue by ashermancinelli** [stedolan/jq#2337]
**Describe the bug**
Release tarball jq-1.6.zip on releases page does not seem to have a configure script pre-autoreconf'ed.

**To Reproduce**
```console
$ wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.zip
$ unzip ./jq-1.6.zip
$ file jq-jq-1.6/configure
jq-jq-1.6/configure: cannot open `jq-jq-1.6/configure' (No such file or directory)
```

**Expected behavior**
A configure script already in the tarball as with previous releases and is mentioned in the README.

**Environment (please complete the following information):**
 - OpenSUSE TW
 - jq-1.6

**Comment by mudit31** [comment]
@ashermancinelli , I think you have an extra `jq-` in your file command.

For me, the following works:
```
$ wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.zip
$ unzip jq-1.6.zip
$ file jq-1.6/configure
jq-1.6/configure: POSIX shell script, ASCII text executable, with very long lines
```
[tar.gz](https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.tar.gz) also works similarly.
This works if you download sources from https://stedolan.github.io/jq/download/. 

If you download sources from [github releases page](https://github.com/stedolan/jq/releases), then the issue you described happens.

**Comment by ashermancinelli** [comment]
Thanks!
