### ISSUE TITLE
feat: invert JQ select query (add a ! unary operator)

### ISSUE THREAD

**Issue by georgettica** [stedolan/jq#2339]
**Describe the bug**
when I was using the `select` I expected I could invert the condition

**To Reproduce**
```
$ echo {} | jq '{"a": [{"a":"test"},{"a":"test1"},{"a":"best1"}]}' | jq '.a[] | select(.a| test("test"))'
{
  "a": "test"
}
{
  "a": "test1"
}
```
I want to have a way to set `select(! .a| test("test"))` or `not select(.a| test("test"))` or something of the sort

**Expected behavior**
I expect the negated response to be returned

**Environment (please complete the following information):**
 - MacOS
 - jq version : 1.6

**Additional context**
I searched in stackoverflow and the results seems very clunky, is https://stackoverflow.com/questions/44563115/how-to-use-jq-to-filter-select-items-not-in-list

**Comment by itchyny** [comment]
Try `select(.a | test("test") | not)`.

**Comment by georgettica** [comment]
good enough for me and I will post it where I saw the issue

thanks for the super quick respone! @itchyny
