### ISSUE TITLE
jq adds BOM to JSON file on Windows

### ISSUE THREAD

**Issue by dcporter65** [stedolan/jq#2351]
Running jq on Windows adds a byte order mark (BOM) to the start of a JSON file. The BOM is illegal in JSON and causes a parsing error when running the JSON file through other tools.

### To reproduce

Using Notepad++, create a file called `fruit.json` containing the following:

```json
{
  "fruit": {
    "name": "apple",
    "color": "green",
    "price": 1.2
  }
}
```

Note that the encoding in the bottom right of the screen is shown as UTF-8.

![image](https://user-images.githubusercontent.com/83212011/134425688-16d3f09b-7a1f-45c0-8375-9665e3687a8b.png)

Run the following command:

`jq '.fruit' fruit.json > apple.json`

Open `apple.json`.

### Result

The encoding has changed to UTF-16 LE BOM.

![image](https://user-images.githubusercontent.com/83212011/134425737-63d8a8cc-bcc8-478d-bb0b-6af11a97bd28.png)

### Expected

The encoding should not change and the BOM should not be added.

### Environment
 - Windows 10
 - jq 1.6

**Comment by polluks2** [comment]
Indeed, [Implementations MUST NOT add a byte order mark to the beginning of a JSON text](https://datatracker.ietf.org/doc/html/rfc7159#section-8.1).

**Comment by ikegami** [comment]
`jq` doesn't create a UTF-16 file (with or without BOM). It's the `>` of older versions of PowerShell that does that. You need PowerShell version 6+.

[Installing PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell)

**Comment by dcporter65** [comment]
> 

@ikegami Excellent. Thanks. Just tested in PowerShell 7.1 and the problem has gone away. 

Sorry for doubting you, `jq`!
