### ISSUE TITLE
js converts only from thousands the first 5 json objects : how to solve the problem?

### ISSUE THREAD

**Issue by raphael10-collab** [stedolan/jq#2364]
I `want` to convert to `jsonl` file the following : 

    -rw-rw-r--  1 raphy raphy 1,9M nov  4 10:34 conceptnet.json

When doing : 

    jq -cn --stream "fromstream(1|truncate_stream(inputs))" conceptnet.json > conceptnet.jsonl

it converts only the first 5 json objects
[conceptnet.txt](https://github.com/stedolan/jq/files/7474115/conceptnet.txt)
: 

nano conceptnet.jsonl

        {"_from":"àcid_gras_saturat","_to":"ácid_gras_insaturat","rel":{"rel_type":"Antonym","language":"ca","license":"-sa/4.0","sources":"/s/resource/wiktionary/fr","process":"/s/process/wikiparsec/2"}}
        {"_from":"gawas","_to":"sulod","rel":{"rel_type":"Antonym","language":"ceb","license":"-sa/4.0","sources":"/s/resource/wiktionary/en","process":"/s/process/wikiparsec/2"}}
        {"_from":"gawas","_to":"sulod","rel":{"rel_type":"Antonym","language":"ceb","license":"-sa/4.0","sources":"/s/resource/wiktionary/en","process":"/s/process/wikiparsec/2"}}
        {"_from":"tollpatschig","_to":"gewandt","rel":{"rel_type":"Antonym","language":"de","license":"-sa/4.0","sources":"/s/resource/wiktionary/en","process":"/s/process/wikiparsec/2"}}
        {"_from":"ungewiss","_to":"gewiss","rel":{"rel_type":"Antonym","language":"de","license":"-sa/4.0","sources":"/s/resource/wiktionary/en","process":"/s/process/wikiparsec/2"}}

I enclose here the `conceptnet.json` file (the source) which I had to rename as `conceptnet.txt`

How to solve the problem?

OS: Ubuntu 20.04

**Comment by itchyny** [comment]
Somehow 6th (and later) elements are string; `jq -c ".[] | type" conceptnet.json`.

**Comment by raphael10-collab** [comment]
Thank you @itchyny for pointing me to the right direction.
I have to investigate why this happens from the 6th element onwards

I close the issue
