### ISSUE TITLE
`has(x)` doesn't work for the last element in the array

### ISSUE THREAD

**Issue by arbitrary-dev** [stedolan/jq#2369]
**Describe the bug**
`has(x)` doesn't work for the last element in the array

**To Reproduce**
```
$ jq --null-input '[1,2,3,4]|has(1)'
true
$ jq --null-input '[1,2,3,4]|has(2)'
true
$ jq --null-input '[1,2,3,4]|has(3)'
true
$ jq --null-input '[1,2,3,4]|has(4)'
false
```

**Expected behavior**
```
$ jq --null-input '[1,2,3,4]|has(4)'
true
```

**Environment (please complete the following information):**
 - OS: Gentoo/Linux x86_64
 - jq 1.7

**Comment by itchyny** [comment]
The `has` function checks the **index** exists in the array (or key in the object). Consider using `contains` to check if a value contained in the array.
