### ISSUE TITLE
parse error: Invalid numeric literal at line 3, column 11

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [stedolan/jq#2408]
Getting issue in this command 
curl 'https://api.inkdrop.app/' | jq .

Please, someone, help me how to resolve this issue 
![Screenshot (587)](https://user-images.githubusercontent.com/73753957/152392642-4de20453-591f-4ceb-9301-f0b62620bfc3.png)

**Comment by wader** [comment]
Works for me. Maybe try add `-s ` to curl. Don't know how windows handles stderr and pipeing.
```
$ curl -s 'https://api.inkdrop.app/' | jq .
{
  "ok": true
}
```

**Comment by gurjeetsinghvirdee** [comment]
> 
not working `after adding -s` it shows like this

![Screenshot (588)](https://user-images.githubusercontent.com/73753957/152398989-9c76f6c7-879e-4e08-8369-40418ed0163e.png)

**Comment by wader** [comment]
Im guess `curl` is not really curl in your shell https://superuser.com/questions/344927/powershell-equivalent-of-curl

**Comment by gurjeetsinghvirdee** [comment]
> Im guess `curl` is not really curl in your shell https://superuser.com/questions/344927/powershell-equivalent-of-curl

Thanks, man issue resolved

**Comment by wader** [comment]
No problem! happy jq:ing

**Comment by onurhan1337** [comment]
@gurjeetsinghvirdee Hi, I get same error. How you can solved that?

**Comment by samivic** [comment]
I tried 

> `scoop install jq`

and it worked for me.
