### ISSUE TITLE
`implode` crashes on array containing something else than a number

### ISSUE THREAD

**Issue by 01mf02** [stedolan/jq#2427]
**Describe the bug**
`implode` crashes when giving to it an array that contains a non-number.

**To Reproduce**
~~~
$ jq -n '[[]] | implode'
jq: src/jv.c:726: jv_string_implode: Assertion `jv_get_kind(n) == JV_KIND_NUMBER' failed.
Aborted (core dumped)
$ jq -n '[null] | implode'
jq: src/jv.c:726: jv_string_implode: Assertion `jv_get_kind(n) == JV_KIND_NUMBER' failed.
Aborted (core dumped)
~~~

**Expected behavior**
jq should give an error such as: "implode input must be an array **of numbers**", similarly to what happens on giving other values to `implode`:
~~~
jq -n '1 | implode'
jq: error (at <unknown>): implode input must be an array
~~~

**Environment (please complete the following information):**
 - OS and Version: Linux
 - jq version: 1.6

**Comment by itchyny** [comment]
Duplicate issue: #1160

**Comment by 01mf02** [comment]
Oh, sorry for the duplicate.
