### ISSUE TITLE
why output file  size is double than raw file?

### ISSUE THREAD

**Issue by daixiangzi** [stedolan/jq#2428]
jq version 1.6
raw_file.json:4.1M
jq . raw_file.json>format.json
format.json is 8.5M

**Comment by wader** [comment]
what does `diff -u raw_file_json format.json` say? i would guess jq reformats it differently somehow

**Comment by pkoppstein** [comment]
@daixiangzi - You've asked for the JSON to be "pretty-printed", so why are you surprised?  If you want the JSON to be compressed, use the -c command-line option.  If you want it to be pretty-printed using (slightly) less space, try `-t` or `--indent 1`.
