### ISSUE TITLE
tool that shows all possible jq paths in a given json file

### ISSUE THREAD

**Issue by ilyash** [stedolan/jq#243]
( Copy+pasting unanswered email: )

Hi.

I have just prepared a tiny tool that shows all possible jq paths in a given json file. I guess it can help people that use jq. I'm not sure where in the docs it goes. Can you please add a link wherever you think is appropriate?

Please note (also, should be clear to users before following the link) that the script was not heavily tested and I guess is alpha quality in general, quick and dirty, naive implementation.... but still works for me.

https://github.com/ilyash/show-struct

Thanks!

**Comment by jacobsalmela** [comment]
@nicowilliams or @ilyash what about showing the values of those paths as well?

**Comment by ayosec** [comment]
If anyone is interested, the following code show all paths with their values:

```jq
paths(scalars) as $p
  | [ ( [ $p[] | tostring ] | join(".") )
    , ( getpath($p) | tojson )
    ]
  | join(" = ")
```

----

Example:

```bash
$ jq -r '
paths(scalars) as $p
  | [ ( [ $p[] | tostring ] | join(".") )
    , ( getpath($p) | tojson )
    ]
  | join(" = ")
' <<'INPUT'
{
  "a": 1,
  "b": [ "red", "green", "blue" ],
  "c": {
    "d": [
      {
        "a": 100,
        "b": 200,
        "c": "x\ny\nz"
      },
      {
        "a": 101,
        "b": 201
      }
    ]
  }
}
INPUT
```

Output:

    a = 1
    b.0 = "red"
    b.1 = "green"
    b.2 = "blue"
    c.d.0.a = 100
    c.d.0.b = 200
    c.d.0.c = "x\ny\nz"
    c.d.1.a = 101
    c.d.1.b = 201

**Comment by gertcuykens** [comment]
@ayosec is it possible to have this? thx
```
a = 1
b[0] = "red"
b[1] = "green"
b[2] = "blue"
c.d[0].a = 100
c.d[0].b = 200
c.d[0].c = "x\ny\nz"
c.d[1].a = 101
c.d[1].b = 201
```
Tried it myself but seems alot harder then I expected.

**Comment by pkoppstein** [comment]
The following produces the output you've indicated you want:

```
def path2text($value):
  def tos: if type == "number" then . else "\"\(tojson)\"" end;
  reduce .[] as $segment ("";  .
    + ($segment
       | if type == "string" then "." + . else "[\(.)]" end))
  + " = \($value | tos)";
  

paths(scalars) as $p
  | getpath($p) as $v
  | $p | path2text($v)
```

**Comment by gertcuykens** [comment]
yep works awesome thx, wouldn't be able to find it myself in a million years :)

**Comment by nzbart** [comment]
@gertcuykens I think [gron](https://github.com/tomnomnom/gron) may be what you're after if you want to list all the values like that.

Some minor tweaks to the output of gron make it possible to get a list of jq compatible paths with array numbering removed:

```

  "a": 1,
  "b": [ "red", "green", "blue" ],
  "c": {
    "d": [
      {
        "a": 100,
        "b": 200,
        "c": "x\\ny\\nz"
      },
      {
        "a": 101,
        "b": 201
      }
    ]
  }
}' | gron | sed -E 's/\[[0-9]+\]/\[]/g; s/ = .*;//g; s/^json//' | sort | uniq
```

Output:
```
.a
.b
.b[]
.c
.c.d
.c.d[]
.c.d[].a
.c.d[].b
.c.d[].c
```

**Comment by YordanGeorgiev** [comment]
@ilyash - open a buy me a beer / coffee account ... I will be one of the first to send you money ...

**Comment by orvn** [comment]
I've been using this syntax 

```jq
jq 'select(objects)|=[.] | map( paths(scalars) ) | map( map(select(numbers)="[]") | join(".")) | unique'
```

That last pipe to unique is also helpful for really large objects.

**Comment by jseifeddine** [comment]
bit of both your suggestions combined

jq 'path(recurse(if type|. == "array" or . =="object" then .[] else empty end))|[.[]|tostring]|join("/")'
