### ISSUE TITLE
Cannot remove or replace nbsp characters with sub/gsub

### ISSUE THREAD

**Issue by sebma** [stedolan/jq#2431]
**Describe the bug**
Cannot remove or replace [nbsp characters](https://en.wikipedia.org/wiki/Non-breaking_space) with sub/gsub.

**To Reproduce**
Have some nbsp characters in the JSON data and extract fields from it and then substitute the nbsp characters with the `gsub` function using `\xC2\xA0` : 
```jq
jq: error: Invalid escape at line 1, column 4 (while parsing '"\x"') at <top-level>, line 1:
recurse | arrays[] | ( select(.class == "video-card_n ellip").title | gsub("\n";" ") | gsub("\xC2\xA0";"") ),( select(.class == "video-card_lk").href | sub("[?].*$";"") )                                                                        
jq: error: Invalid escape at line 1, column 4 (while parsing '"\x"') at <top-level>, line 1:
recurse | arrays[] | ( select(.class == "video-card_n ellip").title | gsub("\n";" ") | gsub("\xC2\xA0";"") ),( select(.class == "video-card_lk").href | sub("[?].*$";"") )                                                                        
jq: 2 compile errors

```
**Expected behavior**
The nbsp characters are replaced.

**Environment (please complete the following information):**
 - OS and Version: Ubuntu Linux 20.04 LTS
 - jq version : 1.6

**Additional context**

**Comment by sebma** [comment]
@wader Thanks. but now if I type this : 
```jq
$ jq --arg nbsp_UTF16 '\u00A0' -r 'recurse | arrays[] | ( select(.class == "video-card_n ellip").title | gsub("\n";" ") | gsub($nbsp_UTF16;" ") ),( select(.class == "video-card_lk").href | sub("[?].*$";"") )'
```
It does not substitute the nbsp characters.

**Comment by wader** [comment]
No problem, string encoding can easily get confusing. I think in your case `nbsp_UTF16` env will be just a string and not be "unescaped" by jq:
```
$ nbsp_UTF16='\u00A0' jq -rn 'env.nbsp_UTF16'
\u00A0
```
maybe something like this:
```sh
$ nbsp_UTF16='"\u00a0"' jq -rn '(env.nbsp_UTF16 | fromjson)' | hexdump -C
00000000  c2 a0 0a                                          |...|
00000003
``` 
or just use `"\u00a0"` directly in the query.

Maybe calling it UTF16 (which endian?) is confusing, it's a codepoint not a unicode byte encoding.

**Comment by sebma** [comment]
@wader What is `fromjson` ?

Do I need it after my `gsub` call ?

**Comment by wader** [comment]
> @wader
> 
> > ```shell
> > $ nbsp_UTF16='"\u00a0"' jq -rn '(env.nbsp_UTF16 | fromjson)' | hexdump -C
> > ```
> 
> What is `fromjson` ?
> 
> Do I need a `fromjson` call after my `gsub` call ?

`fromjson` is a jq function that converts a string with json into json values.  So something like `gsub(env.nbsp_UTF16 | fromjson; " ")`

> 
> > Maybe calling it UTF16 (which endian?) is confusing,
> 
> What name do you propose for this nbsp variable ?

I think i would skip passing it as a environment variable and just do `gsub("\u00a0";"")` instead.

> 
> > , it's a codepoint not a unicode byte encoding.
> 
> What is the difference between a unicode codepoint not a unicode byte encoding ?

codepoint is numbers assigned to different symbols etc in unicode. UTF-* is different ways to encode those codepoint numbers into a byte stream.

**Comment by sebma** [comment]
@wader 

> codepoint is numbers assigned to different symbols etc in unicode. UTF-* is different ways to encode those codepoint numbers into a byte stream.

Can a codepoint map to more than one specific character ?

**Comment by wader** [comment]
> Can a codepoint map to more than one specific character ?

One codepoint will map to different bytes sequences based on which UTF-* encoding you use. In the case of jq it will read UTF-8 JSON and then in the jq language a string will be represented as a list of code points (you can use `explode` to see them) and then when outputting JSON it will convert things into UTF-8 again. That is why you see the byte sequence `\xc2\xa0` in a JSON file etc but that is the UTF-8 encoding of the nbsp code point 160 (0xa0).

**Comment by sebma** [comment]
@wader Thanks for all your help.

God bless you.

**Comment by wader** [comment]
@sebma 👍 no problem, glad you solved it
