### ISSUE TITLE
Output to multiple files

### ISSUE THREAD

**Issue by zxcat** [stedolan/jq#2438]
I need to move the values of some keys of a large JSONs input into separate files. Currently, this requires writing several `jq` commands for the same JSON, which is very slow with large inputs.

It would be great if `jq` could read and parse JSON once and then output to different files.  
Alternatively, it could set ENV variables so I can write files outside of `jq`.

**Comment by itchyny** [comment]
You can bind shell variables by evaluating jq output.
```sh
eval "$(jq -nr '{x:1,y:{y:2},z:{"some":"large json"}} | @sh"x=\(.x|tojson); y=\(.y|tojson); z=\(.z|tojson)"')"

echo "$x"
echo "$y"
echo "$z"
```

**Comment by emanuele6** [comment]
Someone asked time ago on the `#jq` IRC channel on libera.chat

I proposed this solution:
```bash
#!/bin/sh --

jq -r '
    try (               [ .index, .isActive ] | @tsv "1\(.)"),
    try (.friends[]   | [  .name,      .age ] | @tsv "2\(.)"),
    try (.companies[] | [  .name,  .address ] | @tsv "3\(.)")
' file.jsonl \
| sed -n -e 's/^1//w file1.tsv' -e t \
         -e 's/^2//w file2.tsv' -e t \
         -e 's/^3//w file3.tsv'
```

N.B. if your output is not `@tsv` or something else that is guaranteed to be one line long, you should use something like `"1\((. / "\n")[])"` instead of just `"1\(.)"`.

**Comment by zxcat** [comment]
Thanx, I've tried both.
The first one is more flexible for me, coz allows to put partial JSON into a variable.
