### ISSUE TITLE
Catching errors doesn't work on parse error

### ISSUE THREAD

**Issue by kenorb** [stedolan/jq#2441]
**Describe the bug**

I've sample 8 json rows, and the 2nd appears to be invalid for some reason.
I'm trying to ignore it by try/catch, but jq stops.

**To Reproduce**

Run:

```
$ zcat jq-twitter-json-error.json.txt.gz | jq -r 'try error(.user.id) catch .'
946181726124036100
parse error: Invalid \uXXXX\uXXXX surrogate pair escape at line 2, column 724
```

**Expected behavior**

- The error shouldn't happen (JSON should be valid based on the Twitter dump).
- In case of error, `jq` should continue with processing.

**Environment (please complete the following information):**
 - OS and Version: Ubuntu 21.10
 - jq version: jq-1.6

**Additional context**

Sample file (8 rows): [jq-twitter-json-error.json.txt.gz](https://github.com/stedolan/jq/files/8884553/jq-twitter-json-error.json.txt.gz)

**Comment by wader** [comment]
Hey, you probably have to parse each line by itself. Try something like this:
```sh
jq -R 'fromjson?' jq-twitter-json-error.json.txt
```
or something like this if you want to do something with the errors:
```sh
jq -R 'try fromjson catch .' jq-twitter-json-error.json.txt
```

**Comment by vintnes** [comment]
JQ's not wrong: looks like the output was interlaced and an escape is missing 2 bytes.

```
$ zcat jq-twitter-json-error.json.txt.gz | sed -n '2p' | cut -c 684-769
All views my own.\ud83d\udc68\ud83c\udf{"created_at":"Tue Apr 17 20:02:00 +0000 2018",
```

**Comment by kenorb** [comment]
> Hey, you probably have to parse each line by itself.

Thanks for the suggestion, that could work.

    jq -R 'try fromjson catch . | .user.id' jq-twitter-json-error.json.txt

**Comment by kenorb** [comment]
> JQ's not wrong: looks like the output was interlaced and an escape is missing 2 bytes.

You're right, JSON got corrupted for some reason. I'll have to check the original dump data.

**Comment by kenorb** [comment]
Closing as it seems it works as designed.
