### ISSUE TITLE
Suspicous wiki edit adds tracker to install page

### ISSUE THREAD

**Issue by wader** [stedolan/jq#2443]
https://github.com/stedolan/jq/wiki/Installation/_compare/6948363^...6948363

@RnDMn what was this change about? i've reverted it for now

**Comment by wader** [comment]
User was deleted by github

**Comment by emanuele6** [comment]
I reported the account about an hour ago. =)

This has also happened to the wiki pages of [mpv](https://github.com/mpv-player/mpv/wiki) some months ago.

**Comment by wader** [comment]
👍  reported it also :) wonder what the goal is? looked like it was a geo ip tracker redirecting to the previous url. Maybe the redirect url can be changed later on for nastier things?
