### ISSUE TITLE
Commands work in terminal but not within shell script

### ISSUE THREAD

**Issue by amillion8** [stedolan/jq#2457]
Hello,
I have a shell script that executes jq commands to parse json and everything works when executed in the terminal, but errors out when executed from within the script. Below are the details:

Environment: 
Ubuntu 20.04.4 LTS running on Windows 10 Enterprise 64-bit machine (Linux US-2X2MBK3 5.10.16.3-microsoft-standard-WSL2 #1)

Shell: 
Bash 5.0.17(1)-release

jq: 
jq-1.6

Code:
CLUSTER_NAME="alex-test"
CLUSTER_INFO=$(databricks clusters list --output json | jq -r --arg cluster_name "${CLUSTER_NAME}" '.clusters[]? | select(.cluster_name == $cluster_name)')

Result from the terminal:
{ "cluster_id": "0516-130337-t4f355at", "creator_user_name": "xxxxxxxx", "spark_context_id": 3587274670623381000, "cluster_name": "alex-test", "spark_version": "9.1.x-cpu-ml-scala2.12", "spark_conf": { "spark.databricks.io.cache.parquet.numWriters": "8", "spark.sql.execution.arrow.pyspark.fallback.enabled": "true", "spark.sql.adaptive.enabled": "true", "spark.databricks.delta.optimizeWrite.enabled": "true", "spark.databricks.delta.autoCompact.enabled": "true", "spark.rdd.compress": "true", "spark.hadoop.fs.azure.account.oauth2.client.id.xxxxx.dfs.core.windows.net": "{{secrets/xxxxx/xxxxx}}", "spark.files.maxPartitionBytes": "268435456", "spark.databricks.delta.preview.enabled": "true", "spark.hadoop.fs.azure.account.oauth2.client.endpoint.xxxxx.dfs.core.windows.net": "https://login.microsoftonline.com/xxxxx/oauth2/token", "spark.databricks.preemption.timeout": "30s", "spark.hadoop.fs.azure.account.auth.type.edpanalyticsdev.dfs.core.windows.net": "OAuth", "spark.hadoop.fs.azure.account.oauth2.client.secret.xxxxx.dfs.core.windows.net": "{{secrets/xxxxx/xxxxx}}", "spark.sql.adaptive.autoOptimizeShuffle.enabled": "true", "spark.databricks.optimizer.adaptive.enabled": "true", "spark.sql.legacy.timeParserPolicy": "LEGACY", "spark.sql.execution.arrow.fallback.enabled": "true", "spark.sql.sources.partitionOverwriteMode": "dynamic", "spark.databricks.preemption.enabled": "true", "spark.sql.execution.arrow.pyspark.enabled": "true", "spark.databricks.preemption.threshold": "0.5", "spark.sql.legacy.parquet.datetimeRebaseModeInWrite": "LEGACY", "spark.sql.inMemoryColumnarStorage.batchSize": "25000", "spark.hadoop.fs.azure.account.oauth.provider.type.edpanalyticsdev.dfs.core.windows.net": "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider" }, "azure_attributes": { "first_on_demand": 1, "availability": "ON_DEMAND_AZURE", "spot_bid_max_price": -1 }, "node_type_id": "Standard_DS3_v2", "driver_node_type_id": "Standard_DS3_v2", "cluster_log_conf": { "dbfs": { "destination": "dbfs:/cluster_logs" } }, "autotermination_minutes": 30, "enable_elastic_disk": true, "disk_spec": {}, "cluster_source": "UI", "enable_local_disk_encryption": false, "instance_source": { "node_type_id": "Standard_DS3_v2" }, "driver_instance_source": { "node_type_id": "Standard_DS3_v2" }, "effective_spark_version": "9.1.x-cpu-ml-scala2.12", "state": "TERMINATED", "state_message": "Inactive cluster terminated (inactive for 30 minutes).", "start_time": 1652706217345, "terminated_time": 1656371010258, "last_state_loss_time": 1656369024515, "last_activity_time": 1656369067872, "last_restarted_time": 1656369024595, "autoscale": { "min_workers": 1, "max_workers": 3 }, "default_tags": { "Vendor": "Databricks", "Creator": "xxxxx", "ClusterName": "alex-test", "ClusterId": "0516-130337-t4f355at", "Environment": "DEV", "Org": "Enterprise" }, "cluster_log_status": { "last_attempted": 1656370843229 }, "termination_reason": { "code": "INACTIVITY", "type": "SUCCESS", "parameters": { "inactivity_duration_min": "30" } }, "init_scripts_safe_mode": false }

Result from the script:
+ CLUSTER_NAME=alex-test
++ databricks clusters list --output json
++ jq -r --arg cluster_name alex-test '.clusters[]? | select(.cluster_name == $cluster_name)'
parse error: Invalid numeric literal at line 1, column 6
+ CLUSTER_INFO=

**Comment by wader** [comment]
One tricky might be to replace jq with `tee /tmp/output` in the script to see what is written

**Comment by amillion8** [comment]
The answer to your question #1 is that there’s nothing different running script from running it from the terminal – I use same terminal window to execute commands and the script. Same environment, same configs, same everything.

I ran the script (or to be exact, just this portion) without using jq, and it produced a valid json – it return a list of all clusters. I ran the output against json validator and it came back as valid

Alex
(847) 845-6940

**Comment by amillion8** [comment]
Thank you Mattias,

I now see a different error and will investigate further. Please keep this case open for a little longer while I do that.

Alex
(847) 845-6940

**Comment by amillion8** [comment]
I have found a solution, closing this ticket

**Comment by wader** [comment]
Nice, care to share what it was? Maybe useful for others
