### ISSUE TITLE
Ability to list or iterate module functions

### ISSUE THREAD

**Issue by eddiewebb** [stedolan/jq#2465]
My use case is odd, and if it doesnt apply more widely I understand.

I'd like to be able to import a module and just execute all functions there.

WHY?!
Testing.

I find JQ a well known and powerful format for JSON assertion testing.

## Example

I have a core module with testing helpers (`validate` , `assert` , etc)  (credit: Srinath Sankar)

Developers author individual `.jq` modules using those to define custom tests.

```
# must be relative path to assertion utility
include "../utilities/assert";

def check_decision:
  # Declaration
  . as $response
  # Empty array to collect responses
  | []
  # Assertions
  | assert($response | type == "object"; "Response is not an object")
  | assert($response.status | . == "HARD_FAIL"; "Status not HARD_FAIL")
  | assert($response.hard_failures | type == "array"; "hard_failures not an array")
  | assert($response.hard_failures | length == 2; "Expected 2 hard failures")
  # Output
  | validate;
```

THe "testing tool" then loops all cases, imports their custom.jq file, and calls a single, pre-agreed function name `check_decision`.

```
jq -L test_data/utilities/ -L $folder -M 'include "assert"; include "assertion"; check_decision' 

# exits with 0 or prints error and non-zero exit
```

But I'd like to support many test cases inside the single file.

```
jq -L test_data/utilities/ -L $folder -M \
          'include "assert"; \
           include "assertion"; \
           "assertion" | run_all' 

```

Where `run_all` would be my own custom function using some module built-in that takes a module name or object and spits out an array of function names.

```
for <name> in "my_module" | SOME_BUILTIN_THAT_EXPOSES_FUNCTION_ARRAY
....call MODULE::NAME
```

**Comment by wader** [comment]
Currently standard jq lacks reflection, eval, AST parsing or call function by name support and I don't think it will be added any time soon. But I can see some possible solutions:

- Use program to pattern match (regex? `^def\s+([\w_]+).*$` etc) on the test source to find test functions names, then generate a string with jq code to call them and give that to jq
- Run your own modified verison of jq with additional support for reflection, eval etc
  If you want to see example how that can be done (with gojq) you can look at https://github.com/wader/fq which has some (non-public) support for basic reflection (the `scope` function), `eval` and AST parsing (`_query_fromstring`).

**Comment by eddiewebb** [comment]
> * Use program to pattern match (regex? `^def\s+([\w_]+).*$` etc) on the test source to find test functions names, then generate a string with jq code to call them and give that to jq


Thanks @wader - this is the route I ended up taking and it works well enough.  Thanks!

**Comment by eddiewebb** [comment]
> @eddiweb - Neither jq nor gojq has anything like what you have described, but if you are not already familiar with the `--run-tests [filename]` option, it might be worth your while becoming more familiar with it. The option is described on the jq man page, though only minimally.
> 
> Another point which may be worth your consideration is that if all the modules you want to be able to test in a uniform way have a distinguised testing function (e.g. `def runtests: ...`), then you can easily test each module in a uniform way along the following lines:
> 
> ```
> import "test_module" as mymodule;
> mymodule::runtests
> ```

Thanks, the problem is that I wont know the method names in advance and they will be numerous per file. The --run-tests seemed more about testing jq, not asserting particular json structure.

Anyhow the suggestion of @wader  works well enough for me and we can consider this ask closed.

**Comment by wader** [comment]
@eddiewebb Great 👍  and please give me a shout if you end up building something generic, think i could use something like that
