### ISSUE TITLE
Inproper select behavior inside string interpolation

### ISSUE THREAD

**Issue by sdomi** [stedolan/jq#2476]
**Describe the bug**
While using multiple levels of string interpolation, jq improperly handles the `select()` operator.

**To Reproduce**
Consider the following snippet:
```
jq '"\(select(.nyaa) | .nyaa) asdf"'
```

With no `nyaa` key present (e.g. `{"meow":"asdf"}` input data), this snippet does not return anything. With it present (e.g. `{"nyaa":"uwu"}`), it returns both the contents of the `nyaa` key and the string `asdf`.

**Expected behavior**

```
jq '"\(if .nyaa != null then .nyaa else "" end) asdf"'
```

When `if` is used instead of `select()`, jq always returns the string `asdf` (as it should).

Furthermore, if `""` is replaced with `empty`, it behaves just like `select()` 

**Environment (please complete the following information):**
 - OS and Version: Alpine Linux edge
 - jq version: jq-master-v20200122-107-g1c092dff7c

**Comment by wader** [comment]
Hi, `select` works a bit differently compared to `if`. When the select condition evaluates to false it will backtrack (`empty`). As you also noticed it is defined like this `def select(f): if f then . else empty end;`.

So `echo '{"meow":"asdf"}' | jq '"\(select(.nyaa) | .nyaa) asdf"'` will end up as `"\(empty) asdf"` and i guess that can be seen as `empty + " asdf"` which i think make sense does not output any value.

I think you can use the `//` operator to get what you want, either `'"\(select(.nyaa).nyaa // "") asdf"'` or `'"\(.nyaa // "") asdf"'`, but be aware how `//` works with `null` and `false`.

**Comment by sdomi** [comment]
Looks like it's not a bug after all. Thanks for the clarification and the note about `//`, I haven't heard about it before.
