### ISSUE TITLE
jq doen't support numeric fields?

### ISSUE THREAD

**Issue by tm-107** [stedolan/jq#2497]
**I have the following json data**

```
{
  "inverters": [
    {
      "serial": "xxxxxxxxxxxx",
      "0": {
        "Power": {
          "v": 0,
          "u": "W",
          "d": 1
        }
      },
      "events": 1
    }
  ],
  "total": {
    "Power": {
      "v": 0,
      "u": "W",
      "d": 1
    }
  }
}
```

**What works fine:**
`jq .inverters[0].serial`
or
`jq .total.Power.v`

**What doesn't work:**
`jq .inverters[0].0`
or
`jq .inverters[0].0.Power.v`

Is this a bug or a desired behaviour?

**Comment by wader** [comment]
Hi, object keys needs to be strings, so try `.inverters[0]."0".Power.v` or `.inverters[0].["0"].Power.v`

**Comment by tm-107** [comment]
Hi, unfortunately no success

```
jq .inverters[0]."0".Power.v
jq: error: Invalid numeric literal at EOF at line 1, column 3 (while parsing '.0.') at <top-level>, line 1:
.inverters[0].0.Power.v
jq: error: syntax error, unexpected LITERAL, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
.inverters[0].0.Power.v
jq: 2 compile errors
```

```
jq .inverters[0].["0"].Power.v
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
.inverters[0].[0].Power.v
jq: 1 compile error
```

**Comment by pkoppstein** [comment]
@wader gave the jq program, which would have to be suitably quoted if it is entered at a shell prompt, e.g.

          jq '.inverters[0]["0"]'

**Comment by tm-107** [comment]
@wader 
Thank you very much!
I also tried that, but not without the point ...

`jq .inverters[0].["0"].Power.v` didn't work, but
`jq .inverters[0]["0"].Power.v` worked fine :-)
