### ISSUE TITLE
Print strings without quotes

### ISSUE THREAD

**Issue by phihag** [stedolan/jq#250]
When I print strings, they are always surrounded with quotes:

```
$ echo '{"search":"jq!"}' | jq '@uri "http://www.google.com/search?q=\(.search)"'
"http://www.google.com/search?q=jq!"
```

(This is with jq 18e828f17cc3f87728d57e424814df45b5eec7f1 ). I'd like to feed this output into a program that expects URLs to be newline-separated and verbatim. How can I get the output without quotes, i.e.

```
http://www.google.com/search?q=jq!
```

**Comment by socketpair** [comment]
Instead of this one should implement `jq '  xxxxxx | to_raw_string'`

**Comment by k001** [comment]
Why is referenced to Elasticsearch this one @wgrzelak ?

**Comment by wgrzelak** [comment]
I have used this topic as an example of simplifying an output of `jq` command :)

**Comment by dotnetchris** [comment]
Thank you @stedolan

**Comment by userException** [comment]
> `jq -r` (or `jq --raw-output`)

I am using fastlane to do some dynamic changes to my iOS app's property list file.  The sybtax goes like this:

display_name: sh("jq -r .app_name ../billerConfig.json")

- display_name is the property of fastlane, which changes the name of my app.
- sh: signifies that we are trying to run a shell script in fastlane
- Rest of the command is understandable

Now when I see my project, I see there is a huge white space and then next line inserted, at the end of the app name. I don't think this is the issue with jq but just asking here, if it could be ?

**Comment by smac89** [comment]
@userException See if this helps:

https://github.com/stedolan/jq/issues/1735#issuecomment-520650243

**Comment by userException** [comment]
Using "chomp" worked for me: sh("jq -r '.appName' ../billerConfig.json").chomp

**Comment by celesteking** [comment]
![very-important](https://user-images.githubusercontent.com/748075/97054422-60291380-154a-11eb-880a-8ef05787699a.jpg)

**Comment by vintnes** [comment]
@celesteking here's a fun fact: over 300 people subscribe to this entire issue board and just received that image in their work emails.

Another fun fact: many people are working remotely and regularly sharing their screens.

**Comment by celesteking** [comment]
What's done is done. I really like jq, just wanted to share my delightment with the usage of this tool. And it's not about the tool itself, absolutely not, but about the thorough documentation and the community. I've never had a problem looking up the usage examples and finding the right answer on google (either leading here, to issues section, or on SO).

Pressing the "like" button [won't "subscribe" you](https://github.com/isaacs/github/issues/631) to the issue, so it narrows down to just 9 ppl ;)

**Comment by wtlangford** [comment]
> Pressing the "like" button [won't "subscribe" you](https://github.com/isaacs/github/issues/631) to the issue, so it narrows down to just 9 ppl ;)

I see 317 watchers of the repo, but regardless of the number, it's still not appropriate. I've removed the image.

**Comment by 4thel00z** [comment]
@socketpair 
you can just use 
`jq <whatever> | cut -d '"' -f 2`

**Comment by AQS-DTheuke** [comment]
If you have an array that you want to output as plain string you have to use:

````sh
jq '.[]' -r
````

or

````sh
jq 'map(.textPayload) | .[]' -r
````
