### ISSUE TITLE
Using `select` with `-e`: exit code only depends on last item

### ISSUE THREAD

**Issue by pswaminathan** [stedolan/jq#2500]
**Describe the bug**
Using `select`, the exit code when using the `-e` flag depends only on the last item processed, not any item.

**To Reproduce**
```
$ echo '{"some": "out", "success": true}\n{"some": "out", "success": false}' | jq -e 'select(.success)' 1>/dev/null; echo $?
4

$ echo '{"some": "out", "success": false}\n{"some": "out", "success": true}' | jq -e 'select(.success)' 1>/dev/null; echo $?
0
```

**Expected behavior**
Both of the above lines produce the same output (when run without the output flags):
```
$ echo '{"some": "out", "success": true}\n{"some": "out", "success": false}' | jq -e 'select(.success)'
{
  "some": "out",
  "success": true
}
```

I would expect the exit code to be 0 for both, as valid output was produced. Instead, the exit codes differ depending on whether or not the _last_ item produced a valid output.

**Environment (please complete the following information):**
 - OS and Version: macOS Monterey 12.6.1
 - jq version 1.6

**Additional context**
N/A

**Comment by wader** [comment]
Hi, could you try jq master? `brew install --HEAD jq` if your using homebrew. I suspect this might be fixed by https://github.com/stedolan/jq/pull/1697 that was merged after jq 1.6

**Comment by pswaminathan** [comment]
Yes, that fixed it! I tried to look for open issues first. Seems I didn't search effectively enough, as I didn't see the issue that fixed. Thanks for your help!

**Comment by wader** [comment]
@pswaminathan 👍 no problem, hope there will be new release eventually
