### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by kloczek** [stedolan/jq#2525]
Last release was in 2016 and since then in gt repo have been already commited +150 commits
https://github.com/stedolan/jq/compare/jq-1.6...master
Do you have ay plans to release new version? 🤔

**Comment by wader** [comment]
Hello, see https://github.com/stedolan/jq/issues/2305

**Comment by kloczek** [comment]
OK so I'll close this ticket 😋

**Comment by wader** [comment]
👍 and let's hope the maintenance issue gets resolve eventually
