### ISSUE TITLE
MAC brew install fails with: The requested URL returned error: 403 

### ISSUE THREAD

**Issue by muharemd** [stedolan/jq#2531]
**Describe the bug**
Installation of jq fails on MAC OS with error message: "UNAUTHORIZED"
Trying manually to get to site below getting this error.
Brew command is failing as well with the same 403 error message.
```
https://ghcr.io/v2/homebrew/core/oniguruma/manifests/6.9.8 cannot be accessed
```
And failing with:
```
 "{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}"
```

**To Reproduce**
Run on MAC OS "brew install jq" and you will get this:
```
==> Fetching dependencies for jq: oniguruma
==> Fetching oniguruma
==> Downloading https://ghcr.io/v2/homebrew/core/oniguruma/manifests/6.9.8
curl: (22) The requested URL returned error: 403                              

Error: jq: Failed to download resource "oniguruma_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/oniguruma/manifests/6.9.8
```

**Expected behavior**

**Environment (please complete the following information):**
 - OS and Version:  macOS Ventura
 - jq version is not known to me as i am not authorized to access the repo to download the files.

**Additional context**

**Comment by pkoppstein** [comment]
Browsing stackoverflow.com reveals this observation:

> My work network/VPN was causing this error. I was able to download successfully disabling my VPN and using my mobile network connection.


[https://stackoverflow.com/questions/70338745/brew-install-fails-with-403-unauthorized]

**Comment by muharemd** [comment]
Thank you @pkoppstein for your help here.
Would you please check if you can access that public site/link?
I tried on my phone and home laptop which are not behind any firewall or limited by VPN, still having the same "unauthorized" message.

**Comment by pkoppstein** [comment]
I have the same problem with the ghcr.io link, but perhaps the relevant question is why that URL is being used at all.
The brew recipe for oniguruma refers only to 
https://github.com/kkos/oniguruma/releases/download/v6.9.8/onig-6.9.8.tar.gz

So perhaps you should try installing oniguruma directly, i.e.`brew install oniguruma`

I'm out of my depth here, but I've read that sometimes setting the environment variable HOMEBREW_FORCE_BREWED_CURL makes a difference.  In bash, you'd run:

    export HOMEBREW_FORCE_BREWED_CURL=1

**Comment by mlohnash** [comment]
I have the same issue as @muharemd, on a MAC and `brew install jq` fails at oniguruma. 

I tried the `brew install oniguruma` and was able to successfully install jq through brew. 

Thank you!

**Comment by muharemd** [comment]
Thank you people for helping with this, both of those you mentioned @mlohnash are puling from the same repo which for me is: 403 "UNAUTHORIZED"
I manually downloaded package and placed to the MAC and it is working, just later have to manually check for updates.
I exported this variable as suggested, did not help.
`export HOMEBREW_FORCE_BREWED_CURL=1`

```
host$ brew install oniguruma
==> Fetching oniguruma
==> Downloading https://ghcr.io/v2/homebrew/core/oniguruma/manifests/6.9.8
curl: (22) The requested URL returned error: 403                              

Error: oniguruma: Failed to download resource "oniguruma_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/oniguruma/manifests/6.9.8
```

**Comment by muharemd** [comment]
Thank you @pkoppstein for your help here.
Would you please check if you can access that public site/link?
I tried on my phone and home laptop which are not behind any firewall or limited by VPN, still having the same "unauthorized" message.
