### ISSUE TITLE
test expression ignores trailing white space

### ISSUE THREAD

**Issue by lcarva** [stedolan/jq#2534]
**Describe the bug**
`test` always seem to ignore trailing white space.

**To Reproduce**
```
jq -n '"one\n" | test("^one$"; "s")'
```
Returns `true`

**Expected behavior**
The expression above should return `false` because single line mode is being used, and the value being checked has a character that is not specified in the regex.

**Environment (please complete the following information):**
 - OS and Version: `Fedora Linux 37`
 - jq version: `jq-1.6`

**Additional context**
I have tried multiple combinations of the expression, but it always evaluates to `true`:

```
$ jq -n '"one\n" | test("^one$"; "s")'
true

$ jq -n '"one\n" | test("\\Aone\\Z"; "s")'
true

$ jq -n '"one\n" | test("^one$"; "m")'
true

$ jq -n '"one\n" | test("\\Aone\\Z"; "m")'
true

$ jq -n '"one\n" | test("^one$"; "p")'
true

$ jq -n '"one\n" | test("\\Aone\\Z"; "p")'
true
```

**Comment by lcarva** [comment]
Workaround:
```
jq -n '"one\n" | test("^one$") and (test("\n") | not)'
```

**Comment by wader** [comment]
Hi, haven't used the `s` flag myself. Oniguruma (the RE engine jq uses) says that the `s` flag makes `^` behave as  `\A`  and `$` as `\Z'` https://github.com/kkos/oniguruma/blob/28ee452bc98501b9b82e088948044fb810f2833c/doc/API#L79 and `\Z` means "end of string, or before newline at the end" https://github.com/kkos/oniguruma/blob/master/doc/RE#L180 so maybe it makes sense?

**Comment by lcarva** [comment]
Thanks for the prompt response! 

The second link you shared documents `\z` (lower-case) as "end of string". I had no idea it existed. 

Sure enough, this works as expected:

```
$ jq -n '"one\n" | test("\\Aone\\z"; "p")'
false

$ jq -n '"one" | test("\\Aone\\z")'
true
```

**Comment by wader** [comment]
👍 nice, ah good to know!
