### ISSUE TITLE
`isnan` is not working as expected 

### ISSUE THREAD

**Issue by matrixzj** [stedolan/jq#2540]
expected result for `isnan` for "string" should be `true`

```bash
$ echo '["string"]' | jq '.[] | type'
"string"

$ echo '["string"]' | jq '.[] | isnan'
false

```

jq version
```bash
$ jq --version
jq-1.6
```

**Comment by pkoppstein** [comment]
@matrixzj - `isnan` means `is NaN`, so clearly your expectations needs adjusting.

There is an interesting discrepancy between jq and gojq on the behavior of `isnan` in the presence of non-numbers:

`gojq: isnan cannot be applied to: string ("string")`

It seems to me that jq's adherence to the principle that `is*` predicates shouldn't raise errors when given valid inputs is laudable.

**Comment by emanuele6** [comment]
No, `isnan` is working as expected. `isnan` is the `isnan()` function from C's standard math library for floating point numbers; it is true if the input is a floating point number representation of `nan`.

```bash
bash-5.1$ jq -n 'nan | isnan'
true
bash-5.1$ jq -n 'infinite / infinite | isnan'
true
bash-5.1$ jq -n '40 | asin | isnan'
true
bash-5.1$ jq -n '1 | isnan'
false
bash-5.1$ jq -n '"foo" | isnan'
false
```

If you an expression that returns true if the input is not a number, use `type!="number"`.

Note that `nan | type == "number"` is `true`, but `jq` serialises it to JSON as `null`. (This only matters if you are purposefully doing floating point math in `jq`, using `infinite`/`nan`/`asin` or other math functions that can return a invalid ("nan") floating point number).

**Comment by matrixzj** [comment]
@emanuele6  THanks for explanation. 

So `isnan` will identify inputs are a floating number or not. That's why `int` and `string` will be also resulted as `false`. 

Maybe, we can do some improvements with `jq` manual.

**Comment by emanuele6** [comment]
> So `isnan` will identify inputs are a floating number or not.

Not quite. `1.9 | isnan` is also false.

This is a technical detail, but `jq` internally used the `double` (double precision floating number) type from C.

And the format used to represent those allows representing error values called [`NaN`](https://en.wikipedia.org/wiki/IEEE_754#NaNs) to represent unrepresentable results (e.g. `infinite/infinite`, `-0/0`, the arcsine/arcosine (`asin`/`acos`) of any value not within `[-1,1]`, the square root (`sqrt`) of a negative number, etc).

You use `isnan` function to check if a math computation resulted in an error, and handle the error (e.g. `.value | asin | if isnan then 1 else . end` returns the arcsine of `.value`, but defaults to `1` if the arcsine of `.value` cannot be computed. Math functions also behave like this in other languages e.g. `Infinity / Infinity`, and `Math.asin(40)` will not throw an error, and will just return `NaN`.
