### ISSUE TITLE
`index()` returns byte offset while string slice operates on code points

### ISSUE THREAD

**Issue by he-la** [stedolan/jq#2544]
**Describe the bug**
Using `index(pattern)` returns the byte offset in the input string, which is inconsistent with how string slicing works. This causes confusing / dangerous behaviour when the two are combined.

**To Reproduce**
In this example, `”` is `RIGHT DOUBLE QUOTATION MARK`, which takes 3 bytes in unicode.
```
echo '"”#"' | jq '
(. | index("#")) as $hashtag_idx |
.[$hashtag_idx:]'
```
outputs the empty string
```
""
```
because `index("#")` is `3`.

**Expected behavior**
The most intuitive behaviour would be to output
```
"#"
```
i.e. the substring starting from the character that was searched for with `index()`.

**Environment (please complete the following information):**
 - NixOS 22.11, nixpkgs rev. `103fe0800b9d739c279997561c9da9d242d5b6b8`
 - `jq-1.6`

**Additional context**
This might be intended behaviour (?). In that case I'd voice the opinion that it's dangerous, though I probably don't grasp the full scope of `index()` usecases.

**Comment by emanuele6** [comment]
You can use `first(scan(".") | select(. == "#"))` or `first(scan(".") | select(. == "#")) // null` as a workaround.

**Comment by pkoppstein** [comment]
The jq wiki has a page devoted to ["How to Avoid Pitfalls"](https://github.com/stedolan/jq/wiki/How-to:-Avoid-Pitfalls).

It includes a section [index/1 is byte-oriented but match/1 is codepoint-oriented](https://github.com/stedolan/jq/wiki/How-to:-Avoid-Pitfalls#index1-is-byte-oriented-but-match1-is-codepoint-oriented)

Here is a copy of the codepoint-oriented version of `index/1` for strings given there:
```
# codepoint-oriented version of `index/1` for strings
# e.g. ("”#a" | myindex("#a")) yields 1
def myindex($string):
  ($string|length) as $sl
  | if $sl > length
    then null
    else
      explode as $x
      | ($string|explode) as $s
      | first(range(0; 1 + length - $sl) as $i
              | select($x[$i: $sl+$i] == $s) | $i) // null 
   end;
```

**Comment by pkoppstein** [comment]
Backwards compatibility is the big issue.  

(The anomaly is surely an historical artifact: in the very early days of jq, the creator of jq seems mainly to have been interested in having an `indices` filter that would work similarly for both array and string inputs, and used the machinery that was available at the time for handling the strings.)

One day, perhaps, `offset/1` will be defined to address the two major issues with index/1`, the other one being that the latter is horrendously inefficient because it is defined using `indices/1`.

**Comment by he-la** [comment]
Closing since this appears to be well-known and wontfix until a `jq-2.0` comes along or `offset/1` is introduced. Thanks for the tips everyone!
