### ISSUE TITLE
I/O primitives

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#255]
`read` fits in well enough (see the `handles` branch of my github clone of jq).

`open` and `write` should probably require jq_compile*() to provide more control over whether a jq program can call such builtins... because one very nice property of jq so far is that its programs are strictly filters, referentially transparent, with no side-effects -- nice little sandboxes.  It should remain that way by default, IMO.

**Comment by nicowilliams** [comment]
Superseded by #925.

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/pull/1005
