### ISSUE TITLE
Cannot index array with string "imageTag"

### ISSUE THREAD

**Issue by jedrekdomanski** [stedolan/jq#2551]
**Describe the bug**
I am not able to filter results based on key name in an array

**To Reproduce**
I fetch all images from my AWS ECR by a repository name and region
```
aws ecr list-images --repository-name myrepo --region myregion                                                                                                                                                                                   
{
  "imageIds": [
  {
    "imageDigest": "sha256:836113eb1f6ed347ad91749c3ac37a5422130131b6e076e76d",
    "imageTag": "someTag1"
  },
  {
    "imageDigest": "sha256:0f5090c3fc8eb271a8affd661468cf026d7ea210a2",
    "imageTag": "someTag2"
  },
  {
    "imageDigest": "sha256:a4b7e8966c0a8878af02aaa211b170f628947c755e",
    "imageTag": "someTag3"
  }
  ]
}
```
I grep by the only key "imageIds"
```
aws ecr list-images --repository-name lms --region us-east-2 | jq '.imageIds'
```
and I get an array of objects
```
[
  {
      "imageDigest": "sha256:836113eb1f6ed347ad91749c3ac37a",
      "imageTag": "someTag1"
    },
    {
      "imageDigest": "sha256:0f5090c3fc8eb271a8affd661468cf026d",
      "imageTag": "someTag2"
    },
    {
      "imageDigest": "sha256:a4b7e8966c0a8878af02aaa211b170f62",
      "imageTag": "someTag4"
    }
]
```
then I want to find only the images that match a given `imageTag`. I do it as the documentation says:
https://github.com/stedolan/jq/wiki/Cookbook#filter-objects-based-on-the-contents-of-a-key
```
jq '.imageIds | select(.imageTag | contains("master"))'
```
I get an error
```
jq: error (at <stdin>:326): Cannot index array with string "imageTag"
```

**Expected behavior**
Filter works and returns proper results

**Environment (please complete the following information):**
 - OS macOS Ventura
 - jq version 1.6

**Comment by itchyny** [comment]
Try `.imageIds | .[] | select(.imageTag | contains("master"))`, note the `.[]` to iterate through the array. And `.imageIds | .[]` can be shorten to `.imageIds[]`.

**Comment by wader** [comment]
And can do `.imageIds | map(select(.imageTag | contains("master")))` if you want to iterate, select and collect into an array again.

**Comment by jedrekdomanski** [comment]
@itchyny That worked! Is the documentation not clear enough or am I missing something?

**Comment by jedrekdomanski** [comment]
Oh, probably because some images are untagged...
