### ISSUE TITLE
Typo on ariness at jq wiki

### ISSUE THREAD

**Issue by hansonchar** [stedolan/jq#2556]
**Describe the bug**

At https://github.com/stedolan/jq/wiki/jq-Language-Description#Lexical-Symbol-Bindings-Function-Definitions-and-Data-Symbol-Bindings

"E.g., in the body of a function defined as `def cond(c; t; f): if c then t else f end;` the function symbols `c`, `t`, and `f`, are bound to the first, second, and third argument expressions, respectively, and the name of the function, `cond` with ariness 2, is made visible to all jq code that follows its definition."

`cond` in this example has an ariness of 3, not 2.

**Comment by wader** [comment]
Hi, i think you should be able to edit the wiki

**Comment by hansonchar** [comment]
Good point.  Done.
