### ISSUE TITLE
select duplicates the input when iterator is used in the argument

### ISSUE THREAD

**Issue by dayyeung** [stedolan/jq#2570]
**Describe the bug**
According to the docs, `select` should either produce its input unchanged or produce no output. It is not the case in the following example.

**To Reproduce**
```
$ jq -n '{"a":[1,2,3]} | select(.a[])'
{
  "a": [
    1,
    2,
    3
  ]
}
{
  "a": [
    1,
    2,
    3
  ]
}
{
  "a": [
    1,
    2,
    3
  ]
}
```

**Expected behavior**
```
{
  "a": [
    1,
    2,
    3
  ]
}
```

**Environment (please complete the following information):**
 - OS and Version: macOS 13.2.1
 - jq version: 1.6

**Comment by wader** [comment]
Hi, i think you probably want `.`:
```sh
$ jq -n '{"a":[1,2,3]} | .'
{
  "a": [
    1,
    2,
    3
  ]
}
```

So what happens is that for `<input> | select(<condition>)` select will output `<input>`  for each true output of `<condition>`, the condition will get `<input>` as input and in most practical cases it only output one value.  The condition in this case is `.a[]` which will output three numbers `1`, `2` and `3`, can try with `jq -n '{"a":[1,2,3]} | .a[]'`, all which are considered true so select outputs `<input>` three times.

**Comment by dayyeung** [comment]
@wader Thanks for the explanation.

The example is just a minimal test case. The following might make more sense:

```
jq -n '{"a":[1,2,3]} | select(.a[] | . > 1)'
```

I understand there are different ways to achieve it, but this is short and intuitive.

I guess the [docs](https://stedolan.github.io/jq/manual/#select(boolean_expression)) is so simple that this is techinically not incorrect, just undocumented behavior. This is however IMO very unintuitive, and probably not intended.

FYI [yq](https://github.com/mikefarah/yq) seems to agree:

```
$ yq -n '{"a":[1,2,3]} | select(.a[])' -o json
{
  "a": [
    1,
    2,
    3
  ]
}
```

Feel free to close the issue if this is not a bug.

**Comment by wader** [comment]
> @wader Thanks for the explanation.
> 
> The example is just a minimal test case. The following might make more sense:
> 
> ```
> jq -n '{"a":[1,2,3]} | select(.a[] | . > 1)'
> ```

Then i think you probably want:
```sh
$ jq -n '{"a":[1,2,3]} | .a[] | select(. > 1)'
2
3
```

> I understand there are different ways to achieve it, but this is short and intuitive.
> 
> I guess the [docs](https://stedolan.github.io/jq/manual/#select(boolean_expression)) is so simple that this is technically not incorrect, just undocumented behavior. This is however IMO very unintuitive, and probably not intended.
> 
> FYI [yq](https://github.com/mikefarah/yq) seems to agree:
> 
> ```
> $ yq -n '{"a":[1,2,3]} | select(.a[])' -o json
> {
>   "a": [
>     1,
>     2,
>     3
>   ]
> }
> ```
> 
> Feel free to close the issue if this is not a bug.

I think you might misunderstand how generators and select work. select does not digg into it's input and select our things to output, it only evaluates a condition based on the input and if true it outputs the same input else nothing. In jq it's implemented like this `def select(f): if f then . else empty end;`. See this for example:
```sh
$ yq -n '{"a":[1,2,3]} | select("can by any true value", "even another strings")' -o json
{
  "a": [
    1,
    2,
    3
  ]
}

$ jq -n '{"a":[1,2,3]} | select("can by any true value", "even another strings")'
{
  "a": [
    1,
    2,
    3
  ]
}
{
  "a": [
    1,
    2,
    3
  ]
}
```

Im not sure why yq only outputs once but maybe that is some design decision. I haven't used yq myself much but i think your query with yq would be something like this:

```sh
$ yq -n '{"a":[1,2,3]} | .a[] | select(. == 2 or .== 3)' -o json
2
3
```

So what happens is that `.a[]` will iterate the array and output each value, so `select` we evaluated three times.

For some reason i can't get `>` to work with numbers in yq, no idea what is going on:

```
$ yq -n '1 > 2' -o json
Error: Parsing expression: Lexer error: could not match text starting at 1:3 failing at 1:4.
	unmatched text: ">"
$ yq -n '1 + 2' -o json
3
```

**Comment by wader** [comment]
Turn out i had a version old version of yq, now it works:
```
$ yq -n '{"a":[1,2,3]} | .a[] | select(. > 1)' -o json
2
3
```

**Comment by emanuele6** [comment]
`yq` (or at least the program named "yq" that you linked) is not a `jq` implementation, it says it uses a "jq"-like syntax, but in reality it is very different for any program that is non trivial.

It is a bit of a stretch to say it is not documented, it is just a fundemental feature of the language, functions that take `$` arguments, and many operators including `+` and `if-then-else`, evaluate multiple times for each value generated by their operands:
```jq
(
  def f($s): [ $s | ascii_upcase ];
  f("hi", "hello", "foo")
  # this is the same as f("hi"),f("hello"),f("foo")
),
(
  (1,2,3) + 4 # same as (1 + 4),(2 + 4),(3 + 4)
)
```
The documentation does say ["If the condition `A` produces multiple results, then `B` is evaluated once for each result that is not false or null, and `C` is evaluated once for each false or null."](https://stedolan.github.io/jq/manual/#if-then-else), and you can see that `select(foo)` is `if foo then . else empty end`.
This happens and should be expected to happen in `jq`.

**Comment by pkoppstein** [comment]
First I'd like to confirm that @emanuele6's contribution to this thread is spot on. There is no doubt that the behavior in question is intended; it is in fact fundamental to the way jq is stream-oriented.   There is ample documentation about that.

Second, it is true that the jq "manual" is quite terse, but that is in general also intentional.  Thus, in the section on `select`, we find the statement that seems to be the source of the OP's perplexity:

    The function select(foo) produces its input unchanged if foo returns true for that input, and produces no output otherwise.

This is a terse way of saying: 

    The jq expression `select(foo)` produces its input unchanged for each value in the stream produced by `foo` that is truthy for that input, and produces no output for that value otherwise.

Since that is fairly convoluted, I doubt it will help much, so perhaps the main conclusion of this thread is that the `Examples` section should be expanded to include an example, such as: `1,2 | select(true, 3, false, null)`

**Comment by emanuele6** [comment]
Also I am not even sure what you would want `select(.a[])` to do.

You mentioned mikefarah's `yq`; there, `select(.a[] > 1)` for example, as far as I can tell, is equivalent to using `any` in `jq`:
```jq
{a:[-1,0,1]},
{a:[-1,0,1, 2]},
{a:[1,1,1]},
{a:[2, 3, 4]} |
select(any(.a[]; . > 1)) # or: select(any(.; .a[] > 1))
# output:
#   {"a":[-1,0,1, 2]}
#   {"a":[2, 3, 4]}
```
Or, to generalise, `select(f)` in mikefarah's `yq` is equivalent to `select(any(.; f))` in `jq`: if that is what you want, you can use that.

If instead you want `select(.a[] | . > 1)` to output the input with all the elements of `.a` that are not `> 1` removed, you should use `del()`:
```jq
{a:[1,2,-1,3,0,4]} |
del(.a[] | select(. <= 1)) |
. # {"a":[2,3,4]}
```
Or, alternatively, `.a |= map(select(. > 1))`.

**Comment by dayyeung** [comment]
Thanks for all the explanations.

My expected behavior would be what @emanuele6 described in the `any` case.
I guess I just find it unintuitive and do not think it will ever be useful for `select` to duplicate the input (except for specifically utilizing this side-effect).

I still like the `yq` behavior more but I do understand the rationale to make it consistent across all functions.

I think the issue can be closed, thanks!

**Comment by emanuele6** [comment]
> I guess I just find it unintuitive and do not think it will ever be useful for select to duplicate the input (except for specifically utilizing this side-effect).

But it is not a side effect, it is just weird to call with `select/1` with a `.[]` or `..` in it.

A `.[]` in jq is like a for loop in other languages. It will run the function multiple times, and you should expect it to do so. (unless the function is taking the expression as a non-`$` argument, and using it in a lambda-like way.)

> I think the issue can be closed, thanks!

Why don't you close it then?

**Comment by dayyeung** [comment]
> unless the function is taking the expression as a non-`$` argument, and using it in a lambda-like way

That's the thing. This is what I expected because of the nature of `select`.

> but you are just making select more limited and complex for no reason at that point

Let's just agree to disagree.

> Why don't you close it then?

I thought maybe you might want to keep the issue open for adding an example to the docs as suggested by @pkoppstein?
I will just close it then.
