### ISSUE TITLE
awk-like BEGIN/END would be nice

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#259]
Ideally every jq program that includes a BEGIN and/or END user-defined function should have those functions invoked once at begin-/end-time (with null as input) as if their invocation were the top-level program.

State could be kept in a "buffer" or file (see https://github.com/nicowilliams/jq/tree/handles).  Ideally the output of BEGIN could also be bound to a `$variable` that's visible to the real top-level program.

I've looked into what it would take to do this.  My best idea is to have a function that replaces the top-level bytecode (which is trivial to identify) with bytecode to invoke BEGIN/END as appropriate, and a small change to main() so it can tell jq_start() that the current invocation is precedes the first or follows the last.  Doing this in parser.y looks particularly difficult, but it should be simple to just swap out the top-level bytecode.

**Comment by brainstorm** [comment]
Sorry but I don't see how jq's `-n` option could be used to emulate awk's BEGIN :-S 

I'm trying to have the following prefix/header:

```
$ORIGIN domain.com.
$TTL 1h
```

Then the next entries will be populated [by this oneliner in jq](https://www.commandlinefu.com/commands/view/24090/wip-route53-export-hosted-zone) to migrate DNS records from AWS's Route53:

```bash
$ aws route53 list-resource-record-sets --hosted-zone-id <ZONE_ID> --profile prod | jq -r '.ResourceRecordSets[] | [.Name, .Type, .ResourceRecords[0].Value] | join("\t")' -
```

Could you illustrate how you ended up solving this small awk-BEGIN brain teaser with jq? :)

**Comment by pkoppstein** [comment]
@brainstorm - It would appear that this (closed) issue has little to do with your problem, and you might be better off ignoring it.

In simple cases, you can just use the "," operator to add "beginning" and/or "ending" text, and it looks as though that should be sufficient in your case:

       jq -r '"BEGINNING", "TEXT", myprogram, "ENDING", "TEXT"'

Things might be a bit more complicated if the "BEGIN" or "END" block must read from STDIN.  That's where `-n` might come in, but that's just incidental to the use of `input` and/or `inputs`.

Anyway, if I were you, I'd focus on the actual task you have.  If you have further questions about solving your problem, please ask them at stackoverflow.com with the jq tag: https://stackoverflow.com/questions/tagged/jq
