### ISSUE TITLE
characters encoding change

### ISSUE THREAD

**Issue by lazna** [stedolan/jq#262]
downloaded json utf-8 encoded data under windows is displayed fine as a simple curl.exe output, but if piped into jq (......| jq.exe ".")  it displayed all output as expected but with crippled diacritic.

How can I preserve characters encoding?

Petr Laznovsky

**Comment by nicowilliams** [comment]
Is this a dup of #824?

**Comment by svnpenn** [comment]
#939

**Comment by svnpenn** [comment]
#811
