### ISSUE TITLE
Problems with the `--online-input` option

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#267]
When using --online-input, the jq program can't distinguish between multiple top-level array inputs.  And newlines work like commas to separate top-level array elements.

Possible fixes for the first problem include:

1) consume just one top-level array and exit if any other type of top-level value is read instead, and exit after consuming at most one top-level value (an array).

2) in online input mode inputs should be seen as arrays of index and value, with the index being numeric if the top-level value is an array, strings if the top-level value is an object, or null if the top-level value is a scalar.

(1) seems heavy-handed.  (2) is more work.  (2) also generalizes to more than the top-level, and could be used to parse inputs in an entirely online manner.

(2) seems like the way to go.

Also, the -I short-hand for --online-input should be removed and made available instead for other purposes, such as defining a library include path.

**Comment by tttp** [comment]
Hi,

The man page still reference the online-input option

I'm not sure I understand what is the alternative now to handle large json files. Could you clarify?

**Comment by bterlson** [comment]
@nicowilliams I would also like to know what the --online-input replacement is.

**Comment by nicowilliams** [comment]
@bterlson `--stream`

**Comment by bterlson** [comment]
@nicowilliams awesome thanks, I didn't see that in the docs :)
