### ISSUE TITLE
Too many commas causes output to repeat

### ISSUE THREAD

**Issue by jkleint** [stedolan/jq#269]
I'm trying to pick out many values (10,000) from a large object with many fields (100,000).  So as a small example, if I want to pick out 1 and 3:

    $ echo '{"1":1, "2":2, "3":3}' | jq '.["1"],.["3"]'
    1
    3

First, please let me know if there is a better way to do this.  My current approach is to generate a large jq expression with all the elements I want to pick out, and load it from a file with `-f`.  As a test, this should return the number of elements I requested (at a maximum).  This works fine with up to 3641 elements separated by commas:

    $ echo '{"1": 1}' | jq -f <(seq 3641 | python -c 'import sys; print(", ".join(""".["{}"]""".format(line.rstrip("\n")) for line in sys.stdin))') | wc -l
    3641

But if I ask for 3642, I get twice that:

    $ echo '{"1": 1}' | jq -f <(seq 3642 | python -c 'import sys; print(", ".join(""".["{}"]""".format(line.rstrip("\n")) for line in sys.stdin))') | wc -l
    7282

Looking at the actual output you'll see it repeats.  FWIW it doesn't seem to be a limit on the textual size of the expression, but the number of items.  I'm using jq 1.3 on Ubuntu 13.10 64-bit.

**Comment by dtolnay** [comment]
In 1.5 the boundary seems to have doubled:

    $ echo '{"1": 1}' | ./jq -f <(seq 7282 | python -c 'import sys; print(", ".join(""".["{}"]""".format(line.rstrip("\n")) for line in sys.stdin))') | wc -l
    7282
    $ echo '{"1": 1}' | ./jq -f <(seq 7283 | python -c 'import sys; print(", ".join(""".["{}"]""".format(line.rstrip("\n")) for line in sys.stdin))') | wc -l
    14564

In any case, this is caused by putting the program counter and jump offsets into uint16 variables. I will add a compile error if the bytecode size exceeds 0xFFFF to avoid surprises like this.

**Comment by nicowilliams** [comment]
A few thoughts:

 - The obvious workaround for the 16-bit max bytecode address is to split up one's code into functions.  But having the compiler be smart enough to do it for you is likely to be `ETOOHARD`.

 - relative addressing won't help: the first `FORK` in a chain coding `exp,exp,exp,exp,...` refers to the address of the last expression in the chain.

 - We could have long-jump variants of `FORK`, `JUMP`, and so on if it mattered, or just switch to larger addresses and leave it at that.  Even with large addresses, bytecode units should still be 16-bits (with addresses taking up two).

**Comment by dtolnay** [comment]
I think if this restriction works for Java/Scala/Groovy/Clojure/every JVM language, we shouldn't think too hard about working around it as long as failures don't silently produce incorrect values like they used to.

**Comment by nicowilliams** [comment]
Oh sure, but someone seems to have needed larger bytcode bodies, and these seemed like thoughts that should be recorded in case they might prove useful later.
