### ISSUE TITLE
error: syntax error, unexpected QQSTRING_START, expecting $end

### ISSUE THREAD

**Issue by brewingcode** [stedolan/jq#273]
This is with jq v1.3 on OSX 10.9.1.

I'm unable to access a hash key with a double-quoted string (the key contains special characters). A trivial example shows:

```
$ echo '{"foo": "bar"}' | jq .foo    # without quotes works just fine
"bar"
$ echo '{"foo": "bar"}' | jq '."foo"'    # quoting causes a syntax error
error: syntax error, unexpected QQSTRING_START, expecting $end
."foo"
^
1 compile error
```

[The manual](http://stedolan.github.io/jq/manual/#Basicfilters) shows almost this exact case:

![image](https://f.cloud.github.com/assets/1566363/1969069/21c16d00-82ed-11e3-8827-8fa9152dcd9d.png)

**Comment by mgol** [comment]
The syntax `.foo."bar-baz"` worked for me with latest jq (1.5), the one `.foo.["bar-baz"]` didn't. It seems the docs are incorrect?

**Comment by lluchs** [comment]
Try removing the last dot: `.foo["bar-baz"]`

**Comment by pkoppstein** [comment]
@mgol - You are correct that `.foo.["bar-baz"]` is not supported in 1.5; if you wanted to use the square-bracket notation, you would have to write `.foo | .["bar-baz"]`

The square-bracket notation (i.e. `.[ ACCESSOR ]` where ACCESSOR is an expression that evaluates to a JSON string or integer) is actually the fundamental one (i.e. supported by jq 1.3, 1.4, 1.5 and possibly others).
