### ISSUE TITLE
Unable to extract strings from a json object using jq

### ISSUE THREAD

**Issue by nabadeep** [stedolan/jq#282]
jq '.result.data[0].notes'  fetches 

"{\"recordCountValidation\":\"failure\",\"Metafile Md5\":\"d41d8cd98f00b204e9800998ecf8427e\",\"schemaValidation\":\"failure\"}"

Can somebody fetch me the things further ---
 the recordCountValidation's value as failure
or, the shemaValidation's value as failure.

**Comment by timvisher** [comment]
`jq` is amazing! :)

I have an array:

```
[
  {
    "foo": "bar"
    "bat": "bin"
    "json": "{\"key\": \"value\" …}"
  },
  …
]
```

And I would like to transform it to:

```
{
  foo: "bar"
  bar: bat
  json: {
    key: "value",
    …
  }
}
…
```

`fromjson` doesn't appear to work like `'.[] | {foo, bar, json: fromjson(json)}'`. What should I be reaching for here?

**Comment by timvisher** [comment]
ah. apparently `.[] | {foo, bar, json: (.json | fromjson)}` is the magic trick.

**Comment by pkoppstein** [comment]
No magic, just pipes and closures.  The magic would have been the transmogrification of `"bat":"bin"` to `bar:bat`, except it was evidently just a typo :-)

**Comment by RichardBronosky** [comment]
How is this for magic? (I use this to make Terraform output, AWS cli output, and AWS logs readable. One command to beautify them all!

From @pasamio's example:
```
## Input:
jq 'walk(if type == "string" and .[0:2] == "{\"" then .=(.|fromjson) else . end)' <<EOF
{
  "result": {
    "data": [
      {
        "notes": "{\"recordCountValidation\":\"failure\",\"Metafile Md5\":\"d41d8cd98f00b204e9800998ecf8427e\",\"schemaValidation\":\"failure\"}"
      }
    ]
  }
}
EOF

## Output:
{
  "result": {
    "data": [
      {
        "notes": {
          "recordCountValidation": "failure",
          "Metafile Md5": "d41d8cd98f00b204e9800998ecf8427e",
          "schemaValidation": "failure"
        }
      }
    ]
  }
}
```

From @timvisher's example:
```
## Input:
jq 'walk(if type == "string" and .[0:2] == "{\"" then .=(.|fromjson) else . end)' <<EOF
[
  {
    "foo": "bar",
    "bat": "bin",
    "json": "{\"key\": \"value\"}"
  }
]
EOF

## Output:
[
  {
    "foo": "bar",
    "bat": "bin",
    "json": {
      "key": "value"
    }
  }
]
```

**Comment by pkoppstein** [comment]
@RichardBronosky - Note that `.=(.|fromjson)` can be simplified to `fromjson`. (How's that for magic?)
