### ISSUE TITLE
accept incomplete json

### ISSUE THREAD

**Issue by billehunt** [stedolan/jq#31]
Hey, I know there are good arguments not to do this, but...

My first use for jq is to parse live logs that I record in json. jq is super awesome. However...

Because I'm running it on logs, my logs all begin with '[', and then each line is something like: 
{"date":"2012-10-22 00:02:45","level":"INFO","controller":"services","method":"get_my_stores_and_ads","message":"begin_execution","params":["917i","3ktDWc3TppvuBHGYDRUw3C"],"post":false,"version":"917i","user_id":"1979"},

So, each of my logs has no closing ']'. I know this not the problem of jq; you should be able to expect complete json. And I'm not even sure of a best solution. Perhaps if a file didn't parse, jq could retry adding a ']' on the end? Anyway, if you see this as a common use case, something to consider.

**Comment by lucatpa** [comment]
I think adding partial parsing support for truncated json would be valuable, sometimes you get some and it would be really good to be able to use `jq` to inspect it. This could be only enabled via an option, so normally it should of course fail when invalid json is parsed.

**Comment by wader** [comment]
Maybe `--stream` in combination with `setpath` could be used? something like this:
```sh
$ echo '{"a": [1,2,{"c":123},"b":767' | jq --stream | jq -n 'reduce inputs as $i ({}; if ($i | has(1)) then setpath($i[0]; $i[1]) else . end)'
parse error: ':' not as part of an object at line 1, column 25
{
  "a": [
    1,
    2,
    {
      "c": 123
    }
  ]
}
```

**Comment by lucatpa** [comment]
Oh, that workaround is already something! Nice!
