### ISSUE TITLE
jq installed through the package management tool on Ubuntu or CentOS will modify the value of the original long integer

### ISSUE THREAD

**Issue by cuishuang** [stedolan/jq#3185]
**Describe the bug**

Jq installed through the package management tool on Ubuntu or CentOS will modify the value of the original long integer

Jq installed via brew on Mac behaves normally

**To Reproduce**

Install jq by `apt get` or `yum`

the origin text:
```json
{
    "userinfo": {

        "userids": [123, 58112233445566804, 789]
    }

}
```

 cat test.json | jq .

the format text:
```json
{
  "userinfo": {
    "userids": [
      123,
      58112233445566800,
      789
    ]
  }
}
```

**Expected behavior**

58112233445566804 should not be changed

**Environment (please complete the following information):**

- OS and Version: NAME="CentOS Linux"    VERSION="7 (Core)"

- jq version:  jq-1.6

**Additional context**

<img width="777" alt="image" src="https://github.com/user-attachments/assets/9bce80ae-fd45-4285-8273-447dc9dafb2c">

**Comment by wader** [comment]
Hi, see #2962

**Comment by cuishuang** [comment]
> Hi, see #2962

Thanks!
