### ISSUE TITLE
Querying Nested objects

### ISSUE THREAD

**Issue by vito-c** [stedolan/jq#319]
Let's say I have:
echo '{ "a":{"b":{"c":{"d":10}}}}' | jq '.[][][].d'
which returns the value 10 is there anyway to do this with some kind of wild card? Like echo '{ "a":{"b":{"c":{"d":10}},"e":{"d":5}}}' | jq '.*.d' ? :)

Also is there a way to have it query for all objects that match?
echo '{ "a":{"b":{"c":{"d":10}},"e":{"d":5}}}' | jq '.*.d'

I was lastly wondering what you guys thought of json path? would be neat if you could incorporate that into jq

**Comment by gberche-orange** [comment]
I had a similar need of selecting a field within a nested json graph, and pruning out empty arrays and nulls. The syntax proposed in this thread is fine except that its verbose. I therefore shorthanded it into a bash function:

```
#jqe as jq nested expression
 function jqe { jq "..  |  ${1}? | select(. != []) | select (. != null)"; }
```

```
$ cf curl /v2/service_plans/aa5704e9-1957-4e20-8cec-242fb803f8e9/service_instances  | head -n 20
{
   "total_results": 9,
   "total_pages": 1,
   "prev_url": null,
   "next_url": null,
   "resources": [
      {
         "metadata": {
            "guid": "40df65dc-571b-422c-9a41-6cb5218f0f7d",
            "url": "/v2/service_instances/40df65dc-571b-422c-9a41-6cb5218f0f7d",
            "created_at": "2014-12-02T17:30:38Z",
            "updated_at": null
         },
         "entity": {
            "name": "mysql-spring-travel",
            "credentials": {},
            "service_plan_guid": "aa5704e9-1957-4e20-8cec-242fb803f8e9",
            "space_guid": "8d74f1c3-e005-42ad-bd31-675d5dc0e1de",
            "gateway_data": null,
[...]

$ $ cf curl /v2/service_plans/aa5704e9-1957-4e20-8cec-242fb803f8e9/service_instances  | jqe .space_guid
"8d74f1c3-e005-42ad-bd31-675d5dc0e1de"
"32056146-258b-48cf-b0be-a85f059331d6"
"0551cebc-847b-491b-b408-072e20d7485d"
"c2a89e41-2494-4d7b-a59f-2011e1624cd1"
"7c7906b5-305a-40fb-8004-20805a689d67"
"ec7a94e7-ed24-4a9b-a81f-b7b66665481a"
"ec7a94e7-ed24-4a9b-a81f-b7b66665481a"
"a7e6d95a-dc3e-497c-8a4b-e6ae21e9ad00"
"90d6b238-3f79-46f4-82f7-8dc93e9dfda8"
```
This enables me to nicely script REST APIs browsing

```
 cf curl /v2/service_plans/aa5704e9-1957-4e20-8cec-242fb803f8e9/service_instances  | jqe .space_url | xargs -n 1 cf curl | jqe .name
```

Maybe a new jq command line option would be useful to some users to avoid such custom shorthands

**Comment by pkoppstein** [comment]
@gberche-orange wrote:
> The syntax proposed in this thread is fine except that its verbose.

Defining a bash function as you have done is a good way to avoid verbosity. 

Your jq could be made slightly less verbose by using 'values':
```
..  |  .space_url? | values | select(. != []) 
```
or a single select:
```
..  |  .space_url? | select( . != null and . != []) 
```

A case can certainly be made for something shorter than `.space_url? | values` but, as has been pointed out in this thread and elsewhere, in the JSON world there is nothing special about the combination (null or []).  In jq and elsewhere, null and false are paired as the "non-truthy" values, but 0, [] and {} are all "truthy".    

By the way, for anyone who may not have noticed, jq "master" provides `scalars_or_empty` in addition to the type-based filters provided by jq 1.4.

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/1568

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/536
