### ISSUE TITLE
Deleting keys from objects?

### ISSUE THREAD

**Issue by ghost** [stedolan/jq#323]
It is pretty simple to add/update a key from an object using jq:

`echo '{"a": 1, "b": 2}' | jq '.c = 3'`

```
{
  "a": 1,
  "b": 2,
  "c": 3
}
```

However, I haven't found a simple way to delete a key from an object. It seemed to me that it would be intuitive to try the following:

`echo '{"a":1, "b":2}' | jq '.b = empty'`

and jq produced nothing (which, once I tried comma-separated values as rvalues, kind of made sense).

I have found that `with_entries(select(.key != "b"))` solves my problem, but it feels clumsy when compared to the succinctness of `.c = 3`.

`echo '{"a": 1, "b": 2}' | jq 'with_entries(select(.key != "b"))'`

```
{
  "a": 1
}
```

**Comment by guidorice** [comment]
What was the final filter to solve the problem of filtering properties from an array? I couldn't quite piece it together from this thread. For context, I am just trying to remove the centroid property from a geojson FeatureCollection.

**Comment by drjasonharrison** [comment]
@guidorice see https://stackoverflow.com/questions/36227245/deleting-multiple-keys-at-once-with-jq

The accepted answer by user3899165:


You can provide a stream of paths to delete:

`$ cat test.json | jq 'map(del(.Country, .number, .Language))'`

Also, consider that, instead of blacklisting specific keys, you might prefer to whitelist the ones you do want:

`$ cat test.json | jq 'map({label, region, locale, currency})'`

**Comment by dasaro77** [comment]
Note that here's an updated list of CLI commands that I have now run:

##############################
PROJECT:  `update-guava-rails-dev`
URL:  https://console.aws.amazon.com/codesuite/codebuild/874037557740/projects/update-guava-rails-dev/history?region=us-east-1&builds-meta=eyJmIjp7InRleHQiOiIifSwicyI6e30sIm4iOjIwLCJpIjowfQ
CHANGE:  `aws_stuff/buildspec_k8s.yml` ==> `ops/aws/codestar/buildspec_k8s.yml`
CLI:
```
aws codebuild update-project --name update-guava-rails-dev \
	--source "$(aws codebuild batch-get-projects --names update-guava-rails-dev \
		| jq '.projects[0].source | .buildspec = "ops/aws/codestar/buildspec_k8s.yml"')"
```


##############################
PROJECT:  `guava-rails-dev-2`
URL:  https://console.aws.amazon.com/codesuite/codebuild/874037557740/projects/guava-rails-dev-2/history?region=us-east-1&builds-meta=eyJmIjp7InRleHQiOiIifSwicyI6e30sIm4iOjIwLCJpIjowfQ
CHANGE:  `aws_stuff/buildspec_docker.yml` ==> `ops/aws/codestar/buildspec_docker.yml`
CLI:
```
aws codebuild update-project --name guava-rails-dev-2 \
	--source- "$(aws codebuild batch-get-projects --names guava-rails-dev-2 \
		| jq '.projects[0].source | .buildspec = "ops/aws/codestar/buildspec_docker.yml"')"
```

##############################
PROJECT:  `guava-rails-dev-rspec`
URL:  https://console.aws.amazon.com/codesuite/codebuild/874037557740/projects/guava-rails-dev-rspec/history?region=us-east-1&builds-meta=eyJmIjp7InRleHQiOiIifSwicyI6e30sIm4iOjIwLCJpIjowfQ
CHANGE:  `aws_stuff/buildspec_rspec.yml` ==> `ops/aws/codestar/buildspec_rspec.yml`
CLI:
```
aws codebuild update-project --name guava-rails-dev-rspec \
	--source "$(aws codebuild batch-get-projects --names guava-rails-dev-rspec \
		| jq '.projects[0].source | .buildspec = "ops/aws/codestar/buildspec_rspec.yml"')"
```

##############################
PROJECT:  `update-guava-rails-prod`
URL:  https://console.aws.amazon.com/codesuite/codebuild/874037557740/projects/update-guava-rails-prod/history?region=us-east-1&builds-meta=eyJmIjp7InRleHQiOiIifSwicyI6e30sIm4iOjIwLCJpIjowfQ
CHANGE:  `aws_stuff/buildspec_k8s.yml` ==> `ops/aws/codestar/buildspec_k8s.yml`
CLI:
```
aws codebuild update-project --name update-guava-rails-prod \
	--source "$(aws codebuild batch-get-projects --names update-guava-rails-prod \
		| jq '.projects[0].source | .buildspec = "ops/aws/codestar/buildspec_k8s.yml"')"
```
