### ISSUE TITLE
`sort` and friends are not stable

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#343]
We use the C library's `qsort()`, which is typically an unstable qsort.  We test with an input where lack of stability can result in errors.  This one test fails on Windows, for example.

**Comment by pkoppstein** [comment]
NOTE:  As of January 18, 2016 (7835a72), the builtin sort and sort_by filters are stable.  

(See https://github.com/stedolan/jq/commit/7835a724d65708f4511e5d26c5ae9a1a5c1da576)

**Comment by hawicz** [comment]
Fwiw, this doesn't appear to be in any release yet.
Also, it would be nice if the man page documented the fact that the sort is now stable, and provided an example of how to sort by multiple fields.

**Comment by pkoppstein** [comment]
@hawicz - Please review the relevant sections of the [FAQ](https://github.com/stedolan/jq/wiki/FAQ) to verify that the information you have in mind is all there. You could search for the following strings to find the relevant sections:

    Is jq's sort stable?

    How can I sort an array using multiple criteria?

**Comment by hawicz** [comment]
I was thinking more of https://github.com/stedolan/jq/blob/master/docs/content/3.manual/manual.yml#L1265

**Comment by nicowilliams** [comment]
Fixed with `7835a724d65708f4511e5d26c5ae9a1a5c1da576`
