### ISSUE TITLE
Error with reading large integer?

### ISSUE THREAD

**Issue by bsbkeven** [stedolan/jq#369]
Hello,

I am running jq (version 1.3), and find that it seems to be reading large integers (>= 17 digits) incorrectly. For example, if I run 
    `jq '.id'`
on the following input:

```
    {"id" : 125276004817190914}
    {"id" : 12527600481719091}
    {"id" : 1252760048171909}
    {"id" : 12527.6004817190914}
```

the output is:

```
    125276004817190910
    12527600481719092
    1252760048171909
    12527.600481719091
```

Results on the first and second line (18 and 17 digits) are incorrect, but the third line (16-digits integer) and the fourth (floating number) are correct.

Seems like this hasn't been reported before. So I just want to bring it up and wonder if anyone has had this issue as well? Thanks!

**Comment by jrdriscoll** [comment]
I don't have a lot to add to this discussion other than to note that I was shocked that `echo 11111111111111111 | jq '.'` produced something other than its input.  That being said, I never expected infinite precision arithmetic.

**Comment by dequis** [comment]
Submitted #1246, which solves this issue in a conservative way - no bigint libraries, only for ints up to 64 bits, and only if no operations are done over them, much like awk's behavior in previous comments:

    $ echo 111111111111111111 | jq -c '[., 1*.]'
    [111111111111111111,111111111111111100]

**Comment by sp-james-mcmurray** [comment]
I had this issue today with jq-1.5.

Where for large integers, it is changing the last values to 0s, even converting to strings doesn't help (as it reads it as integer first):

> "3265374331746778600"
"3349146353896582000"
"3658445187091539500"
"381327942920288"
"4540495826739245000"
"4609284046671461000"

Should be:

> 3265374331746778747
3349146353896582298
3658445187091539618
4540495826739245237
4609284046671461009

**Comment by nicowilliams** [comment]
@sp-james-mcmurray Internally jq uses IEEE754 doubles for number representation.  Any integers whose absolute values are larger than 2^52 - 1 will not be faithfully represented.

**Comment by mitar** [comment]
I just use Python and its `json` module. Now that Python maintains the order in its dicts, it is easy to modify JSON and get output match the input, expect for the changes you want.

**Comment by nicowilliams** [comment]
@mitar please don't leave this comment on every issue that deals with jq and IEEE754.  Thanks.

**Comment by umairrafiq** [comment]
One workaround for this issue is to double quote integers as string before sending to jq. 
An easy way to do that in bash using perl :
perl -pe 's/("(?:\\.|[^"])*")|-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?/$1||qq("$&")/ge'  
sourced from : https://unix.stackexchange.com/a/504446/368108
