### ISSUE TITLE
selecting an array element, based on subelement value -> jq: error: Cannot index array with string

### ISSUE THREAD

**Issue by ghost** [stedolan/jq#370]
my input is

```
{
  "ACTION": "domain.list",
  "DATA": [
    {
      "TYPE": "slave",
      "AXFR_IPS": "none",
      "DOMAIN": "domain1.com",
      "TTL_SEC": 0,
      "SOA_EMAIL": "",
      "DOMAINID": 11111,
      "DESCRIPTION": "",
      "EXPIRE_SEC": 0,
      "RETRY_SEC": 0,
      "STATUS": 1,
      "LPM_DISPLAYGROUP": "",
      "REFRESH_SEC": 0
    },
    {
      "TYPE": "slave",
      "AXFR_IPS": "none",
      "DOMAIN": "domain2.net",
      "TTL_SEC": 0,
      "SOA_EMAIL": "",
      "DOMAINID": 22222,
      "DESCRIPTION": "",
      "EXPIRE_SEC": 0,
      "RETRY_SEC": 0,
      "STATUS": 1,
      "LPM_DISPLAYGROUP": "",
      "REFRESH_SEC": 0
    },
    {
      "TYPE": "slave",
      "AXFR_IPS": "none",
      "DOMAIN": "domain3",
      "TTL_SEC": 0,
      "SOA_EMAIL": "",
      "DOMAINID": 33333,
      "DESCRIPTION": "",
      "EXPIRE_SEC": 0,
      "RETRY_SEC": 0,
      "STATUS": 1,
      "LPM_DISPLAYGROUP": "",
      "REFRESH_SEC": 0
    },
  ],
  "ERRORARRAY": []
}
```

I can easily select a specific element in the sequence with

```
| jq '.DATA | .[2]'

    {
      "TYPE": "slave",
      "AXFR_IPS": "none",
      "DOMAIN": "domain2.net",
      "TTL_SEC": 0,
      "SOA_EMAIL": "",
      "DOMAINID": 22222,
      "DESCRIPTION": "",
      "EXPIRE_SEC": 0,
      "RETRY_SEC": 0,
      "STATUS": 1,
      "LPM_DISPLAYGROUP": "",
      "REFRESH_SEC": 0
    },
```

or select all specific subelements

```
| jq '.DATA | .[].DOMAINID'

    "11111"
    "22222"
    "33333"
```

but can't seem to understand how to pick out ONLY the 'DOMAINID' value, for the element where DOMAIN == 'domain2'.  I.e., my desired result is

```
"22222"
```

If I try to select 1st

```
| jq '.DATA | select(.DOMAIN=="domain2")'
```

I get

```
jq: error: Cannot index array with string
```

How do I find/select the desired subelement?

**Comment by kovacshuni** [comment]
used this now, thanks!

**Comment by frbrando** [comment]
This is great, thank you for posting!

**Comment by sn391** [comment]
how ti use select for more filters?

**Comment by ayoubensalem** [comment]
Arigatooo !

**Comment by Alexhha** [comment]
You can you just
```
| jq '.DATA[]  | select(.DOMAIN == "domain2").DOMAINID'
```

**Comment by RichardBronosky** [comment]
How would you select any of multiple values for `DOMAIN`? With python you can do `if string in list:`

I was hoping for ```
| jq '.DATA[]  | select(.DOMAIN in ["domain2", "domain3"]).DOMAINID'
```

**Comment by pkoppstein** [comment]
@RichardBronosky - The following is one way to achieve what you want and is along the lines of your attempt:

    .DATA[] | select(.DOMAIN == ("domain2", "domain3")) | .DOMAINID

If that seems a bit too mysterious, you might prefer something that looks more conventional, such as:

    .DATA[] | select(.DOMAIN | IN("domain2","domain3")) | .DOMAINID

If your jq does not have IN/1, you could use this def:

    def IN(s): first(select(s == .)) // false;

In future, please ask usage questions at stackoverflow.com using the jq tag: https://stackoverflow.com/questions/tagged/jq

**Comment by RichardBronosky** [comment]
@pkoppstein Wow! That was quick. I was in the middle of writing my question on SO when you replied. https://stackoverflow.com/questions/50750688/jq-select-where-attribute-in-list/50750734#50750734

**Comment by manuviswam** [comment]
What if I want to select only the first match?

**Comment by pkoppstein** [comment]
@manuviswam - You could use `first` as described in the jq manual, e.g. `first( ... )`
