### ISSUE TITLE
jq '.1'

### ISSUE THREAD

**Issue by rkuksa** [stedolan/jq#374]
Hello!
I have much data with same content, like below:

<pre>{
  "1":{
    "key":"value",
     ...
  }
}</pre>

<pre>curl $URL | jq '.1'
error: syntax error, unexpected LITERAL, expecting $end
.1
^^
1 compile error
</pre>

Can't find, how to access <code>.1.key</code> without sed:

<pre>curl $URL | json_pp | sed -r 's/^  "/  "x/' | jq '.x1.key'
value
</pre>

**Comment by huyngo81** [comment]
Thanks alot. It works :+1:
