### ISSUE TITLE
Cannot select field if field name has dashes

### ISSUE THREAD

**Issue by ilkka** [stedolan/jq#38]
Given this JSON:

``` json
[
    {
        "my-field": "val1",
        "other_field": "valA"
    },
    {
        "my-field": "val2",
        "other_field": "valB"
    }
]
```

this works:

```
$ ./jq '[.[]|{other_field}]' < test.json
[
  {
    "other_field": "valA"
  },
  {
    "other_field": "valB"
  }
]
```

but this does not:

```
$ ./jq '[.[]|{my-field}]' < test.json
error: syntax error, unexpected '-', expecting '}'
[.[]|{my-field}]
        ^
1 compile error
```

I think it should since the JSON is valid. Maybe there is a way around this?

**Comment by ereyes01** [comment]
I think it's important to note that if you ever script the query string to `jq`, it would be unsafe in the generic case to not use the `jq ".[$keyname]"` notation if the names of your keys are not statically known/defined. A simple `jq ".$keyname"` would break if $keyname ever has a hyphen in it.

**Comment by ereyes01** [comment]
In fact, it seems like it would be more correct if, in your parser, you would prioritize matching key names over evaluating operators.

example: `echo '{"key-10": 10}' | jq ".key-10"`

Ideally would print "10"...  and:

`echo '{"key-10": 10}' | jq ".key-10-10"`

would print "0". I say this of course, after having thought about all the possibilities for a full 5 minutes or so :-)

**Comment by dtolnay** [comment]
Then you have a problem if someone wants to subtract 10 from a key:

    echo '{"key": 11, "key-10": 12}' | jq ".${KEY}-10"

This would require the even more confusing `".${KEY}-(10)"` or `"(.${KEY})-10"`.

**Comment by hexsel** [comment]
Just for posterity, the following seems to work:

    jq .\"a-b\"

Seems like the shortest working query string with a hyphen.

**Comment by mcwumbly** [comment]
I ran into this issue today and this workaround in the comment above doesn't seem to work for me in jq 1.3.  Anyone have any tips for what works today when strings have dashes in them?

**Comment by pkoppstein** [comment]
Assuming the input is a JSON object, it's always safe to use the  form: `.[ $keyname ]` where `$keyname` is a JSON string.

**Comment by wtlangford** [comment]
I should also point out that jq-1.3 is quite old. jq-1.5 is the current
release, and jq-1.6 is hopefully released soon (pending mine or
@nicowilliams' schedules).

As for jq-1.3, is that the package provided by your system or by your
sysadmin? In the latter case, I'd recommend pestering them to upgrade you
to 1.5 (which is much nicer in a lot of ways, and should not have any
backwards incompatibilities). If the former... I'm going to guess you're on
Debian. ;)

**Comment by mcwumbly** [comment]
thanks @pkoppstein - that helps, and this works:

```bash
echo '{ "foo-bar":"baz" }' | jq '.[ "foo-bar" ]'
```

**Comment by pierreprinetti** [comment]
Instead, this does not seem to work:

```shell
echo '[{ "foo-bar":"baz" }]' | jq '.[0].[ "foo-bar" ]'
```

**Comment by nicowilliams** [comment]
> Instead, this does not seem to work:
> 
> ```shell
> echo '[{ "foo-bar":"baz" }]' | jq '.[0].[ "foo-bar" ]'
> ```

You don't need that second period.  Use `jq '.[0]["foo-bar"]'`.

That is, to chain index operations you must not use a period between the index operators.  Only the first index operator needs a period (so as to distinguish it from the array constructor syntax).

We should probably make it so that extra period is not a syntax error, as this is a bit of an FAQ.

(Replying by email, so I think the formatting won't show correctly.  But I'll set the MIME type to see if I can get it to work.)

**Comment by davison** [comment]
I have a similar problem, but in my case I'm iterating over a loop and attempting to use a bash variable as the key.  None of the above solutions work because they all seem to rely on using outer single-quotes to wrap the entire jq query, and bash will not interpolate a variable in that single-quoted string..

```
$ key="foo-bar"; echo '[{ "foo-bar":"baz" }]' | jq '.[0].[ "$key" ]'
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
.[0].[ "$key" ]     
jq: 1 compile error

key="foo-bar"; echo '[{ "foo-bar":"baz" }]' | jq ".[0].[ \"$key\" ]" 
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
.[0].[ "foo-bar" ]     
jq: 1 compile error
```

Is there any way to specify the key in a shell variable?

**Comment by pkoppstein** [comment]
> key="foo-bar"; echo '[{ "foo-bar":"baz" }]' | jq '.[0].[ "$key" ]'

There are two problems with the above. First, the abbreviation `.[0].["KEYNAME"]` is not (currently) supported.  The second has to do with the relationship between the shell or environment variable $key and the jq variable `$key`.

In a nutshell, here is what is recommended:

    key="foo-bar"; echo '[{ "foo-bar":"baz" }]' | jq --arg key "$key" '.[0]|.[ $key ]'

For future reference, please ask usage questions at stackoverflow.com with the jq tag: https://stackoverflow.com/questions/tagged/jq

**Comment by dhjw** [comment]
If you need to pass a variable containing a string with a dash and save it in a variable in a bash script...

`result=$(jq --arg a "$query" '.[$a]' -r some.json)`
