### ISSUE TITLE
Date utilities

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#387]
Built-ins to handle date formatting and parsing would be very convenient.

Roughly we need something like SQLite3's date functions, and given that SQLite3 is in the public domain, that might be a good source of such functions.  See http://sqlite.org/lang_datefunc.html .

In particular we need something like wrappers to the C `strptime(3)` and `strftime(3)` functions, as well as some generic utilities for parsing/formatting from/to common-place date formats, including Unix time and ISO 8601 formats, as well RFC5424 (syslog) date format.

**Comment by singpolyma** [comment]
I would settle for the ability to shell out so I could run `date`

**Comment by svnpenn** [comment]
:+1:

**Comment by dtolnay** [comment]
Nico added several date and time builtins in a4b9552 and ccfba00.
