### ISSUE TITLE
jq - windows examples

### ISSUE THREAD

**Issue by DBAranAce** [stedolan/jq#392]
Hi,

I am trying to run jq on an output from aws cli command but it does not work. i tried to run a simple example but it's not working as well. can you provide with some windows examples i can start play with?

Thanks

**Comment by jszabo98** [comment]
It looks like even in powershell in windows you have to backslash the doublequotes.

**Comment by nicowilliams** [comment]
@jszabo98 Windows doesn't use single quotes, and since you're escaping the double quotes, it's splitting on the space.  Try `jq -n "\"Hello world!\""` (which works for me).

**Comment by jszabo98** [comment]
Powershell uses both single quotes and double quotes.  But somehow the double quotes sometimes get lost with external programs, even within single quotes.

**Comment by nicowilliams** [comment]
@jszabo98 oh, that's because on Windows there's no proper argument vector, and programs have to do their own command-line parsing.

**Comment by Loizzus** [comment]
> @jszabo98 Windows doesn't use single quotes, and since you're escaping the double quotes, it's splitting on the space. Try `jq -n "\"Hello world!\""` (which works for me).

Sadly this doesn't work for me. Here is my code:
`IF "%COMPANY_ID%"=="" curl -H "Authorization: Bearer %ACCESS_TOKEN%" -X GET https://api.company.com/vapid/companies | jq ".[] | select (.name=="\"My Company Name\"") | .[].id"`

@nicowilliams do you have any ideas?

**Comment by ClaudiaR6** [comment]
> ¿Podemos tener un ejemplo simple _y completo_ para imprimir bastante un archivo json en Windows?
> 
> Uno realmente no debería tener que pasar más de 5 minutos leyendo los documentos y tratando de descubrir cómo en el mundo realizar la tarea JSON más simple posible, imprimir un archivo .json, sin obtener
> 
> > error: error de sintaxis, INVALID_CHARACTER inesperado, esperando $end
> 
> en cada intento.
> 
> `jq '.' < file.json`falla `type file.json | jq '.'`falla, etc. Altamente frustrante.


type file.json | jq 

A mi eso me sirvió Gracias
