### ISSUE TITLE
Comments in Json

### ISSUE THREAD

**Issue by vito-c** [stedolan/jq#402]
Is there a way to have jq ignore comments that have been added to the json file:
{
/\* People insist on putting comments in data */
"foo": "test",
"bar": "baz"
}

**Comment by pkoppstein** [comment]
Regarding the handling of comments in JSON, see https://github.com/stedolan/jq/wiki/FAQ#processing-not-quite-valid-json

**Comment by vito-c** [comment]
@pkoppstein Thanks! Do you know if that will also work for mongodb generated json ... this typically looks something like this:
```
{
        "_id" : ObjectId("1234567890"),
        "foo" : ObjectId("123456789"),
        "bar" : ObjectId("8897865866758"),
        "timestamp" : ISODate("2015-04-05T16:00:00.174Z")
}
```

**Comment by pkoppstein** [comment]
@vito-c - That of course is, as they put it, "mongodb-extended-json", not JSON. ("http://docs.mongodb.org/master/reference/mongodb-extended-json)

MongoDB does provide a utility for producing JSON from a MongoDB instance (but apparently not from a text file):
```
mongoexport is a utility that produces a JSON or CSV export of data stored in a MongoDB instance
```
Details about mongoexport are at: http://docs.mongodb.org/master/reference/program/mongoexport/#bin.mongoexport

**Comment by pauldraper** [comment]
To [quote](https://github.com/stedolan/jq/issues/348#issuecomment-43711400) the great @pkoppstein,

> Nothing I've read about jq suggests that it should reject invalid JSON. In fact, it would be great if it had the ability (perhaps governed by a switch) to transform imperfect JSON into JSON.

> Please also note that the most recent "Proposed Standard" for JSON (http://tools.ietf.org/html/rfc7159) explicitly says:

> > A JSON parser MAY accept non-JSON forms or extensions.

For example, jq accepts strings containing U+0083, which is **not** valid JSON according to RFC7159. In fact, this is almost exactly the same as the comments issue; both are valid JavaScript but not valid JavaScript Object Notation.

It would be reasonable to have a "strict" (or "non-strict") flag. I don't expect jq to output non-strict JSON. But it would be good for it to accept non-strict JSON, just as it does today.

**Comment by alexkli** [comment]
> It would be reasonable to have a "strict" (or "non-strict") flag. I don't expect jq to output non-strict JSON. But it would be good for it to accept non-strict JSON, as it already does today.

👍

**Comment by ricsam** [comment]
For some lightweight parsing and modifying of jsonc documents I've created [jsonc-cli](https://www.npmjs.com/package/jsonc-cli) which is just a cli front-end for Microsoft's [jsonc-parser](https://www.npmjs.com/package/jsonc-parser).

**Comment by ghost** [comment]
If you have `node` installed, save this bash snippet as `/usr/local/bin/stripjsonc`

```sh
#!/bin/bash
node -p 'JSON.stringify(eval(`(${require("fs").readFileSync("'${1}'"||0, "utf-8").toString()})`))'
```

:warning: uses `eval` so you must trust that your input is actually JSON/JSONC

Then
```sh
echo '{"foo":42 /*hello*/}' | stripjsonc # => {"foo":42}
# or
cat /tmp/foo.jsonc # { /*hello*/ "foo":7}
stripjsonc /tmp/foo.jsonc # => {"foo":7}
```
