### ISSUE TITLE
Accessing the environment from jq

### ISSUE THREAD

**Issue by wingZero21** [stedolan/jq#405]
Hi,

Another quick one.

Is there anyway to use variables within the JQ commands that have been set outside of JQ.

I have some names that I want to iterate through however the only way I can get JQ to see the variable is by using a quotes around the variable eg :'$IP' which works however I think its then causing a problem because of it already using the single quotes.

Is there anyway to escape this so it just sees the variable and runs correctly?

Details:
cat json jq '.[] | select(.agent_name=="'$IP'") | .uuid'

**Comment by rkondakindi** [comment]
thanks for sharing this. But, seems it is not working for me. Please let me know if I'm missing something here. 

JQ version and using `macOS high Sierra (10.13.6)` 
```
$ jq -V
jq-1.6
```

for me `--arg foo bar` is not working. Here find the log

Command without variable: 
`cat serv.json | jq '.services[] | select(.status == "ACTIVE") | .events[] | select(.createdAt >= 1572025061)| .message' ` gives the following result
**"(service pp-quad-aws-svc-dev) has reached a steady state."
"(service pp-quad-aws-svc-dev) has reached a steady state."
"(service pp-quad-aws-svc-dev) has reached a steady state."
"(service pp-quad-aws-svc-dev) registered 1 targets in (target-group arn:aws:elasticloadbalancing:us-east-1:991286002725:targetgroup/pp-quad-aws-svc-dev-alb-tg/9d23ca4203e38a95)"
"(service pp-quad-aws-svc-dev) has started 1 tasks: (task 73fb5a1a-c837-41ab-a338-cc42cd03a35f)."**

The output of TIME value 
```
$ echo $TIME
1572025061
```

jq command with `--arg` option which is not giving any result:

`cat serv.json | jq  --arg time $TIME '.services[] | select(.status == "ACTIVE") | .events[] | select(.createdAt>=$time)| .message'`

above same command without quotes for variable also giving null value

`cat serv.json | jq  --arg time $TIME '.services[] | select(.status == "ACTIVE") | .events[] | select(.createdAt>=$time)| .message'`

**Comment by wtlangford** [comment]
@rkondakindi: 
From the man page:
```
o   --arg name value:

    This option passes a value to the jq program as a predefined variable. If you run
    jq with --arg foo bar, then $foo is available in the program and has the value
    "bar". Note that value will be treated as a string, so --arg foo 123 will bind
    $foo to "123".

    Named arguments are also available to the jq program as $ARGS.named.

o   --argjson name JSON-text:

    This option passes a JSON-encoded value to the jq program as a predefined
    variable. If you run jq with --argjson foo 123, then $foo is available in the
    program and has the value 123.
```

`--arg` treats the value as a string. If the value is json-encoded (like that number you're using), you should use `--argjson`.

In the future, please ask usage questions such as this at stackoverflow.com with the jq tag: https://stackoverflow.com/questions/tagged/jq

That way, your question will most likely be answered more quickly, and others will more likely benefit from the answer(s).
