### ISSUE TITLE
jq 1.4 source requires bison

### ISSUE THREAD

**Issue by g5pw** [stedolan/jq#416]
In the process of updating the jq port at MacPorts, I noticed that the source (download from http://stedolan.github.io/jq/download/source/jq-1.4.tar.gz) requires bison to be installed at configure time. Build instructions [here](https://stedolan.github.io/jq/download/#from_source_on_linux_os_x_cygwin_and_other_posixlike_operating_systems) suggest that bison is not necessary if not downloaded from git.

**Comment by nicowilliams** [comment]
Fixed in master.
