### ISSUE TITLE
escape chars

### ISSUE THREAD

**Issue by edap** [stedolan/jq#42]
How can I escape "$" char?
I'm trying to parse the youtube apis, getting this _media$group_
This work

```
  curl 'https://gdata.youtube.com/feeds/api/standardfeeds/IT/most_recent_Sports/?v=2&alt=json' | jq' .feed.entry[] | {title}'
```

This is not working:

```
  curl 'https://gdata.youtube.com/feeds/api/standardfeeds/IT/most_recent_Sports/?v=2&alt=json' | jq' .feed.entry[] |  {media$group}'
```

**Comment by Jean-Baptiste-Lasselle** [comment]
> @theoreticaLee you can use keys with slashes, but you'll have to use explicit strings as the keys:
> 
> `jq '.slash/key'` won't work, but `jq '.["slash/key"]'` will.
> `jq '{slash/key}'` won't work, but `jq '{"slash/key"}'` will.

honestly love that one : just so useful today, using hashicorp vault api...

**Comment by v6dou** [comment]
@Jean-Baptiste-Lasselle I'm dealing with the same thing, in the list of accessors at sys/auth

**Comment by v6dou** [comment]
None of the above solutions worked, I had to generate a jqparams.txt file using a "heredoc" and put environment variables in it, then pass that using jq --from-file jqparams.txt. 

Would be nice to see this program play better with `bash` primitives.

**Comment by Chealer** [comment]
For what it's worth, to access a sub-element where the sub-key has a slash:
`jq '.devDependencies."@angular/cli"' package.json`
