### ISSUE TITLE
enhancement request: regex filters

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#432]
jq now has basic regex support in the form of `match` and `test` (see #431 and #164) but I believe still lacks "builtin" support for the following:

```
split(REGEX)
sub(REGEX, STRING)
gsub(REGEX, STRING) 
scan(REGEX)
```

**Comment by guruprasannaps** [comment]
I want to validate the filename. If the file name contains the \ / : * ? " < > | I should get the result as false. I tried many things but unable to make it work. CVOuld you help me please on this. how I can validate?
test("\ / : * ? " < > |*"; "gx")] is throing an compilation error .Please help me

**Comment by pkoppstein** [comment]
@guruprasannaps - One answer:

    jq -R 'test("[\\/:*?\"<>|]") | not'

In short, the regex must be a JSON string.

In future, please ask usage questions at stackoverflow.com with the jq tag: https://stackoverflow.com/questions/tagged/jq

Thank you.

**Comment by guruprasannaps** [comment]
Thank you very much for your quick support, I will ask the new question in the above link.
