### ISSUE TITLE
ARM builds

### ISSUE THREAD

**Issue by benwa** [stedolan/jq#441]
Any chance for official ARM builds?  Android/iOS/etc. could really use a quality JSON processor.

**Comment by ojacques** [comment]
@wtlangford - I'm doing some research / trials on IOS which could use a pre-built jq command line for IOS (my home automation system controlled through siri). Do you happen to have built jq in full, as a command line? This is for IOS 9/iPhone 6. And yes, this is on a JB iPhone. Thanks much!

**Comment by wtlangford** [comment]
Olivier, I don't, though I'm sure it wouldn't be particularly difficult.
You'd just need to tell configure that you want to cross-compile onto
aarch64.  You'll probably need a few extra LDFLAGS or CFLAGS so that
clang-llvm will build it right.

**Comment by ajorpheus** [comment]
> @wtlangford - I'm doing some research / trials on IOS which could use a pre-built jq command line for IOS (my home automation system controlled through siri). Do you happen to have built jq in full, as a command line? This is for IOS 9/iPhone 6. And yes, this is on a JB iPhone. Thanks much!

Did you happen to compile jq for iOS ?
