### ISSUE TITLE
enhancement request: pow(n)

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#443]
jq currently has Bessel functions and many other math functions -- but not pow(n)!  The main feature of the following implementation is the preservation of numerical accuracy as much as jq allows.   

    # 0^0 => 1
    # Preserve accuracy for integers as much as jq allows.
    # This version is self-contained.
    def pow(n):
      if n == 0 then 1
      elif . == 0 then 0
      else ( (n | floor) == n) as $intp
           | ( (n % 2) | if . == 0 then 1 else -1 end ) as $sign
           | if . == -1 and $intp then $sign
             elif . < 0 then -(.) | pow(n) * $sign
             elif $intp and n > 0 then . * pow(n - 1)
             else log * n | exp
             end
      end;

Example:

     input: 2 | [ pow(3), (log*3|exp) ]
     output: [ 8, 7.999999999999998 ]

**Comment by pkoppstein** [comment]
```
$ uname -a
Darwin wws 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64

$ git log -1
commit 6e27de4f747bc1f048aa54f3ea854f7320419e62
Author: David Tolnay <dtolnay@gmail.com>
Date:   Tue Jun 30 08:24:26 2015 -0700
    strftime wrong day-of-week (fix #838)
$ autoreconf -i ; ./configure ; make
...
In file included from builtin.c:107:
libm.h: In function 'f_pow10':
libm.h:132: warning: implicit declaration of function 'pow10'
libm.h:132: warning: incompatible implicit declaration of built-in function 'pow10'

Undefined symbols for architecture x86_64:
  "_pow10", referenced from:
      _f_pow10 in libjq.a(builtin.o)
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make[1]: *** [jq] Error 1
make: *** [all] Error 2
```

**Comment by nicowilliams** [comment]
What does config.log say about this?  Why did it find this function if it's
not there?

Is jq linking with libm?

Is there a manpage on pow10() on OS X?

**Comment by pkoppstein** [comment]
More details:
```
$ ./configure
...
checking for pow... yes
checking for pow10... yes
...

# extract from config.log:

configure:18260: checking for pow
configure:18288: gcc -std=gnu99 -o conftest -g -O2   conftest.c     -lonig >&5
configure:18288: $? = 0
configure:18329: result: yes
configure:18360: checking for pow10
configure:18388: gcc -std=gnu99 -o conftest -g -O2   conftest.c     -lonig >&5
conftest.c: In function 'main':
conftest.c:67: warning: implicit declaration of function 'pow10'
conftest.c:67: warning: incompatible implicit declaration of built-in function 'pow10'
configure:18388: $? = 0
configure:18429: result: yes

$ make
...
In file included from builtin.c:107:
libm.h:132:3: error: invalid preprocessing directive #LIBM_DD
In file included from builtin.c:1239:
libm.h:132:3: error: invalid preprocessing directive #LIBM_DD
In file included from builtin.c:1365:
libm.h:132:3: error: invalid preprocessing directive #LIBM_DD
```

Changing the following five lines in libm.h to just "LIBM_DD_NO(pow10)" resolves the problem:
```
#ifdef HAVE_POW10
# LIBM_DD(pow10)
#else
LIBM_DD_NO(pow10)
#endif
```
Also:
(1) "man pow" succeeds, but "man pow10" does not.

(2) Makefile includes these lines: 
libjq_la_LIBADD = -lm
jq_LDADD = libjq.la -lm

**Comment by nicowilliams** [comment]
Thanks.  I made a ridiculous thinko/braino I'll libm.h.  Ay!
