### ISSUE TITLE
enhancement request: transpose

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#449]
jq currently does not have a filter for transposing an array of arrays. The following proposal allows for alternative ways to handle jagged interior arrays:

  1) (**rectangular**) interpret each of the missing elements as a filler element;

  2) (**right-trim**) interpret each of the missing elements as null, then remove trailing nulls, and finally replace any remaining nulls with the filler element;

  3) (**shortest**) ignore all but the first *min* elements of the interior arrays, where *min* is the length of the shortest.

The filler element defaults to null.

The following definitions only introduce one new function name, "transpose", and for that
reason are in places a little more complex than would otherwise be the case.

    # In all cases, "transpose" expects its input to be null or an array
    # each element of which should be an array or null.  The result is an
    # array that represents the transposition of the input.  If the input
    # array is rectangular, then the output is also rectangular.
    #
    # transpose(filler; opt) is the workhorse:
    #   filler specifies the filler element;
    #   opt == true ==> right-trim
    #   opt == false ==> shortest
    #   any other value for opt ==> rectangular
    
    # transpose/0 is defined as transpose(null; null), i.e. produce rectangular results with null as the filler.
    # transpose(opt) is defined as transpose(null; opt), i.e. use null as the filler.
    #
    # null elements in the input array are regarded as generators; for example:
    # [[1,2], null, [3,4]] | transpose(0)  => [[1,0,3], [2,0,4]]
    #
    # Note also that:
    # null   => null
    # [ [] ] => []    # the input represents a matrix with no rows
    # [null] => []    # null is needed 0 times to make a rectangular matrix
    #
    # Examples using transpose/0:
    # []    => []
    # [[1]] => [[1]]
    # [[1,2], [3,4]] => [ [1,3], [2,4] ]
    # [[1,2], [3]]   => [ [1,3], [2,null] ]
    # [[1], [2,3]]   => [ [1,2], [null,3] ]
    
    # opt == true => right-trim
    # opt == false => shortest
    # any other value => rectangular
    def transpose(filler; opt):
      if length == 0 then . # length of null is 0 too
      elif opt == true
           then transpose(filler; null )
                | map( reverse | reduce .[] as $x ([]; if length == 0 and $x == null then . else [$x] + . end) )
      elif opt == false
           then (map(length) | min) as $min | map( .[0:$min]) | transpose(filler; null)
      elif filler==null
           then
             # The following test optimizes away the call to map but is equivalent to (map(length == 0) | all) 
             if reduce .[] as $a (true; if . then 0 == ($a | length) else false end) then []
             else [map(.[0])] + (map(.[1:]) | transpose(filler; null))
             end
      else transpose(null;null) | map( reduce .[] as $x ([]; . + [if $x == null then filler else $x end] ) )
      end;
    
    def transpose: transpose(null; null);
    
    def transpose(opt): transpose(null; opt);
    
Notes:
*  The implementation would be simpler if `map` were used, but for efficiency it is not.
*  The implementation for right-trim would be simpler if a helper function were introduced.
*  transpose|transpose is the identity operator for null and rectangular inputs, but not otherwise.

**Comment by dtolnay** [comment]
Transpose added in 85f0e30.
