### ISSUE TITLE
builtin functions: not/1; is_integral/0

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#468]
# not/1 is defined in terms of not/0
    def not(x): x | not;

    # is_integral/0 evaluates to true if . is an integer-valued JSON number, or a string
    # that evaluates to a such a number; otherwise it evaluates to false, except that 
    # empty|is_integral evaluates to empty.
    def is_integral: if type == "number" then floor == .
      else try (tonumber|is_integral) catch false
      end;

Examples:
>   [ not(range(0;2)) ] => [false, false]
>    not(null) => true
>   "1.1E2" | is_integral => true
>    true | is_integral => false

**Comment by dtolnay** [comment]
This turned into a module system discussion. Please comment/reopen if you feel strongly about including is_integral as a builtin instead of in a library.

**Comment by pkoppstein** [comment]
For future reference, here's a better definition of "is_integral" that handles strings using test/1 (which wasn't available when the definition above was proposed):
```
# An integral number, or a string which could plausibly be interpreted
# as an integer, such as "-1.00" or " 1e+2 ".  However, apart from
# leading blanks and a single optional sign, the integer must begin
# with a digit.
def is_integral:
  if type == "number" then floor == .
  elif type == "string"
     then test("^ *[+-]?[0-9]+(\\.?0*)([Ee]\\+?[0-9]+)? *$")
  else false
  end;
```
