### ISSUE TITLE
Compile only what builtins are needed

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#470]
Currently jq [partially] compiles all the jq-coded builtins, every time, even if they aren't needed.  As the builtin library grows this could become a problem.  We may need the builtin system to learn how to compile only what's needed.  Such an optimization would be much too hard to extend to libraries, but then, a proper library system will help users manage what they need to import for their jq programs.

Also, for libjq users, it should be possible to save compilations for reuse across many `jq_state`s.

Finally, the thought occurs that we could pre-parse, and even more completely compile builtins at jq build-time.  We'd put the builtins in a separate file and then save either the block representation of parsed builtins, or a bytecode representation that requires relocation.

Currently the jq compiler does linking with the intermediate (bloc) representation of jq code, but being able to do linking after conversion to bytecode would enable pre-compilation of jq-coded builtins.  C-coded builtins would always have to be linked at the block intermediate stage to avoid having to change bytecode offsets.

**Comment by dtolnay** [comment]
Ditto Stephen - the compiler is really fast, so the tradeoff against complexity doesn't seem to be worth it. We can reopen if this becomes a problem.
