### ISSUE TITLE
tsv and/or csv output support

### ISSUE THREAD

**Issue by johan** [stedolan/jq#48]
Could we get a command-line flag to spit out tab- or comma-separated values instead of concatenated json objects, csv/tsv-quoting cells as necessary?

It would make jq a real power house for reports and spreadsheets generation.

**Comment by Fjelley85** [comment]
Hi, I also have a problem with "Cannot index array with string"

My code: curl 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | ./jq -r '.[] |  .committer | {login: .login,id: .id} | @csv'

Help would be appreciated

**Comment by pkoppstein** [comment]
The login and id values are associated with the "author" field:
```
jq -c -r '.[] | .author | {login,id} ' 
```
To output them using @csv:
```
jq -c -r '.[] | .author | [.login, .id] | @csv ' 
```

**Comment by Fjelley85** [comment]
Thank you!

**Comment by sankalp-mobolt** [comment]
Thanks, the @csv option was unknown to me till now! :+1:

**Comment by sankalp-khare** [comment]
Thanks! the @csv option is very helpful :+1:

**Comment by joelpurra** [comment]
I've finally moved my CSV/TSV utility scripts to [jq-hopkok's tabular folder](https://github.com/joelpurra/jq-hopkok/tree/master/src/tabular) -- see also other helpful schell scripts for parallel processing etcetera.

---

**Comment by AlJohri** [comment]
It would be really great to have a way to turn lists of objects into csvs (with header) automatically.

Right now I'm resorting to [`json2csv`](https://www.npmjs.com/package/json2csv):

```bash
curl 'http://.../nfl/participants/' | jq -c '.apiResults[].league.players[] | {teamId: .team.teamId, nickname: .team.nickname, playerId: .playerId, firstName: .firstName, lastName: .lastName}' | json2csv > players.csv
```

I would love to instead do `| @csv` directly to a list of objects.

```bash
curl 'http://.../nfl/participants/' | jq -r '.apiResults[].league.players[] | {teamId: .team.teamId, nickname: .team.nickname, playerId: .playerId, firstName: .firstName, lastName: .lastName} | @csv' > players.csv
```

Is there any chance something like this can be implemented?

**Comment by pkoppstein** [comment]
Here's a def that takes a stream of JSON objects and produces output suitable for feeding directly to @csv or @tsv.  It does NOT require the keys to be consistently ordered, and only pays attention to the keys in the first object.  An illustrative example follows.
```
def object2array(stream):
  foreach stream as $x (null;
    if . == null then $x | [true, keys_unsorted] else .[0]=false end;
    (if .[0] then .[1] else empty end),
    .[1] as $keys | $x | [getpath( $keys[] | [.]) ] );
```
### Example
```
def data: [{a:1,b:2}, {b:22,a:11,c:0}];

object2array(data[])
```
### Output
```
["a","b"]
[1,2]
[11,22]
```

## to_table
`to_table` (available [here](https://stackoverflow.com/questions/56890557/how-do-i-flatten-a-large-complex-deeply-nested-json-file-into-multiple-csv-fil) takes a very different approach.  It can handle JSON irregardless of the depth of nesting, but is only useful if there is sufficient regularity, notably of the ordering of keys within corresponding objects.

**Comment by AlJohri** [comment]
How can I easily use “object2array” myself and on my team? Is there some way to definite global functions and share them? I would like to just run “| object2array” and have it work on my laptop and my colleagues laptops. What’s the best distribution strategy

**Comment by pkoppstein** [comment]
Unfortunately, all the simple options that I know of have one drawback or another.

Probably the simplest approach would be for everyone to add the desired utility functions to a file called ~/.jq since, if it exists, it will automatically be read in on startup.  The main drawback of this approach is that it prevents ~/.jq from being used as a directory, which jq's module system by default recognizes as the location of jq modules.

Another option would be to take advantage of jq's module system. This is a tiny bit complicated, but is certainly worth considering. Here is one approach:

1. Copy the desired def into ~/.jq/jq.jq
2. Invoke jq as usual but preface the jq program with `include "jq";`
   e.g. jq 'include "jq"; ...' input.json

A third option which I've had some success with is to piggy-back off npm, but as best I can tell, it's not completely trivial.

**Comment by richardjharris** [comment]
`@tsv` seems to work for me on jq-1.6 (Manjaro Linux)
