### ISSUE TITLE
jq no longer builds on Ubuntu 12.04

### ISSUE THREAD

**Issue by wwalker** [stedolan/jq#488]
root@ip-10-183-62-73:~/jq# cat /etc/issue
Ubuntu 12.04.4 LTS \n \l

root@ip-10-183-62-73:~/jq# yacc --version
bison (GNU Bison) 2.5

history: 
   21  git clone https://github.com/stedolan/jq
   22  cd jq
   23  autoreconf -i;./configure

root@ip-10-183-62-73:~/jq# make
  LEX    lexer.c
  YACC   parser.c
/root/jq/parser.y:100.1-11: invalid directive: `%precedence'
/root/jq/parser.y:101.1-11: invalid directive: `%precedence'
/root/jq/parser.y:102.1-11: invalid directive: `%precedence'
/root/jq/parser.y:221.1-6: invalid directive: `%empty'
/root/jq/parser.y:487.1-6: invalid directive: `%empty'
/root/jq/parser.y:654.1-6: invalid directive: `%empty'

**Comment by dtolnay** [comment]
Using `./configure --disable-maintainer-mode` now builds against the pregenerated parser.c and lexer.c without requiring bison 3.0.

**Comment by pkoppstein** [comment]
@dtolnay - The "--disable-maintainer-mode" is mentioned in the FAQ, but I don't see it mentioned in docs/content/2.download/default.yml where the need for bison is mentioned.

Should the FAQ be mentioned somewhere in docs/ ?

**Comment by dtolnay** [comment]
Good idea. I added it to the end of the build instructions on the download page. I will move it into the main build steps for the 1.5 release.

**Comment by pkoppstein** [comment]
@dtolnay - A very, very small point:

As defined on the Home page of the wiki:

> "a version number such as 1.4+ means a (sufficiently recent) version after 1.4."

In docs/content/2.download/default.yml it says:

>      ... For jq 1.5+, neither is required ...

I would suggest simply dropping the "+" since normally anything said of jq x.y is meant
to apply to jq version >= x.y, or thereabouts :-)

**Comment by dtolnay** [comment]
Done. Thanks for pointing that out.
