### ISSUE TITLE
ANSI colors shouldn't assume dark background

### ISSUE THREAD

**Issue by wavebeem** [stedolan/jq#495]
ANSI colors shouldn't assume a dark background. For example, the "punctuation" characters of JSON show up as a bold white, something extremely hard (or impossible) to read on a light background.

OS X uses a white terminal by default, so I'm sure this affects a lot of people.

The alternative would be to specify "bold default" as the color for the punctuation rather than "bold white", so it used the appropriate text color.

See screenshot:
![screen shot 2014-07-21 at 14 12 07](https://cloud.githubusercontent.com/assets/176815/3650394/0b4a9908-111c-11e4-98d6-3f31d0e7acac.png)

**Comment by NightMachinary** [comment]
https://github.com/stedolan/jq/issues/83 is still unsolved though:
![image](https://user-images.githubusercontent.com/36224762/115283813-1ddf3880-a161-11eb-8c34-79acc9004f5e.png)

![image](https://user-images.githubusercontent.com/36224762/115283831-25064680-a161-11eb-9b17-30b5c547fa65.png)

**Comment by migmit** [comment]
It's back with a vengeance
<img width="238" alt="Screenshot 2023-09-26 at 01 02 14" src="https://github.com/jqlang/jq/assets/2890201/a24dee5b-775f-4134-b2d4-808e759ff9c5">
