### ISSUE TITLE
Iterate over result in bash

### ISSUE THREAD

**Issue by k-bx** [stedolan/jq#503]
Hi! So, I'm using Riak indexes, which looks something like this:

```
curl -Ss http://myriak.server:8098/buckets/mybucket/index/index_int/100/200/
{"keys": ["foo", "bar", "baz"]}
```

Obvious task is to iterate over this "keys" list later in order to actually query for values and filter them with jq.

I just did this https://gist.github.com/k-bx/019fa8429b3634acd0c0 , but it looks ugly (stripping out N symbols, splitting by comma, removing `"`'s from keys.

Would be really cool if jq would be able to do that for me.

Thanks!

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/pull/1005

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/925

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/255

**Comment by thiagodolabella** [comment]
I'm trying to use every Key,Value of an output and pipe it to another command.
Here is what I'm trying to use:

INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)

aws ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID"

With the above command, I have the following output:

    {
    "Tags": [
        {
            "ResourceType": "instance",
            "ResourceId": "i-0342a609edf80001a",
            "Value": "A-VALUE",
            "Key": "A-KEY"
        },
        {
            "ResourceType": "instance",
            "ResourceId": "i-0342a609edf80001a",
            "Value": "B-VALUE",
            "Key": "B-KEY"
        },
        {
            "ResourceType": "instance",
            "ResourceId": "i-0342a609edf80001a",
            "Value": "C-VALUE",
            "Key": "C-KEY"
        },
        {
            "ResourceType": "instance",
            "ResourceId": "i-0342a609edf80001a",
            "Value": "D-VALUE",
            "Key": "D-KEY"
        },
        {
            "ResourceType": "instance",
            "ResourceId": "i-0342a609edf80001a",
            "Value": "E-VALUE",
            "Key": "E-KEY"
        },
        {
            "ResourceType": "instance",
            "ResourceId": "i-0342a609edf80001a",
            "Value": "F-VALUE",
            "Key": "G-KEY"
        },
        {

Now I want to pipe each Key,Value to the following command:

    aws ec2 create-tags --resources XXXXX --tags Key=H-KEY,Value=H-VALUE

Where the quantity and values of Key,Value are variable. So I believe I need a "for each".

May you help me?


It's like: For each Key,Value, do:

aws ec2 create-tags --resources XXXXX --tags Key=A-KEY,Value=A-VALUE

aws ec2 create-tags --resources XXXXX --tags Key=B-KEY,Value=B-VALUE

aws ec2 create-tags --resources XXXXX --tags Key=C-KEY,Value=C-VALUE

aws ec2 create-tags --resources XXXXX --tags Key=N...-KEY,Value=N...-VALUE

**Comment by purpliminal** [comment]
@thiagodolabella In the future, please send usage questions to StackOverflow's JQ tag, and avoid reusing existing issues for unrelated questions.

One way to do this would be to have `jq` generate a script you can then pipe back to the shell, something like:

`jq -r '.Tags[] | "aws ec2 create-tags --resources XXXXX --tags Key=\(.Key),Value=\(.Value)"' | sh`
