### ISSUE TITLE
get last element from array

### ISSUE THREAD

**Issue by vtolstov** [stedolan/jq#509]
For example i have array like:

```
[
{
  "type": "strip",
  "output": "output/debian-7-x86_64-strip/"
},
{
  "type": "compress",
  "format": "gzip",
  "output": "output/debian-7-x86_64-compress/"
}
]
```

How can i get "output" value from last element from array? I don't known count of elements it may contain 1 or 20 elements, but i need only last.

**Comment by hannestyden** [comment]
You could also reverse the array and pick the first element:

For the input
```JSON
[
  [ "last" ],
  [ 1, "last" ],
  [ 2, 1, "last" ],
  []
]
```
`jq '(.[] | reverse)[0]'` outputs﻿
```
"last"
"last"
"last"
null
```

**Comment by jtakalai** [comment]
Works for me:
```
$ jq --version
jq-1.5
$ echo '{"test":[1,2,3]}' |jq .test[-1]
3
```
