### ISSUE TITLE
Case insensitive contains function

### ISSUE THREAD

**Issue by glaudiston** [stedolan/jq#512]
There is a way to use the contains function with case insensitive mode ?
I'm trying to do a case insensitive search with "contains" function:
Given a JSON:
{
  "sample": [
    {
      "k": "aBc"
    },
    {
      "k": "bCd"
    }
  ]
}

$ echo '{ "sample": [ { "k" : "aBc" }, { "k" : "bCd" } ] }' | jq '{ "sample" : [ { "k" : ( .sample[].k | select ( contains("B") ) ) } ] } '
{
  "sample": [
    {
      "k": "aBc"
    }
  ]
}

It returns only the first "k" , but I expect to return the both.

Some idea?

**Comment by sebma** [comment]
@dtolnay Will the `contains` function support the `"i"` flag in the near future ?

**Comment by wtlangford** [comment]
It's unlikely our `contains` function will support an `i` flag, as it would greatly complicate the implementation (case-insensitivity is tricker than it sounds when you support unicode).

As @pkoppstein wrote above, our regex functions do support case-insensitive modes, so you could implement a case-insensitive contains using them: `test("your pattern"; "i")`- just keep in mind that `your pattern` will be interpreted as a regex, not as plain text, so you'll need to escape any characters that regexes consider special.

**Comment by pkoppstein** [comment]
@sebma -- As @wtlangford mentioned:

> ... so you'll need to escape any characters that regexes consider special.

Here's a jq function that should do just that:
```
def deregex:
  reduce ("\\\\", "\\*", "\\^", "\\?", "\\+", "\\.", "\\!", "\\{", "\\}", "\\[", "\\]", "\\$", "\\|" ) as $c
    (.; gsub( $c; $c));
```
