### ISSUE TITLE
oniguruma.h can't find, what this header-file used for ?

### ISSUE THREAD

**Issue by b08060514** [stedolan/jq#534]
when `./configure`, it happend :

```
checking for oniguruma.h... not found
configure: Oniguruma was not found.
configure:  Try setting the location using '--with-oniguruma=PREFIX' 
configure: error:  oniguruma is required to build jq.
```

``` c
/* confdefs.h.  */
#define PACKAGE_NAME "jq"
#define PACKAGE_TARNAME "jq"
#define PACKAGE_VERSION "1.5.0"
#define PACKAGE_STRING "jq 1.5.0"
#define PACKAGE_BUGREPORT "mu@netsoc.tcd.ie"
#define PACKAGE "jq"
#define VERSION "1.5.0"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define YYTEXT_POINTER 1
/* end confdefs.h.  */
 #include <oniguruma.h>
int
main ()
{

  ;
  return 0;
}
```

`#include <oniguruma.h>` what this head-file is used for?  and how to fix this problem ?

Best regards

**Comment by textarcana** [comment]
I just got done compiling jq on Mac OSX, thought I'd share what I had to do. Note I use MacPorts not HomeBrew so if that's different for you then you may need compile fewer / more things from source.


#### Install Bison 3:

    cd /tmp
    wget http://ftp.gnu.org/gnu/bison/bison-3.0.3.tar.gz
    tar -xvzf bison-3.0.3.tar.gz
    cd bison-3.0.3
    sudo port install m4
    ./configure --prefix=/usr/local/bison
    sudo make install
    sudo ln -s /usr/local/bison/bin/bison /usr/bin/bison

#### Install RVM dependencies:

    cd ~/jq/docs
    curl -L https://get.rvm.io | bash -s stable --ruby=1.9.3
    cd docs
    bundle install

#### Install C headers

    wget http://www.geocities.jp/kosako3/oniguruma/archive/onig-5.9.6.tar.gz
    tar -xf onig-5.9.6.tar.gz
    cd onig-5.9.6
    ./configure
    make
    sudo make install

#### Build jq

    cd ~/jq
    autoreconf -i
    ./configure
    make -j8
    sudo make install

**Comment by pkoppstein** [comment]
@textarcana - Thanks for the "recipe", which I have incorporated into a new page on the jq wiki: https://github.com/stedolan/jq/wiki/Installation
