### ISSUE TITLE
Deep fields

### ISSUE THREAD

**Issue by pannous** [stedolan/jq#536]
it would be very nice if we could query deep fields without knowing the exact path,
 for example instead of 
jq '.results.hits.hits[].title' 
just 
jq '..title' 
or so

**Comment by svnpenn** [comment]
Couldnt you just do:

~~~
jq '.. | .title? | select(.)'
~~~

also it feels like this should be a builtin

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/1568

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/319
