### ISSUE TITLE
Split an URL/URI into components

### ISSUE THREAD

**Issue by joelpurra** [stedolan/jq#537]
Does anyone have jq code to split an URL/URL ([RFC3986)](https://tools.ietf.org/html/rfc3986) into components? I'm thinking scheme, authority, path, query, fragment and, and the possibly splitting those into further parts (domain, port, querystring parameters etcetera).

```text
   The following are two example URIs and their component parts:

         foo://example.com:8042/over/there?name=ferret#nose
         \_/   \______________/\_________/ \_________/ \__/
          |           |            |            |        |
       scheme     authority       path        query   fragment
          |   _____________________|__
         / \ /                        \
         urn:example:animal:ferret:nose
```

Dealing with URLs from the public web and anticipating problems with malformed input, which is why I'm asking if anyone might have done something similar. [So far I've only used a basic `split("...")`](https://github.com/joelpurra/har-dulcify/blob/master/src/extract/request/expand-parts.sh) to get protocol/scheme and domain (further split into components).

Is there a module yet?

---

**Update**

Released code to convert URL strings to/from objects, for jq v1.4:

- https://github.com/joelpurra/jq-hopkok/tree/master/src/url

**Comment by dirk-proper** [comment]
This is exactly what I needed, but I had to tweak the regex in the parseURL function to make it work for me:
```
def parseURL:
    capture( "^((?<scheme>[^:/?#]+):)?(//(?<authority>(?<domain>[^/?#:]*)(:(?<port>[0-9]*))?))?((?<path>[^?#]*)\\?)?((?<query>([^#]*)))?(#(?<fragment>(.*)))?");
```

**Comment by erhhung** [comment]
I've enhanced the example here with query string decoding and elimination of nulls.
For simplicity, it assumes that query params contain only **unique** key-value pairs.
I may have also missed some URI components that may need to be `urldecode`ed.

```jq
def urldecode:
  # urldecode courtesy of: https://gist.github.com/jcracknell/52cf4e0f8c4518a853784638db8a258d
  def unhex:
    if 48 <= . and . <= 57 then . - 48 elif 65 <= . and . <= 70 then . - 55 else . - 87 end;
  def bytes:
    def loop($i):
      if $i >= length then empty else 16 * (.[$i+1] | unhex) + (.[$i+2] | unhex), loop($i+3) end;
    [loop(0)];
  def codepoints:
    def loop($i):
      if $i >= length then empty
      elif .[$i] >= 240 then (.[$i+3]-128) + 64*(.[$i+2]-128) + 4096*(.[$i+1]-128) + 262144*(.[$i]-240), loop($i+4)
      elif .[$i] >= 224 then (.[$i+2]-128) + 64*(.[$i+1]-128) + 4096*(.[$i]-224), loop($i+3)
      elif .[$i] >= 192 then (.[$i+1]-128) + 64*(.[$i]-192), loop($i+2)
      else .[$i], loop($i+1) end;
    [loop(0)];
  gsub("(?<m>(?:%[0-9a-fA-F]{2})+)"; .m | explode | bytes | codepoints | implode);

def urlparse:
  # urlparse courtesy of: https://github.com/stedolan/jq/issues/537
  # delete nulls courtesy of: https://github.com/stedolan/jq/issues/104
  capture("^((?<scheme>[^:/?#]+):)?(//(?<authority>(?<domain>[^/?#:]*)(:(?<port>[0-9]*))?))?((?<path>[^?#]*)\\?)?((?<query>([^#]*)))?(#(?<fragment>(.*)))?")
    | if .query then .query |= ((split("&") | .[] |= (split("=") | {(.[0]): .[1] | urldecode})) | add) else . end
    | del(.[] | nulls);
```

Running the above function gives output like:
```bash
$ jq -R "$(< urlparse.jq)"'urlparse' <<< 'https://github.com/search?o=desc&p=1&q=jq&s=updated&type=Repositories'
```
```json
{
  "scheme": "https",
  "authority": "github.com",
  "domain": "github.com",
  "path": "/search",
  "query": {
    "o": "desc",
    "p": "1",
    "q": "jq",
    "s": "updated",
    "type": "Repositories"
  }
}
```

**Comment by mandric** [comment]
Can these by any chance get added to jq std lib? :D

**Comment by pkoppstein** [comment]
I just noticed that there's a serious bug in the `capture` in @erhhung's `def urlparse`.  It should be:
```
capture("^((?<scheme>[^:/?#]+):)?(//(?<authority>(?<domain>[^/?#:]*)(:(?<port>[0-9]*))?))?((?<path>[^?#]*))?(\\?(?<query>([^#]*)))?(#(?<fragment>(.*)))?")
```

That is, a "query" must be preceded by `?`.

**Comment by erhhung** [comment]
> I just noticed that there's a serious bug in the `capture` in @erhhung's `def urlparse` (which was borrowed from @dirk-proper's post). The call to `capture` should be:
> 
> ```
> capture("^((?<scheme>[^:/?#]+):)?(//(?<authority>(?<domain>[^/?#:]*)(:(?<port>[0-9]*))?))?((?<path>[^?#]*))?(\\?(?<query>([^#]*)))?(#(?<fragment>(.*)))?")
> ```
> 
> That is, a "query" must be preceded by `?`.

@pkoppstein Thanks for pointing out the regex bug.

I've updated the previous post with a corrected version (like yours, but further simplified by removing extraneous parentheses) since others may likely just copy the code.  
I've also demo'ed another unit test case without query.

I've included the original, **faulty definition below** for history.
```jq
def urlparse:
  # urlparse courtesy of: https://github.com/stedolan/jq/issues/537
  # delete nulls courtesy of: https://github.com/stedolan/jq/issues/104
  capture("^((?<scheme>[^:/?#]+):)?(//(?<authority>(?<domain>[^/?#:]*)(:(?<port>[0-9]*))?))?((?<path>[^?#]*)\\?)?((?<query>([^#]*)))?(#(?<fragment>(.*)))?")
    | if .query then .query |= ((split("&") | .[] |= (split("=") | {(.[0]): .[1] | urldecode})) | add) else . end
    | del(.[] | nulls);
```

**Comment by phalbert** [comment]
thank you for this solution

**Comment by tionis** [comment]
This does not handle URLs like https://example.com/foo?edit

**Comment by tionis** [comment]
I fixed it:
```jq
def urlparse:
  # urlparse courtesy of: https://github.com/stedolan/jq/issues/537
  # delete nulls courtesy of: https://github.com/stedolan/jq/issues/104
  capture("^((?<scheme>[^:/?#]+):)?(//(?<authority>(?<domain>[^/?#:]*)(:(?<port>[0-9]*))?))?(?<path>[^?#]*)?([?](?<query>[^#]*))?(#(?<fragment>.*))?")
    | if .query
      then .query |= ((split("&") | .[] |= (split("=") | if (.|length) > 1
                                                         then {(.[0]): .[1] | urldecode}
                                                         else {(.[0]): ""} end)) | add)
      else . end
    | del(.[] | nulls)
 ```

**Comment by wader** [comment]
Any ideas how URLs processing functions/formats etc would work? https://github.com/wader/fq has `from_url`/`to_url` that are based on https://pkg.go.dev/net/url but it does not feel particulary elegant, but works ok. Ex:

```sh
$ fq -R from_url <<< 'https://example.com/foo?edit'
{
  "host": "example.com",
  "path": "/foo",
  "query": {
    "edit": ""
  },
  "rawquery": "edit",
  "scheme": "https"
}

$ fq -Rr 'from_url | .query.id=123  | to_url' <<< 'https://example.com/foo?edit'
https://example.com/foo?edit=&id=123
```

**Comment by mcoliver** [comment]
I know this is an old thread but perhaps this helps someone down the line.  I wrote a pretty simple tool called uq that parses urls and spits out colorized (or non colorized) output.  It recursively looks for urls and will convert url encoding to ascii.  Pretty bare bones.  [https://github.com/mcoliver/uq](https://github.com/mcoliver/uq)

**Comment by titaniumtraveler** [comment]
> Any ideas how URLs processing functions/formats etc would work? https://github.com/wader/fq has `from_url`/`to_url` that are based on https://pkg.go.dev/net/url but it does not feel particulary elegant, but works ok. Ex:
> 
> $ fq -R from_url <<< 'https://example.com/foo?edit'
> {
>   "host": "example.com",
>   "path": "/foo",
>   "query": {
>     "edit": ""
>   },
>   "rawquery": "edit",
>   "scheme": "https"
> }
> 
> $ fq -Rr 'from_url | .query.id=123  | to_url' <<< 'https://example.com/foo?edit'
> https://example.com/foo?edit=&id=123

I would say it should probably be exposed as an API like the `*_entries` functions.
Like there is `to_entries`, `from_entries`, `with_entries(f)`, there should be `to_url`, `from_url`, `with_url(f)`

Seems like good standard to use for converting between and manipulating formats.

**Comment by joelpurra** [comment]
As an external URL-as-components JSON preparser, there's [`trurl`](https://curl.se/trurl/) ([source code](https://github.com/curl/trurl), [man page](https://curl.se/trurl/manual.html)). It's a part of the [`curl`](https://curl.se/) project, using the same `libcurl` URL parsing logic.

Depending on your use-case `trurl`'s URL cleanup/normalization/de-obfuscation might be useful:

- Ipv4 address normalization of scary decimal/octal/hexadecimal variants (`https://646464646/` is `https://38.136.68.134/`).
- Ipv6 address normalization, zone id.
- Decoding/encoding internationalized domain name (IDN) punycode/unicode (for example [emoji domains](https://en.wikipedia.org/wiki/Emoji_domain); https://xn--ls8h.la/).
- Relative path `/one/../two/../three/./four` normalization.
- URI `%xx` percent-encoding normalization; similar to per-component `@urid | @uri`.
- Well-known default protocol port removal.

URL normalization is useful on its own and should simplify further URL handling. Beware that some of the above obfuscations may also be used by attackers to bypass naive URL-based filtering/security.

---

See also usage examples in their manual.

```shell
trurl --json 'foo://example.com:8042/over/there?name=ferret#nose'
```

```json
[
  {
    "url": "foo://example.com:8042/over/there?name=ferret#nose",
    "parts": {
      "scheme": "foo",
      "host": "example.com",
      "port": "8042",
      "path": "/over/there",
      "query": "name=ferret",
      "fragment": "nose"
    },
    "params": [
      {
        "key": "name",
        "value": "ferret"
      }
    ]
  }
]
```

---

The [`trurl` package](https://github.com/curl/trurl/wiki/Get-trurl-for-your-OS) seems commonly available:

[![Packaging status](https://repology.org/badge/vertical-allrepos/trurl.svg)](https://repology.org/project/trurl/versions)
