### ISSUE TITLE
Working with huge data sets - parallelization speed ups, `reduce` with `--slurp`

### ISSUE THREAD

**Issue by joelpurra** [stedolan/jq#550]
For json data in the gigabytes, the key is using [GNU `parallel`](https://www.gnu.org/software/parallel/) for both mapping and reducing. `parallel` helps speeding up the process by utilizing all available CPU cores (by default), and allows for stepwise reductions without running out of RAM.

Assuming a single `input.json` file with separate objects. No separator, but they start and end without indentation.

```json
{
    "a": 1
}
{
    "a": 2
}
```

```bash
parallel --pipe --group --block 10M --recend '\n}\n' jq 'do whatever with each object here'
```

This works great, as `parallel` will make sure that the input is spread objects in 10 megabyte chunks (rounded up to where the nearest object ends with `\n}\n`) to one jq process per CPU core, yet keep the resulting `output.json` grouped (object order doesn't matter to me). I've put the parallelization in a separate script, [`parallel-chunks.sh`](https://github.com/joelpurra/har-dulcify/blob/master/src/util/parallel-chunks.sh).

```bash
<"input.json" parallel-chunks.sh jq 'some kind of transform' >"output.json"
```

For reductions, I just repeat the process multiple times on 10 megabyte chunks until I only have one object left:

```jq
reduce .[1:][] as $item
(
	.[0];
	# Merge the first object with each of following objects however you like:
	. * $item
)
```

I run the above as `jq --slurp 'reduce ...'`. One example of a simple reduce/merge is the one that recursively adds objects and properties which are numbers, [`reduce-merge-deep-add.sh`](https://github.com/joelpurra/har-dulcify/blob/master/src/util/reduce-merge-deep-add.sh)

Repeated reductions usage (pseudo-code)

```bash
<"input.json" parallel-chunks.sh reduce-merge-deep-add.sh >"output.tmp.1.json"

while [[ $(getJsonObjectCount "output.tmp.1.json") > 1 ]] do
	<"output.tmp.1.json" parallel-chunks.sh reduce-merge-deep-add.sh >"output.tmp.2.json"
	mv "output.tmp.2.json" "output.tmp.1.json"
}

mv "output.tmp.1.json" "output.json"
```

I use this, in a somewhat more complicated way (cleaning up temp-files, cross-platform counts etcetera) when I prepare (map) and collect aggregate (reduce) numbers from different web pages in [`aggregate/all.sh`](https://github.com/joelpurra/har-dulcify/blob/master/src/aggregate/all.sh). Will try to generalize it later, so you can run something like `repeated-reductions.sh` with any `jq --slurp 'reduce ...'`.

I also use [pipe viewer `pv`](http://www.ivarch.com/programs/pv.shtml) to monitor speed sometimes, but since the output size (usually, otherwise use [`--size`](http://www.ivarch.com/programs/quickref/pv.shtml)) is unknown, it's only a crude indicator on that end.

```bash
pv -cN 'input' "input.json" | parallel-chunks.sh jq 'some transformation' | pv -cN "output" >"output.json"
```

In my case, I have about 100k separate objects in a single file, about six gigabytes in size. I've put them in the same file (at first) to reduce the number of non-sequential disk reads/file lookups, and so I can keep output from each step ([there are many steps](https://github.com/joelpurra/har-dulcify/blob/master/src/one-shot/data.sh)) together as a single file.

Is this anything like how you've solved your CPU/memory limitation problems too?

**Comment by dtolnay** [comment]
This would make a great [Cookbook](https://github.com/stedolan/jq/wiki/Cookbook) entry if you have some time to write it up as one.

**Comment by joelpurra** [comment]
@dtolnay: good idea. Usage is based on jq v1.4 though, so will keep it in [jq-hopkok's parallelism folder](https://github.com/joelpurra/jq-hopkok/tree/master/src/parallelism) together with the shell scripts and add a link instead. Just pushed an update with some 20 utilities.
