### ISSUE TITLE
Split output array length inconsistency

### ISSUE THREAD

**Issue by joelpurra** [stedolan/jq#552]
Splitting a string where the string to split on matches the last character in the input string returns an array that's shorter than other results. Compare with a split on the first character.

```bash
echo '"xyz"' | jq 'split("x"), split("y"), split("z")'
```
```json
[
  "",
  "yz"
]
[
  "x",
  "z"
]
[
  "xy"
]
```

Shouldn't it return an empty string instead of omitting the last result?

**Comment by joelpurra** [comment]
I'll revisit this, as I just now experienced problems with `length` and `join/1` for the split strings in the original issue. Please note that both the original and this issue have been (re-)tested using `jq --version` `jq-1.5rc1`.

## `jq-1.5rc1`

### Original `split/1` issue from above

`split("z")` produces a single element array instead of two.

```bash
echo '"xyz"' | jq 'split("x"), split("y"), split("z")'
```
```json
[
  "",
  "yz"
]
[
  "x",
  "z"
]
[
  "xy"
]
```

### `length` versus `join/1` inconsistencies

What happens if I compare `length` and `join/1`? Further inconsistencies. Notice the difference in the first example - length 2, but join doesn't have a dot in it. It seems empty strings are counted by `length`, but not used by `join/1`.


```bash
echo '"xyz"' | jq 'split("x"), split("y"), split("z") | length'
```
```json
2
2
1
```

```bash
echo '"xyz"' | jq 'split("x"), split("y"), split("z") | join(".")'
```
```json
"yz"
"x.z"
"xy"
```

---

## Expected behavior

```bash
echo '"xyz"' | jq 'split("x"), split("y"), split("z")'
```
```json
[
  "",
  "yz"
]
[
  "x",
  "z"
]
[
  "xy",
  "",
]
```

```bash
echo '"xyz"' | jq 'split("x"), split("y"), split("z") | length'
```
```json
2
2
2
```

```bash
echo '"xyz"' | jq 'split("x"), split("y"), split("z") | join(".")'
```
```json
".yz"
"x.z"
"xy."
```

---

## Comparison to javascript

```javascript
"xyz".split("x")
// ["", "yz"]

"xyz".split("y")
// ["x", "z"]

"xyz".split("z")
// ["xy", ""]
```
```javascript
"xyz".split("x").length
// 2

"xyz".split("y").length
// 2

"xyz".split("z").length
// 2
```
```javascript
"xyz".split("x").join(".")
// ".yz"

"xyz".split("y").join(".")
// "x.z"

"xyz".split("z").join(".")
// "xy."
```

As you can see, empty strings are counted and joined.

**Comment by joelpurra** [comment]
It seems @pkoppstein's confirmed fix doesn't work - but guess it's because of #576.

**Comment by nicowilliams** [comment]
Thanks for the bug report!  keep banging on it.  I'll fix this sometime
this coming week, and if i can fix the remaining module system problems in
a couple of hours then we'll have a 1.5rc2 soon enough.

**Comment by joelpurra** [comment]
Released a bugfix package, which will alleviate problems for now.
https://github.com/joelpurra/jq-bugfix-jq-552

```jq
import "joelpurra/jq-bugfix-jq-552" as BugfixJq552;

# These tests fail for vanilla split/join, but they are detected and shows debug output.
#
# BugfixJq552::warningSplit: Single string to two empty parts. SHOWS DEBUG OUTPUT.
"a" | BugfixJq552::warningSplit("a") # Expected [ "", "" ], Actually [ "" ]

# BugfixJq552::warningSplit: Single string to two parts z. SHOWS DEBUG OUTPUT.
"xyz" | BugfixJq552::warningSplit("z") # [ Expected "xy", "" ], Actually [ "xy" ]

# BugfixJq552::warningJoin: Single string to two empty parts. SHOWS DEBUG OUTPUT.
[ "", "" ] | BugfixJq552::warningJoin("a") # Expected "a", Actually ""

# BugfixJq552::warningJoin: Two parts x. SHOWS DEBUG OUTPUT.
[ "", "yz" ] | BugfixJq552::warningJoin("x") # Expected "xyz", Actually "yz"


# Instead use the functions which attempt to fix these inconsistencies.
#
# BugfixJq552::attemptFixSplit: Single string to two empty parts.
"a" | BugfixJq552::attemptFixSplit("a") # [ "", "" ]

# BugfixJq552::attemptFixSplit: Single string to two parts z.
"xyz" | BugfixJq552::attemptFixSplit("z") # [ "xy", "" ]

# BugfixJq552::attemptFixJoin: Single string to two empty parts.
[ "", "" ] | BugfixJq552::attemptFixJoin("a") # "a"

# BugfixJq552::attemptFixJoin: Two parts x.
[ "", "yz" ] | BugfixJq552::attemptFixJoin("x") # "xyz"
```

**Comment by joelpurra** [comment]
@nicowilliams: this fix broke another case, as detected by [joelpurra/jq-bugfix-jq-552](https://github.com/joelpurra/jq-bugfix-jq-552).

Updated the package with additional tests (including plain `split`/`join` tests) and fixes for the current version 60d1ecb. See [`tests/all.sh`](https://github.com/joelpurra/jq-bugfix-jq-552/blob/master/tests/all.sh) for test cases and [`jq/main.jq`](https://github.com/joelpurra/jq-bugfix-jq-552/blob/master/jq/main.jq) for how I worked around them. Might add some more tests later.

These `split`s now work:

```bash
# split: Single string to two empty parts.
jq -n '"a" | split("a")' # Expected [ "", "" ]

# split: Single string to two parts z.
jq -n '"xyz" | split("z")' # [ Expected "xy", "" ]
```

This `split` does not work:

```bash
# split: Single string split with empty string.
jq -n '"a" | split("")' # Expected [ "a" ], Actually [ "a", "" ]
```
These `join`s do not work:
```bash
# join: Single string to two empty parts.
jq -n '[ "", "" ] | join("a")' # Expected "a", Actually ""

# join: Two parts x.
jq -n '[ "", "yz" ] | join("x")' # Expected "xyz", Actually "yz"
```

**Comment by nicowilliams** [comment]
On Tue, Jan 13, 2015 at 06:56:58AM -0800, Joel Purra wrote:
> @nicowilliams: this fix broke another case, as detected by [joelpurra/jq-bugfix-jq-552](https://github.com/joelpurra/jq-bugfix-jq-552).

Thanks.

Shouldn't splitting on the empty string yield an array of single-character (well, single-codepoint; jq doesn't know about characters) strings, with an empty string in the front and an empty one at the end?

"Obviously" in this case we can just drop the leading and trailing empty strings.  But it's not so obvious to me.

> This `split` does not work:
> 
> ```bash
> # split: Single string split with empty string.
> jq -n '"a" | split("")' # Expected [ "a" ], Actually [ "a", "" ]
> ```

Why shouldn't we expect `["","a",""]`?

> These `join`s do not work:
> ```bash
> # join: Single string to two empty parts.
> jq -n '[ "", "" ] | join("a")' # Expected "a", Actually ""
> # join: Two parts x.
> jq -n '[ "", "yz" ] | join("x")' # Expected "xyz", Actually "yz"
> ```

I didn't touch `join`.  I'll take a look.  These are definitely bugs.

**Comment by joelpurra** [comment]
@nicowilliams: `split` seems to work now, thanks!

**Comment by joelpurra** [comment]
@nicowilliams wrote:
> Shouldn't splitting on the empty string yield an array of single-character (well, single-codepoint; jq doesn't know about characters) strings, with an empty string in the front and an empty one at the end?

Yes - forgot this was the standard thing for split on an empty string, and didn't get to writing multi-character test cases. `"abc" | split("") # ["a","b","c"]` Looks good, thanks!
