### ISSUE TITLE
enhancement request: first/2 and first_with_index/2

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#554]
Given a generator, one often just wants the first item that satisfies
some condition.  It is currently surprisingly awkward to accomplish this
task efficiently.

Suppose, for example, `primes` generates primes, and we want the first prime greater than n:

An efficient solution is:
```
def firstPrimeGreaterThan(n):
  foreach primes as $p (null; if . then break elif $p > n then $p else empty end; .);
```
But this requires too much typing (and too much thought), given that we ought
to be able to write something straightforward, such as:
```
  first(primes; . > n)
```
Similarly if we want the first item together with its index.

Below are two functions, first/2, and first_with_index/2, that fill the bill.

The main question, I think, is whether *_with_index should emit [ix, value] or [value, ix].
```
# Emit the first item that satisfies the condition.
def first(generator; condition):
  # [ done, answer ]
  foreach generator as $i
    ([false,null];
     if .[0] then break elif ($i | condition) then [true,$i] else . end;
     if .[0] then .[1] else empty end );

# first_with_index(generator; condition) emits [x, i] where x is the
#  first item (in the sequence of values generated by the
#  generator) that satisfies the condition, and i is its 0-based index
#  in the sequence.
def first_with_index(generator; condition):
  foreach generator as $i
    ([false,null,0];  # [done, answer, ix]
     if .[0] then break elif ($i | condition) then [true, $i, .[2] + 1] else .[2] += 1 end; 
     if .[0] then .[1:] else empty end );
```

**Comment by dtolnay** [comment]
Ditto Nico - these belong in a module.
