### ISSUE TITLE
`to_entries` always outputs keys sorted - can it be avoided?

### ISSUE THREAD

**Issue by joelpurra** [stedolan/jq#561]
I care about output ordering, as I intend to use automated jq output in a report. After using `to_entries` (or `with_entries`) my original ordering is lost.

In these examples I want to keep the order `c, b, a`. The numeric values are an example; I can't use them for key ordering.

Order changed by `to_entries`.

``` bash
echo '{ "c": 1, "b": 2, "a": 3 }' | jq 'to_entries'
```

``` json
[
  {
    "key": "a",
    "value": 3
  },
  {
    "key": "b",
    "value": 2
  },
  {
    "key": "c",
    "value": 1
  }
]
```

Order changed by `with_entries`, because it uses `to_entries`.

``` bash
echo '{ "c": 1, "b": 2, "a": 3 }' | jq 'with_entries(.)'
```

``` json
{
  "a": 3,
  "b": 2,
  "c": 1
}
```

Using `from_entries` is no problem. Using `reverse` as an example only.

``` bash
echo '{ "c": 1, "b": 2, "a": 3 }' | jq 'to_entries | reverse | from_entries'
```

``` json
{
  "c": 1,
  "b": 2,
  "a": 3
}
```

My problem is similar to the ordering issues in #48 "tsv and/or csv output support". I'm writing generic code though, and want to avoid manually specifying column ordering for each dataset.

Should `to_entries` produce key-sorted output?

**Comment by Gerst20051** [comment]
:+1:
