### ISSUE TITLE
Raw lines to an array of lines?

### ISSUE THREAD

**Issue by rfletcher** [stedolan/jq#563]
Is there a way to convert multiline, non-JSON input to a JSON array of lines in one invocation of `jq`?

Desired result:

``` shell
echo -en "foo\nbar\nbaz" | jq <unknown set of options and expression>
[
  "foo",
  "bar",
  "baz"
]
```

Failed attempts:

``` shell
$ echo -en "foo\nbar\nbaz" | jq --raw-input '[.]'
[
  "foo"
]
[
  "bar"
]
[
  "baz"
]
```

``` shell
$ echo -en "foo\nbar\nbaz" | jq --raw-input --slurp '[.]'
[
  "foo\nbar\nbaz"
]
```

I did manage to get the result that I want, but only by using `--raw-input` and `--slurp` separately:

``` shell
$ echo -en "foo\nbar\nbaz" | jq --raw-input . | jq --slurp .
[
  "foo",
  "bar",
  "baz"
]
```

Is that the preferred way?

**Comment by andrewharvey** [comment]
`| .[0:-1]` will remove that last empty element.

**Comment by davidfetter** [comment]
```jq --raw-input --slurp 'split("\n") | map(select(. != ""))' query.txt```
removes blank lines.

**Comment by pkoppstein** [comment]
If your jq has `inputs` then to avoid having to read the whole file into memory up front, it would be better to use it, e.g. if empty lines are to be omitted:

    jq -nR '[inputs | select(length>0)]'

**Comment by scr-oath** [comment]
How about using the `--args` flag:

```
$ jq -n '$ARGS.positional' --args foo bar baz
[
  "foo",
  "bar",
  "baz"
]

```

**Comment by lorenzogrv** [comment]
@pkoppstein Awesome solution, but I would like to ask:

1. why `--null-input` if ussing `--raw-input`?
2. Wouldn't `jq --raw-input '[inputs]'` suffice?

> If your jq has `inputs` then to avoid having to read the whole file into memory up front, it would be better to use it, e.g. if empty lines are to be omitted:
> 
> ```
> jq -nR '[inputs | select(length>0)]'
> ```

**Comment by itchyny** [comment]
@lorenzogrv  Unless specifying the `--null-input` (`-n`) option, the first input value is used as the input to the query. Checkout the difference of `seq 3 | jq -nR '., [inputs]'` and `seq 3 | jq -R '., [inputs]'`.

**Comment by lorenzogrv** [comment]
@itchyny oh, I see. Thx 😄
