### ISSUE TITLE
Array contruction reacts differently to input sourced from slurp vs standard

### ISSUE THREAD

**Issue by henriksteen** [stedolan/jq#564]
Given the following input:
{"list":["a"]}
{"list":["b","c"]}
{"list":["d"]}

.list|length produces:
1
2
1

-s .[]|.list|length produces
1
2
1

So far so good, but

-s [.[]|.list|length] produces:
[1,2,1]

Whereas:
[.list|length] produces:
[1] 
[2]
[3]

They both had the same input, so why the radically different results?

According to the manual it looks like [1,2,3] is the intended outcome in both cases. Am I missing something?

**Comment by nicowilliams** [comment]
@henriksteen I think the `inputs` built-in probably satisfies this request.  Can you confirm?

(I.e., you can now `jq -n 'reduce inputs (...)'` to process a stream of inputs incrementally without having to slurp them but still being able to map/reduce over them.)
