### ISSUE TITLE
Bug: Will not run on RHEL 5 or 6

### ISSUE THREAD

**Issue by dtklein** [stedolan/jq#569]
JQ will not run in current versions of RHEL 5 and RHEL 6. The error message is 

/www/layer7/scripts/jq: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /www/layer7/scripts/jq)

The servers in which this was tested run RHEL 5u10 and RHEL 6u5 respectively.

Because RHEL 7 is so new, most RHEL boxes one encounters will be the most recent RHEL 5 or RHEL 6 version. 

Is there a way to run JQ on a standard RHEL box? Any chance we could get a statically-compiled version, so it could be used in any Linux box, of any (reasonable) version?

**Comment by nicowilliams** [comment]
Built statically for Linux for jq-1.5rc1.

**Comment by dtklein** [comment]
Thank you so much! We simplified several scripts running in BASH on Windows, and have been looking forward to getting that same benefit on Linux. Happy New Years and props for such a great tool. 


--
david t. klein
david@tenar.us

@dtklein

**Comment by nicowilliams** [comment]
Happy new year to you as well @dtklein!  I'm glad you're getting good use out of jq.
