### ISSUE TITLE
merge arrays

### ISSUE THREAD

**Issue by vito-c** [stedolan/jq#572]
`echo '{ "a":"foo", "b":["one","two","three"] } { "b":["three","four"], "c":["five"], "d":"bar" }' | jq -s add`
result:
`{
  "a": "foo",
  "b": [
    "three",
    "four"
  ],
  "c": [
    "five"
  ],
  "d": "bar"
}`

I'd like to merge obj1.b and obj2.b + obj2.c into a resulting object that has everything.

I tried things outlined here: https://github.com/stedolan/jq/issues/502 using flatten and reduce but haven't been getting any luck :(

**Comment by aep-sunlife** [comment]
This is the behavior I would expect of `| flatten` or `| add` or `| +` but none of these reliably concatenates arrays.
