### ISSUE TITLE
Add built in printf function

### ISSUE THREAD

**Issue by ekimekim** [stedolan/jq#614]
As it stands, there is currently little flexibility in how to convert values to a string.
What I would like is a printf-style function that can format a string based on inputs. I'd imagine something like:
printf(format_str) : Takes a list as input and outputs a string. Each element of the list is used as the input to the respective format character. The list must be the correct length.

For example:
`["foo", 3.14159, 2.71828] | printf("Hello %5s, your data is %.2f, %d")`
would produce
`"Hello   foo, your data is 3.14, 2"`

Another possible option that would work better with the existing string interpolation might be a function that simply does the tostring conversion with a format spec, like `1|format("02d") == "01"`.
Then my above example might look more like:
`["foo", 3.14159, 2.71828] | "Hello \(.[0]|format("5s")), your data is \(.[1]|format(".2f")), \(.[2]|format("d"))"`

**Comment by vlcinsky** [comment]
My need is to be able converting integers into hex representation (that is how I came to this issue).

Looking forward to see printf in next jq version..

**Comment by dolzenko** [comment]
Sorry to hijack, but that issue comes up as the "convert to string result", so I decided not to create a new one. Soo how does one currently converts number to string?

**Comment by pkoppstein** [comment]
@dolzenko: `tostring`

**Comment by pbkdf3** [comment]
is there any way to produce formatted (non json) final output with jq yet?  so many applications for this.

**Comment by pbkdf3** [comment]
anyone ending up here might want to look at string interpolation, does 99% of what I'd use printf for: https://stedolan.github.io/jq/manual/#Stringinterpolation-\(foo)

**Comment by Wolf480pl** [comment]
@pbkdf3 look at the example in the first post / issue description - it's mostly about various number conversion/formatting options (decimal/hex/scientific, leading zeros/spaces, decimal places, etc.)

**Comment by nicowilliams** [comment]
A proper `printf` will have to wait until we have varargs support, whenever that might be.  In the meantime you can use string interpolation.

**Comment by tomwhoiscontrary** [comment]
I would like to convert timestamps expressed in milliseconds since the epoch to ISO 8601 strings, with the milliseconds part. jq's built-in time formatting doesn't support milliseconds, so i could use printf, or some more sophisticated string interpolation, to format the milliseconds part, but jq doesn't have that either. One or the other would be really useful!

For my own future reference, i ended up with this:

```
(.event.timestamp / 1e3 | strftime("%Y-%m-%dT%H:%M:%S")) + ".\(.event.timestamp / 100 % 10)\(.event.timestamp / 10 % 10)\((.event.timestamp) % 10)Z"
```

**Comment by mmoya** [comment]
Linking to #1341 for further reference.

**Comment by ygoe** [comment]
I'd already be happy to pad a string with spaces to a specified length. Can't find a function for that and printf should be able to do that.

**Comment by johnhawkinson** [comment]
@nicowilliams wrote four years ago:
> A proper `printf` will have to wait until we have varargs support, whenever that might be. In the meantime you can use string interpolation.

The things I want to use printf for don't seem to be possible with string interpolation, (nor do they strictly require varargs support).
For instance, I want to right-align 3-digit numbers (minimum working example):

```sh
$ echo '[94, 172]' | jq -r '.[]' | awk '{$1=sprintf("%3d", $1); print}'
 94
172
```

Or various other printf conversions. Is there some workaround short of filtering through an external tool like awk?
If not, should this issue be reopened, or is there a more appropriate issue for this?

**Comment by pkoppstein** [comment]
Padding is easily done using defs such as these:
```
def lpad($len; $fill): tostring | ($len - length) as $l | ($fill * $l)[:$l] + .;

def lpad($len): lpad($len; " ");

def lpad: lpad(4);
```

Certainly having a `printf` would be convenient, but in terms of string manipulation, jq is already quite capable, thanks to its support for regular expressions via Oniguruma.

**Comment by lgfausak** [comment]
since the string is interpolated when parsed we can't save the 'format' for later use:

```
$ jq -rn '"test\(.num)" as $fs|{"num":1}|$fs'
testnull
```
this one works...
```
$ jq -rn '{"num":1}|"test\(.num)"'
test1
```
i tried like this, no luck:
```
$ jq -rn '"test\\(.num)" as $fs|{"num":1}|$fs'
test\(.num)
```
an eval like function would be needed to make interpolation work with a saved 'format' string.

**Comment by pkoppstein** [comment]
@lgfausak wrote:
> we can't save the 'format' for later use

One can "save" a format using a suitable `def`.

For example:

def f($num): "number: \($num)";

**Comment by wader** [comment]
@lgfausak if you looking for some kind of simpler templating with dynamic strings then  i've used something like this:

```jq
def template($s):
  ( . as $env
  | $s
  | gsub("\\{(?<var>.*?)}"; $env[.var])
  );

{name: "jq"} | template("hello {name}")

```

**Comment by robzr** [comment]
I made a module that implements `printf` in jq - hope this is of use to someone - https://github.com/robzr/jq-printf

**Comment by vgrebenschikov** [comment]
Guys, how to to dumb conversion from decimal number to hex number?

**Comment by wader** [comment]
@vgrebenschikov [fq](https://github.com/wader/fq) has a quite generic to/from radix implementation, i ripped it out and patch it up a bit to work with jq https://gist.github.com/wader/694fcc7d0184661a5c7a397530258cfc

Usage
```sh
$ jq -n -L . 'include "radix"; "fe" | from_radix(16)'
254
$ jq -n -L . 'include "radix"; 254 | to_radix(16)'
"fe"
```

**Comment by vgrebenschikov** [comment]
> @vgrebenschikov [fq](https://github.com/wader/fq) has a quite generic to/from radix implementation, i ripped it out and patch it up a bit to work with jq https://gist.github.com/wader/694fcc7d0184661a5c7a397530258cfc
> 
> Usage
> 
> ```shell
> $ jq -n -L . 'include "radix"; "fe" | from_radix(16)'
> 254
> $ jq -n -L . 'include "radix"; 254 | to_radix(16)'
> "fe"
> ```

thanks, 
although it would be very cool to have them onboarded in basic jq

**Comment by wader** [comment]
@vgrebenschikov yeap agree, would be nice

**Comment by dmartin-isp** [comment]
I wanted to output columns, like you do with printf and space padded formatting. All the recommendations I see on the interwebs are `write a def` or `call external printf`.  Would love some way to print aligned columns. Doesn't have to be printf.
