### ISSUE TITLE
Stop storing binaries in version control

### ISSUE THREAD

**Issue by svnpenn** [stedolan/jq#615]
Currently JQ binaries are stored in the `gh-pages` branch, this is bad.

~~~
$ git clone --bare git://github.com/stedolan/jq
Cloning into bare repository 'jq.git'...

$ du -bhs jq.git
9.1M    jq.git
~~~

Now you may say, "just use `--single-branch`", and yes this will help if you
want to work on `master`

~~~
$ git clone --bare --single-branch git://github.com/stedolan/jq
Cloning into bare repository 'jq.git'...

$ du -bhs jq.git
2.3M    jq.git
~~~

However, what if I want to make some changes on `gh-pages`

~~~
$ git clone --bare --single-branch --branch gh-pages git://github.com/stedolan/jq
Cloning into bare repository 'jq.git'...

$ du -bhs jq.git
8.3M    jq.git
~~~

No one is going to do a Pull Request on a binary file, so it does not make sense
to keep them on a branch. JQ binaries should be stored as releases, examples

[Clementine/releases](/clementine-player/Clementine/releases)
[notepad2-mod/releases](/XhmikosR/notepad2-mod/releases)

**Comment by dtolnay** [comment]
@nicowilliams, I migrated all existing binaries from version control into GitHub releases: [jq-1.4](https://github.com/stedolan/jq/releases/tag/jq-1.4) and [jq-1.3](https://github.com/stedolan/jq/releases/tag/jq-1.3).

Here is a script to verify the hashes of the binaries I migrated:

```sh
#!/bin/sh

set -eu

git clone --single-branch --branch gh-pages git@github.com:stedolan/jq.git
cd jq

check_hash() {
    local_hash=`sha1sum < $1`
    release_hash=`curl -L -s -S \
        https://github.com/stedolan/jq/releases/download/$2 | sha1sum`
    if [ "$local_hash" = "$release_hash" ]
    then
        echo pass $2
    else
        echo FAIL $2
    fi
}

check_hash download/linux32/jq jq-1.4/jq-linux-x86
check_hash download/linux64/jq jq-1.4/jq-linux-x86_64
check_hash download/osx32/jq jq-1.4/jq-osx-x86
check_hash download/osx64/jq jq-1.4/jq-osx-x86_64
check_hash download/solaris11-32/jq jq-1.4/jq-solaris11-32
check_hash download/solaris11-64/jq jq-1.4/jq-solaris11-64
check_hash download/win32/jq.exe jq-1.4/jq-win32.exe
check_hash download/win64/jq.exe jq-1.4/jq-win64.exe

check_hash download/linux32/jq-1.3/jq jq-1.3/jq-linux-x86
check_hash download/linux64/jq-1.3/jq jq-1.3/jq-linux-x86_64
check_hash download/osx32/jq-1.3/jq jq-1.3/jq-osx-x86
check_hash download/osx64/jq-1.3/jq jq-1.3/jq-osx-x86_64
check_hash download/win32/jq-1.3/jq-1.3.exe jq-1.3/jq-win32.exe
check_hash download/win64/jq-1.3/jq-1.3.exe jq-1.3/jq-win64.exe
```

**Comment by dtolnay** [comment]
@nicowilliams, as @svnpenn pointed out we can shrink the git repo size significantly by retroactively removing the binaries. Here is a script to remove the binaries from the history. It shrinks the size of `git clone --bare --single-branch --branch gh-pages ...` from 8.6 MB down to 1.9 MB, and the size of `git clone --bare ...` from 11 MB down to 3.7 MB. The resulting commit hash is a22f5425c95036dc444cca487dbf614cdb85a541. Please run the script to confirm no funny business, and then I will force push a22f5425c95036dc444cca487dbf614cdb85a541 to gh-pages using `--force-with-lease`.

```sh
#/bin/sh

set -eu

git clone git@github.com:stedolan/jq.git
cd jq
git checkout e11ab45a6b8a9e17b9311bb53e7db3baf86f0a25 # gh-pages

git filter-branch --index-filter '
    git rm --cached --ignore-unmatch -r -- \
    download/linux* download/osx* download/solaris* download/source* download/win*
    ' HEAD

final_hash=`git rev-parse HEAD`
if [ $final_hash != a22f5425c95036dc444cca487dbf614cdb85a541 ]
then
    echo "Unexpected final hash $final_hash"
    exit 1
fi

echo "SUCCESS"
```

**Comment by nicowilliams** [comment]
Excellent, thanks for doing this.  I'll review and run  this tomorrow.

**Comment by nicowilliams** [comment]
Actually, I checked now.  Looks good!  Go for it.

**Comment by dtolnay** [comment]
Done.

**Comment by dtolnay** [comment]
For additional tamper-proofing, the commit I force pushed is:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

a22f5425c95036dc444cca487dbf614cdb85a541
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJVxad8AAoJEPm6FDuV/22C/XgP/014ZEv+pPFhU9FGWPszcJd9
l2QbA2P0kbwpj8JAQRMuK7IwHQYqXtPAmfad2GgmAYJAPZSb4H9AyaFqvddPy+KU
EVsWLTRWxSRytnqvdLDnk/7fR6aQUfiNEln1UeUpqdjp8asRr3wykF2Y1sXvIjP4
hBEJxm6x7aezNhF68VqLcXa6mtV4LS1BYrnm9+4Kh0jpiDosEja4Q3LscJ2Z1CbA
oG0TVxevguVeokUyLjHib2pPoWRFAj6u5wz3GZPY68t6OZpY86J9mDUd8+Ls0L44
Ykb/4ELMwIppZUYAQgg9VAfVwSVp5MOI+YOgGw2EsuH5GENnDb4O86mHqTQGkiWy
QrW4Neu8ncAxvFu3aA1xZcc7u0yZ88c1f5rUiZBpcsyduLc7Cf80XlHh+O9Fwlmf
SY/BqlgAfJPvjwQ7Eskwms/K4gn13UBo6WF2vMwpYLmemBXSaXJ4P9Xq0Zprf6c7
UJ7AzqHp/N+1GD9gzRVaSTRqIruicqRpsO5zuuRrCFTRBUO4kxtBzp3VYtlffBOS
0vVINqimn2xzHfgsgFBMph3QRvdgnLqZD2ReotqWEEcJdG7JqQlYjNSGexYuVKyg
+NO9gzJQUyVTB3zLDSAsySLE9hKl9TLOYjoN70vGS1y28lmk2VgkelHIAzm3F/G+
hmIRJD0p77cJ1Owaom2H
=1KW3
-----END PGP SIGNATURE-----
```

You can verify my signature using `gpg --verify`.

**Comment by nicowilliams** [comment]
Is there a way to mark a branch as no-ffa in github?

**Comment by dtolnay** [comment]
What do you mean? How would that be useful?

**Comment by nicowilliams** [comment]
In case a developer accidentally does a git push -f they shouldn't.

**Comment by nicowilliams** [comment]
I completely botched my earlier question, of course.  See the edits.

**Comment by svnpenn** [comment]
Whoa @dtolnay, you fixed it! Great work
