### ISSUE TITLE
Option to skip input with invalid character sequences

### ISSUE THREAD

**Issue by francois** [stedolan/jq#621]
The message:

```
parse error: Invalid characters in \uXXXX escape
```

is very uninformative :( I'm processing millions of JSON documents through Hadoop Streaming. I don't know which line exactly has issues.

Ideally, I'd like an option to simply skip a / JSON object that has errors. My input consists of JSON objects on a single line, e.g. each line is a complete JSON object. If parsing fails for a line, I should start again on the next line.

**Comment by assafmo** [comment]
This feature will be great!
