### ISSUE TITLE
Using Variables in shell script 

### ISSUE THREAD

**Issue by kboghdady** [stedolan/jq#626]
How I can use shell variables on the jq command 
For example 
ID="THE_ID: .ID"
jq '. |{ $ID}'  file.json 

any ideas ?

**Comment by espoelstra** [comment]
Also note that when you are using single quotes around the jq query, you should NOT double quote around jq --arg variables within the query, it confuses and breaks things. This "shell-ism" is a habit that tripped me up in jq.

This first example would work:
```projectID=$(cat file.json | jq -r --arg EMAILID "$EMAILID" '.resource[]
                               | select(.username==$EMAILID) | .id')
```

This second example probably wouldn't:
```projectID=$(cat file.json | jq -r --arg EMAILID "$EMAILID" '.resource[]
                               | select(.username=="$EMAILID") | .id')
```

**Comment by higkoo** [comment]
jq '."media"."track"[] | select(."@type"=="General") | ."Encoded_Application"' 
# output: "Lavf56.40.101"

`{
  "media": {
    "@ref": "2016-07-13_03-01-49.flv",
    "track": [
      {
        "@type": "General",
        "VideoCount": "1",
        "AudioCount": "1",
        "FileExtension": "flv",
        "Format": "Flash Video",
        "FileSize": "739869",
        "Duration": "2.233",
        "OverallBitRate": "2650673",
        "FrameRate": "30.000",
        "FrameCount": "67",
        "File_Modified_Date": "UTC 2016-07-12 19:01:52",
        "File_Modified_Date_Local": "2016-07-13 03:01:52",
        "Encoded_Application": "Lavf56.40.101"
      },
      {
        "@type": "Video",
        "Format": "AVC",
        "Format_Profile": "Main",
        "Format_Level": "3.1",
        "Format_Settings_CABAC": "Yes",
        "Format_Settings_RefFrames": "4",
        "CodecID": "7",
        "Duration": "2.233",
        "BitRate": "2500000",
        "Width": "1280",
        "Height": "720",
        "Sampled_Width": "1280",
        "Sampled_Height": "720",
        "PixelAspectRatio": "1.000",
        "DisplayAspectRatio": "1.778",
        "FrameRate_Mode": "CFR",
        "FrameRate": "30.000",
        "FrameCount": "67",
        "ColorSpace": "YUV",
        "ChromaSubsampling": "4:2:0",
        "BitDepth": "8",
        "ScanType": "Progressive",
        "Delay": "0.000",
        "StreamSize": "697812",
        "Encoded_Library": "x264 - core 142",
        "Encoded_Library_Name": "x264",
        "Encoded_Library_Version": "core 142",
        "Encoded_Library_Settings": "cabac=1 / ref=1 / deblock=1:0:0 / analyse=0x1:0x111 / me=hex / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=12 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=120 / keyint_min=12 / scenecut=40 / intra_refresh=0 / rc_lookahead=10 / rc=cbr / mbtree=1 / bitrate=2500 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=2500 / vbv_bufsize=2500 / nal_hrd=none / filler=1 / ip_ratio=1.40 / aq=1:1.00"
      },
      {
        "@type": "Audio",
        "Format": "AAC",
        "Format_AdditionalFeatures": "LC",
        "CodecID": "10-2",
        "Duration": "2.229",
        "BitRate": "156250",
        "Channels": "2",
        "ChannelPositions": "Front: L R",
        "ChannelLayout": "L R",
        "SamplesPerFrame": "1024",
        "SamplingRate": "44100",
        "SamplingCount": "98299",
        "FrameRate": "43.066",
        "Compression_Mode": "Lossy",
        "Delay": "0.000",
        "Delay_Source": "Container",
        "StreamSize": "43535",
        "StreamSize_Proportion": "0.05884"
      }
    ]
  }
}`
