### ISSUE TITLE
Document when each feature was added

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#630]
The following lousy bit of shell gives an approximation.  Some builtins appear more than once, while anything known to `parser.y` instead of `builtin.c` does not appear at all:

        prev=master;
        for i in $(seq 0 4|tac) 5;
        do
            ((n=i+1))
            v=jq-1.$i
            [[ $v = jq-1.5 ]] && v=master
            #echo BETWEEN $prev and $v;
            git log -p ${v}..$prev builtin.c |
              grep '^[+] *"def' |
            cut -d: -f1 |
            sed -e 's/^[+]  "def //' \
              -e 's/[(][^;]*;[^;]*;[^;]*;*[)].*$/\/4/' \
              -e 's/[(][^;]*;[^;]*;*[)].*$/\/3/' \
              -e 's/[(][^;]*;*[)].*$/\/2/' \
              -e 's/[(][^;][)]*$/\/1/' \
              -e 's/$/ jq-1.'"${n}/"
            prev=$v;
        done | sort -u

**Comment by wtlangford** [comment]
@nicowilliams I'd like to make this coincide with the 1.5 release, so we have a new, clean version of the docs to bundle with the release.  I'm marking this as a 1.5 milestone so we don't miss it and I'll start working on it again in force.

**Comment by nicowilliams** [comment]
Thanks!

**Comment by pkoppstein** [comment]
@wtlangford - As you may already have noticed, there is currently a discrepancy between the current version of manual.yml and http://stedolan.github.io/jq/manual: the description of `split` and `splits` is correct in the former, but the latter describes `split2(re)`, which I doubt ever existed.  I mention this partly in the hope that the online manual can be corrected, and also in case there's any doubt about the reason for preferring the pair of names split/split2 over split/split2: it is simply that splits(re) produces a stream, whereas split(sep) produces an array. Thanks.

**Comment by chiefy** [comment]
:+1: just ran into this using 1.4 and trying to use `jq -j` which I really need :santa:

**Comment by dtolnay** [comment]
I am keeping this marked for the 1.5 milestone, but I think we should release with or without it. #866 will alleviate some of the pain.

**Comment by nicowilliams** [comment]
While this would be nice, it is now not a show-stopper for 1.5.

**Comment by dtolnay** [comment]
I think #866 has addressed the same needs as this, perhaps even in a better way. Let me know if you disagree.

**Comment by tianon** [comment]
Historic versions of the manual are indeed fantastic, but do serve a slightly different audience than this request -- I see the "since X.Y" in docs like Go as a handy way to decide whether I'm willing to accept that minimum version constraint on *my* code for users of it, especially when I'm already on a newer version but still care about older versions (especially given the descriptions of existing functions often improve over time, so there's a benefit to reading the "newer" docs even if 1.6 is the target). 😅
