### ISSUE TITLE
error code isn't set when 'jq' fails

### ISSUE THREAD

**Issue by yurivict** [stedolan/jq#638]
jq prints an error like this

```
jq: error: Cannot iterate over null
```

but returns zero exit code, so shells can't detect an error

**Comment by hmrm** [comment]
I'm still seeing this issue

**Comment by nicowilliams** [comment]
>
> I'm still seeing this issue
>

On master, with the `-e` option?

**Comment by hmrm** [comment]
It looks like I'm on an older version; sorry about the confusion!
