### ISSUE TITLE
Flatten array objects with parent values?

### ISSUE THREAD

**Issue by kmatt** [stedolan/jq#646]
Given:

```
{"id": 1, "date": "2014-12-30", "history":[{"id":1, "date":"2014-12-30", "type":"open"},{"id":2, "date":"2014-12-31", "type":"close"}]} 
```

I am attempting to flatten the data for import into RDBMS tables (via the @csv operator), with each object in the "history" array (with 1 or more array elements) as a separate line with the parent fields duplicated, as in:

```
{"id": 1, "date": '"2014-12-30", "id":1, "date":"2014-12-30', "type":"open"}
{"id": 1, "date": '"2014-12-30", "id":2, "date":"2014-12-31', "type":"close"}
```

eventually becoming

```
1, 2014-12-30, 1, 2014-12-30, "open"
1, 2014-12-30, 2, 2014-12-31, "close"
```

I see a flatten command coming in jq 1.5, but not sure if it or another method is already available in jq 1.4. Noting the "id" field is duplicated in name (as with the data I am receiving), I could either deal with it by position,  or accept a prefix assigned by jq.

Is there a generic pattern in jq to flatten a 1-level nested array like this?

**Comment by MostefaKamalLala** [comment]
7 years laters. I used it and still work with the actual jq. Thnx
