### ISSUE TITLE
ER: curl

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#650]
There has been some discussion about endowing jq with curl-like
support for retrieving information (and especially JSON) from remote
resources. In order to expedite enhancements in this direction (as
well as to provide support for reading from LOCAL files), I would like
to propose that jq use the "easy interface" of libcurl.  To this end,
I am appending a stand-alone C program, parts of which could be used 
for integrating jq and libcurl to support synchronous retrieval.

I realize that libcurl may be overkill, so if there are better
alternatives that would enable similar support for synchronous
retrieval of JSON documents (both locally and remotely) to be provided
expeditiously, that is fine.  However, I'd also like to point out that
libcurl could be used in the short-run without without making a
long-term commitment to using libcurl: stability is only needed for
the jq filters.

Still, libcurl has its advantages.  It is widely used and will
presumably be supported indefinitely.  It is sophisticated and will
provide a path for jq to follow as its own capabilities become more
sophisticated.

### Motivation
One of the reasons for requesting this enhancement is that I am using
a RESTful collection of tens of thousands of JSON documents, linked
together by ids in a kind of "graph database".  For example, an id
field in one document might be "1622", referring to another JSON
document at

http://api.legiscan.com/?key=InsertKeyHere&op=getSponsor&id=1622

Similarly, there are references within this "graph database" to entities
available elsewhere on the web as JSON objects.

The ability to query local files is also a major motivation.

### Non-JSON resources
For the sake of simplicity, the following assumes that the resource being
queried will return a single JSON entity.

### Specification
In order to accommodate future enhancements, I would tentatively
propose that all parameters except the URL and timeout be passed in
via a JSON object, e.g.
```
 { "username": "jqUser", "password": "secret", 
   "headers": { "User-Agent": "jq" } }
```
One possibility along these lines would be for jq initially to support
two jq filters:
```
def curl(obj; timeout): # timeout in seconds; input is a string specifying the URL with query parameters

def curl(obj): curl(obj;10);
```
These would of course either fail (or return null) or return a JSON entity.

### Questions

What should the name of the jq filter for retrieving JSON entities be?

How should non-JSON resources be supported?

### First Steps
The following is a standalone C program with functions that could be used to integrate jq with libcurl. Please feel free to use it.
```
// The following is based on http://curl.haxx.se/libcurl/c/getinmemory.html

// gcc -lcurl curl.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>

struct MemoryStruct {
  char *memory;
  size_t size;
};

static size_t
WriteMemoryCallback(void *contents, size_t size, size_t nmemb, void *userp)
{
  size_t realsize = size * nmemb;
  struct MemoryStruct *mem = (struct MemoryStruct *)userp;
 
  mem->memory = realloc(mem->memory, mem->size + realsize + 1);
  if (mem->memory == NULL) {
    /* out of memory! */ 
    fprintf(stderr, "WriteMemoryCallback: not enough memory (realloc returned NULL)\n");
    return 0;
  }
 
  memcpy(&(mem->memory[mem->size]), contents, realsize);
  mem->size += realsize;
  mem->memory[mem->size] = 0;

  // To verify mem->memory has the string:
  // printf("%s\n", mem->memory); 
  return realsize;
}

// timeout in seconds
long jv_curl(char *url, long timeout, void *userp) {
  struct MemoryStruct *chunk = (struct MemoryStruct *)userp;

  struct curl_slist *headers = NULL;

  CURL *curl = curl_easy_init();
  if (curl) {
    CURLcode res;
    curl_easy_setopt(curl, CURLOPT_URL, url);
    /* follow redirection */ 
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);

    curl_easy_setopt(curl, CURLOPT_TIMEOUT, timeout); 

    /* github requires User-Agent so for now ...*/
    headers = curl_slist_append(headers, "User-Agent: jq");
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteMemoryCallback);
    /* pass our 'chunk' struct to the callback function */ 
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void *)chunk);
 
    /* Perform the request, res will get the return code */ 
    res = curl_easy_perform(curl);

    /* Check for errors */ 
    if(res != CURLE_OK) {
      fprintf(stderr, "curl_easy_perform() failed: %s\n",
              curl_easy_strerror(res));
    } else {
       /* chunk->memory now points to a memory block that is chunk->size
        * bytes big and contains the remote file.
	*/
      printf("TEST: %lu bytes retrieved\n", (long)chunk->size);
      printf("TEST: %s\n", chunk->memory);

    }
    /* always cleanup */ 
    curl_easy_cleanup(curl);
  }
  return (long)chunk->size;
}

int main() {
  struct MemoryStruct chunk;
  chunk.memory = malloc(1);  /* will be grown as needed by the realloc above */ 
  chunk.size = 0;            /* no data at this point */ 
  char *url = 
    // "http://api.legiscan.com/?key=InsertKeyHere&op=getSponsor&id=1622";
       "http://apicommons.org/api-commons-manifest.json";
  printf("%lu bytes retrieved\n", jv_curl(url, 10L, &chunk));
  printf("%s\n", chunk.memory); 

  return 0;
 
}
```

**Comment by ModalUrsine** [comment]
I just discovered jq (d'oh!). How long has this been going on, i.e. when was jq first made available to the world at large? 
thanx

**Comment by nicowilliams** [comment]
@stedolan's first commit on the public repo was on July 18, 2012.

**Comment by slapresta** [comment]
Hey!

I'm very interested on this discussion. This jq+shell sample application we made for Typeform I/O would be way cleaner if it lived entirely inside jq: https://github.com/TypeformIO/JQ-FormCreation

**Comment by nicowilliams** [comment]
I think I'd rather see file/popen I/O builtins than have jq link with libcurl and OpenSSL and such.  A module system extension for C-coded modules would also work.

**Comment by dtolnay** [comment]
I agree with Nico that popen builtin or C-coded module are the best ways to implement this.

As for design, I think we should focus on a general, low-level API analogous to Go's [(*http.Client) Do](https://golang.org/pkg/net/http/#Client.Do). My weak preference is `curl/0` with an input map similar to [http.Request](https://golang.org/pkg/net/http/#Request) and an output map similar to [http.Response](https://golang.org/pkg/net/http/#Response). Then higher-level helpers can be built on top as we figure out which ones would be most useful.

    {   url: "http://api.legiscan.com/?key=InsertKeyHere&op=getSponsor&id=1622",
        method: http::GET,
        header: {
            Accept: ["application/json"]
        },
        timeout: 5 * time::second}
    | curl
    | [.statuscode, .header["Content-Type"], .body|fromjson]

**Comment by nicowilliams** [comment]
@dtolnay Welllll, if you wanted to call jq from Java, say, then you'd be unhappy with popen on systems where the kernel/libc don't support vfork() and use it in posix_spawn().  Also, a curl jq interface must not expose the mess of CLI options that is curl.  That said, we'll get a lot of mileage out of a shell-out, so we should do it.

As for a libcurl interface, if we ever do it at all then I'd like to do that via dynamically loaded jq functions.  It's reasonable to have a build dependency on Oniguruma (or descendant) for regexp as that brings in no further dependencies, but once we're talking about about curl we also get OpenSSL and/or friends and things begin to get ugly.  Also, we'd have to finish the C-coded generators business if we're going to talk to libcurl in any way other than through curl(1).

**Comment by nicowilliams** [comment]
glibc might support vfork() on some kernels nowadays since about a year ago, IIUC, but I'm probably not looking in the right place, and I'm just wasting my time.  We should hope popen() uses posix_spawn(), and that the latter uses a non-COW vfork(), and if anyone is unhappy with the lack of a true vfork() then we can tell them to complain to their OS vendor/distro.
