### ISSUE TITLE
cannot index array with string on array slice

### ISSUE THREAD

**Issue by tcoopman** [stedolan/jq#665]
Json:

```
[{"name":"JSON", "good":true}, {"name":"XML", "good":false}]
```

This works `.[].name` while this fails: `.[0:1].name` with error: `jq: error: Cannot index array with string`

Probably a beginner error, but I can't seem to find out what's wrong.

**Comment by joelpurra** [comment]
> This works .[].name while this fails: .[0:1].name with error: jq: error: Cannot index array with string

In the first case, each of the objects are returned separately, and you get two separate results. In the second case you extract a portion of the original array as a new array. Try `.[0:1][].name` to expand the resulting array to separate objects -- in this case a single object.

```bash
jq -n '[{"name":"JSON", "good":true}, {"name":"XML", "good":false}] | .[0:1][].name'
```

**Comment by tcoopman** [comment]
Thanks!
