### ISSUE TITLE
jq -e returns 0 if it doesn't find the file

### ISSUE THREAD

**Issue by rgeary1** [stedolan/jq#667]
"jq -e .foo missing.json" returns with exit code 0

Expected : returns non-zero exit code. For both -e and non "-e" mode.

**Comment by nicowilliams** [comment]
Thanks for the report!

**Comment by nicowilliams** [comment]
Question: should jq first open all files, then process them, or should it open them as it goes?

This may seem like a trivial question, but it's not.  Suppose you want jq to read from a pipe multiple times.  Each time there's EOF, open again.  Opening all files first would make this not work as expected.

**Comment by nicowilliams** [comment]
Another question is whether `-e` should matter for this.  If jq can't open a file named on the command-line, then surely that should always be an error, right?

**Comment by nicowilliams** [comment]
I'll make it open as needed.  Failure to open will always yield a non-zero exit status.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> Questions: ...

You might find comfort in `cat`:
```
$ cat not_here <(echo here)
cat: not_here: No such file or directory
here
$ echo $?
1
```
