### ISSUE TITLE
join/1 should respect empty strings in input

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#668]
The `join/1` builtin needs help:

    -def join($x): reduce .[] as $i (""; . + (if . == "" then $i else $x + $i end));
    +def join($x): reduce .[] as $i (null; (.//"") + (if . == null then $i else $x + $i end));

See also comments on #552.

**Comment by joelpurra** [comment]
@nicowilliams: `join` fails for an empty input array; see pull request #669.

**Comment by joelpurra** [comment]
This issue was fixed by #669 cca3e92. Thanks!
