### ISSUE TITLE
Feature request: parse non-JSON encoding (output from npm version)

### ISSUE THREAD

**Issue by sandinmyjoints** [stedolan/jq#674]
```
$ npm version
{ 'pn-snippet': '1.0.0',
  npm: '2.1.18',
  http_parser: '1.0',
  node: '0.10.35',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.30',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1j' }
```

This is JS, not JSON. I can easily correct the quotes on the command line, but not so easy to add quotes to the keys that are missing them. It would be great for jq to have an "object mode" ("sloppy mode"?) that would accept this, even if just to make a best-effort at spitting out real JSON to stdout, so I could then use *that* with jq. :)

**Comment by pkoppstein** [comment]
Agreed.  

In the meantime, besides prodding the good people at npm, one possibility would be to use a "javascript to json" pipeline, e.g. in ruby:
```
require 'json'
require 'execjs'

line=ARGF.read
x = ExecJS.eval( line )
case x
    when Array, Hash
      p JSON.generate(x)
    else
      p x.to_json
end

```
Example:
```
$ npm version | ruby js2json.rb | jq fromjson
{
  "http_parser": "1.0",
  "node": "0.10.26",
  "v8": "3.14.5.9",
  "ares": "1.9.0-DEV",
  "uv": "0.10.25",
  "zlib": "1.2.3",
  "modules": "11",
  "openssl": "1.0.1e",
  "npm": "1.4.3"
}
```

**Comment by dtolnay** [comment]
Or how about this workaround:

    $ jq -n "$(npm version | tr \' \")"
    {
      "npm": "1.3.10",
      "http_parser": "1.0",
      "node": "0.10.25",
      "v8": "3.14.5.9",
      "ares": "1.10.0",
      "uv": "0.10.23",
      "zlib": "1.2.8",
      "modules": "11",
      "openssl": "1.0.1f"
    }
    $ jq -nr "$(npm version | tr \' \") | .npm" 
    1.3.10
