### ISSUE TITLE
Create object from array of keys and values

### ISSUE THREAD

**Issue by amjibaly** [stedolan/jq#675]
I've been banging my head against the wall for several hours on this and just can't seem to find a way to do this. I have an array of keys and an array of values, how can I generate an object. Input:

    [["key1", "key2"], ["val1", "val2"]]

Output:

    {"key1": "val1", "key2": "val2"}

**Comment by pkoppstein** [comment]
```
[["key1", "key2"], ["val1", "val2"]] | reduce .[] as $pair ( {}; . + { ($pair[0]): $pair[1]})
```

**Comment by amjibaly** [comment]
That's brilliant, thanks so much!

**Comment by amjibaly** [comment]
Oops, I got excited too fast :) This actually does not work:

```
{
  "key1": "key2",
  "val1": "val2"
}
```

**Comment by pkoppstein** [comment]
```
[["key1", "key2"], ["val1", "val2"]]
| .[0] as $keys
| .[1] as $values
| reduce range(0; $keys|length) as $i  ( {}; . + { ($keys[$i]): $values[$i] })
```

**Comment by amjibaly** [comment]
Awesome, thanks!
