### ISSUE TITLE
sort() not the same as sort_by()

### ISSUE THREAD

**Issue by joech4n** [stedolan/jq#676]
## Summary
From http://stedolan.github.io/jq/manual/#sortsortpath_expressionsort_bypath_expression
> sort_by(foo) is an alias of sort(foo); sort_by() is deprecated and will be removed in the next major release.

but `sort_by()` and `sort()` seem to have different behaviors.

## Reproduction
     ~  cat /tmp/json
    [{"foo":4, "bar":10}, {"foo":3, "bar":100}, {"foo":2, "bar":1}]
    
    ~  cat /tmp/json |jq 'sort(.foo)'
    error: too many arguments to sort (expected 0 but got 1)
    sort(.foo)1 compile error
    
    ~  cat /tmp/json |jq 'sort_by(.foo)'
    [
      {
        "foo": 2,
        "bar": 1
      },
      {
        "foo": 3,
        "bar": 100
      },
      {
        "foo": 4,
        "bar": 10
      }
    ]
    
    ~  jq --version
    jq-1.4

Is this a bug? How else can I sort by a field if sort_by is going to be deprecated?

**Comment by pkoppstein** [comment]
A decision was made to retain `sort_by` after all.  Thus the 1.4 documentation is out-of-date with respect to the deprecation notice.  So feel free to continue using sort_by :-)

(The reason for rescinding the deprecation is that sort(_) will be used for sort(comparator).)

**Comment by joech4n** [comment]
Oh, okay cool -- understood! Thanks!

**Comment by pkoppstein** [comment]
p.s. You might be interested in the second Q&A in the "General Questions" section of the FAQ: https://github.com/stedolan/jq/wiki/FAQ#general-questions

**Comment by joech4n** [comment]
`sort_by()` is exactly what I'm looking for. Thanks @pkoppstein!
