### ISSUE TITLE
Merge arrays

### ISSUE THREAD

**Issue by ashleycoker** [stedolan/jq#680]
I have two files:

```
[
  {
    "name": "Aleshia Tomkiewicz",
    "index": 0
  },
  {
    "name": "Evan Zigomalas",
    "index": 1
  }
]
```
and 

```
[
  {
    "title": "iPad_12345",
    "deviceAuthCode": 12345
  },
  {
    "title": "iPad_12346",
    "deviceAuthCode": 12346
  }
]
```

How do I merge these to get the result:

```
[
  {
    "name": "Aleshia Tomkiewicz",
    "index": 0,
    "title": "iPad_12345",
    "deviceAuthCode": 12345
  },
  {
    "name": "Evan Zigomalas",
    "index": 1,
    "title": "iPad_12346",
    "deviceAuthCode": 12346
  }
]
```

**Comment by slapresta** [comment]
Okay, so let's say you have your people data over at `people.json` and your devices data at `devices.json`; from now on `$people` and `$devices`.

A note first: There are two possible interpretations of what you want: one in which you want the element `n` of `$people` to be mixed with the element `n` of `$devices`, and one in which you want the element of `$people` whose `index` property is `n` to be mixed with the element `n` of `$devices`. I'm assuming the former for now.

Under that assumption, what you want is to pair the elements of your two arrays with each other, then add them together. On jq, you can "zip" them with the `transpose` function by putting them in an array, and then add the elements of the resulting array with `add`:

`jq -n --argfile people people.json --argfile devices devices.json '[$people, $devices] | transpose | map(add)'`

If, instead, you want to match them by the `index` property, then what you need to do is to map each of the `$people` values to the result of adding itself to the value at `$devices` at `.index`; that is:

`jq -n --argfile people people.json --argfile devices devices.json '$people | map(. + $devices[.index])'`

Hope this helps!

**Comment by ashleycoker** [comment]
Thanks for helping....

`error: transpose is not defined`

...cant see it in docs either....

**Comment by slapresta** [comment]
Oh, right, sorry, `transpose` was defined on the master branch relatively recently. I forgot it wasn't available yet. This should work, although if your version is old maybe the `--argfile` command-line option is not available and that would really suck.

`jq -n --argfile people people.json --argfile devices devices.json '$people | to_entries | map(.value + $devices[.key])'`

**Comment by ashleycoker** [comment]
You are a life saver!
That works perfectly!
I got as far as using to_entries but then got stuck!  I will spend the time to learn from this.  Thanks a lot for your help  ;-)

**Comment by ashleycoker** [comment]
By the way this also works without `--argfile` by using `slurp`:

```
jq '.[0] as $people | .[1] as $devices | $people | to_entries | map(.value + $devices[.key])' -s json/people.json json/devices.json 
```

**Comment by pkoppstein** [comment]
To zip the two together constructively using jq 1.4:
```
jq -n --argfile people 680_1.json --argfile devices 680_2.json '
  reduce range(0; $people|length) as $i ([]; . + [ $people[$i] + $devices[$i] ])'
```
