### ISSUE TITLE
Sequence parser does not require first text to start with RS

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#687]
When using `--seq` the parser should not start parsing until the first RS octet is found.

**Comment by pkoppstein** [comment]
@nicowilliams - RS is a *s*eparator character, so I hope that the --seq option will handle it as such.

**Comment by nicowilliams** [comment]
It's not just a separator.  Check out the soon to be RFC.

**Comment by nicowilliams** [comment]
Although I'm inclined not to fix this...
