### ISSUE TITLE
Problem building jq on OSX (bison not needed)

### ISSUE THREAD

**Issue by joeschmoe40** [stedolan/jq#689]
A small problem, that I was able to workaround, but which I thought you might like to
fix.  (Yes, I know that there are pre-compiled binaries for OSX on the web page, but I
prefer to build from source)

The probem is this:
    1) You don't need bison (or flex) to build from tarball (this is both
        true/verified by me, and stated explicitly in the README file)
    2) However, the ./configure script checks for bison and wants the version to be
        at least 2.5.  Unfortunately, my system has bison version 2.3.

I was able to hack around this by figuring out that it (the configure script) was looking for the word
"warnings" in the output of "bison -y --help", so I wrote a shell script version of bison (in $PATH, ahead of the system bin directory) that outputs that word - this allowed the configure script to run to completion, after which the program was easily compiled/built.

The point here is that since bison isn't needed to build from source (tarball), the configure script shouldn't be checking for it.  I don't know if this problem was triggered specifically because I do have bison (an old version) on my system; I don't know what would happen if one didn't have bison at all.

**Comment by wtlangford** [comment]
I assume you're building the 1.4 version of jq, as since then we've upgraded to bison 3.0+.  At any rate, the way that section works is that if you don't have a version of bison > 2.5, as far as we're concerned you don't have a working bison, and the script will abort.

@nicowilliams is flex/bison really not required for building from source when we make our release source tarballs?  If that's the case then I should really go tweak that section.

**Comment by joeschmoe40** [comment]
Yes, I am building 1.4.  And, yes, you *don't* need bison to build from the tarball.  Presumably, you *do* need it to build from git, but that's not what I am talking about in this thread.

As I said, the problem is simply in configure.  Once I was able to "trick" configure, the program built just fine.

Note also: when I first found this problem, I emailed Lee Thompson (et al) and received a positive reply,including this text:

> Sounds like a bug!  You should be able to build from tarball cleanly w/o flex/bison.  Log a bug/enhancement and I=92ll try to fix.

(which is why I am posting here as well)

**Comment by joeschmoe40** [comment]
I can now confirm that if you try to build jq (from tarball) on a system that doesn't have bison at all, it configures and builds just fine.  So, it (the issue raises in this thread) is really only a problem in that oddball case where you have an old version of it (bison) on your system.

I was able to configure & build jq on a Linux system which has no bison at all installed.

**Comment by slapresta** [comment]
It's not such an "oddball case" considering that our typical user has `brew` installed, and `brew` requires the XCode dev tools, which include an old version of `bison`. Plus, when you install `bison` from `brew`, it does NOT go on the $PATH (`brew` avoids stepping over system utilities) which makes this harder to fix for Mac users.

**Comment by joeschmoe40** [comment]
> It's not such an "oddball case" considering that  …

Agreed.  I was being self-deprecatory…

(I am the OP, and I first hit this problem building on a Mac)

**Comment by slapresta** [comment]
I'm a Mac user too. This has happened to me a few times and I've always circumvented it in some way (by temporarily tweaking `$PATH` until the right version of `bison` is on top, I think) but I've always thought the issue was on *my* side.

**Comment by joelpurra** [comment]
@slapresta wrote:
> I'm a Mac user too. This has happened to me a few times and I've always circumvented it in some way (by temporarily tweaking $PATH until the right version of bison is on top, I think) but I've always thought the issue was on my side.

I've always thought the problem was Apple sticking to old versions ;) Apart from that I also manually set path to the one `brew` installed to (but didn't link).

**Comment by joeschmoe40** [comment]
Given the tone of the last few comments, I feel I need to re-iterate that this is *not* a "version of bison" problem or a PATH problem or an Apple Xcode problem or any of those "usual' sorts of problems.

It *would* be one or more of those sorts of problems *if* bison were used (i.e., necessary) in the building of "jq" from a tarball.  But it isn't.

Therefore, this is solely a "configure" script problem.  The configure script should no more be checking for the presence or version of bison on your system than it should be checking for the presence and/or version of Microsoft Word.

Now, having said that, I'm beginning to think that the underlying issue is that the packagers of "jq" use the same "configure" script for the "git" version of the program as they do for the "tarball" version, and haven't yet come to the conclusion that they shouldn't do that.  They need to have some kind of process in place that modifies the "configure" script for the tarball distribution.

**Comment by joelpurra** [comment]
@joeschmoe40 wrote:
> Now, having said that, I'm beginning to think that the underlying issue is that the packagers of "jq" use the same "configure" script for the "git" version of the program as they do for the "tarball" version, and haven't yet come to the conclusion that they shouldn't do that. They need to have some kind of process in place that modifies the "configure" script for the tarball distribution.

Sorry, meant that I'm building straight from the git repository as I'm also working on pull requests for jq. Haven't tested the tarballs nor am I a maintainer/packager.

**Comment by nicowilliams** [comment]
I'm very tempted to always fallback on pre-compiled parser and lexer.

@stedolan didn't want this, and for developers I agree that it's not what we want, except that a) not everyone who builds from git is a developer (most, I'd wager, aren't), b) making `./configure` distinguish between building from tarball vs building from git is not really desirable, IMO.

Perhaps what we should do is have a `--enable-maintainer-mode` option for `./configure`, which when used insists on using bison/flex.  But this wouldn't help the case where the user *is* a developer and they forget to enable maintainer mode.  Which brings us back to distinguishing build-from-git vs. build-from-tarball in `./configure`.

Another option would be to build two different `./configure` files, one for building from git, one for disting via tarballs.  The difference could be easy enough to edit in with `sed(1)`.

Anyways, a *low* priority for me.  If someone sends a PR, I'll review it and take it when it's ready.

**Comment by nicowilliams** [comment]
FYI, this will be fixed in 1.5.

I've added `--disable-maintainer-mode` to ./configure (`AM_MAINTAINER_MODE([enable])`) to support building from git without flex and/or bison.

I've also made Oniguruma optional (if not found then regexp support will not be included and regexp-related tests will fail).

**Comment by nicowilliams** [comment]
I'll close this when 1.5 ships, as leaving this open until then seems useful as this is an FAQ.

**Comment by joeschmoe40** [comment]
Out of curiosity, will it issue a warning/hint when the user fails config (since he won't know about the new "disable" option to the 'configure" program), suggesting that he try it again with that option?

N.B.  This is obviously a "solved problem" for me; I'm just thinking of the next guy (or gal) who runs into this...

**Comment by nicowilliams** [comment]
@joeschmoe40  Ah, yes, I should change the wording of the `AC_MSG_ERROR()` in that case, to something like:

    You need version 3.0 or greater, or use --disable-maintainer-mode.

Thanks for noting this.

**Comment by nicowilliams** [comment]
Fixed in master and 1.5rc2.

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/1386
