### ISSUE TITLE
Resources for learning 'jq'?

### ISSUE THREAD

**Issue by joeschmoe40** [stedolan/jq#690]
I've just started with jq.  I've read the man page and gotten some of the examples to work.

In fact, for what I want to do with it, the simple '.' program may be all I need, but I'd like to do a little more.  The question is: Are there further resources (help) available - that bridges the gap between the manual (and the provided tutorials in the tarball) and the level that most of the people on this board already possess?  I.e., how do you get from 1 to 2 on the skill scale?  (I've already gotten from 0 to 1).

In particular, I'd like to know how to do these two simple things:

1) Display all the keys and values.  '.[]' prints all the values, but I need the keys as well.

2) Display all the string and numeric keys and values.  Again, '.[]|strings' gets all the strings, but I want the numbers as well (but no anything not string or number).  And I want the keys, too.

Anyway, I'm sure these are trivial for you guys to answer, but I am also looking for the more general solution - which books or URLs do I read for these answers?

**Comment by slapresta** [comment]
Some common patterns are on the Wiki, on the [JQ Cookbook](https://github.com/stedolan/jq/wiki/jq%20Cookbook) section. It's quite incomplete, but better than nothing; check it out and contribute whenever you learn something new!

> 1) Display all the keys and values. '.[]' prints all the values, but I need the keys as well.

`to_entries` is probably what you need. If you find yourself converting to entries and back, on a `to_entries | something | from_entries` fashion, consider `with_entries`.

> 2) Display all the string and numeric keys and values. Again, '.[]|strings' gets all the strings, but I want the numbers as well (but no anything not string or number).

`strings` is just an alias for `select(type == "string")`, and `numbers` is defined on the same way. Therefore, `select(type == "string" or type == "number")` should work. The `scalars` builtin is pretty close to what you want, so it may be useful to you too. You can see how those builtins that are defined in jq itself are defined over at [`builtin.c`](https://github.com/stedolan/jq/blob/master/builtin.c#L1015).

>  And I want the keys, too.

As you wish: `to_entries | map(select(.value | type | . == "string" or . == "number"))`

Hope this works!

**Comment by pkoppstein** [comment]
Besides the manual, tutorial, [FAQ](/stedolan/jq/wiki/FAQ) and [Cookbook](/stedolan/jq/wiki/jq%20Cookbook), there are over 200 solved examples at Rosettacode.org: http://rosettacode.org/wiki/Category:Jq

**Comment by joeschmoe40** [comment]
Thanks everyone!

I may get to 2 (out of 10) yet.
