### ISSUE TITLE
No -j --join-output option in 64bit linux binary

### ISSUE THREAD

**Issue by jkgeyti** [stedolan/jq#691]
The `-j --join-output` flag is not available in the current jq binary for 64bit linux, despite being in the documentation (http://stedolan.github.io/jq/manual/).

**Reproducing**:

    # install newest version of jq
    $ wget http://stedolan.github.io/jq/download/linux64/jq && chmod +x jq && mv jq ~/bin/
    $ jq --version
    jq-1.4
    
    # use problematic flag
    $ cat file.json | jq -j .
    jq: Unknown option -j
    Use jq --help for help with command-line options,
    or see the jq documentation at http://stedolan.github.com/jq
 
    $ cat file.json | jq --join-output .
    jq: Unknown option --join-output
    Use jq --help for help with command-line options,
    or see the jq documentation at http://stedolan.github.com/jq

**Comment by pkoppstein** [comment]
@jkgeyti - Unfortunately the online documentation is currently a little ahead of the jq 1.4 release.  This is not altogether a bad thing, because it is (at least for many people) quite easy to upgrade to the "master" version on github.  That version is of course subject to change, but I would say that for features such as the one you mention (and for most of the documented-too-soon features), you wouldn't have to worry about stability.

**Comment by jkgeyti** [comment]
I see, that's fair, but a little unfortunate, as the jq command line tool contains no help to options, but simply refers to the manual. I guess the best solution would be to start versioning the documentation as well (`/manual/latest`, `/manual/master`, `/manual/1.4` etc).

**Comment by wtlangford** [comment]
So, versioning in the online manual is something I'm working on to coincide
with the 1.5 release. Your jq is likely referring to the main page `man
jq`, unless you simply downloaded the standalone binary.

**Comment by jkgeyti** [comment]
Yes, I have simply downloaded the jq binary. One of main reasons I love jq is being able to drop it in `~/bin` on any machine I can ssh to. I was not aware there was a man page, so that definitely solves the immediate need. Glad to hear you're planning on versioning the documentation.

Thanks for a great tool!

**Comment by wtlangford** [comment]
That ability is one of the things we consider when we attempt to add major
features to jq, so I'm glad to hear that!
