### ISSUE TITLE
sort and sort_by not working the same

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [stedolan/jq#693]
The [documentation](http://stedolan.github.io/jq/manual/#sortsortpath_expressionsort_bypath_expression) suggests that `sort(expression)` should work the same as `sort_by(expression)`, but that doesn't seem to be the case. 

Input (simplified):

    [ {"published": "2014-01-01", "name": "AAA"}, {"published": "2015-01-01", "name": "BBB"} ]

Filter:

    [ .[] | {"p": .published, "t": .name  }] | sort_by(.p) | reverse | .[0]

This yields the correct result:

    {
        "t": "BBB",
        "p": "2015-01-01"
    }

But when I execute the same filter using `sort`, I get an error:
<pre>
error: too many arguments to sort (expected 0 but got 1)
[ .[] | {"p": .published, "t": .name  }] | sort(.p) | reverse | .[0]
                                           ^^^^
1 compile error
</pre>

Is this behaviour correct or is there something wrong with my filter using `sort`? If `sort_by` is eventually removed, how would I process the given input to get the same results?

(Using jq version 1.3)

**Comment by dtolnay** [comment]
Thanks for reporting this. Quoting from #860:

> There has been some back-and-forth regarding sort/1, which unfortunately has made it somewhat difficult to match different versions of jq with different versions of the documentation.
>
> For your reference, the documentation at "master" currently documents sort/0 and sort_by/1; these have not changed and there is no plan to change their specification.

The manual no longer has the example with `sort(.foo)`, and we are no longer planning to remove `sort_by`.
