### ISSUE TITLE
Mention jq-related github repos in docs

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#698]

**Comment by nicowilliams** [comment]
Today I ran into https://github.com/jqsh.  Very nice idea!  There's also Python bindings to libjq floating about, and so on.  We should probably link to all of these from the wiki, and maybe even from the README.

**Comment by pkoppstein** [comment]
The github link is https://github.com/bmatsuo/jqsh
(The main documentation is at http://godoc.org/github.com/bmatsuo/jqsh)

@nicowilliams - How about changing the "Forums" heading on the FAQ page to "Related Resources", and including Forums and Projects as subheadings?

**Comment by nicowilliams** [comment]
On Sun, Feb 15, 2015 at 08:40:03PM -0800, pkoppstein wrote:
> The github link is https://github.com/bmatsuo/jqsh

That's a *different* jqsh.  So that's: a Rust, a Python, and a Golang
jqsh.  Cool!

> @nicowilliams - How about changing the "Forums" heading on the FAQ page to "Related Resources", and including Forums and Projects as subheadings?

Sure, make it so.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> I ran into https://github.com/jqsh
When I go there, it's just a "0 0 0 0 0 0" page; and repositories tab says: JQSH doesn’t have any public repositories yet.

I did find the repo at https://github.com/jq-shell/jqsh ...

> Sure, make it so.
OK.

**Comment by nicowilliams** [comment]
Did I write https://github.com/jqsh somewhere?  Yes, I did.  Comment corrected.  It's https://github.com/jq-shell.

**Comment by nicowilliams** [comment]
Mind you, my plan is to refactor `builtin.c` and `linker.c` so that all the builtins are in a special builtin module that gets loaded once, then I want to add I/O builtins and an `eval` builtin.  Then we can build a REPL.  See also #660.

**Comment by dtolnay** [comment]
https://github.com/stedolan/jq/wiki/FAQ#projects
