### ISSUE TITLE
QUESTION: A way to concatenate input objects into one

### ISSUE THREAD

**Issue by gustaff-weldon** [stedolan/jq#70]
Is there way to to take an array of objects and produce one object as a result?
input:

``` js
[
 { "id" : "key1", "value" : "value1" },
 { "id" : "key2", "value" : "value2" }
]
```

And I would like to transform this output into

``` js
{
   "key1": "value1",
   "key2": "value2"
}
```

I can get a set of objects by using

```
jq ".[] | { (.id): .value} "
```

but that's not what I want.

Is there a way to use `+` to merge with last result? Or just to back-reference last result somehow?
Or maybe a `{}` syntax  similar to creating an array by surrounding whole expression eg.

```
jq "{ .[] |  (.id): .value } "
```

I have also tried abusing `=` operator (`jq ".[] | (.id)= .value "`, but it did not yield usable results.
Any help would be appreciated.

**Comment by mailsanchu** [comment]
My scenario is slightly different. Keys are dynamic
[
  {
    "100": "ONE",
    "200": "TWO"
  },
  {
    "100": "1",
    "200": "2"
  }
]
My expected output is {"1":"ONE","2","TWO"}. How can I write an jq expresssion
