### ISSUE TITLE
How to truncate a value

### ISSUE THREAD

**Issue by jurgynet** [stedolan/jq#700]
I have a comment field. Sometimes the value goes long, I'd like to truncate it to 100 chars.
In shell I could cut 1-100 chars, perl use printf("-100.100s", val), in SQL use substring(), etc.
how can I accomplish trunc with jq?

**Comment by pkoppstein** [comment]
If s is a string, s[0:n] will give you up to n characters, assuming n is (or evaluates to) an integer.

E.g. `"abc"[0:1]` evaluates to "a", as does `"abc" | .[0:1]`

It it's not a string, use `tostring | .[0:n]`
