### ISSUE TITLE
Sorting version numbers with sort/sort_by

### ISSUE THREAD

**Issue by bhourigan** [stedolan/jq#708]
I'm trying to sort an array based on a version number, but this number doesn't sort numerically.

Example: https://gist.github.com/bhourigan/a7dbeabd9c662174eada

In this case 2.15 > 2.4, but sort_by(number | tonumber) will sort it as a single floating point number. Is it possible to get jq to sort this data structure?

I'm consuming AWS EC2 AMI tags, using the following query:

jq -r '[.Images[] | .Tags[] | select(.Key=="version")] | sort_by(.Value | tonumber)'

**Comment by slapresta** [comment]
Hi!

I'm pretty busy right now; I'll try to revisit this later with a thorough explanation. I think `sort_by(.Value | split(".") | map(tonumber))` will do the trick to you.

**Comment by bhourigan** [comment]
Makes perfect sense looking at split() and map() docs. thank you!

**Comment by inianv** [comment]
I've tried to explain how it worked in this StackOverflow answer for [jq find the max in quoted values](https://stackoverflow.com/a/57071319/5291015)

**Comment by SuperSandro2000** [comment]
This does sadly not work when the version numbers include ``rc``.

**Comment by sebma** [comment]
Hi, I'm finally managed so the version numbers of a PYPI package when they look like dates :
```bash
$ pythonPackage=certifi
$ curl -s https://pypi.org/pypi/$pythonPackage/json | jq -r '.releases | keys | sort_by( values | split(".") | map(tonumber) )' | tail 
  "2019.3.9",
  "2019.6.16",
  "2019.9.11",
  "2019.11.28",
  "2020.4.5",
  "2020.4.5.1",
  "2020.4.5.2",
  "2020.6.20",
  "2020.11.8"
]
```
Is there a more simple way to sort numbers naturally that with `jq` ?

**Comment by pkoppstein** [comment]
@sebma: Your jq program can be slightly improved (simplified and made more efficient) but is otherwise exactly what's needed:

    jq -r '.releases | keys_unsorted | sort_by( split(".") )' | map(tonumber) )'

**Comment by sebma** [comment]
@pkoppstein Just tried your command, it does not work, it seems there is a quote and a parenthesis pb.

**Comment by pkoppstein** [comment]
@sebma - Sorry for the typos.  Fixed. The point is to use keys_unsorted (to avoid an unnecessary sort), and to omit `values`.

**Comment by sebma** [comment]
@pkoppstein Thanks to you I've written my answer to a question in S.O. : https://stackoverflow.com/a/64866883/5649639

**Comment by pkoppstein** [comment]
@sebma - For the max, you can simply use `max_by/1`, which is simpler and much more efficient than using `sort_by/1`.

**Comment by sebma** [comment]
@pkoppstein I'm a `jq` roockie`, can you be more specific ? What is this `/1` meaning ?

**Comment by pkoppstein** [comment]
`foo/N` is shorthand for the definition of "foo" with arity N.  The output of `builtins/0` uses this notation, which is often used in languages for which the combination of a name and an arity are sufficient to determine the relevant definition (aka dispatch).

**Comment by sebma** [comment]
@pkoppstein OK I see, so applied to my example, that would give : 
```bash
$ pythonPackage=certifi
$ curl -Ls https://pypi.org/pypi/$pythonPackage/json | jq -r '.releases | keys_unsorted | max_by( split(".") | map(tonumber) )'
2020.11.8
```
Thanks again :+1:

**Comment by pklapperich** [comment]
> This does sadly not work when the version numbers include `rc`.

Maybe not perfect, but you can use `sub` to do a regex substitution. For my purposes, I'm assuming anything with letters in the suffix is <= anything without letters in the suffix, so just delete the suffix before finding the max:

```
echo '["1.2.3b1", "2.12.3b3", "2.12.3", "2.12.4rc2", "2.12.4"]' | jq -r '. | max_by( sub("[a-zA-Z]{1,}.*$";"") | split(".") | map(tonumber) )'
```

**Comment by tianon** [comment]
It's not pretty by any means, but I implemented `dpkg` version number sorting in https://github.com/tianon/debian-bin/blob/448b5784ac63e6341d5e5762004e3d9e64331cf2/jq/dpkg-version.jq

(including stealing `dpkg`'s own test cases in https://github.com/tianon/debian-bin/blob/448b5784ac63e6341d5e5762004e3d9e64331cf2/tests/jq-dpkg-version.sh)
