### ISSUE TITLE
'.' by default

### ISSUE THREAD

**Issue by dougblack** [stedolan/jq#710]
My number one use case for `jq` is piping json into it with the basic filter (`'.'`) to get formatted and colored output.

It seems this is such a prevalent action, it would make sense for this to be the default action when just running `jq` with no supplied filter.

e.g.
```
$ echo '{"foo": "bar"}' | jq
{
  "hi": "foo"
}
```

Interested in other's thoughts.

**Comment by nicowilliams** [comment]
In master you get `.` by default if there are no arguments and stdout is a
tty and stdin isn't (this last condition should get dropped).

**Comment by dougblack** [comment]
Ah! I didn't even think to check the latest version. Apologies and thanks for the snappy reply.
