### ISSUE TITLE
Variables with addition, weird behaviour

### ISSUE THREAD

**Issue by Blewin** [stedolan/jq#711]
Why does 
   100+10 as $dodo | 1
with null input equal 101? 
(here https://jqplay.org/ and also locally, in command line)

Sorry if its not a bug, i just learned jq, but this confuses me to no end, and nobody on #jq on freenode is active

**Comment by wtlangford** [comment]
So, what you've found is a "feature".

What you've wrote is equivalent to `100 + (10 as $dodo | 1)`.  It's an interesting operator precedence/parser behavior, but I wouldn't consider this is a bug.  If you're looking to get `100 + 10` bound into `$dodo`, you should do `(100+10) as $dodo | 1`.

Good catch, though!

Re: #jq, you're definitely correct.  Nobody's active there.  I'll make sure I'm actually lurking there in the future, as I definitely intend to be.

**Comment by nicowilliams** [comment]
Hmmm, I'm on ##jq.

The precedence issue is hard to do anything about at this point.  `+` and friends should have had higher precedence than `as`.

**Comment by Blewin** [comment]
thanks! sorry  I did not think of something so simple ;)
