### ISSUE TITLE
jq-mode for Emacs?

### ISSUE THREAD

**Issue by mcandre** [stedolan/jq#712]
Could someone upload a jq-mode for editing `.jq` files in Emacs?

**Comment by ljos** [comment]
I started a preliminary mode at https://github.com/ljos/jq-mode if anyone is interested.

**Comment by dtolnay** [comment]
Great, I added a link in the [wiki](https://github.com/stedolan/jq/wiki/FAQ#projects). I am closing this issue because I don't think this belongs in the main jq project.
