### ISSUE TITLE
version.h not found

### ISSUE THREAD

**Issue by cartoloupe** [stedolan/jq#721]
Observing this error after following the steps to build in README:

```bash
jq master@33a8567 $ make -j8
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       main.o
main.c:14:10: fatal error: 'version.h' file not found
#include "version.h"
         ^
1 error generated.
make[1]: *** [main.o] Error 1
make: *** [all] Error 2
```

 - [ ] I look for `version.h` but don't find it in the repo. Is `version.h` generated somehow, somewhere?

My previous steps were:
```bash
git clone https://github.com/stedolan/jq.git
cd jq
autoreconf -i  
./configure --disable-maintainer-mode
```

**Comment by nicowilliams** [comment]
This really was a build system race condition.  If you'd run "make" again it would have built.

**Comment by cbuntain** [comment]
This issue is marked as closed, but I also ran into it. To work around the problem, you can run `make version.h` to generate the appropriate file.

**Comment by flip111** [comment]
`make version.h` doesn't work
