### ISSUE TITLE
Allow json-ld key syntax (@ character in key)

### ISSUE THREAD

**Issue by jmatsushita** [stedolan/jq#722]
Hi there,

Just started using jq and I'm really impressed! I am trying to convert a json document to json-ld but I'm not sure how to create keys such as "@id" or "@context". Can this be done?

Best,

Jun

**Comment by slapresta** [comment]
I think I'm not understanding what you're trying to achieve here. A quick attempt at creating keys with at-signs seems to work fine: 

```
ᗒ jq -n '{"@id": "foo", "@context": "bar"}'
{
  "@id": "foo",
  "@context": "bar"
}
```

If you're having trouble **accessing** those keys, use the quoted brackets notation:

```
ᗒ jq -n '{"@id": "foo", "@context": "bar"} | .@id'
jq: error: syntax error, unexpected $end, expecting QQSTRING_START
```

```
ᗒ jq -n '{"@id": "foo", "@context": "bar"} | .["@id"]'
"foo"
```

**Comment by nicowilliams** [comment]
The JSON-LD spec (http://www.w3.org/TR/json-ld/#json-ld-grammar) says

    A JSON-LD document MUST be a valid JSON document as described in [RFC4627].

which means that jq should be able to handle it just fine.  The problem you're running into is the one that @slapresta supposes: that you must be trying to write jq expressions like `.something.@id`, which doesn't work because `@id` is not an identifier in _jq_.  This should work: `.something.["@id"]`.  Granted, that adds four characters you wouldn't have had to type otherwise, but hey, JSON-LD came years after jq...  :)

**Comment by slapresta** [comment]
@nicowilliams Shouldn't it be `.something["@id"]`? That is, without the dot before the brackets.

**Comment by pkoppstein** [comment]
jmatsushita wrote:
> I am trying to convert a json document ...

If you want to write a jq program to assist with the conversion, then you might find `translate_keys` as defined in the FAQ (https://github.com/stedolan/jq/wiki/FAQ#general-questions) helpful.

**Comment by jmatsushita** [comment]
Thanks everyone for the informative answers. It was as simple as not realising that I could use double-quotes around key names... FYI, this is [what I was working on.](https://gist.github.com/elf-pavlik/406ffe0300e399f72c11#comment-1408649)

Kudos for the amazing software and the supportive community!

Jun

**Comment by nicowilliams** [comment]
@jmatsushita I'm glad it worked out!  This is cool, and just the sort of task that jq is really good at.

**Comment by slapresta** [comment]
Glad to see you enjoy jq! Your script is a great use case.

Some random tips:

```
  featured: (if .map.featured then .map.featured else "false" end), 
  arranged: (if .map.arranged then .map.arranged else "false" end), 
```

You could do the same using the... erm... double slash thing:

```
  featured: .map.featured // "false", 
  arranged: .map.arranged // "false", 
```
---

```
[ .metacode_id | ( 
      if . == 1047793150 then "Project" 
      elif . == 980190962 then "Person" 
      elif . == 1047793145 then "Event" 
      else "" end), 
      "mmc:\(.)" ]
```

This might just be my irrational dislike of if statements talking, but I think this would look better as:
```
[ .metacode_id | {
      "1047793150": "Project" 
      "980190962": "Person" 
      "1047793145": "Event" 
    }[tostring] // "",
    "mmc:\(.)" ]
```

I haven't tested this, so you may be able to substitute `{}[tostring]` with `{}[.]`. Also, I get the feeling you wanted `empty` and not `""` there, but I kept it for the sake of maintaining consistency in outputs.

Overall, I loved reading through your jq script! It's very clean and well-thought, and while I don't know the ins and outs of JSON-LD nor of whatever it is converting from, it seems to make a lot of sense. You also used a lot of features I don't usually use (@format filters, string interpolation, object product) which is great.

**Comment by pkoppstein** [comment]
@jmatsushita - The following further simplifies your code.  Fortunately, it does produce the same output :-)

```
curl 'http://metamaps.cc/maps/1207/contains.json' | jq '
  . as $in
  | .synapses as $synapses
  | .map
  | { name: .name,
      description: .desc,
      image: "http://metamaps.cc\(.screenshot_url)",
      permission: "mm:\(.permission)",
      featured: (.featured // "false"),
      arranged: (.arranged // "false"),
      dateCreated: .created_at,
      dateModified: .updated_at,
      creator: { "@id": @uri "http://metamaps.cc/explore/mapper/\(.user_id)",
      "@type": "Person",
      name: .user_name,
      image: "http://metamaps.cc\(.user_image)" },
      contributor: [$in.mappers[]
                  | {"@id": @uri "http://metamaps.cc/explore/mapper/\(.id)",
                     "@type": "Person",
                     name: .name,
                     image: (if .image | startswith("/") then "http://metamaps.cc\(.image)" else .image end) }
      ],
      "@graph": [$in.topics[]
                | .id as $topicid
                | {"@id": @uri "http://metamaps.cc/topics/\(.id)",
                   "@type": [ .metacode_id
                            | ( if   . == 1047793150 then "Project"
                                elif . == 980190962  then "Person"
                                elif . == 1047793145 then "Event"
                                else ""
                                end),
                              "mmc:\(.)"],
                   name: .name }
           + ( $synapses
               | map(select(.desc == "author" and .node1_id == $topicid)) 
               | if length != 0 then { "author": [ .[] | "http://metamaps.cc/topics/\(.node2_id)" ] }
                 else {}
                 end )
           + ( $synapses
               | map(select(.desc == "attendee" and .node1_id == $topicid))
               | if length != 0 then { "attendee": [ .[] | "http://metamaps.cc/topics/\(.node2_id)" ] }
                 else {}
                 end )
           + ( $synapses
              | map(select(.desc == "event" and .node1_id == $topicid))
              | if length != 0 then { "event": [ .[] | "http://metamaps.cc/topics/\(.node2_id)" ] }
                else {}
                end ) ] }'
```

**Comment by jmatsushita** [comment]
This is great feedback! Thanks so much. Wouldn't it be great if this happened: jingweno/jqplay#8 ?
