### ISSUE TITLE
Input errors (e.g. file-system corruption) not detected, cause inf-loop

### ISSUE THREAD

**Issue by agordon** [stedolan/jq#725]
Hello,

currently, jq does not properly detect or handle input errors (e.g. e.g. file-system corruption) and is stuck in an infinite loop, (as `fgets()` in `utils.c:jq_util_input_read_more()` returns NULL but the reason for the NULL is never checked for).

Adding `ferror()` check is one way to handle it ( see https://github.com/stedolan/jq/compare/master...agordon:detect-input-errors ) - but full solution is not immediately clear to me, as the error handling code inside the jv engine is a bit tricky.

To reproduce, use this script ( https://gist.github.com/agordon/37e56543775222e3d1e0 ) to create a corrupted ext3 filesystem with a JSON file in it.

Then running `jq . /tmp/badfs/1.json >/dev/null` will run forever.

**Comment by nicowilliams** [comment]
I believe this is fixed in master.
