### ISSUE TITLE
Checksum/signature for releases

### ISSUE THREAD

**Issue by JensRantil** [stedolan/jq#726]
I've found `jq` to a be a useful utility to use when doing one-off debugging on servers. However, I am somewhat reluctant to download straight from github without at least checking the checksum of the published file (for security reasons). Even better would be if releases could be PGP signed.

See this as a feature request. Thoughts?

**Comment by nicowilliams** [comment]
Having the releases in the git repo itself has the convenience of Merkle
hash trees providing some integrity protection (those of us with clones
would notice non-fast-forward changes upstream).  But it's also annoying
when it comes time to clone the repo.  If we're going to use github
releases for releases (as I did for 1.5rc1) then we should at least include
a hash of the released files in the main repo.

If you're reluctant to download and execute the binaries (I am!) then you
should just build from git (I do).

**Comment by dtolnay** [comment]
@nicowilliams if you still have the 1.5rc2 binaries locally, please confirm my checksums using those. Otherwise please confirm using this script:

```sh
#!/bin/sh

check_hash() {
    expected_hash="$1  -"
    github_hash=`curl -L -s -S \
        https://github.com/stedolan/jq/releases/download/$2 | sha1sum`
    if [ "$expected_hash" = "$github_hash" ]
    then
        echo pass $2
    else
        echo FAIL $2
    fi
}

check_hash 4975875ed6e758ef5f14ddb72026d430ff6b7b65 jq-1.5rc2/jq-linux-x86
check_hash ec498ea174ab4e696d02016e2ad47fbdec2b3aa3 jq-1.5rc2/jq-linux-x86_64
check_hash b5ac856d9f900bd65a56862685851bf86b2f4a19 jq-1.5rc2/jq-osx-x86_64
check_hash 8155d59b1e078335fbff9087c41a5ee20f72194b jq-1.5rc2/jq-win32.exe
check_hash 029bac3d1d95741dc95eee11b9b81a3c8ce12666 jq-1.5rc2/jq-win64.exe

check_hash d207828ea824eb4619a3ec4e10eced5a756052b0 jq-1.5rc1/jq-linux-x86_64-static
check_hash 151d909b5414a9d6c005dd09e653cc274e8ecdf5 jq-1.5rc1/jq-win32.exe
check_hash 061d6db97bf71378440a3d740f86b93b3d995467 jq-1.5rc1/jq-win64.exe
```

**Comment by nicowilliams** [comment]
@dtolnay Yes, the script looks good and so does its output.

**Comment by dtolnay** [comment]
Great. I am closing this but I filed #889 to look into a PGP signature for 1.6 binaries, since I most likely will not get to it for 1.5.

**Comment by dtolnay** [comment]
@JensRantil, just to follow up in case you were not watching #889, future releases will be signed by the [jq release signing key](http://pgp.mit.edu/pks/lookup?op=vindex&search=0xAF19040C71523402) and the signatures will be put in [/sig](https://github.com/stedolan/jq/tree/master/sig). I have retroactively signed the old releases after checking the checksums.

**Comment by JensRantil** [comment]
@dtolnay Awesome! Thanks!
