### ISSUE TITLE
filter 'flatten' doesn't work?

### ISSUE THREAD

**Issue by xied75** [stedolan/jq#728]
It doesn't work on my ubuntu, as well on the online playground.

```
error: flatten is not defined
flatten1 compile error
```

**Comment by slapresta** [comment]
Can you paste here the output of `jq --version`?

**Comment by xied75** [comment]
Sure.

```
dong@dong-Ubuntu:~$ jq --version
jq-1.4
```

The online playground does same.

**Comment by slapresta** [comment]
Right. I think `flatten` was added **after** the release of 1.4. If you've read about it then there may be something wrong with the documentation; thanks for the report!

For what it's worth, `flatten` is completely defined in jq itself. You can add this line at the beginning of your jq script to be able to use `flatten`.

```
def flatten: reduce .[] as $i ([]; if $i | type == "array" then . + ($i | flatten) else . + [$i] end);
```

Alternatively, you can compile jq from master.

**Comment by dtolnay** [comment]
#866 will make it easier to find documentation for released versions instead of looking at documentation for the upcoming release.

**Comment by aep-sunlife** [comment]
Would be helpful to annotate each function with the earliest version that implements it.

**Comment by wader** [comment]
> Would be helpful to annotate each function with the earliest version that implements it.

It has been discussed in https://github.com/jqlang/jq/pull/3189 and hopefully i can happen once that is merged.
