### ISSUE TITLE
Escaping characters with --raw-output

### ISSUE THREAD

**Issue by agordon** [stedolan/jq#729]
Hello,

I'm wondering if there's a way to escape printed strings (such as '\t' and '\n') when using `--raw-output`,
and if not, would such an option be useful?

A example to illustrate the issue:
```
# When not using raw-output, strings are escaped:
$ echo '{"name":"John\tDoe","id":"hello\nworld"}' | jq '[ .name, .id ]'
[
  "John\tDoe",
  "hello\nworld"
]
$ echo '{"name":"John\tDoe","id":"hello\nworld"}' | jq '.id'
"hello\nworld"
$ echo '{"name":"John\tDoe","id":"hello\nworld"}' | jq '.name'
"John\tDoe"

# When using raw-output (and the output is one string), strings are not escaped:
$ echo '{"name":"John\tDoe","id":"hello\nworld"}' | jq -r '.name' 
John     Doe
$ echo '{"name":"John\tDoe","id":"hello\nworld"}' | jq -r '.id'
hello
world
```

This can be unexpected, as the manual tells that `--raw-output` can be used when one wants to produce non JSON, especially tabular output:
```
$ echo '{"name":"John\tDoe","id":"hello\nworld"}' | jq -r '[ .name, .id ] | join("\t") '
John     Doe       hello
world
```

Is there a way to ensure the strings are escaped even with raw-output?
or another way to safely output strings in non-json format?

Ideally the output would've been:
```
John\tDoe         hello\nworld
```

Thanks,
 gordon

**Comment by pkoppstein** [comment]
If you have access to a version of jq with gsub, you could use that, as illustrated by the following:
```
$ jq -r -n '"a\tb\nc" | gsub( "\t"; "\\t") | gsub( "\n"; "\\n")'
a\tb\nc
```

**Comment by joelpurra** [comment]
This works for jq 1.4:

```jq
def replace(a; b):
	split(a)
	| join(b);
```

**Comment by slapresta** [comment]
The `@tsv` format filter was recently added on master. Sounds like what you want.

**Comment by nicowilliams** [comment]
Yes, do try `@tsv`.
