### ISSUE TITLE
How to echo special char like @ ?

### ISSUE THREAD

**Issue by qingshanli1988** [stedolan/jq#730]
[root@44620 ~]# tail -2 /wls/logs/oslog//z2bs4020//var/cron/log-2015-03 |jq .              
{
  "message": "<  root 21609 c Tue Mar 17 12:00:00 2015",
  "@version": "1",
  "@timestamp": "2015-03-17T04:00:01.119Z",
  "host_name": "z2bs4020",
  "type": "HOST",
  "host": "z2bs4020",
  "path": "/var/cron/log"
}
{
  "message": "<  root 21610 c Tue Mar 17 12:00:00 2015",
  "@version": "1",
  "@timestamp": "2015-03-17T04:00:01.119Z",
  "host_name": "z2bs4020",
  "type": "HOST",
  "host": "z2bs4020",
  "path": "/var/cron/log"
}
[root@044620 ~]# tail -2 /wls/logs/oslog//z2bs4020//var/cron/log-2015-03 |jq .["\@timestamp"]
error: syntax error, unexpected INVALID_CHARACTER
.[\@timestamp]  1 compile error
[root@44620 ~]# tail -2 /wls/logs/oslog//z2bs4020//var/cron/log-2015-03 |jq .["@timestamp"]
jq: error: timestamp is not a valid format
jq: error: timestamp is not a valid format
[root@44620 ~]#

**Comment by pkoppstein** [comment]
Using jq 1.4 and assuming the JSON is in 730.json:
```
 $ jq '."@timestamp"' 730.json
"2015-03-17T04:00:01.119Z"
"2015-03-17T04:00:01.119Z"
$ jq '.["@timestamp"]' 730.json
"2015-03-17T04:00:01.119Z"
"2015-03-17T04:00:01.119Z"
```
