### ISSUE TITLE
How to deal with JSON bigger than ARG_MAX?

### ISSUE THREAD

**Issue by FindNemo** [stedolan/jq#732]
Command line parameter has ARG_MAX size limit. And the value of ARG_MAX is different between different OS.

**Comment by slapresta** [comment]
I'm not sure if I'm understanding your problem correctly, but you should be able to put the jq script you're running on a file and refer to that file using the `-f` flag. If you're passing too many JSON input files, you can just cat them together and pass them as one.

**Comment by nicowilliams** [comment]
Put it in a file and use `--argfile`.

**Comment by FindNemo** [comment]
thank you
