### ISSUE TITLE
SIGFPE on module by 0

### ISSUE THREAD

**Issue by slapresta** [stedolan/jq#735]
Accidentally found this.

Steps to reproduce:
```
jq -n '3 % 0'
```

Expected:
??? (maybe error?)

Actual:
```
fish: Job 1, “jq -n '3 % 0'” terminated by signal SIGFPE (Floating point exception)
```

**Comment by wtlangford** [comment]
Thanks!  I'll take a look at it tonight.

**Comment by wtlangford** [comment]
Yeah, it looks like we just weren't checking for 0 there, since division by 0 just returns +Inf or -Inf.  I've updated it now to throw an error when trying to mod by 0.
