### ISSUE TITLE
change in behavior of --argfile array between 1.4 and current master

### ISSUE THREAD

**Issue by sparr** [stedolan/jq#736]
git master:

    $ jq 'map((.name))' test.json
    [
      "a",
      "b"
    ]
    $ jq --argfile x test.json '$x|map((.name))' test.json
    jq: error: Cannot index array with string "name"
    $ jq --argfile x test.json '$x[]|map((.name))' test.json
    [
      "a",
      "b"
    ]

jq-1.4:

    $ jq 'map((.name))' test.json
    [
      "a",
      "b"
    ]
    $ jq --argfile x test.json '$x|map((.name))' test.json
    [
      "a",
      "b"
    ]
    $ jq --argfile x test.json '$x[]|map((.name))' test.json
    [
      []
    ]
    [
      []
    ]

test.json contents:

    [
      {
        "name" : "a"
      },{
        "name" : "b"
      }
    ]

**Comment by nicowilliams** [comment]
This will feature prominently in the 1.5 release docs, but `--argfile` as it appears in 1.4 has bad semantics: it slurps the whole file like `jq -s .` would, and if the result is an array of one value, it binds the varname to the first value in that array.  Instead it should either read only the first text in the input file, or always slurp all of them.

**Comment by sparr** [comment]
How can I adapt my code to work in 1.5? Preferably in both.

**Comment by nicowilliams** [comment]
Can you try the change I just pushed?  It loads only the first text from the argfile.

**Comment by sparr** [comment]
Your patch fixes this test case; produces a new/different failure mode in my bigger real use case. I'll make a new test case when I have time.

    $ jq --argfile mat data/json/materials.json -f armor_stats.jq data/json/items/armor.json
    jq: error: Cannot iterate over null

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> Can you try the change I just pushed? It loads only the first text from the argfile.

It seems to behave according to the new spec, but the "Bad JSON" part of the "file not found" error message is a bit weird:
```
jq: Bad JSON in --argfile a nonexistent.json: Could not open nonexistent.json: No such file or directory
```

**Comment by nicowilliams** [comment]
@sparr Make sure that your argfiles have only one JSON text and it should work.

**Comment by nicowilliams** [comment]
@pkoppstein  Heh, yeah, that is odd-looking.

**Comment by sparr** [comment]
@nicowilliams this is the argfile in question https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/materials.json
and this the input https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/armor.json
and the jq script is here: https://gist.github.com/sparr/1866598487991848a3aa

**Comment by pkoppstein** [comment]
@sparr - One problem is that not all your objects have a .covers key, so `.covers | join(", ")` will fail.

Since you have access to jq on master, try this:
```
jq 'map(.covers | debug | join(",") )' armor.json 
```
The good news is that:
```
$ jq '[ map(select(.covers == null )) ] | length' armor.json
1
```

**Comment by sparr** [comment]
@pkoppstein you've got an extraneous [] in that good news, there are actually 46 entries with no .covers.

I'm ok with the join failing, since the failure goes to stderr, for now.
