### ISSUE TITLE
Setup CI build?

### ISSUE THREAD

**Issue by xied75** [stedolan/jq#737]
Dear all,

Not exactly sure if this has been raised before, any chance we could setup CI e.g. Travis to do the testing? I just cloned the code and it failed tests.

Best,

Dong

**Comment by wtlangford** [comment]
I'm definitely all for having some kind of CI prior to merging pull requests. @nicowilliams @pkoppstein, thoughts?

That being said, I just pulled master (7d6d4066dd2fdedae90ce3498b8f5a4702dffaa7) and ran the tests and it passed for me.  That commit's also older than your comment, so I'm not sure what you were encountering...

**Comment by nicowilliams** [comment]
I want to setup Travis, but evidently I need to create a new github account just for that.  Travis wants too much permission, and I can't accept that.

Tests pass for me.  If tests fail anywhere, we need details.

**Comment by pkoppstein** [comment]
@xied75 wrote:
> I just cloned the code and it failed tests.

```
$ ./jq --version
jq-1.5rc1-48-g7d6d406

$ tests/run tests/all.test
[42,[42]]
{"foo":420,"bar":240}
jq: error: syntax error, unexpected INVALID_CHARACTER, expecting $end (Unix shell quoting issues?)
}
jq: 1 compile error
Testing 'true' at line number 8
...
247 of 248 tests passed (0 malformed)
$

$ /usr/bin/sw_vers
ProductName:	Mac OS X
ProductVersion:	10.7.5
BuildVersion:	11G63b
```

Am I doing something wrong?

**Comment by nicowilliams** [comment]
Can you post the test-suite.log?

**Comment by wtlangford** [comment]
Uh, I always run that with `make check`, but that shouldn't matter. Also, the version on the jq I built from source is `jq-1.4-268-g7d6d406`, which is weird.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> Can you post the test-suite.log?

```
$ make check
make  check-am
make  check-TESTS
FAIL: tests/all.test
============================================================================
Testsuite summary for jq 1.5rc1-48-g7d6d406
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to mu@netsoc.tcd.ie
============================================================================
make[3]: *** [test-suite.log] Error 1
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check] Error 2
```

The interesting stuff in the log is basically what I sent.  It begins and ends as follows:

```
=============================================
   jq 1.5rc1-48-g7d6d406: ./test-suite.log
=============================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/all
===============

jq: error: syntax error, unexpected INVALID_CHARACTER, expecting $end (Unix shell quoting issues?)
}
jq: 1 compile error
[42,[42]]
{"foo":420,"bar":240}
Testing 'true' at line number 8
...
247 of 248 tests passed (0 malformed)
FAIL tests/all.test (exit status: 1)
```

**Comment by nicowilliams** [comment]
That's the summary.  jq --run-tests always outputs that the stuff you quoted.  Look for lines starting with `**`.

**Comment by pkoppstein** [comment]
@nicowilliams - If the "syntax error" and "compile error" errors shown above are expected, then maybe it would be less confusing if that could be mentioned in the output?

Anyway, regarding the log, I believe these are the lines you're interested in:
```
*** Expected [[2015,2,5,23,51,47,4,63],1425599507], but got [[2015,2,5,23,51,47,0,0],1425599507] for test at line number 1133: [strptime("%Y-%m-%dT%H:%M:%SZ")|(.,mktime)]
Testing 'strftime("%Y-%m-%dT%H:%M:%SZ")' at line number 1135
```

**Comment by nicowilliams** [comment]
Thanks.  That's your libc's `strptime()` not outputting day of the week and day of the year in its broken-down time representation.  I gather this is on OS X?

What to do?  Options:

 - tweak the test to set those two to zero so that it passes
 - tweak `strptime` to not output those two (and then tweak the test to match)
 - write more code to compute the missing values

**Comment by nicowilliams** [comment]
There may be a workaround:

http://stackoverflow.com/questions/22600198/strptime-to-strftime-for-day-of-the-week

**Comment by nicowilliams** [comment]
@pkoppstein Can you try the fix for this in the `mktime` branch of my clone of jq?

**Comment by pkoppstein** [comment]
@nicowilliams -- Excellent!
```
~/github/nicowilliams/jq$ /usr/bin/sw_vers
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F1066

~/github/nicowilliams/jq$ ./jq --version
jq-1.2-602-gddad961

~/github/nicowilliams/jq$ make check
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: tests/all.test
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
============================================================================
Testsuite summary for jq 1.2-591-gccfba00
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by nicowilliams** [comment]
Thanks for checking @pkoppstein!

**Comment by dtolnay** [comment]
If I am interpreting the comments correctly, the strptime issue has been resolved.

As for CI, the Travis build is configured correctly as of #833. I have been watching the builds of my fork. If we convince @stedolan to sign up at https://travis-ci.org and add this repo, we can put a badge like ![travis](https://api.travis-ci.org/dtolnay/jq.svg) in the readme to force us to keep an eye on it.

**Comment by dtolnay** [comment]
Moved to #869 so we track this request separately from the build failure.
