### ISSUE TITLE
Key names can not include colons :

### ISSUE THREAD

**Issue by TomOnTime** [stedolan/jq#741]
jq can't search keynames that include colons.  This is a big problem for hiera/puppet users since they often have keynames in the form of function::parameter

To reproduce:

```
$ cat x.json 
{
  "first": "value1",
  "key::name": "value2"
}
$ jq <x.json '.first'
"value1"
$ jq <x.json '.key::name'
error: syntax error, unexpected ':', expecting $end
.key::name
    ^
1 compile error
$ 
```

**Comment by slapresta** [comment]
The `.foo.bar` syntax only accepts a limited set of characters. Try `.["foo"]["bar"]`, or, in recent versions, `."foo"."bar"`

**Comment by TomOnTime** [comment]
Ok. This works. Can you update the docs?  I think a lot of Puppet users would appreciate it because they'll be looking for that too.

```
jq <x.json '.["key::name"]'
```
(this works in jq version 1.3)

**Comment by slapresta** [comment]
It is mentioned pretty thoroughly on [the manual](http://stedolan.github.io/jq/manual/).

> ## `.foo`, `.foo.bar`
> 
> If the key contains special characters, you need to surround it with double quotes like this: `."foo$"`.

> ## `.[<string>]`, `.[2]`, `.[10:15]`
>
> You can also look up fields of an object using syntax like `.["foo"]` (`.foo` above is a shorthand version of this).

Contributions and improvements to the docs are welcome and heavily encouraged, but I'm not sure about what to change.

**Comment by nicowilliams** [comment]
Perhaps the tutorial and manual should both list the `.["key"]` or `."key"`
syntax first, *then* point out that `.key` is a handy shorter form, rather
than the inverse.

**Comment by slapresta** [comment]
That sounds like a good idea.

**Comment by TomOnTime** [comment]
TBH, when I read that I didn't see the benefit of .["key"]. It just seemed like more typing for no purpose.  Having an explicit example of a key that wouldn't work in the short form would make it more clear.

**Comment by TomOnTime** [comment]
See https://github.com/stedolan/jq/pull/745
