### ISSUE TITLE
Need a way to treat multiple input files as an array

### ISSUE THREAD

**Issue by sparr** [stedolan/jq#744]
I'd like to be able to do `jq 'whatever' *.json` and have it work as if I had input a single array where each item in the array was the contents of one of the json files. Right now it seems like there's no way to perform operations over the aggregate contents of the files, with each of them instead being filtered separately.

**Comment by wtlangford** [comment]
Well, you can do `jq --slurp 'whatever' *.json`, which will provide an
array of all of the items in all of the files.  The way we currently handle
multiple files doesn't lend itself to per-file processing, though (an array
for each file).

As it is right now, we handle multiple files by assuming that they are a
continuation of the previous data.

That being said, I can definitely see use-cases for this behavior.
 @nicowilliams, do you see anything that I'm missing?

**Comment by xbao** [comment]
A little shell hackery until then:

```
jq '.' <<< $(echo -n '['; for file in *.json; do cat "$file"; echo -n ","; done | sed '$ d'; echo -n ']') > combinedarray.json
```

**Comment by nicowilliams** [comment]
```
$ jq --slurp-file whatever "$(cat *.json)" ...
```

**Comment by nicowilliams** [comment]
```
$ cat *.json | jq -s ...
```

**Comment by ml10** [comment]
Just noting that `cat`ting all of the files together does not work when also using `input_filename` or `input_line_number` as it will change the meaning of both of those.

**Comment by nhtzr** [comment]
For that, usually I end up piping two jq invocations: 
```
jq -n 'inputs | {"object": . , "filename": input_filename, "lineNumber": input_line_number}' *.json |
 jq -ns 'inputs'
```

The first invocation generates the values, and the second invocation packages them in an array.
Although I'm not sure if that's the most proper approach.

**Comment by ml10** [comment]
Yeah, that's almost exactly where I ended up after a bit more fiddling.
