### ISSUE TITLE
Link to download compiled version is broken

### ISSUE THREAD

**Issue by pippobaudos** [stedolan/jq#746]
Tried the link to download js: http://stedolan.github.io/jq/download/linux64/jq 
But it looks to be broken.

**Comment by dtolnay** [comment]
Thanks for reporting this. I don't know what happened because that file has not changed since June 12, 2014 ([see here](https://github.com/stedolan/jq/commits/gh-pages/download/linux64/jq)). The link works for me. Closing for now, but please comment if it still does not work for you.
