### ISSUE TITLE
raw / -r output of null value - shouldn't return anything

### ISSUE THREAD

**Issue by nneul** [stedolan/jq#747]
localhost# echo '{"TZ":null}' | jq '.["TZ"]'
null
localhost# echo '{"TZ":null}' | jq -r '.["TZ"]'
null

Seems like the raw version of that should return an empty value, not the text null. The non-raw output makes sense since it's javascript/json syntax.

**Comment by slapresta** [comment]
Not sure if it is a bug or not, but, as a workaround, you can add `// empty` at the end of your script, like this:

`echo '{"TZ":null}' | jq -r '.["TZ"] // empty'`

This will also turn other falsey values, like "false", into an empty value, which may not be what you want.

**Comment by nneul** [comment]
Thank you, that is a useful workaround in the mean time!

**Comment by nneul** [comment]
That does raise the question of what the appropriate return would be for 'true' and 'false' as well in the raw output. I can see arguments in favor of multiple format possibilities. Maybe something like '//empty' but to select a desired behavior.

**Comment by nicowilliams** [comment]
I think it's too late for this change.  Sorry.  (But convince me otherwise.  Maybe we could have two `-r` options do this?)

**Comment by dtolnay** [comment]
Ditto Nico. `// empty` is a reasonable workaround and is explicit about what you want.
