### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by Svampen** [stedolan/jq#749]
Hi

We are using jq to validate json strings (awesome tool btw) but on some machine we use we get the following error by just running jq:
./jq
Floating point exception

That machine is running a pretty old linux kernel, could that be the issue?
Linux NAME 2.6.16.60-0.21-xenpae #1 SMP Tue May 6 12:41:02 UTC 2008 i686 i686 i386 GNU/Linux

Any idea if this is solvable by compiling a jq on that machine or is it a problem in jq it self?

Thanks for any input you can give me.

/Stefan

**Comment by wtlangford** [comment]
I can't imagine what would be causing that.  You can definitely try to compile it (and I would! there's a lot of nice features in master that haven't made it to an official version yet).
How did you install jq on that machine?  Through your package manager or via the downloads on http://stedolan.github.io/jq ?

**Comment by Svampen** [comment]
I will try compiling it from source tomorrow and see if that helps.

I downloaded the 32bit version of http://stedolan.github.io/jq so we use the same binary on all the machines.

**Comment by Svampen** [comment]
After building jq from source (using the tarball) on a linux machine with the same kernel as the machine that had Floating point exception, it now works fine.

This issue can be closed
Thanks for the support

/Stefan
