### ISSUE TITLE
Calling jq_start repeatedly on multiple strings

### ISSUE THREAD

**Issue by saptarshiguha** [stedolan/jq#756]
Hello
I couldn't find a mailing list, so asking here.
b) with the C API i have initiated jq, and called jq_compile_args for the filter
c) I am using the C API that takes a C string (the input JSON), calls jv_parse(on this string), jq_start, checks the kind and calls jv_dump_string.
I then call (c) again for a new string but my program crashes with

execute.c:143: stack_push: Assertion `jv_is_valid(val)' failed.
Aborted (core dumped)

Is this expected? Am i supposed to call (b) and (c) together for each string? Wouldn't calling (b) be redundant since the filter is same for all? Or do i need to implement a jq_input_cb?
thanks!

**Comment by nicowilliams** [comment]
First you call jq_start() with the input value, then you call jq_next() in
a loop to extract the jq program's outputs.  When you are ready to provide
a new input value to the jq program, you call jq_reset().  Lather, rinse,
repeat, and when you're all done you teardown the jq_state.

**Comment by saptarshiguha** [comment]
Yes, did almost all of that except for jq_reset. Searching the repo, jq_reset is not in jq.h or jv.h, in fact it is only in 

https://github.com/stedolan/jq/blob/24005287f4ed1ffe486060b3156d5dfe6a3847da/execute.c#L261

Shouldn't it be in the header files (it would be nice, then  I can use FFI to import it)

**Comment by nicowilliams** [comment]
@saptarshiguha Er, sorry, I was wrong.  There's no need to call jq_reset().

Can you post a gist with your C code?

**Comment by nicowilliams** [comment]
(And maybe we should add a demo C program that lacks all the complexity of `main.c`.)
