### ISSUE TITLE
--slurp --raw-input is broken

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#761]
The jq manual is quite clear that it should be possible to read a text file using --slurp and -R together:
```
.... Instead, each line of text is passed to the filter as a string. 
If combined with --slurp, then the entire input is passed to the filter
as a single long string.
```
This was working beautifully in jq 1.4 but at some point, that ceased to be the case.  Using recent versions of jq, the combination of -s and -R seems to yield the behavior of -R alone.  

At various levels, this change seems to me to be a bug in itself, but even if it is not, it would still be desirable for jq 1.5 to be able to read a text file as a "single long string" as before.

**Comment by nicowilliams** [comment]
Thanks for the report.  Will fix soon.

**Comment by pkoppstein** [comment]
@nicowilliams - Thanks for fixing this.  There does, however, seem to be a problem, as shown in the transcript below.  It concerns a file with a large number of lines, each of which consists of a string of "a"s.  I've only noticed the problem for large files, which makes it very weird. 
```
$ ~/github/jq/jq --version
jq-1.5rc1-68-g25bf315

$ /usr/local/bin/jq --version
jq-1.4

$ wc polya.txt
   10000   10000 100010000 polya.txt

$ grep -v '^a*$' polya.txt

$ /usr/local/bin/jq -R -s length polya.txt
100010000

$ ~/github/jq/jq -R -s length polya.txt
100030000
```
