### ISSUE TITLE
Colored pagination

### ISSUE THREAD

**Issue by neowulf33** [stedolan/jq#764]
Objective: Ability to paginate colored output.

I didn't find any documentation regarding a pagination switch within the jq tool. The only quick recourse for a user is to pipe the jq output to a `less` like utility. However, this does not yield the colored output.

If the colors were rendered as raw control characters - piping the colored output to `less -R` would make this feature a possibility.

**Comment by wtlangford** [comment]
Do jq -C **jq args** | less -R

**Comment by neowulf33** [comment]
Cool that works! Thanks.

**Comment by wfxr** [comment]
Thanks for @wtlangford 's solution. It works as expected.

But I found write `-C ... | less -R` again and again is very boring. Especially when I need modify the arguments frequently.

Put the following function at `bashrc` or `zshrc` will release your fingers:

```bash
jqjq() {
    # -F tell less exit if output content can be displayed on one screen
    jq -C "$@" | less -FR
}
```

Then you use `jqjq` the same way as `jq`. When the content is too long, less will automatically take over it.

```bash
jqjq args
```

If you don't like to use another command, add one more line:

```bash
alias jq='jqjq'
```

Now everything doesn't change. Pager will be used when necessory.

```bash
jq args
```
