### ISSUE TITLE
Allow tonumber to work on booleans

### ISSUE THREAD

**Issue by jkleint** [stedolan/jq#768]
It would be nice if you could pass a boolean to `tonumber`:
```
$ echo false | jq tonumber
jq: error: boolean cannot be parsed as a number
```

**Comment by nicowilliams** [comment]
What would be the expected result?  Zero for `false` and one for `true`?  I'm inclined to say "no", since you can redefine `tonumber` is your own jq programs.

**Comment by pkoppstein** [comment]
@jkleint - I would also argue against such a change. The strongest argument against the proposal is undoubtedly that it would potentially break existing programs, but it's not such a great idea anyway (e.g. overloading makes debugging harder). Also, it's easy enough to define boolean2integer if that's what one needs, or as @nicowilliams pointed out, even tonumber can be locally redefined, though maybe that should be regarded with caution.
