### ISSUE TITLE
line by line output for shell scripting

### ISSUE THREAD

**Issue by eriksank** [stedolan/jq#774]
The output is absolutely correct but at the same time totally suitable for further commandline processing:

$ bitcoin-cli -regtest getblock 044a0be4a...c1b6df6603f4dedcbfc  | jq -r '.tx'
[
  "7da8c88128a700c6a6498db77264b74f42b7f913c43ba75173b7a7076d084e55",
  "145cbb3d8aa089bf02bd08b03d7895a5cfff21730dabaf435c62ccd176406509"
]

I would need:

$ bitcoin-cli -regtest getblock 044a0be4a...c1b6df6603f4dedcbfc | jq -r '.tx'
7da8c88128a700c6a6498db77264b74f42b7f913c43ba75173b7a7076d084e55
145cbb3d8aa089bf02bd08b03d7895a5cfff21730dabaf435c62ccd176406509

The next tool in the pipeline does not work with json. It needs the output line by line. There does not seem to be a way to achieve that kind of output with jq?

**Comment by slapresta** [comment]
`jq -r '.tx[]'`
