### ISSUE TITLE
Redirect usage questions to stackoverflow

### ISSUE THREAD

**Issue by joelpurra** [stedolan/jq#778]
In order to reduce the amount of jq usage questions here on the github issue tracker, how about encouraging users to ask this type of questions on [stackoverflow.com](https://stackoverflow.com/) instead? It would reduce the number of questions which could be answered with a mere RTFM -- altough the jq community is nice enough to take their time and help out in all cases. I hope this would reduce the number of issues core devs have to read, consider and often respond to -- especially when there are several followup questions and external tools are involved.  Other software projects already use this approach.

Stackoverflow has a [jq tag](https://stackoverflow.com/tags/jq/info) and [over 100 questions have been tagged](https://stackoverflow.com/questions/tagged/jq). This would also encourage others, outside of the core devs, to answer questions in exchange for internet points. I also hope stackoverflow users unfamiliar with jq become interested in using it themselves when they read these usage questions.

Links from the [jq webpage](https://stedolan.github.io/jq/) and [README.md](https://github.com/stedolan/jq#readme) would be a good start. 

Issues which can and should be redirected to stackoverflow can be answered with a copy-paste answer, linking to stackoverflow. These issues can also be [labeled as `usage`](https://github.com/stedolan/jq/labels) (or another name) here on github.

```text
Thank you for using `jq`!

Usage questions are best asked on [stackoverflow.com](https://stackoverflow.com/) -- see [questions already tagged with the jq tag](https://stackoverflow.com/questions/tagged/jq].

You can also test your queries on [jqplay.org](https://jqplay.org/).
```

Bugs in jq are still a developer issue, it's just that the sheer number of mere usage questions (trivial or not) dilute the github issues and move dev's focus away from working on the jq code base.

What do you think?

**Comment by nicowilliams** [comment]
Yes!  I will do this later today.  We've probably getting a lot of queries
due to jq having been on the Hacker News front page for a whole day
recently.

**Comment by nicowilliams** [comment]
Done.  Updated gh-pages and the README.

**Comment by joelpurra** [comment]
@nicowilliams: great! Really hope this reduces the steady stream of random jq usage "issues"/questions.

**Comment by joelpurra** [comment]
Just noticed you can add the jq tag to new stackoverflow questions right in the link to the ask new question form. While it's not necessary to add it to the current list of support links in the documentation, it could be used at some point.
https://stackoverflow.com/questions/ask?tags=jq

By the way, there are now 140 questions tagged with jq -- looks like about 40% increase in less than two months! Many thanks to Jeff Mercado, who seems to be the top answerer =)
https://stackoverflow.com/questions/tagged/jq
https://stackoverflow.com/tags/jq/topusers
https://stackoverflow.com/users/390278/jeff-mercado
