### ISSUE TITLE
How to dump paths to leafs and the leaf values?

### ISSUE THREAD

**Issue by tischwa** [stedolan/jq#78]
Hi,

I'm trying to achieve the following: Dump paths to leafs and the leaf values.

Example:

$ echo '{"a":{"b":1,"c":2},"d":["x",1]}' | jq '<what to write here?>'
a.b = 1
a.c = 2
d.0 = x
d.1 = 1

I think using the recurse-function it should be possible somehow, any ideas?

It is a bit similar to what

https://github.com/wuyongzheng/json-liner

does, but the output format is more or less fixed there. And using jq I could apply all of jq's filtering possibilities.

Regards,
Tilo

**Comment by lucaswerkmeister** [comment]
You can also use `paths(scalars)` instead of `path(leaves)` to get a version without custom functions:
```jq
paths(scalars) as $p | [$p, getpath($p)]
```
As far as I can tell, it’s equivalent to @stedolan’s suggestion.

**Comment by tlwhitec** [comment]
Hi, maybe it's silly to ask on such an old issue, but is there a reason `getpath` is not documented?

**Comment by pkoppstein** [comment]
`getpath` is documented in the manual at 
https://stedolan.github.io/jq/manual/

it was not documented in earlier versions, perhaps because it was originally viewed as being subject to change.

**Comment by talwrii** [comment]
It's probably worth noting that there is a high-star command-line tool [gron](https://github.com/tomnomnom/gron) to do this. Interestingly gron can reverse the transformation from paths -> leaves back into JSON which has some interesting possibilities. I also wrote the tool [json-leaves](https://github.com/talwrii/json-leaves) which does the same thing - before someone pointed out that gron existed. I might recommend gron unless you plan to edit the tool and know python; Gron is written in Go.
