### ISSUE TITLE
How to ignore leading parenthesis in JSON?

### ISSUE THREAD

**Issue by corone17** [stedolan/jq#780]
Today I've just discovered jq and have started experimenting with it, but I'm facing a problem for which I can't seem to find a solution.

I have the following (shortened) JSON that looks like this:
```json
parseMetadata({"STATUS":"OK","VERSION":"1.11.12","prid":"VPWON_1232766",......,"tijdsduur":"
00:05:27","start":"00:23:13","eind":"00:28:40",......,"sko_t":"1210","sko_cl":"3284"}})
//epc
```
Without `parseMetadata(` and `) //epc` `jq.exe -r .tijdsduur sample.json` works just fine, but since I'm calling the JSON with curl, I can't change that. At the Windows command-line I get the following:
```
curl.exe -s --url http://url-to-JSON | jq -r .tijdsduur
parse error: Invalid numeric literal at line 1, column 15
```
How can I tell jq to ignore the non-JSON data?

Is curl really necessary btw? Or can jq also load a JSON-url like that?
Thank you.

**Comment by slapresta** [comment]
That's not a JSON; this is often referred as JSON with padding, or JSONP. It does (usually) contain valid JSON inside. I would recommend you to write a short script to strip the parenthesis out. As an example, this ugly Python one-liner does it; you could pipe it between curl and jq to get the parenthesis stripped.

`python -c 'import sys; print ")".join("(".join(sys.stdin.read().split("(")[1:]).split(")")[:-1])'`

**Comment by corone17** [comment]
Coding in Python isn't my strongest virtue. If I just copy-paste your Python one-liner, I get the following:
```
curl.exe -s --url http://url-to-JSON | python -c 'import sys; print ")".join("(".join(sys.stdin.read().split("(")[1:]).split(")")[:-1])' | jq -r .tijdsduur
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal
(23) Failed writing body
```

I take it curl or jq can't do this JSONP to JSON conversion?
Since I'm working with batch-script, I'd prefer a fix in batch :(.

**Comment by pkoppstein** [comment]
@corone17 asked:
> I take it curl or jq can't do this JSONP to JSON conversion?

jq has all the power that's needed here. Here's one way to strip the "padding", assuming the input is valid JSON-P:
```
jq -R -r ' index("(") as $i |  rindex(")") as $j | .[$i+1: $j]'
```
The above is written for clarity; it could be shortened.  Anyway, you'd end up with a pipeline like this:
```
curl ...  | jq <as above> | jq ...
```

**Comment by nicowilliams** [comment]
You can do this with jq, just slurp raw (`-s` and `-R`), then use
`startswith` and `endswith`, and the substring operator, and `fromjson`.

**Comment by corone17** [comment]
These "|" pipes make it really problematic in batch. But anyway, my results:
```
curl.exe -s --url http://e.omroep.nl/metadata/aflevering/POMS_VPRO_850040 |
jq -R -r ' index("(") as $i | rindex(")") as $j | .[$i+1: $j]' | jq -r .tijdsduur
'rindex' is not recognized as an internal or external command,
operable program or batch file.
```
```
curl.exe -s --url http://e.omroep.nl/metadata/aflevering/POMS_VPRO_850040 |
jq -R -r ' index("(") as $i ^| rindex(")") as $j ^| .[$i+1: $j]' | jq -r .tijdsduur
error: syntax error, unexpected INVALID_CHARACTER, expecting $end
'1 compile error
(23) Failed writing body
```
```
curl.exe -s --url http://e.omroep.nl/metadata/aflevering/POMS_VPRO_850040 |
 jq -R -r '.[1+index("("): rindex(")")]' | jq -r .tijdsduur
error: syntax error, unexpected INVALID_CHARACTER, expecting $end
'.[1+index(():1 compile error
(23) Failed writing body
```
even...:
```
jq.exe -R -s '[.[]^|startswith("tijdsduur")]' POMS_VPRO_850040.json
error: syntax error, unexpected INVALID_CHARACTER, expecting $end
'[.[]|startswith(tijdsduur)]'1 compile error
```

P.s. `jq.exe -Rs` results in `jq.exe: Unknown option -Rs`. I've used a lot of command-line tools, but this must be the first where you can't combine parameters.

**Comment by nicowilliams** [comment]
jq -R -s --arg prefix ... 'select(startswith($prefix)
andbendswith($suffix)) | .[($prefix|length):length-($suffix|length)] |
fromjson | ...'

Fill in the blanks.  Mind you, this won't process your input incrementally.

**Comment by pkoppstein** [comment]
@corone17  - I'm sorry I didn't make it clear that the snippet I gave was suitable for a Mac/Linux/Unix command line.  For Windows, you either need to adjust the quotation marks (see below), or put your jq commands into a file, and invoke jq as: jq -f FILENAME

For Windows, the following should be about right:
```
jq -R "index(\"(\") as $i |  rindex(\")\") as $j | .[$i+1: $j]"
```

**Comment by corone17** [comment]
@pkoppstein - with "-r" (raw output) added I can say, we're getting somewhere :)
```
curl.exe -s --url http://e.omroep.nl/metadata/aflevering/POMS_VPRO_850040 |
jq -R -r "index(\"(\") as $i | rindex(\")\") as $j | .[$i+1: $j]" | jq -r .tijdsduur
00:05:27
parse error: Invalid numeric literal at line 3, column 0
```
Your code succesfully removes `parseMetadata(`, `)` (after the closing curly bracket) and the first `/`, but
```
/epc

```
with a new line / eol-character ([cr][lf]) remains.

@nicowilliams - I appreciate your help, but we're on a completely different level here. Like I said, I discovered jq today and I have absolutely no idea what that code does, or what I have to fill in the first blank. Windows would also happily tell me that 'fromjson' isn't a valid command or program.

**Comment by pkoppstein** [comment]
@corone17 - So far as I know, the //epc is not part of JSONP, so I'm not sure where it comes from and therefore am not sure what the best way to get rid of it will be.  The approach suggested by @nicowilliams (using -s) would definitely be one possibility, but you'll need to read up on jq to figure out the details.  I think you'll find that a worthwhile investment of your time, but you might like to try using `sed` or `grep` or whatever your Windows toolbox has to offer.

**Comment by pkoppstein** [comment]
@corone17 - A simple solution is:
```
jq -R -s -f jsonp.jq
```
assuming jsonp.jq is a file with contents:
```
.[1+index("("): rindex(")")] | fromjson
```

Equivalently:
```
C:\  jq -R -s ".[1+index(\"(\"): rindex(\")\")] | fromjson"
```

**Comment by corone17** [comment]
The equivalent of `grep` for Windows would be `findstr`. `findstr` can only search in 1 line at a time, in which case the `//epc` part is of no concern anymore. So yesterday I came up with this dirty fix:
```
@ECHO off
FOR /F %%A IN ('curl.exe -s --url http://e.omroep.nl/metadata/aflevering/POMS_VPRO_850040 ^|
findstr "parseMetadata" ^| jq.exe -R -r "index(\"^(\") as $i | rindex(\"^)\") as $j | .[$i+1
: $j]" ^| jq -r .tijdsduur') DO SET t=%%A
ECHO %t%
```
But ultimately your code looks best:
```
@ECHO off
SETLOCAL ENABLEDELAYEDEXPANSION
SET /P "prid=PRID: "
FOR /F "delims=" %%A IN ('curl.exe -s --url http://e.omroep.nl/metadata/aflevering/!prid! ^|
jq.exe -R -s ".[1+index(\"^(\"): rindex(\"^)\")] | fromjson" ^| jq.exe -r .start') DO SET "ss=%%A"
FOR /F "delims=" %%B IN ('curl.exe -s --url http://e.omroep.nl/metadata/aflevering/!prid! ^|
jq.exe -R -s ".[1+index(\"^(\"): rindex(\"^)\")] | fromjson" ^| jq.exe -r .tijdsduur') DO SET "t=%%B"
ECHO Start:     %ss%
ECHO Tijdsduur: %t%
ENDLOCAL
```
Result:
```
PRID: POMS_VPRO_850040
Start:     00:23:13
Tijdsduur: 00:05:27
```
Just like the code above with `findstr`, the characters that needed to be escaped posed a bit of a problem at first, but in the end it works great! To really understand the jq commands, I do have to better read up the manual still.
Thanks a lot for your help, pkoppstein!

**Comment by corone17** [comment]
I'm sorry for reopening this issue, but the following is driving me crazy:
```bat
@ECHO off

SET "curl=C:\map with spaces\curl.exe"
SET "jq=C:\map with spaces\jq.exe"

SETLOCAL ENABLEDELAYEDEXPANSION
SET "prid=POMS_VPRO_837418"
FOR /F "usebackq delims=" %%A IN (
	`"%curl%" -s --url http://e.omroep.nl/metadata/aflevering/!prid! ^|
	"%jq%" -R -s ".[1+index(\"^(\"): rindex(\"^)\")] | fromjson" ^| "%jq%" -r .start`
) DO SET "ss=%%A"
FOR /F "usebackq delims=" %%B IN (
	`"%curl%" -s --url http://e.omroep.nl/metadata/aflevering/!prid! ^|
	"%jq%" -R -s ".[1+index(\"^(\"): rindex(\"^)\")] | fromjson" ^| "%jq%" -r .tijdsduur`
) DO SET "t=%%B"

ECHO Start:     %ss% !ss!
ECHO Tijdsduur: %t%  !t!
ENDLOCAL
```
(note: the reason I put the curl|jq-command on a new line is readability)

The moment I put curl and jq in a map with spaces, I'm in trouble. Despite the double quotes and even "usebackq delims=", it results in the following every single time:
```
'C:\map' is not recognized as an internal or external command,
operable program or batch file.
'C:\map' is not recognized as an internal or external command,
operable program or batch file.
Start:
Tijdsduur:
```
Could this again be a jq syntax issue?

**Comment by pkoppstein** [comment]
@corone17 - As I mentioned, the simplest way to avoid most of the annoying escaping issues would be to use `jq -R -s -f jsonp.jq`.

Also, it seems a shame to have to call "curl" twice.  Have you thought about formatting the results as "SET" commands, along the lines of:
```
"SET ss=\(.start)\nSET t=\(.tijdsduur)"
```
That way, you could direct the output to MYSET.bat (using jq's -r option) and then call "CALL MYSET.bat".

**Comment by corone17** [comment]
> Also, it seems a shame to have to call "curl" twice.

Even this gave me lots of headaches! I'm still a novice programmer, so after lots of trail and error and reading I discovered trying to work with **multiline** variables in batch can cause a lot of problems.
So to overcome this issue I had to make sure to put jq's output in a variable as a **single** line. Along the way I also discovered I didn't need the fromjson-filter, as jq can perfectly process a single line (or 'slurped') json:
```bat
@ECHO off

ECHO Voer npo.nl programmalink in :
SET url=
SET /P url=
:: http://www.npo.nl/buitenhof/03-05-2015/VPWON_1232766/POMS_VPRO_850040 bijvoorbeeld
SETLOCAL ENABLEDELAYEDEXPANSION
FOR /F "tokens=6 delims=/" %%A IN ("%url%") DO (
	SET prid=%%A
	FOR /F "delims=" %%A IN ('curl.exe -s --url http://e.omroep.nl/metadata/aflevering/!prid! ^| jq.exe -R -r -s ".[1+index(\"^(\"): rindex(\"^)\")]"') DO SET json=%%A
	FOR /F "delims=" %%A IN ('ECHO !json! ^| jq.exe .') DO ECHO %%A
	ECHO.
	FOR /F "delims=" %%A IN ('ECHO !json! ^| jq.exe -r .start') DO SET ss=%%A
	FOR /F "delims=" %%A IN ('ECHO !json! ^| jq.exe -r .eind') DO SET to=%%A
	FOR /F "delims=" %%A IN ('ECHO !json! ^| jq.exe -r .tijdsduur') DO SET t=%%A
	ECHO Start:     !ss!
	ECHO Einde:     !to!
	ECHO Tijdsduur: !t!
)
ENDLOCAL
PAUSE
```
This script finally works, but I do have a question about the retrieval of the 3 object values.
Instead of having to write 3 for-loops to retrieve .start, .eind, and .tijdsduur, I was wondering if could do something like this...
```bat
FOR /F "tokens=1-3 delims=," %%A IN ('ECHO !json! ^| jq.exe -r ".start,.eind,.tijdsduur | some-filter"') DO (
	SET ss=%%A
	SET to=%%B
	SET t=%%C
)
```
...where `jq.exe -r ".start,.eind,.tijdsduur | some-filter"` would generate `00:23:13,00:28:40,00:05:27`, instead of all values on a new line.

Since the "C:\map with spaces\"-issue isn't particularly jq-related, I move to [stackoverflow](https://stackoverflow.com/questions/30121075/) for that.
