### ISSUE TITLE
Extract first nested element

### ISSUE THREAD

**Issue by mehimadri** [stedolan/jq#781]
I am trying to retrieve the first element from the following json:
[
  {
    "category": "RealtimeConcurrent",
    "quota": 2
  },
  {
    "category": "Realtime",
    "quota": 60
  },
  {
    "category": "Concurrent",
    "quota": 2
  },
  {
    "category": "General",
    "quota": 60
  }
]
When I use jq '..category' I get the following
"RealtimeConcurrent"
"Realtime"
"Concurrent"
"General"
However I would like retrieve the elements separately, like I need to extract "RealtimeConcurrent". What should I do to achieve this. Thanks!

**Comment by pkoppstein** [comment]
@mehimadri - Maybe I'm being dense, but I don't understand what it is you want. The filter 
```.[].category
``` (which is perhaps what you meant) yields the values you show separately, which is what you say you want.

Please clarify (briefly).  

By the way, many people believe that these "usage" questions are often best asked at  http://stackoverflow.com/questions/tagged/jq
