### ISSUE TITLE
fix for gsub bug

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#782]
This update addresses two important issues related to the sub and gsub filters,
while also greatly simplifying the implementation of the entire sub/gsub family.

In summary: sub/3 is added, and all the other sub and gsub filters are replaced by trivial implementations that use sub/3 directly or indirectly.

The main problems with the existing implementations are:
* (1) gsub(re;s) and gsub(re;s;flags) produce incorrect results when "s" contains back-references.
* (2) sub/3 is not defined.

For example, consider: `"a1b2" | gsub("(?<d>\\d)"; ":\(.d);")`
This should produce "a:1;b:2;" but currently produces ":1;:2;" instead.

(My apologies for not being able to offer a PR regarding the following.  It's complicated to explain, so I won't try.)

The following lines are intended to replace the entire block of lines implementing sub and gsub in builtin.c.  jq has been built and successfully tested with the update.  It would be nice to add a reference to sub/3 in the documentation :-)

```
  // If s contains capture variables, then create a capture object and pipe it to s
  "def sub($re; s; flags):"
  "  . as $in"
  "  | (flags | index(\"g\")) as $g"
  "  | (if $g then flags[0:$g] + flags[$g+1:] else flags end) as $flags"
  "  | [match($re; $flags)]"
  "  | if length == 0 then $in"
  "    else .[0] as $edit"
  "    | ($edit | .offset + .length) as $len"
       //  # create the "capture" object:
  "    | reduce ( $edit | .captures | .[] | select(.name != null) | { (.name) : .string } ) as $pair"
  "        ({}; . + $pair)"
  "    | $in[0:$edit.offset]"
  "      + s"
  "      + ($in[$len:] | if $g then sub($re; s; flags) else . end)"
  "    end ;",
  //
  "def sub($re; s): sub($re; s; \"\");",
  // repeated substitution of re (which may contain named captures)
  "def gsub($re; s; flags): sub($re; s; flags + \"g\");",
  "def gsub($re; s): sub($re; s; \"g\");",
```

**Comment by thedward** [comment]
This is fantastic. I was just trying to figure out a working implementation myself. Thanks for beating me to it!

**Comment by pkoppstein** [comment]
@thedward - A third reason for this change is that with it, gsub is much faster than before (e.g. more than 10x):
```
def test(n):
  ("a" * n) | gsub("a";"b") | length;

test(1e3)
```
```
# BEFORE (current version -- jq-1.5rc1-70-g7675f74)
$ time jq -n -f gsub.jq
1000
# user	0m2.881s
# sys	0m0.036s
```
```
# AFTER (new gsub):
# time jq -n -f newgsub.jq
#user	0m0.191s
#sys 	0m0.010s
```

@wtlangford - Since you've taken the lead on regex before, is there any chance you could update jq with this change?  Thanks.

**Comment by nicowilliams** [comment]
@pkoppstein A PR would help, yes, particularly if I have comments to make.  You can use the github web UI to edit `builtin.c` in the browser.

One comment I have is that in `sub/3` you assume at most one instance of `"g"` in `flags`.

Another comment is that `sub/3` is recursive, but not tail-recursive.  Is this a problem?  I'd think so.  Which relates to: why is it better to implement the `"g"` flag in jq rather than let Oniguruma handle it?  What other bugs might we be introducing by doing this?

Another comment is: what about tests?  A regression test for the bug in `gsub/2` would be nice.

**Comment by nicowilliams** [comment]
Assuming only one `"g"` in flags is probably fair, but removing all instances is more defensive.

Another comment is: I'd like to understand why the new `gsub` is so much faster than before.

What was the source of the bug you mentioned: the jq code for `_stredit` or something in Oniguruma?

**Comment by pkoppstein** [comment]
@nicowilliams - The version above was intended to be correct-simpler-faster rather than "optimized-prematurely", but it's easy enough to optimize as you suggested.  Here accordingly is the ready-to-install-in-builtin.c version (i.e., it has been compiled and tested):
```
  // If s contains capture variables, then create a capture object and pipe it to s
  "def sub($re; s; flags):"
  "  def subg: explode | select(. != 103) | implode;"
  // # "fla" should be flags with all occurrences of g removed; gs should be non-nil if flags has a g
  "  def sub1(fla; gs):"
  "    def mysub:"
  "      . as $in"
  "      | [match($re; fla)]"
  "      | if length == 0 then $in"
  "        else .[0] as $edit"
  "        | ($edit | .offset + .length) as $len"
           //  # create the "capture" object:
  "        | reduce ( $edit | .captures | .[] | select(.name != null) | { (.name) : .string } ) as $pair"
  "            ({}; . + $pair)"
  "        | $in[0:$edit.offset]"
  "          + s"
  "          + ($in[$len:] | if gs then mysub else . end)"
  "        end ;"
  "    mysub ;"
  "    (flags | index(\"g\")) as $gs"
  "    | (flags | if $gs then subg else . end) as $fla"
  "    | sub1($fla; $gs);",
  //
  "def sub($re; s): sub($re; s; \"\");",
  // repeated substitution of re (which may contain named captures)
  "def gsub($re; s; flags): sub($re; s; flags + \"g\");",
  "def gsub($re; s): sub($re; s; \"g\");",

```

The above version of gsub draws on the 1.5rc1 version, but that version was never really intended to conform to standard gsub semantics.  Since the newer (recursive) version yields "correct" results and is simple and faster, it seems like the obvious path forward, even if it is not the absolute best that Oniguruma can ultimately support.

**Comment by nicowilliams** [comment]
@pkoppstein OK, but why not use the `g` flag?  Also, don't we need new tests?

**Comment by pkoppstein** [comment]
@nicowilliams asked:
> why not use the g flag?

If you're asking why not implement gsub using match with the "g" flag -- that's what was tried (with only limited success) before -- it's difficult to keep track of the offsets. It might be worthwhile pursuing that avenue if it was faster, but it isn't.  (Perhaps there's a better way to integrate jq and Oniguruma, but I'm working with what we've got.)  

The first test in the following already exists in all.test and is included to suggest the appropriate placement of the others.
```
# reference to named captures
gsub("(?<x>.)[^a]*"; "+\(.x)-")
"Abcabc"
"+A-+a-"

gsub("(?<x>[a-z])(?<y>[0-9])"; "+\(.x):\(.y)")
"aax1y2zzz"
"aa+x:1+y:2zzz"

gsub("a";"b")
"aaa"
"bbb"

gsub("a"; "b"; "i")
"xaAay"
"xbbby"

gsub("aa";"b")
"aaaaaaa"
"bbba"

gsub("aa";"b")
"aaaaaaa"
"bbba"

gsub("a";"abc")
"abcabc"
"abcbcabcbc"
```

**Comment by nicowilliams** [comment]
Hmm, what about the regexp you posted about initially, `(?<d>\\d)`.  How do I parse that?

**Comment by nicowilliams** [comment]
Oh, it's a named matching group.

**Comment by nicowilliams** [comment]
And I have too many backslashes.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> And I have too many backslashes.

No, we want two here:  PCRE `\d` (a digit) has to be written as "\\d" in JSON.  A relevant test triple would be: 
```
gsub( "(?<d>\\d)"; "\(.d)!")
'"123"
"1!2!3!"
```

**Comment by pkoppstein** [comment]
@nicowilliams - Thanks! 

A small detail -- this update added sub/3, not gsub/3, which was there all along.  That is, we now have all four of [g]sub/{2,3}, i.e. the manual.yml needs to be tweaked.

(While on the topic of the jq manual -- it would be good if the online manual referred to "splits" rather than "split2".)
