### ISSUE TITLE
unique function -args broken/doesn't work as documented

### ISSUE THREAD

**Issue by virtzilla** [stedolan/jq#783]
If I try the examples documented for the unique function I get an error whenever trying to provide an argument. See below. 

*echo "[{"foo": 1, "bar": 2}, {"foo": 1, "bar": 3}, {"foo": 4, "bar": 5}]" | jq 'unique(.foo)'* 
*error: too many arguments to unique (expected 0 but got 1)* 
*unique(.foo)1 compile error*

BTW - Same thing if I try it on https://jqplay.org. If I leave off the parentheses/argument, it will filter uniqueness on the entire record, but it doesn't appear to work with any args as documented.

If I try the other example (copy paste from the doc) with the length function on jqplay.org, I also get an error:

*jq 'unique(length)'*
*error: syntax error, unexpected INVALID_CHARACTER, expecting $end*
*jq 'unique(length)'   1 compile error*

**Comment by wtlangford** [comment]
At a guess, this is one of the places where the docs are ahead of the
current version. We likely overloaded unique after 1.4 and the docs leaked
that through. If you can, build master and it should work.

**Comment by slapresta** [comment]
Use `unique_by` on 1.4.

**Comment by dtolnay** [comment]
#866 will solve the problem of docs being ahead of the released versions.
