### ISSUE TITLE
A newline character is always added to the output

### ISSUE THREAD

**Issue by niekoost** [stedolan/jq#787]
Problem
jq always outputs an extra newline, even when -r (raw output) or -c (compact output) are used. This is nice from a visual perspective when you're using it from a command line, but not when you only want the output for further processing in, for instance, a PHP script.

Example
input: "[{},{}]"
command: jq '. | length' -c
output: "2
"
expected output: "2"

Request
Please provide an option to suppress the additional new line.

Context:
I use jq as a processor for Mandrill events in my PHP scripts. These events are provided in JSON, representing an array of event objects. Since these events also contain the raw message (which can be very large), I first check some fields to determine how to further process each event. I use proc_open.

**Comment by nicowilliams** [comment]
This is only safe in raw output mode!  And it's provided now in master (see `-j`).

In non-raw output mode jq could skip the newline when the value to be printed is an array, object, or string.

**Comment by nicowilliams** [comment]
This should be implemented by having `-j` not emit the newline in non-`--raw-output` mode when the value last output is an array, object, or string.

**Comment by joonas-fi** [comment]
I ran into this as well. I am selecting a single string from a JSON file, and was expecting raw mode to not end up with a newline. I am using jq to extract a string to a shell variable (`foo=$(jq ...)`). Using `$ jq .... | tr -d '\n'` is not acceptable generally (was in my case) because it removes all newlines - not just the last one.

**Comment by nicowilliams** [comment]
I think we can probably have this work such that if you use `-j` twice then no newline is output ever, but in non-raw output mode it will output a space after any number, boolean, or `null`.

**Comment by nicowilliams** [comment]
Actually, in 1.5 it's already the case that you can use `-j` to stop newlines being printed, but it does put jq into raw-output mode.

**Comment by mig82** [comment]
I'm using JQ to define a Git filter for JSON files and this `-j` flag is what I was looking for. Super-useful.

**Comment by Kiemes** [comment]
Would have saved me quite some time if this would be in `jq --help` directly. My bad. I tend to not read every last line of CLI output ;) (meaning `See the manpage for more options`). Thanks for the option though! Very helpful

**Comment by AmadeusK525** [comment]
I agree that having this on `--help` would be pretty good :)
