### ISSUE TITLE
Bring back --online-input?

### ISSUE THREAD

**Issue by bterlson** [stedolan/jq#788]
--online-input was present previously and made it possible to handle a large array or object being streamed over a long period of time, eg if my input is like:
```
[ { a: 1 }, { a: 2}, ... time passes ... , {a : 10000 } ]
```
I could transform this stream using --online-input, but with the latest version the only option is to wait for the stream to end (when the array literal is closed) before anything is sent to output. This is bad when such streams are very long (containing, say, millions of entries and gigabytes of data streamed over a long period of time).

**Comment by bterlson** [comment]
apparently --stream exists and I missed it. Thanks :-D

**Comment by nicowilliams** [comment]
`--online-input` was awful.  `--stream` is much better: it's a proper streaming parser.
