### ISSUE TITLE
Reserved words should not generate errors when used as object keys

### ISSUE THREAD

**Issue by ssimeonov** [stedolan/jq#794]
The output below sums up the issue. It's strange for reserved words such as `label` and `break` to generate syntax errors when, by default, jq allows unquoted object keys. At minimum, the error message should be more helpful.

```bash
➜ jq --null-input '{label: true}'
jq: error: syntax error, unexpected label (Unix shell quoting issues?) at <top-level>, line 1:
{label: true}
jq: 1 compile error
➜ jq --null-input '{"label": true}'
{
  "label": true
}
```

**Comment by nicowilliams** [comment]
@ssimeonov Well, keywords are keywords.  I'll see what I can do about the error message.

**Comment by nicowilliams** [comment]
I can make it so keywords are allowed as dict keys, but I probably can't do much better (e.g., allowing them as function names or variable names).

**Comment by nicowilliams** [comment]
Thanks for this idea, it's very nice.

**Comment by ssimeonov** [comment]
@nicowilliams you are welcome. `jq` is an awesome tool. Thanks for pushing it forward.
