### ISSUE TITLE
Is there a function to return the parent of a node?

### ISSUE THREAD

**Issue by soheilpro** [stedolan/jq#796]

**Comment by nicowilliams** [comment]
There is no such function.  A `jv` value can be referenced from many other `jv` values, so libjv couldn't provide such functionality.  jq can't either for the same reason.  You can keep track of the parent node in your jq program however, assigning it to a `$parent` variable with which to keep track of it, but you'll have to implement your own recursor, something like this, for example:

    ./jq -cn '{a:{b:{c:0}}}|[null,.]|recurse(.[1] as $parent|try (.[1][]|[$parent,.]) catch empty)'

**Comment by pkoppstein** [comment]
@soheilpro - Here is a slightly different take on your question.

It is motivated by the observation that the jq filter .[], if given an array as input, emits a stream of the array's elements.  We could therefore define a similar filter, parent_child/0, which, if given an array, $in, as input, instead emits the stream:  .[] | [$in, .]

For example: [1,2] | parent_child would yield the stream:
```
[[1,2], 1]
[[1,2], 2]
```

For objects, it seems to me that it may be more useful to view the "children" of an object as the stream of {key: value} pairs.  

These considerations lead to the following definition:
```
# If the input is composite, emit a stream of [parent, child] pairs, 
# otherwise do not emit anything
def parent_child:
  . as $in
  | if type == "object" then
      (keys[] as $key
       | [$in, { ($key):  $in[$key] }])
    elif type == "array" then
      ($in[] | [$in, .])
    else empty
    end;
```

**Comment by soheilpro** [comment]
Thank you guys.
