### ISSUE TITLE
Is there a way to `interlace`?

### ISSUE THREAD

**Issue by evandrix** [stedolan/jq#797]
Hi,

I've a recent use case where, given a JSON dict, like:
{
   "_id": "my-unique-id",
   "k1": ["a","b","c"],
   "k2": [1,2,3,4],
   "k3": "a string value"
}

I would like to use `jq` to display the length of all values in the dict which are arrays (excluding strings), together with their associated keys alongside, so something like:
   k1 3
   k2 4
_id, and k3 are omitted, because they are strings, not arrays

Is this already possible? I found the function `keys`, but that doesn't seem to help with doing this at all.

**Comment by pkoppstein** [comment]
With your input, the following will produce {"k1": 3, "k2": 4}:
```
 . as $in
 | reduce keys[] as $key ({}; . +  ($in[$key] | if type == "array" then {($key): length} else null end) )
```

**Comment by evandrix** [comment]
yep, that works perfectly. Thanks!

**Comment by pkoppstein** [comment]
You're welcome.

By the way, some people prefer solutions like the following:
```
 . as $in | with_entries( if .value | type == "array" then .value |= length else empty end)
```
It is shorter, but probably requires more explaining.
