### ISSUE TITLE
implode assertion violation

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#802]
```
$ jq --version
jq-1.5rc1-96-g74ecb88
$ jq -n '[1e10] | implode'
Assertion failed: (codepoint >= 0 && codepoint <= 0x10FFFF), function jvp_utf8_encode, file jv_unicode.c, line 77.
```
Same thing with jq 1.4

**Comment by nicowilliams** [comment]
Should invalid codepoints be replaced with `U+FFFD` or should `implode` raise an error?  The latter seems best because jq programs could replace invalid codepoints with `U+FFFD` themselves.

**Comment by pkoppstein** [comment]
The complementarity of implode/explode is best-served if implode raises an error, but we can have our cake and eat it by adding `implode/1`, e.g. implode(true) (meaning replace invalid codepoints by U+FFFD) and/or implode(s) (defining the replacement character if `s  | (string and length == 1)`).

**Comment by nicowilliams** [comment]
I was thinking that `implode/1` should take a stream of codepoints as its argument, then it's cheap and easy to filter/map away invalid codepoint values.  Anyways, fixed.
