### ISSUE TITLE
How to merge 2 files json in one with 1 array only for all ? thx

### ISSUE THREAD

**Issue by mistertest** [stedolan/jq#805]
Hello, 
I'm a french user of linux ubuntu, for my project about streaming i need to do specific opperations about scrapping and  json on my vps ubuntu.

So i want use this great tool with my ubunu.
The problem : 

I have a series of  files in a folder like that:
a-01.json
a-02.json
a-03.json
etc...

All json generated by my module node js for scrapping look like that  : 

a-01.json : 

[
{
"title1": "title1",
"title2": "title2",
},
{
"title1": "title1",
"title2": "title2",
}

]

a-02.json : 
[
{
"title1": "title1",
"title2": "title2",
},
{
"title1": "title1",
"title2": "title2",
}

]

And i want to merge all files in one json and i want it look like that : 

[
{
"title1": "title1",
"title2": "title2",
},
{
"title1": "title1",
"title2": "title2",
},
{
"title1": "title1",
"title2": "title2",
},
{
"title1": "title1",
"title2": "title2",
}
]

I use this command but not exactly wahat i want : 

jq -s '.' a-*.json > manifest.json

Thank you verry much for your help the comunauty !

**Comment by slapresta** [comment]
Using the `-s` option will return an array containing the contents of the input JSON files, which, in your case, are also arrays. This means that you need to spread (`...[]`) two array levels, and collect (`[...]`) the result.

`jq -s '[.[][]]' a-*.json > manifest.json`

**Comment by mistertest** [comment]
Wooowww the fastest answer i have ever seen in my life of dev !
And it's work verry well on first test,  Thank you Segnor slapresta.

**Comment by slapresta** [comment]
You're welcome! If you need anything else, try the `jq` tag on StackOverflow; they're even faster over there!

**Comment by mistertest** [comment]
Ok thanks, i have litle problem :the result in not in order cetain elements comes before others, the alphabetical is not respected. How can i do that ?

**Comment by pkoppstein** [comment]
It would seem that you want to sort the array previously obtained.  If, for example, you want to sort by the values of the keys "title1" and "title2", then the relevant filter would be:
```
sort_by([.title1, .title2])
```
By the way, as @slapresta pointed out, usage questions are probably best asked at  http://stackoverflow.com/questions/tagged/jq

**Comment by mistertest** [comment]
Ok thx i will reading somes documentation about that and will going to satckoverflow for next questions.
