### ISSUE TITLE
--help is useless

### ISSUE THREAD

**Issue by rdm** [stedolan/jq#807]
Existing behavior looks like this.

    $ jq -help
    C:\Windows\system32\jq.exe: Unknown option -help
    Use C:\Windows\system32\jq.exe --help for help with command-line options,
    or see the jq documentation at http://stedolan.github.com/jq

    $ jq --help
    
    jq - commandline JSON processor [version 1.4]
    Usage: C:\Windows\system32\jq.exe [options] <jq filter> [file...]
    
    For a description of the command line options and
    how to write jq filters (and why you might want to)
    see the jq manpage, or the online documentation at
    http://stedolan.github.com/jq

But there is no jq manpage distributed for the windows version, and the one line of usage should probably be the default for an unrecognized command line option.

I was expecting one line summaries for at least the most common command line options (the ones with single character aliases). Could something like a cut-down version of the "Invoking JQ" part of the manual get included? (If this is acceptable and you'd like me to submit a pull request with a "usage.c", please let me know...)

Perhaps also a plain text copy of the man page and/or the manual should be distributed for windows?

**Comment by pkoppstein** [comment]
The current ("master") version of jq behaves differently.  Both "jq -h" and "jq --help" produce:
```
jq - commandline JSON processor [version 1.5rc1-96-g74ecb88]
Usage: jq [options] <jq filter> [file...]

	jq is a tool for processing JSON inputs, applying the
	given filter to its JSON text inputs and producing the
	filter's results as JSON on standard output.
	The simplest filter is ., which is the identity filter,
	copying jq's input to its output unmodified (except for
	formatting).
	For more advanced filters see the jq(1) manpage ("man jq")
	and/or http://stedolan.github.com/jq

	Some of the options include:
	 -c		compact instead of pretty-printed output;
	 -n		use `null` as the single input value;
	 -e		set the exit status code based on the output;
	 -s		read (slurp) all inputs into an array; apply filter to it;
	 -r		output raw strings, not JSON texts;
	 -R		read raw strings, not JSON texts;
	 -C		colorize JSON;
	 -M		monochrome (don't colorize JSON);
	 -S		sort keys of objects on output;
	 --arg a v	set variable $a to value <v>;
	 --argjson a v	set variable $a to JSON value <v>;
	 --slurpfile a f	set variable $a to an array of JSON texts read from <f>;
	See the manpage for more options.
```

But I would agree that this too could be improved -- especially the last line.

**Comment by dtolnay** [comment]
Nico added a more useful --help output in e151a30.
