### ISSUE TITLE
Debugging & performance tuning

### ISSUE THREAD

**Issue by ssimeonov** [stedolan/jq#808]
I am used to `jq` being very fast most of the time so it's surprising when a script seems to execute very slowly. This happened to me over the weekend and, in the process of diagnosing the problem, I realized that `jq` has extremely limited debugging & performance tuning abilities. I wonder what others are doing when faced with these issues and what is a minimal set of capabilities that could support more complex `jq` scripts. 

My standard approach to debugging is to generate multiple outputs, e.g., 

```
.foo | ., .bar
```

This works to an extent but has the following problems:

1. Diagnostic output (`.` in the above case) is mixed with real output on STDOUT.
1. A script error can prevent the diagnostic output, strangely, even if it happens after it?
1. This can't help performance tuning.

A minimal set of features that could be very helpful could be:

- The ability to output to STDERR
- The ability to output the current time as milliseconds since epoch

The above example could then become something like:

```
.foo | ([now, .] | stderr), .bar
```

STDERR could be post-processed with `grep` (to filter non JSON output, e.g., error messages) and then `jq` to analyze the diagnostic output (likely with `--slurp`). Because of this, `stderr` output should always be compact and in JSON format.

Beyond the minimal feature set, I would really enjoy having a set of lap timers that work along the lines of:

```
# Assume prologue, work & epilogue are functions
start_lap(0) | prologue |
.[] |
start_lap(1) | work | end_lap(1) |
epilogue | end_lap(0) |
(timers | stderr), .
```

I could imagine `timers` to output something like the following on STDERR:

```
[[start of first lap timestamp, end of last lap timestamp, number of laps, milliseconds per lap], ...]
```

Is there anything in the works to help debugging & performance tuning? What are others doing?

**Comment by pkoppstein** [comment]
@ssimeonov asked:
> Is there anything in the works to help debugging & performance tuning?

If at all possible, I would recommend that you try building the 'master' version of jq available from https://github.com/stedolan/jq/; if you are unable to do so, then please consider the executables for 1.5rc1 available at https://github.com/stedolan/jq/releases

In any case, the above-mentioned "releases" page includes some details about what's become available since jq 1.4.  

Here is a brief and probably incomplete summary of some enhancements that are available in the 'master' version and that may be of interest to you:

1) Filters
 debug
 stderr
 error
 now

e.g.
```
$ jq -n 'now | debug'
["DEBUG:",1433814220.706848]
1433814220.706848
```
2) Greatly enhanced error messages, e.g. 
parse error: Invalid numeric literal at line 4, column 0

**Comment by wtlangford** [comment]
It's worth noting the (undocumented) debug flags: `--debug-dump-disasm` and `--debug-trace`

`--debug-dump-disasm` dumps out the intermediate representation your jq program compiles to.  Practice reading it can sometimes reveal why your script is running slowly.  `--debug-trace`, while less useful for "why is this slow", can sometimes be useful for "why is this wrong?"

The code in master/1.5rc1 also has quite a few performance improvements over 1.4, including compile-time constant folding and tail-call recursion.  There were also some interesting behaviors that caused reference counting to be... odd, leading to increased memory usage (and therefore memory copies, therefore slowdowns) that I think we found and fixed.  So, I'd definitely recommend a switch to 1.5rc1 (or master).

**Comment by nicowilliams** [comment]
Some day a debugger would be nice...  The enhancements in master should help a great deal (they help me), I hope.

**Comment by ssimeonov** [comment]
@wtlangford I have been running 1.5rc1. I used to build interpreters and compilers in another life so I'll take a look at `--debug-dump-disasm`. These behaviors are not a substitute for debug output or timing.

**Comment by ssimeonov** [comment]
@nicowilliams I'm curious, which enhancements were you referring to?

**Comment by ssimeonov** [comment]
@pkoppstein very helpful info, thanks. I'm running 1.5rc1 already. When I tried the tip of `master` a couple of weeks back it had trouble building on Mac OS X Yosemite and Ubuntu Linux.

**Comment by wtlangford** [comment]
@ssimeonov Definitely not a substitute, but hopefully useful in the intermediate term.  We might be a ways out from a debugger yet.
Out of curiosity, what issues were you having building `master` on OS X?

**Comment by nicowilliams** [comment]
> @nicowilliams <https://github.com/nicowilliams> I'm curious, which
> enhancements were you referring to?
>

There are error reporting enhancements, a built-in for outputting debug
messages, a built-in for getting the current time, datetime built-ins, a
built-in for outputting to stdout.  That's pretty much what you asked for.
Some of this is in master, not 1.5rc1.

I should make an rc2 next week.

**Comment by ssimeonov** [comment]
@nicowilliams an rc2 would be welcome!

**Comment by ssimeonov** [comment]
@wtlangford on the tip of `master`, the error on Mac OS X is

```
./libtool: line 7902: func_munge_path_list: command not found
```

Full output: https://gist.github.com/ssimeonov/98d3dd13c6eecb3ae454

**Comment by pkoppstein** [comment]
@ssimeonov wrote:
> Strangely, I get the same error today on rc1 while a few weeks ago I was able to build rc1

That may the most important clue yet.

I'm not sure how useful the following is, but just in case:

1) I've been using three different Macs to compile 'master' and have never run into a difficulty similar    to the one described.
2) I've compared the "autoreconf -i ; ./configure" output on one of the Macs with the gist provided. The main difference seems to be the Darwin version number, e.g.:

 < checking dynamic linker characteristics... darwin13.4.0 dyld 
 > checking dynamic linker characteristics... darwin14.3.0 dyld

Is it possible that an environment variable such as DYLD_LIBRARY_PATH is relevant here?

**Comment by ssimeonov** [comment]
@pkoppstein just FYI, that environment var is not present in my env.

**Comment by nicowilliams** [comment]
There is now a `debug` builtin for this purpose.
