### ISSUE TITLE
$ENV instead of env

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#820]
I added `env` so as to not have to bother creating an `$ENV` object from the environ, but jq could just check if the program has an unresolved reference to `$ENV`, then create an `$ENV` object and bind it.

This would make accessing the environment more comfortable, more like how it is in most high-level programming languages.

**Comment by nicowilliams** [comment]
This can wait till 1.6 though.

**Comment by nicowilliams** [comment]
This basically requires writing a function to recursively traverse the block program just like `block_bind_subblock()` does, but instead of establishing a binding it could call a callback for each unbound symbol.  This would then get called to see if `$ENV` is unbound.  A benefit of this is that when `block_compile()` fails jq could use this new function to print a list of unbound symbols, instead of making the user find them all through trial and error.

**Comment by nicowilliams** [comment]
Fixed with 3504bd9; see #1353.

**Comment by pkoppstein** [comment]
@nicowilliams: This commit seems to break compilation in some environments.  On a Mac:

```
~/github/jq$ git log -1
commit 8ea21a54adfa9e518f4855d2dc06ae3c0456d69c
Author: Nicolas Williams <nico@cryptonector.com>
Date:   Wed Feb 22 23:01:56 2017 -0600

    Add `halt`, `halt_error` builtins (fix #386)

~/github/jq$ make
...

  CC       src/compile.lo
src/compile.c:1011:7: error: use of undeclared identifier 'environ'
  if (environ == NULL)
      ^
src/compile.c:1013:22: error: use of undeclared identifier 'environ'
  for (size_t i = 0; environ[i] != NULL; i++) {
                     ^
src/compile.c:1016:22: error: use of undeclared identifier 'environ'
    if ((eq = strchr(environ[i], '=')) == NULL)
                     ^
src/compile.c:1017:41: error: use of undeclared identifier 'environ'
      r = jv_object_delete(r, jv_string(environ[i]));
                                        ^
src/compile.c:1019:44: error: use of undeclared identifier 'environ'
      r = jv_object_set(r, jv_string_sized(environ[i], eq - environ[i]), jv_string(eq + 1));
                                           ^
5 errors generated.
make[2]: *** [src/compile.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
~/github/jq$ 
```

**Comment by nicowilliams** [comment]
It does.  I'm confused as to why it breaks with clang but not gcc.

**Comment by wtlangford** [comment]
If you remove the include guards around `environ` it works under clang on OSX.  I can take a look at this, if you'd like.

Do you run with an actual gcc on OSX (not Apple's _abomination_ where clang masquerades as a gcc frontend), nico?

**Comment by nicowilliams** [comment]
I... don't build on OS X, except when we do releases.

**Comment by nicowilliams** [comment]
I want to CI for OS X at some point too.

**Comment by nicowilliams** [comment]
Pushed to my master; let's see if Appveyor and Travis are happy now.

**Comment by nicowilliams** [comment]
It was a silly typo.

**Comment by wtlangford** [comment]
Travis already does builds on osx.

**Comment by nicowilliams** [comment]
Oh, oh, right.

**Comment by nicowilliams** [comment]
Pushed fix to `master` after Appveyor build completed.
