### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by BHare1985** [stedolan/jq#825]
Loading a 3GB geojson file and all i want to do is extract the features array. This a little bit into the process : http://i.imgur.com/cOZE54U.png hitting 26GB memory, it eventually hit my system limit of 32GB and crashed.

Can't provide the geojson file, but here is the command I ran

`jq --compact-output ".features" test.geojson > test_new.geojson `

**Comment by pkoppstein** [comment]
Were you using jq version 1.4?   If so, could you try jq 1.5rc1 (https://github.com/stedolan/jq/releases) or (even better if you can compile it) the "master" version (https://github.com/stedolan/jq)?

**Comment by nicowilliams** [comment]
@BHare1985 You'll want the `--stream` option.  Working with streaming is harder though.

**Comment by nicowilliams** [comment]
BTW, the way you'd do this with streaming would be something like this:

    % jq --stream 'select(.[0].[0] == "features") | ...'

The `...` part would probably be the stream-to-value function that can be found in `tests/modules/streaming.jq` in the git source tree.  That module needs a bit of work and its functions should be made builtins.  (There should be at least three functions: one to truncate streams as in that test module, one to stream values, and one to covert streams to properly-formed values.)
