### ISSUE TITLE
Select by evaluating all array values at once

### ISSUE THREAD

**Issue by anayram** [stedolan/jq#828]
Very likely making a beginner error here but I can't seem to find the answer: I am stuck when trying to get records that lack a specific value by using 'not equal' (!=) or the 'not' operator. I am using filters like:
jq -s 'select(.foo != "value A")'
jq -s 'select(.foo | contains("value A") | not)'

Which work ok most of the time, except if I need it to evaluate an array of values like "hasModel" in the example below.
```json
{
  "RELS-EXT": {
        "hasModel": [
          "info:License",
          "info:default",
          "info:ser",
          "info:tr"
        ]
      },
      "pid": "sample-identifier-1"
}
{
  "RELS-EXT": {
        "hasModel": [
          "info:default",
          "info:ser",
          "info:tr"
        ]
      },
      "pid": "sample-identifier-2"
}
```
I want to get identifiers for records where 'hasModel' doesn't have any values containing 'License'. But if I use any of the filters mentioned before, records containing 'License' will be selected and not filtered out because it reads the rest of the values (info:default, info:ser, info:tr) as not 'License'.
I think that the problem may be that  my jq expression seems to evaluate over each array value separately, not over all array values in a record. I used --slurp (-s) with no luck.

I have tried:
jq -s '.[] | select(."RELS-EXT".hasModel[]?!="info:License") | .pid'
and
jq -s '.[] | select(."RELS-EXT".hasModel[]? | contains("info:License") | not) | .pid'

**Comment by slapresta** [comment]
Right. Your "diagnosis" is correct, as in, the values that are not "License" verify the condition and thus the condition for the `select` is true and the value gets selected, even if it is not true for all elements; in fact, the value would get selected once for each valid condition. It seems like you'd want to use either the `any` or the `all` filter.

So, starting from your sample programs:

`select(."RELS-EXT".hasModel[]?!="info:License") | .pid`
`select(."RELS-EXT".hasModel[]? | contains("info:License") | not) | .pid`

We could use `all` to express the condition in a way similar to the first program:

`select(."RELS-EXT".hasModel? | all(. != "info:License")).pid`

Or we could use `any` to express the condition in a way similar to the second program:

`select(."RELS-EXT".hasModel? | any(contains("info:License")) | not).pid`

Hope this helps!

**Comment by pkoppstein** [comment]
```
select( .["RELS-EXT"].hasModel | map(index("License") ) | any | not) | .pid
```
or (using a version of jq with any/1):
```
select( .["RELS-EXT"].hasModel | any( index("License") ) | not ) | .pid
```

Alternatively, to avoid the difficult-to-read `select( _ | not )`:
```
 .pid as $pid | if .["RELS-EXT"].hasModel | map(index("License") ) | any then empty else $pid end
```

**Comment by anayram** [comment]
It is really great to have these examples. All programs worked except for the filter 
select(."RELS-EXT".hasModel? | all(. != "info:License")).pid
which brought results containing the unwanted value.

Thanks so much.
