### ISSUE TITLE
main.c:136: undefined reference to `priv_fwrite' in master

### ISSUE THREAD

**Issue by l29ah** [stedolan/jq#830]
Tried to build ec7647c4ab1c50d7f45c8ff9fd73917af867e0be in Gentoo, got this: https://bpaste.net/show/850b05544ba8

**Comment by nicowilliams** [comment]
Ah, yes, I've not used `--disable-static` for a while.  We should put `priv_fwrite()` in `util.h`.

In the mean time, building with `--disable-dynamic --enable-static` is your workaround.
