### ISSUE TITLE
Unicode input from console not quite right

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#846]

**Comment by nicowilliams** [comment]
Paging @svnpenn.  Can you confirm?

**Comment by svnpenn** [comment]
@nicowilliams I will check it out

**Comment by nicowilliams** [comment]
Ah, but it's not broken.  The problem is that there is still buffering, so we need to flush.  And if you run with `--unbuffered` all is OK.

**Comment by svnpenn** [comment]
You mean like `fflush(stdout);`?

**Comment by nicowilliams** [comment]
Yeah.

**Comment by dtolnay** [comment]
Has this been resolved? If not, what is the remaining action?

**Comment by nicowilliams** [comment]
I still have to figure this one out.

**Comment by nicowilliams** [comment]
I've tested every version of jq since the first commit that added the use of `WriteFile()` to write to the console, and I see the same behavior with all of them.  Basically, my fix for handling Unicode on the Windows console is not complete, but I don't know what the remaining problem is about.  It seems there's a bug as to Unicode input from the console.

**Comment by nicowilliams** [comment]
We should investigate using https://github.com/rainers/cv2pdb to make debugging jq executables made with mingw possible.

**Comment by nicowilliams** [comment]
I forget what this is about, but the commentary seems to indicate it's not a problem now.  Closing.
