### ISSUE TITLE
make clean should not trigger configure

### ISSUE THREAD

**Issue by kislyuk** [stedolan/jq#848]
I don't know autotools, so I'm not sure why, but "make clean" triggers a run of configure:
```
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --disable-docs --no-create --no-recursion
...
```
It would be preferable if that could be avoided.

**Comment by wtlangford** [comment]
So, the only reason that should happen is if you don't already have a
makefile.  Autotools will run configure if you run make and don't have a
makefile.

**Comment by ScoreUnder** [comment]
Surely you would need a makefile in place to launch autotools from that target?

**Comment by nicowilliams** [comment]
In master there's no such bug, and make clean does not remove the Makefile (make distclean is another story).  What version of jq are you using?

**Comment by dtolnay** [comment]
I have run into this a few times on master. In my experience it has been when I modify configure.ac, so it "kind of" makes sense. Here is a repro:

    git clone https://github.com/stedolan/jq.git
    cd jq
    autoreconf -i && ./configure
    make clean # does not trigger configure
    touch configure.ac
    make clean # triggers configure

@kislyuk, is this maybe what happened in your case?

**Comment by nicowilliams** [comment]
Autotools do arrange to re-./configure when configure.ac is modified, yes.  That's a feature.

**Comment by dtolnay** [comment]
I am going to assume this was caused by configure.ac being modified. If anyone can reproduce this issue without touching configure.ac, we can reopen and debug.
