### ISSUE TITLE
http://stedolan.github.io/jq/tutorial/ clips left, unnecessarily scrolls.

### ISSUE THREAD

**Issue by skierpage** [stedolan/jq#849]
In both Firefox and chromium, tutorial content is clipped on the left side. This arises from the negative margin on the row:
```
.row {
    margin-left: -20px;
}
```
Also, fixing a width seems unnecessary
```
.container {
    width: 940px;
}
```
Without specifying `width` you get nicer wrapping behavior in small windows.

Also I would add some padding-left and padding-right to this, since the text of examples and the navbar starts right at the left window edge.

Screenshot in chromium:
![2015-07-13 jq tutorial](https://cloud.githubusercontent.com/assets/1303668/8660018/54925bb8-2963-11e5-8c74-2976f4f537dd.png)

**Comment by dtolnay** [comment]
I think that part of the CSS comes from Bootstrap and the Bootswatch theme. I am not comfortable enough with CSS to fix it myself, so the fix may be to upgrade to a newer version of Bootstrap and Bootswatch.

**Comment by dtolnay** [comment]
#163 is a similar complaint.

**Comment by dtolnay** [comment]
I upgraded to the latest Bootstrap and Bootswatch and this is fixed. Please let me know if you notice any regressions.
