### ISSUE TITLE
del example not correct

### ISSUE THREAD

**Issue by syddel** [stedolan/jq#853]
The first example for `del` in the manual (documentation) is:

    jq 'del(.foo)'
    Input	[{"foo": 42, "bar": 9001, "baz": 42}]
    Output 	{"bar": 9001, "baz": 42}

This will produce an error, as the input only contains a single array (and does not specify an array key named `foo`).

To remove `foo` from the object inside the array in the above example, this could be used:

    jq 'del(.[].foo)'
    Input	[{"foo": 42, "bar": 9001, "baz": 42}]
    Output 	[{"bar": 9001, "baz": 42}]

(note the output is an array).

**Comment by dtolnay** [comment]
Thanks for reporting. The example was fixed in #475. Since then, we have added a test to automatically check every example in the manual so we will never have another release with broken examples.
