### ISSUE TITLE
No -I flag on 1.4; docs say there is

### ISSUE THREAD

**Issue by clarkgrubb** [stedolan/jq#857]
I have 1.4 on Mac.  Docs say there is an -I flag, but I'm not seeing it.

    $ jq --version
    jq-1.4
    
    $ echo '[1,2,3]' | jq -I '.'
    jq: Unknown option -I
    Use jq --help for help with command-line options,
    or see the jq documentation at http://stedolan.github.com/jq
    
    $ man jq | grep -- '-I'
           o   --online-input/-I:
    
    $ echo '[1,2,3]' | jq --online-input '.'
    jq: Unknown option --online-input
    Use jq --help for help with command-line options,
    or see the jq documentation at http://stedolan.github.com/jq

I downloaded the 1.5 release candidate, but it requires Bison 3.0, and Yosemite ships with 2.3, so bit too much effort for me.

**Comment by dtolnay** [comment]
Thanks for reporting this. This was a mistake in the man page that was released with 1.4. #866 will help with seeing command line flags for a particular version of jq, and as we discover mistakes like this we will be able to fix them more easily than a man page.

**Comment by pkoppstein** [comment]
@dtolnay wrote:
> This was a mistake in the man page that was released with 1.4.

FYPI - some of the documentation related to post-1.4 enhancements escaped into the wild, and I believe that explains the appearance of "-l" in places where it should not have been.  (The "-l" was introduced by @wtlangford for a "library" system.)

**Comment by dtolnay** [comment]
Ah that makes more sense. Thanks for clarifying that.
