### ISSUE TITLE
Sort not working right

### ISSUE THREAD

**Issue by miked63017** [stedolan/jq#860]
Grabbed the latest download for OSX and was having problems with sort, so I RTFM and saw the sort examples there. Tested one of them and it doesn't work either 

https://jqplay.org/jq?q=sort(.foo)&j=%5B%7B%22foo%22%3A4%2C%20%22bar%22%3A10%7D%2C%20%7B%22foo%22%3A3%2C%20%22bar%22%3A100%7D%2C%20%7B%22foo%22%3A2%2C%20%22bar%22%3A1%7D%5D

**Comment by miked63017** [comment]
Apparently using sort_by, which is supposed to be deprecated and just a link to sort, seems to work. Hopefully sort_by is not removed until sort is fully working

**Comment by pkoppstein** [comment]
@miked63017 - There has been some back-and-forth regarding sort/1, which unfortunately has made it somewhat difficult to match different versions of jq with different versions of the documentation.  

For your reference, the documentation at "master" currently documents sort/0 and sort_by/1; these have not changed and there is no plan to change their specification.  

The plan is for sort/1 to sort the input array by the specified comparator.

**Comment by dtolnay** [comment]
The manual no longer has the example with `sort(.foo)`. Thanks for reporting this!
