### ISSUE TITLE
Print array element if it contains

### ISSUE THREAD

**Issue by miked63017** [stedolan/jq#861]
This may already be possible but I cannot figure out how to do it, I have an array of objects and I would like to filter out the objects that dont have a key containing a certain string and display the ones that do.

```
{
  "arrayOfStuff": [
    { "key1": "lorem ipsum",
      "key2": "bler dar de"},
    { "key1": "blah blah blah",
      "key2": "der der der"},
    { "key1": "blurb blurb blurb",
      "key2": "dar dar dar"}
  ]
}
```
I would like to be able to print out elements that have a value inside key that contains ".*dar.*". I think it would be possible if I was working with numbers in the values but cannot figure out how to do a regex, and using contains just prints true or false. I would basically like to know how to get the following output

```
{ 
  "key1": "lorem ipsum",
  "key2": "bler dar de"
}
{
  "key1": "blurb blurb blurb",
  "key2": "dar dar dar"
}
```
I would picture the command looking similar to this but cannot get anything to work
```
cat JSONFile.json | jq '.arrayOfStuff | if .[].key2 =~ /.*dar.*/ then .[] end'
```

Anybody know of a way to do this?

**Comment by slapresta** [comment]
For all sort of filtering tasks, you will almost always want to use the `select` builtin; and for text matching tasks, you may want to use `contains`. A working script for your use case would be as follows:

`jq '.arrayOfStuff[] | select(.key2 | contains("dar"))' JSONFile.json`

**Comment by pkoppstein** [comment]
@miked63017 - As a footnote to @slapresta's reply, I'd add that after the release of jq 1.4, regex support has been added, as described in the online manual (http://stedolan.github.io/jq/manual) - see e.g. `test(regex)`.  There is, however, no support for `=~`.

Please also note that usage questions are often best asked at http://stackoverflow.com/questions/tagged/jq

**Comment by miked63017** [comment]
Thanks guys this was exactly what I needed.
