### ISSUE TITLE
Add 1.4 and 1.3 manuals to website

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#866]
I updated the website to show the 1.5 manual from master, since there were already a few things marked "requires 1.5". I need to generate 1.4 and 1.3 manuals and add links to them. These will be useful to people using out-of-date deb/yum repositories or stuck on old versions for some other reason.

**Comment by wtlangford** [comment]
@dtolnay I'm working on a redo of the documentation that includes
versioning and behavior changes across versions so that we don't have
issues anymore. That being said, versions on specific releases are good, too

**Comment by dtolnay** [comment]
> includes versioning

Do you mean notes like "since 1.4" next to sections of the manual? I know API docs for other languages often include this.

> behavior changes across versions

These would be more appropriate for release notes. Maybe release notes need to be featured more prominently on the website.

> redo of the documentation

Wow, what else is involved? Please let me know if you would like me to stay away from docs for a while so we avoid merge conflicts.

Anyway, I think having historic manuals is valuable. If you are stuck on 1.4, it is easier to use a 1.4 manual than to dig through a 1.5 manual where half does not apply, even if things are marked "since 1.5".

**Comment by nicowilliams** [comment]
Please push this.  Historic manuals are nice even if the 1.5 manual also
covers history.

**Comment by dtolnay** [comment]
I intend to get to this within the next week.

**Comment by dtolnay** [comment]
Easier than expected! See [dev](http://stedolan.github.io/jq/manual/), [v1.4](http://stedolan.github.io/jq/manual/v1.4/), [v1.3](http://stedolan.github.io/jq/manual/v1.3/)
