### ISSUE TITLE
Register jq for Travis CI and Coveralls

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#869]
Only @stedolan can do this!

https://travis-ci.org/
https://coveralls.io/

I have been using these on my fork, but my fork is often out of date.

Plus we get shiny badges like (from my fork) ![travis](https://travis-ci.org/dtolnay/jq.svg?branch=master) ![coveralls](https://coveralls.io/repos/dtolnay/jq/badge.svg?branch=master&service=github)

**Comment by dtolnay** [comment]
Step-by-step guide:

# Go to https://travis-ci.org/
# Click friendly green "Sign Up" button
> > > ![screenshot from 2015-07-26 21 55 47](https://cloud.githubusercontent.com/assets/1940490/8899013/aca1c016-33e3-11e5-96b8-fd5ca6088ba0.png)

# Review permissions, click "Authorize Application"
> > > ![screenshot from 2015-07-26 21 57 43](https://cloud.githubusercontent.com/assets/1940490/8899018/c8f15e70-33e3-11e5-9276-4c27840a5295.png)

# Click "+" next to "My Repositories" on the left
> > > ![screenshot from 2015-07-26 21 58 06](https://cloud.githubusercontent.com/assets/1940490/8899019/cbb748c2-33e3-11e5-96de-eb5028bd8342.png)

# Click toggle switch next to "stedolan/jq"
> > > ![screenshot from 2015-07-26 21 58 27](https://cloud.githubusercontent.com/assets/1940490/8899021/cdf4e022-33e3-11e5-8205-6a601d344a16.png)

# Toggle switch turns green! Done with Travis
> > > ![screenshot from 2015-07-26 21 58 43](https://cloud.githubusercontent.com/assets/1940490/8899054/50055754-33e4-11e5-8bad-f5ce0d15682d.png)

# Go to https://coveralls.io/
# Click ominous red "Get Started For Free"
> > > ![screenshot from 2015-07-26 21 59 26](https://cloud.githubusercontent.com/assets/1940490/8899056/52b12028-33e4-11e5-8eb6-ddc2f0123cac.png)

# Review permissions, click "Authorize Application"
> > > ![screenshot from 2015-07-26 21 59 41](https://cloud.githubusercontent.com/assets/1940490/8899057/54d4e330-33e4-11e5-9dd5-c962fd9e5edf.png)

# Click "Repos" at the top of left bar
> > > ![screenshot from 2015-07-26 21 59 50](https://cloud.githubusercontent.com/assets/1940490/8899098/dbcb0720-33e4-11e5-8ccc-9465defce444.png)

# Click "Add Repos" at the top right
> > > ![screenshot from 2015-07-26 22 00 06](https://cloud.githubusercontent.com/assets/1940490/8899101/de981222-33e4-11e5-91da-11135e0936f8.png)

# Click toggle switch next to "stedolan/jq"
> > > ![screenshot from 2015-07-26 22 00 12](https://cloud.githubusercontent.com/assets/1940490/8899102/e08da574-33e4-11e5-9e62-75e91d8bbeef.png)

# Toggle switch turns green! Done!
> > > ![screenshot from 2015-07-26 22 00 15](https://cloud.githubusercontent.com/assets/1940490/8899103/e2473a88-33e4-11e5-8a73-a2fe3224cba7.png)

**Comment by stedolan** [comment]
Done! (finally >_>)
