### ISSUE TITLE
`inputs` filter drops first element with `--stream`

### ISSUE THREAD

**Issue by slapresta** [stedolan/jq#874]
Maybe I am misunderstanding `inputs` or `--stream`, but I get the feeling this isn't supposed to happen? The entry for `.results[0].foo` is missing when you use `inputs` with `--stream`.

```
ᐷ cat test.json 
{
"results": [
{"foo": 1, "bar": 2},
{"foo": 2, "bar": 7},
{"foo": 3, "bar": 5}
]
}
```

Expected:

```
ᐷ jq --stream -s 'length' test.json
11
```

Actual:

```                                                                          
ᐷ jq --stream '[inputs] | length' test.json
10
```

**Comment by nicowilliams** [comment]
Whether you use `--stream` or not you need to use `-n` (usually) when you use `inputs`.  If you try it I think you'll see it works as expected.

**Comment by nicowilliams** [comment]
$ jq -cn --stream '[inputs] | length' test.json
    11
    $

**Comment by nicowilliams** [comment]
BTW, FYI, this has bitten me too :) so I'm tempted to make `inputs` fail unless `-n` was given...  But one might want to be able to interleave reading from `stdin` between the jq program and the jq executable's input loop, no?

**Comment by slapresta** [comment]
Care explaining why you need `-n`? It is not obvious to me...

**Comment by wtlangford** [comment]
At a guess, without looking, inputs just keeps talking the next input. If
you don't use -n, the first was already consumed as the jq program's
initial input. -n prevents that and you get the intended behavior.

**Comment by nicowilliams** [comment]
Every jq expression/program needs an input value.  The jq executable reads
values from stdinn or named files and passes those as  `.` to the top-level
jq program, except when you use the -n option.  When you use the -n option
the jq executable does not read from stdin or any files and instead runs
the top-level program with a single input value: null.

**Comment by nicowilliams** [comment]
Running `jq --stream '[., inputs] | length]'` will also do what you want, and might make this more explicit.

One reasonably expects that `inputs` will produce _all_ inputs, but jq itself will consume at least one if given a chance, and that's what `-n` prevents.
