### ISSUE TITLE
Opposite of --slurp

### ISSUE THREAD

**Issue by stanch** [stedolan/jq#878]
Given the input
```json
[
  { "foo": "bar" },
  { "foo": "baz" }
]
```
it would be nice to have an option to dispense with the outer array (kind of the opposite of `--slurp`).
So instead of
```
jq '.[].foo' input
```
we could write
```
jq --chew '.foo' input

**Comment by nicowilliams** [comment]
In jq-1.5rc2 you can do this:

    $ jq -n '[{foo:"bar"},{foo:"baz"}]' | jq -cn --stream 'fromstream(1|truncate_stream(inputs))'
    {"foo":"bar"}
    {"foo":"baz"}
    $

**Comment by nicowilliams** [comment]
This allows you to process a single, huge, monolithic JSON text incrementally.  You could, for example, look for a needle in the stack by matching the outputs of `inputs` in `--stream` mode, looking for paths and/or values that are the needle, and produce results (and/or quit) as soon as possible, without waiting for the end of the JSON text, or having to build up a huge in-memory representation of it.

**Comment by nicowilliams** [comment]
This replaces the `--online-input` option that jq had in master (never shipped) for a while.

**Comment by nicowilliams** [comment]
@stanch can you confirm that this works for you?

**Comment by stanch** [comment]
My goal was more conciseness/readability than performance. Many tools output a top-level array instead of one-JSON-object-per-line (for example, `docker inspect`). So I thought a short option for parsing this kind of input would be nice. Regarding your example, I think `jq '.[].foo'` is more readable in its original form, so I’d rather stick to that than do `-cn --stream ...`

**Comment by nicowilliams** [comment]
Since `.[]...` works for you, there's no need to add `--unslurp`, and we prefer to not add options if we can avoid it.  (`--stream` couldn't be done otherwise.)

**Comment by stanch** [comment]
Fair enough :)

**Comment by nicowilliams** [comment]
In fact, now that we have `inputs` I think we ought to obsolete `-s`/`--slurp`!  That can now be written as `jq -n '[inputs]'`.

:)

**Comment by dtolnay** [comment]
I agree!

**Comment by nicowilliams** [comment]
If you'd like we could note that in the release notes and manual for 1.5...

**Comment by nicowilliams** [comment]
@stedolan has expressed a desire to a) keep a lid on new command-line options, b) add language features that make it possible to jq-code what are now command-line options.  Quite a few options can be jq-coded:

 - `--tab`, `--indent`, `-j`, `-a`, `-c`, `-C`, `-M`, `-S`, and `-R` could all be implemented in a builtin interface to the JSON encoder, with jq itself always in raw-output mode or with the jq-coded encoder invoking a builtin to output to stdout.  Yes, I'm guilty of adding some of these options :(
 - `-h` could just be a function named `help` :)
 - `-n` could just be how it *always* is, with jq programs having to read from `stdin` using `input` and `inputs`.
 - `-s` can be `[inputs] | `
 - `--seq`, `--stream`, and the normal input mode could have been implemented as a builtin interface to the parser and having jq always in raw-input mode.
 - `-V` could be a function named `version` :)
 - `-e` should always be on.
 - `--argfile` and `--slurpfile` could have been builtins or use `import` (which can import data).
 - `--argjson` could just be how all surplus arguments are handled (collected and bound to `$ARGS`), with a builtin for reading files.
 - `--arg` could just not have been.

That leaves just these options:

 - `-f`
 - `--unbuffered`
 - `--debug-dump-disasm` and `--debug-trace`
 - `--run-tests`

And even these could be implemented as builtins!

A `main()` with much, much less argument parsing would be nice.

But perhaps this would all also be a larger cognitive burden on users.  So we should be careful about removing options even if backwards incompatibility did not bother us.  But we should strive to make the jq language and its builtins as powerful as possible so that we can avoid adding more options.

**Comment by pkoppstein** [comment]
> I think we ought to obsolete -s

I can't speak for @stedolan but I will say that there is a wonderful simplicity to 'jq -s' or even 'jq -s .' compared to 'jq -n '[inputs]', which for most would require digging through the documentation, and for some, it will mean perplexity when they try `jq '[inputs]`. By contrast, using -s requires no more than browsing 'jq -h'.

Plus there is a ton of stuff out there about how "-s" is available.  You can change the documentation but not all those helpful postings.

Another consideration is that existing jq users may already have built 'jq -s' into their pipelines. Certainly, many have it well embedded in their brains. 

I don't mean to sound overly curmudgeonly, but in this case, I just don't see the great need to force this change on everyone.  After all, we're well past jq-beta.  At the very least, I think feedback from the community should be sought.

**Comment by nicowilliams** [comment]
Eh, there's no danger of impending obsolescence for any options.  My impression is that even if jq were thus from day zero, many of these options are easier on users than the alternatives, and your comments tend to confirm that (certainly now that we're far from day zero).

**Comment by nicowilliams** [comment]
I should add that @stedolan hasn't, IIRC, made any noise about removing options, and I do think we should add builtins that would allow us to remove options if we wanted to even if we never do.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> I should add that @stedolan hasn't, IIRC, made any noise about removing options

But he has been completely silent on all things jq recently, hasn't he?  In any case, my impression is that there's been general agreement that the main objective should be to avoid adding options.

> and I do think we should add builtins 

Absolutely.

Please also note that my curmudgeonly comments were focused exclusively on `-s`; although some of the considerations would obviously apply to other options, I think we should consider any proposal to remove an option strictly on the merits.  

Speaking of which --- if -e were to become the default, would there be any real need (other than backward-compatibility) for an option to revert to the prior behavior?  Is this something that should be considered for jq 1.5?

**Comment by joelpurra** [comment]
@nicowilliams, @pkoppstein: I've been meaning to refer to my proposed solution regarding backwards compatibility: #558 [Use semantic versioning for jq releases](https://github.com/stedolan/jq/issues/558).

Breaking changes can and should be introduced to further jq's usefulness, but should only be introduced when incrementing the major version. But then keep in mind that the major version isn't holy -- it's just a flag for breaking changes -- so don't be afraid to use it.

It's easy enough to keep different branches for v1.x.x and v2.y.y or vNext. Those who stick with an older major version can still have non-breaking features backported, given enough interest from both users and maintainers.

**Comment by stanch** [comment]
As someone who uses `-r`, `-c`, `-C`, and `-M` on a regular basis, I would argue that since they deal with the representation/formatting, rather than the data transformation itself, it’s better to keep them as flags. Besides being semantically pleasing, this approach has an advantage of simplifying the creation of aliases that format the output in a certain way. The same goes for `--tab`, `--indent` & co.

On the other hand, I think it makes sense to use built-ins instead of the flags that can be seen as performing `JSON → JSON` (or `JSON-stream → JSON`, etc) transformations, like `-s`. My only concern here would be that those build-ins should not take hours to type ;)

**Comment by nicowilliams** [comment]
Yes, perhaps as should add a builtin named `unslurp` that does what I posted above....

**Comment by nicowilliams** [comment]
@pkoppstein We'll do nothing about `-e` in 1.5.  Except maybe warn that it will become the default in a future release.

**Comment by nicowilliams** [comment]
@joelpurra We'll never have a version of jq that implements multiple incompatible versions of jq in one executable, unless those incompatibilities are only about jq-coded builtins.  It would be ETOOHARD to have multiple parsers (syntaxes) or compilers (semantics) in one executable.  Which means that versioning arguments to the executable would at best help cause failure earlier.

It will be much easier to just avoid backwards-incompatible changes altogether.  And that's exactly what we've been doing and will continue to do.  If we're obliged to make them, we'll provide ample warning and minimize them as much as possible.

Providing builtin equivalents to all the command-line options would be extremely useful for FFI bindings to libjq (think of the Python bindings), so we should do it, though obviously not for 1.5.

**Comment by joelpurra** [comment]
@nicowilliams wrote:
> @joelpurra We'll never have a version of jq that implements multiple incompatible versions of jq in one executable

Never said anything about multiple versions in the same executable. Not sure where you got that from.

**Comment by nicowilliams** [comment]
@joelpurra Right, but semantic version for the jq executable means only that if you tell it what version you wanted and it's not compatible, then it will fail sooner (and safer, which is nice) -- if it supported multiple incompatible versions then it could switch/select between them.  But semantic versioning belongs in the package system, not the executables themselves.

**Comment by joelpurra** [comment]
@nicowilliams: I see potential in both preventing jq script execution in an incompatible jq version, as well as dynamically selecting the best jq version for the job. This is why I have suggested an `engines` hash/object with semver ranges in jqnpm -- but dynamic jq executable/library selection hasn't actually been implemented yet. It kind of depends on jq actually following the semver standard though.

**Comment by nicowilliams** [comment]
@joelpurra jq does, but it omits the micro version number, because we don't need it.  The 1 in 1.4 is a major number, and the 4 is a minor number.  We're not going to write 1.5.0rc2, sorry.  It's 1.5rc2, and the release will be 1.5.

**Comment by joelpurra** [comment]
@nicowilliams: yes -- but it's a shame that jq it seems to prevent jq from having bugfix releases.

**Comment by nicowilliams** [comment]
When we need a micro release we'll consider having one.  There's no need to say .0 in the meantime.

**Comment by nicowilliams** [comment]
We aim not to have breaking changes in minor releases, since that's what major releases are for.  Cases were the semantics being broken were not documented may have breaking changes, but we'll have some sturm und drang first.

**Comment by nicowilliams** [comment]
And if distros wish to add a 0 micro (patch, whatever) version number, because they're forced to by their packaging technology, that's fine.
