### ISSUE TITLE
limit is not defined

### ISSUE THREAD

**Issue by abraham** [stedolan/jq#880]
[limit](https://stedolan.github.io/jq/manual/#limitnexp) is throwing an error locally with `jq-1.4` and on [jqplay](https://jqplay.org/jq?q=%5Blimit(3%3B.%5B%5D)%5D&j=%5B0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%5D).

> error: limit is not defined
> [limit(3;.[])] 1 compile error

**Comment by wtlangford** [comment]
limit leaked out into the docs a bit too soon.  It's a feature to be in
1.5, so can currently be found in master and 1.5rc2.

**Comment by abraham** [comment]
:+1:

**Comment by dtolnay** [comment]
The manual you linked to is for jq 1.5. The one for 1.4 is at http://stedolan.github.io/jq/manual/v1.4/ and does not mention limit.
