### ISSUE TITLE
PGP signature for released binaries

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#889]
Originally requested by @JensRantil in #726.

See https://github.com/tabulapdf/tabula/releases/tag/v1.0.0 for an example of signing binaries.

**Comment by else** [comment]
:+1: 

Would like to have this for the Debian packaging.

**Comment by Origa7jeffrey** [comment]
@@ -1,20 +1 @@
<?xml version="1.0" encoding="UTF-8"?>
<svg width="1200px" height="1200px" viewBox="0 0 1200 1200" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>icon-square-big</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Icon" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="icon-square-big">
            <g id="cube" transform="translate(163.000000, 106.000000)">
                <polygon id="border" fill="#FFFFFF" points="386.995555 0 773.991111 218.926312 773.991111 656.778936 224.24811909 875.705248 3.88630819e-13 656.778936 1.4029432e-13 218.926312"></polygon>
                <g stroke-width="1" transform="translate(47.000000, 61.000000)">
                    <g>
                        <path d="M657.873333,580.673665 L352.774704,753.270266 L352.774704,618.855754 L542.907274,514.29798 L657.873333,580.673665 Z M678.756393,561.792596 L678.756393,200.879411 L567.118828,265.333389 L567.118828,485.143908 L567.118828,497.338618 L678.756393,561.792596 Z M20.8830605,580.673665 L325.981689,753.270266 L325.981689,618.855754 L135.849119,514.29798 L20.8830605,580.673665 Z M1.80262051e-13,561.792596 L-2.44367716e-14,200.879411 L111.637565,265.333389 L111.637565,485.143908 L111.637565,497.338618 L2.0250468e-13,561.792596 Z M13.0709342,177.488009 L325.981689,0.472029449 L325.981689,130.421685 L125.518524,240.660464 L123.966818,241.513778 L13.0709342,177.488009 Z M665.685459,177.488009 L352.774704,0.472029449 L352.774704,130.421685 L553.237869,240.660464 L554.789575,241.513778 L665.685459,177.488009 Z" id="outer-cube" fill="#8ED6FB"></path>
                        <path d="M325.981689,588.282084 L138.43058,485.143908 L138.43058,280.802344 L325.981689,389.085027 L325.981689,588.282084 Z M352.774704,588.282084 L540.325813,485.143908 L540.325813,280.802344 L352.774704,389.085027 L352.774704,588.282084 Z M339.403391,381.336004 L339.378197,381.292365 L339.353002,381.336004 L339.403391,381.336004 Z M151.088673,257.172588 L339.378197,153.628343 L527.66772,257.172588 L339.378197,365.881595 L151.088673,257.172588 Z" id="inner-cube" fill="#1C78C0"></path>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg> 
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 1200"><title>icon-square-big</title><path fill="#FFF" d="M600 0l530.3 300v600L600 1200 69.7 900V300z"/><path fill="#8ED6FB" class="st1" d="M1035.6 879.3l-418.1 236.5V931.6L878 788.3l157.6 91zm28.6-25.9V358.8l-153 88.3V765l153 88.4zm-901.5 25.9l418.1 236.5V931.6L320.3 788.3l-157.6 91zm-28.6-25.9V358.8l153 88.3V765l-153 88.4zM152 326.8L580.8 84.2v178.1L306.1 413.4l-2.1 1.2-152-87.8zm894.3 0L617.5 84.2v178.1l274.7 151.1 2.1 1.2 152-87.8z"/><path fill="#1C78C0" d="M580.8 889.7l-257-141.3v-280l257 148.4v272.9zm36.7 0l257-141.3v-280l-257 148.4v272.9zm-18.3-283.6zM341.2 436l258-141.9 258 141.9-258 149-258-149z"/></svg>
