### ISSUE TITLE
Please, restore the old release

### ISSUE THREAD

**Issue by nikolay** [stedolan/jq#890]
The binary https://stedolan.github.io/jq/download/linux64/jq is gone and I have an elastic farm failing, because this file is now gone. Because AWS Autoscaling Groups cannot easily change user scripts, this little issue is, in fact, a huge one for me.

Is it possible to bring it back at least temporarily?

**Comment by dtolnay** [comment]
I have restored that one binary temporarily. Is your script using `curl -L` or `wget` or similar that would follow 301 response codes? We moved the release binaries out of git and into GitHub releases to reduce the size of the git repo significantly, but we can add 301 redirects at the old URLs.

Sorry for breaking your elastic farm. This is my fault for not considering the repercussions of moving these.

**Comment by dtolnay** [comment]
Never mind, it looks like GitHub does not support htaccess or any other way of setting 301 redirects. Please update your AWS script at your convenience to point to https://github.com/stedolan/jq/releases/download/jq-1.4/jq-linux-x86_64 and then leave a comment here.

**Comment by nikolay** [comment]
I'm sure this does not affect only me. You shouldn't remove advertised binaries without deprecation notice and allowing people to plan for things. Deleting on Saturday is a great way to ruin somebody's weekend, honestly. I appreciate your great work, but a slightly bigger repo is nothing compared to breaking stuff.

**Comment by nikolay** [comment]
Thanks for restoring this! I'm sure others will appreciate the gesture as well. Have a great weekend and thanks for the gesture!

**Comment by nicowilliams** [comment]
It's really quite interesting to see that users are doing what you're doing.  I can understand this completely.  We'll be more careful in the future.  I'll see if there's any way to ask github to add redirect support.  It's a bit too late now obviously, but it might come in handy again later or for other repos.

**Comment by nikolay** [comment]
Well, then maybe you don't have experience with Amazon AWS and their best practice, i.e. using CloudFormation with Autoscaling Groups. I install jq in the user data script as I use it to query AWS CLI responses. Yes, I can update the user data scripts, but sometimes CloudFormation does more change than it's supposed to do (especially when you change the user data in the Launch Configuration) and it's not something people will rush to do in Production for no solid reason.

Anyawy, just imagine how many blog posts and scripts will be out there using the advertised location for the binary. Chef Cookbooks, Ansible Playbooks, SaltStack, Puppet, etc. This is not just a binary, it's contract. And you don't change these lightly.

**Comment by nicowilliams** [comment]
@nikolay 

We have restored that URL.  But note that it takes two to tango -- there are two sides to a contract, and since we never indicated that the download URLs are stable interfaces, or interfaces at all, and no one told us that they depended on them to be stable, we couldn't have known that this change would break your scripts.  Non-interfaces require care to use.  In the future I think we can rely on github releases having stable URLs, so do please change your scripts and hopefully you won't have to again (except to upgrade to a newer jq release).
