### ISSUE TITLE
Recursively sorting nested arrays

### ISSUE THREAD

**Issue by slapresta** [stedolan/jq#893]
(Context: http://stackoverflow.com/questions/31930041/using-jq-or-alternative-command-line-tools-to-diff-json-files)

I'm trying to sort arrays recursively inside objects so as to compare those objects regardless of the ordering of the elements of their arrays. My naïve attempt was to `(.. | arrays) |= sort` every input object. However, this doesn't work as expected; if an array contains arrays, then sorting the inner arrays may alter their expected ordering in the outer array. Since the sorting is done on the outer array first, the result is not actually sorted. Consider this sample:

```
ᐷ jq -c -n '[[4, 1, 7], [8, 5, 2], [3, 6, 9]] | (.. | arrays) |= sort'
[[3,6,9],[1,4,7],[2,5,8]]
```

Is there any way to recurse an object from the inside out, or to reverse the recursion stream?

**Comment by nicowilliams** [comment]
Right, `recurse` and friends (`..` is an alias for `recurse/0`) are pre-order tree traversals.  You probably want a post-order tree traversal.

This should work:

    def post_recurse(f): def r: (f|select(.!=null)|r), .; r;
    def post_recurse: post_recurse(.[]?);
    (post_recurse|arrays)|=sort

You can even cause `..` to behave this way by defining your own `recurse/0`, but there's no guarantee that that will be permitted in the future.

**Comment by pkoppstein** [comment]
The generic function "walk/1" can be used to do what you want:
```
# Apply f to composite entities recursively, and to atoms
def walk(f):
  . as $in
  | if type == "object" then
      reduce keys[] as $key
        ( {}; . + { ($key):  ($in[$key] | walk(f)) } ) | f
  elif type == "array" then map( walk(f) ) | f
  else f
  end;
```
```
[[4, 1, 7], [8, 5, 2], [3, 6, 9]] | walk(if type == "array" then sort else . end)
```
produces
```
[[1,4,7],[2,5,8],[3,6,9]]
```

walk/1 is actually pretty powerful and quite useful ... a candidate perhaps for builtin.c?

**Comment by slapresta** [comment]
Thank you both! I updated the issue with a working solution.

@pkoppstein `walk` seems indeed pretty useful. I would love it if it was part of the builtins.

**Comment by nicowilliams** [comment]
Open a separate issue for `walk`.  It will not be in 1.5, of course.

**Comment by nicowilliams** [comment]
The post-order recursors may be useful in 1.6 as well.

**Comment by pkoppstein** [comment]
PR: https://github.com/stedolan/jq/pull/895
