### ISSUE TITLE
jv_sort: Assertion `jv_get_kind(objects) == JV_KIND_ARRAY' failed.

### ISSUE THREAD

**Issue by DRMacIver** [stedolan/jq#901]
One more AFL bug:

The following command triggers an assertion:

```
jq -n '[]as$p|getpath($p),setpath($p;0),delpaths(null)'
```

Output:

```
null
0
jq: jv_aux.c:553: jv_sort: Assertion `jv_get_kind(objects) == JV_KIND_ARRAY' failed.
Aborted
```

This was tested running against 3ef92863f2e66dcac54073df44db3a77556be204

**Comment by dtolnay** [comment]
This is great. Keep them coming.

    jq -n 'delpaths(null)'

**Comment by DRMacIver** [comment]
I suspect I might be at the limit of what the current method is going to find without some serious server time (right now this is just running on my laptop), as that was the only bug that came up from running overnight. Will of course let you know if anything else turns up though.
