### ISSUE TITLE
header fields ordered & colored by it's category defined by rfc2616

### ISSUE THREAD

**Issue by Mudox** [stedolan/jq#903]
As per rfc2616 section 4.2:

> The order in which header fields with differing field names are received is not significant. However, it is “good practice” to send general-header fields first, followed by request-header or response-header fields, and ending with the entity-header fields.

Can jq provide a switch to order & color the header fields by their categories. I think it would be a little feature for those HTTP protocol learners to distinguish different kind of headers at a glance.

**Comment by nicowilliams** [comment]
jq does not speak HTTP.  One could jq-code parsers and encoders for any text-oriented protocols' formats, so in a sense, there's nothing to do here.  Even colorization could be jq-coded if jq had a `isatty` or `$isatty` builtin...

**Comment by Mudox** [comment]
My bad, I mistakenly put the issue in the wrong page. I was putting it on [httpie](https://github.com/jkbrzt/httpie)
