### ISSUE TITLE
documentation on streaming

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#904]
From the "development" version of the jq manual:

> The examples below use the the streamed form of [0,[1]], which is [[0],1],[[1,0],2],[[1,0]],[[1]])].

There's a spurious ")" in the line above, but that line doesn't make much sense anyway.  Fortunately, jq says:
```
$ jq -nc '[0,[1]] | tostream'
[[0],0]
[[1,0],1]
[[1,0]]
[[1]]
```

**Comment by nicowilliams** [comment]
Thanks!

**Comment by pkoppstein** [comment]
@nicowilliams - Now that that's cleared up, I'd like to point out that the following example is a tiny bit confusing because of the redundancy of the "1":
```
          - program: '[1|truncate_stream([[0],1],[[1,0],2],[[1,0]],[[1]])]'
            input: '1'
            output: ['[[[0],2],[[0]]]']
```
A better way to present this example would be as follows: 
```
          - program: '[truncate_stream([[0],1],[[1,0],2],[[1,0]],[[1]])]'
            input: '1'
            output: ['[[[0],2],[[0]]]']
```

But feel free to choose an even better way :-)
