### ISSUE TITLE
Support non-object module/import metadata

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#906]
Non-object metadata should be put into an object with the key "metadata". So these should be equivalent:

    include "awesome" 2.0;
    include "awesome" {"metadata": 2.0};

**Comment by pkoppstein** [comment]
I don't mean to throw a spanner into the works (especially with respect to finishing 1.5), but why is the Exp part of `"include" String Exp ';'` needed at all?  It seems to me that the metadata associated with a module should be defined by the module, not by the "include" statement required to include (or import) it.

The same consideration also applies to the Exp part of `"import" String "as" IDENT Exp ';'`.

If support for the Exp part of include and/or import is dropped now, then that should simplify things w.r.t. 1,5; and if it turns out later that there is some reason to include it, it can be added later.

Sorry if I'm missing something.

**Comment by nicowilliams** [comment]
@pkoppstein It's metadata about what the importer wants.  So that a pkg system inspecting a module to find missing dependencies can find out where to look for them.  For example.

**Comment by nicowilliams** [comment]
If we should reconsider anything it's whether to use *paths*.  Ideally dependencies should be named by URI, and the process of resolving those into local files should be hidden.  It's a bit late for that for 1.5, and we can always add that in later.

**Comment by nicowilliams** [comment]
In fact, if anything, I rue having dropped `import SYMBOL ...;` and gone with `import STRING ...;` instead.

**Comment by nicowilliams** [comment]
Also, @pkoppstein, with 1.5 coming this weekend, what we need from you is to know whether there's something missing w.r.t. the module system that can't be added later.  Like the package universe thing.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> It's metadata about what the importer wants.

OK, but shouldn't this be postponed until the form of some matching rules has been established?  What does `include "awesome" 2.0` mean in jq 1.5? If it is equivalent to `include "awesome" {"metadata": 2.0}`, how will we distinguish between 'require version 2.0 or greater', 'require version 2.0 exactly', 'require version x where 2.0 <= x < 3.01', and so on?

Regarding the module system in general --- if you rue something as fundamental as adopting "import STRING ...." then I wonder whether we shouldn't either (a) declare the whole module system to be experimental and therefore subject to change; or (b) more carefully define in the documentation what is fixed and what isn't.

(For example, currently one can `def foo::bar: 1;` anywhere, but (as I recall) it's not clear whether this is an accident or a feature.  Similarly, if module foo defines bar, will foo::bar always be valid outside foo?)

**Comment by nicowilliams** [comment]
No, because it's useful *now* to external pkg managers.

**Comment by nicowilliams** [comment]
Being able to `def foo::bar: ...;` is an undocumented accident.  It may yet be a happy one, but it shouldn't be documented as we might want do forbid it later, though honestly, I don't see the harm.  As for what's valid where, the symbol resolution rules are quite simple: each expression can only see bindings established by previous expressions and defs (and ones imported), with the most recent one (from back to front) being the one that's seen when there's multiple bindings for one name.  The only exception is that references to functions are bound preferentially to the defining function (to enable recursion).

**Comment by nicowilliams** [comment]
As for `import IDENT ...;` vs `import STRING ...;`, we can always add alternatives later and make it that importing a path means importing from manually-installed modules, while importing in an alternative way means importing from a repository of modules that cannot be managed as manually.  So I'm not too upset about it.

It's time to ship 1.5.

**Comment by nicowilliams** [comment]
One nice thing about `import SYMBOL ...;` was that it automatically prevented parent directory traversal.  There were other benefits.  The main benefit of `import STRING ...;` is that external package managers have slightly less work to do (no need to `s,::,/,g`).

**Comment by nicowilliams** [comment]
@pkoppstein I hate the idea of marking such an important feature experimental.  I might want to add some verbiage to the manual about things that may change later.  We'll see.  And yes, I've been mulling changing it back to `import SYMBOL ...;`, but I think @dtolnay would just be greatly annoyed :)  It's time to ship 1.5.  So, dinner, cherry-pick a bunch of docs/site commits, build, release, file a PR against Homebrew.
