### ISSUE TITLE
Canonical URL and redirect to https site

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#908]
See https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by nicowilliams** [comment]
Oh right, we have all of these references to the http location:

    README.md:[http://stedolan.github.io/jq](http://stedolan.github.io/jq).  This
    configure.ac:             [jq], [http://stedolan.github.io/jq])
    docs/default_manpage.md:    http://stedolan.github.io/jq
    docs/site.yml::url: http://stedolan.github.io/jq
    jq.spec:URL: http://stedolan.github.io/jq
    main.c:    "\tand/or http://stedolan.github.io/jq\n\n"
    main.c:  fprintf(stderr, "or see the jq manpage, or online docs  at http://stedolan.github.io/jq\n");

**Comment by dtolnay** [comment]
I intend to take care of this tonight or tomorrow. One thing I can't fix is the link at the top of [this page](https://github.com/stedolan/jq). Time to get @stedolan's attention.

**Comment by nicowilliams** [comment]
We could open an issue against OCaml...

**Comment by dtolnay** [comment]
Well it is not really important, especially if we do a javascript redirect to https.

#869 we could open against OCaml.

**Comment by nicowilliams** [comment]
Yeah, #869 would be nice to get fixed.

**Comment by dtolnay** [comment]
Site now redirects to https. I will keep an eye on when Google notices the "canonical" link and starts linking to https.

**Comment by nicowilliams** [comment]
I'll probably cherry-pick all the docs and site changes into the 1.5 branch.  Any objections?

**Comment by dtolnay** [comment]
The only ones worth cherry-picking are c426d49 and a5b2c55. Nothing else affects the manpage. I suppose they affect people who download the 1.5 source and do `rake serve`, but we are never going to update gh-pages from the 1.5 tag, only from master.

**Comment by dtolnay** [comment]
Also dea7868 if you have the patience, but make sure not to get any of the walk/1 stuff.

**Comment by nicowilliams** [comment]
@dtolnay have you any opinion as to `import STRING...;` vs `SYMBOL`?

**Comment by dtolnay** [comment]
C, Go, and Ruby use strings. Java, Python, and D use symbols. I don't have a strong preference but I think strings are fine for an initial attempt.

**Comment by dtolnay** [comment]
Personally I would have gone with these:

    import awesome;
    import awesome as ax;
    static import awesome;

Where static import replaces what we called "include". D uses "static import" while Java uses "import static" and I have a slight preference for the former.

But I was a bit late to the party.

**Comment by nicowilliams** [comment]
Don't we need to the site updates to generate the 1.5 manual?  I'll just pick them.

**Comment by dtolnay** [comment]
No I will just copy master's 3.manual/manual.yml to 3.manual/v1.5/manual.yml.

**Comment by nicowilliams** [comment]
OK, thanks.

**Comment by dtolnay** [comment]
Great, Google is now linking to https.
