### ISSUE TITLE
Website updates for 1.5

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#910]
- Index page dropdown
- Index page news
- Download page binary links
- Download page move `--disable-maintainer-mode` into main build steps
- Copy the manual

**Comment by dtolnay** [comment]
Also some non-website updates.

- Add checksums to sha1sum.txt
- Update NEWS file

**Comment by dtolnay** [comment]
Can you think of any backward-incompatible changes that are worth calling out in the release notes?

**Comment by nicowilliams** [comment]
Habemus 1.5.  See also https://github.com/Homebrew/homebrew/pull/42988.

**Comment by nicowilliams** [comment]
Good night!

**Comment by dtolnay** [comment]
Great, I will take care of the website.

**Comment by nicowilliams** [comment]
@dtolnay Can I leave turning the crank on gh-pages to you?  I'm off on another longish trip.  Two weeks this time.  Thanks!

**Comment by nicowilliams** [comment]
I can't think of any backwards-incompatible changes to documented
functionality.

**Comment by nicowilliams** [comment]
Thanks for updating the website!
