### ISSUE TITLE
Win32 build is broken, needs to find PathIsRelativeA()

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#911]
`linker.c` needs to include `<windows.h>` and `<shlwapi.h>`, and jq needs to link with `-lshlwapi` when building with mingw.  I'm not sure if the latter is something we should do unconditionally in `configure.ac`, so I'll not fix that (instead we can point out the need to add it to `LDFLAGS` in the ./configure incantation).

**Comment by dtolnay** [comment]
Why would we not want to link with `-lshlwapi` unconditionally (on mingw, anyway)?

**Comment by nicowilliams** [comment]
Ah yes, I'd be matching on the host triple, so yes, it should be unconditional in the mingw case.

**Comment by svnpenn** [comment]
For any dummies out there, that means you need to do this to fix it:

    make clean
    make LDFLAGS=-lshlwapi

**Comment by JanSchulz** [comment]
Seems that the `make LDFLAGS=...` is still needed: #1074

With that, I get:
```
  CC       src/linker.lo
src/linker.c: In function 'path_is_relative':
src/linker.c:32:13: warning: implicit declaration of function 'PathIsRelativeA' [-Wimplicit-function-declaration]
   int res = PathIsRelativeA(s);
             ^
```

Only a warning, but...

**Comment by JanSchulz** [comment]
And on 32bit it it still sfails even with that: https://github.com/stedolan/jq/pull/1075#issuecomment-172264537

```
CC       src/jv_file.lo
  CC       src/jv_parse.lo
  CC       src/jv_print.lo
  CC       src/jv_unicode.lo
  CC       src/linker.lo
src/linker.c: In function 'path_is_relative':
src/linker.c:32:13: warning: implicit declaration of function 'PathIsRelativeA' [-Wimplicit-function-declaration]
   int res = PathIsRelativeA(s);
             ^
  CC       src/locfile.lo
  CC       src/util.lo
  CC       src/lexer.lo
  CC       src/parser.lo
  CCLD     libjq.la
libtool: warning: undefined symbols not allowed in x86_64-pc-mingw32 shared libraries; building static only
  CC       src/main.o
  CCLD     jq.exe
./.libs/libjq.a(linker.o): In function `path_is_relative':
C:\projects\jq/src/linker.c:32: undefined reference to `PathIsRelativeA'
collect2.exe: error: ld returned 1 exit status
Makefile:893: recipe for target 'jq.exe' failed
make[1]: *** [jq.exe] Error 1
make[1]: Leaving directory '/c/projects/jq'
Makefile:734: recipe for target 'all' failed
```

**Comment by nicowilliams** [comment]
Checking for the header seems better than making this conditional on mingw.
