### ISSUE TITLE
Build OS X binaries for jq 1.5

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#912]
They are missing from https://github.com/stedolan/jq/releases/tag/jq-1.5

**Comment by nicowilliams** [comment]
Oh, I was going to count on Homebrew.  Hold on.

**Comment by dtolnay** [comment]
Okay then. I don't use OS X so I don't know how comfortable people are with Homebrew for something like this.

**Comment by nicowilliams** [comment]
OS X amd64 executable added.

**Comment by dtolnay** [comment]
@nicowilliams don't forget to fix Homebrew/homebrew#42988.

**Comment by nicowilliams** [comment]
Good point.  Update pushed.
