### ISSUE TITLE
getpath/setpath undocumented?

### ISSUE THREAD

**Issue by jcreedcmu** [stedolan/jq#914]
I don't know if this is intentional because they're deprecated or something. (I note that https://github.com/stedolan/jq/commit/9af03c2 exists which removed a use of `getpath` from the docs)

If there's another convenient way of achieving the same effect of these functions, I would be interested in knowing.

**Comment by nicowilliams** [comment]
There's no reason not to have getpath and setpath be supported public
interfaces.

**Comment by jcreedcmu** [comment]
In that case I'd like to suggest including some kind of "see also" reference to them from the description of `paths()`, since that was the point at which I wondered how to invert the computation that `paths()` does --- the only reason I found `getpath` at all is that `setpath` was mentioned in the FAQ on the jq wiki and then I started looking at the source.

**Comment by nicowilliams** [comment]
Documented in `master` now with b6e3657.
