### ISSUE TITLE
Portable C

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#915]
The website touts "portable C". We need to clarify how we interpret this. jq compiles with `-std=gnu99 -Wpedantic` (after fixing 73b9e8d, eb2fc1d, and ec7c3cf) but not `-std=c99` or `-std=c11` because of the use of `strdup` and `fileno`. Is it worth reworking these to support `-std=c99`?

**Comment by wtlangford** [comment]
Reworking for `fileno` is going to be a bit more difficult, I believe, since it is a POSIX extension.  That said, I thought we had a strdup replacement in the codebase already?

If we're going to work towards "portable C" or at least c99, should we also check for any gcc-specific extensions we're using?  I think we have `__attribute__((constructor))` in there somewhere. (I think I found that it was actually unused?)

**Comment by nicowilliams** [comment]
It's portable, but given the use of #ifdefs for WIN32 it's like ported than
portable.  I'm not as all concerned about supporting C99 unless the effort
needed is minimal.  We should take a PR for it if it was acceptable, but
I'd not put a lot of effort into it myself.

**Comment by dtolnay** [comment]
Makes sense.

**Comment by nicowilliams** [comment]
`fileno()` is a POSIX interface, no?  http://pubs.opengroup.org/onlinepubs/9699919799/functions/fileno.html

Anyways, we could autoconf detect support for `fileno()` and not automatically adjust to tty/not-a-tty cases when `fileno()` is not available.  But where is `fileno()` not available?  It's even available on Windows.

As for C99 vs C11... at some point I'd like to have an option to build an MT-safe libjq that uses atomic refcount increment/decrement operations, and I'll probably want to have an option to use C11 atomics (though using an atomic library for C99 would work too).  Finally, it'd be nice to be able to use various C extensions to make function cleanup easier, but we can probably hold off on that.  (I'm thinking of two things to make dealing with string jv's easier.  One is a macro that `jv_free()`s `jv`s after using them, but that would not feel very C-ish.  The other is using an array to collect references to `jv`s and then releasing just the array.)
