### ISSUE TITLE
FreeBSD instructions

### ISSUE THREAD

**Issue by thompsa** [stedolan/jq#917]
jq is simple to install on FreeBSD, entry for downloads page.

### FreeBSD
* Install [textproc/jq](http://www.freshports.org/textproc/jq/) with `pkg install jq`

**Comment by dtolnay** [comment]
Thanks! I will add it right away. Can you make a commit to bump them to 1.5, or find the right person to ask?

**Comment by dtolnay** [comment]
[GitHub failed](https://status.github.com/messages/2015-08-18) just as I was pushing the website update. I will push it as soon as I can.

**Comment by dtolnay** [comment]
[Done](https://stedolan.github.io/jq/download/)

**Comment by DaniellMesquita** [comment]
GitHub releases aren't including this.
