### ISSUE TITLE
Selecting objects based on value outside of object

### ISSUE THREAD

**Issue by rokka-n** [stedolan/jq#918]
Hi,

I'm trying to print objects where .A[].something[].values are inside .A[].something_else.values

Specifically this is for "aws elb describe-load-balancers"

I'd like to print only specific entries from .ListenerDescriptions[] array, where .Listener.InstancePort is inside another object, .BackendServerDescriptions[].InstancePort

If I do something like this
.LoadBalancerDescriptions[] |  (.ListenerDescriptions[] | select([.Listener.InstancePort] | inside([.BackendServerDescriptions[].InstancePort]))
then jq won't be able to index array with string "BackendServerDescriptions"
because BackendServerDescriptions is obviously outside of .ListenerDescriptions[]

```
       "ListenerDescriptions": [
        {
          "Listener": {
            "InstancePort": 443,
            "SSLCertificateId": "some_ss_cert",
            "LoadBalancerPort": 443,
            "Protocol": "HTTPS",
            "InstanceProtocol": "HTTPS"
          },
          "PolicyNames": [
            "some_policy"
          ]
        },
        {
          "Listener": {
            "InstancePort": 80,
            "LoadBalancerPort": 8080,
            "Protocol": "TCP",
            "InstanceProtocol": "TCP"
          },
          "PolicyNames": []
        }
     "BackendServerDescriptions": [
        {
          "InstancePort": 80,
          "PolicyNames": [
            "some_elb-proxy-policy"
          ]
        }
      ],
      "LoadBalancerName": "lb_name",

```
It should print something like this:
lb_name,80,TCP

**Comment by dtolnay** [comment]
You can use `as` to create variables pointing to useful parts of your input without changing the "current value" represented by `.`. Here is an example of one way to do this:
```
<input.json jq -r '
        .ListenerDescriptions as $listeners |
        .LoadBalancerName as $name |
        .BackendServerDescriptions[].InstancePort as $port |
        $listeners[].Listener | select(.InstancePort == $port) |
        "\($name),\($port),\(.Protocol)"
        '
```

**Comment by rokka-n** [comment]
It worked! :)

```
aws elb describe-load-balancers | ./jq-linux64 -r   ' .LoadBalancerDescriptions[]  |
.ListenerDescriptions as $listeners | .LoadBalancerName as $name | 
.BackendServerDescriptions[].InstancePort as $port  | 
$listeners[].Listener | select(.InstancePort == $port) |
 "\($name),\($port),\(.Protocol)"  '
```

I wonder (now theoretically) if there is a way to do it without variables? 
Or it's a perfect example of a case from jq documentation where "an array of blog posts, with “author” and “title” fields, and another object which is used to map author usernames to real names"?

**Comment by pkoppstein** [comment]
> I wonder (now theoretically) if there is a way to do it without variables?  

Yes:
```
{ LoadBalancerName,
   "port": (.BackendServerDescriptions[].InstancePort),
   "Listener": (.ListenerDescriptions[].Listener)  }
  | select(.port == .Listener.InstancePort)
  | "\(.LoadBalancerName),\(.port),\(.Listener.Protocol)"
```
