### ISSUE TITLE
Stricter checking of path expressions in 1.5

### ISSUE THREAD

**Issue by jakirkham** [stedolan/jq#921]
I am seeing an error in 1.5 that was not present in 1.4. Here are some test files and sample output that demonstrate the issue ( https://gist.github.com/jakirkham/0d2f4708cad69e71b1f6 ). In short, I am running the following command on an empty iPython Notebook and seeing the error below.

    $ jq '( .cells[] | select(.outputs) ) |= [] | (.cells[] | select(.execution_count)) |= null' Untitled.ipynb
    jq: error (at Untitled.ipynb:34): Invalid path expression with result {"cell_type":"code","execu...

**Comment by dtolnay** [comment]
It was a bug in jq 1.4 that allowed this to work in the first place. It looks like the code you meant to write is:

    jq '(.cells[].outputs) = [] | (.cells[].execution_count) = null'

Let me know if I misinterpreted your example. It would help to have the input you used as well.

**Comment by jakirkham** [comment]
No, that seems correct, it seems to produce the right result, and is a bit more succinct. Is this more efficient, as well?

So, maybe I'm missing something else, but your argument is that `select` shouldn't check for a particular dictionary/object key.

**Comment by dtolnay** [comment]
Here is what the manual has to say about select: https://stedolan.github.io/jq/manual/#%60select%28boolean_expression%29%60

> The function select(foo) produces its input unchanged if foo returns true for that input, and produces no output otherwise.

The behavior you were seeing in 1.4 was obviously not this. The `=` was affecting the object that corresponds to `foo` in the manual, instead of affecting "the input unchanged." This was due to a bug in the implementation of `select` in 1.4.

**Comment by jakirkham** [comment]
Right, ok. Thanks for the clarification @dtolnay.

**Comment by jakirkham** [comment]
So, actually, that ends up needing a little bit more modification as we only want to change `outputs` or `execute_counts` if they exist. It turns out they will always exist in an iPython `cell` that equals `"code"`. So, this works a bit better.

    jq '(.cells[] | select(.cell_type == "code") | .outputs) = [] | (.cells[] | select(.cell_type == "code") | .execution_count) = null'

**Comment by jakirkham** [comment]
Alternatively, one can do this without the knowledge of the `cell` value like so.

    jq '(.cells[] | select(has("outputs")) | .outputs) = [] | (.cells[] | select(has("execution_count")) | .execution_count) = null'
