### ISSUE TITLE
I/O primitives, take N

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#925]
New plan for better I/O.

First, finish the C-coded generators branch.  C-coded generators are like C-coded functions, but take a `void **state` argument in which to keep state, return an invalid jv to denote backtracking, and get called with invalid inputs to denote resumption (i.e., the expression that gets the generator's output backtracked).  During backtracking due to errors or cleanup any suspended C-coded generators get to cleanup state, and even catch errors -- this is important as we'll see below.

Second, manage privilege as follows:
- low-level I/O C-coded builtins are only provided to bind unbound references in mid-/high-level I/O builtins and not to any others nor user-coded jq programs;
- two sets of mid-/high-level I/O builtins: one that does real I/O, and one set of stubs that raise errors;
- by default user-coded jq programs and modules get the stub I/O builtins;
- a single new CLI option for indicating which module(s) (or even the top-level program) get the real I/O builtins;
- modules allowed privileges can also grant them to others via the `import`/`include` directives (e.g., `import "foo" {privileged: true};`).

This means that users can create modules that perform access controls for sandboxing jq programs' I/O.  They can express all authorization as jq code, or they can jq-code a module that allows expressing authorization via JSON files, allowing incantations like this: `jq --arg ACL acl.json --privilege wrappers/json_acl 'include "wrappers/json_acl"; readfile'` -> read files named on `stdin` wherever the given ACL file permits it.

Because we'd be encouraging the creation of wrapper modules, we might want to have an option for implicitly injecting `include`s of wrapper modules into top-level programs, so the previous example becomes `jq --arg ACL acl.json --privilege wrappers/json_acl --include wrappers/json_acl readfile` or maybe `jq --arg ACL acl.json --include-privileged wappers/json_acl readfile`.

Third, create low-level C-coded generators for opening files/commands, and which output "file handles" (which will be plain jv values, of course), and C-coded read/write functions.  These will never be available to users; only mid-/high-level builtin functions will have these, and the mid-/high-level builtins will never leak file handles or allow user programs to provide file handles that could get passed to the low-level I/O builtins.  This, and the state management that C-coded generators get to do, means that we can _safely_ actually encode things like `FILE *` values as jv values.

This plan works for file I/O and popen.

For other things, like co-routines, we may need a better notion of file descriptor-like handles, but that can be left out of scope for now even, though co-routines are appealing.  (Icon, like jq has no closures of indefinite extent.  Icon uses co-expressions to get around that limitation, with co-expressions holding on to copies of lexically visible bindings at co-expression instantiation time.  Something similar for jq would be very nice indeed.  Co-routines are a very nice balance of trade-offs compared to `call/cc` and a reasonable trade-off for lacking indefinite-extent closures (and as the latter can be used together with CPS conversion to construct `call/cc`, I repeat myself).  jq needs a co-eval as well, so as to make it possible to jq-code a REPL that doesn't have to spawn jq.)

Bottom-line: jq programs would remain by-default sandboxed to filtering inputs to outputs, and jq would remain a DSL, but I/O with a decent privilege management model would begin to make jq a more general-purpose language.

It is worth noting that jq is a functional language, and that while adding builtins with non-deterministic behavior by and large does not change that, it does mean that the compiler has to know that such builtins are non-deterministic if we ever get to generalize constant-folding, or attempt better common sub-expression elimination, or other optimizations.  We've already crossed the non-determinism Rubicon with the `input` and `inputs` builtins, and in practice jq programs are small enough that constant-folding and CSE is something that the user can be expected to do themselves if it really matters, so we might never care that much (users can constant-fold arithmetic, but not array/object construction, so it pays to have that).

EDIT: Fix typo.

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/pull/1005

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/503

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/255

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/147

**Comment by alimpfard** [comment]
Came to give some input (heh) on the current state of I/O in jq, but seems that y'all have it in [pipeline](https://github.com/stedolan/jq/pull/1843)
and since implementing a lisp on a (mainly) json processor isn't exactly orthodox...I'll leave it.

(what _is_ the current state of this matter?)

**Comment by nicowilliams** [comment]
The current version is all in the `dlopen` branch of my clone.

**Comment by nicowilliams** [comment]
Superseded by #1843.
