### ISSUE TITLE
Streaming, example from FAQ works improperly

### ISSUE THREAD

**Issue by dim-an** [stedolan/jq#927]
Code from [example](https://github.com/stedolan/jq/wiki/FAQ#streaming-json-parser) gives unexpected results (note: missing "Group" key in first result).

     » cat jq-bug  
    [{"Id":{"Group":0,"Id":0},"DcId":0},
    {"Id":{"Group":0,"Id":1},"DcId":0}]
     » jq -c --stream 'fromstream(1|truncate_stream(inputs))' < jq-bug
    {"Id":{"Id":0},"DcId":0}
    {"Id":{"Group":0,"Id":1},"DcId":0}
     » jq --version                                                   
    jq-1.5

**Comment by nicowilliams** [comment]
Don't forget to use the `-n` option when you do this.  (I can't check right
now if there could be something else going on.)

**Comment by dim-an** [comment]
Looks like `-n` option fixes issue. But I don't understand why. Can you explain what's going on?

**Comment by nicowilliams** [comment]
Without -n jq consumes at least one input from stdin (in this case the
streamed stdin), but here you need all inputs to be produced by the inputs
builtin.

**Comment by nicowilliams** [comment]
Perhaps we should encourage users to use `jq -n 'inputs | ...'` instead of `jq '...'`.

**Comment by nicowilliams** [comment]
Another possibility would be to warn if a program uses `inputs` and the `-n` option wasn't used.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> Another possibility would be to warn if a program uses inputs and the -n option wasn't used.

A possibility, yes, but one to be deplored, unless there were also an option to inhibit the warning.

The other possibility you mention (encouraging `jq -n inputs`) would detract from the hard-won simplicity that allows (for example) `curl ... | jq`.  I'm afraid we've painted ourselves into a corner.

By the way, as potentially important as --stream is, I've found it to be so slow that some other alternative has (at least so far) always worked out to be much more practical.  (In a separate thread elsewhere, @dim-an indicated he also found an alternative solution was more practical with respect to his large file.) Is there any likelihood that we'll see a significant performance improvement for the streaming parser in the foreseeable future, at least for certain types of input?

**Comment by nicowilliams** [comment]
@pkoppstein Overall streaming will probably require more allocations (and deallocations) than not streaming, so it's likely to be slower in that sense (for some simple test data I'm getting about 45% slower).  But if you have a large input you'll be using to drive some other slow process (e.g., inserts into a DB) then being able to get started earlier and make progress can make a difference.

**Comment by nicowilliams** [comment]
Also, the right way to test performance of the parser is to measure `jq empty` vs. `jq --stream empty` with the same large input.  When I do that then streaming is faster, as I'd hoped.

The problem here is that printing values appears to be slow.  (Also, `jq .` vs `jq --stream .` will have the first eval two opcodes once each vs the latter eval those two opcodes many times, but right now I think the slowness comes from the printer, not the parser.)

**Comment by nicowilliams** [comment]
You can see that the number of opcode evaluations is not really the problem from things like `jq --stream empty` going faster than `jq empty`...  But thanks for asking about performance.  I suspect that proper profiling will show that the problem is the repeated initialization and teardown of the dtoa context.

**Comment by nicowilliams** [comment]
Proof that it's the JSON printer and not anything else can be had by using raw output.  Timing `jq -r --stream '.[1]'` (with an input consisting of an array of strings) vs `jq --stream .` with the same input makes this clear.

**Comment by nicowilliams** [comment]
I have tried adding `jq_dump*` variants of `jv_dump*` that cache a single dtoa context and it makes a significant (20%) difference for the `jq --stream .` case, so, yes, the dtoa context setup can be amortized and should be.

**Comment by nicowilliams** [comment]
@pkoppstein See the `faster_outputs` branch of my clone for an early attempt to speed up printing of values by jq.  The performance improvement is as described above.

**Comment by pkoppstein** [comment]
> ... faster_outputs branch ...

Alas, for my hitherto-defined testcase, it's no improvement on my Mac (and indeed a tiny bit slower):
```
$ ls -l big.json
  24000008 Jun 12 03:15 big.json

$ time ~/github/jq/jq --stream . big.json > /tmp/big.json.streamed
user	0m8.840s
sys	0m0.250s

$ time ~/github/nicowilliams/jq/jq --stream . big.json > /tmp/big.json.streamed.nico
user	0m9.013s
sys	0m0.217s

$ time ~/github/nicowilliams/jq/jq --stream . big.json > /tmp/big.json.streamed.nico
user	0m8.917s
sys	0m0.220s
```

For comparison:
```
$ time ~/github/jq/jq . big.json > /tmp/big.json.dot
user	0m5.274s
sys	0m0.370s
```

**Comment by nicowilliams** [comment]
@pkoppstein Can you characterize your input?

**Comment by pkoppstein** [comment]
> Can you characterize your input?

In a word: boring.

```
{
 
"00000000": "00000000",
"00000001": "00000001",
...
}
```

**Comment by nicowilliams** [comment]
Thanks.  Boring is good.

**Comment by pkoppstein** [comment]
In case it helps, here are the times writing to /dev/null with -r:
```
$ time ~/github/jq/jq -r --stream . big.json > /dev/null
user	0m8.785s
sys	0m0.060s

$ time ~/github/nicowilliams/jq/jq -r --stream . big.json > /dev/null
user	0m8.683s
sys	0m0.058s

$ time ~/github/jq/jq -r . big.json > /dev/null
user	0m5.341s
sys	0m0.247s
```

**Comment by nicowilliams** [comment]
Sure, /dev/null might help, but the real thing to compare to (to get the cost of printing versus not printing) is `empty` vs. `.`.  I wrote this patch two weeks ago and I got a 20% improvement.  I didn't save my tests.  I'll try to reconstruct them.  For the test data I'm using now (huge top-level objects) I see that streaming is 50% slower than not streaming, for various kinds of inputs.  For the kinds of inputs I care about (arrays of values) it can be as little as 15% slower.  For huge top-level objects it's 50%, which is somewhat surprising, and I'll have to spend some time profiling it, but I'd rather work on the use case I care about (where 15% slower is bad enough eventually).

**Comment by pkoppstein** [comment]
@nicowilliams - I agree that arrays of values are probably the most important case, not least because of the way JSON was originally defined (i.e. requiring the top-level entity be composite).  For this reason, though, I think we may be barking up the wrong tree.  At least, let's take as a primary goal the ability to "unslurp" a top-level array very quickly, without reading it all in.  I think an "--unslurp" option might be the way to go.  This would have exactly the same semantics as .[] for arrays, but would not entail all the work currently required by --stream.

**Comment by nicowilliams** [comment]
Using `--debug-trace` it's possible to see that we do have two references to the path component of the output of streaming in the desired input case, but the whole output has only one reference.  In other words, we're allocating and deallocating an array for each output of the streaming parser.  Instead we could recycle the output and mutate it, which will be much faster.
