### ISSUE TITLE
Android binaries

### ISSUE THREAD

**Issue by mschewe** [stedolan/jq#928]
Thanks! Great project, I really love it!
I'am using it in several scripts on the server now. 

I would love to have it on Android devices too. 
A binary for ARM architecture would be great. Is there already any progress?

**Comment by dtolnay** [comment]
See #441. @wtlangford has a script to compile libjq for iOS here: https://gist.github.com/wtlangford/32b47d5eb823dee2e15f. You may be able to do something similar for Android. Let us know if you get it working by adding the steps to the [cross-compilation](https://github.com/stedolan/jq/wiki/Cross-compilation) wiki page.

**Comment by else** [comment]
jq compiles fine on arm64, armel and armhf. Check out Debian's [buildd](https://buildd.debian.org/status/package.php?p=jq&suite=unstable) logs.
