### ISSUE TITLE
jqplay broken

### ISSUE THREAD

**Issue by somaiah** [stedolan/jq#932]
https://jqplay.org/ does not allow pasting of JSON. Seems to have been broken after the upgrade to v1.5

**Comment by jingweno** [comment]
@somaiah I reverted to `jq` 1.4 for now...

**Comment by jingweno** [comment]
This is [fix](https://github.com/jingweno/jqplay/pull/42).

**Comment by jingweno** [comment]
@nicowilliams We can close this?
