### ISSUE TITLE
inside is not defined

### ISSUE THREAD

**Issue by nVitius** [stedolan/jq#934]
The function referenced in the docs "inside" is showing up as not defined. I'm trying to use it on jqplay, which is using version 1.4

**Comment by dtolnay** [comment]
The `inside` builtin was added in jq 1.5. Here is the manual for jq 1.4: https://stedolan.github.io/jq/manual/v1.4/

There were some issues upgrading jqplay to 1.5. It is being tracked at https://github.com/jingweno/jqplay/issues/41 and https://github.com/jingweno/jqplay/pull/42.
