### ISSUE TITLE
jq1.5 Linux Binaries not compiled with ONIGURUMA library

### ISSUE THREAD

**Issue by timnashcouk** [stedolan/jq#935]
The binary versions, do not have support for regex due to missing library and while I appreciate it's optional, the library is not in src, and the link points to a Yahoo holding page, meaning can't even compile with support built in.

Really the binaries should include support for one of jq biggest feature :(

**Comment by wtlangford** [comment]
That's a new thing, that the oniguruma library's page is gone.  I've got a copy of the tar.gz somewhere.  I can move it into the repo if we want. @nicowilliams @dtolnay any opposition to that?

Also, most linux distros I've seen have an oniguruma package in their package manager.

That being said, was there a reason we didn't roll regex into the pre-built binaries?

**Comment by dtolnay** [comment]
Which binary are you using? It looks like linux64 is okay:

```
$ sha1sum jq-linux64
d8e36831c3c94bb58be34dd544f44a6c6cb88568  jq-linux64
$ ldd jq-linux64
	not a dynamic executable
$ ./jq-linux64 -n '"abbbc" | match("(b+)")'
{
  "offset": 1,
  "length": 3,
  "string": "bbb",
  "captures": [
    {
      "offset": 1,
      "length": 3,
      "string": "bbb",
      "name": null
    }
  ]
}
```

@wtlangford let's try to keep binaries out of git (see #615). Please add it to the github release instead: https://github.com/stedolan/jq/releases/edit/jq-1.5

**Comment by wtlangford** [comment]
@dtolnay Definitely not a binary, but a local copy of the oniguruma source as a backup.  Think a `vendors` folder, like bundle will do.

**Comment by dtolnay** [comment]
Oh okay. That sounds good.

**Comment by wtlangford** [comment]
Hm, at that point, do we want to eschew the external dependency and just keep it internal?  The reason I didn't do it originally was so that it was easy to get bug/security fixes included.  But if oniguruma's website is gone...  That landing page is geocities.jp's 404.  Do we want to switch libraries?

**Comment by wtlangford** [comment]
On that note, there's this: https://github.com/k-takata/Onigmo which was forked from oniguruma and appears to be more feature-rich and still under active development.  Also, it's the thing ruby is using.

**Comment by dtolnay** [comment]
Looks good. I will have time this weekend to update the travis build and installation instructions to use Onigmo, unless you get to it earlier.

**Comment by timnashcouk** [comment]
I was using 32bit Linux binary, switched to 64 and it is indeed compiled with correct support.

**Comment by nicowilliams** [comment]
Oh!  The Linux 32-bit executable is statically linked, but there's no Oniguruma support in it.  I'll have to re-release that one.

**Comment by dtolnay** [comment]
@nicowilliams any update on this?

**Comment by nicowilliams** [comment]
I'll build one Monday night.

**Comment by nicowilliams** [comment]
Built.  Just gotta sign and update the release.

**Comment by nicowilliams** [comment]
My apologies for being so late on this.

**Comment by nicowilliams** [comment]
@dtolnay Maybe the download page should mention that the 1.5 jq executable for linux32 has been re-released?

**Comment by dtolnay** [comment]
I don't think it's important. The signature comes with a timestamp anyway. Thanks for taking care of this.
