### ISSUE TITLE
Count length in bytes in UTF8 (or arbitrary encoding)

### ISSUE THREAD

**Issue by jnothman** [stedolan/jq#941]
I was hoping to use `jq` to transform some JSON records into [redis](http://redis.io) [`APPEND`](redis.io/commands/append) commands (to produce json-seq entries), via its [`redis-cli --pipe` mass-insertion protocol](redis.io/topics/mass-insert). This involves formatting a string in which each argument is prefixed by its length in bytes. `length`, however, only counts the number of Unicode characters. Seeing as strings are output in UTF8, a function to calculate the number of bytes in UTF8 would be valuable so I can construct a redis command as follows:
```
jq -j '(tostring | "\u001e\(.)\n") as $blob | "*3\r\n$6\r\nAPPEND\r\n$\(.key | byteslength)\r\n\(.key)\r\n$\($blob | byteslength)\r\n\($blob)\r\n"'
```

**Comment by pkoppstein** [comment]
@jnothman - There's a good chance the following will work, though I'm not sure:
```
def blength: @uri | gsub("%.."; "a") | length;
```
Here are some (encouraging) examples:
```
"a"
1

"á"
2

"日"
3

"\t"
1
```

`gsub` was introduced in jq 1.5 but has been available in pre-release versions of jq 1.5 for some time.

**Comment by jnothman** [comment]
Neat idea! It's a bit roundabout, given that [a builtin patch is pretty simple](https://github.com/jnothman/jq/tree/byteslength), but I appreciate that minimal changes to builtins, or even the packaged library, are preferred.

Should we assume instead that this is one for the cookbook and close this issue, or need we evaluate the efficiency of this approach?

**Comment by pkoppstein** [comment]
@jnothman - I'd definitely suggest that you create a PR for your patch.  As you say, the change is minimal, and the wins for jq are significant in terms of friendliness and performance.

**Comment by dtolnay** [comment]
Added in #944.
