### ISSUE TITLE
if-then-else documentation

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#942]
The jq 1.5 manual is out-of-sync with jq 1.5 behavior when it says:

> If the condition A produces multiple results, it is considered “true” if any of those results is not false or null. If it produces zero results, it’s considered false.

The jq 1.5 behavior (which I believe is actually "correct") is based on the "regularity" of if-then-else in all positions.  Here are some illustrative examples:

```
$ jq -n 'if 1,null,2 then 3 else 4 end'
3
4
3

$ jq -n 'if empty then 3 else 4 end'

$ jq -n 'if 1 then 3,4 else 5 end'
3
4

$ jq -n 'if null then 3 else 5,6 end'
5
6
```

**Comment by nicowilliams** [comment]
Are you saying there was a change relative to 1.4?  Anyways, the conditional expression's outputs are all evaluated, and for each output the then or else clause expressions are evaluated.

**Comment by pkoppstein** [comment]
@nicowilliams asked:
> Are you saying there was a change relative to 1.4?

No.  In fact, it looks like the out-of-sync problem may have been there in 1.3.  

Anyway, as I said before, it seems to me the documentation should be changed.

**Comment by nicowilliams** [comment]
The then/else exps also get evaluated for all their outputs: `jq -cn '[if range(10) % 2 == 1 then "hi","there" else "boo","hoo" end]|join(" ")'`.

In general all expressions produce all their outputs.  Exceptions include things like `first(EXP)`.  Compare to Icon where the default is to take just the first output, and so there's an `every EXP` form to force the production of all values.  The Icon approach is much more friendly to newcomers...  Also Icon never evaluates more than one output for conditional expressions.  I only miss the latter aspect of Icon.

**Comment by pkoppstein** [comment]
@nicowilliams - You evidently didn't read or didn't understand or don't' remember my original posting, so I won't repeat it, but to be clear: Given we're agreed the behavior is correct, the documentation needs to be changed.

**Comment by dtolnay** [comment]
Thanks for flagging this! I have changed all four manuals to say the following:

> If the condition `A` produces multiple results, then `B` is evaluated
> once for each result that is not false or null, and `C` is evaluated
> once for each false or null.

I debated removing the paragraph entirely, but I do think it is worth clarifying this. Let me know if you can suggest any improvements to the wording.

I also found this amusing comment in the unit tests:

    # FIXME: define/test behaviour of 'if (.foo,.bar) then A else B end'

It seems like this behavior was figured out fairly late.
