### ISSUE TITLE
strange output

### ISSUE THREAD

**Issue by VitaliyKulikov** [stedolan/jq#945]
filter: `jq .value`

input: `{"value":643172583639224320}` 
output: `643172583639224300` 

__additional 0 at the end__

**Comment by VitaliyKulikov** [comment]
seems `| tonumber` adds **zero** at the end 

filter: `jq .value | tonumber`

input: `{"value": "643172583639224320"}` 
output: `643172583639224300`

**Comment by pkoppstein** [comment]
jq (through jq 1.5) loses precision for very large and for very small numbers.  Search for "number" in the FAQ (https://github.com/stedolan/jq/wiki/FAQ)

**Comment by VitaliyKulikov** [comment]
thanks for info. so, going right-trim the output just for now)

**Comment by nicowilliams** [comment]
@VitaliyKulikov No, jq did not add a zero.  Look carefully.  jq changed the 2 in the tens column to a zero.  You can't fix this by trimming the output.  The problem is a lack of precision in IEEE754 64-bit double-precision floating point numbers, which jq uses.

**Comment by VitaliyKulikov** [comment]
@nicowilliams thanks a lot. my mistake, i should compare whole strings. got it.
