### ISSUE TITLE
Creating Json result

### ISSUE THREAD

**Issue by Nic2012** [stedolan/jq#946]
Hi,
I have an output like this
**Label: ISO Speed
Type: RADIO
Current: 200
Choice: 0 200
Choice: 1 250
Choice: 2 320**

My first attempt with jq returns like this
... | jq --slurp --raw-input --raw-output 'split("\n")'
**[
  "Label: ISO Speed",
  "Type: RADIO",
  "Current: 200",
  "Choice: 0 200",
  "Choice: 1 250",
  "Choice: 2 320"
]**
But when I try to extract into key-value pairs by the following, I receiving an error
...| jq --slurp --raw-input --raw-output 'split("\n") | map( split(":") | {.[0]: .[1]})'
error: syntax error, unexpected '.'

How can I solve it to get final structure
**{ label: 'ISO Speed',
  type: 'radio',
  current: '200',
  choice:
   [ '200',
     '250',
     '320' ]}**

Maybe somebody can help, I am bloody beginner in jq and I havent found examples handling creation of JSON.
Thanks and best regards,
Nic

**Comment by dtolnay** [comment]
Here is a partial solution. It uses the `reduce` feature of jq 1.5 to combine each input line into one object.

```
<input.txt jq -n --raw-input '
    reduce (inputs | split(": ")) as [$key, $value] ({}; .[$key] =
        if has($key)|not then
            $value
        elif .[$key]|type == "array" then
            .[$key]+[$value]
        else
            [.[$key], $value]
        end)'
```

There are three cases when adding an item.

1. If the key is being seen for the first time, add `$key:$value` to the object.
2. If the key is being seen for the second time, change the value in the object to `[$oldvalue, $newvalue]`.
3. If the key is being seen for the third or later time, change the value in the object to `$oldvalue + [$newvalue]`.

Here is the output for your example input:

```
{
  "Label": "ISO Speed",
  "Type": "RADIO",
  "Current": "200",
  "Choice": [
    "0 200",
    "1 250",
    "2 320"
  ]
}
```

I will let you figure out the remaining steps: changing the keys to lowercase, and removing the 0, 1, 2 from the array values.

**Comment by nicowilliams** [comment]
But when I try to extract into key-value pairs by the following, I receiving an error
    ...| jq --slurp --raw-input --raw-output 'split("\n") | map( split(":") | {.[0]: .[1]})'
    error: syntax error, unexpected '.'

That's because when you use a non-constant-string expression for an object key you need to wrap it in parenthesis, so this compiles:

    ...| jq --slurp --raw-input --raw-output 'split("\n") | map( split(":") | {.[0]: .[1]})'

**Comment by Nic2012** [comment]
Many thanks, but it doesnt work. I have version 1.4-1, maybe it has also to do with the way of calling

gphoto2 --quiet --get-config iso | jq -n --raw-input '
    reduce (inputs | split(": ")) as [$key, $value] ({}; .[$key] =
        if has($key)|not then
            $value
        elif .[$key]|type == "array" then
            .[$key]+[$value]
        else
            [.[$key], $value]
        end)'
jq: --null-input cannot be used with --raw-input or --slurp
Use jq --help for help with command-line options,
or see the jq documentation at http://stedolan.github.com/jq

**Comment by nicowilliams** [comment]
(The need to wrap object-construction key expressions in parenthesis is an accident of how parsing is done.  Dropping it creates 3 shift/reduce and three reduce/reduce conflicts for `parser.y`.)

**Comment by dtolnay** [comment]
Here is the equivalent for jq 1.4, but it is slightly more complicated than the 1.5 solution.

```
jq --slurp --raw-input '
    split("\n") | reduce (.[] | split(": ")) as $item ({};
        $item[0] as $key |
        $item[1] as $value |
        .[$key] =
            if has($key)|not then
                $value
            elif .[$key]|type == "array" then
                .[$key]+[$value]
            else
                [.[$key], $value]
            end)'
```

**Comment by nicowilliams** [comment]
(The need to wrap object-construction key expressions in parenthesis is an accident of how parsing is done.  Dropping it creates 3 shift/reduce and three reduce/reduce conflicts for `parser.y`.  There might be a way to disambiguate the grammar so we can drop this parenthesize-the-key-expression requirement...  We should look into that.)

**Comment by Nic2012** [comment]
Yeah that works !
```
{
  "Label": "ISO Speed",
  "Type": "RADIO",
  "Current": "200",
  "Choice": [
    "0 200",
    "1 250",
    "2 320",
    "3 400",
    "4 500",
    "5 640",
    "6 800",
    "7 1000",
    "8 1250",
    "9 1600"
  ]
}
```
Any chance to prevent the numbering in the array? So far many thanks.

**Comment by dtolnay** [comment]
See if you can figure that out. [`index`](https://stedolan.github.io/jq/manual/v1.4/#%60index%28s%29%60,%60rindex%28s%29%60) and [`.[a:b]`](https://stedolan.github.io/jq/manual/v1.4/#%60.[%3Cstring%3E]%60,%60.[2]%60,%60.[10:15]%60) may be helpful.

**Comment by pkoppstein** [comment]
Since the input is nearly-YAML, here's a slightly different take on the problem using any-json (https://www.npmjs.com/package/any-json):
```
    $ awk '$1=="Choice:" {if (!choice) {print "Choice:"; choice=1}; print " " $NF; next} {choice=0; print}'  test.txt |\
      any-json -format=yaml \
      jq '.Choice |= (split(" ") | map(tonumber))'
```
Output:
```
{
  "Label": "ISO Speed",
  "Type": "RADIO",
  "Current": 200,
  "Choice": [
    200,
    250,
    320
  ]
}
```

**Comment by Nic2012** [comment]
I thing by split(" ")[1] i could manage it, but why starts it from index 2 ?
```
gphoto2 --quiet --get-config iso | jq --slurp --raw-input '
    split("\n") | reduce (.[] | split(": ")) as $item ({};
        $item[0] as $key |
        $item[1] as $value |
        .[$key] =
            if has($key)|not then
                $value
            elif .[$key]|type == "array" then
                .[$key]+[$value | split(" ")[1]]
            else
                [.[$key], $value]
            end)'
{
  "Label": "ISO Speed",
  "Type": "RADIO",
  "Current": "200",
  "Choice": [
    "0 200",
    "1 250",
    "320",
    "400",
    "500",
    "640",
    "800",
    "1000",
    "1250",
    "1600"
  ]
}
```

**Comment by Nic2012** [comment]
Well, i found no function or hint in jq. v1.4 to convert a string to lowercase.
So as the input has to be preprocessed by "tr" like
```
... | tr '[:upper:]' '[:lower:]' | jq --slurp --raw-input ...
```

**Comment by pkoppstein** [comment]
@nic2012 - Please see the FAQ https://github.com/stedolan/jq/wiki/FAQ, where two functions for jq 1.4 are given.

**Comment by Nic2012** [comment]
@pkoppstein
Yeah, many thanks. I was focussing on the manual only. ascii_downcase is what y meant ? Yes but I have still v1.4 and no idea how i can add alternative code inside
```
gphoto2 --quiet --get-config iso | jq --slurp --raw-input '
    split("\n") | reduce (.[] | split(": ")) as $item ({};
        $item[0] as $key |
        $item[1] as $value |
        .[$key] =
            if has($key)|not then
                $value
            elif .[$key]|type == "array" then
                .[$key]+[$value | split(" ")[1]]
            else
                [.[$key], $value | split(" ")[1]]
            end)'
```

**Comment by Nic2012** [comment]
Found it :)
```
 | jq -s -R '
    def ascii_downcase:explode | map( if 65 <= . and . <= 90 then . + 32  else . end) | implode; ascii_downcase | split("\n") | reduce (.[] | split(": ")) as $item ({};
        $item[0] as $key |
        $item[1] as $value |
        .[$key] =
            if has($key)|not then
                $value
            elif .[$key]|type == "array" then
                .[$key]+[$value | split(" ")[1]]
            else
                [.[$key], $value | split(" ")[1]]
            end)'
```

**Comment by pkoppstein** [comment]
@Nic2012 - Whichever version of jq you use, you can always add function definitions by inserting them before they are used.  Since your program is more than one line, I'd strongly recommend putting all the jq code in a file (say, my.jq), and then using the -f option, e.g. `jq -s -r -f my.jq`

**Comment by Nic2012** [comment]
@pkoppstein
Yeah, many thanks. I was focussing on the manual only. ascii_downcase is what y meant ?
Found it :)
```
 | jq -s -R '
    def ascii_downcase:explode | map( if 65 <= . and . <= 90 then . + 32  else . end) | implode; ascii_downcase | split("\n") | reduce (.[] | split(": ")) as $item ({};
        $item[0] as $key |
        $item[1] as $value |
        .[$key] =
            if has($key)|not then
                $value
            elif .[$key]|type == "array" then
                .[$key]+[$value | split(" ")[1]]
            else
                [.[$key], $value | split(" ")[1]]
            end)'
```

**Comment by Nic2012** [comment]
Maybe I am blind, but is there any example in faq for string replacement that from
```
Label: ISO Speed
Choice..
```
goes to
```
{
"Label": "ISOSpeed"
"Choices": [
  ...
  ]
}
```

**Comment by nicowilliams** [comment]
@Nic2012 Version 1.5 has been released, and has some (ASCII-only) case conversion functions.

**Comment by pkoppstein** [comment]
@Nic2012  - Here's an illustration of way to "rename" a key:

    $ jq -n '{"Choice":1} | .Choices = .Choice | del(.Choice)'
