### ISSUE TITLE
Newlines not supported on jqplay with jq 1.5

### ISSUE THREAD

**Issue by somaiah** [stedolan/jq#948]
This works:

JSON:

    {
       "expand": "schema names"
    }

Filter: .expand
Result: "schema names"

This does not work:

JSON:

    {
       "expand": "schema 
        names"
    }

Filter: .expand
Result: parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 3, column 9

If I check the raw input checkbox:

Result:
jq: error (at <stdin>:1): Cannot index string with string "expand"
jq: error (at <stdin>:2): Cannot index string with string "expand"
jq: error (at <stdin>:3): Cannot index string with string "expand"
jq: error (at <stdin>:3): Cannot index string with string "expand"

I think it worked fine on jq 1.4

**Comment by nicowilliams** [comment]
@somaiah Newlines are not allowed in JSON strings.  They must be escaped as `\n` or as `\u000a`.
