### ISSUE TITLE
An unterminated string is not treated as an error

### ISSUE THREAD

**Issue by rfletcher** [stedolan/jq#951]
JSON input containing an unterminated string should be treated as an error. Instead, jq produces no output and exits with `0` status:

    $ echo '"foo' | jq
    $ echo $?
    0

That's a simple case, and maybe an uncommon one, but more complex JSON with the same issue behaves the same way:

    $ echo '{"foo: 1 }' | jq
    $ echo $?
    0

In these cases `jq` should print an error consistent with other kinds of invalid JSON (even if that error is a bad one right now, per issue #501), and exit with a non-zero status. In other words, it should match the behavior already present for other kinds of invalid JSON:

    $ echo 'foo"' | jq
    parse error: Invalid numeric literal at line 1, column 4
    $ echo $?
    4

**Comment by dtolnay** [comment]
Thanks for reporting this. In jq 1.4 there was a helpful error message for this, but it is broken in 1.5.

**Comment by dtolnay** [comment]
`git bisect` points to 0f5345e.

**Comment by dtolnay** [comment]
@nicowilliams do you remember what input caused the infinite loop fixed in that commit? I want to add a test.

**Comment by nicowilliams** [comment]
@dtolnay It was caught by the cheap fuzzer.  I have some rand files lying around, but not that one.  I didn't distill the input from it, sorry :(  I can try to reproduce it by running the fuzzer a lot, but I don't know when I'll get to it.

**Comment by nicowilliams** [comment]
Er, actually, EOF is handled correctly:

    $ printf '"a' | jq .
    parse error: Unfinished string at EOF at line 1, column 2
    $ 

The problem here has to do with the pesky newline.

Compare:

    $ printf '"a\nb"' | jq .
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 2
    $ printf '"a\nb' | jq .
parse error: Unfinished string at EOF at line 2, column 1
    $

**Comment by nicowilliams** [comment]
The problem is a missing call to `jv_parser_set_buf()` and `jv_parser_next()`.

**Comment by nicowilliams** [comment]
Fix coming up.

**Comment by rfletcher** [comment]
Thanks!
