### ISSUE TITLE
Find objects that do not have key

### ISSUE THREAD

**Issue by dbclkclk** [stedolan/jq#952]
I have these objects:

     {"id":"1", "name":"blah", "age":"12"}
     {"name":"blah", "age":"12"}

And I wanted a way to find the objects that do not contain the key "id". Is this possible?

**Comment by dtolnay** [comment]
Try this:

    jq 'select(has("id") | not)'

**Comment by Nottt** [comment]
Sorry for reviving this issue, but I'm really struggling in how to use this and this appears on google search...

Given this JSON:

```
{
      "codec": "SubRip/SRT",
      "id": 23,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "por",
        "number": 24,
        "text_subtitles": true,
        "uid": 4452806849278129445
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 24,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "por",
        "number": 25,
        "text_subtitles": true,
        "track_name": "Brazilian",
        "uid": 13589811319081001606
      },
      "type": "subtitles"
```

I want to get the track ID of itens with `language = por` but that does not contain a `track_name`. 

I tried something like this: 

`mkvmerge -J *mkv | jq -r '.tracks | map(select(.type == "subtitles") | select(.properties.language == "por") | select(has("track_name") | not) |  .id) | map(tostring) | join(",")'`

But it returns 24 and 23...should return only 23

**Comment by dtolnay** [comment]
> ```jq
> select(has("track_name") | not)
> ```

None of those objects has a `.track_name` so this select is true for both id 23 and id 24. 23 has a `.properties.track_name` so you may want:

```jq
select(.properties | has("track_name") | not)
```

**Comment by Nottt** [comment]
So something like this?

```
mkvmerge -J *mkv | jq -r select(.properties | has("track_name") | not) | jq -r '.tracks | map(select(.type == "subtitles") | select(.properties.language == "por") | .id) | map(tostring) | join(",")'
```

There is a syntax error but I don't know where...the idea here was giving the full JSON output for your first jq, get only the entries that don't have a track_name, then just pipe it to my usual jq command that filters based on language so I'd get the desired result: 23

**Comment by Nottt** [comment]
Thanks! It works <3

Just in case anyone want a example of how you use that with other `jq` commands:

```sh
mkvmerge -J *mkv | jq -r '.tracks | map(select(.type == "subtitles") | select(.properties.language == "por") | select(.properties | has("track_name") | not) | .id) | map(tostring) | join(",")'`
```

Maybe it's not the cleanest, but works...thanks

**Comment by Siva-Thilak** [comment]
I konw it's been a while. But I had a simple question. What if the "id" here is an array?
and what if the array name has spaces in between .
For eg,
{"id":"1", "a b c":[ "name" : "foo" ] }
{"id":"2" }
and I want to display only first object? could you kindly help me on this one?
