### ISSUE TITLE
Chocolatey install for Windows fails

### ISSUE THREAD

**Issue by ericcitaire** [stedolan/jq#959]
Chocolatey install fails with an HTTP 404 error, trying to download the binary with URL http://stedolan.github.io/jq/download/win64/jq.exe

     Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
     Au niveau de C:\ProgramData\chocolatey\helpers\functions\Write-ChocolateyFailure.ps1 : 24 Caractère : 8
     +   throw <<<<  "$failureMessage"
         + CategoryInfo          : OperationStopped: (Exception calli...04) Not Found.":String) [], RuntimeException
         + FullyQualifiedErrorId : Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
    Command ['"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\jq\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters ''"'] exited with '1'

**Comment by ericcitaire** [comment]
I made a [pull request](https://github.com/rjocoleman/chocolatey-jq/pull/2) in the chocolatey-jq project request

**Comment by dtolnay** [comment]
Thanks for the pull request, but the chocolatey package from [svnpenn/p](https://github.com/svnpenn/p/tree/master/jq) has already been submitted for moderation with a correct url for jq 1.5. See https://chocolatey.org/packages/jq/1.5. You should already be able to do `choco install jq -version 1.5`.
