### ISSUE TITLE
jq . performs differently with unquoted keys than jq --null-input

### ISSUE THREAD

**Issue by dannydulai** [stedolan/jq#961]
```
% jq --null-input '{ foo: 1 }'
{
  "foo": 1
}
```

```
% echo '{ foo: 1 }' | jq .
parse error: Invalid literal at line 1, column 6
```

```
% jq --version
jq-1.4
% uname
Darwin hiroo2.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
```

**Comment by pkoppstein** [comment]
@dannydulai - You have discovered a neat feature of jq: as a rule, the textual input of a jq program must be valid JSON, but in a jq program, a JSON entity may be specified more flexibly.  

(Incidentally, this is discussed briefly in the FAQ at (https://github.com/stedolan/jq/wiki/FAQ#processing-not-quite-valid-json).)
