### ISSUE TITLE
NaN cannot be selected by path expression

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#962]
```
$ echo '[1,2,null,Infinity,NaN]' | jq '.[] | . = 1'
1
1
1
1
jq: error (at <stdin>:1): Invalid path expression with result null
```

**Comment by nicowilliams** [comment]
@dtolnay Should the `jv_identical()` check perhaps be:

    1305     case JV_KIND_NUMBER:
    1306       r = a.u.number == b.u.number || (isnan(a.u.number) && isnan(b.u.number) && ((uint64_t)a.u.number) == (uint64_t)b.u.number));
    1307       break;

**Comment by dtolnay** [comment]
That would be undefined behavior. Here is what the standard defines in terms of casting from double to uint64_t:

> - When a finite value of real floating type is converted to an integer type other than _Bool, the fractional part is discarded (i.e., the value is truncated toward zero).

> - If the value of the integral part cannot be represented by the integer type, the behavior is undefined.

> - The remaindering operation performed when a value of integer type is converted to unsigned type need not be performed when a value of real floating type is converted to unsigned type.

> - If the value being converted is outside the range of values that can be represented, the behavior is undefined.

Maybe it could be `*(*uint64_t)(&number)` which is still undefined but maybe more likely to be meaningful.

I can see how this may catch a few additional cases of invalid path expressions, but I don't think the tradeoff in portability makes sense.

**Comment by nicowilliams** [comment]
Yes, the only safe way to make this cast is by going through `void *`, but you understood what I meant: bit-wise compare the things.  My concern is that `jv_identical()` is exposed, therefore that this may trip up some user other than this use of it.

**Comment by dtolnay** [comment]
Got it. I was only thinking in the context of this ticket. If we can do this safely and correctly (cast to `void*`, loop to `sizeof(double)`) then it makes sense.

**Comment by dtolnay** [comment]
Filed #978 to track.

**Comment by nicowilliams** [comment]
Sure, `memcpy(&a.u.number, &b.u.number, sizeof(a.u.number))` should work.
