### ISSUE TITLE
walk function not work

### ISSUE THREAD

**Issue by linquize** [stedolan/jq#963]
Using jq 1.5,
`walk` function not work

From the example doc,
```
$ jq 'walk(if type == "array" then sort else . end)'
jq: error: walk/1 is not defined at <top-level>, line 1:
walk(if type == "array" then sort else . end)
jq: 1 compile error
```

**Comment by dtolnay** [comment]
`walk` is not in jq 1.5. It will be in the next release.

Here is the manual for 1.5: https://stedolan.github.io/jq/manual/v1.5/

**Comment by linquize** [comment]
oops

**Comment by pkoppstein** [comment]
@linquize -- `walk` is just a few lines of jq, so if you want to use it, you have a choice: snarf a copy of the function for your use; or install the "master" version of jq from github.

**Comment by mewalig** [comment]
can someone post those lines of jq that define ```walk```?

**Comment by dtolnay** [comment]
@mewalig you missed the first few lines when you copied.

```
# Apply f to composite entities recursively, and to atoms
def walk(f):
  . as $in
  | if type == "object" then
      reduce keys[] as $key
        ( {}; . + { ($key):  ($in[$key] | walk(f)) } ) | f
  elif type == "array" then map( walk(f) ) | f
  else f
  end;
```

**Comment by mewalig** [comment]
Thank you!

**Comment by gsime1** [comment]
Hi - I have this version of jq `jq-1.5-1-a5b5cbe` and even `sudo apt-get install --only-upgrade jq` but I get the same error when running a filter.jq with the walk function - works perfectly on jqplay.

**Comment by isaiahfisher** [comment]
How do you add walk to your jq installation? Where would you place the function code?
