### ISSUE TITLE
building static jq

### ISSUE THREAD

**Issue by luneart** [stedolan/jq#964]
I test and develop using a *buntu system, however the goal is to deploy on a very limited shell (the sh from BusyBox 1.23.2). I needed the string manipulation functions not yet into the release, so I compiled the master branch with static-linking option, eg `make LDFLAGS=-all-static -j8`.
It worked, with the warning:
"warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking".

Also, `make check` failed onigtests, but I guess that's expected regarding the oniguruma dependency issues.

That's it for the bug report. On a personal note now: as long as I don't use login (due to getpwuid) nor RE (due to oniguruma) features, I'm fine right?

**Comment by dtolnay** [comment]
The lack of getpwuid will cause problems with library paths relative to the home directory (`-L ~/...`). I think you may get a segmentation fault if you use that. Other absolute and relative library paths will work, and if you are running from a shell then `~` is expanded anyway so jq never sees it.

You can include oniguruma in a statically linked jq. In fact this is what the [linux release binaries](https://github.com/stedolan/jq/releases/tag/jq-1.5) do. It should happen automatically if libonig2 and libonig-dev (on *buntu) are installed when you run `./configure` and `make`.

`make check` is expected to fail onigtests when not compiled with oniguruma. This is why onigtests are split out from the rest of the tests.

You're fine as long as you don't use `-L ~/...` and any of the regex functions (`test`, `match`, `capture`, `scan`, `splits`, `sub`, `gsub`).

**Comment by pkoppstein** [comment]
@luneart wrote:
> I needed the string manipulation functions not yet into the release ...

Please note that jq 1.5 (the current release) does include all the regex functions.  In fact, I cannot think offhand of any string manipulation functions that have been added since version 1.5, unless you count utf8bytelength as such.

**Comment by luneart** [comment]
I had the 1.3 from my distro's repo, and I needed `ltrimstr`. I tried the binary previously compiled on the target system, works like a charm (but no regexes nor paths, so no risks).
jq is really an awesome tool, it replaced a big python processing. Thanks a lot!

**Comment by nicowilliams** [comment]
jq will use `$HOME` if set and won't use `getpwuid()` in that case.
