### ISSUE TITLE
Succinct expression for the following in jq?

### ISSUE THREAD

**Issue by evandrix** [stedolan/jq#972]
i recently had to "summarise" json pulled from mongo for a colleague, i.e. transform something like:
{
   "key1": "val1",
   "key2": {"$numberLong": 42}},
   "key3": {"key3_1": "val2"}}
   ...
}
...to...
[
   "key1",
   "key2",
   {"key3": ["key3_1"]},
   ...
]

I went to read up the docs and play around with recurse, walk (I'm ok with using master, rather than release v1.5), the .. operator, to/from/with_entries builtin functions etc., but only got so far as just "sort of" preserving the structure but setting leaf node values to null, so like:
{
   "key1": null,
   "key2": null,
   "key3": {"key3_1": null}}
   ...
}

Just to clarify a little on the task at hand: I wish to show the "structure of the json i.e. keys only, including nested keys recursively, except if the child is a dict with only keys that begin with $, since those are artifacts of mongoexport, so {"key1":{"$key2":"val1"}} should become ["key1"] ideally, but I've only managed to achieve {"key1":null} thus far.

Thanks in advance.

**Comment by evandrix** [comment]
I would like the "structure" to be returned as a list, i.e. like how the default builtin function 'keys' works.

**Comment by pkoppstein** [comment]
Two schema inference engines are at #748 - they might be of help, either directly or inspirationally. However it isn't clear to me what it is you want with regard to arrays.

**Comment by evandrix** [comment]
Basically apply like what the default jq function 'keys' does recursively, i.e. return an array of strings of the keys of the json, except if the value contains a key begins with $, in which case discard that value.

It's mainly just that 'keys' doesn't do recursive, neither can I specify to exclude certain keys.

**Comment by nicowilliams** [comment]
@evandrix `path(..)` in 1.5 does something like `keys` recursively.

**Comment by evandrix** [comment]
But path(..) doesn't present it in the format as I would like - stated in my original post - neither can it filter out certain keys?

**Comment by pkoppstein** [comment]
@evandrix - The idea is that 'path(..)' will produce a stream, which you can then filter (e.g., using select). Since you indicated you want the final answer to be an array, your program might end up looking something like this:
```
[path(..) | select( SELECTION_CRITERIA )]
```

p.s. If you want programming help, you might like to try asking at stackoverflow.com, using the jq tag.
