### ISSUE TITLE
stream to array convertor without slurp

### ISSUE THREAD

**Issue by JanChavel** [stedolan/jq#977]
My JSON input:

      {  "Key": "Team",     "Value": "AA" }
      {  "Key": "Division", "Value": "BB" }

Desired output:

    [
      {  "Key": "Team",     "Value": "AA" },
      {  "Key": "Division", "Value": "BB" }
    ]

I cannot use --slurp option because I'm in a middle of complex jq code.
The mentioned input is a result of my function and I need to convert it to an array for further processing.

The solution recommended in FAQ: https://github.com/stedolan/jq/wiki/FAQ#general-questions

    cat json | jq 'reduce . as $i ([]; . + [$i])'

produces something different:

    [
      {  "Key": "Team",     "Value": "AA" }
    ]
    [
      {  "Key": "Division", "Value": "BB" }
    ]

**Comment by dtolnay** [comment]
It would help to have at least a little more of the surrounding code. Typically the way to do this is to wrap the code that produces a stream inside `[` `]`.

For example this produces a stream for each input:

```
$ echo 1 2 3 | jq '.+1 | range(1;.)'
1
1
2
1
2
3
```

This produces an array for each input:

```
$ echo 1 2 3 | jq '.+1 | [range(1;.)]'
[
  1
]
[
  1,
  2
]
[
  1,
  2,
  3
]
```

Note that whatever jq code you write is going to be run once per json item in the input. So if you want the output to have a single json array across all of the input items, you are going to need `--slurp` or similar. Some examples for my dummy code:

```
$ echo 1 2 3 | jq --slurp '[.[] | .+1 | range(1;.)]'
[
  1,
  1,
  2,
  1,
  2,
  3
]

$ echo 1 2 3 | jq -n '[inputs | .+1 | range(1;.)]'
[
  1,
  1,
  2,
  1,
  2,
  3
]

$ echo 1 2 3 | jq -n 'reduce inputs as $i ([]; . + [range(1; $i+1)])'
[
  1,
  1,
  2,
  1,
  2,
  3
]
```
