### ISSUE TITLE
jq needs a library!

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#98]
A C library for jq would. be. awesome.  Ditto Python, node/JS, ..., but a C library should be easier given that jq is already written in C.

This is really like XSLT/XPath for JSON, and simplified a great deal.  I can do things with jq in a few characters that require multiple lines of Python/whatever, so I'm starting to resort to popen().  A library would be easier to use :)

**Comment by progrium** [comment]
+1 +1 +1 Especially @icholy on the Go bindings.

**Comment by netsgnut** [comment]
@dtolnay, should this be reopened or a new issue to be created instead? Thanks!

**Comment by dtolnay** [comment]
A library exists already. For example [jq.py](https://github.com/mwilliamson/jq.py) is built on it. The documentation is lacking but see [C API: libjq](https://github.com/stedolan/jq/wiki/C-API:-libjq) for what is exported and public.

**Comment by netsgnut** [comment]
Oops my bad, didn't realize we now have a binding library now. Thanks for the pointer.

**Comment by nicowilliams** [comment]
Until we have good docs I wouldn't say that the API is stable, though we're unlikely to make backwards-incompatible changes, really.

**Comment by nicowilliams** [comment]
Also, if someone sends a PR with docs for the API...
