### ISSUE TITLE
Support Avro file format

### ISSUE THREAD

**Issue by pm-vasu-cherlopalle** [stedolan/jq#980]
Any plans on supporting AVRO file formats

**Comment by dtolnay** [comment]
Not in jq. The avro-tools jar includes "fromjson" and "tojson" conversion commands, so you could convert your avro files to json for use with jq.

**Comment by nicowilliams** [comment]
Every once in a while I think that a notion of ancillary user-defined type information in jv values would be handy.  It'd be just a tag that gets propagated in copies.  I can even imagine function dispatch based on input (`.`) value type tag.  Anyways.  As for AVRO and similar, in principle nothing stops one from jq-coding parsers and encoders.

**Comment by nicowilliams** [comment]
(Any notion of user-defined types would have to be a major release, and would require lots of thought.  I'm not sure it could be made to work.  When using JSON we'd lose the type tags, so type inference would be necessary (perhaps as the responsibility of the jq program) -- that's just one example of a problem that would arise.  But it sure is appealing.)
