### ISSUE TITLE
Example blocks in online manual don't expand anymore

### ISSUE THREAD

**Issue by jaybocc2** [stedolan/jq#988]
Most `> Example` blocks are not expanding.  I have to manually go into the CSS and remove "collapse" from the class tag to view the example.

**Comment by eliasdorneles** [comment]
I can reproduce both in development version and stable versions.
Also, it fails both in Chrome in FF.

**Comment by dtolnay** [comment]
Thanks for reporting. This was caused by my fix for #986 last night. The padding of the next section was covering up the link to expand the examples. I have reverted that change and I will try to come up with a different way to fix #986.
