### ISSUE TITLE
from_entries does not support "name"

### ISSUE THREAD

**Issue by dhobbs** [stedolan/jq#990]
I had an array containing:

```
[{"name": "foo", "value":1}]
```

According to the docs, from_entries accepts key, Key, Name as valid keys. It's a little surprising that it supports 'key' or 'Key' but not 'name' or 'Name'. The docs are accurate but I spent about 10 minutes wondering why my filter didn't work as I saw the 2 cases for Key and assumed Name would work the same way :)

Any chance of making it consistent?

**Comment by dtolnay** [comment]
Sounds reasonable, thanks for reporting this.
