### ISSUE TITLE
Does anyone use setup.sh?

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#993]
Does it need to be in the repo with a scary "RUN ME" comment at the top? It seems like `.gitignore` does a good enough job keeping generated files out of git. I have never needed setup.sh, but I don't want to remove it without warning if other people depend on it.

**Comment by else** [comment]
I don't use it for the Debian packaging.

**Comment by nicowilliams** [comment]
I don't use it.  If you and I don't, if @else doesn't, if the `brew` formula doesn't, well, then I think we should remove it, yeah.
