### ISSUE TITLE
jq 1.5 FTBFS on MIPS

### ISSUE THREAD

**Issue by else** [stedolan/jq#994]
The 1.5 version [fails to build from scratch](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802208) on MIPS*. The bug report contains the [test-suite.log](https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=3;att=1;bug=802208;filename=test-suite.log):

<pre>
========================================
   jq 1.5-1-a5b5cbe: ./test-suite.log
========================================

# TOTAL: 4
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/mantest
===================

Segmentation fault
rake aborted!
Errno::EPIPE: Broken pipe @ io_write - <STDOUT>
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:50:in `write'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:50:in `puts'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:50:in `puts'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:50:in `block (5 levels) in <top (required)>'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:50:in `each'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:50:in `block (4 levels) in <top (required)>'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:47:in `each'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:47:in `block (3 levels) in <top (required)>'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:46:in `each'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:46:in `block (2 levels) in <top (required)>'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:45:in `each'
/home/jwilk/jq-1.5+dfsg/docs/Rakefile:45:in `block in <top (required)>'
Tasks: TOP => mantests
(See full trace by running task with --trace)
FAIL tests/mantest (exit status: 139)

FAIL: tests/jqtest
==================

Segmentation fault
FAIL tests/jqtest (exit status: 139)

FAIL: tests/onigtest
====================

Segmentation fault
FAIL tests/onigtest (exit status: 139)

FAIL: tests/shtest
==================

jq: jv.c:435: jvp_string_ptr: Assertion `jv_get_kind(a) == JV_KIND_STRING' failed.
Aborted
FAIL tests/shtest (exit status: 134)
</pre>

Version 1.4 worked [just fine](https://buildd.debian.org/status/package.php?p=jq&suite=jessie). Any ideas?

**Comment by dtolnay** [comment]
It seems like the situation has gotten worse since #593. I will set up a VM and try to debug both.

**Comment by else** [comment]
Thanks! The original author of the bug has provided a stacktrace; the problem seems to disappear with optimizations off.

**Comment by dtolnay** [comment]
For future reference, I have set up QEMU with Debian jessie using the steps here: http://www.stderr.nl/Blog/Software/Debian/SqueezeOnMips.html

```
qemu-img create -f qcow2 debian_mips.qcow2 2G
wget http://ftp.debian.org/debian/dists/jessie/main/installer-mips/current/images/malta/netboot/initrd.gz
wget http://ftp.debian.org/debian/dists/jessie/main/installer-mips/current/images/malta/netboot/vmlinux-3.16.0-4-4kc-malta
qemu-system-mips -hda debian_mips.qcow2 -kernel vmlinux-3.16.0-4-4kc-malta -initrd initrd.gz -append "root=/dev/ram console=ttyS0" -nographic
```

For some reason the installer did not create a user account even though I put in user/pass so I had to boot with `systemd.unit=rescue` to create one.

`dpkg` was in a weird partially installed state and missing `start-stop-daemon`:

```
wget http://ftp.debian.org/debian/pool/main/d/dpkg/dpkg_1.17.25_mips.deb
mkdir dpkg
dpkg-deb -R dpkg_1.17.25_mips.deb dpkg
cp dpkg/sbin/start-stop-daemon /sbin
```

**Comment by dtolnay** [comment]
I was not able to reproduce this in QEMU on Debian jessie. After installing `build-essential`, `autoconf`, `libtool`, `flex`, `bison` and `libonig-dev`, both `make` and `make check` work fine on [current master](https://github.com/stedolan/jq/tree/b80d58e16743bd8b3a750c6a27e8003f33a1e46e). I also did not reproduce #593.

```
$ file jq
jq: ELF 32-bit MSB executable, MIPS, MIPS-II version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 2.6.32, BuildID[sha1]=afa0080ed5d0e5600f44e874b5f3b425492cf4a5, not stripped
$ uname -a
Linux debian-mips 3.16.0-4-4kc-malta #1 Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) mips GNU/Linux
$ dpkg-architecture
DEB_BUILD_ARCH=mips
DEB_BUILD_ARCH_BITS=32
DEB_BUILD_ARCH_CPU=mips
DEB_BUILD_ARCH_ENDIAN=big
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=mips
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=mips-linux-gnu
DEB_BUILD_MULTIARCH=mips-linux-gnu
DEB_HOST_ARCH=mips
DEB_HOST_ARCH_BITS=32
DEB_HOST_ARCH_CPU=mips
DEB_HOST_ARCH_ENDIAN=big
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=mips
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=mips-linux-gnu
DEB_HOST_MULTIARCH=mips-linux-gnu
DEB_TARGET_ARCH=mips
DEB_TARGET_ARCH_BITS=32
DEB_TARGET_ARCH_CPU=mips
DEB_TARGET_ARCH_ENDIAN=big
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=mips
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=mips-linux-gnu
DEB_TARGET_MULTIARCH=mips-linux-gnu
```

I guess the next things to try are gcc 5.2.1, jq 1.5 release tag (although I can't think of any important changes between 1.5 and master), and 64-bit.

**Comment by dtolnay** [comment]
I will give this another shot this weekend.

**Comment by else** [comment]
Any update? =)

**Comment by jwilk** [comment]
This turned out to be a [GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68273).

**Comment by nicowilliams** [comment]
Thank you @jwilk for linking the GCC bug.
