### ISSUE TITLE
Object key with period can't be referenced 

### ISSUE THREAD

**Issue by meshelton** [stedolan/jq#997]
````bash
echo '{"test.test" : "Hello!"}' | jq ."test.test" 
````
Should return "Hello!" but returns null instead.

**Comment by thedward** [comment]
This is a shell quoting issue, try `jq '."test.test"'`

**Comment by meshelton** [comment]
Don't think so:

````bash
echo '{"test.test" : "Hello!"}' | jq '."test.test"'
error: syntax error, unexpected QQSTRING_START, expecting $end
."test.test"
 ^
1 compile error
````

**Comment by wtlangford** [comment]
What version of jq are you running? `jq --version`

**Comment by dtolnay** [comment]
Version 1.3 or earlier you need to use `jq '.["test.test"]'`.

**Comment by meshelton** [comment]
Version 1.3, that was the problem. Thanks for the replies!
