### ISSUE TITLE
JQ Taking too much of cpu

### ISSUE THREAD

**Issue by JSONPRE** [stedolan/jq#998]
Hi,
We are using json with almost 240 items and jq is used as json parser. when the script runs it takes almost 20% of cpu. is there any way to reduce the cpu.

sample json:
```
[
    {
        "Category": "abcd",
        "Details": [                                                                                                                       
            {
                "Name": "mnop"
            },
            {
                "Name": "ijkl"
            },
            {
                "Name": "iopa"
            }
        ]
    },
    {
        "Category": "abced",
        "Details": [
            {
                "Name": "sdgfs",
                "Critical": "2",
                "Warning": "1",
                "Unit": "ms",
                "AliasName": "vsdsv" 
            },
            {
                "Name": "xvvcx",
                "Critical": "2",
                "Warning": "1",
                "Unit": "ms",
                "AliasName": "jhhj" 
            }
        ]
    }
]
```

sample shell script to read json:
```
#CONFIG_FILE contains the json. 
fileout1=`cat $CONFIG_FILE`
tmp=`echo $fileout1| jq ".[$i].Category"`
temp=`echo $fileout| jq ".Details[$j].Critical"`
CriticalThreshold=$(echo "$temp"| cut -d\" -f 2)
```

**Comment by dtolnay** [comment]
This part:

    echo $fileout1 | jq ...

passes each word in CONFIG_FILE as an individual argument to echo, which may be slow depending on your shell's implementation of echo.

I made a 100 MB version of your input to compare the following alternatives:

````
$ time echo $fileout1 | jq '.[0].Category'
"abced"
real  0m11.590s
user  0m12.164s
sys   0m0.605s

$ time echo "$fileout1" | jq '.[0].Category'
"abced"
real  0m7.043s
user  0m6.662s
sys   0m0.483s

$ time jq '.[0].Category' $CONFIG_FILE
"abced"
real  0m3.506s
user  0m3.335s
sys   0m0.172s

$ time jq '.[0].Category' <$CONFIG_FILE
"abced"
real  0m3.509s
user  0m3.297s
sys   0m0.216s
```

And here is a diagram of the memory usage for the 4 alternatives in the same order:
![system monitor_003](https://cloud.githubusercontent.com/assets/1940490/10709419/8a83142c-79e2-11e5-9a89-136b98a212f2.png)
(The largest peak is ~1.3 GB.)

So at least in my shell, using a single argument to echo (`"$fileout1"`) makes a big difference. But using jq to read straight from the file, or using shell redirection, is way better than either.

Also, consider using the `-r` flag for jq which is raw output mode. This prints the output without quotes around strings so you don't have to use `cut` to get rid of quotes.

**Comment by JSONPRE** [comment]
Hi dtolnay,
Thanks for comments, 
the actual script contains 2 loops please refer below , so we use time echo "$fileout1" | jq '.[0].Category' performance impact will happen right?
script:
====
fileout1=`cat $CONFIG_FILE`
while [ $i -lt $length ]
do

metlength=$(jq ".[$i].Details | length" $CONFIG_FILE)

j=0

tmp=`echo $fileout1| jq ".[$i].Category"`
CategoryName=$(echo "$tmp"| cut -d\" -f 2)
TEMP_CATEGORY_SUMMARY="$CategoryName Normal"
while [ $j -lt $metlength ]
do
fileout=`echo $fileout1|jq ".[$i]"`
temp=`echo $fileout| jq ".Details[$j].Name"`
MetricName=$(echo "$temp"| cut -d\" -f 2)
temp=`echo $fileout| jq ".Details[$j].Critical"`
CriticalThreshold=$(echo "$temp"| cut -d\" -f 2)
temp=`echo $fileout| jq ".Details[$j].Warning"`
WarningThreshold=$(echo "$temp"| cut -d\" -f 2)
temp=`echo $fileout| jq ".Details[$j].Unit"`
Unit=$(echo "$temp"| cut -d\" -f 2)
temp=`echo $fileout| jq ".Details[$j].AliasName"`
AliasName=$(echo "$temp"| cut -d\" -f 2)
j=`expr $j + 1`
done
i=`expr $i + 1`
done

**Comment by nicowilliams** [comment]
I would rewrite the script in ksh or bash to get more builtin usage, and I'd rewrite it to use one jq invocation to do more.  Reading a config file's contents into a shell variable and then echoing it to a filter like jq is a rather odd thing to do.

How about this:

    function doit {
        # Do something with $Category, $Name, etcetera.
        echo PROCESSING category $Category name $Name ...
    }
    
    # Output Category=... Name=... ... doit;, then eval it 
    eval $(jq -r '.[]|
      .Category as $cat |
      .Details[] |
      [keys[] as $key | " \($key)" + @sh "=\(.[$key])"] | join("") |
      @sh "Category=\($cat)" + . + " doit;"
    ' "$CONFIG_FILE")

**Comment by nicowilliams** [comment]
This approach has a single execution of jq, no extraneous `echo`s, and so on.  It should be very fast.

**Comment by JSONPRE** [comment]
@nicowilliams  Thanks for your comments . I kindly request to explain your script.? 
eval $(jq -r '.[]|
  .Category as $cat |
  .Details[] |
  [keys[] as $key | " \($key)" + @sh "=\(.[$key])"] | join("") |
  @sh "Category=\($cat)" + . + " doit;"
' "$CONFIG_FILE")

**Comment by nicowilliams** [comment]
@JSONPRE  My script uses jq's `@sh "\(EXP)"` syntax to escape interpolated strings so that they are safe to use in shell with `eval`, and it constructs command-lines of the form `varname=value ... doit`, is shell syntax for calling doit() with those variables in the environment.  So, you define a `doit()` function in shell (or as an external command) and then it will get called with various environment variables set, such as Category, Name, etcetera: one for each key in the Details object for each Category.

**Comment by nicowilliams** [comment]
In particular, this is clever because it uses one jq process and one shell process to do everything, which means you get to minimize the fork/exec overhead and so you get to get better timing information.

**Comment by fschroder** [comment]
+1 to your suggestion of reading straight from the file instead of through echo. I've seen huge time differences (~35s vs <1s) when processing a 250k file.
